### ISSUE TITLE
[4.0.0-beta] TaskFactory not able to spawn new threads 

### ISSUE THREAD

**Issue by GeertvanHorrik** [Particular/NServiceBus#1102]
I am using NServiceBus 4 beta (unstable2911). We are using a library that spawns
a background listener thread using the task factory. It failed however since we
moved the logic of that part of our IT system to NServiceBus. After searching
and stepping through the code it seems that TaskFactory is unable to start the
new task.

We can solve this issue by using the ThreadPool instead, for more information,
see http://sshnet.codeplex.com/workitem/1552

However, if the result of using NServiceBus is that it is "forbidden" to use
TaskFactory, then I think there is a big issue to solve.

Also see http://tech.groups.yahoo.com/group/nservicebus/message/18504

**Comment by Thorium** [comment]
Oh no, it seems that what happens while ,Wait() is not in the same transaction (managed by NServiceBus) which is a problem. See the issue #2674
