### ISSUE TITLE
clear saga timeouts when timeout manager is disabled

### ISSUE THREAD

**Issue by rosieks** [Particular/NServiceBus#1161]
Hi
I use NSB 3.2.7 and I've noticed that when I disable timeout manager `DisableTimeoutManager` then nsb still send message to timeouts queue after saga complete (Clear saga timeouts). As a result I end up with full queue because nothing read from timeout queue. I think that in NSB 4.0 this problem still appear.

**Comment by andreasohlund** [comment]
@DavidBoike is this the issue you just fixed on develop?

**Comment by DavidBoike** [comment]
I believe so. The clear timeouts behavior is made into a no-op when TimeoutManager is disabled, and any extraneous calls to a deferral then result in a thrown exception before you get to the "queue not available" stage.

**Comment by danielmarbach** [comment]
This is fixed in Version 6. Closing
