### ISSUE TITLE
DataBus should support Stream types

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#1199]
It would be nice if you could just define a property of type Stream

	public class MyUberFatCommand
	{
		public Stream Payload { get; set; }
	}

That would also make it *much* easier and lightweight as currently you must read the payload in memory with has a pretty big performance impact when the payload is large.

Second, defining the databus property naming convention is then also pretty simple!

	.DefiningDataBusPropertiesAs(pi => typeof(Stream)==pi.PropertyType)

Does that make any sense?

**Comment by danielmarbach** [comment]
We have [a sample](http://docs.particular.net/samples/pipeline/stream-properties/) for this which is better suited than extending the data bus. I'm closing this.
