### ISSUE TITLE
Change the transportmessage to use a stream instead of a byte[] for the body

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1272]
This will make it easier to control updates to the body and will save memory since we can stream the payload straight into the serializers without copying it into memory

**Comment by johnsimons** [comment]
@andreasohlund this one is done as part of v6 right ?

**Comment by andreasohlund** [comment]
Sort of, the transport provides a stream but we read it into a byte[] right away since its tricky to expose streams to end users and mutators ( see #2974 ).

**Comment by danielmarbach** [comment]
Also related to https://github.com/Particular/NServiceBus/issues/3325

**Comment by danielmarbach** [comment]
I'd say candidate vor vNext

**Comment by andreasohlund** [comment]
Did a spike a few months back on how it would affect mutators and it seems to work given that we create a decorator that preserves the body so we can send the untampered body to SLR/Error/Audit.

This was the decorator

```
class PreserveBodyDecorator : Stream
    {
        readonly Stream tempStream;

        public PreserveBodyDecorator(Stream tempStream)
        {
            this.tempStream = tempStream;
        }

        public override void Flush()
        {
            tempStream.Flush();
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            return tempStream.Seek(offset, origin);
        }

        public override void SetLength(long value)
        {
            tempStream.SetLength(value);
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            throw new NotImplementedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new NotImplementedException();
        }

        public override bool CanRead => true;

        public override bool CanSeek => tempStream.CanSeek;
        public override bool CanWrite => true;
        public override long Length => tempStream.Length;
        public override long Position
        {
            get { return tempStream.Position; }
            set { tempStream.Position = value; }
        }
    }

```

**Comment by danielmarbach** [comment]
See also https://github.com/Particular/NServiceBus/issues/3325

**Comment by danielmarbach** [comment]
@Scooletz can yo summarize your thoughts from https://github.com/Particular/NServiceBus/issues/3325 here and then close the issue 3325

**Comment by Scooletz** [comment]
@danielmarbach Ofc. See below:

- the area of the change makes it non trivial
- it will change many low-level constructs like `OutgoingPhysicalMessageContext.Body'
- it should not be considered as Core v6 target as it may introduce a lot of friction
- I'd still make it a target for v7

**Comment by danielmarbach** [comment]
We made several attempts to try streaming and are now even moving away again on the incoming message see https://github.com/Particular/NServiceBus/pull/3956 Closing
