### ISSUE TITLE
Default queue name for brokers transports is problematic in development

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1383]
The default queue name for broker transports when using the `As_AClient` role or self hosting is EndpointName@MACHINENAME.

This unfortunately has the disadvantage of not working in a development team environment as the mappings would be different in each developer machine :disappointed: 

//cc @andreasohlund

**Comment by andreasohlund** [comment]
@SzymonPobiega how does the routing changes in v6 effect this one?

**Comment by SzymonPobiega** [comment]
@johnsimons @andreasohlund that will depend on the transport impl. There is the new `BindToLocalEndpoint` in the transport definition that is responsible for setting the properties specific to local machine.

In MSMQ that would be adding `Machine` property. In SQL and RabbitMQ transports that method will probably be `NOOP` (returning the same thing it gets) so, no matter what profile is selected, the queue name will always be equal to endpoint name (+ scale out discriminator and transport-specific overrides)

**Comment by andreasohlund** [comment]
So close or keep this one?

**Comment by SzymonPobiega** [comment]
Let's confirm first if everything works as I think it would be? (what I wrote is a theory). @tmasternak can you verify what are the queue names for SQL transport in a self-hosted endpoint?

**Comment by danielmarbach** [comment]
@tmasternak [can you look](https://github.com/Particular/NServiceBus/issues/1383#issuecomment-166398629) at and close this one with OK.

**Comment by tmasternak** [comment]
I confirm. In self-hosted environment the queue name does not include machine name for sql.
