### ISSUE TITLE
Allow endpoints to use multiple transports

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1469]
To better support users with a mixed environment we should support multiple transports for each endpoint

* Pub/Sub should be seamless without sharing substorages

* Each endpoint has a default transport

* Endpoint mappings/routing should support specifying transport type

* ServiceControl needs to support multi transport to allow for a "uber central error q" if needed

**Comment by danielmarbach** [comment]
In V5 we support multiple endpoints in the same "host". Closing this one.
