### ISSUE TITLE
Turn off checks for messaging best practices on case by case basis

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus#1471]
I have a publisher that does Bus.Publish(ISomeEvent). I'd also like to send this information to other sites over the gateway. However, Bus.SendToSites fails because of the message [best practices check](http://support.nservicebus.com/customer/portal/articles/856271-introducing-ievent-and-icommand).

In v4.0, when using the unobtrusive mode, I have to either 
- translate the event to a command, send it over the gateway and translate back to event at the other end
- register the event as a command in my unobtrusive conventions

See [here](http://tech.groups.yahoo.com/group/nservicebus/message/20340) for more details

**Comment by andreasohlund** [comment]
Fixed in v6 http://docs.particular.net/nservicebus/messaging/best-practice-enforcement
