### ISSUE TITLE
Creating queues automatically while in development, good or bad?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1489]
### Current situation
The F5 problem free experience that we currently give our users where we run the installers(queues get automatically created, databases get created, ...) by default if the user is running inside VS (debugger is attached) is quite nice. **But it also has its own disadvantages.**

### Disadvantage
When it comes time to deploy in a real environment, users don't actually know the procedure on how to do it!
Yes you need to run the installers! If running with our host you need to call -install!

So I wonder if in this case "the cure is worse than the disease", thoughts?

**Comment by danielmarbach** [comment]
The [development transport](#2950 ) would solve by creating queues for development only, that will free up the production transports to never automatically create queues. Closing as Duplicate.
