### ISSUE TITLE
Refactor satellites to abstract class

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1497]
### Proposal
- [ ] Create an abstract class called `Satellite` that will wrap `bool Handle(TransportMessage message);` in a child container
- [ ] Update all satellites to use new abstract class
- [ ] New abstract class will implement both `ISatellite` and `IAdvancedSatellite` and make the definitions overridable

I would also mark `ISatellite` and `IAdvancedSatellite` as obsolete in favor of the new abstract class.
We could also get rid of `SatelliteContext` and push all that logic into the abstract `Satellite` class.

**Comment by danielmarbach** [comment]
This is no longer necessary since we revamped the approach to satellites in V6
