### ISSUE TITLE
Add support for unobtrusive IHandleMessages<IMessage>

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#151]
We no longer require IMessage to be implemented, Perhaps a IHandleMessages<object> or IHandleMessages<dynamic> will do?

**Comment by ivanpaulovich** [comment]
Hey @andreasohlund! 

Do you mean that we could remove the `IHandleMessages` from the Handlers?
It didn't work for me.

**Comment by andreasohlund** [comment]
No, IHandleMessages is still needed but the T doesn’t have to be IMessage.

Can you elaborate on why having the IHandleMessages is problematic for you?

**Comment by ivanpaulovich** [comment]
Hi @andreasohlund,

My application has Events and Event Handlers in the Domain Layer and I wouldn't like to add NServiceBus dependency there. I was considering that as you already have Conventions for messages that you could have Conventions for Handlers as well.

I would accept if I just need the signature `async Task Handle(T message)` on all event handlers.

**Comment by andreasohlund** [comment]
Seems like this discussion was concluded in https://github.com/Particular/NServiceBus/issues/5459
