### ISSUE TITLE
Fix the Scaleout Sample

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#1545]
**Problem:**

The sample for the ScaleOut has the following issues:

- It leads users in thinking that they can run distributor + worker on the same box!!! (which is an anti-pattern)
- It gets confusing (rightfully so) when the messages occasionally get lost (while they hide in the Orders.Handler.Guid queue)

**Suggested fix:**

- Modify the scaleout sample to only contain the master node.
- Document how to scale out by either copying the bin folder to another machine or copy to the local machine and tweek the endpoint name + distributor address to simulate a scale out scenario
- Also point the users to the ScaleOut HOL
- Remove the code in the core that auto generates unique input queue names
- Create a acceptance test that runs a master node (valid for msmq only)

**Comment by andreasohlund** [comment]
@indualagarsamy is this done?

**Comment by SimonCropp** [comment]
if this is still an issue raise it in the docs repo
