### ISSUE TITLE
Local backoff for outbox

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#1573]
As an extension to the planned outbox feature (which supports non-DTC), it would be beneficial for some remote storages to have a backoff outbox as well in case it would not be reachable from the machine, this should be an opt in feature and we need to communicate explicitly though that we're in best effort mode at that time, f.e. the machine gets recycled in azure

**Comment by andreasohlund** [comment]
@SzymonPobiega is this the sample you just wrote on using the outbox to get "store and forward" ?

**Comment by SzymonPobiega** [comment]
@yvesgoeleven is it something like this http://docs.particular.net/samples/outbox/store-and-forward/ ?

**Comment by yvesgoeleven** [comment]
Yes, but the store and forward should only be used in case the remote queues are unreachable. Reason is that cloudservices disk should also not be considered durable, so if you would put something on it (in a local db or through whatever means) it's almost guaranteed to produce message loss. So it should only be used in case of networking issues, but otherwise not.

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers @timbussmann and I vote to close this. Implementing our own store and forward just in case remote queues are unreachable including the challenges associated with it doesn't sound like something we want to achieve in the near future.
