### ISSUE TITLE
Subscribe to same event type from multiple publishers 

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1583]
#### Here is the scenario:

Two publishers publish different event types, eg MyEvent1 and MyEvent2
Both of these events share the same base interface/abstract class, eg:

```c#
public interface MyEvent1 : MyCommonInterface {}
public interface MyEvent2 : MyCommonInterface {}
```

A subscriber want to subscribe to both of those events using the base interface, eg:
```xml
<MessageEndpointMappings>
      <add Assembly="boo" Type="MyCommonInterface" Endpoint="MyEndpointA" />
      <add Assembly="boo" Type="MyCommonInterface" Endpoint="MyEndpointB" />
</MessageEndpointMappings>
```
The above does not work and it fails saying ""MyCommonInterface" is already subscribed."

Should this be supported?
/cc @andreasohlund @udidahan

**Comment by danielmarbach** [comment]
Ping @timbussmann @DavidBoike @bording this might be relevant for your routing discussion.

**Comment by timbussmann** [comment]
the v6 code first API provides an API which supports the initial scenario as described by @DavidBoike here: https://github.com/Particular/NServiceBus/issues/3911#issuecomment-235378695

closing this.
