### ISSUE TITLE
Stop sending .net specific type info in the EnclosedMessageTypes header

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1610]
We're leaking platform info and it should be enough to send the Fullname eg Acme.OrderPlaced (we actually already support this on the receiving side) and the message version. 

This will also solve a concrete issue we have in ServiceControl where the EndpointPlugin merges the messages dll so it's sent as:

```
EndpointPlugin.Messages.Heartbeat, EndpointPlugin"
```

But the backend doesn't ilmerge so the heartbeat message is in a assembly called EndpointPlugin.Messages.

This causes the messages to fail unnecessarily.
# Testing
- Make sure that performance is not effected

**Comment by danielmarbach** [comment]
@andreasohlund we no longer merge the heartbeat messages but we share the contract and manipulate the $type. Can we close this?

**Comment by andreasohlund** [comment]
I just used the plugin as an example, the core is still sending the assembly qualified name: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serialization/SerializeMessageConnector.cs#L59

**Comment by danielmarbach** [comment]
Discussed with @timbussmann and we are not clear about the actual benefits of this change. It is a behavior breaking change. The implications of this would be that we might be able to use "duck typing" on the receiving side (but this might be highly dependent on the serializer used). The downsides could be that we are no longer able to dynamically load assemblies into the AppDomain like we do with unobtrusive messages. Should we support both? Until we cannot express a real value of this I'm leaning towards closing.

**Comment by andreasohlund** [comment]
>Should we support both? Until we cannot express a real value of this I'm leaning towards closing.

Agreed, we can already handle cases where only the fullname is present so there isn't much value to this.
