### ISSUE TITLE
Refactor serializers to not depend on message mapper

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1620]
we have the knowledge of the types outside the serializers. we should pass that in at serialization time so the serializers dont need to re-query the message mapper

**Comment by andreasohlund** [comment]
@SimonCropp didn't we have a recent issue for this one as well?

**Comment by danielmarbach** [comment]
@SzymonPobiega gave this another try recently. Decoupling from the mapper would be a good thing but arguably only a small benefit. But since we are now updating the serializers anyway should we give it another GO?

**Comment by SzymonPobiega** [comment]
@danielmarbach I am :+1: for trying once again, maybe with a task force and some pair programming we would be able to kill it.

**Comment by SimonCropp** [comment]
How about some mob programming? I know andreas has some history that would be important

**Comment by danielmarbach** [comment]
I like mob programming. The question is: Should we do it in v6 timeframe,
if yes, why?

**Comment by timbussmann** [comment]
@danielmarbach and me decided to close this one. Effort seems to be too high for the little value. Refactorings can still be made within task-forces which touch that code, this doesn't need to be addressed as an independent issue.
