### ISSUE TITLE
Serializers should not be configuring MessageMapper

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1625]
Currently the `MessageMapper` is configured inside the Serializers

 * https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/XML/Config/XmlSerialization.cs
 * https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/Json/Config/BsonSerialization.cs
 * https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/Json/Config/JsonSerialization.cs

However it is not just "a serialization concern". For example `UnicastBus` relies on it https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/UnicastBus.cs#L768

So is someone wants to create their own serializer they would need to know to also configure `MessageMapper`. This is not a great scenario.
 
`MessageMapper` config should be treated as seperate concern.

**Comment by danielmarbach** [comment]
@SzymonPobiega can you write in your investigation outcome summary here?

**Comment by danielmarbach** [comment]
Ping @SzymonPobiega

**Comment by SzymonPobiega** [comment]
In current V6 we have a compromise solution where `IMessageMapper` is passed to a serializer factory method. We should get rid of it entirely in next release.

**Comment by timbussmann** [comment]
MessageMapper is now initialized from the shared `SerializationFeature`.
