### ISSUE TITLE
Remove use of [ThreadStatic] from XmlMessageSerializer 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1626]
So `XmlMessageSerializer` makes heavy use of `[ThreadStatic ]`
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/XML/XmlMessageSerializer.cs#L1382

This is not great for several reasons

* Unintended side effects: Threads can be re-threads or multiple actions can happen on the same thread. So it can be easy for bugs to occur as code evolves.
* Performance implications: [The cost of ThreadStatic attribute](http://tips.x-tensive.com/2008/10/cost-of-threadstatic-attribute.html)

`XmlMessageSerializer` should be changed to use the factory pattern  and create lightweight instances of "serializers" or "deserializers". Then these instances can have their own instance variables.

This would also have a side effect of splitting `XmlMessageSerializer` into 3, more manageable, parts.

**Comment by SimonCropp** [comment]
@andreasohlund so is the plan in V6 to split XmlMessageSerializer out into its own repo? if so this is not worth fixing

**Comment by johnsimons** [comment]
I disagree @SimonCropp.
Regardless on which repo we address this, I think refactoring `XmlMessageSerializer` as the issue describes is a big win for code maintenance.

**Comment by andreasohlund** [comment]
What benefits would splitting the xml serializer out give us? 

Are you proposing that we ship wo serializer "in the box" and force users to always select one?

**Comment by SimonCropp** [comment]
@andreasohlund so we have a requirement to "be as easy to get started OOTB". So as part of that I think we need at least one serializer in the core. I dont think we need two.

**Comment by johnsimons** [comment]
Totally agree @SimonCropp, so which one are u proposing to leave in the core ?

**Comment by SimonCropp** [comment]
json was my thinking. although there is the additional complexity of we would be changing the default serializer. so obviously would be done in a major release with associated doco.

**Comment by johnsimons** [comment]
I think it would be safer and easier for our end users to just leave the xml in the core and move everything else out, that said, the Binary serializer is really not hurting us at all so I would leave that as well.

The json is a bit more interesting because Azure uses it as its default, so Azure users would have to reference a new package, but hopefully those users are not large numbers.

**Comment by andreasohlund** [comment]
I'd say json is definitely the way to go long term since its definitely the number one format these days, at least compared to XML. Using json would very likely make feature like https://github.com/Particular/Requirements/issues/151 since that payload obviously would be json

**Comment by SimonCropp** [comment]
already done
