### ISSUE TITLE
Allow configurable message retry upon failure to support broker failover

### ISSUE THREAD

**Issue by freemansoft** [Particular/NServiceBus#1682]
NServiceBus 4.0 does not appear to have native retry support for non-MSMQ HA broker failover.  You can get an exception when you send a message to a broker node that has gone down. Client code can catch that exception and retry.  The message will go through if you try and send again because the cluster will fail over to the new master messaging node and NServiceBus creates a new connection for messages following failover.  I believe this works because some of the client code,  Rabbit code,in particular, has settings for MaxRetries and RetryDelay that are used in the TryToConnect() to re-establish the connection.

The dev team has said that there is code to handle re-connection in endpoints when the Bus.Send() or Bus.Publish happens inside of a  message handler.  There are cases where messages are sent from code that is not a handler. In these cases there is no retry behavior. Ex: applications that produce change events as part of their normal processing. These applications are not NServiceBus endpoints and do not have  NServiceBus handlers.  

Every Bus.Send() and Bus.Reply() call needs to be wrap-able with retry logic. That currently has to happen in custom code. It might be possible to create a wrapper object that is configured in the DI container and injected into application code. That won't be enough because "Bus"/"IBus" is injected into a bazillion NServiceBus classes so there isn't any obvious way to wrap the Bus class with a proxy, wrapper or aspect to add the retry behavior. Someone could add a helper hook to the dependency configuration for a wrapper/proxy.  That would let folks pick which type of retry they want including the number of retries and the roll off times and algorithms.  Supporting different retry behavior for different message types seems useful but more complicated.

How do people create robust apps that handle cluster failover?

Original question at https://groups.google.com/forum/#!topic/nservicebus/iOnPVXuuoKs

**Comment by andreasohlund** [comment]
Moved to https://github.com/Particular/NServiceBus.RabbitMQ/issues/17
