### ISSUE TITLE
How to create queue when self hosting?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1703]
When NServiceBus is self hosted, the "installation time" is not well defined, specifically how does a user create the queues at install time?

Currently most self hostings out there are calling:
```c#
Configure.Instance.ForInstallationOn<Windows>().Install();
``` 
And usually this is called from:
```c#
...
.CreateBus()
.Start(() => Configure.Instance.ForInstallationOn<Windows>().Install());
```

Even though the above works and this is what we have been telling people to do, it is not the correct way to do it because the code above will run every time the self hosted is restarted and if the user follows best security practices the account running the self hosted should be as restrictive as possible and therefore not have rights to create queues.

**So the question is, how do we provide a nice install time for self hosting?**

**Comment by danielmarbach** [comment]
On the fence about this. The new way of declaring it is

```
var endpointConfiguration = new EndpointConfiguration();
endpointConfiguration.EnableInstallers();
```

currently when you have that flag we will run the installers. A workaround for a user is trivial for self hosting. The code could look like that:

```
static void Main(string[] args) {
   var endpointConfiguration = new EndpointConfiguration();
   if(args[0] == "install")
     endpointConfiguration.EnableInstallers();
   }
}
```

we could also provide a sample for that (the sample could also use a reg key or anything like that). But from an API perspective I think when a user tells us to enable the installers we should run them and not do any underlying magic. Raised a doc issue here https://github.com/Particular/docs.particular.net/issues/1889
