### ISSUE TITLE
Decide what to do about `HandleCurrentMessageLater`

### ISSUE THREAD

**Issue by mookid8000** [Particular/NServiceBus#1705]
The current behavior in 4.1 (and probably also in the upcoming 4.2) is that `Bus.HandleCurrentMessageLater()` will send the transport message currently being handled to the back of the input queue - and nothing else! 

Three fifths of the core team expected that the message handler pipeline would stop after having executed the handler in question, but that was not the case.

IOW, when the doco states that "the message will be moved to the back of the input queue", I would argue that the word "moved" ought to be changed into "copied".

In 4.3 we should probably decide whether we want to a) change the behavior so that any handlers following the current handler will be aborted, or b) change the doco and/or change the API to be more intuitive.

I'm leaning towards (b) and renaming it to `ForwardCurrentMessageToSelf`, because then the behavior we expected can easily be achieved by going 

    Bus.ForwardCurrentMessageToSelf();
    Bus.DoNotContinueDispatchingCurrentMessageToHandlers();

`ForwardCurrentMessageToSelf` would be a better name IMO because it matches the already existing `ForwardCurrentMessageTo(destination)`

**Comment by danielmarbach** [comment]
@andreasohlund @johnsimons We haven't made a decision based on this for handler context. 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerContext.cs#L40

Should we close this or rename the method? (I doubt it is worth it)

**Comment by johnsimons** [comment]
I'm leaning towards rename, but not sure we need to do it for v6

**Comment by andreasohlund** [comment]
I'd say not important enough to include in v6?

**Comment by danielmarbach** [comment]
I agree

**Comment by timbussmann** [comment]
should we consider to deprecate `HandleCurrentMessageLater` completely in v7? The new recoverability API allows fairly complex customizations which can probably handle most scenarios already?

**Comment by andreasohlund** [comment]
You mean to use "MoveToCustomErrorQueue(mainInputQueue)" to send it to the back of the queue?

**Comment by timbussmann** [comment]
I meant immediate/delayed retry, depending on the behavior you want to achieve.

**Comment by andreasohlund** [comment]
That depends on the transport, for msmq and sql "immediate" means roll it back to the top of the queue but for others (think rabbit put it at the back when U nack, @bording ?). 


One use case could be a message to update entity X but the "create X" message is further down in the queue for some reason.

SLR with small delay would work here I guess but not as efficient as the current `HandleCurrentMessageLater`.


Not against deprecating though

**Comment by andreasohlund** [comment]
Side note:

There is no doco or samples for this http://docs.particular.net/search?q=HandleCurrentMessageLater

**Comment by danielmarbach** [comment]
The conversation here shows the API itself is not exactly intention revealing. So what are the real use cases this API was built for? // cc @udidahan

**Comment by udidahan** [comment]
The "real" use case was (as described) put the current message in the back of the queue as an alternative way of holding on to the message for some time. No deep analysis was done - it was just, "hey, this might be a good idea", and it got implemented.

**Comment by danielmarbach** [comment]
@udidahan why not defer it then? Because HandleLater is very vague anyway. When the queue is empty handling later would have not much of an effect because the message would just reappear.

**Comment by udidahan** [comment]
@danielmarbach you're absolutely right. It wasn't a well thought out feature.

**Comment by danielmarbach** [comment]
Not criticizing btw.
I'm traying to understand the context and see if it makes sense to stay
with the API or guide users into a better direction

**Comment by udidahan** [comment]
I'm all for guiding users in a better direction.

**Comment by andreasohlund** [comment]
To @udidahan 's defense I'm pretty sure we didn't have "defer" back then so
timeouts where only available to sagas ;)

**Comment by bording** [comment]
> That depends on the transport, for msmq and sql "immediate" means roll it back to the top of the queue but for others (think rabbit put it at the back when U nack, @bording ?).

I did look into this a bit, and it appears that Rabbit attempts to put the message back on the queue as close to its original position as possible, so that should mean back to the head of the queue most of the time.

**Comment by andreasohlund** [comment]
I've raise an issue to deprecate the api

https://github.com/Particular/NServiceBus/issues/4110

closing this discussion
