### ISSUE TITLE
Split MessageMappers into specific uses

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1722]
So as part of 4.2 we obsoleted MessageMapper  #1624 

On v5 this needs to be finished. 

There are two implementations of `IMessageMapper`/`IMessageCreator`:  

 * `SimpleMessageMapper` used by `BinarySerialization`
 * `MessageMapper` used by `BsonSerialization`, `JsonSerialization` and `JsonSerialization`

The plan is to remove `IMessageMapper` and `IMessageCreator`  make the implementations specific use classes for their serializers.

**Comment by timbussmann** [comment]
is there anything in this issue we should address in v6 or v7 for a specific reason?

**Comment by danielmarbach** [comment]
Closing this. Several people took a stab at it and failed. Not sure it is worth pursuing it for now.
