### ISSUE TITLE
Introduce Satellite conventions to be able to specify queue addresses

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#1738]
Currently the satellites such as the timeout feature use subscopes of the endpoints address. This for example creates various queues like:

endpoint.retries
endpoint.timeouts
...

The problem with this is that when we want to specify a broker convention on the ActiveMQ broker we cannot do it globally but we have to repeat each configuration for each created queue. If we could name those queues or change the naming convention we would be able to use the following naming:

timeouts.endpoint
retries.endpoints

Which would then allow to define broker conventions like:

timeouts.*
retries.*

**Comment by andreasohlund** [comment]
@SzymonPobiega will the address refactorings you did make this configurable?

**Comment by SzymonPobiega** [comment]
In https://github.com/Particular/NServiceBus/pull/2818 I introduced a method like this:

```
public void UseCustomLogicalToTransportAddressTranslation(Func<LogicalAddress, string, string> translation)
```

which allows the user to completely override the default mapping for all the local addresses. With item 133 (sender-side distribution we'll take it a step further and allow to use convention for both local and remote addresses)

**Comment by andreasohlund** [comment]
@SzymonPobiega is this still relevant?

**Comment by SzymonPobiega** [comment]
I think that V6 solves that problem. Transports get the instance of `EndpointInstanceName` and translate it however they want, e.g. putting qualifier (satellite name) in front.
