### ISSUE TITLE
Should not populate exception headers before the message is forwarded to the error queue!

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#1773]
**Steps to repro**
1. Set up SLR
2. Stop the endpoint after the FLR has attempted and the message has been  SLR retried but not forwarded to the error queue.
3. Inspect the headers and notice that it has all of the headers relating to exceptions.

We should only add the exception headers when the message is going to be forwarded to the error queue and not before.

See code here:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Faults/Forwarder/FaultManager.cs#L32

Instead, this should only happen when forwarding to the error queue.

@HEskandari @dannycohen - If we fix this issue, how will this affect ServiceInsight?

**Comment by andreasohlund** [comment]
This is fixed in v6 already
