### ISSUE TITLE
Simplify the way we attach headers to messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1793]
I propose the following:

1. Add a Headers property to the upcoming SendOptions
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/SendOptions.cs#L5
2. Obsolete Headers.SetMessageHeader https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus/Headers.cs#L234 and guide users to the Bus.Send(SendOptions) if they need to setheaders
3. Obsolete the Headers.GetMessageHeaders method and guide users to the current message context if they need access to headers on incoming messages https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus/IBus.cs#L315

This would greatly simplify they way we manage headers with little impact on usability.

Thoughts?

**Comment by timbussmann** [comment]
since the API changed drastically with the introduction of `IMessageHandlerContext` and `SendOptions` I think we can safely close this issue. Feel free to reopen in case you disagree.
