### ISSUE TITLE
Deserialization private setters

### ISSUE THREAD

**Issue by marinkobabic** [Particular/NServiceBus#1804]
It would be nice when you could set this setting on the DefaultContractResolver

defaultContractResolver.DefaultMembersSearchFlags |= BindingFlags.NonPublic

by default. So If the message has private setters you would be able to set them using the Json.

**Comment by frankclaassens** [comment]
What was the outcome of this? Can the default JsonSerializer now set private properties?

@andreasohlund @danielmarbach

**Comment by andreasohlund** [comment]
@frankclaassens I've modified https://docs.particular.net/samples/serializers/newtonsoft/ to use

```
public class CreateOrder :
   IMessage
{
   public CreateOrder(int orderId)
   {
       OrderId = orderId;
   }
   public int OrderId { get; private set; }
}
```

and that works all fine, is that what you're asking?
