### ISSUE TITLE
NServicebus 4.2 logs warning about message not found in registry

### ISSUE THREAD

**Issue by twDuke** [Particular/NServiceBus#1834]
Hi we have recently upgraded to NSB 4.2 from 3.5.

After the upgrade NSB logs a warning

```
Message header 'SomeNamespace.ISomeEvent__impl, NServiceBus.Scheduling.Messages__impl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' was mapped to type  'SomeNamespace.ISomeEvent__impl' but that type was not found in the message registry, please make sure the same message registration conventions are used in all endpoints, specially if you are using unobtrusive mode. MessageId: 37cbec38-7957-4b7a-b313-804f6ed3b6fd\37679827
```

If i debug i can see we have a entry in message registry for SomeNamespace.ISomeEvent But the type it looks for is SomeNamespace.ISomeEvent__impl.

We have not changed our unobtrusive settings after the upgrade, so question is what has changed?

I can see the logging has changed in change set 5f1c72ba, seems the file has been renamed or something so cant seem to see full history.

Have we always had the problem, but only recently logging behavior in NSB has changed?

Also open on SO
http://stackoverflow.com/questions/20394590/nservicebus-4-2-logs-warning-about-message-not-found-in-registry

**Comment by gkorobkov** [comment]
I use NServiceBus 4.6.3 and I still have this issue:
2017-08-15 16:38:02,664 [35] WARN  NServiceBus.Unicast.DefaultDispatcherFactory [(null)] <(null)> - Message header 'NameSpace.Type' was mapped to type 'NameSpace.Type' but that type was not found in the message registry, please make sure the same message registration conventions are used in all endpoints, specially if you are using unobtrusive mode.

How can i resolve this warning?

This is a code sample https://github.com/gkorobkov/NSBus4/blob/master/Gk.Ordering/Gk.Ordering.Server/EndpointConfig.cs

**Comment by andreasohlund** [comment]
Responded on the Google Group https://groups.google.com/d/msg/particularsoftware/3aqjDnrN6tM/LQ-TRA_XAwAJ
