### ISSUE TITLE
Move AutoCreation feature from Azure transports to the core (to replace DoNotCreateQueues)

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#1844]
Feature.Disable<QueueAutoCreation>() is improvement over .DoNotCreateQueues()

**Comment by timbussmann** [comment]
@Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers  is this still an issue for azure transports? At first glance the setting can be read by downstreams by the public `CreateQueues` extensions or by directly querying the settings for the "Transport.CreateQueues" key. I think we can close this?

**Comment by SeanFeldman** [comment]
@timbussmann ASB is setting `"Transport.CreateQueues"` on the configuration.
What's the `CreateQueues` extension? I'd rather go through that and not the settings with the magical string :)

**Comment by timbussmann** [comment]
@SeanFeldman I read the issue as a problem for transports not having access to these information which should be possible in the current code base. I'm closing this therefore. If I missed something and this is still an issue, please reopen.
