### ISSUE TITLE
Switch to Json as the default serializer

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1924]
I'd say we should switch to simple.json and move the json.net impl to a separate repo

**Comment by danielmarbach** [comment]
We now support multi deserializer. The user still has to pick a default serializer for outgoing messages. So in theory we could support this in V6.

**Comment by andreasohlund** [comment]
IMO the way forward is to

1. Make serializer choice mandatoru (default serializer if multiple are in use)
2. Move the json.net one out of the core
3. Consider supporting the data contracts serializer since that one is built into dot net

Closing this one as `Withdrawn`
