### ISSUE TITLE
First Level Retries Leaks w/ Competing Consumers

### ISSUE THREAD

**Issue by abombss** [Particular/NServiceBus#1928]
It looks like FLR uses an internal dictionary to track attempts which could cause leaks as messages fail on consumer A and complete on consumer B, they are never cleaned up from A.

https://groups.google.com/forum/#!topic/particularsoftware/dpvLC96p5Og

**Comment by johnsimons** [comment]
@andreasohlund will this be fixed in v6 ?
Do we still patch previous versions ?

**Comment by andreasohlund** [comment]
Yes fixed in v6. Lets do a Impact Asseement to figure out if we should backport?

**Comment by johnsimons** [comment]
@abombss what versions do you need this fixed for ?

**Comment by johnsimons** [comment]
@abombss ping ?

**Comment by abombss** [comment]
Sorry for the late response we are on 4.6.6

**Comment by andreasohlund** [comment]
@abombss we have a fix for this ready for the upcoming v6. How much issues is this causing you at the moment?

Are you able to wait until v6 is out and you can upgrade?

**Comment by abombss** [comment]
I think so, we have bigger issues than this and I think we might skip v5,
and focus on v6. is there a rough eta on v6, year / quarter it will be
available?

**Comment by andreasohlund** [comment]
We usually release a new major each year so early Q3 is my best guestimate
atm

**Comment by johnsimons** [comment]
It seems this is addressed in the next major
