### ISSUE TITLE
Native Support for FLR / SLR

### ISSUE THREAD

**Issue by abombss** [Particular/NServiceBus#1929]
Transports that support dead-lettering and delivery counting should be allowed to use those native capabilities when evaluating number of message processing attempts for FLR and SLR.

With the current implementation its non-deterministic such that depending on the number of nodes I have competing and processing messages the max number of attempts could be unknown.  This becomes more problematic when we have things like autoscaling for our service such that number of nodes may not be known.

With Azure ServiceBus not being able to known how many times the message it becomes difficult to properly configure max Delivery Attempts before Azure uses its native poison message handling to dead letter the message.

**Comment by johnsimons** [comment]
This will be possible in v6.
Not sure if override the `MoveFaultsToErrorQueueBehavior` is the best way to achieve this thought.
@andreasohlund thoughts ?

**Comment by johnsimons** [comment]
We will work on this in the Azure repo, closing this issue

**Comment by andreasohlund** [comment]
I assume that if the transport supports FLR/SLR natively we could just expose a .UseNativeRetries() in the transport that just removes the FLR+SLR behaviors.

Does this make any sense?

Side note: We're contemplating merging the above into a single RetriesBehavior which would make this even easier
