### ISSUE TITLE
When upgrading the NServiceBus.Host nuget it hacks the app.config

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1956]
- using the fluent API and have NSB things in the app.config 
- upgrade NServiceBus.Host
- result is lots of NSB config in my app.config that conflicts with my fluent config effectively breaking my solution.

NServiceBus.Host should not hack app.config on a nuget upgrade

**Comment by samartzidis** [comment]
I would like to support that request as well. In addition, I would like to suggest that it does not overwrite any existing EndpointConfig.cs file.
