### ISSUE TITLE
NServiceBus Inconsistency Regarding The Configuration Of The Audit Queue

### ISSUE THREAD

**Issue by JeffreyAllenMiller** [Particular/NServiceBus#1963]
My scenario is that successfully processed orders are always being sent to a local Audit queue as opposed to a remote queue on another machine via Audit@MachineName. We desire to have the Audit messages sent to a dedicated server where ServiceControl will process them and expose the API that drives ServiceInsight and ServicePulse.

I found the following URL which helped me figure this out http://particular.net/articles/auditing-with-nservicebus. From my perspective though this is an issue that should still be addressed.

Let me explain. I originally had my service configured with this setting
 and I was running using NServiceBus 4.3. With this configuration it always writes to the local audit queue. I was pulling my hair out over this issue. I just upgraded to Version 4.4 and the same thing happens. 

However, if I reconfigure it to use
 
and remove the ForwardReceivedMessagesTo entry it works. That is to say it sends it to the remote server.

I was pulling my hair out for half a day trying to figure this out as we were working on setting up and testing ServiceControl and ServiceInsight (by the way ServiceInsight rocks now), as I did not see this in release notes or I missed it. In either case, it appears that we are trying to have our cake and eat it too. If we are attempting to be backward compatible then in my estimation, ForwardReceivedMessagesTo should continue to work as in the past. In which case I would consider this a bug worth fixing. Likewise, if both settings are present and we are attempting to be backward compatible then the question raised is this an exception case or do we by convention honor the newest configuration setting (this could work but is confusing to say the least). However, if backward compatibility is not the goal, then the Bus should throw an exception indicating that ForwardReceivedMessagesTo is deprecated and specify the new configuration mechanism to used moving forward.

**Comment by danielmarbach** [comment]
I'm sorry that we dropped the ball on this. I think there is a confusion between Auditing and Forwarding. We clarified the documentation around it, here is an extract

> Auditing and Forwarding are very similar, both send a copy of the processed message to another queue. The main difference are intended usage scenarios.

> Auditing is used for collecting information on what is happening in the system, therefore the audited message is enriched with additional information regarding processing it. The forwarded message is a copy of the processed message, without the additional auditing information.
> http://docs.particular.net/nservicebus/messaging/forwarding

If this still an issue or the documentation is unclear feel free to reopen this issue or another issue so that we can help out clarifying or updating the documentation. Closing
