### ISSUE TITLE
Change the license expiration dialog to display appropriate messages when the license expires. 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#1999]
- [ ] Implement the license expiration dialog to be consistent with the rest of the platform.
- [ ] Use proper message when trial expires
- [ ] Use proper message when upgrade protection expires

Relates to https://github.com/Particular/Requirements/issues/20

cc/ @andreasohlund

**Comment by timbussmann** [comment]
We think this should be addressed by the "optimize trial extensions" initiative, so let's close the issue here. Feel free to reopen if you disagree @kbaley @ramonsmits @sergioc @YifatS
