### ISSUE TITLE
Should the transport expose an API to aid in verifying if a target queue exists?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2016]
Given that we have multiple transports today, it would be nice to have an API that exposes IfQueueExists whose implementation would be based on the transport being used.

This would come in handy:
when endpoints need to fail on startup if certain queues don't exist, rather than having to send a message and to catch a `QueueNotFoundException`

@andreasohlund @johnsimons - Thoughts??

**Comment by andreasohlund** [comment]
It seems to hard to make it consistent across all transports. Closing this one
