### ISSUE TITLE
Auto correlation for ReplyToOriginator between sagas doesn't work

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2018]
If calling ReplyToOriginator from either:

1. A timeout handler
2. A handler that didn't start the saga

the autocorrelation for request/response doesn't work. This is because the saga id of the initating saga is needed to correlate back. This is lost when the saga instance is rehydrated.

### Repro

A full set of acceptance tests showing this can be found here:

https://github.com/Particular/NServiceBus/blob/4e4ab0317960bd827e2ff3f77e52042ab7131abc/src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs

### Workaround

The workaround is to specify mappings so that the infrastructure can find the originating saga using some property in the reply message.

### Solution
We need to store the saga id of the starting saga in some kind of metadata field . (We should move the OriginatingEndpoint and OriginatingMessageId there as well)

This issue is opened to not confuse users seeing this issue:

https://github.com/Particular/NServiceBus/issues/629

**Comment by johnsimons** [comment]
@andreasohlund any news on this? Do we want this done for v6 ?
Should this be moved to requirements ?

**Comment by andreasohlund** [comment]
No progress, adding metadata will be a tricky change. Lets raise a issue in req. to track this. I think this one should be kept open since its actually a real bug

**Comment by johnsimons** [comment]
Requirements issue raised https://github.com/Particular/Requirements/issues/224
I'll close this one for now till we flush out all the requirements

**Comment by vchircu** [comment]
The link above - [Particular/PlatformDevelopment#224](https://github.com/Particular/PlatformDevelopment/issues/224) is broken. Can someone please fix it?

**Comment by andreasohlund** [comment]
@vchircu updated, here's the new link https://github.com/Particular/NServiceBus/issues/3322
