### ISSUE TITLE
Better error logging when RavenDB connection fails (e.g. due to a timeout)

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2032]
I'm following a case from a customer facing strange issues on a test environment. Those issues seems to be related to a missing RavenDB connection string in the configuration file.
After fixing the configuration file the environment started behaving correctly.
The hiccup was that discovering that the issue was not easy. RavenDb and the web servers are on different boxes. They only spotted this due to the timeouts coming from reading from the timeout store and then triggering a circuit breaker. It may be useful for NServiceBus to throw a specific error if it can’t communicate with Raven to make this a bit more obvious.

**Comment by danielmarbach** [comment]
@Particular/ravendb-persistence-maintainers can parts of this be addressed in the ravendb repo? If so can we close this?
