### ISSUE TITLE
Roslyn C# compiler can't consume extension methods from NServiceBus.Core

### ISSUE THREAD

**Issue by KevinH-MS** [Particular/NServiceBus#2060]
### Symptoms

User cannot build a NServiceBus 3.3 solution in Visual Studio 2015. Will receive a compiler error that it cannot resolve extension method.

For example
```
Error	CS1061	'Configure' does not contain a definition for 'DefiningExpressMessagesAs' and no 
extension method 'DefiningExpressMessagesAs' accepting a first argument of type 'Configure' 
could be found (are you missing a using directive or an assembly reference?)
```

### Root cause

The new Roslyn compile is more strict about assemblies containing extension methods containing the [ExtensionAttribute](http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.extensionattribute.aspx).

---
The recently previewed C# 6.0 compiler (https://roslyn.codeplex.com/) has a known breaking-change that requires assemblies define extension methods to have an assembly-level System.Runtime.CompilerServices.ExtensionAttribute.  The NServiceBus.Core assembly does not seem to contain this attribute.  Would it be feasible to add this attribute?
  
FWIW, the lack of this attribute will also prevent all versions of the Visual Basic.NET from consuming these extension methods.

**Comment by memark** [comment]
This will be a problem for anyone still on the 3.x version upgrading to VS 2015. See this bug on connect
https://connect.microsoft.com/VisualStudio/feedback/details/1196361

Is there any way a fixed version

**Comment by SimonCropp** [comment]
@memark here is 3.3.14 http://www.nuget.org/packages/NServiceBus/3.3.14

**Comment by memark** [comment]
@SimonCropp Yes. It is also missing the attribute. (Maybe I misunderstood what you meant by sending me this link?)

**Comment by SimonCropp** [comment]
@memark Sorry I misunderstood. I thought you were having trouble building NSB.  Can you email me at simon.cropp@particular.net I have a few suspicions of how to fix this but I will need your help to test them

**Comment by SimonCropp** [comment]
@memark thanks for the email. I believe I have a fix for this. See the PR here https://github.com/Particular/NServiceBus/pull/2704

Unfortunately I am heading of on leave tomorrow. However I have given @andreasohlund a run down of the issue

**Comment by andreasohlund** [comment]
@memark I've prepared a beta for a 3.3.15 release. Would you have any chance to verify that it fixes your issue? http://builds.particular.net/viewLog.html?buildId=102294&buildTypeId=NServiceBusCore_Build&tab=artifacts   (just log in as guest)

**Comment by memark** [comment]
@andreasohlund Thank you, this fixes my issue. Referencing this version of NServiceBus.Core, my code compiles fine in VS 2015.

**Comment by andreasohlund** [comment]
Thanks, we'll proceed with release

**Comment by memark** [comment]
The initial fix was impressively fast, but now it's been twelve days. Are there any plans to release this fix any time soon?
