### ISSUE TITLE
IHandleSagaNotFound fires multiple times for a message that targets multiple sagas

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2080]
The current api is confusing, here is the definition of how it should work:

* `IHandleSagaNotFound` should only fire if no saga was invoked for the message
* `IHandleSagaNotFound` should only fire once per message
* `IHandleSagaNotFound` should not fire for timeouts - fixed
* `IHandleSagaNotFound` should only fire if no explicit `IHandleSagaNotFound<T>` has been called

Semantics for `IHandleSagaNotFound<T>` (new interface) is:

* Can only be defined on a saga that is handling the give message
* Is invoked if the given saga couldn't be found for the message
* Should not apply for timeouts

**Comment by johnsimons** [comment]
Sounds good @andreasohlund, can u raise it in the requirements?

**Comment by nohros** [comment]
The bug part(fire multiple times) will be fixed for v4.x?

**Comment by johnsimons** [comment]
@andreasohlund I think we should also fix `IHandleSagaNotFound` should only fire if no saga was invoked for the message, at the moment it fires if the first Saga is not found, even thought subsequent sagas could be found :(

**Comment by SeanFeldman** [comment]
@johnsimons could you please add `###Docs` or link doco PR to this? Thank you :)

**Comment by andreasohlund** [comment]
@SeanFeldman pretty sure this should be classified as a bug, not feature?

@johnsimons please confirm

**Comment by indualagarsamy** [comment]
@andreasohlund - either way, shouldn't our doco be updated / clarified on the ISagaNotFound section. At the moment, there is a code snippet, but i think it deserves its own section, see current doco here: http://docs.particular.net/nservicebus/sagas-in-nservicebus

**Comment by andreasohlund** [comment]
Thing is that this one just fixed the fact that we call the handlers multiple time. The new api hasn't been implemented yet?

**Comment by johnsimons** [comment]
@SeanFeldman the doco is done as part of the PR #2629

**Comment by danielmarbach** [comment]
What about this?

https://github.com/Particular/NServiceBus/issues/298
