### ISSUE TITLE
Redundant use of DelegateFactory.CreateSet in XmlMessageSerializer

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2083]
so in here `XmlMessageSerializer`

we have 

            foreach (var p in props)
            {
                logger.Debug("Handling property: " + p.Name);

                DelegateFactory.Create(p);
                if (!isKeyValuePair)
                {
                    DelegateFactory.CreateSet(p);
                }

                InitType(p.PropertyType);
            }

            foreach (var f in fields)
            {
                logger.Debug("Handling field: " + f.Name);

                DelegateFactory.Create(f);
                if (!isKeyValuePair)
                {
                    DelegateFactory.CreateSet(f);
                }

                InitType(f.FieldType);
            }
        }

Note the use of `DelegateFactory.CreateSet` that doesnt use the return value.  So either this is a bug or it is redundant code. No idea which ATM

**Comment by johnsimons** [comment]
Addressed in https://github.com/Particular/NServiceBus/commit/fe402e7ea5196f34bf29883fa957ffdc68cdcbd0
