### ISSUE TITLE
Make MSMQ CircuitBreaker configurable

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus#2085]
from [NServiceBus.SqlServer #7](https://github.com/Particular/NServiceBus.SqlServer/issues/7)

```
<appSettings>
  <add key="NServiceBus/MsmqDequeueStrategy/Threshold" value="100"/>
  <add key="NServiceBus/MsmqDequeueStrategy/ResetEvery" value="00:00:30"/>
</appSettings>
```

related code [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs#L363)

**Comment by danielmarbach** [comment]
@johnsimons I think @chrisbednarski made a good point and since we implemented it in https://github.com/Particular/NServiceBus.SqlServer/issues/7 shouldn't we align MSMQ as well?

**Comment by andreasohlund** [comment]
If we do this it should be a code first API

`.UseTransport<Msmq>().CircuitBreaker().Bla`

**Comment by danielmarbach** [comment]
This seems to be an additive API we could add to MSMQ only. would this change our viewpoint in terms of future or next minor?

**Comment by bording** [comment]
> If we do this it should be a code first API

👍 v4 of RabbitMQ now has this:

https://docs.particular.net/nservicebus/rabbitmq/connection-settings#controlling-behavior-when-the-broker-connection-is-lost-timetowaitbeforetriggering

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/15.
