### ISSUE TITLE
Have MSMQ throw if CheckMachineNameForComplianceWithDTCLimitation isn't satisfied

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2132]
If we are to be safe by default for production, shouldn't we be throwing in the `CheckMachineNameForComplianceWithDTCLimitation`, see 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/CheckMachineNameForComplianceWithDtcLimitation.cs

@andreasohlund @indualagarsamy @SimonCropp thoughts?

**Comment by andreasohlund** [comment]
Do we see this as a breaking change?

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/14.
