### ISSUE TITLE
Remove TimeoutData.Id

### ISSUE THREAD

**Issue by synhershko** [Particular/NServiceBus#2169]
To separate persistence from this DTO

See https://github.com/Particular/NServiceBus.RavenDB/commit/5d053f256e55bac528de4916c0883bc6dae16578#commitcomment-6581498

@andreasohlund @johnsimons @SimonCropp

**Comment by johnsimons** [comment]
@andreasohlund do you see us pulling this off in the v6 timeline ?

**Comment by andreasohlund** [comment]
I'd say lets bump it

**Comment by andreasohlund** [comment]
Not going to make it into v6, milestone removed

**Comment by andreasohlund** [comment]
While this is still valid we're moving towards a model where all the transports cater for their own timeout needs natively in some form so we're not likely to prioritize this. Closing
