### ISSUE TITLE
Ability to opt out of using message conventions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2202]
The message conventions allow the users to convey the intent of messages. But they already convey that intent by calling bus.publish/ bus.send or bus.reply. so allowing users to "also convey the intent via conventions" should be an optional second check.

**Comment by andreasohlund** [comment]
How far away are we from supporting this?

**Comment by andreasohlund** [comment]
The thing we need to figure out is the autosubscribes since they only would work for things flagged as "events"

Do we want  to:

1. Subscribe to all messages (v4 did this)
2. Tell users to manually subscribe

Thoughts?

**Comment by timbussmann** [comment]
I like the idea of support poco messages without further configuration.

@andreasohlund both approaches don't seem very appealing but in that case I'd prefer option 1. What about providing a new handler interface `IHandleEvents` which is used for autosubscription instead?

**Comment by andreasohlund** [comment]
Actually the spike @SzymonPobiega did where we essentially autoroute all messages (including commands) would make this a non-issue.

Can you shime in here @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@andreasohlund that's a bit more complex. What my spike did was:
 * Make message-driven pub-sub a separate feature that requires specific configuration (e.g. which message should be subscribed -> removes dependency on ability to distinguish events on subscriber side)
 * Allow all unicast transports to use zero-config routing through some kind of storage in which commands and events are treated equally
 * Assume multicast transports would use multicast for commands (this is a far-fetched assumption since e.g. in Rabbit there is now way to enforce a particular number of queues bound to a given exchange)

**Comment by andreasohlund** [comment]
This turns out to be pretty straight forward, see https://github.com/Particular/NServiceBus/pull/4622

**Comment by andreasohlund** [comment]
Question is how dangerous this is since we only auto subscribe to events this means that users that skips the conventions won't have their subscriptions setup properly?

We could go back to "autosubscribe to everything we have a handler for" that we had in v4?

**Comment by timbussmann** [comment]
> We could go back to "autosubscribe to everything we have a handler for" that we had in v4?

probably no big deal for MSMQ, especially when no publishers have been registered, but not sure how this would impact rabbit and other transports? @bording

**Comment by bording** [comment]
>  but not sure how this would impact rabbit and other transports?

The main thing that would happen in Rabbit is that you'd end up creating type exchanges and bindings that would end up never being used, if the type was actually only even sent and not published. It wouldn't be a problem, aside from creating infrastructure in the broker that never gets used.

**Comment by andreasohlund** [comment]
Just noting that once https://github.com/Particular/NServiceBus/pull/5130 is merged we no longer need conventions to be able to receive messages given that all `T`'s in `IHandleMessages<T>` will be registered regardless if they match a convention or not

**Comment by andreasohlund** [comment]
I still like @timbussmann 's idea with `IHandleEvents` to deal with autosubscribe best but just adding that we also could make autosubscribe a mandatory config and provide a convention there:

`.EnableAutoSubscribe(t=> t.Namespace.EndsWith(".Contracts")));`

**Comment by andreasohlund** [comment]
>Just noting that once #5130 is merged we no longer need conventions to be able to receive messages given that all T's in IHandleMessages<T> will be registered regardless if they match a convention or not

Strike that, https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs#L29 still prevents this
