### ISSUE TITLE
Feature request: Async message handler

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2220]
Is there any chance to have an async message handler? Something like:

```
interface IAsyncMessageHandler<TMessage>
{
    Task Handle( TMessage message );
}
```

The scenario is:
Given that there are tons of library out there that support the async pattern it is pretty easy for the end user to be required to go down to the async/await pattern or, worse, to be required to use the TPL directly, in this last case 2 things can happen:

```
class MyHandler : IHandleMessages<MyMessage>
{
    public void Handle( MyMessage message )
    {
             Task.Run( ()=> { ... } );
    }
}
```

the above will generate a new thread, or something handled by the TPL, and the the message handler will end before the real work is completed, and second if there is any Exception in the generated task we cannot capture it and we are requiring the user to write a contiuation, check for failure and manually raise the exception for us.

Comments?
.m

**Comment by Thorium** [comment]
+1 for Async, for concurrency, to not block the thread.

**Comment by boxofnotgoodery** [comment]
Any update or thoughts on this?

**Comment by danielmarbach** [comment]
Here is our recent announcement. http://particular.net/blog/async-await-its-time

**Comment by danielmarbach** [comment]
Closing this one. It is on mission.
