### ISSUE TITLE
Scheduler API created an unnecessary extra thread to execute the users action

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2325]
So the way our Schedule API works is by using a special message `ScheduledTask` that gets deferred.
We then have a [handler in the core](https://github.com/Particular/NServiceBus/blob/release-5.0.0/src/NServiceBus.Core/Scheduling/ScheduledTaskMessageHandler.cs) that is handling those messages.

That handler is calling `scheduler.Start` which if we dig into that code calls the users action in a new thread, see https://github.com/Particular/NServiceBus/blob/761877c61d6968661f719a23576d13b09e2be6dd/src/NServiceBus.Core/Scheduling/DefaultScheduler.cs#L45

This to me seems to be unnecessary since the handler is already using its own thread.

I propose we remove the creation of a new thread.
This also has the added benefit of enlisting in the current `TransactionScope` and `ThreadStatics` would also work.

**Comment by danielmarbach** [comment]
We changed the behavior in V6 to no longer spin up dedicated tasks

https://github.com/Particular/NServiceBus/commit/d96be1169c796b9e34ad01495b12bc1126b405f8#diff-696f13b7392fcbb966e1347c09534cf1L36

I'm closing this one. Feel free to reopen if necessary.
