### ISSUE TITLE
Our use of internal extension methods

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2326]
As part of reviewing #2322 I noticed that @SimonCropp is using an extension method in the PR and I raised whether we really needed it.

Here is the extract of the conversation between @SimonCropp and I:

> johnsimons
> Does this method really need to be an extension method?
> Even though we are not making this public I still think it would be better to restrict our usages of extension methods that are used infrequently and do not really provide much gain.
> 
> 
> SimonCropp
> @johnsimons disagree. extension methods should be used when they result in more readable code
> 
> and this
> ```c#
> if (type.IsTypeFromParticularAssembly())
> {
>     return false;
> }
> ```
> is more readable than this
> ```c#
> if (ParticularAssemblyHelper.IsTypeFromParticularAssembly(type))
> {
>     return false;
> }
> ```
> in this case the type name is only noise.
> 
> 
> johnsimons
> @SimonCropp my issue is that in this case we are adding an extension method to a CLR type and that means that now every time we have a type instance that shows up in intellisense.
> If this particular method becomes helpful to other areas of the code, then yes we can then re-evaluate whether it is a good idea to expose it as an extension method to as you point out making the code more readable, but in this occurrence the extension method is really only called from a single place in the framework (excluding tests). So I am wondering if this is a premature optimisation.
> 
> In summary I would really dislike to see us with intellisense like this:
> ![350e82b0-28d0-11e4-96b5-521ab5bdd4bc](https://cloud.githubusercontent.com/assets/122651/3991018/659a2d2c-28d9-11e4-8b9c-548e27976178.png)
> This happens when we reference RhinoMocks!
> 
> 
> SimonCropp
> That is an unfair comparison. I am extending a very specific class. no polluting intenseness for all objects
> 
> 
> johnsimons
> Well I think that depends, you are extending `Type` which is actually used quite frequently in our framework, so IMO I see it as an unnecessary requirement for this case as explained in the previous comment.
> Anyway, I'm just pointing out that slowly our intellisense is becoming bloated with extension methods that majority of time are only really used in a single class which begs the question whether it should be easily exposed everywhere or kept private within the scope of that class.
> Pretty much what we are doing with the features classes.
> 
> 
> SimonCropp
> while I am happy to have this discussion it should not happen as part of this PR. This extension method approach is in keeping with the current code base. for example https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Utils/Reflection/ExtensionMethods.cs
> 
> so feel free to raise a new issue that this conversion can happen on and the outcome can be applied consistently across the entire codebase.

So what does everyone else think ?
Do we need to put rules in place, the same way as we currently have the rule that **we do not add public extension methods to types that we do not own** ?

**Comment by andreasohlund** [comment]
This discussion seems to be stale, please reopen if someone feels that we still need to align
