### ISSUE TITLE
Xml in a message can cause a SO during message deserialization

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2336]
When the endpoint is attempting to deserialize a message, if the content has unescaped xml, this causes a StackOverflow exception.

This only happens in interop situations, messages serialized by NServicesBus xml serializer are escaped correctly.
--

**Steps to reproduce**
- Create a NSB endpoint
- Have a message definition as 
```c#
  public class Tie3ConfirmedEvent 
    {
        public DateTime TieConfirmedTime { get; set; }
        public int TieId { get; set; }
        public string IpAddress { get; set; }
        public string ConfigContent { get; set; } 
    }
``` 
- Have a message handler for this in the endpoint
- Send a message with xml as below using QueueExplorer or any other tool with the following:
```xml
<?xml version="1.0"?>
<Messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/ClassLibrary1.MyEvents">
	<Tie3ConfirmedEvent>
		<TieConfirmedTime>2014-08-26T19:38:01.2188085-07:00</TieConfirmedTime>
		<TieId>255</TieId>
		<IpAddress>172.255.243.222</IpAddress>
		<ConfigContent>
			<anything name="Andrew" value="DidStuff" dataType="string" />
		</ConfigContent>
	</Tie3ConfirmedEvent>
</Messages>
```
Note that this throws a SO
![image](https://cloud.githubusercontent.com/assets/854553/4054864/90eb14ba-2d97-11e4-9244-eeb5ba3c87f5.png)

**Workaround**
-  Change the message definition for the type that is expecting XML to `XElement` instead of `string`
```
 public class Tie3ConfirmedEvent 
    {
        public DateTime TieConfirmedTime { get; set; }
        public int TieId { get; set; }
        public string IpAddress { get; set; }

        public XElement ConfigContent { get; set; } 
    }
```

-  Add endpoint initialization that sets up the deserialization properly such as:

```c#
public class SetupXmlDeserialization : IWantToRunBeforeConfiguration 
{ 
  public void Init() 
  { 
    Configure.Serialization.Xml(m => m.DontWrapRawXml()); 
  } 
}
```

**Comment by johnsimons** [comment]
This will be addressed in https://github.com/Particular/docs.particular.net/issues/579
