### ISSUE TITLE
Component Registration API on bus configuration not consistent to extension aproach used elsewhere

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#2341]
this lambda API feels off now that most of the builder is extension based: 

builder.RegisterComponents(c => c.ConfigureComponent<DebugFlagMutator>(DependencyLifecycle.InstancePerCall));

should be 

builder.RegisterComponents().ConfigureComponent<DebugFlagMutator>(DependencyLifecycle.InstancePerCall));

**Comment by andreasohlund** [comment]
Is this worth the hazzle it would create for the users? 

Since we're moving away from containers anyway I'm going to close this
