### ISSUE TITLE
move more Host concepts out of the core

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2342]
These are all host specific concepts and should not exist in the core

* `EndpointSLAAttribute` 
* `EndpointNameAttribute` 
* `IConfigureThisEndpoint`

**Comment by SimonCropp** [comment]
@andreasohlund 

re EndpointSLAAttribute

given the code api is the same amount of code for users, string typed, and and much less code for us do we just "mark as obsolete with warning" now and switch to error in v6

**Comment by SimonCropp** [comment]
also the removal of IConfigureThisEndpoint from the core needs EndpointSLAAttribute to be removed first

**Comment by andreasohlund** [comment]
Sounds good, is there doco that we need to remove/update?

**Comment by SimonCropp** [comment]
@andreasohlund  yeah there are two token mentions of `EndpointSLA` http://docs.particular.net/search?q=EndpointSLA   i would say just remove them and point to the code version

**Comment by andreasohlund** [comment]
Makes sense

**Comment by SimonCropp** [comment]
@indualagarsamy will this effect servicematrix?

**Comment by indualagarsamy** [comment]
@SimonCropp - I am assuming that these will be available on the NServiceBus.Host nuget package.
At the moment, yes the EndpointSLA attribute is being generated and also the interfaces with `IConfigureThisEndpoint` - but these happen when creating a NSB host endpoint. 

If you are obsoleting the interface and the attribute then I can make the appropriate fixes in SM to the new API changes / removing them. Please ping me on the PR.
