### ISSUE TITLE
IManageMessageFailures is incompat with non transactional 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2364]
Since IManageMessageFailures is called from within `FirstLevelRetries`. and `FirstLevelRetries` is only executed for transactional https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Transport/TransportReceiver.cs#L313

So IManageMessageFailures  wont execute. and hence error queue wont execute.

First is this correct? Need to write an acceptance test  So since there are incompat should we throw an exception if someone defines both?

**Comment by johnsimons** [comment]
Issue addressed as part of #2601
