### ISSUE TITLE
Persistence no longer required for SendOnly endpoints

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2367]
## 

When eg running RabbitMQ in sendonly mode

```
var config = new BusConfiguration();
config.UseTransport<RabbitMQTransport>();
var sendOnly = Bus.CreateSendOnly(config);
```

Throws https://github.com/Particular/NServiceBus/blob/release-5.0.0/src/NServiceBus.Core/Persistence/PersistenceStartup.cs

I think the same problem exists for a regular endpoint that doesn't use any persistences, eg a rabbit with timeout management disabled and no sagas in scanned types.

I think this check needs to be lazy in some way.

**Comment by dtabuenc** [comment]
With the new change I can no longer publish from Send-Only configured endpoints. We have many web-site endpoints that simply publish messages but never receive anything (subscriptions and all that are handled by a separate NSB host process). While it's nice to not require subscription persistence for send-only endpoints, it should not simply ignore the config if it is there, which is what this "fix" seems to do.

**Comment by andreasohlund** [comment]
@dtabuenc you're correct. I've raised a bug to track this

https://github.com/Particular/NServiceBus/issues/2612
