### ISSUE TITLE
Send/store metadata for error/audit metadata separately to original message

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2368]
So exceptions stack trace can be very large. should we trim them?

Should the transport supply the "how long"?

---

_update by @adamralph_
### Problem

E.g. when an exception is thrown from a handler and the exception message is large, the error message we create and send to the error queue may cause the transport to refuse the message since we copy the exception message into the headers. In this scenario the endpoint is stopped and the original message remains in the queue.

This problem generalises to any point where we add headers to a message or tamper with it in any other way. This is a fundamental design flaw. We should keep the additional metadata separate from the original message.

In https://github.com/Particular/NServiceBus/issues/2956 we hardcoded the error message size limit to 16,384 to overcome an immediate problem for a customer using the RabbitMQ transport but this does not fix the problem generally. Nor did it solve the problem for that customer in all cases. Since the fix, the customer is sending even larger messages and the hardcoded limit of 16.384 it still too high. A new bug has been raised to reflect their current problem #3023.

The suggested plan of attack is that we will not fix bug #3023 as it is effectively unfixable in all current major versions due to a design flaw which would require a breaking change to re-mediate. Instead we will attempt to offer the customer a workaround. We will offer this feature in v6 and recommend an upgrade to avoid the problem and any workarounds.
### Plan of Attack
- [ ] _TBD_
- [ ] Prepare docs
- [ ] Prepare announcement
- [ ] Release
- [ ] Publish docs

**Comment by johnsimons** [comment]
Concern raised in https://github.com/Particular/Requirements/issues/219

**Comment by adamralph** [comment]
From https://github.com/Particular/PlatformDevelopment/issues/219 :

@johnsimons:

>So exceptions stack trace can be very large. should we trim them?
> Should the transport supply the "how long"?
> Perhaps a setting in NSB it self?
> 
> Originally raised in Particular/NServiceBus#2368

@andreasohlund

> I think the transport should define a max header size and then we can try to come up with an algorithm to trim long headers?

@mauroservienti 

> I'd say first compress (gzip) and only as the last option trim

@andreasohlund 

Interesting. Are you talking about gzipping the individual values?

@mauroservienti 

> yes, why not compress the header values (only those that can be long, such as the StackTrace)?

> it can be easily done using a GZipStream, don't really know what the compression rate can be and if it worth the effort, but generally text can be compressed quite a bit.

> it's obvious that is not a solution because it is always possible that a compressed value is still large enough to violate the transport message limits, but is better than losing a portion of the information (not really losing since we still have logs at the endpoint).

@SeanFeldman 

> Just as a thought - what if ExceptionHeaders are turned into DataProperties? We have no limit on size of those and could easily store as much as needed w/o need to compress or risk to loose message itself.

**Comment by adamralph** [comment]
@Particular/engineers after chatting with @johnsimons about this, I feel this is something we should address in V6 and switch to a model where we do not tamper with the original message, but use other means to communicate metadata for auditing, error diagnosis etc., which will obviously affect things like ServiceControl.

**Comment by SzymonPobiega** [comment]
@adamralph :+1: for proceeding with designing the plan of attack. Given SC is in the picture, it surely won't be a walk in the park.

**Comment by danielmarbach** [comment]
:+1: @andreasohlund And I also talked about that and the possibility to
have an additional message containing a special payload. Correlating etc.
is not trivial but solvable

On Wednesday, October 21, 2015, Szymon Pobiega <notifications@github.com>
wrote:

> @adamralph <https://github.com/adamralph> [image: :+1:] for proceeding
> with designing the plan of attack. Given SC is in the picture, it surely
> won't be a walk in the park.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2368#issuecomment-149843722>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by adamralph** [comment]
OK, given that we have 4 thumbs up (including @johnsimons) I'm going to mark this short term focus and bump it upwards on the board.

**Comment by SzymonPobiega** [comment]
As this problem is also affecting audits (although the volume of information we add to audits is much smaller), the TF needs to take the effect of this additional message into account. Not only will that require 2x higher message receive throughput but also a correlation mechanism because the messages might come out-of-order.

**Comment by adamralph** [comment]
There was a question regarding the type of this issue, i.e. bug, feature etc.

I've revisited the title and problem and I think it's OK for this to remain as a feature. There is a current bug (https://github.com/Particular/NServiceBus/issues/3023), but it's effectively unfixable. We will offer a workaround and close it as wontfix. We need to change the design, and effectively offer a new feature which anyone writing tooling around our error and audit handling (including ourselves with ServiceControl) can take advantage of.

**Comment by ramonsmits** [comment]
As mentioned, I don't like the trimming, that is data loss.

Couple of options that I didn't read yet. This is more on reducing header size in general.

- Should we even store complex types in headers?
- Use xml attributes to shorten header XML, breaking compatibility with older versions.
- Why not store headers like http headers, key value separated by a colon.
- Use compression on xml fragments. If an compression attribute is set then the value contains base64 compressed data.


You could store the exception data in a separate message, but what it that data larger then the transport message limit? You need to use some kind of storage and I like @yvesgoeleven his idea to use the databus to store the data before it can be processed. The bad thing about the databus is that it purges data based on the TTL AFAIK.

**Comment by adamralph** [comment]
@SzymonPobiega note that an additional message is only one possible solution.

**Comment by adamralph** [comment]
@ramonsmits agreed. Trimming is data loss and, in retrospect, https://github.com/Particular/NServiceBus/issues/2956 may have been a misstep. In fact, if we are successful in providing a workaround for https://github.com/Particular/NServiceBus/issues/3023 then we may want to consider reverting the patch introduced in 5.2.7 (good that we didn't backport! :wink:).

Generally, I think we should push for a solution which does not tamper the original message in anyway. Reduction of header size isn't enough. We could always have a situation where a customer specifically tunes his messages to fit just inside the transport size limit and even a little tinkering could push it over the edge.

**Comment by timbussmann** [comment]
but we're heavily relying on custom headers, not only for auditing. While long exception messages may be the obvious failure reason, even adding a SLR header may exceed the transport size limit, right?

I do not fully agree on the "data loss" argument when truncating exception messages. The exception message doesn't belong to the "data", the original message and it's headers are the data. The exception should also be logged fully in the endpoint's log file. Therefore truncating the exception is no data loss at all. That information is not relevant for processing data, it's a helpful information for the user to avoid going through tons of log files.

**Comment by adamralph** [comment]
@timbussmann the SLR header is a good point. It could get quite contrived/complex if we're persisting even that outside the message itself.

You also make a fair argument regarding the exception message and data loss. I agree that this should not be the canonical reference for the exception details.

However, how far can truncation take us? I originally thought about a solution where the truncation could be made configurable to allow apps to be tuned according to their needs but I think this will end up in a trial and error scenario, where, in the face of failures, a customer will end up bisecting the truncation limit and retrying until they reach the point where the error message is allowed into the transport. They may even go all the way, or close to, a setting of zero (i.e omit the exception message entirely) but it's likely that problems with putting their original messages on the bus will start to outweigh error message problems as they approach that limit.

Another thing we *could* do, is to build in this trial and error into the core itself, i.e keep trimming until success, but I'm sure I'm not the only one who finds that more than a little ugly. However, the workaround for https://github.com/Particular/NServiceBus/issues/3023 may even end up being exactly that.

As I think more about trimming, it seems that all paths end up in trial and error trim size reduction, whether automated or manual. It doesn't feel like a good solution.

**Comment by danielmarbach** [comment]
Since the message size limit belongs to the transport such a trimming can
only be properly addressed by the transport. You could fall back to
gzipping the strings but this is also weird...

On Thursday, October 22, 2015, Adam Ralph <notifications@github.com> wrote:

> @timbussmann <https://github.com/timbussmann> the SLR header is a good
> point. It could get quite contrived/complex if we're persisting even that
> outside the message itself.
>
> You also make a fair argument regarding the exception message and data
> loss. I agree that this should not be the canonical reference for the
> exception details.
>
> However, how far can truncation take us? I originally thought about a
> solution where the truncation could be made configurable to allow apps to
> be tuned according to their needs but I think this will end up in a trial
> and error scenario, where, in the face of failures, a customer will end up
> bisecting the truncation limit and retrying until they reach the point
> where the error message is allowed into the transport. They may even go all
> the way, or close to, a setting of zero (i.e omit the exception message
> entirely) but it's likely that problems with putting their original
> messages on the bus will start to outweigh error message problems as they
> approach that limit.
>
> Another thing we *could* do, is to build in this trial and error into the
> core itself, i.e keep trimming until success, but I'm sure I'm not the only
> one who finds that more than a little ugly. However, the workaround for
> #3023 <https://github.com/Particular/NServiceBus/issues/3023> may even
> end up being exactly that.
>
> As I think more about trimming, it seems that all paths end up in trial
> and error trim size reduction, whether automated or manual. It doesn't feel
> like a good solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2368#issuecomment-150166697>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by timbussmann** [comment]
Do we need to actually define a "maximum payload size" (e.g. user message size) per transport which makes sure there is enough space left to put on our custom headers in every occasion? 
For the exception headers: Is it possible to check the final message size before sending it to the transport and truncate then if necessary? This would mean as long there is enough space, our headers could be larger than our predefined "maximum header size" but we would be able to cut that down when necessary.

**Comment by danielmarbach** [comment]
Regarding moving exception into another messages payload and correlation.
This is peobably the most scalable solution. Since failure messages are
eventual consistent anyway it would hurt that much. In fact since we'd like
to split audits and errors anyway in SC this might be the logical
consequence

On Thursday, October 22, 2015, Adam Ralph <notifications@github.com> wrote:

> @timbussmann <https://github.com/timbussmann> the SLR header is a good
> point. It could get quite contrived/complex if we're persisting even that
> outside the message itself.
>
> You also make a fair argument regarding the exception message and data
> loss. I agree that this should not be the canonical reference for the
> exception details.
>
> However, how far can truncation take us? I originally thought about a
> solution where the truncation could be made configurable to allow apps to
> be tuned according to their needs but I think this will end up in a trial
> and error scenario, where, in the face of failures, a customer will end up
> bisecting the truncation limit and retrying until they reach the point
> where the error message is allowed into the transport. They may even go all
> the way, or close to, a setting of zero (i.e omit the exception message
> entirely) but it's likely that problems with putting their original
> messages on the bus will start to outweigh error message problems as they
> approach that limit.
>
> Another thing we *could* do, is to build in this trial and error into the
> core itself, i.e keep trimming until success, but I'm sure I'm not the only
> one who finds that more than a little ugly. However, the workaround for
> #3023 <https://github.com/Particular/NServiceBus/issues/3023> may even
> end up being exactly that.
>
> As I think more about trimming, it seems that all paths end up in trial
> and error trim size reduction, whether automated or manual. It doesn't feel
> like a good solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2368#issuecomment-150166697>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by adamralph** [comment]
Added to 6.0.0 since any solution is likely to be breaking so we should at least consider for 6.0.0 before bumping to 7.0.0.

**Comment by DavidBoike** [comment]
The real problem here is exception traces. What other header even comes close to being a significant payload by itself?

i would not support doubling the volume of audit messages just to absolutely never touch a message in any way/shape/form. If a customer message is so big that adding an SLR header will put it over the limit, they're mere bytes away from the limit and already flirting with disaster.

**Comment by SeanFeldman** [comment]
I like the idea of claim check. So what @yvesgoeleven [suggested here](https://github.com/Particular/NServiceBus/issues/2368#issuecomment-58180732) could be an option. It doesn't increase number of messages and allows maximum size of user payload.

**Comment by johnsimons** [comment]
@SeanFeldman that idea is not bad at all but we would need a way to clean it up

**Comment by SeanFeldman** [comment]
@johnsimons don't know if we should clean it up, or provide guidance to our customers.

**Comment by andreasohlund** [comment]
I like @timbussmann 's idea with a "max payload size", https://github.com/Particular/NServiceBus/issues/2368#issuecomment-150169746, since that would also help us provide users with better guidance when they have messages that goes over the limit even without our headers. Witht that in place we can have different strategies to solve it for the messages that will be to big:

* compress
* shorten
* store extra stuff elsewhere (the claim check mentioned)
* extra message
* etc

**Comment by timbussmann** [comment]
> The real problem here is exception traces. What other header even comes close to being a significant payload by itself?

I disagree. The real problem is, that we add headers to messages without any prechecks. While fixing this for exception messages will help for most cases, it doesn't solve the issue and some day users will come with failing messages because their message was already at the size limit when we're adding SLR headers. How do fix the issue then?

**Comment by andreasohlund** [comment]
Not going to make it into v6, milestone removed
