### ISSUE TITLE
Allow MSMQ DeadLetter flag to be controlled per message send/publish operation

### ISSUE THREAD

**Issue by RobertoDelloglio** [Particular/NServiceBus#2372]
It would be useful to have a way to customize the behaviour, for MSMQ or any other transport with the concept of dead letter, of DeadLetter for some specific messages. (maybe using an attribute like [Express] or [TimeToBeReceived])

Now the deadletter is configured in the connectionstring of the Transport and affect all the message that are submitted to the queue. 

My case is a Web Site that needs to send message in a reliable way (using dead letter + TTBR=infinite) but also needs to send some messages that can be processed or not and should disappear in the receiving queue after some time (using dead letter=false + TTBR = 1 minute)  without polluting the dead letter of the sender machine if not processed in the given time (TTBR).

Thanks.

**Comment by christoffer-lundqvist** [comment]
I totally agree with Roberto. We have exactly same need. Some messages from a sending endpoint should be able to be configured to not use the Dead letter queue.

**Comment by andreasohlund** [comment]
I think the most sensible default would be to turn deadlettering off for messages with TTBR set since a TTBR means that you're good with loosing the message so the deadlettering would most likely not add any value.

Side note: Please be aware of the limitations of TTBR with msmq: 

https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-msmq-transport

**Comment by christoffer-lundqvist** [comment]
That default works for us.

**Comment by andreasohlund** [comment]
I've raised a separate issue to change the default to OFF id TTBR is used https://github.com/Particular/NServiceBus/issues/2372

**Comment by timbussmann** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/16.
