### ISSUE TITLE
Obsolete .ScaleOut().X 

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2412]
Since its no longer used. All transports should support seamless scaling

**Comment by johnsimons** [comment]
@andreasohlund we have re-purpose these feature in v5.2, see https://github.com/Particular/NServiceBus/commit/14517c0dc6815cba2d53ee9bb517b09fe0eb3f0f

Are you sure you still want to deprecate `config.ScaleOut()` ?

**Comment by andreasohlund** [comment]
Agree to keep .ScaleOut() but we should remove .SingleBrokerQueue()?

**Comment by johnsimons** [comment]
> Agree to keep .ScaleOut() but we should remove .SingleBrokerQueue()?

How about `UseUniqueBrokerQueuePerMachine` do we also remove it ?, BTW, just checked v6 and we are not using "ScaleOut.UseSingleBrokerQueue" setting so it is ok to remove, but what are the implications of this removal for the transports ?

**Comment by andreasohlund** [comment]
I've removed it from rabbit+sql and I've talked it through with @SeanFeldman and @yvesgoeleven so we're good in that regards

**Comment by SeanFeldman** [comment]
@andreasohlund can we go over this again with @yvesgoeleven and myself?

**Comment by andreasohlund** [comment]
Yup, schedule a call?

**Comment by SzymonPobiega** [comment]
Include me in the call. Need to understand that better. To me the only sensible options are queue-per-endpoint or queue-per-instance with an exception that non-broker transports do not support queue-per-endpoint.

**Comment by andreasohlund** [comment]
@SzymonPobiega will this be covered in the new routing in v6?

**Comment by SzymonPobiega** [comment]
I left `ScaleOut.UniqueQueuePerEndpointInstance` for now.

**Comment by andreasohlund** [comment]
Duplicate of #3495
