### ISSUE TITLE
When_receiving_that_completes_saga

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#2441]
Is unable to handle retries after the saga has completed as the in memory persister blows up with 'Saga not found' exception

**Comment by danielmarbach** [comment]
@yvesgoeleven is this still an issue or can we close?

**Comment by dbelcham** [comment]
@yvesgoeleven any thoughts on this now?

**Comment by yvesgoeleven** [comment]
I assume this got resolved by introducing the idempotency check on test runs we have in place all over now. I'd say close it, will reopen if I ever see it again.
