### ISSUE TITLE
JSON Serializer plan of attack for v6

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2460]
Today we ilmerge json.net, this is the problems I see;

* We can't expose json.net types since we ilmerge with /internalize (if not we'll run into type clash issues)
* We wan't to switch to a more lightweight json lib in the core
* Adds  1mb to the size of the core

How about this, for v6

- [ ] Require serializer to be configured explicitly
- [ ] Move the json.net serializer to a separate repo
- [ ] Rename the serializer to JsonNetSerializer
- [ ] Add obsolete to guide users to the new nuget for json.net
- [ ] Add a more light weight json serializer to the core (eg. simple.json) as a .cs file

**Comment by johnsimons** [comment]
@andreasohlund please move this to requirements repo
