### ISSUE TITLE
Get rid of external container support

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2469]
Stop supporting multiple DI containers that users can chose (and even optionally pass their own instances). Use factory (method) pattern instead, where applicable to allow users to use whatever method they want to create instances of handlers etc. Make sure these factories get enough context information (IBus, other APIs) to be a viable replacement for current approach (where user can inject anything that is public in the core).

Related to #2199

**Comment by dbelcham** [comment]
@SzymonPobiega do you have any interest in pursuing this topic? It seems to me that multi container support is something that is well entrenched in our extensibility offerings.

**Comment by timbussmann** [comment]
I think https://github.com/Particular/PlatformDevelopment/issues/1090 replaces this issue?

**Comment by dbelcham** [comment]
Would seem that it has. Closing and deferring to the PlatDev issue for now.
