### ISSUE TITLE
Make endpointname mandatory

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2477]
So we can avoid issues like #2453

**Comment by johnsimons** [comment]
Anyone gave any thoughts on how to enforce this?
Do we go with something like:
```c#
var config = new BusConfiguration(endpointName);
```

**Comment by andreasohlund** [comment]
Doesn't feel discoverable but I don't have a better idea.

Do we have other things that are mandatory?

If we had that, how would we design it?

**Comment by johnsimons** [comment]
> Doesn't feel discoverable but I don't have a better idea.

What do you mean, if we make it part of the ctor of `BusConfiguration`, isn't that really in their faces?


> Do we have other things that are mandatory?

quite possible


> If we had that, how would we design it?

Maybe something like:
```c#
var config = new BusConfiguration(new RequiredSettings());
```

**Comment by andreasohlund** [comment]
> What do you mean, if we make it part of the ctor of BusConfiguration,
isn't that really in their faces?

Yes, I was just referring to the "magical string"

`var c = new BusConfiguration("yxz");`

but yes it's pretty obvious when they ready the api docs that they should
pass in the endpoint name


> var config = new BusConfiguration(new RequiredSettings());

Sounds reasonable

Since an error queue is required for non-sendonly endpoints should we
consider a Bus.Create(config,"error") ?

**Comment by danielmarbach** [comment]
I like the idea with `RequiredSettings` although this is not currently inline how other required things like for example the Persistence are chosen.

**Comment by johnsimons** [comment]
agree @danielmarbach 

What are the options?

**Comment by andreasohlund** [comment]
I did a quick spike on this (did some research for https://github.com/Particular/PlatformDevelopment/issues/621)

https://github.com/Particular/NServiceBus/commit/fa172a9aef0010de239abfe28ff90fdf108d5a61 (needs some obsoletes to be put back in)

it was pretty easy and talking about it with @SimonCropp we concluded that it was 2-3 hours of doco work to complete including the upgrade guide.

Would we consider this for v6? cc @Particular/nservicebus-maintainers @Particular/tf-v6-launch 

This would be a small step towards https://github.com/Particular/PlatformDevelopment/issues/621 as well.

**Comment by danielmarbach** [comment]
I'm fully game for that change. It also allows us to remove any magic associated to endpoint name determination. It is a good change and forces users to give meaningful endpoint names

**Comment by SzymonPobiega** [comment]
I am :+1:

**Comment by timbussmann** [comment]
:+1: 

also, passing it in as a parameter to `EndpointConfiguration` seems to be a way better approach than throwing at startup like missing persistence.

**Comment by mikeminutillo** [comment]
I am :+1:
I think this helps to make the Endpoint concept explicit rather than a rename of BusConfig. That is, it will drive users to think about Endpoints.

**Comment by dvdstelt** [comment]
How would I now name my endpoint in an NSBHost hosted scenario?

```
    public class EndpointConfig : IConfigureThisEndpoint, AsA_Server
    {
        public void Customize(EndpointConfiguration endpointConfiguration)
        {
            endpointConfiguration.EndpointName("Impossible"); <--- obsolete! now I HAVE to rename namespace or use attribute?
```

This should be validated upon starting the endpoint, not make it mandatory in the ctor.

**Comment by andreasohlund** [comment]
One of the following:

1. Change the namespace surrounding the endpoint config to your liking.
2. Use the `EndpointName("MyEndpoint")` attribute
3. Specify it on the commandline, `NServiceBus.Host.exe /endpointName:MyEndpoint`

Would any of the above work?

**Comment by andreasohlund** [comment]
>Would any of the above work?

And if not: Switch to self hosting  - http://docs.particular.net/nservicebus/hosting/windows-service#bootstrapping-nuget

**Comment by dvdstelt** [comment]
I understand the alternatives. My point is that we moved the name to ctor to make it more clear to people, whereas I think it has improved only a single scenario. There are other scenarios where this issue still exists.

**Comment by dvdstelt** [comment]
"explicit" should've been used in my last comment, instead of "clear"

**Comment by andreasohlund** [comment]
Since we're on the path of deprecating the NServiceBus.Host I'd say that's something we can live with?

**Comment by DavidBoike** [comment]
I would like to point out that 2 of the methods (namespace and attribute) are static, and the only one that is even a little dynamic is the command line, which means any sort of multi-tenant situation now must be handled by DevOps, and cannot be handled in code. There's no possible way to pull that value from a config file, for example.

**Comment by andreasohlund** [comment]
>which means any sort of multi-tenant situation now must be handled by DevOps

Agreed, that said this is an advance usage IMO so switching to self hosting seems reasonable?

**Comment by danielmarbach** [comment]
@andreasohlund @dvdstelt [This](https://github.com/Particular/NServiceBus.Host/pull/87) would solve it
