### ISSUE TITLE
InstallationSupport only enabled when Debugger.IsAttached

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#2486]
The following issue/confusion: https://github.com/Particular/NServiceBus.Azure/issues/181 was caused by the fact that InstallationSupport is only enabled when the debugger is attached

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Installation/InstallationSupport.cs#L22

This was a major gotcha for me, sean and the user (and took us 7 days to figure out collectively)... I would like to see the use of Debugger.IsAttached removed, so that the code base behaves consistently between debug and production behavior...

**Comment by andreasohlund** [comment]
Given the learning transport I'd say we should focus to kill the entire installation support instead?

**Comment by bording** [comment]
@andreasohlund What do you mean by "kill the entire installation support" ?

**Comment by andreasohlund** [comment]
I mean't to obsolete IWantToInstallSomething and guide users to use scripts
to setup infrastructure assets needed by the endpoint (tables, queues, etc)

**Comment by andreasohlund** [comment]
As of v6 installers are no longer enabled when the debugger is attached:

https://docs.particular.net/nservicebus/operations/installers#running-installers

@yvesgoeleven closing this issue
