### ISSUE TITLE
MSMQ connection strings are not validated

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2510]
MSMQ connections strings support the following settings:

```
deadLetter=true/false;
journal=true/false;
cacheSendConnection=true/false;
useTransactionalQueues=true/false;
timeToReachQueue=timespan
```

If the user enters invalid keys and or value we should throw a exception that states what is wrong.

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/13.
