### ISSUE TITLE
Error message point to PS cmdlet that is not present

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus#2519]
The core contain an error message that instruct the user to run a cmdlet that is not installed since it was moved out of the core.
```
NServiceBus performance counter for {0} is not set up correctly. Please run Install-NServiceBusPerformanceCounters cmdlet to rectify this problem.", counterName);
```

**Comment by gbiellem** [comment]
I need to update the doco prior to releasing the new PS MSI download.  Once that's out how about we advise that they download it instead

**Comment by johnsimons** [comment]
Sounds good @gbiellem, anything I can help with ?

**Comment by johnsimons** [comment]
@gbiellem it would be really nice to fix this for 5.2 release, what can we do?

**Comment by gbiellem** [comment]
@johnsimons 

I think the ps module is ready but feel free to test it.  

Outstanding:
- The installer doesn't currently have a theme consistent with the other products  (do we bother?)
- doco hasn't been updated. 
- need to modify the downloads page on public website once it's release to provide a link 
- Add it to the PI ?

Feel free to tackle any of these

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/NServiceBus/commit/01985d895a66a923f397a9c15a954dad6fe73b1a
