### ISSUE TITLE
Reply from finder results in invalid OriginatingSagaId header

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2525]
Run `When_reply_from_a_finder` and set a break point here https://github.com/Particular/NServiceBus/blob/a8f9b0036eb2f66e4cd3bb224ee2c3b1ab170e1d/src/NServiceBus.Core/Sagas/PopulateAutoCorrelationHeadersForRepliesBehavior.cs#L23

You will notice `saga.NotFound` is false so we enter and set invalid header ie `OriginatingSagaId` will be null.

So to fix we should fix the double negation and rename `saga.NotFound` to `saga.Found`, default it to false and set it to true when it is found

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/NServiceBus/commit/da25fed083a5384415e3f4dc1f26c18f7ebe8e71
