### ISSUE TITLE
re-apply "Firing callback on replies only"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2539]
So this commit https://github.com/Particular/NServiceBus/commit/c0d0ce67ef350e650a75b2284814a7398af88116 had to be locked at version 5 as part oft his commit https://github.com/Particular/NServiceBus/commit/78f545b6aee433c878f3c246f35551c71d06ad8e

Since version 4 still has a Send intent for return messages, we need to re-evaluate how to identify return message in below v5

**Comment by SimonCropp** [comment]
@andreasohlund want to pair on this?

**Comment by johnsimons** [comment]
@SimonCropp so does the current code break callbacks between v5 and v4 ?
Can you explain what the bug is?

**Comment by johnsimons** [comment]
@andreasohlund can you help @SimonCropp and I understand if there is actually a bug here or not ?

**Comment by johnsimons** [comment]
@andreasohlund ping, see previous comment

**Comment by johnsimons** [comment]
@andreasohlund closing this one, feel free to reopen it if you think is important
