### ISSUE TITLE
Identifying remote queue using IP instead of machine names

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2547]
We currently compare machine names to identify if the queue about to be created is in a remote machine or not, see https://github.com/Particular/NServiceBus/blob/33947a34659fbad5e9636873aefe7ab2a6077533/src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs#L35

Wouldn't it be better to identify if the machine is remote or not via:

``` c#
static bool? IsLocalIpAddress(string hostName)
{
    if (string.IsNullOrWhiteSpace(hostName))
    {
        return null;
    }
    try
    {
        var hostIPs = Dns.GetHostAddresses(hostName);
        var localIPs = Dns.GetHostAddresses(Dns.GetHostName());

        if (hostIPs.Any(hostIp => (IPAddress.IsLoopback(hostIp) || (localIPs.Contains(hostIp)))))
        {
            return true;
        }
    }
    catch
    {
        return null;
    }
    return false;
}
```

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/12.
