### ISSUE TITLE
Include validation in our config sections

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2549]
The .Net CLR allows for ConfigurationProperties in custom config sections to include validation.

I have already modified [SecondLevelRetriesConfig](https://github.com/Particular/NServiceBus/blob/33947a34659fbad5e9636873aefe7ab2a6077533/src/NServiceBus.Core/SecondLevelRetries/Config/SecondLevelRetriesConfig.cs#L17-L19) to take advantage of it.

This is a good way to standardise the validation and defaults across code only and config file.

**Comment by andreasohlund** [comment]
Since we're moving away from config sections in the core I don't see this becoming relevant
