### ISSUE TITLE
Common set of acceptance tests for saga persisters

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2550]
Extract the saga persister tests (mostly from RavenDB impl) to a common project just like container tests and use them for all saga persistence implementations.

A WIP pull is here https://github.com/Particular/NServiceBus/pull/2511

**Comment by timbussmann** [comment]
There is also an issue in pdev about this: https://github.com/Particular/PlatformDevelopment/issues/1123
Is it worth keeping this open @SzymonPobiega @Particular/nservicebus-maintainers ?

**Comment by SzymonPobiega** [comment]
@timbussmann nope. The PlatDev issue covers more than this I believe.
