### ISSUE TITLE
Add code API for error queue

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2554]
Proposed new public API:
```c#
var configuration = new BusConfiguration();
configuration.ErrorQueue("MyErrorQueue");
```

**Comment by SimonCropp** [comment]
@andreasohlund why dont we default to "error" if it is not defined? the same way we do for audits

**Comment by johnsimons** [comment]
@SimonCropp looking for the audit code only api, and I can't find it, can u point me to it?

**Comment by SimonCropp** [comment]
@johnsimons my mistake i thought we did have one :(

But i think the issue still stands. I would like to have a sensible default and have it configurable via code

**Comment by johnsimons** [comment]
What would be the proposed api ?

**Comment by johnsimons** [comment]
Should this be raised in requirements?

**Comment by SimonCropp** [comment]
```
var configuration = new BusConfiguration();
configuration.ErrorQueue("MyErrorQueue");
```

> Should this be raised in requirements?

Dont see why something this trivial should go through requirements

**Comment by johnsimons** [comment]
> Dont see why something this trivial should go through requirements

Famous last words ;)

**Comment by johnsimons** [comment]
I would raise this in requirements and quite possible it will be fast tracked.
But it would be nice to let others know what the plan is, specially since we already have a code only solution that works using `IProvideConfiguration<MessageForwardingInCaseOfFaultConfig>`.
I know that `IProvideConfiguration<T>` is not the best api, hence it would be nice to explore in the requirements repo this new alternative and what this means for all our usages of `IProvideConfiguration<T>`.

**Comment by SimonCropp** [comment]
@johnsimons there is already a requirements issue to track the larger change https://github.com/Particular/Requirements/issues/168

As for the error queue, and prob the audit queue as well, they are so commonly used they should be configurable by code no matter the outcome of that requirements issue.

**Comment by johnsimons** [comment]
@SimonCropp excellent, so it sounds like we can close this one and wait for the outcome of https://github.com/Particular/Requirements/issues/168, does that sound reasonable?

**Comment by SimonCropp** [comment]
@johnsimons no

> they are so commonly used they should be configurable by code no matter the outcome of that requirements issue.

**Comment by andreasohlund** [comment]
I'm +1 for adding `configuration.ErrorQueue("MyErrorQueue");` right away since it adds value for both us and our users.

**Comment by SimonCropp** [comment]
@andreasohlund what about a sensible default?

**Comment by andreasohlund** [comment]
I vote for `error`

**Comment by SimonCropp** [comment]
closing so we can focus on the larger code configuration issue
