### ISSUE TITLE
Allow transports to get name of the configured error queue

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2567]
Since transports use error queue to send messages which have invalid headers, it is required to pass the error queue name to the transport either when configuring or via the Init method. This is a potential breaking change if we go with Init.

**Comment by johnsimons** [comment]
This is related to #2463

@SimonCropp any ideas how we should make the contract more explicit ?

**Comment by SzymonPobiega** [comment]
in #2601 we discussion with @andreasohlund that instead of passing the queue name we should throw some specific exception in the transport receiver if we encountered a malformed message and the next behavior on the pipeline should take care of putting it in the error queue.

**Comment by andreasohlund** [comment]
Yes, so if we pull that off we don't need to make it available to the transports and they don't have to code for it which IMO greatly simplifies implementing a transport

**Comment by johnsimons** [comment]
@SzymonPobiega with all the refactoring u been doing has this been addressed ?

**Comment by SzymonPobiega** [comment]
@andreasohlund I think you're working on that area now, right?

**Comment by andreasohlund** [comment]
Yes, already fixed in https://github.com/Particular/NServiceBus/pull/2828
