### ISSUE TITLE
Detect if a callback has been set for bus.Send

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2596]
The current api, `IBus.Send().Register()` doesn't allow us to add headers/etc on the message to tell the server if there is a callback "waiting" for a potential reply since the `.Register` happens after the send has completed. This info will be needed in the future when we perform directory based routing using ServiceControl to make decisions like `

```
if IncomingMessage.HasCallbacks then 
    route to exact instance that sent the request
else 
   route to any endpoint instance
```

I propose that we move ahead with the new bus.Send api suggested in https://github.com/Particular/NServiceBus/issues/1730 and put a callback option there.

Something like this
```
var options = new SendOptions();

options.OnReply(r=>{...}); 

bus.Send(new MyRequest(),options)
```

Should we also consider moving the callback support out of the core to make it an explicit opt-in using `install-package NServiceBus.Callbacks` as described in https://github.com/Particular/NServiceBus/issues/2390 ?

All this could be added in v5.X + old api obsoleted with remove in v6.0

**Comment by andreasohlund** [comment]
Are we all good with splitting the callbacks out to a NServiceBus.Callbacks assembly and making it opt-in? (@udidahan?)

**Comment by udidahan** [comment]
@andreasohlund you mean in v6?

**Comment by andreasohlund** [comment]
Yes, v6

**Comment by udidahan** [comment]
OK then.

**Comment by johnsimons** [comment]
@andreasohlund how will this affect transports with callback queues ?

**Comment by andreasohlund** [comment]
> how will this affect transports with callback queues ?

In a positive way IMO. Right now they have to have them on to be safe by default. Now they can check if the "callbacks" feature is enabled and only then create the callback queue and start the callback receiver

**Comment by distantcam** [comment]
After discussing it with @andreasohlund we came up with the following API

    var options = new SendOptions();

    var replyTask = options.GetReplyTask().ContinueWith(t =>
    {
        // Do something with the reply
    });

    await bus.SendAsync(new Message(), options);

This clearly shows that there's a separation between the send completing, and a reply coming back.

This also allows the user to use the full `Task` system including checking for faults, continuing on a specific scheduler, etc.

**Comment by johnsimons** [comment]
What do u plan to expose on the t.result in continuewith ?

**Comment by danielmarbach** [comment]
From the code flow perspective it would be better to be able to do
something like that:



var options = new SendOptions();

var replyTask = options.GetReplyTask();

await bus.SendAsync(new Message(), options);

var response = await replyTask;

//continue here



@andreasohlund and I noted that somewhere in his sublime text two or three
weeks ago as a proposal. Thoughts?



*From:* Cameron MacFarland [mailto:notifications@github.com]
*Sent:* Dienstag, 10. März 2015 12:10
*To:* Particular/NServiceBus
*Cc:* Daniel Marbach
*Subject:* Re: [NServiceBus] Detect if a callback has been set for bus.Send
(#2596)



After discussing it with @andreasohlund <https://github.com/andreasohlund>
we came up with the following API

var options = new SendOptions();



var replyTask = options.GetReplyTask().ContinueWith(t =>

{

    // Do something with the reply

});



await bus.SendAsync(new Message(), options);

This clearly shows that there's a separation between the send completing,
and a reply coming back.

This also allows the user to use the full Task system including checking
for faults, continuing on a specific scheduler, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/Particular/NServiceBus/issues/2596#issuecomment-78034019>
.

**Comment by johnsimons** [comment]
@danielmarbach what would happened if user does something like:
```c#
var options = new SendOptions();

var replyTask = options.GetReplyTask();

await bus.SendAsync(new Message(), options);
await bus.SendAsync(new Message2(), options);
await bus.SendAsync(new Message3(), options);

var response = await replyTask;

//continue here
```

What is  the result ? Would that even work ?

**Comment by johnsimons** [comment]
I think we need to lock down this API so users cannot stuff it up.
I would prefer to have something like:
```c#
bus.SendAsync(new Message()).ContinueWith(t=> ...);
```
I don't think we need a `PublishAsync` ?

**Comment by andreasohlund** [comment]
The only 2 must haves for the api is:

1. We need to be able to set a header on the outgoing message indicating that there is a callback set (to enable our routing to adjust for that scenario)
2. It needs to be extendable so that the callbacks can reside in a separate assembly

**Comment by danielmarbach** [comment]
@johnsimons this can be handled by making the SendOptions GetReplyTask
throwing when it is called multiple times or even make it reusable
depending where we want to take this.



Another thing which can be achieved (because my proposed solution is more
composable):



var options1 = new SendOptions();

var options2 = new SendOptions();



var options3 = new SendOptions();





var replyTask1 = options1.GetReplyTask();

var replyTask2 = options1.GetReplyTask();

var replyTask3 = options1.GetReplyTask();





await bus.SendAsync(new Message(), options1);

await bus.SendAsync(new Message2(), options2);

await bus.SendAsync(new Message3(), options3);



var firstDoneTask = await Task.WhenAny(replyTask1, replyTask2, replyTask3);

var response firstDoneTask.Result;



*From:* John Simons [mailto:notifications@github.com]
*Sent:* Dienstag, 17. März 2015 01:43
*To:* Particular/NServiceBus
*Cc:* Daniel Marbach
*Subject:* Re: [NServiceBus] Detect if a callback has been set for bus.Send
(#2596)



@danielmarbach <https://github.com/danielmarbach> what would happened if
user does something like:

var options = new SendOptions();



var replyTask = options.GetReplyTask();



await bus.SendAsync(new Message(), options);

await bus.SendAsync(new Message2(), options);

await bus.SendAsync(new Message3(), options);



var response = await replyTask;



//continue here

What is the result ? Would that even work ?

—
Reply to this email directly or view it on GitHub
<https://github.com/Particular/NServiceBus/issues/2596#issuecomment-82006418>
.

**Comment by johnsimons** [comment]
At the moment all proposed api do not mention what the return value is, we currently support return an enum (int) and also a convoluted was to get to the messages array
I would like to propose as part of this change to remove the return enum and instead only support returning messages.
This would mean:
- Users get what they have always wanted in a more fluid api, RPC style calls;
- We can get rid of `bus.Return`, has that is not needed;

Thoughts?

**Comment by johnsimons** [comment]
> We need to be able to set a header on the outgoing message indicating that there is a callback set (to enable our routing to adjust for that scenario)

@andreasohlund is this another YAGNI ?

**Comment by distantcam** [comment]
Ok, what about this?

    var responseHandle = await bus.SendAsync(new Message()); // Returns immediately

    responseHandle.ReplyTask.ContinueWith(/* continuation */);

The reply task only completes when a reply is received. This solves the problem of multiple sends with the same option object and is a nicer API for the user.

Only downside is that there's a subtle implication that the send has completed because it has returned, when that's not actually true.

@johnsimons I had the return value being the value coming from the reply task. I believe that's how it currently works (the callback is given the result).

**Comment by johnsimons** [comment]
On a call with @distantcam we had another go at designing the api, here is what we came up with:
```c#
public async Task<IHttpActionResult> GetOrders()
{
	SendContext response = bus.Send(new Message());

	//response.ReplyTask.ContinueWith()...
	CompletionResult result = await response.ReplyTask;

	MyMessage msg = result.Messages[0]

	return Ok(msg);
}
```

**Comment by danielmarbach** [comment]
So SendAsync is gone?

Am Donnerstag, 19. März 2015 schrieb John Simons :

> On a call with @distantcam <https://github.com/distantcam> we had another
> go at designing the api, here is what we came up with:
>
> public async Task<IHttpActionResult> GetOrders()
> {
>     SendContext response = bus.Send(new Message());
>
>     //response.ReplyTask.ContinueWith()...
>     CompletionResult result = await response.ReplyTask;
>
>     MyMessage msg = result.Messages[0]
>
>     return Ok(msg);
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2596#issuecomment-83352927>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by johnsimons** [comment]
Yes @danielmarbach 
We think using a name like `SendAsync` could give the wrong impression (the sending is being performed in an async way which is not true).

**Comment by danielmarbach** [comment]
Why don't we add different methods?

Like Task SendAsync and Task<TResponse> SendWithResponseAsync()

It would be cool to have a oneliner :)

Am Donnerstag, 19. März 2015 schrieb John Simons :

> On a call with @distantcam <https://github.com/distantcam> we had another
> go at designing the api, here is what we came up with:
>
> public async Task<IHttpActionResult> GetOrders()
> {
>     SendContext response = bus.Send(new Message());
>
>     //response.ReplyTask.ContinueWith()...
>     CompletionResult result = await response.ReplyTask;
>
>     MyMessage msg = result.Messages[0]
>
>     return Ok(msg);
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2596#issuecomment-83352927>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by danielmarbach** [comment]
What about the future when we support async?

Am Donnerstag, 19. März 2015 schrieb Daniel Marbach :

> Why don't we add different methods?
>
> Like Task SendAsync and Task<TResponse> SendWithResponseAsync()
>
> It would be cool to have a oneliner :)
>
> Am Donnerstag, 19. März 2015 schrieb John Simons :
>
>> On a call with @distantcam <https://github.com/distantcam> we had
>> another go at designing the api, here is what we came up with:
>>
>> public async Task<IHttpActionResult> GetOrders()
>> {
>>     SendContext response = bus.Send(new Message());
>>
>>     //response.ReplyTask.ContinueWith()...
>>     CompletionResult result = await response.ReplyTask;
>>
>>     MyMessage msg = result.Messages[0]
>>
>>     return Ok(msg);
>> }
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Particular/NServiceBus/issues/2596#issuecomment-83352927>
>> .
>>
>
>
> --
>
> Daniel Marbach
>
> Solution Architect, Particular Software
>
> Email:  daniel.marbach@particular.net
> <javascript:_e(%7B%7D,'cvml','daniel.marbach@particular.net');>
>
> Web:    www.particular.net
> <http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>
>
>

-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by distantcam** [comment]
@danielmarbach The `SendWithResponseAsync()`, what's being awaited here? Is it the send or the reply? If an error occurs was it caused by the send, or the reply?

Given there are 2 different concepts here an API that distinguishes between them is better than an API that shoves everything into a single line because that would be cooler.

**Comment by danielmarbach** [comment]
Good point cameron! Because I'm not yet convinced about the proposals I'm
brainstorming

Am Donnerstag, 19. März 2015 schrieb Cameron MacFarland :

> @danielmarbach <https://github.com/danielmarbach> The
> SendWithResponseAsync(), what's being awaited here? Is it the send or the
> reply? If an error occurs was it caused by the send, or the reply?
>
> Given there are 2 different concepts here an API that distinguishes
> between them is better than an API that shoves everything into a single
> line because that would be cooler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2596#issuecomment-83368772>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by danielmarbach** [comment]
@distantcam I thought about it again. I changed my mind. We are a library/abstraction layer on top of the queues. Why do we need to bother users with Continuations in order to get the response. I think we can handle the continuation inside the library and give them back a task which can await the response. This reduces nesting of continuations and makes the code more readable which is a benefit:

````
interface IBus
{
	Task SendAsync(object message, SendContext context);
	
	Task<TResponse> SendAndAwaitResponseAsync<ResponseMessage>(object message, SendContext context);
}

public class SomeController : ApiController 
{
	public Task<IActionResult> Get() {
		var response = await bus.SendAndAwaitResponseAsync(message, new SendContext());
	}
}
`````

**Comment by andreasohlund** [comment]
>is this another YAGNI ?

No, when me and @udidahan was going through how routing would work when there are callbacks set we came to the conclusion that the routing needs to know if there are callbacks to make sure responses are routed to the correct instance. Happy to talk that through on a call if needed!

**Comment by johnsimons** [comment]
@danielmarbach I think we are pretty much aligned, the example you have provided is pretty much the same as what Cam and I came up with

**Comment by johnsimons** [comment]
@andreasohlund are you talking about the current routing implementation or a future version ?

**Comment by distantcam** [comment]
@johnsimons No the sample provided by @danielmarbach is not the same as mine.

Using @danielmarbach's example

    public class SomeController : ApiController 
    {
        public Task<IActionResult> Get() {
            try {
                var response = await bus.SendAndAwaitResponseAsync(message, new SendContext());
                return Ok(response);
            } catch (Exception ex) {
                // Is this exception because of the send, or the reply?
            }
        }
    }

The subtle distinction is that in my example the reply task is separate from the send method, as this is an important difference for the user.

Here's my take.

    public class SomeController : ApiController 
    {
        public Task<IActionResult> Get() {
            var sendResult = await bus.SendWithContextAsync(message, new SendContext())
                .ReportError("An error occurred during sending");
            var result = await sendResult.ReplyTask
                .ReportError("An error occurred during a response");
            return Ok(result);
        }
    }

    public static class TaskExtensions
    {
        public static Task<T> ReportError<T>(this Task<T> task, string errorMessage)
        {
            var tcs = new TaskCompletionSource<T> ();
		
            task.ContinueWith (ant =>
            {
                if (task.IsFaulted)
                {
                    Console.WriteLine(errorMessage + ant.Exception.InnerException);
                    tcs.SetException(ant.Exception.InnerException);
                }
                else if (ant.IsCanceled)
                    tcs.SetCanceled();
                else
                    tcs.SetResult(ant.Result);
            });
            return tcs.Task;
        }
    }

**Comment by andreasohlund** [comment]
@johnsimons the one we're building right now

**Comment by johnsimons** [comment]
Done as part of ##2689
