### ISSUE TITLE
log4net error when shutdown service (NServiceBus Host)

### ISSUE THREAD

**Issue by minhhut** [Particular/NServiceBus#2605]
I don't use log4net but when i shutdown i got exception about it. See picture

![image](https://cloud.githubusercontent.com/assets/656141/5502988/5544ed9c-8769-11e4-80f8-4c800b0b61ae.png)

**Comment by johnsimons** [comment]
@minhhut any update on this, what version of NserviceBus are u running?

**Comment by johnsimons** [comment]
@minhhut if you can please send us a repro of this issue, for now I am closing this as we do not have enough info to act on it.
