### ISSUE TITLE
When_customising_hostinfo.UsingNames uses internal class DeterministicGuid

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2606]
Because of that fact every project other than NServiceBus (which has `[InternalsVisibleTo]`) that references `AcceptanceTests.Sources` will not compile

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/NServiceBus/commit/0a346d58ea6852dfd0e16c7605cd409f96826b1c
