### ISSUE TITLE
Databus: What is this check used for?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2608]
Looking at the code with @SeanFeldman, the check `!context.Settings.TryGet("dataBusDefinitionType", out dataBusDefinitionType)` did not make sense to us:
Where is the `dataBusDefinitionType` being set? What is it used for?
We could not reference for where this key is being set.

**Code:**
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DataBus/DataBusFileBased.cs#L23

@andreasohlund ?

**Comment by johnsimons** [comment]
no idea, what is the bug?

**Comment by SeanFeldman** [comment]
`dataBusDefinitionType` setting is never set, but is used.

**Comment by johnsimons** [comment]
Cool, can u fix it?

**Comment by johnsimons** [comment]
Code removed in https://github.com/Particular/NServiceBus/commit/b79d175bf59428db16bdfdcab769def57d6e329a
