### ISSUE TITLE
The type of message is not included when logging a failure in processing a message

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2609]
Is it possible to include the full message type in the failed message logs?
## 

**Related post in GoogleGroups:**
https://groups.google.com/forum/#!topic/particularsoftware/FiF1RH0QqF8

**Comment by johnsimons** [comment]
It looks like this issue is resolved:
"Azure stores the exception in a different column"

**Comment by danielHalan** [comment]
Actually the issue is about the log record,
 [Info] "Failed to process message"

To include message type in that text string, ie. (and maybe even include the exception type)
 [Info] Failed to process message 'Ns.Commands.DoSomething' (xxxxxxxException)

**Comment by johnsimons** [comment]
Ok @danielHalan

**Comment by johnsimons** [comment]
@Particular/nservicebus thoughts ?

**Comment by SeanFeldman** [comment]
Agree with @danielHalan 
>[Info] Failed to process message 'Ns.Commands.DoSomething' (xxxxxxxException)

Is better than just 
>[Info] Failed to process message

**Comment by johnsimons** [comment]
Even thought it may make sense to include that extra info, I do not think it provides such added benefit.
In v5.1 we have added the capability of [subscribing to error notifications](http://docs.particular.net/nservicebus/subscribing-to-push-based-error-notifications), which IMO are a much better fit for this kind of diagnostics.
So based on that I am :-1: to do this change.

**Comment by danielHalan** [comment]
The benefit is when browsing the info-logs, and one want to map the errors occurring there to other sources of Error lists. also its a time saver when monitoring the logs output, and not needing to go to other sources if the errors are of expected message type.

**Comment by mauroservienti** [comment]
I'm with @danielHalan, the need should be seen from the DevOps point of view, maybe in a production environment, I'm not expecting anyone writing code to determine which message type is failing, I simply expect to look in the logs, or much better in the Windows EventLogs where I configured to log engine to write things to.

**Comment by indualagarsamy** [comment]
+1 with @SeanFeldman - sometimes we need to troubleshoot looking at the logs and it can be useful.

**Comment by janovesk** [comment]
This was a regular complaint from previous clients upgrading from earlier versions of Nservicebus which did include the messagetype. Ops guys lost the ability to quickly scan logs and access severity. I

**Comment by danielmarbach** [comment]
I'm with @johnsimons [comment](https://github.com/Particular/NServiceBus/issues/2609#issuecomment-71569273) we have the capability with the notifications.

Can we come up with a good ToString approach which provides small benefit?

@janovesk @mauroservienti @indualagarsamy anyone up for a PR?

**Comment by andreasohlund** [comment]
This is still a thing, @Particular/nservicebus-maintainers flagging this as candidate for next release

**Comment by timbussmann** [comment]
additional information is now logged as part of the `Exception.Data` collection. The default logger does log those values, other loggers might require additional configuration to make use of this information.
