### ISSUE TITLE
Probable incorrect assignment in ReleaseDateAttribute

### ISSUE THREAD

**Issue by rosieks** [Particular/NServiceBus#2610]
Hi, I just wanted to run NSB 4.6.8 on license that is valid to 16 September and I received license error. After little investigation I just noticed that ReleaseDateAttribute can have wrong assignment to original date.

    public ReleaseDateAttribute(string originalDate, string date)
    {
        this.OriginalDate = date; // is this correct???
        this.Date = date;
    }

**Comment by johnsimons** [comment]
@andreasohlund @SimonCropp how does this thing work?

**Comment by SimonCropp** [comment]
fixed by https://github.com/ParticularLabs/GitVersion/issues/347

**Comment by johnsimons** [comment]
@SimonCropp what version of gitversion has the fix?

**Comment by SimonCropp** [comment]
2.0.1. I am finalising the release now

**Comment by johnsimons** [comment]
cool, thanks
