### ISSUE TITLE
Connection strings for persisters

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#2611]
Currently core only supports connection string for transport. Persisters requires connection string as well. Would be good to be able to define all persisters connection strings within `connectionStrings` section

``` xml
  <connectionStrings>
    <add name="NServiceBus/Transport" connectionString="" />
    <add name="NServiceBus/Persistence/Saga" connectionString="" />
    <add name="NServiceBus/Persistence/Timeout" connectionString="" />
    <add name="NServiceBus/Persistence/Subscription" connectionString="" />
    <add name="NServiceBus/Persistence/Outbox" connectionString="" />
    <add name="NServiceBus/Persistence/GatewayDeduplication" connectionString="" />
  </connectionStrings>
```

By having this, users would need to have less configuration work if they don't override defaults and minimize amount of XML typing/configuration.

For Azure transport, it would be something like this:

``` xml
  <connectionStrings>
    <add name="NServiceBus/Transport" connectionString="UseDevelopmentStorage=true" />
    <add name="NServiceBus/Persistence/Saga" connectionString="UseDevelopmentStorage=true" />
    <add name="NServiceBus/Persistence/Timeout" connectionString="UseDevelopmentStorage=true" />
    <add name="NServiceBus/Persistence/Subscription" connectionString="UseDevelopmentStorage=true" />
  </connectionStrings>
```

instead of:

``` xml
  <configSections>
    <section name="AzureSubscriptionStorageConfig" type="NServiceBus.Config.AzureSubscriptionStorageConfig, NServiceBus.Azure" />
    <section name="AzureSagaPersisterConfig" type="NServiceBus.Config.AzureSagaPersisterConfig, NserviceBus.Azure" />
    <section name="AzureTimeoutPersisterConfig" type="NServiceBus.Config.AzureTimeoutPersisterConfig, NserviceBus.Azure" />
  <configSections>

  <connectionStrings>
    <add name="NServiceBus/Transport" connectionString="UseDevelopmentStorage=true" />
  </connectionStrings>

  <AzureSagaPersisterConfig ConnectionString="UseDevelopmentStorage=true" />
  <AzureTimeoutPersisterConfig ConnectionString="UseDevelopmentStorage=true" />
  <AzureSubscriptionStorageConfig ConnectionString="UseDevelopmentStorage=true" />
```

**Comment by johnsimons** [comment]
@SeanFeldman doesn't this change needs to be done in Azure? Not sure what to do in the core?

**Comment by SeanFeldman** [comment]
@johnsimons `NServiceBus/Transport` is not set by transport, so what's the rational for `NServiceBus/Persistence/*` to be set by transport? When persistence is required, it leads to each transport to set its own configs (example for Azure transport above).

**Comment by johnsimons** [comment]
sounds good @SeanFeldman, how do you propose to proceed?

I think raven and NH already do this kind of thing.

Will the interfaces have an explicit signature, eg:
```c#
Init(string connStr);
```

**Comment by yvesgoeleven** [comment]
We could obviously do this on a persister by persister basis, but the risk of getting misalignment over time is significant and confusing to the user imo. I would vote for consistent keys enforced by the feature in the core and then injected into the different implementations. I see no reason why the concept of a connectionstring for Sql would be different than for Raven or Azure storage

**Comment by andreasohlund** [comment]
Sounds good to me

**Comment by andreasohlund** [comment]
What's the status here?

From my perspective it seems like we're moving more towards a model where each persister provides its own api so this seems more like guidance.

>If a persister requires a connection string consider using the naming convention `NServiceBus/Persistence/{TypeOfStorage}` ?

Ie nothing we can do in the core other than documenting this guidance?

**Comment by dbelcham** [comment]
What/where are you thinking we should document this @andreasohlund ?

**Comment by timbussmann** [comment]
>  but the risk of getting misalignment over time is significant and confusing to the user imo.

given that we don't expect users to regularly switch persistence, I don't think that risk is something which is worth to implement a generalization in the core. I'm with @andreasohlund here. Since we don't have any guidance on this, not sure why we can't just close this?

**Comment by andreasohlund** [comment]
>What/where are you thinking we should document this

Perhaps we could start with something in?
https://github.com/Particular/PlatformDevelopment/tree/master/designprinciples/nservicebus

But ideally it should be public so perhaps there is a better place? docs?

**Comment by dbelcham** [comment]
@andreasohlund sounds more like a design principle ("If you have a config value it's name should follow this pattern") than it does doco. Looking at the files in PlatDev I'm not sure which one should hold this info though. Possibly [component naming](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-naming.md) although one could argue that the file would need to be renamed to "naming"

**Comment by andreasohlund** [comment]
> Looking at the files in PlatDev I'm not sure which one should hold this info though. Possibly component naming although one could argue that the file would need to be renamed to "naming"

Lets go with that for now? (cc @Particular/nservicebus-maintainers )

**Comment by andreasohlund** [comment]
PR is merged, closing this
