### ISSUE TITLE
Send only endpoints can't publish messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2612]
Caused in 5.1 by this change:

https://github.com/Particular/NServiceBus/commit/411d1b32cdf126e0ac61e783129085f783c9b3c7

we need to check and use persistence if it has been enabled even though the endpoint is send only.

**Comment by johnsimons** [comment]
@andreasohlund what do u mean by:
> we need to check and use persistence if it has been enabled even though the endpoint is send only

what are u proposing ?

**Comment by andreasohlund** [comment]
Just saying that we should allow storages to be configured for send only endpoints. This allows a user to configure a subscription storage so that bus.Publish can work.

Makes sense?

**Comment by ramonsmits** [comment]
So how should such a publisher receive registrations without an incoming queue? Is the thought that the 'senders' are part of some sort of service where another isolated process is responsible for processing subscriptions?

**Comment by andreasohlund** [comment]
Yes either that or read the subscribers from a central place. Also for brokers you don't need receive capabilities in order to publish since the broker handled the subscriptions
