### ISSUE TITLE
Remove generic argument from ISendOnlyBus.Publish<T>(T message)

### ISSUE THREAD

**Issue by iskandersierra** [Particular/NServiceBus#2616]
There is no need for the T argument to be there. In fact the Send counterpart do not have it, as I believe it shouldn't. For compatibility reasons a new Publish(object message) should be added instead of modifying the current one.
Seems trivial but I got confused by the signature because I though the static type of the variable was used for something and because I'm using a polling mechanism for publishing all events in my store, the event variable is just IEvent, so I had to look to UnicastBus.Publish<T> code to make sure only the runtime type of the message were used.

**Comment by johnsimons** [comment]
:+1: 

@Particular/nservicebus thoughts ?

**Comment by SimonCropp** [comment]
@johnsimons looks reasonable. So assign to v6?
