### ISSUE TITLE
Deprecate IManageUnitsOfWork

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2618]
And guide users to the pipeline instead since that is a better abstraction

**Comment by andreasohlund** [comment]
At least for UOW I'd say the pipeline is better since it allows a more natural programming model with `using` etc. and we should push users this way. Just look at the UoW for NH back in NH 4.5

https://github.com/Particular/NServiceBus.NHibernate/blob/support-4.5/src/NServiceBus.NHibernate/UnitOfWorkManager.cs#L14

Thoughts?

**Comment by SimonCropp** [comment]
@andreasohlund well it depends if u see UOW as

 * a rarely used extensibility/infrastructure api; or
 * a regularly used business api

perhaps do a poll on the group?

**Comment by johnsimons** [comment]
@andreasohlund I would still have this interface

**Comment by andreasohlund** [comment]
> I would still have this interface

So pushing the users down a tricky path in terms of coding is not an issue in your opinion?

I might be biased but getting the UoW setup correctly has always been black magic. Just look at this guy's blog post http://andreasohlund.net/2011/11/22/a-nservicebus-unit-of-work-implementation-for-ravendb/ :)

**Comment by ramonsmits** [comment]
I have often used the UoW to create a DbContect and an ISession . Also used UoW in the past for logging different thread contexts and for creating session security tokens used to communicate with external systems. Just to apply DRY for a lot of infrastructural code.

I think people wouldn't mind migrating their code if it gets less error prone with less lines of code.

How would the pipeline work? It should not be difficult to create a UoW implementation based on the pipeline then.

**Comment by indualagarsamy** [comment]
With the pipeline isn't this way better now, especially with the using block that the users can wrap?
Having the need for a Begin and End that the `IManageUnitsOfWork` interface imposes is counterproductive? @johnsimons - what uses do you see for keeping the IManageUnitsOfWork? Thoughts? My vote is for deprecating the IManageUnitsOfWork

**Comment by johnsimons** [comment]
@andreasohlund I am :+1: to remove the current UoW interface as long as we replace it with a better abstraction that still allows a user to implement the UoW pattern in a single class.

At the moment pointing the users to just use the raw pipeline is IMO making the developers task a lot harder.

So can you propose a new API that  abstracts away the complexity of the pipeline and makes developers write a UoW a piece of cake ?

**Comment by johnsimons** [comment]
@andreasohlund what is the plan of attack for this ? Do we postpone ?

**Comment by andreasohlund** [comment]
It's still on my radar, I'll try to get to it

**Comment by johnsimons** [comment]
@andreasohlund can we postpone the fixing of `IManageUnitsOfWork` to v7 timeline ?

**Comment by andreasohlund** [comment]
Let's leave it alone for now, removing milestone

**Comment by kijanawoodard** [comment]
FWIW, we just ran into issues where we suspect ordering issues with multiple IManageUnitsOfWork implementations.

The code was doing this: http://andreasohlund.net/2010/03/25/thread-static-caching-in-nservicebus/
Switched to: http://docs.particular.net/samples/unit-of-work/using-childcontainers/

The pipeline method
1. Makes more sense.
2. Is less "magic"
3. Reduced duplicated IoC config code across the project

**Comment by andreasohlund** [comment]
Closing in favor of https://github.com/Particular/NServiceBus/issues/4298
