### ISSUE TITLE
Obsolete the MasterNode concept and move it to the external distributor

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2620]
Since its a distributor only concept

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Distributor/MasterNode/MasterNodeConfig.cs#L8

**Comment by johnsimons** [comment]
@SzymonPobiega are you addressing this in one of your PRs ?

**Comment by SzymonPobiega** [comment]
@johnsimons I want to. I think this concept should be replaced by a concept of a physical public address.

**Comment by SzymonPobiega** [comment]
We're retiring the distributor in V6, no longer relevant.
