### ISSUE TITLE
Request: BusConfiguration.AddAssembly

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus#2624]
I am very particular about what assemblies I let NServicebus scan because I've run into conflicts before with 3rd party assemblies.  However I just came across an issue where I want a dependency of my project to be able to add itself into the scannedTypes list WITHOUT replacing whats already been scanned.

I am hesitant to implement IWantToRunWhenConfigurationIsComplete in my dependency because I don't want the users to have to remember to scan my assembly is they are using AllAssembles.Matching logic too.  Also my dependency is injecting things into the NServicebus container which won't work at that point.

My integration class is here https://github.com/volak/Aggregates.NET/blob/master/src/Aggregates.NET/Integrations/NServicebus.cs

It runs as an extension method off BusConfiguration to register internal types into NServicebus.

And I have 2 message types inside, Accept and Reject which I need to inject into the BusConfiguration's scannedTypes list.  So I would either need a config.AddTypes or config.AddAssembly method on BusConfiguration.

While investigating this issue it seems like this wouldn't be too hard to implement, I can even do a PR and tests if wanted.

**Comment by volak** [comment]
Right after submitting that I had a thought, this kind of change would introduce an order of operations issue.  For instance this would work

```
config.AssembliesToScan( AllAssemblies.Matching() );
config.AddAssembly( typeof().Assembly )
```

Whereas this would not

```
config.AddAssembly( typeof().Assembly )
config.AssembliesToScan( AllAssemblies.Matching() )
```

A better solution would queue up a list of assemblies to scan and wait to populate scannedTypes until after IConfigureThisEndpoint is finished

**Comment by johnsimons** [comment]
@volak 
So in summary, you would like the api to be additive, right ?

I'm :+1: 

@Particular/nservicebus thoughts ?

**Comment by volak** [comment]
Yes - short and sweet :+1:

**Comment by johnsimons** [comment]
@Particular/nservicebus thoughts ?

**Comment by SimonCropp** [comment]
@volak is the only thing you want to pick up in the other assembly `IWantToRunWhenConfigurationIsComplete`?

**Comment by volak** [comment]
@SimonCropp No, actually I don't want to implement `IWantToRunWhenConfigurationIsComplete` because when setting up `AllAssemblies.Matching` it would be better to not have to include my assembly's name.
It would make more sense for my library to add itself into my client's assembly list for maximum compatibility.
Problem is by calling `Busconfiguration.AddTypes` the existing types are cleared

**Comment by johnsimons** [comment]
My proposal is to add the following api:
```c#
public void AddAssemblies(params Assembly[] assemblies);
public void AddTypes(params Type[] types);
```
This would be all additive.

The question  then is, should the existing api be obsolete ?

**Comment by danielmarbach** [comment]
This is fixed for next release as part of https://github.com/Particular/NServiceBus/pull/2670
