### ISSUE TITLE
Exception Data property is ignored when setting exception headers

### ISSUE THREAD

**Issue by davidsavagejr** [Particular/NServiceBus#2630]
When setting the exception headers for a handled exception, the Data property is ignored.  Adding these to the headers allows for the attaching of useful data at the time the exception is thrown and saves time trying to track it down in a log file.

For example, in a Saga, I may have been sent something "bad" and I need to throw/abort the process - but I want to include data elements on the exception to help solve the issue; rather than having to string.format.

**Comment by SeanFeldman** [comment]
Hi @davidsavagejr, 
Could you please sign our [Contributor License Agreement (CLA)](http://www.particular.net/contributors-license-agreement-consent)? 
Thank you.

**Comment by davidsavagejr** [comment]
@SeanFeldman I might be missing a step but I've signed it ~3 times now.  Did it register?

**Comment by SeanFeldman** [comment]
@davidsavagejr Thank you, it's registered now (can see it) and apology for inconvenience :)
