### ISSUE TITLE
Assembly filtering is not consistent

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2632]
Framework assemblies (.NET, Enterprise Library) are [filtered out](https://github.com/Particular/NServiceBus/blob/83ddf0d9b2bb6ab791ec55b44b9759c603a355ad/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L164) when scanning assembly directory but are not filtered out when scanning assemblies already loaded into the app domain.

**Comment by johnsimons** [comment]
Duplicate https://github.com/Particular/NServiceBus/issues/2572#issuecomment-63736350
