### ISSUE TITLE
Acceptance tests fail to nuget restore because filename too long

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#2633]
Nuget restore cannot restore the acceptence test sources for repository NServiceBus.AzureServiceBus, and acceptencetests source 5.2 beta1, because the resulting filenames are to long. The basepath on my machine is...

C:\github.org\nsb\NServiceBus.AzureServiceBus\src\packages\NServiceBus.AcceptanceTests.Sources.5.2.0-beta0001\content\App_Packages\NSB.AcceptanceTests.5.2.0-beta0001

I worked around the issue for now by reverting back to 5.1.0, but we should figure out a consistently shorter convention for these paths as we're flirting with the max file length limits, even on the build server, the basepath is:

C:\BuildAgent\work\9e81da84cea5f13f\src\packages\NServiceBus.AcceptanceTests.Sources.5.2.0-beta0001\content\App_Packages\NSB.AcceptanceTests.5.2.0-beta0001

Which is only a few characters shorter than on my machine...

**Comment by yvesgoeleven** [comment]
PS: it's a nuget restore because I'm moving code from azure repo to azureservicebus repo, same issue would happen on install

**Comment by synhershko** [comment]
You mean the entire path is too long? if so this is an issue to raise with nuget

**Comment by johnsimons** [comment]
@yvesgoeleven I think this is mostly occurring because you are using the beta package.
We already follow a convention for source only packages.
