### ISSUE TITLE
Make the IncomingContext constructor public to help with unit testing behaviors

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2635]
At the moment, users who want to unit test their behavior code can't because the constructor of the IncomingContext is internal, whereas OutgoingContext is not.

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Contexts/IncomingContext.cs#L12

**Comment by indualagarsamy** [comment]
@Particular/engineers - any objections on if I make the constructor public?

**Comment by andreasohlund** [comment]
No objections

**Comment by johnsimons** [comment]
I think we have already done this in the PR we are working on

**Comment by indualagarsamy** [comment]
@johnsimons - which PR? How long before it gets merged? Or can I just make this change in develop ?
