### ISSUE TITLE
Do we support non generic Sagas?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2637]
As part of merging #2613, I have noticed that we do not support non generic sagas, or in other words, we do not support someone creating a saga that instead of deriving from `Saga<T>` they derive from just `Saga`.

The code that will cause an exception is [here](https://github.com/Particular/NServiceBus/blob/6f7a1ff5bc685159484c1f8837d1c400cc1266ae/src/NServiceBus.Core/Sagas/TypeBasedSagaMetaModel.cs#L58), as you can see we assume that the saga that we are about to register has a generic argument of type `IContainSagaData` (this assumption is fine for sagas that derive from `Saga<T>` but it will fail for sagas that only implement `Saga`).

@Particular/nservicebus 
Is this something we should support?

**Comment by SeanFeldman** [comment]
What would be a scenario for using `Saga` w/o data? Usually Saga is introduced when you need a "memory effect" which would be `ContainSagaData`.

**Comment by SimonCropp** [comment]
i see no need for it

**Comment by johnsimons** [comment]
@SeanFeldman it is still fine to use just `Saga` and still save data, the only difference is that the "data" is not typed

**Comment by johnsimons** [comment]
@SimonCropp so should we handle this more gracefully? At the moment blows up :disappointed:

**Comment by andreasohlund** [comment]
Throwing a better ex seems resonable.

Do we even need the non generic type?

**Comment by johnsimons** [comment]
> Do we even need the non generic type?

Yes



> Throwing a better ex seems resonable.

agree, i'll look into it

**Comment by andreasohlund** [comment]
Ok, I would change the classification from `Bug` to `Improvement` though

**Comment by johnsimons** [comment]
A better exception has been added
