### ISSUE TITLE
Scheduler with scale-out

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#2639]
## Who's affected

- Anyone who's using Scheduler API and wants to scale-out

## Symptoms 

- Scheduled tasks are not executed

## Steps to reproduce
When scheduler used to schedule a task in an endpoint that is scaled-out to several instances, tasks will not guaranteed to be executed due to Scheduler API in-memory implementation.

## Related
https://github.com/Particular/Requirements/issues/188

**Comment by SeanFeldman** [comment]
@Particular/engineers please provide feedback on how critical it is or not

**Comment by johnsimons** [comment]
IMO this is kind of a critical issue since we are consuming the message from the queue and not executing the handler, it feels like message loss to me.

@andreasohlund thoughts ?

**Comment by andreasohlund** [comment]
I'd say this is "message loss" since a task not executing might result in messages not beeing sent /business logic not executed. So +1 for critical.

**Comment by SeanFeldman** [comment]
Question from https://github.com/Particular/NServiceBus/commit/d08e6596ffa3606d4bbe0076ff01e9814d4b691b#commitcomment-9525024: is this a hotfix or a minor release?

**Comment by andreasohlund** [comment]
@SeanFeldman since we've announced the limitations of the scheduler can we close this one?
