### ISSUE TITLE
StorageDrivenPublisher: GetMessageMetadata fail to get a type

### ISSUE THREAD

**Issue by ydchome** [Particular/NServiceBus#2643]
In StorageDrivenPublisher, it gets the message metadata using the event type's FullName, instead of AssemblyQualifiedName. It causes internal implementation of GetMessageMetadata fail to get a type via using type name without assembly qualified. There is another overload method: MessageMetadata GetMessageMetadata(Type messageType) in MessageMetadataRegistry. The following code shows that it has already know about the type, it can just pass in type, instead of type name and get back type based on the name. It can optimize for performance.  

            var eventTypesToPublish = MessageMetadataRegistry.GetMessageMetadata(publishOptions.EventType.FullName)
                .MessageHierarchy
                .Distinct()
                .ToList();

In my application, it fails to get a type based on partial type name, if change to assembly qualified name or type, it just works fine.

**Comment by johnsimons** [comment]
@ydchome how do I reproduce this issue?

**Comment by johnsimons** [comment]
@ydchome What version of NServiceBus are you on?

**Comment by ydchome** [comment]
The version of NServiceBus is 5.1.2. My application is WCF application and host on IIS, I test the change in test environment, it works as above described and can be reproduced.And I think it is hard to setup a external environment and reproduce it.

I check the doc of Type.GetType ( https://msdn.microsoft.com/en-us/library/w3f99sx1(v=vs.110).aspx ), it said "The assembly-qualified name of the type to get. See AssemblyQualifiedName. If the type is in the currently executing assembly or in Mscorlib.dll, it is sufficient to supply the type name qualified by its namespace."

For some reason, my app's assembly jump into NServicebus assembly, Type.GetType does't like to look at my app's assembly in current AppDomain.

**Comment by johnsimons** [comment]
@ydchome having a hard time understanding all this moving parts.

So are you saying that when your endpoint receives a message, somewhere down in `MessageMetadataRegistry` an exception is thrown?

**Comment by SimonCropp** [comment]
@ydchome specifically can you provide an exception stack trace

Also it would be much easier to look into this if you could provide a way to reproduce it. Perhaps modify one of the samples to match your scenario? eg this one http://docs.particular.net/samples/web/asp-mvc-application/

**Comment by johnsimons** [comment]
@ydchome if you any extra info that helps us reproduce this issue let us know and we will reopen the issue
