### ISSUE TITLE
Create a unit test suite for our serializer api

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2652]
This suite would:

1. Help when building/maintaining serializers
2. Document the minimum set of features that we require a serializer to support (eg. `List<T>`)

This suite would be distributed as a source only package

**Comment by andreasohlund** [comment]
@hmemcpy would we say that the work you're doing is covering this? or is there still value in a separate unit tests suit as well?

**Comment by hmemcpy** [comment]
@andreasohlund yes, I'm working on it as part of the serializer backwards-compatibility suite, in fact, existing xml serializer tests will be executed as part of it.

**Comment by andreasohlund** [comment]
So close this once when your done?

**Comment by hmemcpy** [comment]
Closing. Implemented in https://github.com/Particular/ProductionTests/issues/14
