### ISSUE TITLE
Change signature of IMutateOutgoingTransportMessages.MutateOutgoing

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2668]
Currently the signature is:

``` c#
void MutateOutgoing(LogicalMessage logicalMessage, TransportMessage transportMessage);
```

This currently allows for the user to do some really weird things:

``` c#
public void MutateOutgoing(LogicalMessage logicalMessage, TransportMessage transportMessage)
{
    logicalMessage.Headers["Boo"] = "Foo";
    logicalMessage.UpdateMessageInstance(new object());
    // ...
}
```

As you can see it is possible to mutate the state of `logicalMessage`, even though it does not makes sense.

Also, it is not clear that `logicalMessage` refers to the incoming message and `transportMessage` is the message going out.

I would prefer to have something like (not c#):

```
body, headers MutateOutgoing(IncomingMessage)
```

The `IncomingMessage` would be an immutable type.

**Comment by johnsimons** [comment]
@Particular/nservicebus thoughts ?

**Comment by danielmarbach** [comment]
Here is my current thought:

When we take handler context into consideration, some weirdness around mutators and the plans to change the transport seam we need to align where we want to be going. Let's setup a call

**Comment by andreasohlund** [comment]
@SimonCropp covered by your api update for v6? #2839

**Comment by andreasohlund** [comment]
v6 now has a stricter api with a [context parameter ](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageContext.cs)that only gives access to things the users should use.
