### ISSUE TITLE
Wait() 

### ISSUE THREAD

**Issue by Thorium** [Particular/NServiceBus#2674]
If you call .Wait() in NServiceBus event handler, there is a possibility to deadlock / timeout (forever-wait).

The reason is that if async-await-operation happen to change the thread (which happen often under heavy load), the new thread seem not to get the (DTC) transaction that NServiceBus is using. This is because NServiceBus transactions are not having TransactionScopeAsyncFlowOption.Enabled which is new .NET 4.5.1 option.

Now, if you have e.g. multiple inserts to the same database, without the transaction the database can't figure out that these requests comes from the same source. While the work excecuted in the thread 1 will .Wait() for thread 2 to complete, the thread 2 (without transaction) waits the thread 1 to release its lock and complete its transaction.

![Example](http://i.imgur.com/hMIFIom.jpg)

**Comment by johnsimons** [comment]
@Thorium thanks for bringing this issue to our attention.
We will consider upgrading to 4.5.1 as part of v6.

**Comment by distantcam** [comment]
@Thorium Is it possible for you to not use tasks? That way you don't need to wait for anything.

**Comment by Thorium** [comment]
The whole system is based on async operations (hundreds of methods) and now (afterwards) we have taken NServiceBus into use to get benefits of queue based systems: wrap some of the methods to NSB-handlers. So no, it is not a real possibility, would need major refactoring.

I don't quite like the implementation of async-await in C# (as e.g. reactive extensions and F# have better approaches), but it seems that async-await will be the future of C# anyways.

**Comment by johnsimons** [comment]
@Thorium we are looking at fixing this issue as part of the next major release (v6)

**Comment by johnsimons** [comment]
@Thorium I'm trying to replicate this issue and having a bit of difficulty getting the the deadlock or timeout situation you mention, any hints how to reproduce it ?

Also, just to make sure, you have experienced this issue ?

**Comment by johnsimons** [comment]
@Thorium I have uploaded my attempt at repro this issue to https://github.com/johnsimons/Issue_2674, let me know where I am going wrong :disappointed:

**Comment by Thorium** [comment]
See the description johnsimons/Issue_2674#1

**Comment by johnsimons** [comment]
@andreasohlund are we going to clr v4.5.1 in v6 timeline, or postpone ?

**Comment by andreasohlund** [comment]
v6 will be at least 4.5.1
