### ISSUE TITLE
Message handlers are stateful

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2680]
Detected while working on Handler context

	public class Handler : IHandleMessages<MyMessage>, IHandleMessages<AnotherMessage>, IHandleMessages<IMessage>
	{
        public void Handle(MyMessage message)
        {
        }

        public void Handle(AnotherMessage message)
        {
        }

        public void Handle(IMessage message)
        {
        }
    }

When `MyMessage` arrives the core treats this handler as one handler. So a new instance of `Handler` is created and two methods are invoked (first `Handle(MyMessage)` and then `Handle(IMessage)`). I would argue this is a bug. Because a message handler should be stateless. Therefore I see the class above as three message handlers.

Should we change that for the handler context branch. If yes do we change it only for the new APIs or also for the old ones (which would imply a behavior breaking change). If yes what is the impact on sagas? 

    	public class MySaga: Saga<State>, IHandleMessages<MyMessage>, IHandleMessages<AnotherMessage>, IHandleMessages<IMessage>
	{
        public void Handle(MyMessage message)
        {
        }

        public void Handle(AnotherMessage message)
        {
        }

        public void Handle(IMessage message)
        {
        }
    }

@Particular/nservicebus thoughts?

**Comment by andreasohlund** [comment]
+1 for fixing this as a bug in v6

It shouldn't affect sagas since they by definition store their state in the saga data

**Comment by johnsimons** [comment]
@danielmarbach I agree with "message handler should be stateless", however I'm not too sure if users are actually taking advantage of this "feature" for some smart reasons that we haven't thought about yet.
Should we consider polling the forum and ask, before taking this away ?

**Comment by danielmarbach** [comment]
Handlercontext changes that behavior already. Based on what/how we educate
people I'd say handlers must be stateless

-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by danielmarbach** [comment]
@timbussmann you ported my changes to latest V6. Can you verify and close this one if no longer necessary?

**Comment by timbussmann** [comment]
tested current develop with the follow behavior:

using this messages:

```
MyMessage : IMyMessage { ... }
IMyMessage : IMessage { ... }
```

a handler which implements IHandleMessages for every three types (MyMessage, IMyMessage and IMessage) invokes on the same object:
* on MyMessage: Handle(MyMessage) and Handle(IMessage)
* on IMyMessage: Handle(IMyMessage), Handle (MyMessage) and Handle(IMessage)

**Comment by johnsimons** [comment]
How does this work in previous versions ?

**Comment by danielmarbach** [comment]
They are stateful in V5, as they still are now

**Comment by johnsimons** [comment]
I wonder if it would just be easier to have an abstract `HandleMessage<T>` inssead of interface to enforce this more explicitly :wink:

**Comment by SzymonPobiega** [comment]
@johnsimons I :heart: it!

**Comment by danielmarbach** [comment]
@johnsimons this would require us to introduce a new concept for sagas (at least treat them differently). I think we all agree that this wouldn't hurt at all but I have a hunch the impact of that at the current stage is not really big. So I'd vote for not doing it.

**Comment by johnsimons** [comment]
@danielmarbach I am not suggesting doing it right now, all I am saying is, if we are proposing to change the statefulness of handlers, we may as well do it properly.
So if I understand you, we should just not do any of this right now, and re-evaluate it later after v6 ?

**Comment by danielmarbach** [comment]
@johnsimons I think we should pull handlers out from the container for each entry returned from `MessageHandlerRegistry` which makes them stateless but nothing more. It is a trivial change.

**Comment by johnsimons** [comment]
It is trivial, but a behavior change none the less from previous versions.
Hence the reason I raised the question if we should do it more explicitly as part of the API, to comunicate it better to the api users

**Comment by johnsimons** [comment]
@danielmarbach does it hurt us if we don't do this right now ?

**Comment by danielmarbach** [comment]
In the discussions for HandlerContext we decided to do it as part of
handler context in V6

**Comment by SzymonPobiega** [comment]
Did we get any customer-raised issues related to that? If now, I would vote for doing it properly (abstract class) in vNext. 

I don't see a difference in terms of complexity of customer communication between 
 * invoking the container for each entry
 * adding an abstract class

Also, we can introduce an abstract class in V6 (purely as syntactic sugar) and remove the interface in V7, giving users some time to get used to the new approach.

**Comment by timbussmann** [comment]
> Also, we can introduce an abstract class in V6 (purely as syntactic sugar) and remove the interface in V7, giving users some time to get used to the new approach.

sounds like a sepparate issue then?

**Comment by timbussmann** [comment]
> I think we should pull handlers out from the container for each entry returned from MessageHandlerRegistry which makes them stateless but nothing more. It is a trivial change.

we actually already do that but handlers are registered in UnitOfWorkScope.

Is there any reason against changing that to InstancePerCall? The impact on sagas is a bit obscure, but the described scenarios on the issue don't work on any of those scopes with the InMemoryPersister, not sure about other saga persistence options though.

**Comment by timbussmann** [comment]
just checked with v5:
* v5 supports handling the same message by polymorphic handle methods on InMemory, Raven and NHibernate persistence.
* v6 InMemoryPersistence (no other persistence available yet) throws on the same scenario because it doesn't seem to allow saving the saga multiple times. By changing it to `InstancePerCall` the InMemoryPersister throws an concurrency exception.

**Comment by timbussmann** [comment]
can we close this with "won't fix"? @danielmarbach
