### ISSUE TITLE
NServiceBus not picking up response message in MSMQ

### ISSUE THREAD

**Issue by mastrauckas** [Particular/NServiceBus#2682]
I’m having an issue with NServiceBus and MSMQ in my QA environment.    This same procedure works just fine on DEV boxes and Dev environment.    Explain exactly what it’s doing.

I have a webpage that is using SignalR and NServiceBus.  
1.	A user clicks a button in the client web browser.
2.	Usng SignalR a message is sent from the client web browser to the web server.
3.	The SignalR Hub on the web server picks up the message and using NServiceBus bus.Send() sends a request message to NServiceBus distributor.
4.	NServiceBus distributor sends the message to an NServiceBus worker. 
5. The worker process picks up the request message and sends a response message back to the web service using bus.Reply().
6.	NServiceBus handler on the web server picks it up the response message off MSMQ and gives it to SignalR.
7.	SignalR sends it back to the client browser which shows a message.

All this works just fine in our DEV environment.  The DEV environment is setup exactly the same as QA, using the same distributor/worker and configs.  

**This is what we’re noticing in our QA environment:**
1. A user clicks a button in the client web browser.
2. Usng SignalR a message is sent from the client web browser to the web server.
3. The SignalR Hub on the web server picks up the message and using NServiceBus bus.Send() sends a request message to NServiceBus distributor.
4. NServiceBus distributor sends the message to an NServiceBus worker. 
5. The worker process picks up the request message and sends a response message back to the web service using bus.Reply().
6. ****This is where everything stops working****   The response message will show up in MSMQ and will appear stuck.  It will stay in there for hours.  The only way NServiceBus will pick up the message is by recycling the app pool in IIS. 
7. After recycling the app pool it will process the messages in MSMQ but any new ones will have the exact same issue.

Now both environments appear to be exactly the same including the web.config.    When looking at NServiceBus logging this is what I notice are different in the QA environment.

Here are the logs from QA environment that appear different in QA than DEV after recycling IIS pool to get the response message in MSMQ to processes: 

****Beginning QA log entries.****

Stopping 1/1 NServiceBus.SecondLevelRetries.SecondLevelRetriesProcessor, NServiceBus.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c satellite

Stopped NServiceBus.Distributor.MSMQ.ReadyMessages.ReadyMessageSender, NServiceBus.Distributor.MSMQ, Version=4.4.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c.

Stopped NServiceBus.Unicast.Subscriptions.MessageDrivenSubscriptions.StorageInitializer, NServiceBus.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c.

Stopped NServiceBus.Distributor.ReadyMessages.ReadyMessageSender, NServiceBus.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c.

All IWantToRunAtStartup.Start should have completed now.

Stopped NServiceBus.AutomaticSubscriptions.AutoSubscriber, NServiceBus.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c.

Ensuring IWantToRunAtStartup.Start has been called.

Releasing all claimed Semaphore threads.

Finished handling message.

LicenseBehavior

InvokeHandlersBehavior

SagaPersistenceBehavior

AuditInvokedSagaBehavior

SetCurrentMessageBeingHandledBehavior

DataBusReceiveBehavior

LoadHandlersBehavior

ApplyIncomingMessageMutatorsBehavior

CallbackInvocationBehavior

ExecuteLogicalMessagesBehavior

Drain stopping 'Throttling Semaphore'.

Claiming Semaphore thread 1/1.

Initiating shutdown.

Fault manager failed to process the failed message with id 37196055-5d82-44a3-9d2b-a44a00b0d093

Could not forward failed message to error queue 'MySystem.error@MyQAPresentationServer' as it could not be found.

Failed to process message

ExtractLogicalMessagesBehavior

There was a problem deferring the message. Make sure that DisableTimeoutManager was not called for your endpoint.

RemoveIncomingHeadersBehavior

Defer message and send it to MySystem.Presentation@MyQAPresentationServer

RaiseMessageReceivedBehavior

Failed to process message

There was a problem deferring the message. Make sure that DisableTimeoutManager was not 
called for your endpoint.

ApplyIncomingTransportMessageMutatorsBehavior

Defer message and send it to MySystem.Presentation@MyQAPresentationServer

UnitOfWorkBehavior

Failed to process message

There was a problem deferring the message. Make sure that DisableTimeoutManager was not called for your endpoint.

ForwardBehavior

Defer message and send it to MySystem.Presentation@MyQAPresentationServer

AuditBehavior

ImpersonateSenderBehavior

Failed to process message

Received message with ID 497cb568-e82c-4a31-8327-a45a00a8c3b1 from sender 
MySystem.MyService@QADistributor 

There was a problem deferring the message. Make sure that DisableTimeoutManager was not called for your endpoint.

Defer message and send it to MySystem.Presentation@MyQAPresentationServer

Failed to process message

There was a problem deferring the message. Make sure that DisableTimeoutManager was not called for your endpoint.

MessageHandlingLoggingBehavior

ChildContainerBehavior

Defer message and send it to MySystem.Presentation@MyQAPresentationServer

****End Of QA log entries****

The main things I notice it’s trying to defer the message and NServiceBus for whatever reason it shutting down.  I don’t notice either of these on the DEV machines.

If anyone can help I would appropriate it

**Comment by indualagarsamy** [comment]
For future reference, asking this question in the google groups is a better option. We scan the community forums and answer questions and if we find it to be a bug, we raise it here. 

- Can you provide us more details on the NServiceBus versions, (i.e. from your packages.config) file?
- Can you verify that there is a queue called `MySystem.error` on your QA server `MyQAPresentationServer` ?
- Also are you disabling timeouts? 
- How did you install the endpoint on your QA Server, Are all the queues present such as [endpoint].timeouts, [endpoint].retries and [endpoint].timeoutsdispatcher ?
- Can you share your bus configuration code?

**Comment by mastrauckas** [comment]
Thanks for the quick response.  I'll post there next time.  Here is the answer to your questions 
*  The NServiceBus version is 4.75.
* MySystem.presentation.error exist but not MySystem.error.  However I just added MySystem.error.
* Yes, Timeout Manager is being disabled as shown below.
* NServiceBus is being Host in MVC so there was no installation on this part.
*  Only [endpoint].retries exist.

***Here is the web.config file:***
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="MessageForwardingInCaseOfFaultConfig" type="NServiceBus.Config.MessageForwardingInCaseOfFaultConfig, NServiceBus.Core" />
    <section name="UnicastBusConfig" type="NServiceBus.Config.UnicastBusConfig, NServiceBus.Core" />
  </configSections>
  <MessageForwardingInCaseOfFaultConfig ErrorQueue="MySystem.error" />
  <UnicastBusConfig>
    <MessageEndpointMappings>
      <add Assembly="MySystem.Messages" Type="MySystem.Messages.Commands.MyRequest" Endpoint="MySystem.MyService" />
    </MessageEndpointMappings>
  </UnicastBusConfig>
  <appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
  </appSettings>
  <system.web>
    <customErrors mode="Off" />
    <compilation targetFramework="4.5.2" debug="true" />
    <pages controlRenderingCompatibilityVersion="4.0">
      <namespaces>
        <add namespace="System.Web.Helpers" />
        <add namespace="System.Web.Mvc" />
        <add namespace="System.Web.Mvc.Ajax" />
        <add namespace="System.Web.Mvc.Html" />
        <add namespace="System.Web.Optimization" />
        <add namespace="System.Web.Routing" />
        <add namespace="System.Web.WebPages" />
      </namespaces>
    </pages>
  </system.web>
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <modules runAllManagedModulesForAllRequests="true" />
    <httpProtocol>
      <customHeaders>
        <add name="X-UA-Compatible" value="IE=Edge" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NHibernate" publicKeyToken="AA95F207798DFDB4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.4000" newVersion="4.0.0.4000" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Iesi.Collections" publicKeyToken="AA95F207798DFDB4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Ninject" publicKeyToken="c7192dc5380945e7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Ninject.Extensions.NamedScope" publicKeyToken="c7192dc5380945e7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NServiceBus.Core" publicKeyToken="9fc386479f8a226c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.7.0.0" newVersion="4.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NServiceBus" publicKeyToken="9fc386479f8a226c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.7.0.0" newVersion="4.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.4000" newVersion="4.0.0.4000" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Iesi.Collections" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.2.0" newVersion="5.2.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
Here is code in the MVC project that sets up NServiceBus

```
var bus = Configure.With()
                .NinjectBuilder(_kernel)
                .UnicastBus()
                .Log4Net()
                .DisableTimeoutManager()
                .CreateBus();


 bus.Start();
```
Queues that are on the IIS server:
```
MySystem.presentation
MySystem.presentation.error
MySystem.presentation.retries
MySystem.error just added this queue after your response.
```

**Comment by mastrauckas** [comment]
It appears after adding MySystem.error the problem is fixed.  Why would that stop it from working?

**Comment by indualagarsamy** [comment]
From your log, i saw the following: 
```
Fault manager failed to process the failed message with id 37196055-5d82-44a3-9d2b-a44a00b0d093

Could not forward failed message to error queue 'MySystem.error@MyQAPresentationServer' as it could not be found.
```
It appears as if a message was attempted to be forwarded to the error queue. However, since the error queue wasn't present, it resulted in an error and the bus was shutdown. Because the bus was shutdown, it wasn't processing any messages. And restarting the app pool, restarts the bus, essentially making it work until there was another failure where a message was needed to be forwarded to the error queue.

Does that clarify?
I'll close this issue, but feel free to post questions in the newsgroup for any clarifications. Cheers.

**Comment by mastrauckas** [comment]
Yes it make sense why it wasn't working.  

What doesn't make sense is this same setup worked in DEV environment with the same name for the error queue and that error queue doesn't exist.

Doesn't really matter since it's working.

**Comment by indualagarsamy** [comment]
Perhaps we could do a better job in seeing if the configured error queue is present upfront and if not, try and not start the endpoint, as opposed to having the endpoint start and fail only when trying to forward the message to the error queue. I'll raise it with the team and if needed, I'll open another issue. Thank you reporting this.

**Comment by mastrauckas** [comment]
Ok, thanks for your time.  

I also have another issue I'll post in the groups on Monday.
