### ISSUE TITLE
Bus does not implement IManageMessageHeaders

### ISSUE THREAD

**Issue by danielbanda** [Particular/NServiceBus#2683]
When my Saga's unit tests require more complex assertions/expectations that the ones available though Test.Saga I usually set a Mock (moq) of IBus that allows me to more create complex callbacks an among others things

After I upgraded to NSB 5.0 some of my test are breaking because Saga.RequestTimeout internally expects the concrete instance of IBus to also implement IManageMessageHeaders. 

I looked for the usages of IManageMessageHeaders and they seem to go in pair with IBus, meaning that everything that implements IManageMessageHeaders also implments IBus.

Could you guys just merge IManageMessageHeaders into IBus?

I would like to remove this silly mock setup that I'm doing everywhere:
BusMock.SetupGet(x => x.SetHeaderAction).Returns((o, s, arg3) => { });

Not to mention my new mocking interface:
public interface IManageNsbMess : IBus, IManageMessageHeaders
{
}

Thanks in advance.
-Daniel

**Comment by johnsimons** [comment]
We are addressing this issue in the next upcoming major release (v6)
