### ISSUE TITLE
A not started bus instance can send messages

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2685]
With @SeanFeldman we discovered that a non started bus instance can send messages:

    var config = new BusConfiguration();
    config.EndpointName( "testit" );
    config.UsePersistence<InMemoryPersistence>();
    config.EnableInstallers();

    var bus = Bus.Create( config );
    var command = new TestIt { Text = "hello :-)" };
    bus.SendLocal( command );

the bus is created but not started, but the SendLocal (and also Send) worked.

Shouldn't we throw?

**Comment by SeanFeldman** [comment]
I think we should throw. If command is sent and message makes it into a queue, but handler is not picking up, it's a very confusing state.

**Comment by johnsimons** [comment]
This is how SendOnly endpoints have been  working for a long time, what we
can do is maybe make the api more clear so users do not forget to call
start, something like CreateAndStart.
So -1 to fix anything here.

**Comment by SeanFeldman** [comment]
@johnsimons just to note that this was not a SendOnly bus instance
```c#
var bus = Bus.Create( config );
```

**Comment by johnsimons** [comment]
It does not matter, what I'm saying is that it is the same concept.

**Comment by mauroservienti** [comment]
It is a design issue, a bug in the design of the IStartableBus interface that has no reason to inherit from IBushttps://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/IStartableBus.cs
And to me a send only bus and a non started bus are 2 completely different things. The create API should return something that can be started but that cannot send anything. Under the hood all these interfaces are implemented on the same class, UnicastBus, but if they do not inherit from each other the problem goes away immediately.

**Comment by johnsimons** [comment]
@mauroservienti you can always send messages out without starting the bus, the act of "start" really just means that it will receive messages as well.

What is the issue you see with it?

**Comment by mauroservienti** [comment]
* That is not documented anywhere * That Start means start and not StartReceive* That if you send to local it does not work because the bus is not started* that as far as I can see the pipeline is not started so outgoing messages have a different behavior if the same bus is started or not?

**Comment by mauroservienti** [comment]
And the license is not checked, it is checked when started not when created

**Comment by johnsimons** [comment]
> That is not documented anywhere

That can be fixed by documenting it right ?


> That Start means start and not StartReceive

Not sure I follow but I assume it can be addressed with doco as well.


> That if you send to local it does not work because the bus is not started

Well, the sendlocal works fine, the message is queued up, so when the bus starts it will be dequeued, no message loss.


> that as far as I can see the pipeline is not started so outgoing messages have a different behavior if the same bus is started or not?

Can you explain this one a bit more, not following ?

**Comment by johnsimons** [comment]
> And the license is not checked, it is checked when started not when created

Yes that is an issue that I believe has already been raised before

**Comment by johnsimons** [comment]
@Particular/nservicebus thoughts ?

**Comment by andreasohlund** [comment]
Me and @indualagarsamy had another case where the user could still send messages while the bus was stopped and disposed.

It definitely seems wrong to send when disposed. On the fence on the start.

Since we do have a sendonly mode it perhaps we should just remove the .Start() and rename Bus.Create to Bus.Start() ?

Or just make Create return a started bus?

Only use case I've seen for delayed starts is in smart apps where you create the bus and then call start when users click a "connect" button.

**Comment by SzymonPobiega** [comment]
I think we should change this API entirely. @johnsimons remember the conversation we had with @andreasohlund some time ago? I've just raised an issue for that https://github.com/Particular/Requirements/issues/246

**Comment by johnsimons** [comment]
@SzymonPobiega completely agree.

And on that, closing this one as will be address by https://github.com/Particular/Requirements/issues/246
