### ISSUE TITLE
Support for the LightInject service container

### ISSUE THREAD

**Issue by seesharper** [Particular/NServiceBus#2690]
Hi. I am the author of the LightInject (http://www.lightinject.net) IoC framework and I have written an integration for NServiceBus. The question is where should this code live on GitHub? From what I can gather from the other integration's they seem to all belong to the Particular user. Is it possible for me to make a contribution somehow with a entirely new repo (NServiceBus.LightInject) so that it lines up with the Unity, StructureMap and the others? If so, would I at a later time have the possibility to maintain it without sending pull requests?

Best regards 
Bernhard Richter

**Comment by SimonCropp** [comment]
> From what I can gather from the other integration's they seem to all belong to the Particular user

Not exactly. there are many community run projects. You can see them here http://docs.particular.net/platform/extensions

I think it would be better for you to just create a new GitHub repository for it. You can then send us a pull request for this page https://github.com/Particular/docs.particular.net/blob/master/platform/extensions.md

**Comment by johnsimons** [comment]
Hi @seesharper that is awesome news.

As my colleague @SimonCropp mentions, we are more then happy to link to your project from within http://docs.particular.net/platform/extensions also I would recommend posting a quick email in our forum to promote it at groups.google.com/forum/#!forum/particularsoftware

Regarding where the source is kept, we at this stage are not looking at taking any more container integration packages under our organization, so the recommendation is for you to keep it under your own repo and publish your own nugets.

Let us know if there is anything else we can help with?

Regards
John

**Comment by seesharper** [comment]
Hi again.
Actually I do have a question regarding licencing. 

The LightInject integration for NServiceBus relies on the NServiceBus Nuget package. After a while I got a popup stating that I need a license to continue using NSB. The thing is that I am not using NSB for anything else than writing this integration. If I am going to maintain this integration, I would need something more than a trial license. I have read about the RPL license, but could not really figure out how this applies to this particular project. Do I have to release the integration under RPL  as well or could I just stick with MIT which is the license that all other parts of LightInject uses?

Regards 
Bernhard Richter

**Comment by joefeser** [comment]
@seesharper 
Your package should be able to be released as MIT. The end user will still have to agree to the RPL license for NServiceBus when they use the package.

**Comment by danielmarbach** [comment]
@seesharper Your package can use any license which fits your goals of your OSS project. Users of your package although need a valid NServiceBus license. If you need to extend your trial license for maintaining the package feel free to send an email to support at particular.net and we will help you out.
