### ISSUE TITLE
ISubscriptionStorage.Init can suffer from race condition

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2692]
## Symptoms
The initialization of a subscription storage is usually performed in the `ISubscriptionStorage.Init` method.

Currently the framework calls the `Init` from within a `IWantToRunWhenBusStartsAndStops.Start`, because the `IWantToRunWhenBusStartsAndStops.Start` is executed after the main transport has started, there is a possibility of a race condition:

1. Bus starts receiving messages
1. Handler does a `Publish`
1. `IWantToRunWhenBusStartsAndStops.Start` is called

As you can see step 2 can occur before step 3.

This will cause subscribers to not receive the published events

## Who's affected
Publisher endpoints that use MSMQ as the subscription storage and restart with messages in their queue.

**Comment by johnsimons** [comment]
@Particular/nservicebus please review and assess criticality

**Comment by danielmarbach** [comment]
I'd say this is another one of these cases where we should use a FeatureStartupTask?

**Comment by johnsimons** [comment]
@danielmarbach yes, I fixed develop but I don't think we can apply the same fix to previous versions

**Comment by indualagarsamy** [comment]
@johnsimons - do you have a repro or an acceptance test for this?

**Comment by danielmarbach** [comment]
Hack it into unicastbus?

Am Donnerstag, 26. März 2015 schrieb John Simons :

> @danielmarbach <https://github.com/danielmarbach> yes, I fixed develop
> but I don't think we can apply the same fix to previous versions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2692#issuecomment-86354472>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by johnsimons** [comment]
> do you have a repro or an acceptance test for this?

No, if anyone can think of a way to replicate the race condition in a test, go for it.

**Comment by johnsimons** [comment]
> Hack it into unicastbus?

That is a possibility

**Comment by johnsimons** [comment]
Funny, no one has actually commented regarding the criticality of the issue ?

**Comment by andreasohlund** [comment]
Has this been an issue since the dawn of time?

**Comment by johnsimons** [comment]
Since v4.0 i think

**Comment by danielmarbach** [comment]
@johnsimons about the criticality of this issue: A lot needs to go wrong that it occurs and it can only occur during startup and shutdown. I'd say the criticality isn't that high but I agree we need to fix it

**Comment by SzymonPobiega** [comment]
This is technically a message loss scenario and our rules say we back port such bugs. Completely other thing is the time frame. I don't think we need to be in a hurry here since
 * a lot of things has to go wrong for this to occur
 * it was working like this for a long time
 * it only affects a subset of users

**Comment by johnsimons** [comment]
> A lot needs to go wrong that it occurs and it can only occur during startup and shutdown

@danielmarbach, actually it can only occur at startup

**Comment by johnsimons** [comment]
> a lot of things has to go wrong for this to occur

I'm not clear on this statement, can someone expand ?

**Comment by andreasohlund** [comment]
Yes this seems like a hotfix (not urgent though).

**Comment by danielmarbach** [comment]
So a not so hot Hotfix ;)

**Comment by SzymonPobiega** [comment]
lukewarmfix?

**Comment by SimonCropp** [comment]
i prefer the terminology "patch" and "hotfix" where, as per semver, any "only bug fix release" is a "patch" and a "hotfix" is a "patch" with some level of urgency

**Comment by johnsimons** [comment]
I've tried to replicate this issue but could not, that said i do still think we should patch it just to make sure it does not happen.
