### ISSUE TITLE
Only set intent and replytoaddress headers from raw MSMQ message if not already set

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2699]
Right now we always set them but I believe to only set when the header isn't already there to avoid corrupting the original message

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs#L135

**Comment by timbussmann** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/17.
