### ISSUE TITLE
Msmq subscription storage defaults to wrong queue name

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2703]
The msmq subscription storage queue should default to `"{Name of your endpoint}.Subscriptions` but instead is defaulting to `NServiceBus.Subscriptions`.

This affects v5.0+

It also seems that in v4 the users used to be able to override the queue name for the subscription via the config file as well as via the api, in v5 the api method to override is missing!

**Comment by johnsimons** [comment]
@Particular/nservicebus do we backport this one ?

**Comment by SeanFeldman** [comment]
I had a few customers with this issue when they were migrating from v4 to v5. 
My vote is yes (backport).

**Comment by andreasohlund** [comment]
Would you say people would notice this in development?


>I had a few customers with this issue when they were migrating from v4 to
v5.
My vote is yes (backport).

If you're upgrading to v5 wouldn't you go to the latest v5? (so is this
really a reason to backport?)

**Comment by sfarmar** [comment]
:+1:  as @SeanFeldman said, customers are doing that

**Comment by andreasohlund** [comment]
So we should be fine with fixing the latest v5?

**Comment by SeanFeldman** [comment]
Probably yes.

**Comment by johnsimons** [comment]
IMO this could go unnoticed in dev, mostly because user test everything
using the same version but it could be a different story when they rolling
the updates to prod as a side by side deployment.

**Comment by SeanFeldman** [comment]
+1 for bringing side-by-side scenario

**Comment by johnsimons** [comment]
@andreasohlund I think this needs to be backported, to handle side by side upgrades

**Comment by andreasohlund** [comment]
I don't see how this would prevent side by side upgrades? 

Wouldn't vN and vN+1 both be able read the `NServiceBus.Subscriptions` or what ever specific queue you configure it to use? (yes a v5 user would have to explicitly configure the name if not on the latest v5)

**Comment by johnsimons** [comment]
@andreasohlund the issue as I see it is the following.
- User is on v4, therefore using `{Name of your endpoint}.Subscriptions` queue name;
- User upgrades to v5 and because in dev / integration environments they do a full on upgrade, the change in queue names goes unnoticed;
- User starts slowly upgrading prod using side by side deployment, we now have 2 subscription queues!, and the new queue, has no subscribers!
- Not a happy user

Does this make sense ?

**Comment by andreasohlund** [comment]
The steps makes sense but would a user really do a side by side upgrade in
production without testing it in a similar environment?

**Comment by johnsimons** [comment]
> The steps makes sense but would a user really do a side by side upgrade in
> production without testing it in a similar environment?

@andreasohlund IMO, I think it is a plausible scenario, but your call, please let me know so I can either fix it or close it ?

**Comment by andreasohlund** [comment]
I'm +1 for closing (ie not backporting)

@Particular/nservicebus please chime in if you think I'm off
