### ISSUE TITLE
Allow to specify assembly scanner not to scan nested folder

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#2708]
**Breaking changes**

Changing default AssemblyScanner behavior not to scan nested folders.
Nested folders will be scanned only when requested so through code API.

------

Original request came from [google groups](https://groups.google.com/forum/#!msg/particularsoftware/7Me1KKAxmFU/LhiyavkjZb0J)

While we have an [option to scan a folder](http://docs.particular.net/nservicebus/hosting/assembly-scanning#you-can-specify-the-directory-to-scan-), we do not allow specifying that nested folders should not be scanned, while internally `AsseblyScanner` already has that option. 

1. What are the reasons behind making that option internal and not exposing an option to users?
2. Could we add this option for directory scanning we already have (`configuration.ScanAssembliesInDirectory()`)?

Possible API would look like
```c#
// scanNestedDirectories would be optional parameter set to true by default to be backwards compatable
configuration.ScanAssembliesInDirectory(@"c:\my-custom-dir", scanNestedDirectories: false); 
```

@Particular/nservicebus please chime in. Thank you.

**Comment by indualagarsamy** [comment]
Discussed this earlier with @SeanFeldman and I agree. 
- When we explicitly have an option for scanning directories, it seems very restrictive to not give the user the option of controlling the directory scan. (It's like having a `dir` and a `dir /s` option) 
- Unless there are pressing reasons for this argument to be internal, my vote is to make this parameter public. Default behavior can be as it currently exists today.

**Comment by janovesk** [comment]
:+1: 

I heard this requested by users several times, including today.

**Comment by johnsimons** [comment]
:+1: also we should allow specifying whether exes are scanned or not, see https://github.com/Particular/NServiceBus/blob/a69ab8bfd238a3b4dad916c93ba268451fdca531/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L45

This actually used to work but for some reason it got removed :disappointed:

**Comment by johnsimons** [comment]
@SeanFeldman this is an easy one, should I assign it to u?

**Comment by SeanFeldman** [comment]
[`ScanAssembliesInDirectory()`](https://github.com/Particular/NServiceBus/blob/a083112affa6a4d4fd538c2fb62adf01041ddfcf/src/NServiceBus.Core/v6-obsoletes.cs#L42) is marked as obsoleted and replacement is to use `ExcludeAssemblies()`

So that would either require signature change on [`BusConfiguration.ExludeAssemblies()`](https://github.com/Particular/NServiceBus/blob/a083112affa6a4d4fd538c2fb62adf01041ddfcf/src/NServiceBus.Core/BusConfiguration.cs#L74) or additional method.

What would API look like @johnsimons ?

**Comment by SeanFeldman** [comment]
Here's a summary of discussion with @johnsimons and PoA:

- In 4.7 there [was a way to achieve this](https://github.com/Particular/NServiceBus/blob/4.7.5/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L38) that was "lost" in transition to V5
- Since `AssemblyScanner` is invoked twice (by NSB host and later by configuration), we can't rely on configuration
- Change default behavior to what was planned in 4.7 - "'ScanNestedDirectories' will be opt-in
 - Provide configuration file based way to override the new default (similar to [what it was in V4.7](https://github.com/Particular/NServiceBus/blob/4.7.5/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L41))
- Update documentation

**Comment by danielmarbach** [comment]
@SeanFeldman What is the status of this?
