### ISSUE TITLE
 Essential headers missing when message is sent to error queue

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2713]
With the latest patches for #2463, we have forgotten to include essential headers:
- NServiceBus.FailedQ
- All of the exception ones see https://github.com/Particular/NServiceBus/blob/b47c3f12267790ef32c587c23d830dcf477ab95a/src/NServiceBus.Core/Utils/ExceptionHeaderHelper.cs#L19-L57
- Also Headers.HostId and Headers.HostDisplayName

We also seem to need to ensure we remove the Retries header, see https://github.com/Particular/NServiceBus/blob/b47c3f12267790ef32c587c23d830dcf477ab95a/src/NServiceBus.Core/Faults/Forwarder/FaultManager.cs#L102

This cause ServiceControl to not successfully import those messages and those messages are also not able to be replayed via ServiceControl.

**Comment by andreasohlund** [comment]
This is that this happens since the headers can even be corrupted so we can't add any headers at all. The plan is to make SC handle this gracefully (not assume anything about headers being present)

@indualagarsamy @gbiellem is working on that right now

Does this make sense?

**Comment by johnsimons** [comment]
So there is no way to retry such messages?

**Comment by gbiellem** [comment]
@johnsimons 

> So there is no way to retry such messages?

The messages from the acceptance test had no processing endpoint info or failedQ etc
So you'd need to add a mechanism to  enrich it before sending it of for retry presumably by prompting the user for the destination.  Is that what you had in mind?

**Comment by SimonCropp** [comment]
since we cant use the headers the only way would wrap the binary content in a new message.

**Comment by andreasohlund** [comment]
Correct!

**Comment by SimonCropp** [comment]
closing this since there is no possible fix we can do in the core
