### ISSUE TITLE
Allow users to override the hostid before MD5 is used

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2721]
## Who's affected

* Users who want to override the hostid with a custom identifier

## Symptoms

When using 

`busConfguration.UniquelyIdentifyRunningInstance().UsingCustomIdentifier(Guid.NewGuid())`

the custom assigned identifier was still hashed with MD5. 

This change ensures that the custom assigned identifier is not hashed and retained as assigned by the user.

**Comment by danielmarbach** [comment]
Isn't this clearly a bug and not a feature?

**Comment by johnsimons** [comment]
@danielmarbach have made it a bug and assign the correct milestone

**Comment by danielmarbach** [comment]
Release in 5.2.6
