### ISSUE TITLE
DeliveryTime and CriticalTime can be negative

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2731]
I've just imported a users SC database to diagnose an issue in SI and I saw:
![image](https://cloud.githubusercontent.com/assets/122651/7508730/cfe31c8c-f4c8-11e4-9d3c-a669e3fd2388.png)

It seems this user is running in Azure, and obviously hosts datetimes may not be exactly in sync.
So the calculation for DeliveryTime and CriticalTime because it relies on timestamps from multiple machines can get negative values.

**Comment by johnsimons** [comment]
@andreasohlund a good one for you to fix :astonished:

**Comment by johnsimons** [comment]
@SeanFeldman @yvesgoeleven is my diagnosis right ?

**Comment by andreasohlund** [comment]
What can we do here? Just show a `0` if the value is negative?

**Comment by johnsimons** [comment]
This can also occur on site, machines clocks may not be in sync, @gbiellem do you know how often this happens ?

**Comment by johnsimons** [comment]
@andreasohlund the only solution I can think of if we really want to be accurate is to use a time server

**Comment by gbiellem** [comment]
> do you know how often this 

@johnsimons  - Time syncing in Windows is configurable and optional so there is no good answer there.  Yes a time server will mitigate the issue but it's still no guarantee as machines do drift between syncs

**Comment by SeanFeldman** [comment]
@johnsimons on Azure all machines use UTC and by default configured to use a time server that Microsoft defaults to.

>The VMs and services take their time directly from the underlying Hyper-V platform upon boot and from that point forward the clock is maintained by the service. In order to have true time sync across a distributed system you will need to do this at the application layer and/or with a service referencing an singular time server.

**Comment by SimonCropp** [comment]
If we are sure this is a client with time sync problems i think we should document and leave as is. Any zeroing out would only hide the problem the from them

**Comment by andreasohlund** [comment]
Makes sense to me, +1

**Comment by SimonCropp** [comment]
@johnsimons closing this one . please add to the SI doco.
