### ISSUE TITLE
Error trying to serialize (XmlSerializer) properties of type ArrayList

### ISSUE THREAD

**Issue by ismaelhamed** [Particular/NServiceBus#2742]
Given this command:

```
[Serializable]
public class Command : IMessage
{
    public int Id { get; set; }
    public Order<Foo1> Order { get; set; }
}

public class Order<T> 
    where T : class
{
    [XmlElement(typeof(Foo1), ElementName = "Foo1"),
     XmlElement(typeof(Foo2), ElementName = "Foo2")]
    public ArrayList FooList { get; set; }
}
```

I'm getting this error:

```
Type System.Object was not registered in the serializer. Check that it appears in the list of configured assemblies/types to scan.
```

If I configure the bus to use the JsonSerializer it all works fine. Also notice that the System.Xml.Serialization.XmlSerializer knows how to serialize/deserialize this without any problem too, so it seems like a flaw in the NServiceBus serializer.

**Comment by SimonCropp** [comment]
Unfortunately Arraylist is not supported by the built in XML serializer
Also the XML serializer is a custom implementation (does not use the ,net xmlserializer) and as such the standard xml attributes are not supported.
http://docs.particular.net/nservicebus/serialization/xml-serializer

I suggest you move over to using the Json serializer
