### ISSUE TITLE
When Disabling Transactions failed messages are logged with log level INFO

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#2751]
When `Transactions().Disable()` is used failed messages are logged with log level INFO. The user might expect that failed messages will get logged with the log level ERROR. Just as would happen when a message has gone through the whole retry logic.

**Comment by andreasohlund** [comment]
I'll double check, but I'm pretty sure this is fixed in v6

**Comment by andreasohlund** [comment]
Strike that, we only log error when moving to the error queue. So this one would be fixed if we do #2752

**Comment by SzymonPobiega** [comment]
@andreasohlund I doubt we should/can fix #2752. Fixing this one is easy but not sure if we should address it in V5 or V6. What are your thoughts? Would going through `FeatureDevelopment` and assessing the impact help?

**Comment by andreasohlund** [comment]
@timbussmann you are fixing this one right?

**Comment by timbussmann** [comment]
yes, ErrorQ behavior will log exceptions with error level soon (for v6)

**Comment by andreasohlund** [comment]
Nice, please uodate this issue when done

**Comment by ramonsmits** [comment]
@timbussmann Is this behavior part of a different issue? Can we refer to that and close this?

**Comment by timbussmann** [comment]
@ramonsmits I think it was here #2830

**Comment by danielmarbach** [comment]
Closing this [we log with error](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs#L58) in V6

**Comment by danielmarbach** [comment]
Fixed as part of https://github.com/Particular/NServiceBus/commit/72c470ba3215bf4cfd58f691624494ee788a7925
