### ISSUE TITLE
When Disabling Transactions failed messages are not send to the error queue

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#2752]
The transaction documentation states:

>In this mode the transport in use does not attempt to wrap the receive operation in any kind of transaction. Once the message has been received, it can't be put back into the queue. Should the message processing fail for any reason (including system crash), the message is permanently lost.

The user might assume that a failed message would still be written to the error log after reading this.

I can understand that the message is not written to the error log because it is not reliable. So sometimes this could fail which can create a false assumption to the user that it can rely on that.

Another option would be that the user explicitly enables this behavior so that we at least 'try' to move it to the error queue.

```
busConfiguraton.Transactions().Disable();
busConfiguration.EnableFeature<NServiceBus.Features.WriteFailedToErrorQueue>();
```

If not, then we need to better document the behavior.

**Comment by andreasohlund** [comment]
Pretty sure that we've fixed this as we cleaned up the pipeline. I'll verify and update doco as needed.

**Comment by indualagarsamy** [comment]
@andreasohlund - I pulled the latest core and tested this: 
1. With SLR disabled, the message is sent to the error queue
2. With SLR enabled, the message is sent to the error queue
As I was using InMemoryPersistence, mid-point endpoint restarts and the message was gone. I couldn't use either NServiceBus.NHibernate or NServiceBus.RavenDB (coz the develop hasn't been transitioned over to v6). 

**Questions:**
1. Shouldn't this be covered by an acceptance test? Thanks @SimonCropp 
2. Should we back port this to older versions? Or is that too difficult?

**Comment by andreasohlund** [comment]
>1. Shouldn't this be covered by an acceptance test? Thanks @SimonCropp 


Yes, please add relevant ones


>2. Should we back port this to older versions? Or is that too difficult?


To hard IMO, we need the pipeline extending into the transports to make this work

**Comment by andreasohlund** [comment]
@indualagarsamy any luck with the acceptance tests?

We should also add this to the upgrade guide? (Is there some error handling doco that needs to change as well?)

**Comment by indualagarsamy** [comment]
@andreasohlund - As discussed with @colin-higgins - seems like there's more to do here for this issue and I'm capturing what those are as follows:
- [x] Add new acceptance test for making sure that messages aren't lost when transactions are disabled. (See commit above)
- [ ] Update the v5-v6 upgrade guide and document this behavior change
- [ ] Update the documentation here: http://docs.particular.net/nservicebus/messaging/transactions#transactions-unreliable
- [ ] Also review the other acceptance tests. For example, we now do retries as well. This is different from old documented behavior and [existing acceptance test]( https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_default_settings.cs#L13)

**Comment by andreasohlund** [comment]
> For example, we now do retries as well. This is different from old
documented behavior and

I assume this is SLR retries since we can't do FLR if we can't rollback.

Given that the users asked for AtMostOnce I'd say we shouldn't do SLR and
this is v6 bug?

**Comment by indualagarsamy** [comment]
@andreasohlund - what if the users have configured SLR? Do we throw? Isn't SLR on by default? Does transactions off mean we just process once? Can we somehow make that more explicit?

**Comment by andreasohlund** [comment]
>what if the users have configured SLR? Do we throw? 

Good question, if they enabled it explicitly I don't see a big issue to give them SLR? (it wouldn't be atmostonce semantics though)

>Isn't SLR on by default? 

Yes it is but we could disable it when users call `.Transactions().Disable() ?` => soon to be `.RequiredConsistency(ConsistencyGuarantee.AtMostOnce)` - https://github.com/Particular/NServiceBus/pull/2987

>Does transactions off mean we just process once? 

That's the current proposal yes, "AtMostOnce" (error q is fine since the user is in full control if they want to retry it and there by break the at most once part)

> Can we somehow make that more explicit?

I can't come up with anything, ideas?

**Comment by colin-higgins** [comment]
@ramonsmits @indualagarsamy @andreasohlund 

Had a support call today with @SeanFeldman where the customer disabled transactions but had second level retries configured. (They were using version 4.7)
Obviously, no retries or message in the error queue on error. The customer was confused about why the failed messages were not ending up in ServiceControl. 
I think it just outlines the need to make sure the documentation is explicit per version on this. I need to finish this doco PR on that note: https://github.com/Particular/docs.particular.net/pull/880

**Comment by ramonsmits** [comment]
@andreasohlund  You wrote:

> Given that the users asked for AtMostOnce I'd say we shouldn't do SLR

Don't agree that if the user disabled transactions that they want AtMostOnce processing. These are two different things.

**Comment by ramonsmits** [comment]
I like to distinguish in these features:

* FLR (rollback transaction with FLR counter)
* Send back to queue (FLR alternative)
* SLR (move to retries)
* Move to error queue 

These features should be performed in the correct order which is just coincidentally have done here.

Bonus points here as now FLR new style and SLR and forwarding to error queue would work for any non transaction transport like a file, ftp, smtp or any other kind of queue implementation.

**Comment by indualagarsamy** [comment]
Since we have separate issues on what the behavior of FLR/SLR should be addressed in the issue, please continue the discussion in the related issues. 

As far as this issue is concerned, when messages fail, they are forwarded to the error q in version 6. 
This has been now documented in both the documentation and the upgrade guide. (when the doco PR gets merged). 
I'll close the issue when the doco PR gets merged.

**Comment by indualagarsamy** [comment]
Documentation and Upgrade guide regarding the new behavior is now up-to date.

**Comment by indualagarsamy** [comment]
@andreasohlund - this is tagged as a Feature, is that correct?

**Comment by andreasohlund** [comment]
Not sure, is it worth to include in the release notes? (if yes it needs to be a feature since we only include features and bugs)

**Comment by indualagarsamy** [comment]
Can we call it a bug? IMO its a bug? (by behavior). More so than feature.

**Comment by andreasohlund** [comment]
Ok can live with that.

@adamralph do U remember why we removed the old "improvement" label?

**Comment by indualagarsamy** [comment]
@andreasohlund @adamralph - I believe `Improvement` would have been a better fit here.

**Comment by adamralph** [comment]
@andreasohlund @indualagarsamy 

> @adamralph do U remember why we removed the old "improvement" label?

IIRC we wanted to simplify, so as far as users are concerned, we add features and fix bugs, nothing more. Internally, we do refactoring, spikes, clean up tech debt, etc. but these things do not affect releases, and are only of interest to us and contributors.

**Comment by andreasohlund** [comment]
:+1: so let's classify this one (like you already did @indualagarsamy ) and see if we run into this again in the future
