### ISSUE TITLE
TransportDefinition should communicate if it can support busConfiguration.DisableDurableMessages();

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2754]
And throw if it doesnt support it. SQL is currently the only one that does not.

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus/pull/2737

**Comment by andreasohlund** [comment]
The core now requres the transports to return supported constraints via `GetSupportedDeliveryConstraints` and wil throw if non durable is selected for a transport that don't support it
