### ISSUE TITLE
NRE is thrown if only MSMQ storage is selected

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2771]
We need to provide a better exception as config time
### Original report

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/LAUxb8P9VlA/5ThczRXK_28J

**Comment by danielmarbach** [comment]
How about getting rid of MSMQ Persistence?

**Comment by andreasohlund** [comment]
v6 throws a better ex:

```
"The selected persistence doesn't have support for timeout storage. Select another persistence or disable the timeout manager feature using endpointConfiguration.DisableFeature<TimeoutManager>()"
```
