### ISSUE TITLE
FowardingQueue is always automatically created

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2772]
We are creating the forwarding queue when forwarding is enabled every time. Arguably we shouldn't create the forwarding queue

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Behaviors/ForwardReceivedMessages.cs#L30

**Comment by danielmarbach** [comment]
See also https://github.com/Particular/NServiceBus/pull/2785

**Comment by timbussmann** [comment]
closing this issue since we're rethinking queue creation (not limited to the forwarding queue)
