### ISSUE TITLE
Provide better error message when persistence selected doesn't support feature(s) used

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#2773]
Origin: Google user group [thread](https://groups.google.com/forum/#!msg/particularsoftware/yoHSZQjwUQE/bVZgGTu7Q6wJ) raised by Jason Dentler

Thinking out loud: when someone uses config.UsePersistence<MsmqPersistence>(), intent is to use it for all. Since we know that MSMQ persister doesn't support all storages, can we figure out that what storages are not configured and when attempt to utilize them is made throw a specific exception?

@Particular/nservicebus what are you thoughts?

**Comment by SeanFeldman** [comment]
Also, should that info be here: http://docs.particular.net/nservicebus/persistence/

**Comment by andreasohlund** [comment]
Related to https://github.com/Particular/docs.particular.net/issues/702

**Comment by ramonsmits** [comment]
Added some doco to hopefull get better discovery of this issue: https://github.com/Particular/docs.particular.net/pull/1476

It can happen for various reasons.

**Comment by andreasohlund** [comment]
v6 throws better exceptions, eg:

```
{"The selected persistence doesn't have support for timeout storage. Select another persistence or disable the timeout manager feature using endpointConfiguration.DisableFeature<TimeoutManager>()"}
```

Should we close this?

**Comment by danielmarbach** [comment]
:+1: for closing
