### ISSUE TITLE
License priority and trials licenses

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2779]
## Who's affected

Everyone that:
- is **not** using the `NServiceBus.Host`;
- is installing more than one endpoint on the same machine;
- is running endpoints with different credentials
- wants to share the licence across these endpoints at the machine level installing the license in the `HKLM` registry hive.
## Symptoms

The endpoint at startup creates a trial license in the `HKCU` registry hive and starts running in trial mode.
## Triage

none
## Steps to reproduce
1. create a sample console application that starts up a bus instance (do not use the `Host`);
2. Clear the `HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware` and `HKEY_CURRENT_USER\Software\ParticularSoftware` hives of all keys;
3. Create a valid “License” key in the `HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware` hive;
4. Start the sample application, notice that the key `TrialStart` is added with the current date in `HKEY_CURRENT_USER\Software\ParticularSoftware`;
5. Modify this date to sometime in the past, such as `2015-01-13` and restart the application to cause a license failure.
## Workaround

Install the license on a per user basis in the `HKCU` registry hive
## References
- Desk case: https://nservicebus.desk.com/agent/case/11743
- [Operations Licensing](https://github.com/Particular/Operations.Licensing/issues/14)

**Comment by danielmarbach** [comment]
According to our documentation

http://docs.particular.net/nservicebus/licensing/license-management#where-does-nservicebus-look-for-a-license

>  For example, an expired license in HKEY_CURRENT_USER would overrule a valid license in HKEY_LOCAL_MACHINE

This works as defined in the documentation. Since we have a workaround described here I'm closing this. Since this might affect all our products not only NSB we should then probably reopen this issue in PlatformDev if we really think we need a different behavior.

**Comment by danielmarbach** [comment]
I'll reopen.

**Comment by danielmarbach** [comment]
@mauroservienti I linked https://github.com/Particular/Operations.Licensing/issues/14

Would it be possible for you to drive the triage process?

// cc @ramonsmits

**Comment by mauroservienti** [comment]
@danielmarbach it really depends on the priority of this one. I can schedule this in say 10 days or so, before it's hard.

**Comment by timbussmann** [comment]
> I'll reopen.

context?

**Comment by andreasohlund** [comment]
Labeled this as a bug

**Comment by andreasohlund** [comment]
@bording is this something that you might have fixed/can fix as part of https://github.com/Particular/NServiceBus/pull/4588 ?

**Comment by bording** [comment]
@andreasohlund I'll have to verify to make sure I'm understanding the scenario correctly, but I think this would already be fixed by #4588.

**Comment by bording** [comment]
With the changes introduced in 6.3.0, this should be resolved. All possible license locations are searched for licenses, and the "best" license is chosen as the active license, with "best" meaning the license with the expiration that is the farthest in the future.
