### ISSUE TITLE
InsertAfterIfExists and InsertBeforeIfExists do not throw an exception if the specified anchoring step is in a different stage of the pipeline

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#2780]

**Comment by timbussmann** [comment]
Checked against current v6 and it seems to throw the following exception when trying to insertbefore/after a behavior in a different stage:

> Registration '<dependency>' specified in the insertafter of the '<behavior>' step does not exist. Current StepIds: '<behavior>'

The exception message could be a bit more helpful, but it should stop the endpoint from starting with invalid behavior dependencies.

I think we can close this? @Particular/nservicebus-maintainers @SzymonPobiega
