### ISSUE TITLE
Generate missing headers for messages from 3rd party systems to display conversation correctly in ServiceInsight

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus#2797]
Right now if a message from 3rd party system starts a flow, it's not treated as part of the flow unless it has explicitly specified CorrelationId header.
This is different from behaviour for messages coming from NSB endpoint - in such a case the first message will be part of the flow it started.

After change update doco (NServiceBus/messaging/3rd party integration)

**Comment by andreasohlund** [comment]
I think the fix might be to just use the `MessageId` of the incoming message if no conversation id is found https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs#L28

I suspect we need to modify ServiceControl as well to use MessageId when receiving audit messages that has no `ConversationId`

**Comment by danielmarbach** [comment]
@andreasohlund @weralabaj Added feature label. Can you discuss this and see if there is a way forward, including potential consequences for ServiceControl.

**Comment by weralabaj** [comment]
I'm in favour of the approach Andreas proposed above. Seems simple and addresses the issue. @mikeminutillo @johnsimons  can you think of any downsides from SC/SP/SI perspective?

**Comment by johnsimons** [comment]
I am confused, @andreasohlund is talking about ConversationId but the issue refers to CorrelationId, which one is it ?

**Comment by andreasohlund** [comment]
@weralabaj I assumed that you talked about the "conversation id" since that's the things that generates the "message flow" in SI, can you confirm and update the title?

**Comment by weralabaj** [comment]
It's been months since I raised it, so it's hard for me to say without digging again into SI code and repeating tests. 

Either way the problem was that if the message was sent directly and one of those headers wasn't explicitly added when creating the message, then that message wasn't displayed in SI as part of the flow/conversation it started. It was treated as a separate conversation, but all subsequent messages from this conversation were ok.

**Comment by mikeminutillo** [comment]
This is possibly doable using a Map-Reduce index in SC. For each document, this index will add the current message Id and the contents of the RelatedTo header if found. Then we just group the results and make them unique. This is a very common operation in SI so it would make sense to have an index for it instead of relying on the one giant index that we use for everything.

**Comment by johnsimons** [comment]
> I suspect we need to modify ServiceControl as well to use MessageId when receiving audit messages that has no ConversationId

IMO, NSB should enrich the audit message with that data

**Comment by weralabaj** [comment]
I think this is not a very common scenario, since it wasn't raised by the customer. So I'm with John that fixing it in NSB should be sufficient.

**Comment by weralabaj** [comment]
That issue is no longer relevant, it has been addressed in the meantime anyway.
