### ISSUE TITLE
Rename FLR notifications API

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#2808]
The naming `MessageHasFailedAFirstLevelRetryAttempt` does not match with its behavior. Currently each time a message processing fails (including the first time) raises this event. The question is:
* fix the behavior (don't report first processing failure of a message)
* rename the interface to match the current behavior e.g. `MessageHasFailedProcessing`. Would it make sense to add some more info to the event like `NextStep` (FLR, SLR, Error)?

**Comment by danielmarbach** [comment]
> 2) Satellite pipelines reuse certain behaviors (e.g. FirstLevelRetryBehavior) which provide data to the notifications API. This results in FLR/SLR/Error handling in satellite pipelines (Timeout Message Processor and Timeout Dispatcher Processor) will also trigger the corresponding Observables in the notifications error API. Satellite pipeline behaviors probably shouldn't report to the notifications API?

Point 2 is fixed with https://github.com/Particular/NServiceBus/pull/3337

Will edit the description

**Comment by danielmarbach** [comment]
This could be fixed as part of https://github.com/Particular/NServiceBus/issues/3032

**Comment by danielmarbach** [comment]
Flagged as V6.

**Comment by timbussmann** [comment]
with the changes made by https://github.com/Particular/NServiceBus/pull/3568 we no longer raise the FLR attempt failed on the attempt which leads to the SLR attempt. We should align the FLR event with the SLR and ErrorQ event which indicates that a message has failed processing and will be retried by FLR or SLR / moved to error queue.

**Comment by andreasohlund** [comment]
I don't see this as a must have, removing the v6 label

**Comment by timbussmann** [comment]
@andreasohlund in that case I think we should tag it as bug then since the naming clearly doesn't match with how it behaves. I'd rather see it as a v6 change, since it's a small fix which finally improves that api (long overdue).

**Comment by andreasohlund** [comment]
Flagged as bug

**Comment by timbussmann** [comment]
closing this as the API has been renamed with the recoverability changes from https://github.com/Particular/V6Launch/issues/69
