### ISSUE TITLE
NServiceBus.Core.SettingsExtensions tries to create an instance of an abstract class

### ISSUE THREAD

**Issue by a-belevich** [Particular/NServiceBus#2809]
### Who's affected

Users with abstract base classes implementing `IProvideConfiguration<T>`

### Symptoms

Endpoint will not start with the error message that it can't create the abstract class.

### Original bug report

Our solution uses abstract class that implements `IConfigureThisEndpoint, IProvideConfiguration<MessageForwardingInCaseOfFaultConfig>, IProvideConfiguration<AuditConfig>, IProvideConfiguration<SecondLevelRetriesConfig>, IProvideConfiguration<TransportConfig>, IProvideConfiguration<UnicastBusConfig>` interfaces. Every endpoint contains its own descendant of this class and can override some settings. 

When trying to run acceptance tests, endpoint is failed to initialize because it attempts to instantiate an abstract class. It happens because SettingsExtensions.GetConfigSection<T> method doesn't filter out abstract classes:
```
            var typesToScan = settings.GetAvailableTypes();
...
            var sectionOverrideType = typesToScan.FirstOrDefault(t => typeof(IProvideConfiguration<T>).IsAssignableFrom(t));
...
            if (sectionOverrideType == null)
            {
                return configurationSource.GetConfiguration<T>();
            }

            IProvideConfiguration<T> sectionOverride;

            if (HasConstructorThatAcceptsSettings(sectionOverrideType))
            {
                sectionOverride = (IProvideConfiguration<T>)Activator.CreateInstance(sectionOverrideType, new object[] { settings });
            }
            else
            {
                sectionOverride = (IProvideConfiguration<T>)Activator.CreateInstance(sectionOverrideType);
            }
```

**Comment by andreasohlund** [comment]
Fixed by #2810
