### ISSUE TITLE
Stop reusing FirstLevelRetryBehavior for satellites

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#2813]
We currently use FirstLevelRetryBehavior for the main pipeline as well as in the satellite pipelines for the TimeoutManager. Changing the implementation of the main pipeline will also change the satellites.  Should we stop reusing the implementation and have two separate implementations which would allow us to improve the FLR behavior e.g.
* Merge FLR and SLR behavior into a single "Recoverability" behavior in order to avoid using `InsertBeforeExists(...)` in the main pipeline.
* no longer trigger the notifications API from satellite pipelines FLR handling.
* Configure individual FLR policies for main/satellite pipelines.

**Comment by danielmarbach** [comment]
Fixed as part of https://github.com/Particular/NServiceBus/pull/3337
