### ISSUE TITLE
Change NServiceBus.AcceptanceTesting package title

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#2817]
The AcceptanceTesting NuGet package has the following title and description:

```
<title>NServiceBus Acceptance Tests</title>
<description>Acceptance tests for nservicebus core functionality</description>
```

when searching for the AcceptanceTesting library on NuGet this is slightly confusing. To better distinct it from the acceptance tests source package and clarify the package's purpose we should change these fields.

**Comment by danielmarbach** [comment]
Assigned to @timbussmann this can be done in a non-breaking way, takes only a few minutes and better conveys the intent of the package.
