### ISSUE TITLE
MsmqTransportConfigurator.CheckQueue needs to handle exceptions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2829]
in here https://github.com/Particular/NServiceBus/commit/bfee246856c7c25e63ba33db4255c1db0f371580

this was added 

```
if (MessageQueue.Exists(queuePath))
{
    using (var messageQueue = new MessageQueue(queuePath))
    {
        WarnIfPublicAccess(messageQueue);
    }
}
```

to `MsmqTransportConfigurator`

unfortunately if there is a config error and someone has used an invalid queue name this will blow up with a 

```
System.Messaging.MessageQueueException was unhandled
  Message=Invalid queue path name.
  ErrorCode=-2147467259
  StackTrace:
       at System.Messaging.MessageQueue.ResolveFormatNameFromQueuePath(String queuePath, Boolean throwException)
       at System.Messaging.MessageQueue.Exists(String path)
       at NServiceBus.Features.MsmqTransportConfigurator.CheckQueuePermissions.CheckQueue(String address) in c:\Code\NServiceBus\src\NServiceBus.Core\Transports\Msmq\Config\MsmqTransportConfigurator.cs:line 57
```

This does not tell them the queue name text or where the config came from.

Also i dont think that method handles remote queue names so it will most likely break for remote queue. have a look at this code https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs#L58

**Comment by SimonCropp** [comment]
ping @hmemcpy

**Comment by danielmarbach** [comment]
@SimonCropp @hmemcpy can you reach a conclusion how to move this forward? Based on

> Also i dont think that method handles remote queue names so it will most likely break for remote queue. 

it sounds like a bug unless you are only referring to the inclusion of the queue name/path in the exception details. Not really sure based on the description in this issue.

**Comment by danielmarbach** [comment]
Assigned @hmemcpy

**Comment by hmemcpy** [comment]
Thanks, I completely missed this one... I will extract the logic from queue creation to account for the remote queue as well...

**Comment by andreasohlund** [comment]
Moving this one into backlog until we decide its a prio and can get a taskforce on it

**Comment by hmemcpy** [comment]
@andreasohlund there's a PR waiting to fix this.
