### ISSUE TITLE
Should we allow messages to be sent within a suppress transaction scope inside the message handler if DTC is off?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2832]
When DTC is on, inside the message handler transaction scope it is possible to wrap either a send / publishing of a message within a suppress transaction scope to facilitate the messages to be sent  regardless of whether the message handler transaction succeeds or not. 
However with DTC off, this is not possible. 

Should we consider supporting this?

There was a recent desk case relating to this. https://nservicebus.desk.com/agent/case/12858
Related Issue: https://github.com/Particular/NServiceBus/issues/2752

**Comment by andreasohlund** [comment]
This is fixed in v6

http://docs.particular.net/nservicebus/messaging/send-a-message#immediate-dispatch

can we close this one?

**Comment by indualagarsamy** [comment]
@andreasohlund - do we have an acceptance test for this? Is this covered?

**Comment by andreasohlund** [comment]
Yes we have tests for this:

https://github.com/Particular/NServiceBus/tree/develop/src/NServiceBus.AcceptanceTests/Tx/ImmediateDispatch

**Comment by indualagarsamy** [comment]
Closing this as supported in v6.
