### ISSUE TITLE
Make the default concurrency limit set to "transport optimized"

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2833]
Right now and historically we have defaulted `max concurrency` to `1`. This essentially means that we never process messages in parallell. This has the following drawbacks

* Requires users to change defaults to get the best production throughput (violates the `production ready by default` idea, also reminds me of WCF where you had to tweak alot of setting to get it to work)
* Hides any threading issues for them, until they most likely are in production which causes tricky debugging

This also applies to us since I happened to run the acceptance tests allowing parallell processing and behold we have a few tests that are not thread safe :) eg. https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Sagas/When_a_base_class_message_hits_a_saga.cs

**Comment by andreasohlund** [comment]
@Particular/nservicebus @udidahan what do you think?

**Comment by udidahan** [comment]
Those are sound arguments.

**Comment by andreasohlund** [comment]
Since the code change is trivial, and the fact that we need to fix the doco around this any way as part of async, https://github.com/Particular/docs.particular.net/issues/816 , I belive this is a low hanging fruit and we need to do it in a major since its a breaking change.

Assigned to th 6.0.0

**Comment by danielmarbach** [comment]
@andreasohlund as discussed in the meeting I fully agree.

**Comment by andreasohlund** [comment]
v6 now does this, doco have been updated to reflect this https://github.com/Particular/docs.particular.net/pull/827
