### ISSUE TITLE
from MutateOutgoingTransportMessagesContext how do i get the incoming headers 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2836]

**Comment by andreasohlund** [comment]
We decideded to not allow headers to be read on the outgoing pipeline since the only headers that you can rely on to be there would be the one that you set your self. Close this one?

**Comment by SimonCropp** [comment]
> We decideded to not allow headers to be read on the outgoing pipeline. Close this one?

Sure. when that is captured in the upgrade guide and all the existing doco that voids that rule is updated to reflect that.

**Comment by andreasohlund** [comment]
Sorry misread, thought you where talking about the headers on the message you where mutating and not the incoming message
