### ISSUE TITLE
AutoSubscribe+ApplySubscriptions gets registered twice in the IoC

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#2840]
The Feature Startup task for AutoSubscribe is registered with the container as  part of the normal Features process [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Configure.cs#L103). It is also registered by the Setup of the feature itself [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs#L39).

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus/commit/a4b87bae340db7b4ff4ff480431b617e823474f1
