### ISSUE TITLE
LogicalMessageProcessingStageBehavior or Behavior<OutgoingContext>

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2845]
So looking at the current databus implementation in the core `LogicalMessageProcessingStageBehavior` and `Behavior<OutgoingContext>` are the same thing (for the incoming and outgoing)

So why the difference in API?

**Comment by danielmarbach** [comment]
We revamped the API entirely. I'd argue this has been solved with the stages that we introduced. Closing.

Feel free to reopen if you disagree.
