### ISSUE TITLE
Use original message body when dispatching from SLR

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#2850]
When moving a message to the error queue, the `MoveFaultsToErrorQueueBehavior` reverts the the body of the message to the original body (before using message mutators and so on) using this method on the `TransportMessage`: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/TransportMessage.cs#L126

When we defer a message from the `SecondLevelRetriesBehavior` we don't revert the message body. When the message is retried the message already contains the modified body and will be mutated a second time which can cause problems.

There are also some acceptance tests concerning SLR stating that reverting the message body is the desired behavior [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_regular_exception.cs) and [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_serialization_exception.cs).

I suggest we revert the message body when sending messages from the SLR.

**Comment by andreasohlund** [comment]
@Particular/nservicebus I think this is a patch + backport. We're corrupting data?

**Comment by danielmarbach** [comment]
I agree. And worth better ATTs?

**Comment by andreasohlund** [comment]
@timbussmann in what version was this bug introduced?

**Comment by andreasohlund** [comment]
I have a hunch this might be ok in v5 since SLR went through the FaultManager

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Faults/Forwarder/FaultManager.cs

and I think we did the "revert" before calling it

**Comment by timbussmann** [comment]
this is the original commit from john adding the revert logic: https://github.com/Particular/NServiceBus/commit/d3362205ab4652f830f5523d5345bfab11165859
code hasn't changed much regarding this as far as I can tell. At first glance it looks like it's working with v5 as long you use FLR since only FLR does the revert when handing over to FaultManager.

**Comment by andreasohlund** [comment]
Is it possible to create a failing v5 test?

**Comment by timbussmann** [comment]
Ok mistake, FLR isn't a `Feature` in v5, so no disabling it. But I think we only revert the body if we can't deserialize the body (but not if the mutator only changes some values). Going to write a test to verify.

**Comment by timbussmann** [comment]
Ok mistake, FLR isn't a Feature in v5, so no disabling it. V5 should be fine then and tests are in place.

**Comment by andreasohlund** [comment]
Phew, so add test and fix code for v6?

**Comment by timbussmann** [comment]
failing tests already in place since fixing acceptance tests :) Trying to fix this asap.
