### ISSUE TITLE
Repeat for multiple serializers is broken in AcceptanceTest

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2855]
using the release syntax and passing in multiple 

    .Repeat(r => r.For(Serializers.Json, Serializers.Xml)) 

Fails with `A queue with the same path name already exists.`

**Comment by SimonCropp** [comment]
@andreasohlund thoughts if this should still be a supported API?

**Comment by andreasohlund** [comment]
Starting to think that the repeat api isn't worth it and in the few cases we need to "repeat" we should just copy paste the test and configure the endpoint under test differently?

**Comment by andreasohlund** [comment]
But yes it should be supported

Are we running those permutations in paralell?

**Comment by SimonCropp** [comment]
I think the clean up of queues is killing the second run

**Comment by andreasohlund** [comment]
Hmm, why wouldn't the start up the second run create the q?

**Comment by SimonCropp** [comment]
Assuming the creation and deletion is not consistent.

**Comment by danielmarbach** [comment]
@SimonCropp is this still an issue with the new way how we cleanup the ATT runs?

**Comment by andreasohlund** [comment]
Pretty sure the queue cleanup is stable now in v6, please re-open if needed
