### ISSUE TITLE
Remove support for message throughput throttling

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2859]
### Background

We added throttling in v4 due to a license model that allowed users to buy a throttled down version. We used to throttle to 1 msg/s if no license was found but that limit was removed in v4.5 due to a bad implementation. The issue was that if you requested throughput throttling we also limited concurrency to 1 which caused issues if handlers had long execution time. This license limit sort of was converted to a "feature"

### Problems

Implementing this on the core/transport level is tricky since we need to have a generic enough solution that is good enough and safe for all use cases. 

#### Need to take concurrency into account

v5 is doing the throttling inside the pipeline by keepinging track of the number of "pipelines" that have completed per second. And when going past that we don't allow more pipelines to start for that second. The problem here is that the transport is still pushing messages when this happens and if the endpoint is transactional the "commit" will be delayed until the message in flight is allowed to complete. This can turn into issues with transaction timeouts if you don't also tune the concurrency appropriately. So to do this properly we need to start passing the throughput limit to the transport to allow it to optimize. This makes the transports more complex. Most of the time its really on the users who can find the right balance btw concurrency and throughput limits based on their scenario. 

Which leads us to the next problem.

#### It's not suitable for real world use cases

If you lookt at eg. gihub they rate limit on messages per hour,  https://developer.github.com/v3/rate_limit/, so our api is useless here since you can't really use a msg/s limit to mimic this efficiently. The fix here would be to make the "period" configurable. This would make the api even more complex and we also have to decide what periods to support since we store the actual values inmemory and longer periods means that endpoint restarts/crashes would mean we loose track of state and thereby not honoring the setting. Making this durable would also complicate things further.

#### It's endpoint wide

Yes we can always guide users to use separate endpoints for all msg types but if they go with a single endpoint per integration thottling the entire endpoint isn't suitable. We are actually exposed to this our self since out own GH integration endpoint is doing a send local for incoming webhooks. So we'd want that to be unlimited while outgoing ones should be rate limited. This means that if not all messages handled should be throttled our api isn't good enough. Adding that would further complicate it.

This would be better handled by a sample showing the users how to inject their "rate limiter" into selected handlers to get the exact scope they want.

### Examples of others doing this

The only one I could find was a contrib module for akka.net using a timer http://doc.akka.io/docs/akka/snapshot/contrib/throttle.html

### Proposal

- [x] Deprecate msg/s throttling as of v6
- [x] Update doco with above mentioned caveats
- [x] Provide samples, docs on how to do throttling based on real life scenarios ( I propose the github rate limit) https://github.com/Particular/docs.particular.net/pull/1126
- [x] Update the upgrade guide

**Comment by andreasohlund** [comment]
@Particular/nservicebus thoughts?

**Comment by danielmarbach** [comment]
I already said my :+1: in the call

**Comment by wolfbyte** [comment]
After our discussion the other day I don't like the current implementation (for the reasons that you mentioned). I'm +1 for deprecating it

**Comment by dannycohen** [comment]
@danielmarbach - Good argument for deprecating it. :+1

**Comment by SzymonPobiega** [comment]
burn it! Also, why do we need the other concurrency setting (`max concurrency`)?
 * it allows to fine-tune the transport to achieve highest possible receive throughput -- arguably we can do it better inside the transport.
 * it allows to fine-tune the resource usage. Same argument as here applies -- since the setting is global, it is close to useless for capping the resource usage since handlers are usually different

**Comment by andreasohlund** [comment]
>burn it! Also, why do we need the other concurrency setting (max concurrency)?

Interested. lets try to play the devils advocate

>it allows to fine-tune the transport to achieve highest possible receive throughput -- arguably we can do it better inside the transport.

Isn't this exactly what v6 will do, Ie by default let the transport optimize for max performance?


>it allows to fine-tune the resource usage. Same argument as here applies -- since the setting is global, it is close to useless for capping the resource usage since handlers are usually different

I see that my own argument holds here, what about the non thread safe component? (Just guide the users to put a lock around the invocation?)

**Comment by ramonsmits** [comment]
I'm not in favor of dropping throttling support. In the past I made integration endpoints that called rate limited API's. The throttling made sure that I didn't have to code any rate limiting code. Just configure the endpoint and done.

Maybe the implementation can be improved but just removing would break such features dependencies.

**Comment by andreasohlund** [comment]
What if the rate limit, like GH, is on requests per hour?

**Comment by danielmarbach** [comment]
@ramonsmits we didn't remove it. You can still control the concurrency

**Comment by andreasohlund** [comment]
Slack conv with @ramonsmits 

Regarding throughput: We currently support you throttling on msg/s, what if you're calling something that has a limit on calls/h? (like eg. GitHub)

andreas [1:38 PM]
The feature was never really used and hard to implement, hence the idea is to show users how to do implement throttling tailored to their needs instead of providing a half baked one?

ramon [1:41 PM] 
@andreas: msg/s == calls/h

ramon [1:41 PM]
Its just a different divisor

andreas [1:42 PM] 
what if you crash after 30 min?

ramon [1:43 PM] 
3600/h == 1/s right?

andreas [1:43 PM] 
For longer periods we need to be durable => can you see how this feature gets more and more complicated

ramon [1:43 PM] 
So yes, it does not make use of the fact that potentially you have still ‘room’ in  your current rate window

andreas [1:44 PM] 
So if you have a burst of messages why would you not process them as fast as possible as long you're within the quota?

ramon [1:44 PM] 
yes, that would be better but more advanced.

ramon [1:45 PM]
Its not that I don’t agree :simple_smile:

andreas [1:45 PM] 
So instead of us having a leaky abstraction wouldn't it be better to create a few samples that shows a few different ways of doing this?

ramon [1:45 PM] 
Its that very simple rate limiting is probably enough in lots of environments

andreas [1:45 PM] 
Eg to use a saga for durable throttling

andreas [1:46 PM]
And with GH they return what the current quota is so you can use that to recover from a crash

andreas [1:46 PM]
Also if you are maxed out you would most likely want a custom check to raise awareness

ramon [1:46 PM] 
Again, its not that I don’t agree with better implementations.

andreas [1:47 PM] 
and perhaps defer messages to keep them clogging up the queue

ramon [1:47 PM] 
But, if only I need a skateboard that was already there in my backyard, then why do you force me to now build my fighteryet?

ramon [1:47 PM]
That is the point that I want to make :simple_smile:

andreas [1:48 PM] 
If you're lucky enough that NSB has the exact skateboard you need you can use it, but most likely it won't fit you and you would fall down and hurt your back :simple_smile:

ramon [1:48 PM] 
lol

andreas [1:49 PM] 
Instead we guide you what skateboard to buy to get the one that fits you and not the swiss army knife skateboard :wink:

**Comment by ramonsmits** [comment]
@danielmarbach I only read that you can control concurrency, not throttling.

**Comment by ramonsmits** [comment]
I asked @timbussmann this question "Is the pipeline in V6 pluggable in such a way that a customer would be able to build this feature if they would like to have throughput limiting?"

I already mentioned that in the past I relied on this feature due to the other end had implemented a rate limit. By relying on this feature it was possible comply to this in minutes by enabling throttling.

However, there are also other types of reasons for having this. There are numerous firewalls and servers that just auto block you when you are DOSSíng a service due to a huge amount of requests. This can easily happen after network outage for example when a backlog of a email campaign is not delivered yet. The receiver does not have a rate limited API at all so you cannot have any logic that calculates rate or update rate info based on the response headers.

In such scenarios you don't need the added complexity of a saga at all.

**Comment by ramonsmits** [comment]
Another example, the Google Maps API. it has both an API rate limit and a request rate limit:

https://developers.google.com/maps/premium/usage-limits?hl=en

> Shared* daily free quota of 100,000 requests per 24 hours; additional requests applied against the annual purchase of Maps APIs Credits. Maximum of 23 waypoints per request. Rate limit of 50 requests per second.

Do you really want to implement the rate limiting per second via a saga @andreasohlund ?

**Comment by timbussmann** [comment]
It seems there are many possibilities to use existing extension points (handlers, sagas, behaviors) to implement a custom throttling. The question is, how is throttling implemented in the first place? `HandleCurrentMessageLater()` or `Defer()` or even `await Task.Delay`? I think we can't define a single, proper way to do it without knowing about the custom scenario. The question is, do we need a "deeper" extension point than a custom behavior?

**Comment by SimonCropp** [comment]
@ramonsmits 

> I already mentioned that in the past I relied on this feature due to the other end had implemented a rate limit. By relying on this feature it was possible comply to this in minutes by enabling throttling.

I believe @andreasohlund  considered this case and decided it was not actually possible to do in a non-buggy way due to the in memory state. @andreasohlund can u confirm.

**Comment by andreasohlund** [comment]
> @andreasohlund can u confirm.

Yes, the idea is to instead show them (using samples/doco/etc) different ways of throttling and the pros and cons of each approach ( exactness, durability, perf implications etc) to allow the user to select the best approach for his specific problem since I don't see a way for us to provide a generic solution that works well in all scenarios.  

Based on that guidance we can decide if we want to provide throttling in some kind of `NServiceBus.ThroughputThrottling` package in the future.

I propose creating said guidance should be in the scope of this change.

Does this make any sense?

**Comment by ramonsmits** [comment]
ServiceControl uses message throttling (350msg/s) by default to prevent RavenDB indexes to not get stale. Will SC copy this sample in its code base when SC will be migrated to V6?

@johnsimons mentioned that the current sample would not work for SC.

Also, there are probably customers using throttling to reduce IO on certain infrastructure too. Again, I'm againts removing this feature.

**Comment by andreasohlund** [comment]
>Will SC copy this sample in its code base when SC will be migrated to V6?

I'd say yes, it makes sense for SC to have its own custom throttling tailored to its needs? Eg should we throttle across both errors and audits? what about saga audits? (not saying we should do it just highlighting that there might be a need to throttle across more than one queue since Raven is the bottleneck)

>@johnsimons mentioned that the current sample would not work for SC.

Not surprised, coming up with a generic throttling that works for all scenarios if impossible so lets build one that works for SC?

>Also, there are probably customers using throttling to reduce IO on certain infrastructure too. 
Then lets help them achieve that? how can we improve?
