### ISSUE TITLE
When features are deactivated due to prerequisite failure, they should be logged as WARN

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2861]
Currently, what features are enabled in the core is listed as INFO level statements. 
However, if a feature becomes disabled due a pre-requisite not being met, then those should be logged as warnings instead. 

E.g. Starting with v2 of ServiceControl.Plugin.Nsb5.Heartbeats, send only endpoints aren't supported. This information shows up only with INFO level logging and gets filtered out if the level is set to WARN and higher. This would be useful for debugging when logged as a WARN as opposed to INFO.

**Comment by timbussmann** [comment]
+1

**Comment by andreasohlund** [comment]
Can we collect some more examples? (since eg. Sagas is disabled if no sagas are found, I don't think that should be logged as warn?)

**Comment by indualagarsamy** [comment]
If a feature is explicitly enabled by the user in the bus configuration, failure of any kind to enable that should be a warning. I think this comes in because, we can't differentiate how we use features internally within our API vs users enabling them externally ?

**Comment by timbussmann** [comment]
@indualagarsamy but SC plugins for example aren't explicitly enabled (in code) by the user.

What about logging with *WARN* and add a hint for certain features (e.g. Saga) to explicitly disable them if not used?

**Comment by indualagarsamy** [comment]
SC plugin is something that's like external use of the API?

**Comment by timbussmann** [comment]
I meant that installing a plugin NuGet package is basically an explicit "enable" from the user which we currently can't differentiate from other "built in" plugins (while we could do that with `config.EnableFeaure<T>()`).

**Comment by timbussmann** [comment]
quick glance at some features, these are some reasons a feature is disabled by a Prerequisite check:
* feature isn't support on send-only endpoints
* the feature hasn't been configured (e.g. some destination queue)
* the feature has a config which basically renders it useless (maxretries = 0 on FLR)
* the feature has been disabled via config (e.g. SLR)
* no transactions available
* the transport supports the feature native
* the endpoint is a worker node and uses the feature on the master node

**Comment by andreasohlund** [comment]
I'm still not convinced we should WARN here. Perhaps we could add a flag to the prereq if its should log WARN?

Or in the case @indualagarsamy mentions just remove the prereq and just throw/log in `Setup` if the endpoint is sendonly?

**Comment by indualagarsamy** [comment]
@andreasohlund - I'm good with the throw for SendOnly in the use case I mentioned.

**Comment by timbussmann** [comment]
I don't think we should throw from the plugin, since it depends on the core version if it supports send-only endpoints. That's not a plugin decision. If the core changes I don't want to change the plugin again only because I have to remove the throw.

But then let's stay with the *INFO* for now.

**Comment by indualagarsamy** [comment]
@timbussmann - sounds good.
