### ISSUE TITLE
Run FeatureStartupTasks for Send-Only endpoints

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#2869]
In NSB v5 `FeatureStartupTasks` are started and stopped via `IWantToRunWhenBusStartsAndStops` implementation. `IWantToRunWhenBusStartsAndStops` implementations are only executed on regular endpoints (not on Send-Only endpoints). Therefore startup tasks won't be started on Send-Only endpoints. This seems to have changed for v6, where the tasks are started when initializing the bus.

The following features in core use startup tasks which aren't run on Send-Only endpoints:
* AutoSubscribe: task subscribes to events - shouldn't be an issue for Send-Only
* Outbox: task reports a warning if DTC runs - not critical
* DataBus: task starts the DataBus - seems critical at first glance
* ~~InMemoryOutboxPersistence: task cleans old entries from memory - potential memory leak~~ *Edit: Outbox is a phenomenon of the incoming message pipeline so isn't needed for send-only. - David Boike*

I don't know if there are more startup tasks in other repos. One for example is the Heartbeat plugin v2 which won't send heartbeats on Send-Only endpoints.

Would it be possible to backport the v6 implementation for starting `FeatureStartupTask` to v5?

**Comment by andreasohlund** [comment]
>AutoSubscribe: task subscribes to events - shouldn't be an issue for Send-Only

Autosubscribe isn't relevant for send only so this should be ok

>Outbox: task reports a warning if DTC runs - not critical

Same here should not be enabled

>DataBus: task starts the DataBus - seems critical at first glance
Since the cleanup is the responsibility of the receiver this should not be running on send only endpoints (the cleanup that is) The databus it self should be enabled though, perhaps we need to split the features?

>InMemoryOutboxPersistence: task cleans old entries from memory - potential memory leak

See above, outbox not used if sendonly

**Comment by timbussmann** [comment]
so only DataBus remaining as potential bug and open to verify then?

**Comment by andreasohlund** [comment]
Yes

**Comment by timbussmann** [comment]
The `FileShareDataBus` and `InMemoryDataBus` start methods are currently no-ops, therefore no issue with them. But the Azure DataBus does some things in `Start()` therefore that wouldn't work with Send-Only in v5.

**Comment by timbussmann** [comment]
we need to decide if this is a bug or not in order for communicate the heartbeats plugin v2 release.

**Comment by andreasohlund** [comment]
>But the Azure DataBus does some things in Start() therefore that wouldn't work with Send-Only in v5.

Are those things needed for the sends to work?

**Comment by timbussmann** [comment]
note sure, @SeanFeldman may can clarify this.

Imho, even if no feature in v5 is affected by that issue, I still view it as a bug. Not a severe one for sure, but I'd say the Feature API doesn't behave as expected.

**Comment by SeanFeldman** [comment]
@timbussmann we're not using a startuptask with azure databus
https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/blob/master/src/DataBus/AzureDataBusPersistence.cs

**Comment by wolfbyte** [comment]
If we do not fix it then we should update the docs on features to describe
the different behaviors.
http://docs.particular.net/nservicebus/pipeline/features

**Comment by timbussmann** [comment]
@SeanFeldman But the DataBus is started by a startup task. Therefore https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/blob/master/src/DataBus/Azure/BlobStorage/BlobStorageDataBus.cs is never started on Send-Only clients. So is that an issue for Send-Only clients using AzureDataBus?

**Comment by danielmarbach** [comment]
The `FeatureStartupTasks` should not be started with the `IWantToRunWhenTheBusStartsAndStops`. We need to fix that.

**Comment by danielmarbach** [comment]
It should be a first class citizen like it is now in v6

**Comment by andreasohlund** [comment]
Since v6 have this fixed I'm closing this as done. Please reopen if you want to propose a backport

**Comment by timbussmann** [comment]
> This is a bug we should get fixed in V5.

I tend to agree with @DavidBoike. I vote for reopening.

**Comment by andreasohlund** [comment]
Not pretty but there is a workaround:

`timer.Start(_=>bus.Send("servicecontrol",JSonConvert.Serialize(new EndpointHeartbeat())))`

where EndpointHeartbeat =>
https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/develop/src/ServiceControl.Plugin.Nsb5.Heartbeat/Messages/EndpointHeartbeat.cs

would that be enough?
