### ISSUE TITLE
task.completedtask in acceptance tests 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2879]
Just a placeholder

use `task.completedtask` instead of `Task.FromResult(0)` in acceptance tests after the build server is updated to vs2015
https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.completedtask(v=vs.110).aspx

**Comment by danielmarbach** [comment]
@SimonCropp this would mean we need to update to 4.6 on the ATT proj. I propose we do this for the next major release as a whole. Thoughts?

**Comment by SimonCropp** [comment]
@danielmarbach yep. I forgot the 4.6 bit

**Comment by danielmarbach** [comment]
Keep it as a reminder or close?
