### ISSUE TITLE
MutateIncomingMessageContext cancel message processing

### ISSUE THREAD

**Issue by marinkobabic** [Particular/NServiceBus#2914]
Inside of the devevop branch I don't see a way to cancel the processing of the message inside of a IMutateIncomingMessages like this is privided by HandlingStageBehavior.Context.DoNotInvokeAnyMoreHandlers(). 

ContextualBus contains the following method, but this expects that the context is HandlingStageBehavior.Context:

```c#
public void DoNotContinueDispatchingCurrentMessageToHandlers()
{
  ((HandlingStageBehavior.Context)incomingContext).DoNotInvokeAnyMoreHandlers();
}
```

* The idea is to validate the message and notify whatever service about validation result and to cancel the processing of the message if the message validation result is invalid.

* Another scenario is to implement custom authorization and to cancel the whole process if the authorization data is invalid.

Actually the only way I see is to tell the bus to use a fix first message handler and to perform the job inside of this handler.

**Comment by danielmarbach** [comment]
@marinkobabic We considerably revamped the APIs. Currently the mutator context passed into the mutator doesn't allow you to stop the message handling pipeline. In theory you should be able to achieve this by adding a behavior the `IIncomingLogicalMessageContext` stage of the pipeline. For me it smells to allow such advanced behavior inside a mutator. That is not the intention of the design of mutators.

**Comment by marinkobabic** [comment]
@danielmarbach The idea was inside of the mutator to validate the logical message. If the message is not valid to stop the pipe. Have solved it now by doing it in the first handler. The problem is that it used to work and then in the following version not. Please add some documentation what the purpose of this method is and when it should be used and where it's not supposed to be used.

**Comment by danielmarbach** [comment]
I opened up a documentation issue. Closing this one
