### ISSUE TITLE
Misleading error when messages do not implement IMessage

### ISSUE THREAD

**Issue by pawelpabich** [Particular/NServiceBus#2931]
Hi,

I forgot to implement IMessage on my messages that are registered explicitly using custom configuration source.
```
       mappings.Add(new MessageEndpointMapping()
            {
                AssemblyName = typeof(Message1).Assembly.GetName().Name,
                TypeFullName = typeof(Message1).FullName,
                Endpoint = "Queue1",                
            });
```

When I run the app I get "An exception of type 'System.InvalidOperationException' occurred in NServiceBus.Core.dll but was not handled in user code
Additional information: No destination could be found for message type NServiceBusPoC.Message1. Check the <MessageEndpointMappings> section of the configuration of this endpoint for an entry either for this specific message type or for its assembly." 

I find this error message misleading. I would expect to get a message that tells me that Message1 is not implementing IMessage interface. Ideally I would get this error when the bus is created and not when I try to send a message.

```
<packages>
  <package id="NServiceBus" version="5.2.6" targetFramework="net45" />
  <package id="NServiceBus.SqlServer" version="2.2.0" targetFramework="net45" />
</packages>
```

Thoughts?

**Comment by andreasohlund** [comment]
@SzymonPobiega will #2565 address this by any chance?

**Comment by SzymonPobiega** [comment]
Let's add it as a test case when we merge the next bit and see how it behaves. Thanks @pawelpabich !

**Comment by pawelpabich** [comment]
Thanks guys

**Comment by timbussmann** [comment]
@SzymonPobiega is this still an issue with v6?

**Comment by SzymonPobiega** [comment]
@timbussmann not sure. I guess it is worth an acceptance test. What happens if you configure routing for a non-message type?

**Comment by timbussmann** [comment]
* When configuring a route on the code first API for a non-message-type it will throw a "route not found" exception when sending that type.
* When configuring a route on the MEM for a non-message-type it will throw a "Could not find metadata" exception when sending that type.

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers since @timbussmann is gone for a couple of days and I wanted to implement this -- what should we do when we configure routing for assemblies/namespaces? In V5 we were ignoring routing for non-message types.

Also, there is no easy way to fix this with MEM routing because MEMs are implemented in such a way that they use a callback to inform calling code that a type should be routed but there is no context if that type comes from a type-specific mapping or some kind of general (assembly/namespace) mapping.

**Comment by andreasohlund** [comment]
> what should we do when we configure routing for assemblies/namespaces?

How about we throw if there isn't any message at all found in the asm/ns? (since that most likely means a config mistake)

**Comment by SzymonPobiega** [comment]
@andreasohlund what should we do where there are some messages and some non-messages? We have that situation in the samples where the `Shared` project contains both messages and some helper non-message classes.

**Comment by andreasohlund** [comment]
Talked to @SzymonPobiega about this and we don't see enough value with the check. The idea is instead to verify that we throw a helpful exception should you try send/publish a "non message".


@SzymonPobiega will create a acceptance test for this

**Comment by SzymonPobiega** [comment]
Addressed by https://github.com/Particular/NServiceBus/pull/4090
