### ISSUE TITLE
Deprecate `TransportMessage` entirely and use `IncomingMessage` and `OutgoingMessage` where appropriate

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2933]
I did a quick spike today it should be possible to no longer use `TransportMessage` in the core and only used the typed `IncomingMessage` and `OutgoingMessage`. As soon as [batching of outgoing operations](https://github.com/Particular/NServiceBus/pull/2912) is merged we can pull this off.

**Comment by andreasohlund** [comment]
:heart:

**Comment by danielmarbach** [comment]
Done and [documented](http://docs.particular.net/nservicebus/upgrades/5to6#deprecated-transportmessage)
