### ISSUE TITLE
SLR persistence concerns

### ISSUE THREAD

**Issue by udidahan** [Particular/NServiceBus#2935]
Following up on Szymon's [comments in the discussion group](https://groups.google.com/d/msg/particularsoftware/H3J9B3L1fZ8/kr0CxebtBgAJ):

> One more (maybe obvious) thing to remember is the SLR depends on the delayed delivery (a.k.a. timeouts) so if you enable the SLR for your endpoint (the default), you need to configure a real persistence mechanism. Otherwise you are risking losing messages when your endpoint crashes while there are messages waiting for the SLR to retry them.

I'd say that this is far from obvious and leaves users open to the message loss scenario described.

We should do something about this.

**Comment by SzymonPobiega** [comment]
For now (plugging the hole) I've added a warning to the doco (http://docs.particular.net/nservicebus/persistence/) but I agree we should do something more about this.

**Comment by danielmarbach** [comment]
@SzymonPobiega @udidahan we had various discussions in the past that the timeout storage should be part of the transport infrastructure and not a core concern. A generic timeout manager doesn't fit anymore our multi-transport landscape. 

If you feel we should address this, can you flesh out the description and ping the `Particular/tf-v6-launch`

@SzymonPobiega @tmasternak can you link to the relevant timeout manager issues in Platform Development?

**Comment by tmasternak** [comment]
#3532 is the result of discussion about `TimeoutManager`. The idea is to make sure we can exchange the generic implementation with a different one (potentially native for given transport) is minor releases of V6.

**Comment by SzymonPobiega** [comment]
Since #3532 is done, this one can now be happily parked and revisited after the V6 release.

**Comment by timbussmann** [comment]
>  you need to configure a real persistence mechanism

We always force users to define a persistence mechanism and strongly discourage from using InMemoryPersistence in production since it not only causes data loss for scheduled messages. So what do we need to change especially about SLR which does not affect other persistence storages?

**Comment by andreasohlund** [comment]
What action points, if any, do we see here?

**Comment by SzymonPobiega** [comment]
@andreasohlund 
1. Decouple SLR from delayed delivery
2. Implement native delayed delivery in the transports that don't have it

**Comment by andreasohlund** [comment]
Do we have issues for ☝️ ? (close this?)

**Comment by SzymonPobiega** [comment]
@andreasohlund Issues raised: https://github.com/Particular/PlatformDevelopment/issues/969, https://github.com/Particular/PlatformDevelopment/issues/970
