### ISSUE TITLE
Provide an api to detect events being published with no subscribers

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2936]
We had an undocumented feature in v5 where users could get access to this info via:

```
           SubscribersForEvent subscribersForEvent;

                if (context.TryGet(out  subscribersForEvent))
                {
                    //do someting
                }

```

As part of https://github.com/Particular/NServiceBus/pull/2912 this has now been deprecated since we need to modify it to support batches of events.

Should we provide a new api for v6?

Perhaps using the `BusNotifications` is a better idea?

Note that this api would have to be for transports without native pub sub only since for Rabbit and ASB this will happen inside the broker making the info hard to get at.

**Comment by danielmarbach** [comment]
Closing this. Cross-reference it in the new notifications proposal.

https://github.com/Particular/PlatformDevelopment/issues/605
