### ISSUE TITLE
Acceptance Tests should have different fail semantics

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2947]
Currently we let acceptance tests fail whenever there is a log entry written with an exception and the test didn't specify `AllowExceptions`. @timbussmann and I propose to change this behavior to the following:

* Remove the SecondLevelRetries from the AcceptanceTests when not explicitely testing something related to SLR
* Still trace `Exceptions` on the `Context` but do not fail the tests
* Only fail the tests if a message is sent to the error queue

This allows us to use transient failure handling of the core. If we have a permenant failure then the test would still fail because of error handling.

These tests would be much more realistic to production scenarios.

@Particular/nservicebus thoughts?

**Comment by SzymonPobiega** [comment]
:+1: if we can figure out how to effectively detect messages in the error queue.

**Comment by andreasohlund** [comment]
We should be able to use the `BusNotifications` for this?

**Comment by timbussmann** [comment]
@andreasohlund :+1: that's also what I was thinking about

**Comment by danielmarbach** [comment]
Agree. But I have a hunch we need a more composable approach replacing
BusNotifications when we move to capabilities



-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by andreasohlund** [comment]
You mean like proposed in
https://github.com/Particular/PlatformDevelopment/issues/323 ?

**Comment by danielmarbach** [comment]
@andreasohlund :dancer:

**Comment by danielmarbach** [comment]
@timbussmann @andreasohlund I think we have that implemented. Closing. Feel free to reopen if necessary
