### ISSUE TITLE
RabbitMQ transport, XML Serializer and message conventions: unusable endpoint

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2951]
A basic configuration, such as the following:

```
var config = new BusConfiguration();
config.UsePersistence<InMemoryPersistence>();
config.UseTransport<RabbitMQTransport>();
config.Conventions()
    .DefiningCommandsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Commands" ) )
    .DefiningEventsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Events" ) )
    .DefiningMessagesAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Messages" ) );

using( Bus.Create( config ).Start() )
{
    Console.WriteLine( "Bus started..." );
    Console.Read();
}
```

using these packages:

```
<packages>
  <package id="NServiceBus" version="5.2.6" targetFramework="net46" />
  <package id="NServiceBus.RabbitMQ" version="3.0.0" targetFramework="net46" />
  <package id="RabbitMQ.Client" version="3.5.5" targetFramework="net46" />
  <package id="Radical" version="1.5.2.1" targetFramework="net46" />
</packages>
```

creates an endpoint that does not startup, raising the following exception:

```
An unhandled exception of type 'System.NotSupportedException' occurred in NServiceBus.Core.dll

Additional information: IDictionary<T, K> is not a supported property type for serialization, use Dictionary<T,K> instead. Type: RabbitMQ.Client.IBasicProperties Property: Headers. Consider using a concrete Dictionary<T, K> instead, where T and K cannot be of type 'System.Object'
```

There are 2 undiscoverable workarounds:
- change the default XML serializer to, for example, `json`;
- exclude the rabbit types from the message convention;

**Comment by andreasohlund** [comment]
I know @DavidBoike has always proposed to have some convention helpers that excludes `NServiceBus.*, RabbitMQ.*` types by default. Problems is that this is hard to maintain since we have to constantly keep on adding any downstream dependency that we have :(

Eg. someone using the community mongodb persister would probably get the same error for some types in the mongo client

**Comment by mauroservienti** [comment]
> I know @DavidBoike has always proposed to have some convention helpers that excludes NServiceBus.*, RabbitMQ.* types by default. Problems is that this is hard to maintain since we have to constantly keep on adding any downstream dependency that we have :(

can't this be done at downstream dependency level?

* the transport package knows which types should be in the conventions and which should not
* the transport package can register its own conventions that will be evaluated with (`AND`) the user defined ones
* since responsibility is at the dependency level the `dependency committers` knows when/how to update the downstream conventions to reflect changes in the dependency downstream dependencies.

**Comment by DavidBoike** [comment]
@mauroservienti I like that. It puts the responsibility where it belongs. If I invited someone to the party, I should be held responsible if he decides to get drunk and throw someone through a window.

**Comment by danielmarbach** [comment]
@Particular/transport-maintainers Any ideas how to proceed with this? Any chance we can solve this in rabbit directly?

**Comment by mauroservienti** [comment]
IMO my proposal is a viable option, solves the issue at the transport package level.

**Comment by bording** [comment]
Looks like the quick fix would be to add `RabbitMQ.Client` to [this array](https://github.com/Particular/NServiceBus/blob/5d8c6c03b6ae8815a800d1c560440e82004a484b/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L436).

I'm not sure there is anything that could be done solely at the transport level. I didn't see anything that would indicate that the transport assemblies are themselves excluded from scanning, so even doing something like ILMerging the client wouldn't help.

Anything else would require adding a hook into something like the `TransportDefinition` to let the transports specify excluded assemblies/types and then pass them into the `AssemblyScanner` along with the user-supplied values. This would need to happen at a point early enough to let the transport participate, which looks like it would be fairly easy to do.

If the transport could specify assemblies and types to be excluded, would there be a reason to also let it add conventions? Seems unnecessary to me.

**Comment by danielmarbach** [comment]
Yes it would be a quick fix. But I'm sure we should make a proper fix. In the interesting of improving the current situation I'm OK to add the client to the scanner default includes though.

**Comment by dbelcham** [comment]
Closing because the workaround of "excluding the RabbitMQ types in the convention" is considered the right way to solve this problem.
