### ISSUE TITLE
Avoid outages caused by error queue messages being too large

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus#2953]
*Spun off from https://github.com/Particular/NServiceBus.RabbitMQ/issues/102*

### Problem

When an exception is thrown from a handler and the exception message is large, the error message we create and send to the error queue may cause the transport to refuse the message since we copy the exception message into the headers. In this scenario the endpoint is stopped and the original message remains in the queue.

In https://github.com/Particular/NServiceBus/issues/2956 we hardcoded the error message size limit to 16,384 to overcome an immediate problem for a customer using the RabbitMQ transport but this does not fix the problem generally.

Note that the original problem was not entirely fixed by the patch containing #2956. The fate of this feature is tied into the resolution of #3023.

### Plan of Attack

- [ ] *TBD*
- [ ] Prepare docs
- [ ] Prepare announcement
- [ ] Release
- [ ] Publish docs

**Comment by SeanFeldman** [comment]
:+1: This will be very welcomed by ASQ transport that can have no more than 64K in size (message + headers).

**Comment by johnsimons** [comment]
This is actually also an issue for audit messages since we add extra headers/metadata to the message being forwarded!

**Comment by johnsimons** [comment]
@adamralph see https://github.com/Particular/PlatformDevelopment/issues/219

**Comment by adamralph** [comment]
Duplicate of https://github.com/Particular/NServiceBus/issues/2368
