### ISSUE TITLE
Passing `ContextBag` instead of `ReadOnlyContextBag` to the downstreams

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2955]
@danielmarbach you made a case for the context beeing readonly but after seeing what @timbussmann had to do in order to do the TM patch I believe we should make them read/write to allow the downstreams to set context info.

Thoughts?

Also I think we removed the `Set("key","value")`posibility in v6, I think we have to add that back in order to do "stringly typed" apis for situations like @timbussmann 's described above?

**Comment by timbussmann** [comment]
the ability to add new key/values helped much in that scenario. It would probably suffice to only allow writing new values, but that could also be quite an overkill.

**Comment by danielmarbach** [comment]
If there are valid scenarios to make it non-readonly then let's open it up
