### ISSUE TITLE
Create binary and bson serializers repos+nugets

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2966]
Placeholder for v6 

related to https://github.com/Particular/NServiceBus/pull/2965

**Comment by johnsimons** [comment]
Should we wait and see if we actually need them ?

**Comment by danielmarbach** [comment]
:+1:

**Comment by danielmarbach** [comment]
I removed the milestone from this issue.

**Comment by SimonCropp** [comment]
no longer relevant
