### ISSUE TITLE
Circuitbreaker for timeout storage connectivity is using the wrong default

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2994]
The change to [make it configurable](https://github.com/Particular/NServiceBus/issues/1228) seems to have changed it from 2 minutes to 2 seconds by misstake.

This is causing the endpoints to shutdown if there is a short glitch in connectivity.

### Who's affected

All users on `5.1.0` and up

### Symptoms

The endpoint is shutdown if storage is unreachable for more than 2 seconds

### Workaround

Specify a explicit timeout value http://docs.particular.net/nservicebus/errors/critical-exception-for-timeout-outages

### Original report

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/SI2T6SH8un0/yitr1H1ADwAJ

**Comment by indualagarsamy** [comment]
So the proposed change would be to fix it here? From 2 seconds to 2 minutes.
https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Timeout/TimeoutManager.cs#L16

**Comment by andreasohlund** [comment]
Yes, and also add a acceptance test that fakes a bad persister

**Comment by indualagarsamy** [comment]
@colin-higgins - Can you ping me if you have questions?

**Comment by colin-higgins** [comment]
This was included with Ramon's #423 fixes as well as the acceptance test.

**Comment by timbussmann** [comment]
@colin-higgins @andreasohlund @indualagarsamy seems like this was not merged to v6?

**Comment by andreasohlund** [comment]
@timbussmann code on develop looks ok https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L17

close this?

**Comment by timbussmann** [comment]
yup, since this was "backported" to v6, we can close this again :+1:
