### ISSUE TITLE
Round robin tests are flaky on the buildserver

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3003]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Routing/When_distributing_a_command.cs#L10

Disabled it for now

**Comment by timbussmann** [comment]
failing assertions or exceptions while running the test?

**Comment by johnsimons** [comment]
This one seems to work fin against Rabbit impl

**Comment by timbussmann** [comment]
@janovesk you seem to be assigned to this. Is this fixed meanwhile?

**Comment by danielmarbach** [comment]
Unassigned @janovesk

**Comment by danielmarbach** [comment]
The test has [been moved to MSMQ specific tests ](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Msmq.AcceptanceTests/When_distributing_a_command.cs)and it seems it is fixed. We can reopen or fix is as part of https://github.com/Particular/PlatformDevelopment/issues/814 if the problem occurs again.
