### ISSUE TITLE
LicenseManager breaks acceptance tests

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3015]
The LicenseManager works with statics variables. One of them contains the license it reads from a source during the `InitializeLicense()` method. But certain code paths let `InitializeLicense()` not set that license variable. While that doesn't seem to be a problem at first, since all access to that license checks it for null, it also doesn't reset the variable correctly if an expired license was found. 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Licensing/LicenseManager.cs#L91

This shouldn't be an issue for normal endpoints, but in the acceptance tests the static is shared over different tests and the following scenario can happen:

- Test1: Reads valid license -> license stored in static variable
- Test1: Calls `HasLicenseExpired()` which reads the static variable containing the valid license.
- Test2 (testing invalid license handling): Reads an expired license -> license is not reset (not set any value)
- Test2: Calls `HasLicenseExpired()` which reads the static variable still containing the valid license.
- => Code assumes a valid license and does not setup `LicenseReminder` feature correctly which fails the test.

this can only be reproduced if the test is run in combination with a different test running before. Not sure yet why this doesn't fail on the build servers.

**Comment by SimonCropp** [comment]
Instead of putting it in the container why not make the license config api static as well?  I still see no reason to have a per bus license. Not for testing and not for runtime. This is how logging works

**Comment by timbussmann** [comment]
@SimonCropp the intent of this PR was mainly to fix a constantly failing ATT and not to change the API.The statics before this PR didn't work in a endpoint independent way. Let's open a new issue for suggested API changes?
