### ISSUE TITLE
Polymorphic collections (and other types) not supported by xml serialization

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3016]
Now we are not able to properly send xml message with polymorphic collections inside. See and example here: https://stackoverflow.com/questions/33102336/nservicebus-messages-with-properties-of-base-type/33158227#33158227

**Comment by ramonsmits** [comment]
The Json serializer works without any issues. I'm not sure that @hmemcpy suggestion will work as this maybe requires the use of the DataContract serializer. We should compare theire strengths and weaknesses and to my understanding system xml serializer is already there:

http://docs.particular.net/platform/extensions#serializers

**Comment by andreasohlund** [comment]
Since json works and we don't want to promote users crafting complext message contracts should we close this as won't fix?

**Comment by tmasternak** [comment]
I don't think we need to fix this one.

**Comment by andreasohlund** [comment]
Closing this one as `Won't fix`
