### ISSUE TITLE
Memory leak due to race condition in MSMQ MessagePump v6

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3033]
In [MessagePump.cs](https://github.com/Particular/NServiceBus/blob/7952153ff7e433bfa72b4dc0e90c8b98bc1aac77/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L196) we are adding continuation to processing task after adding task to receive task collection. That might cause a situation when the continuation will fire before the element is added to collection. That will cause item in task collection never to be deleted.

@ramonsmits I think that you found a similar issue in v5
@danielmarbach I might be missing something here. Could you validate?

**Comment by danielmarbach** [comment]
Yes I already told @andreasohlund before leaving that we need to track the
task first. I have some time today and send a PR

On Mon, Oct 26, 2015 at 1:55 PM, Tomasz Masternak <notifications@github.com>
wrote:

> In MessagePump.cs
> <https://github.com/Particular/NServiceBus/blob/7952153ff7e433bfa72b4dc0e90c8b98bc1aac77/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L196>
> we are adding continuation to processing task after adding task to receive
> task collection. That might cause a situation when the continuation will
> fire before the element is added to collection. That will cause item in
> task collection never to be deleted.
>
> @ramonsmits <https://github.com/ramonsmits> I think that you found a
> similar issue in v5
> @danielmarbach <https://github.com/danielmarbach> I might be missing
> something here. Could you validate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3033>.
>



-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by danielmarbach** [comment]
@tmasternak see associated PR
