### ISSUE TITLE
Don't add BOM to serialized message

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3050]
When using `JsonMessageSerializer` (by configuring JSON serialization) the raw message body (byte array) contains Byte Order Mark (BOM) bytes. We don't add a BOM when using the XML serializer.

While technically this is still a valid UTF8 string, this can cause lots of trouble if the the BOM isn't removed again when deserializing the message body (which will only done by `StreamReader`). Most serializer/deserializers don't like BOM bytes in strings and will throw an Exception when trying to deserialize such a string (this includes Json.NET, Visual Studio Json string visualizer or JavaScripts JSON.parse). So, parsing the message by using `Encoding.UTF8.GetString(...)`, the BOM will be contained in that string (although invisible).

By default, creating an UTF8 string by using `Encoding.UTF8.GetBytes(...)` or `new StreamReader(stream)` does not add the BOM to the resulting byte array. But when using `new StreamReader(stream, Encoding.UTF8)` the BOM (0xef 0xbb 0xbf) will be added. This is exactly what we're doing here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/Json/JsonMessageSerializer.cs#L35

The BOM can be removed by
- not specifying an encoding, UTF8 will be default but without BOM.
- by using `new UTF8Encoding(false)` instead.

//cc @sfarmar @hmemcpy @tmasternak

**Comment by ramonsmits** [comment]
On that topic, shouldn't we add a header that mentions the kind of encoding of the body just like http does with the `Content-Type` header? Then we are explicit about it.

**Comment by timbussmann** [comment]
good question. Since we're always using UTF8 (and I don't see any reason to do differently) that seems to be unnecessary. If we really want to support different encodings for the message body, we should use the BOM instead. But then, instead of removing it for JSON, we should add it for XML too. In these cases, having a BOM present is perfectly valuable to identify the content as an UTF8 string or even required on all other UTF encodings.

**Comment by danielmarbach** [comment]
@timbussmann How do we proceed with this? What are the backward compatibility implications of this?

**Comment by timbussmann** [comment]
this should have no impact on backward compatibility because
* for incoming messages we need to be able to handle content with or without BOM since we can't control it. I think that should already be fine.
* for outgoing messages it's basically the same: no receiver should every rely on a BOM being present. If consumers want to avoid potential issues with BOM (as we have in ServiceControl, see linked issue) they have to remove it on their side. Since they already would have to do that, it seems to be nice-to-have on the sender side (NServiceBus) and must-have for receivers (users & ServiceControl).

**Comment by ramonsmits** [comment]
@timbussmann @danielmarbach The BOM makes sense when there is no `Content-Type` header. If we add that header then there is no reason to add the BOM. the StreamWriter should be configured not to add the BOM in that case.

I think what is more important is that the user is able to set the encoding of choice when they choose a text based serialization format.

**Comment by timbussmann** [comment]
The main reason I raised this was this issue in SC: https://github.com/Particular/ServiceControl/issues/579
So while NSB is technically behaving correctly, it's a hidden little detail which can bite you if you're messing around with raw message contents. I'm good if we take no further steps on the core side as it's a valid utf-8 string (although not recommended by the utf-8 specification as I understand from the top answer on this SO question: http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom.

**Comment by SzymonPobiega** [comment]
BTW, there is a configuration switch that allows to pass a custom (e.g. no-BOM) encoding that was introduced some time ago: https://github.com/Particular/NServiceBus/commit/1e60297bca65f4ac902645080a5fbdf7666301de

**Comment by jbogard** [comment]
@SzymonPobiega do you have an example of how to remove the BOM encoding? This is affecting some integration scenarios for me as it looks like the BOM is still added on messages.

FYI the BOM should *not* be added on JSON messages, as it's against the RFC:

https://tools.ietf.org/html/rfc7159#section-8.1

**Comment by SzymonPobiega** [comment]
@jbogard here's the doco https://docs.particular.net/nservicebus/serialization/json#customization-customizing-encoding

I wasn't aware that BOM must not be added. That's interesting. I'll raise an issue for that. Thanks!
