### ISSUE TITLE
Remove IObservable on BusNotifications

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3052]
`BusNotifications` provides error and pipeline notifications by exposing `IObservables` which can be subscribed to receive the notifications. I suggest to replace those interfaces by events for the following reasons:
* To make those interfaces really usable, consumers and producers basically must use the reactive extensions packages.
  * This is really annoying if you're not using rx anywhere else and need that package for that specific use case
  * Since we don't want to have a dependency on rx we're implementing our own rx implementations. Even if we copy paste the official rx implementations we'll never be as up to date as the packages.
* Most people who could use the notifications API aren't familiar with rx. This can be a show stopper for interested users.
* There is no drawback by using events instead of observables for rx users, since rx provides easy-to-use converters.

There is one notifications (`BusNotifications.Pipeline.ReceiveStarted`) which exposes an IObservable<IObservable<X>>. This can't be directly mapped to an event like the other notifications.

**Comment by timbussmann** [comment]
@distantcam thoughts on that? objections?

**Comment by SimonCropp** [comment]
+1

want me to have a go at a PR?

**Comment by andreasohlund** [comment]
:+1: I did some coding of a custom check that was subscribing to SLR events and feelt the friction you mentions @timbussmann

**Comment by andreasohlund** [comment]
Relates to https://github.com/Particular/PlatformDevelopment/issues/323

**Comment by distantcam** [comment]
No objection from me.
