### ISSUE TITLE
Make sure FLR and SLR behaves the same in v5 and v6

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3054]
Currently in v6 the FLR `MaxRetries` and SLR `NumberOfRetries` are interpreted in a different way than in v5. We should fix that. E.g. MaxRetries = 3 and NuberOfRetires = 2 result in 9 retires in total in v5 and 12 in v6

**Comment by andreasohlund** [comment]
@tmasternak  Can we close this one as a duplicate of https://github.com/Particular/NServiceBus/issues/3065 ?

cc @MarcinHoppe

**Comment by tmasternak** [comment]
I think that this one is about behavior and #3065 is about naming.

**Comment by andreasohlund** [comment]
Should we bundle this with https://github.com/Particular/NServiceBus/issues/3424 ?

**Comment by MarcinHoppe** [comment]
Or #3466 maybe?

**Comment by tmasternak** [comment]
:+1: #3466

**Comment by andreasohlund** [comment]
Merged into https://github.com/Particular/NServiceBus/issues/3466
