### ISSUE TITLE
Option to disable or cache WindowsIdentityEnricher

### ISSUE THREAD

**Issue by cpx** [Particular/NServiceBus#3057]
I've been doing some profiling of various test applications with NServiceBus (5.2.3), and found that, at least in my scenarios on my machine, the WindowsIdentityEnricher is consuming a pretty significant amount of CPU resources when sending messages.

To isolate and verify it, I created a minimal test application and profiled it. To get rid of the CPU usage resulting from the chosen transport, I implemented a "null" transport that doesn't actually send anything. (code here https://gist.github.com/cpx/30335cb44982e1d724a4). In this scenario, the WindowsIdentityEnricher.MutateOutgoing() method contributed a rather whopping 30% to the inclusive% of the CPU usage (pretty much all of those 30% were spent inside mscorlib). I also measured the throughput with and without the method body commented out. On my (measly) laptop, the throughput with the null transport and the WindowsIdentityEnricher enabled was around 3-4K messages/s. Commenting out the method body more than doubled the throughput, to around 8-9K messages/s.

Obviously, this little bugger is doing quite a bit of work that, frankly, is not very interesting to most end-users.

So, I propose two changes:
1. Refactor the functionality to a enabled-by-default Feature that can be disabled by the user.
2. Add a disabled-by-default setting for the feature to only load the Identity once per thread and then cache it in a thread-static field.

An implementation of both of the above changes can be found in my local branch here (forked off of master): https://github.com/cpx/NServiceBus/tree/disable-WindowsIdentityEnricher
It's really a quite trivial set of changes, and to the best of my knowledge they should be fully backwards-compatible (and thus mergeable into v5). If there is any interest from your end in using this, I'll go ahead and add proper unit tests, documentation, pull requests, etc.

**Comment by andreasohlund** [comment]
We've actually decided to remove it alltogether in v6

https://github.com/Particular/NServiceBus/pull/2973#issuecomment-146842122

A pull would be welcome for v5 though.

That said if you don't need it you could disable if using the following "hack":

```

            var scanner = new AssemblyScanner();

            busConfig.TypesToScan(scanner.GetScannableAssemblies()
.Assemblies.SelectMany(a=>a.GetTypes()).Where(t=>t != typeof(ConfigureWindowsIdentityEnricher)));
      

```

Thoughts?

**Comment by cpx** [comment]
Sounds good to ditch it! Although, judging by your comment, maybe it would be interesting to keep it as a feature and just make it non-default for v6 but default for v5? That way users who still want to have it don't have to write it themselves.

I thought of doing a hack at first, but... I don't like hacks :stuck_out_tongue: It's such a simple thing to change that it's worth it.

Should there be documentation added for this? I had a look at existing docs but can't really find a good place to put it.

**Comment by andreasohlund** [comment]
>Should there be documentation added for this? I had a look at existing docs but can't really find a good place to put it. Also, which branch should I send the PR to?

I don't think there is any doco around this. Not sure how to doco it either since it not really giving any benefits from a security perspective. I could even argue that its a security flaw since we're leeking account information onto the wire.  

@SimonCropp what do you think?

**Comment by danielmarbach** [comment]
@cpx We are unlikely to pull this in for V5 and we removed it entirely in V6. I'm closing this one since there is a workaround provided.

Please reopen if you still feel strongly for this.
