### ISSUE TITLE
Log all publishes at debug level

### ISSUE THREAD

**Issue by abombss** [Particular/NServiceBus#3064]
Taskforce: @Farol @adamralph

In version 4.x of NSB when a message was sent or published it would be logged inside the DispatchMessageToTransportBehavior.  In 5.x the feature was implemented as a separate behavior in LogOutgoingMessageBehavior.  That behavior currently checks if the delivery options are SendOptions so publishing a message will no longer generate any diagnostic information.

While this may seem trivial, its just logging, we rely heavily on this log statement for our monitoring and operations, we also have several acceptance tests breaking as well that rely on this logging while trying to upgrade from 4.x to 5.x

The easy fix to restore previous behavior is to skip the check for a Send vs Publish and log all deliveries.

https://github.com/Particular/NServiceBus/blob/5.2.9/src/NServiceBus.Core/Unicast/Behaviors/LogOutgoingMessageBehavior.cs#L14-L16

**Comment by SeanFeldman** [comment]
@Particular/nservicebus any particular reason why `Publish` operation was left out in v5? Thanks.

**Comment by andreasohlund** [comment]
@abombss we don't currently maintain backwards compatibility for logging so it might be dangerous tolean on it for monitoring. Perhaps add your own behaviors that logs what you need?

@SzymonPobiega do we have similar logging in v6 as part of the new routing?

**Comment by abombss** [comment]
@andreasohlund The question is less around backwards compatibility and more towards understanding the reasoning behind making the diagnostics only for Sends and not including Publishes... If its just a miss during the refactor it can easily be fixed by a PR, no?

Not having any diagnostics when publishing a message seems like a gap that would still need to get filled one way or another.

**Comment by andreasohlund** [comment]
>The question is less around backwards compatibility and more towards understanding the reasoning behind making the diagnostics only for Sends and not including Publishes... If its just a miss during the refactor it can easily be fixed by a PR, no?

Fair point, there is no reason to not log for publishes as well. We'll consider rolling this into a 5.3. 

In the meantime would you be able to add a behavior to your code that does simlar logging to get unstuck? (you would have to cast the options to `PublishOptions` and adjust the log statement accordingly)

**Comment by abombss** [comment]
Yes, we added our own behavior, if we rely on it for ops it makes sense to
use our own. I actually replace the one that is provided, is that the best
approach? , there is no well known key for that, I got based on source
code.

**Comment by andreasohlund** [comment]
I'd say `add` is more future proof/safe than `replace` but both works

**Comment by abombss** [comment]
I am actually doing a remove then add, at the point when the current one
fires there are no headers in the message. We like to log all the headers
so we can query for things inside with our logging tools.

**Comment by Farol** [comment]
After discussing with @adamralph the course of action is as follows:
 - Branch from develop (v6) 
 - Implement this feature
 - pull request to develop 
 - Branch from master (v5) to create branch release 5.3
 - Implement this feature 
 - PR to branch release 5.3
 - PR to master

Then we would make sure that the same behavior will be in v 6.

**Comment by adamralph** [comment]
@Farol I discussed this with @andreasohlund and we think that this can be 6.0 only since there is a workaround for 5.x (which @abombss is using). /cc @SzymonPobiega

**Comment by adamralph** [comment]
Incidentally, it seems that we are currently not logging sends either in v6, so this work can include the restoration of the logging of sends in v6.

**Comment by Farol** [comment]
Will do, it will simplify the steps from the above list.

**Comment by udidahan** [comment]
I believe this connects to some other issue we once talked about - auditing all publish operations, not just relying on the auditing in the subscribers. @andreasohlund do you remember that one?

**Comment by andreasohlund** [comment]
https://github.com/Particular/NServiceBus/issues/1542

**Comment by adamralph** [comment]
@Farol @andreasohlund I'm tempted to close this and spin off a new issue which cleanly describes the problem and solution in the description. Thoughts?

**Comment by andreasohlund** [comment]
:+1:

**Comment by adamralph** [comment]
See #3186
