### ISSUE TITLE
Rename the maxRetries option in FLR and SLR to minAttempts to better reflect the behavior

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3065]
Currently when endpoint instance restarts or in scale out deployments it possible that FLR/SLR will do more attempts than maxRetries. That's why we should change the name that it's actually minAttempts that can be specified.
The previous configuration options should be still supported for compatibility reasons.

**Comment by andreasohlund** [comment]
Let's make this a code only api?

**Comment by tmasternak** [comment]
Current maxRetries or new minAttempts?

**Comment by timbussmann** [comment]
> The previous configuration options should be still supported for compatibility reasons.

but then we should also change that implementation to behave the same like v5. The issue here is that maxRetries = 1 actually means no retries in v5 and one retry in v6.
To me, minAttempts isn't really clear about what is included (FLR, SLR, first processing attempt?). Using minAttempts = 0 would be an invalid configuration.

Should we clarify the configuration further to make clear, we're speaking only about FLR retries here, e.g. "minImmediateRetries"?

//cc @SimonCropp

**Comment by tmasternak** [comment]
I've added v6 v5 differences as a separate issue here: #3054. 

>Should we clarify the configuration further to make clear, we're speaking only about FLR retries here, e.g. "minImmediateRetries"?

I think that we should change that for both.

**Comment by andreasohlund** [comment]
>Current maxRetries or new minAttempts?

I was talking about the proposed new setting

>minImmediateRetries

I like that we separate this from SLR. Since we talk about FLR should we
use `minFirstLevelRetries` ?

**Comment by timbussmann** [comment]
> Since we talk about FLR should we use `minFirstLevelRetries` ?

I'm fine with that too :+1:

**Comment by johnsimons** [comment]
Can we drop this for v6.0?

**Comment by tmasternak** [comment]
@johnsimons I think it's only a name change + doco. In comparison to other work in FLR/SLR it's small. That's why I would say let's do it.

**Comment by andreasohlund** [comment]
@tmasternak so you say deal with it as part of #3032 ?

**Comment by timbussmann** [comment]
I think we should definitely do it. The current configuration naming is just wrong. It doesn't behave like the options suggest it would. I'd consider this a critical task before releasing v6.

**Comment by tmasternak** [comment]
@andreasohlund that's right.

**Comment by andreasohlund** [comment]
Will be covered by https://github.com/Particular/NServiceBus/issues/3466
