### ISSUE TITLE
Confusing obsoletes for Storage

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3074]
In v6 if using the old syntax to specify a specific storage eg:

`c.UsePersistence<FakeTmStorage>().For(Storage.Timeouts);`

will give 2 compiler errors

```
'Storage' is obsolete: Please use `NServiceBus.Persistence.StorageType` instead

```

and 

```
PersistenceExtentions<FakeTmStorage>.For(params Storage[])' is obsolete:
Please use `UsePersistence<T, S>()` instead
```
Following the first will lead no where since changing to `StorageType` give other compile errors since `Storage` is a enum but `StorageType` is a class.

Following the second error is the way to go.

**Comment by timbussmann** [comment]
@andreasohlund that looks like something which should be fixed before the v6 release?
Would it be best to remove the obsolete on `Storage` and instead make sure that all API's accepting a `Storage` parameter are properly obsoleted (as `For` is)?

**Comment by andreasohlund** [comment]
@timbussmann yea, makes sense. Let's do it under maintainer prio

**Comment by danielmarbach** [comment]
@andreasohlund @timbussmann PR is pending and linked
