### ISSUE TITLE
Async/Await support for NServiceBus

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3076]
Connects to Particular/PlatformDevelopment#182

This is the core epic which incorporates the work for making the core async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

### Core

- [x] Finialize the new transport seam 
  - [X] Sync https://github.com/Particular/NServiceBus/pull/2828 @andreasohlund 
  - [x] Refactor `TransactionSettings` https://github.com/Particular/NServiceBus/issues/2868
  - [X] Async https://github.com/Particular/NServiceBus/pull/2870 @andreasohlund 
- [x] Convert one `IBus` method at the time
 - [x] `Publish` and corresponding extension methods @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2891
 - [x] `Send` and corresponding extension methods @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2890
 - [x] `SendLocal` and corresponding extension methods @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2897
 -  [x] `Reply` and corresponding extension methods @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2896
 - [x] `ForwardCurrentMessageTo` @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2894
 - [x] `Subscribe` and `Unsusbcribe` @colin-higgins
  - https://github.com/Particular/NServiceBus/pull/2902
 - [x] `HandleCurrentMessageLater` @danielmarbach
  -  https://github.com/Particular/NServiceBus/pull/2893
 - [x] ~~`DoNotContinueDispatchingCurrentMessageToHandlers`~~ @colin-higgins - not necessary
 - [x] `Start` on `IStartableBus` @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2923
- [X] Acceptance Testing Framework @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2851
  - https://github.com/Particular/NServiceBus/pull/2857
  - https://github.com/Particular/NServiceBus/pull/2858
  - https://github.com/Particular/NServiceBus/pull/2860
- [X] All unit test methods (NUnit supports async/await), done as part of https://github.com/Particular/NServiceBus/pull/2858
- [x] `IWantToRunWhenTheBusStartsAndStops`
 - [x] StartAsync for `IWantToRunWhenTheBusStartsAndStops`   @danielmarbach https://github.com/Particular/NServiceBus/pull/2846
 - [x] StopAsync for `IWantToRunWhenTheBusStartsAndStops`  @danielmarbach https://github.com/Particular/NServiceBus/pull/2849
- [x] Saga Persistence @danielmarbach
  - https://github.com/Particular/NServiceBus/pull/2863
- [x] SagaFinders @timbussmann
 - https://github.com/Particular/NServiceBus/pull/2874
- [x] HandleSagaNotFound @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2873
- [x] Timeout Persistence / Query @timbussmann 
 - https://github.com/Particular/NServiceBus/pull/2862
- [X] SubscriptionStorage / Query @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2865 
- [X] Outbox @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2867
- [x] Gateway deduplication @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2866
- [x] Decide if we should use a cancellation token for aborting the pipeline instead of the Ex we use now
- [x] Agree on how we limit concurrency and or throughput  and what default values we should go with in v6
- [x] Cleanup our doco around why and how to enforce receive limits https://github.com/Particular/docs.particular.net/issues/816
- [x] Transport dispatcher @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2892
- [x] Message Handlers @colin-higgins @seanfeldman
 - [x] https://github.com/Particular/NServiceBus/pull/2887
- [x] Timeout Handlers @timbussmann
 - https://github.com/Particular/NServiceBus/pull/2883
- [X] Saga Base infrastructure including `IAmStartedByMessages` @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2915
- [x] Mutators @SimonCropp 
 - https://github.com/Particular/NServiceBus/commit/29f93b53e1e122bfedb8475b82253d4b2cd1ee68
- [x] Pipeline @danielmarbach
 - https://github.com/Particular/NServiceBus/pull/2906
 - https://github.com/Particular/NServiceBus/pull/2907
- [x] Databus (??) (or should we get rid of it) @seanfeldman
 - https://github.com/Particular/NServiceBus/pull/2877
~~- [ ] Features especially Startup Tasks - check/debate if necessary~~ FeatureStartup Tasks can't currently be made async because they are started during the configuration phase. We need https://github.com/Particular/PlatformDevelopment/issues/246 to support async startup tasks
- [x] Scheduler - check/debate if necessary
- [x] Dynamic routing rules do not allow async loading of rules #3116 @justabitofcode and @janovesk
- [x] Pipeline creation #3117 
- [x] Callbacks #3149, #3150
- [x] Go through all the documentation and update them including add what is missing

**Comment by danielmarbach** [comment]
@Particular/tf-async-core I updated the issue card to reflect what is left to do

**Comment by danielmarbach** [comment]
@udidahan As promised async/await related work for core is getting done, done. We just did the necessary performance improvements for the pipelines in 

https://github.com/Particular/NServiceBus/pull/3262

The associated PR for doco needs a review and merge and then we are done. 

https://github.com/Particular/docs.particular.net/pull/1006

@Particular/tf-async-core @Particular/nservicebus @Particular/documentation Anything left from your perspective which needs to be done before we call the core epic done?

**Comment by mauroservienti** [comment]
@danielmarbach does this mean that we, at transports and persistence level, should not expect any breaking change and can concentrate ourselves in making everything done-done as well?

**Comment by danielmarbach** [comment]
@mauroservienti I think that could be the wrong assumption. When we
splitted into persistency, transport we said everything brought up during
the work there related to core is treated as tasks inside those TFs. By
core being done we considered the API from the view of core as stable
(maybe we need another wording to describe it better)

**Comment by mauroservienti** [comment]
Does it mean that stable doesn't mean no more breaking changes? :-)

On Wednesday, 6 January 2016, Daniel Marbach <notifications@github.com>
wrote:

> @mauroservienti I think that could be the wrong assumption. When we
> splitted into persistency, transport we said everything brought up during
> the work there related to core is treated as tasks inside those TFs. By
> core being done we considered the API from the view of core as stable
> (maybe we need another wording to describe it better)
>
> On Wednesday, January 6, 2016, Mauro Servienti <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @danielmarbach <https://github.com/danielmarbach> does this mean that
> we,
> > at transports and persistence level, should not expect any breaking
> change
> > and can concentrate ourselves in making everything done-done as well?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Particular/NServiceBus/issues/3076#issuecomment-169358374
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3076#issuecomment-169379038>
> .
>


-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by SimonCropp** [comment]
@mauroservienti i have never objected the breaking changes in v6. I object to people making them and then ignoring the impact on dowstream repos. It is fine that we had a period of "break all the things", but as soon as the trigger was pulled on updating all the downstreams that free for all is over. In my thinking the person now making the breaking change should be either fixing the downstreams or working with other people to transition the knowledge.

**Comment by SeanFeldman** [comment]
> the person now making the breaking change should be ... working with other people to transition the knowledge.

:100:%

**Comment by timbussmann** [comment]
Closing this as all tasks seem to be done
