### ISSUE TITLE
throw for config where retries could go over the 24hour max

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3077]
https://github.com/Particular/docs.particular.net/pull/918

**Comment by bording** [comment]
@danielmarbach and I took a look at the doco PR. Where should this 24H limit apply? Both the config and code-based configuration? What about custom retry policies? 

Can you fill out the description a bit more to provide enough context for anyone to be able to work on this?

Or is the doco enough and we can go ahead and close this?

**Comment by andreasohlund** [comment]
I think what @SimonCropp means if for the core to throw on startup when the requested delay retries would potentially delay the message more than 24h? (since we would silently move it to error if it does go past 24h)
