### ISSUE TITLE
Provide custom performance counters each satellite pipeline

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3079]
In v5 we create performance counter instances for every pipeline which reads from a queue. V6 only creates the performance counters for the main pipeline (endpoint input queue). This seems to be a bug which was caused by creating performance counters on a behavior which is only used in the main pipeline.

**Comment by andreasohlund** [comment]
Talking this through with @timbussmann and @danielmarbach we decided that even though its a breaking change this is the right thing to do. Mixing satellites and the main queue is confusing for end users. Yes satellites should expose relevant ops data and they can decide to do it via perf counters. We can add this in a minor version so marking this as a feature and removing the core v6 label.

I will raise an issue to highlight this in the upgrade guide

**Comment by andreasohlund** [comment]
It turns out that https://github.com/Particular/NServiceBus/pull/3568 will actually enable us to provide perf counters (the msg pulled from queue, msg failed and msg processed counters) for satellites. Perhaps we should go with that to not rock the boat?

**Comment by andreasohlund** [comment]
Reopening, I had put "fix #thisissue" in the pull request text by misstake

**Comment by andreasohlund** [comment]
@timbussmann is this worth migrating to the external repo / metrics repo? (or just close)

**Comment by timbussmann** [comment]
@andreasohlund I think at least uniquely addressable queues should also be included (not sure whether this is happening or not). Who's maintaining this repo, metrics maintainers?

**Comment by danielmarbach** [comment]
I think uniquely addressable queues are normal pumps and therefore have counters?

**Comment by timbussmann** [comment]
yeah I thought this would be the case too, but I'm not 100% sure. If this is the current behavior im +1 to close.

**Comment by danielmarbach** [comment]
I think the problem is that there is no differentiatior between the main
pipeline and the individual queue pipeline since the pipelibe id is not
available on the pipeline completed event

Tim Bussmann <notifications@github.com> schrieb am Mi. 24. Mai 2017 um
14:01:

**Comment by andreasohlund** [comment]
Correct, and since there is no differentiator all metrics for the both
pipelines is treated as a single entity.

How about we raise a different issue for that and close this one?

**Comment by timbussmann** [comment]
I believe https://github.com/Particular/NServiceBus/issues/4874 covers everything necessary to provide the required metadata as suggested by @danielmarbach , closing this therefore.
