### ISSUE TITLE
Acceptance tests race-conditions

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3082]
It looks that currently it is possible to have two or more endpoints starting at the same time. This can lead to problems as two endpoints may want to create the same queue at the same time e.g. errors

**Comment by timbussmann** [comment]
@tmasternak is this a scenario where the test uses `Repeat` to run multiple configurations of the test? if so, would these changes actually solve the issue: https://github.com/Particular/NServiceBus/pull/3841/files#diff-4ca9b583e070df8435b9aea8f58708a4L44 ?

**Comment by tmasternak** [comment]
@timbussmann this one originated from two endpoints trying to create shared error/audit queues.

**Comment by timbussmann** [comment]
ah ok. Yeah I think endpoint startup is still concurrent.

**Comment by danielmarbach** [comment]
If I recall correctly it was parallel in older versions and I made it concurrent while implementing the ATT changes. The reasoning was to speed up the overall execution time of the tests.

**Comment by dbelcham** [comment]
Resolved in previous work to remove the reuse of queue names across tests
