### ISSUE TITLE
License file is not read from web app's bin folder

### ISSUE THREAD

**Issue by rlaveycal** [Particular/NServiceBus#3100]
We've checked our license file into a common library (NServiceBus\License.xml) as content. This means it is copied to our applications bin folder on build. This works fine for Win32 apps but for web apps it doesn't as the appdomain base directory is not the bin folder.

Please add ````Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"bin\\NServiceBus\License.xml")```` as a search location to LicenseLocationConventions

**Comment by danielmarbach** [comment]
@rlaveycal There are [various ways ](http://docs.particular.net/nservicebus/licensing/license-management)which allow you to fully customize the license retrieval path. I'm closing this issue.

If you have more questions don't hesitate to reopen.
