### ISSUE TITLE
Endpoint Instance Names & Logical Address

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#3103]
In the V6 transport definition seam, it's the responsibility of the transport to translate a LogicalAddress into a transport specific address https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/TransportDefinition.cs#L63

In order to achieve this, a LogicalAddress is passed in (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/LogicalAddress.cs), which contains an EndpointInstanceName object internally (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/EndpointInstanceName.cs). However I feel that the format of these 2 classes is not what it should be and needs to be revisited.

If we look at a string representation of LogicalAddress for a uniquely identified endpoint, we would get something like this.

"SomeEndpointName-SomeMachineIdentier.SomeSatteliteIdentifier" (aka Sales-MyMachine.timeouts)

However when I look at the object structure I see something else:

- SomeEndpointName is represented by an instance of EndpointName (which is fine)
- SomeMachineIdentier is now represented by either UserDiscriminator or TransportDiscriminator. In my opinion this last one is wrong, it should be determined by the Host (or the user). When hosted in azure cloudservices I would expect a RoleInstanceId here, but when hosted on premises or in regular azure VM I would expect a machine name here.
- SomeSatteliteIdentifier is now called Qualifier
- But the - and . are now "assumed values", even hardcoded in the ToString implementation. But these 2 should really be determined by the Transport imo. ASQ does not support the "." for example. I feel the term TransportDiscriminator should represent the "-" and something else (like TransportQualifier?) should represent the "."

I would also change the transport definition to return the "-" and "." parts, and let the host (or user in case of self hosting) return the MachineIdentifier part

Then the ToTransportAddress function can use all this information to come up with a valid address that conforms to what the transport needs, but also to what is expected by the user in the given hosting environment. The ToString() of LogicalAdress & EndpointName can then also output something that complies to both the expectation of the transport and the host by concatenating all these parts (instead of assuming - and .)

Thoughts?

**Comment by SeanFeldman** [comment]
This is very much related to the [Centralized dynamic scaling based on logical endpoints](https://github.com/Particular/PlatformDevelopment/issues/133) feature documented as [message routing](http://docs.particular.net/nservicebus/messaging/routing). It's geared towards MSMQ and retirement of the Distributor, and I also have a question how will it play with brokers, especially ASB/ASQ. Perhaps we need to review this on a call with @SzymonPobiega and @janovesk that are part of the task force?

**Comment by danielmarbach** [comment]
@Particular/transport-maintainers Is this still relevant? Given the discussions around independent instances and ids as well as the work we poured into the transport seam.

**Comment by yvesgoeleven** [comment]
@danielmarbach this is in essence the same discussion as the instance id one, feel free to close and mark as duplicate
