### ISSUE TITLE
Dynamic routing rules do not allow async loading of rules

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3116]
Relates to #3076 

`RoutingFeature` is the only place left in the core which still issues a `GetAwaiter().GetResult()` call when loading the subscriptions into the dynamic routing table. 

I think we need to redesign the fetching of dynamic rules. Away from an enumerator based interface towards a function which returns a Task with a list of routes (maybe even readonly collection). It would then be the responsiblity of the `UnicastRoutingTable` to asynchronously fetch the dynamic routing rules. 

See also the current doco

> The function is called each time any message is being send so you need to take performance into account (e.g. use caching if the destinations are to be fetched from a database).

Essentially our internal implemenation in `QuerySubscriptionStore` is a database call (IO operation) but the UnicastRoutingTable.AddDynamic interrupts the asynchronous flow. This would also have an impact on the `IUnicastRouter` implemenation.

Thoughts?

@Particular/tf-async-core @SzymonPobiega @janovesk @justabitofcode

**Comment by janovesk** [comment]
Neither me or @SzymonPobiega can see any reason for this needing to be sync at all. 

Did you want to take a stab at this @justabitofcode ?

**Comment by justabitofcode** [comment]
@janovesk Can we pair on it? Let me know when you're available.

**Comment by janovesk** [comment]
Closed by #3127
