### ISSUE TITLE
RijndaelEncryptionService sets the outgoing headers globally, applying it to messages without encrypted properties as well

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3119]
Setting the key identifier header is done when a property is encrypted. This is done on the global headers collection and not on the message headers. This results in all messages containing the key identifier header, also messages that do not have encrypted properties.

The key identifier header does not cause issues. It was added to prevent possible data corruption when decryption properties. The header increases the complete message size a bit.

**Comment by ramonsmits** [comment]
As this is a non critical bug its only fixed in version 5.2.11 which is PR #3109

**Comment by ramonsmits** [comment]
@andreasohlund @SimonCropp @justabitofcode @DavidBoike The first thought was that sending the header with every message wouldn't be harmful. That is why it was decided to only fix this behavior for 5.2+

I just was thinking that the header is currently also send to endpoints that would normally not receive encrypted messages. It is not leaking the key data. If this endpoint is part of a different system or at a different site than this header is available there.

Would we consider this as harmful?

**Comment by justabitofcode** [comment]
I wouldn't consider this harmful per se, as without access to the collection of Keys, having the KeyId in the message header gives nothing away. From a customer point of view however encryption is an emotive subject, and can erode trust if it's not handled correctly. For that reason, I think we should port the fix to earlier versions where possible.

**Comment by ramonsmits** [comment]
So, as the implementation of v3 and v4 relies on a message mutator we can pass the message object to the encryption service to supply context so we can use the extension methods `GetHeader` and `SetHeader`. The DataBus uses the same extension methods but getting/setting those headers is not done in the databus implementation.

**Comment by ramonsmits** [comment]
So if we pass the message `object` to the encryption service so it can set/get headers would we have problems with that?

**Comment by ramonsmits** [comment]
@andreasohlund @SimonCropp @justabitofcode @DavidBoike Can you please mention your opinion about the global header issue? 

> given that this is data that that travels on a queuing system that is secured as well I can't see the huge deal. I mean you would have to hack the system to even see the headers?

The gateway could also pass via headers to a different site.

If we agree that leaking this info is ok then I can release.

**Comment by ramonsmits** [comment]
I ported the fix to 4.7.x, see that PR. So it possible...

**Comment by SimonCropp** [comment]
The identifier in the header is not an issue. We cant stop people putting sensitive data  where they shouldnt. The same goes for any other header or even message content

**Comment by DavidBoike** [comment]
Agree with @SimonCropp. It's nice to not include the key header with non-encrypted messages just for prevention of bloat and "What's this?" type reactions. But I wouldn't bend over backwards to remove it on a whole bunch of backport versions.

**Comment by ramonsmits** [comment]
This is now fixed and released in v5.2.11
