### ISSUE TITLE
Persistence support for NServiceBus v6

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3126]
Taskforce: @DavidBoike @colin-higgins @mauroservienti @SzymonPobiega 

Chickens: @yvesgoeleven @SeanFeldman 

This is the epic which incorporates the work needed to adapt supported persistence stores for NServiceBus v6 .

## Implementing Async/Await
- RavenDB (link: Particular/NServiceBus.RavenDB#113)
- NHibernate (link: Particular/NServiceBus.NHibernate#138)
- AzureStoragePersistence (link: Particular/NServiceBus.AzureStoragePersistence#14)

## Other V6 tasks
- Raven
  - Ensure Raven tests are cleaning up Particular/NServiceBus.RavenDB#116
  - Correctly deal with TransactionRecoveryStorage Particular/NServiceBus.RavenDB#70
    - This is a bug that needs to be included in NSB.Raven 3.x as well Particular/NServiceBus.RavenDB#136
  - Reevaluate DocStore best practices / defaults Particular/NServiceBus.RavenDB#122
  - Evaluate removing MD5 (i.e. FIPS) NServiceBus#1217 (Decided not to pursue, too many breaking changes with saga pointer docs to be worth the effort)
  - Subscription documents per message type & endpoint (https://github.com/Particular/NServiceBus.RavenDB/issues/125)

## Update Samples

- Mongo: Particular/docs.particular.net#1016
- Raven: Particular/docs.particular.net#1017
- NHibernate: Particular/docs.particular.net#1018

**Comment by DavidBoike** [comment]
Sync:

* @DavidBoike pairing with @SeanFeldman today on getting acceptance tests into Azure persistence before a V6 upgrade is attempted.
* Raven PR for V6 into develop is too big to really evaluate and can't be split up in such a way that is compilable. Not going to release as is so just need to merge and stabilize.
* @colin-higgins working on stabilizing Raven.
* Potential breaking change for Raven: change subscription structure to deal with concurrency exceptions that occur frequently with current design.
* @SzymonPobiega working on NHibernate and will push a branch (even though not compiling) for collaboration.
* @DavidBoike will reach out to Oren to schedule a call regarding DocStore best practices (TransactionRecoveryStorage, ResourceManagerId, new V3 features, etc.) but we need to do our homework beforehand.

**Comment by DavidBoike** [comment]
Status:

* Raven
  * Updated to latest CoreV6 unstable 1293
  * All tests passing locally, but some timing out on build server. Not quite sure why yet.
  * David contacting Oren to set up call to understand anything else we should revise as a breaking change with CoreV6.
* NHibernate
  * Branch to update in progress, not currently compilable
  * @SzymonPobiega should know more.
* Azure Storage Persistence
  * Working to add core acceptance tests to CoreV5 version before proceeding with update
  * Meeting scheduled Friday to better understand Timeouts in ASP and any guarantees we make.

**Comment by DavidBoike** [comment]
#### Current Status - Jan 6

* Raven
  * All tests green for latest V6 unstable.
  * Beginning to have doubts if changing subscription document structure is worth the complexity for (probably negligible in most cases) gains in endpoint startup time.
* NHibernate - @SzymonPobiega working on V6 acceptance tests.
* Azure Storage Persistence - @DavidBoike completed addition of acceptance tests for V5. After merge of Particular/NServiceBus.AzureStoragePersistence#16 can proceed to upgrading to V6.

Task force please feel free to update as necessary.

**Comment by SimonCropp** [comment]
@davidboike have u smoke tested the v6 Raven on any of the docs samples?

**Comment by DavidBoike** [comment]
@SimonCropp Nope, not yet, but we added updating Particular/docs.particular.net#1017 to our PoA.

**Comment by DavidBoike** [comment]
#### Current Status - Jan 13

* Raven
  * At station-keeping as V6 continues to evolve, not sure we can call it "done done"
  * Samples are near completion, pending merge of Particular/NServiceBus.RavenDB#130 dealing with the issue of how we are exposing the Raven session to users
  * Dealing with TransactionRecoveryStorag, already on docket for V6 (Raven V4) needs to be implemented on Raven V3 as well, Particular/NServiceBus.RavenDB#136 - @DavidBoike getting it ready
* NHibernate
  * Updating to V6 branch merged to develop
  * Looks like UTs that passed for @HEskandari are now failing on build server
* Azure
  * V5 pull to bring in ATs Particular/NServiceBus.AzureStoragePersistence#16 noted that endpoint instance identifier needed to be use. Inclusion caused [9 new failing tests](http://builds.particular.net/viewLog.html?buildId=140787&buildTypeId=NServiceBus_Persistence_NServiceBus_AzureStoragePersistence_Build), which need to be investigated before merging and proceeding to V6 work.

**Comment by mauroservienti** [comment]
Should we close this one and open specific issues for the remaining work to be done? As per Udi's suggestion

**Comment by colin-higgins** [comment]
@mauroservienti I am good with that

**Comment by timbussmann** [comment]
> Should we close this one and open specific issues for the remaining work to be done? As per Udi's suggestion

how is an epic done when there is still work to do?

**Comment by mauroservienti** [comment]
@timbussmann I tend to agree, dependent work is still pending so this should stay open until all the work is done, last week was proposed to do the opposite, I think that we should define some sort of process around Epics and stick to that.

**Comment by andreasohlund** [comment]
@Particular/tf-async-persistence I can't find anything in the description that is left todo in this repo. Are all outstanding issues tracked by the linked issues in the description? if yes please make sure they are tagged as core v6 and close this one

**Comment by DavidBoike** [comment]
Remaining tasks from each repo that are tagged CoreV6:

* [Raven](https://waffle.io/Particular/PlatformDevelopment?label=Tag:%20Core%20v6&source=Particular%2FNServiceBus.RavenDB) - good to go
* [NHibernate](https://waffle.io/Particular/PlatformDevelopment?label=Tag:%20Core%20v6&source=Particular%2FNServiceBus.NHibernate) - not sure
* [ASP](https://waffle.io/Particular/PlatformDevelopment?label=Tag:%20Core%20v6&source=Particular%2FNServiceBus.AzureStoragePersistence) - good to go

@SzymonPobiega can you please review the NHibernate view and make sure all work that needs doing is captured there? Then we can close this issue.

**Comment by SzymonPobiega** [comment]
@DavidBoike these are two PRs we need to get in and we'll be ready to go:
 * https://github.com/Particular/NServiceBus.NHibernate/pull/176
 * https://github.com/Particular/NServiceBus.NHibernate/pull/175

**Comment by DavidBoike** [comment]
Reviewed both of those PRs. Marked both as `Tag: Core v6` and am closing this issue.
