### ISSUE TITLE
Introduce option to use XmlSerializer from System.Xml.Serialization instead of / as well as NServiceBus.XmlSerializer

### ISSUE THREAD

**Issue by petersgiles** [Particular/NServiceBus#3128]
Currently an endpoint can only be configured to use Serializers that conform to  NServiceBus.Serialization.SerializationDefinition.

While there are some advantages with having our own bespoke version there is a responsibility to keep it bug free, maintained and wire compatible. 

I think it is worth hashing out the advantages and disadvantages of allowing users to use the .Net Serializers with NServiceBus.

**Comment by hmemcpy** [comment]
+1, I also suggested this a while ago: https://github.com/Particular/PlatformDevelopment/issues/415

Now that we have multi-deserialization support in the core, we can move our custom serializer to a "legacy" package, and keep it as a fallback.

**Comment by bording** [comment]
It looks like there is a community serializer for that already:

https://github.com/fhalim/NServiceBus.Serializers.SystemXml

Perhaps keeping support for it at the community level is the best approach. Or we could move it into being an officially supported option.

**Comment by SimonCropp** [comment]
given that project only supports up to version 4 of NSB i think we would need to either send some PRs or take ownership

**Comment by petersgiles** [comment]
@SimonCropp +1 PRs

**Comment by andreasohlund** [comment]
I know Favad, sent a PR https://github.com/fhalim/NServiceBus.Serializers.SystemXml/pull/1
