### ISSUE TITLE
Set correlated saga properties automatically based on the incoming message

### ISSUE THREAD

**Issue by udidahan** [Particular/NServiceBus#313]
Correlated saga properties will automatically get the value of the mapped message property

**Comment by indualagarsamy** [comment]
@andreasohlund - can you update the issue description with what needs to be done, now that the saga meta model is available?

**Comment by andreasohlund** [comment]
@indualagarsamy I've updated the description. Also updated the title since this can be applied to all messages that has some kind of correlation defined. Auto correlation is a different (valid) feature

**Comment by johnsimons** [comment]
@andreasohlund @udidahan is it ok if this does not go out in 5.2?

**Comment by andreasohlund** [comment]
Yes, this should be rehashed in requirements
