### ISSUE TITLE
Transport feature setup

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3140]
Currently MSMQ transport has both a [transport definition](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/Msmq.cs) and [feature](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqTransportConfigurator.cs) associated with it. This feature is enabled by default and used for doing check on queues permissions and TTBR. What happens when somebody uses transport different than MSMQ. It look that we are not disabling MSMQ feature right now and we probably should.

**Comment by andreasohlund** [comment]
Sync with @SzymonPobiega pretty sure he's already fixed this ccc @yvesgoeleven

**Comment by SzymonPobiega** [comment]
There is a PR for that: #3133. Can you give it a quick review @tmasternak ?

**Comment by tmasternak** [comment]
#3133 solves to problem.
