### ISSUE TITLE
Pass TransportTransaction to IDispatchMessages

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3163]
@SzymonPobiega @andreasohlund @weralabaj @timbussmann  We have introduced transport transaction to share transactions between transport and persistence if possible. Do we want to pass it to [IDispatchMessages](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/IDispatchMessages.cs) as well?

**Comment by andreasohlund** [comment]
Sounds resonable to me, explicitness FTW

**Comment by timbussmann** [comment]
sounds good to me

**Comment by SzymonPobiega** [comment]
:+1: x :100:

**Comment by danielmarbach** [comment]
Sounds right for me too.

**Comment by andreasohlund** [comment]
Not a must for v6, flagging as breaking change and removing milestonr

**Comment by andreasohlund** [comment]
Seems like this made in into v6 after all https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/IDispatchMessages.cs#L14
