### ISSUE TITLE
Moving from Strongly named Messages assembly to SemVer (non-strongly named) Messages assembly

### ISSUE THREAD

**Issue by SathishN** [Particular/NServiceBus#3169]
When handler handles messages from clients using older strongly named message assembly. it throws exception NServiceBus.MessageDeserializationException saying can't load the Older strongly named assembly. 

I posted this issue earlier on google groups 
https://groups.google.com/d/msg/particularsoftware/tgA_GZgIaKE/cmMVnAdHdKIJ

I didn't receive a concrete solution to this issue!

Looking for a better solution.

**Comment by danielmarbach** [comment]
Like @SimonCropp mentioned in the google group there are only these three outlined solutions.

> The problem is that you are using strong named message assemblies.
> 
> There are a few options to work around this
> 
> 1. Dont change the assembly version of the messages assembly (you can still change the file version for deployment purposes)
> 2. Dont use strong naming. This is the best option. Unless you want to GAC your messages assemblies there is zero value in using SN. Some people may tell you it is for security, this is not true. See the official MS documentation https://msdn.microsoft.com/en-us/library/wd40t7ad.aspx  "Do not rely on strong names for security. They provide a unique identity only."
> 3. Use binding redirects. So you can redirect the runtime to the correctly referenced version. I have added a PR that illustrates how to do this https://github.com/SathishN/NServiceBusv520Andv338Issue/pull/1

I'm closing this issue.

**Comment by SathishN** [comment]
@danielmarbach thanks for looking into this issue.

I just want to reiterate the problem, I'm in the process of moving away from strong named message assemblies. I still have few clients in prod using older strong named assemblies.

I'm looking for options at my handler side, handling both strong named message(previous version)  
and newer message assembly which isn't strong named.

Assembly binding redirect only works when I strongly name(sign) the newer version of message assembly as well.
