### ISSUE TITLE
NSB 4.0.x will fail to load the type `UnicastBus` if it's using `NServiceBus.Interfaces` of a higher version

### ISSUE THREAD

**Issue by hmemcpy** [Particular/NServiceBus#3179]
By default, the version constraint for the `NServiceBus` 4 dependency is `< 5.0.0.0`. With the `HighestMinor` dependency resolution option, this will cause NuGet to pull the latest `NServiceBus.Interfaces`, e.g. 4.7.x, when installing NServiceBus 4.0.11.

This causes NServiceBus to fail during assembly scanning, trying to load the type `UnicastBus`:
```
Method 'Publish' in type 'NServiceBus.Unicast.UnicastBus' from assembly 'NServiceBus.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
```

To repro: Create a new console app, pull in NServiceBus 4.0.11, select "HighestMinor" in the dependency resolution combo in NuGet.
Putting the following in `Main()` will cause the scan to fail:

    Configure.With().DefaultBuilder();

This does not happen if the version of `NServiceBus.Interfaces` matches that of NServiceBus 4.0 (e.g. both are 4.0.11)

**Comment by bording** [comment]
This doesn't appear to meet the criteria for [backporting ](https://github.com/Particular/PlatformDevelopment/blob/master/Guidelines/Patching.md#bugs-that-fit-the-following-criteria-should-be-patched)a fix.

Closing.
