### ISSUE TITLE
The `EndpointName` class cannot be serialized properly

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#3183]
While working on the RavenDB subscription persistence with @colin-higgins, I came across an issue with the `EndpointName` class.

The `Subscriber` class has an `Endpoint` propery of type `EndpointName`. Instances of `Subscriber` need to be serialized into a RavenDB document, but `EndpointName` wraps a string, and has no public members. The only way to get to the underlying value is by calling `ToString()`.

Without decorating the `EndpointName` class with Json.NET attributes or writing a custom ContractResolver, RavenDB has no way to properly serialize the `Endpoint` property, so it is always null when the document is loaded.

Would it be possible to add a public property that exposes the value of the `name` field?

**Comment by SimonCropp** [comment]
EndpointName should not be used for persistence. just store the string

**Comment by johnsimons** [comment]
@SzymonPobiega 
I think this just enforces that we are exposing the wrong thing to downstreams

**Comment by SimonCropp** [comment]
@johnsimons agreed. i will do a PR to make EndpointName  internal

**Comment by johnsimons** [comment]
@SimonCropp how about we discuss this with @SzymonPobiega first, because this has implications to other areas of the code

**Comment by SzymonPobiega** [comment]
I don't have anything against not exposing it in the subscription seam. As for making it internal, I am not yet convinced but I'd like to see how this PR looks like :)

**Comment by danielmarbach** [comment]
`EndpointName` is still public https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/EndpointName.cs#L6

We still pass it to the `Subscriber` class.

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/Subscriber.cs#L29

Directly storing core types is a huge smell and has bitten us in the past.

See for example

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Timeouts/TimeoutDataV1toV2Converter.cs

I'm :-1: to make endpoint name serializable and I vote for closing this one.

@Particular/nservicebus-maintainers thoughts?

**Comment by timbussmann** [comment]
> I'm :-1: to make endpoint name serializable and I vote for closing this one.

I think we should make the `EndpointName` internal then, but we could raise a dedicated issue for that?

**Comment by bording** [comment]
The original problem that caused me to open this issue was resolved by not using the `EndpointName` directly in the RavenDB document, as @SimonCropp pointed out.

Marking this serializeable is definitely not needed!

**Comment by andreasohlund** [comment]
Agreed! (esp since I'm the one making most of those mistakes in the past  :) )

**Comment by SimonCropp** [comment]
Still think endpoint name should not be exposed publically

**Comment by danielmarbach** [comment]
@SimonCropp do you want to drive this, including downstream implications and doco update?

**Comment by SimonCropp** [comment]
whats to drive? this is closed

**Comment by danielmarbach** [comment]
> Still think endpoint name should not be exposed publically

This issue talks about serializable. Making endpoint name internal would be another thing you raised

**Comment by SimonCropp** [comment]
i raised it and the decision was made to leave it public. no need to have the discussion again
