### ISSUE TITLE
Create testable mocks/helper classes for testing behaviors

### ISSUE THREAD

**Issue by hmemcpy** [Particular/NServiceBus#3184]
Connects to https://github.com/Particular/NServiceBus.Testing/issues/29

**Comment by timbussmann** [comment]
we also need to decide whether they are part of the NSB.Testing package of the core.

**Comment by hmemcpy** [comment]
This is now a part of upgrading NServiceBus.Testing to v6 issue.

**Comment by timbussmann** [comment]
let's track all progress on the https://github.com/Particular/NServiceBus.Testing/issues/29 issue
