### ISSUE TITLE
System.InvalidOperationException occurred. Message=It is required to set the rijndael key identifer.

### ISSUE THREAD

**Issue by fafachd** [Particular/NServiceBus#3189]
When I upgrade from NServiceBus 5.2.8 to 5.2.9 (or later), I get the following exception when sending a message containing encrypted properties:

System.InvalidOperationException occurred
  HResult=-2146233079
  Message=It is required to set the rijndael key identifer.
  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.Encryption.Rijndael.RijndaelEncryptionService.Encrypt(String value) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Encryption\RijndaelEncryptionService.cs:line 147
  InnerException:

**Comment by andreasohlund** [comment]
Do you have a key identifier set? 


More details here:
 

http://docs.particular.net/nservicebus/upgrades/encryption-key-identifiers

**Comment by ramonsmits** [comment]
@fafachd  The encryption documentation has additional details about the key identifier:

http://docs.particular.net/nservicebus/security/encryption

**Comment by fafachd** [comment]
We had not set the key identifier. Thanks for updating the documentation!

**Comment by fafachd** [comment]
You should probably fix the spelling error in the exception details so if people copy the exception details into Google they can find the error ("identifer" should be "identifier").
