### ISSUE TITLE
Add explicit support for controlling what messages are audited

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3192]
Many people want to be able to control of what messages are audited. Based on message type/content/headers.

This was demonstrated at NSBCon london as one of the cool things that can be achieved with the new NSB pipeline.

We have also had several perople ask about this. for example http://stackoverflow.com/questions/29172295/nservicebus-ignore-auditing-specific-message-type

But the realities of this is that it is significant complex to achieve this by plugging into the pipeline. A use would essentially need to fully re-implement the audit feature and replace the existing one. 

Since this is common request it would be good to have a simplified, explicit, api.

moved from here https://github.com/Particular/PlatformDevelopment/issues/250

**Comment by andreasohlund** [comment]
Time to revive the pull from @timbussmann https://github.com/Particular/NServiceBus/pull/1854 ?

**Comment by jonathanrasquin** [comment]
Hi, 

Is there any progress on this issue?

**Comment by timbussmann** [comment]
@SimonCropp are you willing to drive that issue forward on the pdev process (receive short term focus)?

**Comment by jonathanrasquin** [comment]
Thanks guys!

**Comment by tmasternak** [comment]
Removing `Tag: Consider for Short Term Focus`. Please add `Consider for Promotion` if it's still relevant.
