### ISSUE TITLE
Testing transports with multiple topologies

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#3193]
This issue is currently affecting ASB, but could affect any other transport that would have more than one topology (RabbitMQ?).

## Background on the issue

Currently Acceptance Testing framework (ATT) is making certain assumptions about transports. One of the assumptions is that a transport can be instantiated using `Activator.CreateInstance` to query for outbound routing policies in order to determine if a test should or shouldn't be executed. Example:
```c#
.Repeat(b => b.For<AllTransportsWithMessageDrivenPubSub>())
```

There are several problems with this:

1. Transport to relies on a [topology](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Config/AzureServiceBusTransport.cs#L94) to be selected in order to be properly configured. [Topology assignment](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Config/AzureServiceBusTransport.cs#L128) is happening in a feature that is not executed when `Activator.CreateInstance` is used.
1. Transport acceptance testing should go through all topologies, therefore there must be a way to specify topology and pass that into ATT (similar to what's done with transport/connection string)

**Comment by SeanFeldman** [comment]
Currently, for ASB I've hard-wired `StandardTopology` until we find a solution. 

One option would be to allow trhough ATT to wire modifications on Transport and each transport could do whatever it needs to in `SetupAcceptanceTests` [as mocked here](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/AcceptanceTests/SetupAcceptanceTests.cs).

As for the filtering purposes, before endpoints are created, we could invoke customization specified in `SetupAcceptanceTests` func after transport is created by [passing it into the func](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1231/ScenarioDescriptors/AllTransports.cs#L115).

For endpoints that are created and be able to tests all topologies for a given transport, we could assign topology by gaining access to the `Settings` passed into transport when endpoints are created. [Example](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/AcceptanceTests/SetupAcceptanceTests.cs#L16)

@Particular/nservicebus thoughts/comments?

@Particular/azure please note the hardcoded part for ASB

**Comment by andreasohlund** [comment]
>Transport acceptance testing should go through all topologies, therefore there must be a way to specify topology and pass that into ATT (similar to what's done with transport/connection string)

I'd say create transport specific AT:s to cover all the specific topologies?

**Comment by SzymonPobiega** [comment]
I am not sure, what is the benefit of having a single transport with multiple topologies vs having multiple transport (multiple implementations of `TransportDefinition`) in a single package?

**Comment by danielmarbach** [comment]
@andreasohlund Could they use the trick to use the `RuntimeSettings` dictionary we implemented yesterday?

**Comment by andreasohlund** [comment]
>Could they use the trick to use the RuntimeSettings dictionary we implemented yesterday?

I guess, but since this is specific features for ASB I still think creating specific tests for ASB would be better?

**Comment by SeanFeldman** [comment]
@andreasohlund sorry, not following. It's not just some features we want to test that are specific to the transport, we want to exercise _all_ ATTs with each topology under the transport.

**Comment by yvesgoeleven** [comment]
@andreasohlund we already have those, but want to make sure that all topologies are compatible with the core. We do not understand the core fully, we make different assumptions than you guys do, I want to be sure that behavior is not broken by switching out the underlying infrastructure.

**Comment by yvesgoeleven** [comment]
@SzymonPobiega that felt really awkward from a user point of view UseTransport<AzureServicebusWithBasicTopology>()..

**Comment by danielmarbach** [comment]
@Particular/azure-service-bus-maintainers what is the state on this? I removed @SeanFeldman from being assigned since we are currently working on other things. Should we close this?

**Comment by SeanFeldman** [comment]
It's being resolved. ATTs run one topology at a time, so we can close it @danielmarbach.
