### ISSUE TITLE
Creating a Pipeline with Behaviors without StageConnectors should not be possible

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3194]
Currently it is possible to write the following behaviors:

```
class SomeBehavior : Behavior<OutgoingContext>
class SomeBehavior : Behavior<IncomingContext>
class SomeBehavior : Behavior<BehaviorContext>
```

These behaviors compile but will never be invoked by the pipeline. We need to add a check which throws if there are registrations for behaviors which do not belong to a stage.

**Comment by Farol** [comment]
The same issues exists for:
...
class SomeOtherBehavior : Behavior<DispatchContextImpl>
...
It fails silently

**Comment by danielmarbach** [comment]
As of https://github.com/Particular/NServiceBus/pull/3301 you can no longer use the behavior context classes directly.
