### ISSUE TITLE
Objects created in CustomConfig are not available in Context, nor Scenario.Done

### ISSUE THREAD

**Issue by Tra5is** [Particular/NServiceBus#3202]
The callback for defining custom configuration in an acceptance test currently looks like this:

    public EndpointBehaviorBuilder<TContext> CustomConfig(Action<BusConfiguration> action)

If when building an acceptance test the custom config injects new instances into the DI container AND runs in a separate app domain, then those new instances are not available to the test code. 

By adding the context to the CustomConfig action then those new instances can be added to the context and retrieved in Scenario.Done or Given. 

What's important here is that to allow the mock to be inserted into the DI container when using separate app domains, it must be created within the RegisterComponents action, which means it's inaccessible from anywhere else. (Unless there's a reference to it via the context!)

I propose to change the CustomConfig action to this:

    public EndpointBehaviorBuilder<TContext> CustomConfig(Action<BusConfiguration, TContext> action)

A test may look like this:
```
Scenario.Define<Context>()
	.WithEndpoint<Endpoint>(e =>
	{
		e.CustomConfig(c => c.RegisterComponents((r, context) =>
		{
			var myMock = MockRepository.GenerateMock<IMyInterface>();
			myMock.Expect(
				mock => mock.DoStuff(Arg<Request>.Is.Anything))
				.Repeat.Once();

			r.RegisterSingleton(myMock);

			context.Mocks.Add(myMock);
		}));

		e.When(c => c.EndpointsStarted, bus =>
		{
			//exercise code
		});
	})
	.Done(c => c.Mocks.Get<IMyInterface>().VerifyExpectations())
	.Run(new RunSettings { TestExecutionTimeout = TimeSpan.FromSeconds(30), UseSeparateAppDomains = separateDomains });
```

**Comment by timbussmann** [comment]
I don't see a big issue with providing the context to `CustomConfig` (although I can't think of many use cases besides this one).

Is there a specific reason you're using separate AppDomains? We removed that configuration option in the next major version.

**Comment by Tra5is** [comment]
Hey Tim,

We're using separate AppDomains just to enforce clear boundaries between
each endpoint. Some of the endpoints use the same singletons fetched from
the DI container, and we need to ensure these are not shared between
endpoints.

**Comment by timbussmann** [comment]
> Some of the endpoints use the same singletons fetched from
the DI container, and we need to ensure these are not shared between
endpoints.

Are you sharing the same DI container instance over multiple endpoint instances?

**Comment by Tra5is** [comment]
No, the DI container isn't shared. But unfortunately the DI container isn't being used to enforce the singleton lifetime, rather the class is using static methods and variables.
