### ISSUE TITLE
Improved saga mapping api

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3204]
We've been seeing users getting into trouble by forgetting to call `.ToSaga(s=>MyCorrelationProperty)` in their saga mappings. This leads to the mapping not being registered and painful debugging.

Given that v6 will only allow a single correlation property (you will have to use a custom saga finder to have more than one) we can now optimize the api based on this.
### Current API

```
override void ConfigureHowToFindSaga(SagaPropertyMapper<State> mapper)
{
   mapper.ConfigureMapping<OrderAccepted>(m => m.OrderId).ToSaga(s => s.OrderId);
   mapper.ConfigureMapping<OrderPlaced>(m => m.OrderId).ToSaga(s => s.OrderId);                
}
```
### Proposed API

I first started out with a `mapper.CorrelationId(s=>s.OrderId)` proposal but @SimonCropp 
made me realized the benefits of an api that can be enforced at compile time to:
- Give users compiler errors
- Generate scripts to setup tables and indexes

This lead to alternative 2 below. But after talking to @danielmarbach it morphed into alternative 1 below.

Both use the same mapping syntax and only differs in how they annotate the `State` class.

The mappings looks like this: (note that mapper is no longer generic)

```
override void ConfigureHowToFindSaga(SagaPropertyMapper mapper)
{
   mapper.ConfigureMapping<OrderAccepted>(m => m.OrderId);
   mapper.ConfigureMapping<OrderPlaced>(m => m.OrderId);                
}

```

Given this we would have the following state classes
#### Alternative 1

```
//optional: [CorrelationPropertyName("OrderId")]
class State:ContainSagaData<Guid>

```

Where `ContainSagaData` is defined as

```
  class ContainSagaData<T>:IContainSagaData where T : IComparable
            {
                public virtual T CorrelationId { get; set; }

                public virtual Guid Id { get; set; }

                public virtual string Originator { get; set; }

                public virtual string OriginalMessageId { get; set; }
            }
```

The idea is to have the users specify the type of the fixed `CorrelationId` correlated property. This gives a bullet proof api sinceit forces you to exactly one property. We can also restrict the `T` to allow `IComparable` only. This means that we catch most datatype issues att compile time and would only need runtime checks for edge cases like floats and doubles.

The drawback(arguable) with this approach is the fixed name `CorrelationId`which means nothing from a business perspective. To mitigate this we could provide a optional attribute that give the property a "business name" for storage purposes (eg. column name if using NHibernate).
#### Alternative 2

This is quite similar but uses a `CorrelationProperty` attribute instead. This means that the "real" name can be used on the property but wouldn't be as bullet proof from a compile time perspective. That said @SimonCropp has already got some hackery going that plugs into the msbuild pipeline and can check that there is exactly one attribute for all types inheriting from `ContainsSagaData`. 

```
class State:ContainSagaData
    [CorrelationProperty]
    public string OrderId{get;set;}

```

**Comment by mauroservienti** [comment]
I prefer `Alternative 2`, what about adding `BusConfiguration` conventions as well, something similar to:

```
busConfig.DefineSagaCorrelationProperty( (sagaDataType, IEnumerable<PropertyInfo>) => { ... } )
```

We can also introduce some code analyzer in the future.

One thing that I don't know if I like is that the actual design has the clear advantage that all the mapping code is in one place, the `ConfigureHowToFindSaga`, in all the other cases the mapping logic is split into 2 places, the saga and the saga data.

What if:

```
protected override SagaMappingInfo ConfigureHowToFindSaga()
{
   return SagaMappingInfoBuilder.MapSaga<SagaData>( s => s.Property )
                 .ToMessage<OrderAccepted>(m => m.OrderId)
                 .ToMessage<OrderPlaced>(m => m.OrderId);                
}
```

The builder, being a fluent interface, can be designed so that the `MapSaga` method is returning something that is not (yet) a `SagaMappingInfo` instance but something where the only thing you can do is call `ToMessage`, I designed a lot of fluent interfaces in the past for DSL purposes where the goal was to design something *dumb proof*, not easy but can be done, especially in our case where we have only 2 things to do. All can be done in a single class playing with interfaces in order to game the C# intellisense.

**Comment by SimonCropp** [comment]
`busConfig.DefineSagaCorrelationProperty( (sagaDataType, IEnumerable<PropertyInfo>) => { ... } )`

this wont work since @andreasohlund is proposing only supporting one correlation property .

`SagaMappingInfoBuilder.MapSaga<SagaData>( s => s.Property )1

I dont like this syntax since it makes it difficult to derive the saga property at compile time, and hence makes it harder to generate the deployment scripts at compile time

**Comment by mauroservienti** [comment]
> this wont work since @andreasohlund is proposing only supporting one correlation property .

good point, unless the `DefineSagaCorrelationProperty` Func expects as return type one single `PropertyInfo`

> I dont like this syntax since it makes it difficult to derive the saga property at compile time, and hence makes it harder to generate the deployment scripts at compile time

I'm not following, which deployment scripts?

**Comment by SimonCropp** [comment]
@mauroservienti so this https://github.com/SimonCropp/NsbSqlPersistence  

given a saga data like this 

```
   public class SagaData : XmlSagaData
    {
        [CorrelationId]
        public Guid MySagaId { get; set; }
    }
```
as part of a build produces this as part of the build assets

```

declare @tableName nvarchar(max) = '[' + @schema + '].[' + @endpointName + '.MySaga2]';


IF NOT EXISTS 
(
    SELECT * 
    FROM sys.objects 
    WHERE 
        object_id = OBJECT_ID(@tableName) AND 
        type in (N'U')
)
BEGIN
DECLARE @createTable nvarchar(max);
SET @createTable = N'
    CREATE TABLE ' + @tableName + N'(
	    [Id] [uniqueidentifier] NOT NULL PRIMARY KEY,
	    [Originator] [nvarchar](255) NULL,
	    [OriginalMessageId] [nvarchar](255) NULL,
	    [Data] [xml] NOT NULL,
	    [PersistenceVersion] [nvarchar](23) NOT NULL,
	    [SagaTypeVersion] [nvarchar](23) NOT NULL
    )
';
exec(@createTable);
END

declare @dropIndexQuery nvarchar(max);
select @dropIndexQuery = 
(
    SELECT 'DROP INDEX ' + ix.name + ' ON ' + @tableName + '; '
    FROM sysindexes ix
    WHERE 
		ix.Id = (select object_id from sys.objects where name = @tableName) AND
	    ix.Name IS NOT null AND 
	    ix.Name LIKE 'PropertyIndex_%' AND
	    ix.Name <> 'PropertyIndex_MySagaId' 
    for xml path('')
);
exec sp_executesql @dropIndexQuery

IF NOT EXISTS
(
    SELECT * 
    FROM sys.indexes 
    WHERE 
        name = 'PropertyIndex_MySagaId' AND 
        object_id = OBJECT_ID(@tableName)
)
BEGIN
DECLARE @createIndex nvarchar(max);
SET @createIndex = N'
    CREATE  SELECTIVE XML INDEX PropertyIndex_MySagaId
    ON ' + @tableName + '(Data)
    FOR 
    (
        MySagaId = ''/Data/MySagaId'' AS XQUERY ''xs:string'' SINGLETON
    )
';
exec(@createIndex);
END
```

this is then an asset that can be go through standard deployment process rather than doing the "start your endpoint as admin once to run the creation scripts"

**Comment by andreasohlund** [comment]
Not convinced about the SagaMappingInfoBuilder but it does solve on thing for us. We require you to have at least once message that starts the saga and that message needs to have a mapping. That syntax would sort of enforce that. But as @SimonCropp mentions having this info at compile time is really valueble

**Comment by mauroservienti** [comment]
@SimonCropp I was missing that aspect, if we need to achive that then I'm fully :+1: to alternative 2, as said above.

Question: can we achieve the same result, picking up the mapped property at compile time, using my fluent sample and a Roslyn analyzer/thing?

**Comment by SimonCropp** [comment]
@andreasohlund as i have said i can work around this. i got the saga attribute approach in  NsbSqlPersistence working on v5 and have it working on the current version of v6. but lets just say it was not easy to map our current fluent api to a diff fluent api https://github.com/SimonCropp/NsbSqlPersistence/blob/master/Persistence/Saga/MessagePropertyMapper.cs#L19
all so i could only map messages and not saga prop https://github.com/SimonCropp/NsbSqlPersistence/blob/master/Integration/SagaSample/MySaga2.cs#L13

so if producing assets at build time is something we want to enable in other transports i prefer the attribute approach.  

and just to be clear i am not pushing for this. i honestly dont know if this is the ultimate way forward. however as far as i can tell it solves many of the deployment difficulties we currently have

**Comment by SimonCropp** [comment]
@mauroservienti for completeness here are the timeout and subscription scripts also created as part of the build

[Timeout_Create.txt](https://github.com/Particular/NServiceBus/files/59194/Timeout_Create.txt)
[Subscription_Create.txt](https://github.com/Particular/NServiceBus/files/59193/Subscription_Create.txt)

**Comment by SimonCropp** [comment]
@mauroservienti 

> using my fluent sample and a Roslyn analyzer/thing

no since the code that executes the fluent api could exist in another assembly. also Roslyn analyzer are not designed to add assets to the build pipeline. you would actually need to replace the compiler to achieve that

**Comment by mauroservienti** [comment]
oh yes.

**Comment by danielmarbach** [comment]
@mauroservienti can you explain a bit more why you opt for Alternative 2 instead of Alternative 1?

**Comment by danielmarbach** [comment]
Alternative 2 forces us to hack the MSBuild process to check during compilation time wether the correlation property is properly annotated. Alternative 1 forces you to declare the type always.

**Comment by SimonCropp** [comment]
> Alternative 2 forces us to hack the MSBuild process to check during compilation time wether the correlation property is properly annotated.

confused. both 1 and 2 can be validated at build time or run time.

**Comment by danielmarbach** [comment]
@andreasohlund Explained me that Alternative 2 requires you to wrote a custom MSBuild integration. Alternative 1 doesn't need that. There is no way you can forget to define the correlation property.

**Comment by SimonCropp** [comment]
@andreasohlund lied to u. both option 1 and option 2 can be used at compile OR run time

**Comment by danielmarbach** [comment]
Without hacking mbsuild and therefore deploying a custom msbuild task into the users csproj?

**Comment by SimonCropp** [comment]
> Without hacking mbsuild and therefore deploying a custom msbuild task into the users csproj?

neither option 1 or 2 require that to work. they can both function in the old way of being evaluated at runtime.

the thing the attribute approach (both 1 and 2) enable over the fluent api is **the option** to produce things at compile time if we desire to go down that path.

**Comment by andreasohlund** [comment]
> @andreasohlund lied to u. both option 1 and option 2 can be used at compile OR run time

My bad :(

In that case I'm :+1: for alternative 2 since I thing it reads better and having the property on the "state" class is more intuitive and faimiliar to the users IMO

**Comment by DavidBoike** [comment]
With Alternative 2 what happens if the user forgets `[CorrelationProperty]`? Honestly people are going to look at that and say "Oh look, they renamed `[Unique]`. I'm not sure that's bad, and I think (maybe) I might be in favor of Alternative 2 at first blush, but there has to be some non-optional way (Roslyn?) to verify it's added and only once.

**Comment by colin-higgins** [comment]
I prefer Alternative 1. It seems less complicated from our end, and if users want to assign business value to the correlation id, why not do something like this?

```
    public virtual Guid OrderId { get { return CorrelationId; } set { CorrelationId = value; } }
```

Saying that, I am still okay with Alternative 2. I just think Alternative 1 makes it harder to screw up.

**Comment by SimonCropp** [comment]
I slightly prefer option 

@DavidBoike yes both options are trivial to verify at startup, at compile time or with a roslyn analyser.

**Comment by andreasohlund** [comment]
> Honestly people are going to look at that and say "Oh look, they renamed [Unique]. I'm not sure that's bad, and I think (maybe) I might be in favor of Alternative 2

That's my take as well, I belive that this will be easier for the users to grok from an upgrade perspective.

Another pro for Alt.2 is that it's backwards compatible from a data perspective since the "column" names stays the same without the user having to put the `[BusinessName("OrderId")]` (or what ever we would call it) on his state class.

For the above reasons I'm in favor of alt.2 since I think it would be more intuitive for the users.

**Comment by SimonCropp** [comment]
@andreasohlund i think so
