### ISSUE TITLE
Make TimeToBeReceived when having databus properties

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3205]
When messages have Databus properties and no `TimeToBeReceived` is set this basically indicates that the databus blobs can never be purged as the TTL will never expire.

By making  `TimeToBeReceived` required for messages with databus properties it is forcing message designers to think about databus blob expiration/purging policy.

**Comment by andreasohlund** [comment]
I would propose that we introduce a databus storagage specific "max time" instead. Kind of similar to the "max 7 days" that ASB has for messages in its queues?

**Comment by ramonsmits** [comment]
@andreasohlund I like that idea. That could mean that it its lifespan can be longer than the TTBR of the message which could be inline with archive policy for audit messages.

**Comment by timbussmann** [comment]
since TTBR doesn't work well with MSMQ, this doesn't seem to be a valid option? Should we close this issue and discuss possible solutions in the pdev issue you raised @ramonsmits ?

**Comment by ramonsmits** [comment]
@timbussmann The reasoning that because MSMQ has unexpected TTBR behavior is more of a concern to MSMQ. 

The reason for this issue is the abilty to to controlled purged of databus blobs. I do think now that explicitly setting the TTBR value suggestion is not a good solution for that and that it should be solved in another way and that concern is addresses in the platform dev issue so I'm fine with closing this.

**Comment by timbussmann** [comment]
> and that it should be solved in another way and that concern is addresses in the platform dev issue

:+1: closing this then
