### ISSUE TITLE
How to implement callbacks in IDispatchMessages

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3217]
I am a bit stuck on rewritting the RabbitMQ implementation of ISendMessages to IDispatchMessages.

So in Rabbit we were checking if a message intent was a reply and then chnage the destination address based on that.
How do i go about doing the same in IDispatchMessages ?

Here is the code rabbit is using:
```c#
static bool IsReply(SendOptions sendOptions)
{
      return sendOptions.GetType().FullName.EndsWith("ReplyOptions");
}
```

yes it is a bit of a hack, is there a cleaner way of doing this now ? Does the ContextBag give me that info ?

**Comment by johnsimons** [comment]
@SzymonPobiega @andreasohlund @danielmarbach anyone knows ?

**Comment by andreasohlund** [comment]
@weralabaj @tmasternak how did you handle this in the sqltransport?

**Comment by weralabaj** [comment]
@andreasohlund We didn't, because callbacks don't compile with the latest changes in core. They need to be updated first, but that's waiting for @timbussmann changes.

**Comment by danielmarbach** [comment]
@weralabaj not entirely true ;) I updated them :dancer: and they are almost on latest

**Comment by weralabaj** [comment]
@danielmarbach I didn't get to that email yet :D

**Comment by timbussmann** [comment]
> but that's waiting for @timbussmann changes.

which changes?

**Comment by weralabaj** [comment]
@timbussmann Last time we talked we decided that your work on context can impact callbacks a lot and we wanted to avoid rework, or did I misunderstand?

**Comment by timbussmann** [comment]
I think that discussion was more about if it's an async task or a general task since handler context also affects the callbacks update. HandlerContext is pretty stable from an API perspective since weeks already.

**Comment by johnsimons** [comment]
I think there seems to be a misunderstanding here.
The callback impl that I assume you are referencing is https://github.com/Particular/NServiceBus.Callbacks, which I am pretty sure that it does not have much to do with this.
This has to do with the sending messages to the callback queue that is maintained by the transport themselves not NServiceBus.Callbacks, unless everything is changed ?

**Comment by weralabaj** [comment]
@johnsimons Right, I was thinking about NServiceBus.Callbacks.

**Comment by johnsimons** [comment]
I think I know how to implement this, it seems I just add a behavior to `OutgoingReplyContext` and add a flag to the Extensions bag, that then is accessible from IDispatchMessages.

Is this what I am suppose to do ?

**Comment by danielmarbach** [comment]
@johnsimons are you talking about the `MessageIntent`? 

You can get that on the TransportOperation.OutgoingMessage

**Comment by tmasternak** [comment]
@johnsimons do you mean NServiceBus.Callbacks was not intended to replace the transport specific implementations?

**Comment by johnsimons** [comment]
@tmasternak yes

**Comment by johnsimons** [comment]
@danielmarbach will try that and see if it works

**Comment by timbussmann** [comment]
@johnsimons can we close this?

**Comment by johnsimons** [comment]
Aren't callbacks now part of the core ?
So I guess we don't need to do this anymore ?
The best person to answer this is @bording

**Comment by danielmarbach** [comment]
Ok, @bording please close this if no longer necessary.

**Comment by bording** [comment]
@johnsimons Is correct. Callbacks are in core, so it's not needed now.
