### ISSUE TITLE
ContextBag.Remove by key missing ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3219]
It seems I can store an object by key but can't remove it by key, is this by design ?

```c#
context.Extensions.Set("MySpecialKey", mySettings);
context.Extensions.Remove("MySpecialKey"); // <-- This does not work
```

**Comment by andreasohlund** [comment]
Probably just an oversight, what is the use case? can you make it strongly typed?

**Comment by hmemcpy** [comment]
pinging @Particular/tf-handlercontext

**Comment by timbussmann** [comment]
yes `ContextBag.Remove(string key)` is private. I think it makes sense to be public if there is a `Remove<T>()` operation.

**Comment by johnsimons** [comment]
I can fix this one tomorrow @timbussmann.

@andreasohlund the issue is not about strongly typed or not, the issue is about consistency of the public api

**Comment by andreasohlund** [comment]
>the issue is not about strongly typed or not, the issue is about consistency of the public api


Fair enough, just asking if a strongly typed api might be better in that specific case. Still :+1: to add a string overload
