### ISSUE TITLE
Unicast vs Multicast and validation

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3225]
I have notice some inconsistence in transport implementation.

So it seems the transport implementer is declaring upfront the intentions by using the
```c#
public override OutboundRoutingPolicy GetOutboundRoutingPolicy(ReadOnlySettings settings)
{
            return new OutboundRoutingPolicy(OutboundRoutingType.Unicast, OutboundRoutingType.Multicast, OutboundRoutingType.Unicast);
}
```

But then the [MSMQ impl throws](https://github.com/Particular/NServiceBus/blob/b14903ab4955cdd130a27df12d3c686ddc41490f/src/NServiceBus.Core/Transports/Msmq/MsmqMessageSender.cs#L52-L57)
shouldn't the framework prevent this ?

**Comment by timbussmann** [comment]
@johnsimons this seems to be outdated, can you check whether we can close this or update the description?

**Comment by andreasohlund** [comment]
Pretty sure this is no longer an issue with the new routing., @johnsimons please reopen if needed @johnsimons
