### ISSUE TITLE
TransportDefinition.GetDiscriminatorForThisEndpointInstance return value ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3227]
Am I right in assuming that the discriminator for most transport implementations is the current machine name ?
And for Azure is whatever the host tells us ?

What is this used for ?
Does this has any implications on the callbacks queue ? 

So for Rabbit I return machine name ?

**Comment by andreasohlund** [comment]
Pretty sure that the discriminator is what goes between the main address and the satellite addresses so I think a `.` is what rabbit should be using?

**Comment by johnsimons** [comment]
I don't think that is it, see https://github.com/Particular/NServiceBus/blob/551f1c1d14e2d84241b499eadfe3b6ef73f896ae/src/NServiceBus.Core/Transports/Msmq/Msmq.cs#L143-L154

Or maybe I am completely lost here!

**Comment by andreasohlund** [comment]
Ah, now I'm lost as well, seems I mixed up discriminator and qualifier. @SzymonPobiega @janovesk can you shed some light on this?

**Comment by johnsimons** [comment]
Thank you @andreasohlund for validating that I am not going crazy yet ;)

**Comment by SzymonPobiega** [comment]
@johnsimons @andreasohlund discriminator was a term we used for scale-out in V5. `Qualifier` is the one for satellites. 

@johnsimons RabbitMQ should return `null` there as there is no native thing we can use for uniquely naming endpoint instances that use RabbitMQ. This value is used only for MSMQ and Azure transport and in fact there is a PR pending review that removes it.

**Comment by johnsimons** [comment]
@SzymonPobiega what PR is that ?
Do you want another pair of eyes on it, or do u want me to test drive it as part of the rabbit impl ?

**Comment by SzymonPobiega** [comment]
Here's the PR: https://github.com/Particular/NServiceBus/pull/3195

I'll do final touches today.

**Comment by andreasohlund** [comment]
@SzymonPobiega since the PR is merged can we close this?
