### ISSUE TITLE
How to register a pipeline step for the transport ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3228]
I am trying to figure out how to register a pipeline step as part of the `TransportDefinition` impl of rabbitmq transport.

For a bit of context.

Rabbit uses a publishing channel to send messages out, so as part of the transport impl we used to register a "caching" layer as a pipeline step to reuse the channel (more efficient this way).

So we used to register this step as part of the implementation of rabbitmq transport.
But now, I am struggling to figure out how to do this ?
Do I go back to features ?

**Comment by andreasohlund** [comment]
Would just adding the channel to the context like MSMQ does with its native transaction work?

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/ReceiveWithNativeTransaction.cs#L44

**Comment by johnsimons** [comment]
So @andreasohlund you saying that I should create the channel as part of the dequeuing of the message ?
So there is no way to register a step in the pipeline  from a transport implementor.

**Comment by andreasohlund** [comment]
>So @andreasohlund you saying that I should create the channel as part of the dequeuing of the message ?

That seems resonable, you already have the channel available there right?

>So there is no way to register a step in the pipeline from a transport implementor.

You can add a feature and do it there but I have a hunch that needing that is smell and indicates potential flaws in the transport api?

**Comment by johnsimons** [comment]
> That seems resonable, you already have the channel available there right?

Not sure, need to work it out tomorrow



> You can add a feature and do it there but I have a hunch that needing that is smell and indicates potential flaws in the transport api?

I have been raising issues in areas of the api that I think are quite difficult to use, hopefully these will feed the discussion into a better api

**Comment by timbussmann** [comment]
@johnsimons is this still an issue or can we close it?

**Comment by andreasohlund** [comment]
Transports are no longer using behaviors (cc @Particular/transport-maintainers ), closing this one

**Comment by tmasternak** [comment]
@andreasohlund As a note SqlServer uses one for callback backwards compatibility.

**Comment by bording** [comment]
> As a note SqlServer uses one for callback backwards compatibility.

RabbitMQ does also.

**Comment by andreasohlund** [comment]
Got it, I assume it works?
