### ISSUE TITLE
How to implement callbacks in TransportDefinition ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3229]
Please help.

For transports that use a secondary queue for callback receives, where do i now put all this logic?

@SzymonPobiega I remember u showing us a different pipeline for this kind of thing, is that the way to do it ?

**Comment by timbussmann** [comment]
@johnsimons can we close this?

**Comment by danielmarbach** [comment]
We have #3406 and related work. Closing this one
