### ISSUE TITLE
IWantToRunBeforeConfigurationIsFinalized should receive a BusConfiguration instance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3230]
In V5 the `IWantToRunBeforeConfigurationIsFinalized` interface exposes a method, `Run`, that expects to receive a `Configure` instance but it should instead receive a `BusConfiguration` instance to be aligned with the V5 configuration API. Most of the operations on the `Configure` class are `deprecated` causing the `IWantToRunBeforeConfigurationIsFinalized`  to be useless.

**Comment by andreasohlund** [comment]
The only usage in the core is the persistence startup

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/PersistenceStartup.cs

How about we make this a feature and obsolete `IWantToRunBeforeConfigurationIsFinalized` instead?

**Comment by mauroservienti** [comment]
@andreasohlund agree, as discussed with @SimonCropp as well, we should leave it as is in V5 and deprecate it in V6.

**Comment by mauroservienti** [comment]
Currently in V6 the `IWantToRunBeforeConfigurationIsFinalized.Run` method receives a `SettingsHolder` instance, as discussed with @danielmarbach we should change all the public interfaces that deal with the bus configuration and that the end user can deal with to handle a `BusConfiguration` instance.

**Comment by timbussmann** [comment]
@mauroservienti @danielmarbach what should we do with this one? It seems to be wrong to pass an `EndpointConfiguration` at that stage of the endpoint startup?

**Comment by andreasohlund** [comment]
This is tricky, the name implies that it can be used to modify config since we call it "before config is finalized". I'm pretty sure that we assume that no more config calls can be done so passing the EC would be misleading. 

Thinking that the whole thing should be killed in the long run and it's currenly only used by the persistence startup (which is a smell). We could hard code the persistence startup (just like we do with the transport startup) and obsolete the interface?

Only downstream that is using this is the azure multihost and [this pull ](https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/22) removes that usage.

**Comment by timbussmann** [comment]
> Thinking that the whole thing should be killed in the long run and it's currenly only used by the persistence startup (which is a smell). We could hard code the persistence startup (just like we do with the transport startup) and obsolete the interface?

:+1:  "BeforeConfigurationIsFinalized" is a really weird extension point.

**Comment by danielmarbach** [comment]
As it currently stands it is right to pass in the `SettingsHolder`.

About obsoleting it. How about we do a more thorough investigation first like looking through ggroups and docs page and google for what purpose other people are using it before we go ahead with a decision? We have been burned before by just looking out our ecosystem...

**Comment by andreasohlund** [comment]
I agree with @danielmarbach passing settingsholder is close enough for v6. I've raised a new issue to [deprecate IWantToRunBeforeConfigurationIsFinalized](https://github.com/Particular/NServiceBus/issues/3619) 

@mauroservienti I'm closing this issue, please reopen if feel otherwise
