### ISSUE TITLE
Support DI of BusContext

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3232]
With handler context we removed the ability to inject `IBus` everywhere DI was supported. While we don't provide this by default any longer and recommend floating the context, we should provide users the ability to register the current context on the pipeline's child-container themselves.

**Comment by andreasohlund** [comment]
Would doco be enough or are you proposing some kind of core api to do this?

**Comment by timbussmann** [comment]
@danielmarbach checked quickly and we think it's currently not possible to manually register the context in the child-context. Need to verify. Other than that, providing doco with sample code should be good.

**Comment by andreasohlund** [comment]
At least with structuremap you can take a dependency on `StrunctureMap.IContainer` and register it (eg. from a behavior)

**Comment by timbussmann** [comment]
that could probably be a bit more complicated with Ninject named scopes?

**Comment by timbussmann** [comment]
so it currently seems this will only be possible by using the container directly in case the container supports runtime bindings at all. Closing this for now.
