### ISSUE TITLE
MSMQ should support NonDurableDelivery constraint

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3236]
I think NonDurableDelivery constraint is missing in the Msmq transport definition ?

Here is the code where I think is missing https://github.com/Particular/NServiceBus/blob/551f1c1d14e2d84241b499eadfe3b6ef73f896ae/src/NServiceBus.Core/Transports/Msmq/Msmq.cs#L106-L109

**Comment by andreasohlund** [comment]
:+1:

**Comment by andreasohlund** [comment]
This means that we don't support non durable messages. Flagging this as core v6.

We need to

1. Add the contraint to the transport infrastructure
2. Add a msmq acpt test to repro this

**Comment by timbussmann** [comment]
> This means that we don't support non durable messages. Flagging this as core v6.

sidenote: this property is only used in features for prerequiste checks. non durable messages should still work.

**Comment by timbussmann** [comment]
fixed with with #3819
