### ISSUE TITLE
Should DiscardIfNotReceivedBefore be in the NServiceBus root namespace?

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3237]

**Comment by andreasohlund** [comment]
Since it's a transport concern I propose `NServiceBus.Transports`

**Comment by johnsimons** [comment]
@andreasohlund all other concerns are in the root NServiceBus namespace, so should everything else move as well ?

**Comment by andreasohlund** [comment]
@SimonCropp @timbussmann @danielmarbach did we agree on the namespace rules?(where did we write it down?)

@johnsimons I'd say yes, all transport api's should be in the same namespace. 

@simoncropp did you propose `NServiceBus.Transport` ? (no plural s)

**Comment by johnsimons** [comment]
We may be thinking this too much.
Also I think we will be changing the concerns to be a enum flags.

Anyway, IMO the concerns (whatever it becomes) should live in the same namespace as `IPushMessages`

**Comment by andreasohlund** [comment]
>Anyway, IMO the concerns (whatever it becomes) should live in the same namespace as IPushMessages

agreed

**Comment by timbussmann** [comment]
@andreasohlund I asked about documentation of namespace rules here #3218 , no agreement/results so far.

**Comment by andreasohlund** [comment]
We now have agreement, https://github.com/Particular/NServiceBus/pull/3218, lets move this to `NServiceBus.Transport` ?

**Comment by timbussmann** [comment]
> lets move this to NServiceBus.Transport

:+1:

**Comment by andreasohlund** [comment]
Issue raised to track the namespace move https://github.com/Particular/NServiceBus/issues/4181
