### ISSUE TITLE
Migrating NServiceBus.Host.RoleManager to V6 How to do Transactions Disable without knowing transport

### ISSUE THREAD

**Issue by petersgiles** [Particular/NServiceBus#3238]
in NServiceBus.Host.RoleManager.cs after upgrading to NSB v6-latest-unstable

This line says its Obsolete
```
         config.Transactions().Disable();
```

From the Core

```
[EditorBrowsable(EditorBrowsableState.Advanced)]
    [Obsolete("Please use `config.UseTransport<MyTransport>().Transactions(TransportTransactionMode.None);` instead. Will be removed in version 7.0.0.", true)]
    public TransactionSettings Disable()
    {
      throw new NotImplementedException();
    }

```

How do I make it work without any knowledge of what Transport is being used

**Comment by andreasohlund** [comment]
Set it like this https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs#L20

**Comment by andreasohlund** [comment]
You probably want to use `Set` instead of `SetDefault`

**Comment by petersgiles** [comment]
`Settings` is an internal property. Is this intended behaviour?

**Comment by andreasohlund** [comment]
There is a .GetSetting() backdoor that you should use:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/AdvanceExtensibilityExtensions.cs#L13

does that work?

**Comment by petersgiles** [comment]
It compiles now

To Summarise

``` C#
// new API makes this obsolete
config.Transactions().Disable();

// this is how to do it but the Settings property is internal
config.Settings.Set<TransportTransactionMode>(TransportTransactionMode.ReceiveOnly);

// sneaky backdoor compiles
config.GetSettings().Set<TransportTransactionMode>(TransportTransactionMode.None);

```
