### ISSUE TITLE
Creating queues

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3247]
In v6 we have a new way to create queues using QueuesBindings.

But looking at the [msmq impl](https://github.com/Particular/NServiceBus/blob/a612a8745e001c1811801938e73534ccacdef25f/src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs#L29-L32) it looks like the endpoint is also creating queues for "sending addresses", which I think don't belong to the endpoint.

It seems wrong to create queues for destination addresses, is this right ?

**Comment by andreasohlund** [comment]
Yes creating send addresses is wrong since only the "owner" would know that the name is correct or what security settings should be used. 

A development only transport should probabably do it but not a production grade transport.

@Particular/nservicebus thoughts?

**Comment by johnsimons** [comment]
So do we do `If Debbugging` ? Because otherwise `audit` and `error` are not created ?

**Comment by SzymonPobiega** [comment]
@johnsimons I changed the `IWantQueuesCreated` to `QueueBindings` only to allow the dynamic adding of new queues without introducing types inheriting from `IWantQueueCreated`. The bindings are not used for other endpoint's queues, just for audit and error.

**Comment by andreasohlund** [comment]
Should we rename them to something other than "sending" to avoid confusion? How about "shared" ?

**Comment by johnsimons** [comment]
But even those shared queues should not be created by the endpoint right ?

**Comment by SzymonPobiega** [comment]
They should not but this is a shitty compromise to get the `F5` experience. I am all for disabling auto-create if we can provide same experience.

**Comment by andreasohlund** [comment]
>They should not but this is a shitty compromise to get the F5 experience. I am all for disabling auto-create if we can provide same experience.

If we had a dev only transport we should create there to have a nice F5 experience, for now IsDebuggerAttached seems like the best we can do?

**Comment by johnsimons** [comment]
How about acceptance tests ?

**Comment by andreasohlund** [comment]
>It seems wrong to create queues for destination addresses, is this right 

It turns out that sending really should be renamed to `system` or `shared`, this is tracked here https://github.com/Particular/NServiceBus/issues/4151

So in essense we're creating the shared `error` and `audit` queues. We have some vague plans to stop doing this and instead generate scripts to create those queues and educate users how to run those scripts to prepare their environments. 

I'm closing this since I don't see any immediate action points. Please re-open if you feel differently

**Comment by SeanFeldman** [comment]
`system` @andreasohlund, `system` 😉
