### ISSUE TITLE
It doesn't look like the pipeline satellites inherit the max concurrency setting

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3248]
Not sure if this is on purpose ?

See https://github.com/Particular/NServiceBus/blob/a612a8745e001c1811801938e73534ccacdef25f/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L35

The `PushRuntimeSettings.Default`, sets by default 100

**Comment by andreasohlund** [comment]
Its on purpose, we decided to that concurrency settings only applies to the main receiver. Should a satellite want to provide concurrency settings it should expose a specific code api for it. Does this make sense?

**Comment by johnsimons** [comment]
> Should a satellite want to provide concurrency settings it should expose a specific code api for it. Does this make sense?

So do all core satellites support tunning of max concurrency?, I could not figure it out how to do it ? and 100 by default is way too many

**Comment by andreasohlund** [comment]
>So do all core satellites support tunning of max concurrency?

None of them supports it.

> and 100 by default is way too many

Why is 100 to many? (remember that in v6 concurrency != number of threads)

**Comment by johnsimons** [comment]
> in v6 concurrency != number of threads

So u saying I should rump up and rump down on demand ?

**Comment by johnsimons** [comment]
Do we have something in the core that helps with that ?

**Comment by andreasohlund** [comment]
Check with @tmasternak and @weralabaj , they must have done something similar in sqlserver

**Comment by tmasternak** [comment]
In SqlServer we are using MaxConcurrency for all receivers including satellites. 

That being said I think that two questions which we should answer (and @danielmarbach is probably a good person to ask) are
* do we want to have a single setting for all recivers
* what should be a default value for MaxConcurrency

**Comment by johnsimons** [comment]
If I correctly recall, @yvesgoeleven has asked before(when we introduced sattelites) to be able to control the max concurrency setting for satellites because in Azure it can get quite expensive.
So in essence we are kind of prioritising traffic.

@yvesgoeleven is this right ?

**Comment by yvesgoeleven** [comment]
It used to be pretty expensive yes, but today it's okayish
- ASQ is now €0.031 per 1,000,000 transactions
- ASB, for a Standard messaging namespace, is a fixed base charge of €8.433/mo, which includes 12.5M operations, from there on it's a degressive charge of €0.67 per 1,000,000 transactions. Other namespace types have different rates, Basic is €0.0422 per million operations without a base rate, so in the same range as ASQ. Premium is fixed rate of €9.386 per day per throughput unit, number of operations doesn't matter there.

I haven't had complaints about this aspect in the past year, so I guess we're good here

**Comment by yvesgoeleven** [comment]
Btw, we also apply the maxconcurrency settings to all our receivers, so sattelites will be concurrent just like the main transport. If this is wrong, then there should be a way for us to know in the pump what should run at which concurrency.

**Comment by andreasohlund** [comment]
>Btw, we also apply the maxconcurrency settings to all our receivers, so sattelites will be concurrent just like the main transport. If this is wrong, then there should be a way for us to know in the pump what should run at which concurrency.

It's just the max value. Each transport is free to optimize as they see fit. Eg. the sqlserver transport has and adaptive algoritm to ramp up as needed. Could ASB/ASQ use the same behavior to save on storage OPS under low load?

**Comment by yvesgoeleven** [comment]
Yep it slows down, but I was more referring to this

>>So do all core satellites support tunning of max concurrency?

>None of them supports it.

For a transport all queues are equal, so if any sattelite needs guaranteed lower concurrency, then this information needs to somehow be fed into the pump

**Comment by andreasohlund** [comment]
>For a transport all queues are equal, so if any sattelite needs guaranteed lower concurrency, then this information needs to somehow be fed into the pump

All satellits pass the value they like (which is max for now). It's just that we don't allow the end users to tweak it since we couldn't find any use cases for it.

Does this make sense?

**Comment by johnsimons** [comment]
@andreasohlund so how does a tranport impl tweak those settings ?

**Comment by andreasohlund** [comment]
You mean how a satellite tweak the settings?

**Comment by andreasohlund** [comment]
Assuming you mean't satellites you would pass a custom push runtime setting here

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L35

**Comment by johnsimons** [comment]
I mean how does a transport implementer tune these settings for the satellites ?

**Comment by johnsimons** [comment]
I guess what I am saying is that, a user is in control of the max concurrency setting for the main queue, but not the subqueues, which to me does not make sense, since the subqueues is what you would want to deproriize

**Comment by johnsimons** [comment]
So @andreasohlund,vif a user sets max concurrency to 10, I think it makes sense to apply that max to all queues not just the main, thoughts ?

**Comment by tmasternak** [comment]
I think that we have two questions we need to answers:
 * do we want user to be able to change maxconcurrency per satellite 
 * do we want each transport to be able to set specific values per satellite

**Comment by andreasohlund** [comment]
> I think it makes sense to apply that max to all queues not just the main, thoughts ?

Don't agree, satellites are special purpose things and it's up to each satellite to decide.

Let's say I have a non threads safe component and want to run with "1". Why would that force the gateway to run with "1" as well?

I propose we keep the current behavior and expose custom apis as we see the need for it.

Eg the gateway could have: `.Gateway().MaxConcurrentHttpRequest(X)` this has the benefit of use being to provide a api that makes sense for the given use case (note the Http in the name)

>do we want user to be able to change maxconcurrency per satellite

I'd say yes. And more importantly not inherit the setting on the main endpoint

>do we want each transport to be able to set specific values per satellite

I'd say no. The transport should try to honor the setting in the most efficient way it can (eg the adaptive model in SQL Server Transport)

**Comment by andreasohlund** [comment]
As mentioned in my last [comment ](https://github.com/Particular/NServiceBus/issues/3248#issuecomment-165796034)I propose we close this one

**Comment by danielmarbach** [comment]
Closing based on https://github.com/Particular/NServiceBus/issues/3248#issuecomment-210417646
