### ISSUE TITLE
InvalidOperationException 'Collection was modified' while modifying outgoing headers

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3250]
An `InvalidOperationException` occurs when updating the `IBus.OutgoingHeaders` dictionary while another thread is enumerating the dictionary when sending a message.

Affected versions: pre v5.0

The cause is that before v5 the outgoing headers collection is a regular `Dictionary<string,string>` and not of type `ConcurrentDictionary<string,string>` which it is in v5.

**Comment by ramonsmits** [comment]
Encryption service is modifying the outgoing headers collection that made us aware of this.

Primary question is, are we allowed to modify the outgoing headers collection?

If it is, then it must be a concurrent dictionary. If it is not, than why is it a concurrent dictionary in v5?

**Comment by SimonCropp** [comment]
As per the doco that api is only designed to be used at startup http://docs.particular.net/nservicebus/messaging/header-manipulation#writing-outgoing-headers-for-all-outgoing-messages. This has already been fixed in v6
