### ISSUE TITLE
Thread created for each message received due to not making use of threadpool with MSMQ transport

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3251]
A thread is created for each received message via the MSMQ transport. This is caused by passing `TaskCreationOptions.LongRunning` resulting in not using the threadpool.

## Affected versions: 4.x & 5.x

This is limiting performance due to expensive thread creation and also unnecessarily allocating resources.

## Possible solutions

- Not specifying `LongRunning`
- Using a custom thread pool as in v3
- Using `ThreadPool.QueueUserWorkItem`

## References
- [5.2.x](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs#L175
)
- [4.7.x](https://github.com/Particular/NServiceBus/blob/support-4.7/src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs#L170)
- [3.3.x](https://github.com/Particular/NServiceBus/blob/support-3.3/src/impl/unicast/transport/NServiceBus.Unicast.Transport.Transactional/TransactionalTransport.cs) (Uses a custom worker thread collection, not affected)

**Comment by ramonsmits** [comment]
As commented by @danielmarbach , by making use of a (custom) thread pool we are breaking behavior where current customers could be relying on meaning we cannot just modify this as that could break current implementations.

An option would be to make it configurable to make use of the current behavior or to use the or a custom thread pool.

**Comment by ramonsmits** [comment]
Seems that previously a custom scheduler was used:

- https://github.com/Particular/NServiceBus/commit/904802ce841f9d609e1e3d976f3bc771065934aa#diff-1d4ae15bdf6502b1c319704af8c04cb6
- https://github.com/Particular/NServiceBus/commit/904802ce841f9d609e1e3d976f3bc771065934aa
- https://github.com/Particular/NServiceBus/issues/1102

This resulted in issues when customers re-used this scheduler when making use of TPL. Reason was that the custom MTA scheduler was not hidden with `TaskCreationOptions.HideScheduler`. A similar issue was present in the Gateway ( https://github.com/Particular/NServiceBus.Gateway/issues/16 )

Instead of hiding the custom scheduler it was removed and since then messages were processed on a new thread with options `LongRunning` resulting in a new thread for each message.

`LongRunning` was probably choosen to prevent that NServiceBus worker threads would otherwise deplete the default threadpool scheduler when using a large number of worker threads.

**Comment by SimonCropp** [comment]
There is no reason to backport this. If it is fixed in v6 lets leave it as is

**Comment by danielmarbach** [comment]
I'm with @SimonCropp

Let's close it

**Comment by timbussmann** [comment]
closing this as suggested
