### ISSUE TITLE
List on up-for-grabs.net

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3253]
We should start labelling issues as up-for-grabs and show them on [Up-for-grabs.net](http://up-for-grabs.net/) website.

So the *action items* would be

- [x] Add a `Tag: Up For Grabs` label
- [x] List on http://up-for-grabs.net/ - https://github.com/up-for-grabs/up-for-grabs.net/pull/299

@adamralph @andreasohlund join the taskforce?

taskforce: @danielmarbach @andreasohlund @adamralph

**Comment by andreasohlund** [comment]
I'm in


Why just this repo? Why not all our repos?

**Comment by danielmarbach** [comment]
Learn big, fail small. Lead by example.

**Comment by adamralph** [comment]
:+1: let's :shipit:

**Comment by adamralph** [comment]
Took a guess at some labels - not sure what `Type: ` it should be. In other projects I've tended to lump this under docs, e.g. https://github.com/FakeItEasy/FakeItEasy/issues/452

**Comment by adamralph** [comment]
Converted the action items to check boxes.

**Comment by adamralph** [comment]
@danielmarbach @andreasohlund @adamralph

Calling the label `up-for-grabs` is a bit messy. Any objections to `Tag: Up For Grabs` to match our convention?

I suggested elsewhere that we could change our convention so that anything without a prefix is implicitly a tag, but that will also result in quite a messy list of labels in the dropdown, etc.

**Comment by andreasohlund** [comment]
Fair enough, :+1:

**Comment by adamralph** [comment]
I synced the `Tag: Up For Grabs` across all public repos, plus the explicit private ones (https://github.com/Particular/PBot/pull/63 still needs merging to reflect this).

**Comment by adamralph** [comment]
And we're done! Thanks to @jrusbatch
