### ISSUE TITLE
Make 'Default' ScenarioDescriptor run the correct transport for an endpoint

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#3258]
The ATT's contain some tests that deliberatly use a 'FakeTransport' in their endpoint configuration. However the Default ScenarioDescriptor doesn't take this into account. In some (most?) ATT transport variants it appears to work, but that could be sheer luck.

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Transports.cs#L28
- If a specific transport is set using an environment variable, then the test will resolve that transport only, try to cast it to the transport set by the endpoint and blow up.
- If more than 1 (faked) transport would be found in the test run, then msmq would be returned, and again an invalid cast

Somehow, this Default descriptor should always find the transport set by the test endpoint

**Comment by timbussmann** [comment]
@yvesgoeleven since https://github.com/Particular/NServiceBus/pull/3259 has been merged, can this one be closed?

**Comment by andreasohlund** [comment]
Pretty sure this is fixed
