### ISSUE TITLE
Standardize our public namespaces

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3265]
Namespaces are used to help end users and extensibility developers find what they are looking for. There have been talks on standardizing on a few namespaces for our public types.

`NServiceBus`  is the obvious one where we keep types that should be of interest for our end users. Examples here are `IHandleMessages`, `Saga`, all config methods etc.

To help find a set of valid "sub" namespaces I dumped what we have so far:

```

NServiceBus.Satellites(2)
NServiceBus.UnitOfWork(1)
NServiceBus.Serializers.XML(1)
NServiceBus.Serializers.Json(1)
NServiceBus.ObjectBuilder(4)
NServiceBus.ObjectBuilder.Common(1)
NServiceBus.MessageInterfaces(1)
NServiceBus.MessageInterfaces.MessageMapper.Reflection(1)
NServiceBus.Installation(1)
NServiceBus.Encryption(1)
NServiceBus.SecondLevelRetries.Config(1)
NServiceBus.Support(1)
NServiceBus.Settings(4)
NServiceBus.Hosting(1)
NServiceBus.Hosting.Helpers(3)
NServiceBus.AutomaticSubscriptions.Config(1)
NServiceBus.Logging(6)
NServiceBus.Gateway.Deduplication(1)
NServiceBus.Configuration.AdvanceExtensibility(2)
NServiceBus.TransportDispatch(1)
NServiceBus.Serialization(4)
NServiceBus.InMemory.Outbox(1)
NServiceBus.Performance.TimeToBeReceived(1)
NServiceBus.MessageMutator(10)
NServiceBus.Faults(6)
NServiceBus.DeliveryConstraints(2)
NServiceBus.Timeout.Core(4)
NServiceBus.DelayedDelivery(3)
NServiceBus.DataBus(5)
NServiceBus.Container(2)
NServiceBus.Sagas(11)
NServiceBus.Unicast(13)
NServiceBus.Unicast.Routing(1)
NServiceBus.Unicast.Transport(10)
NServiceBus.Unicast.Queuing(2)
NServiceBus.Unicast.Behaviors(1)
NServiceBus.Unicast.Messages(4)
NServiceBus.Unicast.Subscriptions(2)
NServiceBus.Unicast.Subscriptions.MessageDrivenSubscriptions(3)
NServiceBus.Outbox(5)
NServiceBus.Pipeline(13)
NServiceBus.Pipeline.OutgoingPipeline(1)
NServiceBus.Pipeline.Contexts(5)
NServiceBus.Pipeline.Outgoing(1)
NServiceBus.OutgoingPipeline(6)
NServiceBus.Routing(17)
NServiceBus.Routing.StorageDrivenPublishing(1)
NServiceBus.Routing.MessageDrivenSubscriptions(2)
NServiceBus.Routing.Legacy(1)
NServiceBus.Config(14)
NServiceBus.Config.ConfigurationSource(3)
NServiceBus.Persistence(7)
NServiceBus.Persistence.Legacy(1)
NServiceBus.ConsistencyGuarantees(1)
NServiceBus.Extensibility(5)
NServiceBus.Features(34)
NServiceBus.Transports(32)
NServiceBus.Transports.Msmq(4)
NServiceBus.Transports.Msmq.Config(1)
NServiceBus.Audit(2)
``` 

I propose that we go with the following:

- [ ] `NServiceBus.Persistence`
- [ ] `NServiceBus.Transports`
- [ ] `NServiceBus.Container`
- [ ] `NServiceBus.Serializer`
- [x] `NServiceBus.Pipeline`
- [ ]  Document the general rule and also how it applies to the downstreams

**Comment by SimonCropp** [comment]
So your suggested allowed namespaces. R they "for people building x"? Ie only stuff that allows the advanced scenario of building a serializer goes into nsb.serializer?

**Comment by andreasohlund** [comment]
>So your suggested allowed namespaces. R they "for people building x"? Ie only stuff that allows the advanced scenario of building a serializer goes into nsb.serializer?

Correct

**Comment by andreasohlund** [comment]
Since we already have plural s'es on a few of them today I'd say we keep that to minimize the changes.

Ie:

`NServiceBus.Persistence`
`NServiceBus.Transports`
`NServiceBus.Containers`
`NServiceBus.Serializers`
`NServiceBus.Pipeline`

Thoughts?

**Comment by SimonCropp** [comment]
@andreasohlund i am ok with that

**Comment by andreasohlund** [comment]
Talked to @timbussmann and we propose that we go ahead with the `NServiceBus.Pipeline` classes right away? ( @Particular/nservicebus )

**Comment by andreasohlund** [comment]
NServiceBus.Pipeline is now handled in #3319

**Comment by danielmarbach** [comment]
@andreasohlund let's handle the remaining work as part of https://github.com/Particular/PlatformDevelopment/issues/734
