### ISSUE TITLE
Improving MessagingBestPractices/Validations exception messages

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3267]
When I was doing my first nservicebus application I did few things wrong which I was reminded by exception thrown from class:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs

I wonder would it make sense to actually extend the messages of Exceptions by adding this url:
http://docs.particular.net/nservicebus/messaging/messages-events-commands

My first reaction when I got: "Events can have multiple recipient so they should be published." was to actually google the solution and after few hops I came into the above site describing what I did wrong. By adding the above link into the exception message we are shortening the cycle of "looking what I did wrong".

**Comment by andreasohlund** [comment]
@SimonCropp you've been against doco links in code since we didn't have a good way do redirects in docs. Has that changes or does your stance still stand?

**Comment by SimonCropp** [comment]
still stands. no links in code

**Comment by andreasohlund** [comment]
@WojcikMike can the exception text be improved so that googling it will make our docs page the first hit?

**Comment by WojcikMike** [comment]
The messages itself are good, but the way how internet works is that people tend to copy and paste exceptions into stackoverflow and similar forums. So docs are not shown on the first page of google results. 

What if we add:
Consider reading NServiceBus documentation for Messages, Events and Commands 
At the end of each exception message. In that case sample message would be:

"Events can have multiple recipient so they should be published. Consider reading NServiceBus documentation for Messages, Events and Commands."

When I tested it then our site regarding that topic is in top 3 results. However I believe we depend on the name of that article, so if one wouldl change the arcticle header in the future we might not get any results from pointing to documentation.

**Comment by SimonCropp** [comment]
@WojcikMike 

>  the way how internet works is that people tend to copy and paste exceptions into stackoverflow and similar forums

I challenge that. i google for the text. every time. i cant remember the last time i put the text into the search on SO or some forum

**Comment by WojcikMike** [comment]
@SimonCropp I agree that people search using google/bing etc. but if I put message:
"Events can have multiple recipient so they should be published"
Into google i get SO, google groups etc. Becasue people put exceptions in the questions. Becasue of that. My suggestion above. So that if one is copy pasting exception message into google instead of forums he gets NSB doco.

**Comment by SimonCropp** [comment]
@WojcikMike you are optimizing at the wrong end.

If we try to game the exception message, to make it end up at our site, eventually SO and others will adjust to the new exception message and again we will drop off the ranking.

We would be better served improving our doco and hence our search ranking for the current text. 

For example in our doco we could say "when a message failed the specified the convention then the following exception (and message) will be received"

**Comment by WojcikMike** [comment]
@SimonCropp Fair point. Let me make a stab at it. 
My plan of attack is:
* Identify which pages relates to the discussed topic
* Modify the documentation pages to include information about exceptions while violating best practices
* Assuming that we will merge the changes, verify in some time if documentation pages are higher in google/bing search results

**Comment by SimonCropp** [comment]
> verify in some time if documentation pages are higher in google/bing search results

this is not actually our aim. we want people who google for those things to get to the correct answer in the first few links. so if the first few links are stackoverflow we can add another answer, or suggest edits to the exiting one, both of those with a link to the doco that clarrifies the situation

**Comment by WojcikMike** [comment]
From what I saw the article about [Messages, Events and Commands](http://docs.particular.net/nservicebus/messaging/messages-events-commands "Messages, Events and Commands") should be changed with the above issue. There is another page that title would suggest to speak about similar things: [Enforcement of best practices](http://docs.particular.net/nservicebus/messaging/best-practice-enforcement) but it talks more about how to disable the best practices and linking the 1st page. 

Btw. I feel that we should probably close this issue and open new one in [Docs Particular](https://github.com/Particular/docs.particular.net)

**Comment by WojcikMike** [comment]
Tha changes were introduced in the pull request. Messages are present in the documentation so I will close this issue.
