### ISSUE TITLE
Handle failing pre-hotfix 4.7.9, 5.0.8, 5.1.6, 5.2.10 Msmq messages with TTBR set correctly

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus#3268]
[comment](https://github.com/Particular/NServiceBus/issues/2886#issuecomment-166504227) from @mikeminutillo:

@janovesk @andreasohlund There is a subtle issue here with error forwarding.

An endpoint:
* Has Transactions turned on
* Receives a message with TTBR on
* Fails to process the message Then, it will try to forward to the error queue. The TTBR will be copied to the forwarded message and this fix will stop it from going out.

The same happens with audit forwarding but as that occurs for every message it will be immediately apparent. Errors are rarer.

**Comment by janovesk** [comment]
These messages would have had to be in-flight at deploy time or sent from a non-patched endpoint. A patched(4.7.9+, 5.0.8+, 5.1.6+ and 5.2.10+) endpoint would not have generated these messages in the first place.

**Comment by janovesk** [comment]
I think the best solution here is to strip TTBR before the message is moved to the error queue. 

This issue is about Msmq specifically, but I think it makes sense to remove TTBR from any message we move to the error queue. (Potentially saving the original TTBR in a header)

**Comment by andreasohlund** [comment]
@janovesk this is done right?

**Comment by janovesk** [comment]
Ping @andreasohlund

**Comment by janovesk** [comment]
We can close it and reopen if anybody is affected?

**Comment by andreasohlund** [comment]
Closed as wont fix
