### ISSUE TITLE
Receiving two times the same message in a handler

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3274]
I modified pub/sub example to verify certain behavior in NSB v6. Code can be found in here:
https://github.com/WojcikMike/PubSubSample

I have MyPublisher that publish EventMessage (implementetation of IMyEvent), for which I have a Handler in Subscriber2 ([EventMessageHandler](https://github.com/WojcikMike/PubSubSample/blob/master/Subscriber2/EventMessageHandler.cs "EventMessageHandler")). For simplification sake I will ignore Subscriber1.

Subscriber2 in handler EventMessageHandler publishes another Event that MyPublisher is subscribed to.

The issue is that with my current codebase Subscriber2/EventMessageHandler is called 2 times for the same event as well as MyPublisher/[EventMessageHandler](https://github.com/WojcikMike/PubSubSample/blob/master/MyPublisher/EventMessageHandler.cs) is called 2 times  for the same event. 

From my investigation it seems that issue is related to explicit Subscribing to an event + misuse of [MessageEndpointMappings](https://github.com/WojcikMike/PubSubSample/blob/master/MyPublisher/App.config) section in the app.config. 

I see 2 points of consideration with the above situation:
* The same sample run on NSB v 5 works correctly (run's handlers only 1 time)
* as my sample is bad can we do something to detect such situations and prevent them from happening (throw exception for example).

**Comment by weralabaj** [comment]
The part with Mappings seems like a bug to me, I don't see why it should result in sending the same message twice. @SzymonPobiega thoughts on that?
For the issue with subscribing either the user shouldn't be allowed to explicitly subscribe UNLESS they disabled autosubscribe (that means disabling the feature, right?), OR we should ignore multiple subscriptions. My guess is that first option would be easier than trying to figure out whether we have duplicated subscriptions, so API change? @andreasohlund not sure how that fits the original design, is that a big change?

**Comment by WojcikMike** [comment]
@weralabaj I agree with everything that you wrote. It seems that we have never thrown an error while mixing AutoSubscribe and manual subscriptions however I believe that we should. 

btw. the above behavior causes ServiceInsight to crash (see https://github.com/Particular/ServiceInsight/issues/545)

**Comment by SzymonPobiega** [comment]
I went through the the code and this is the "offending" line:

```
<UnicastBusConfig>
  <MessageEndpointMappings>
    <add Assembly="Shared" Endpoint="Samples.PubSub.Subscriber2"/>
  </MessageEndpointMappings>
</UnicastBusConfig>
```

The way new routing works is that when you define a route in `MessageEndpointMappings` it will be used when calling `Publish`. There is another route that is the result of calling `Subscribe` (and sending a subscribe message). These two routes should get deduplicated and the result should be only one route but for some reason there are not.

**Comment by SzymonPobiega** [comment]
I've raised a bug: https://github.com/Particular/NServiceBus/issues/3285

**Comment by weralabaj** [comment]
@SzymonPobiega regarding "either the user shouldn't be allowed to explicitly subscribe UNLESS they disabled autosubscribe (that means disabling the feature, right?), OR we should ignore multiple subscriptions" what do you think is the better option? is it a separate issue or part of the bug you raised?

**Comment by SzymonPobiega** [comment]
@weralabaj subscriptions are not a problem. The fact that there is both auto- and manual subscribe does not cause the problem. The subscription stores properly deduplicate. The problem is that the new routing combines MessageEndpointMappings and subscription store in wrong way. 

But philosophically speaking I see a point in making users decide upfront if they want auto or manual subscription because the current API is not really explicit about that.

**Comment by weralabaj** [comment]
@SzymonPobiega My point exactly, I expect we can do some magic under the hoods, but if possible I'd be in favour of telling users "you shouldn't mix both, pick one".

**Comment by WojcikMike** [comment]
I agree with @weralabaj on this one. As the goal should be to help users use NSB in the best possible way we should inform him of not doing so. However in previous versions mixing subscrition modes was allowed, so this is change in behavior.

**Comment by WojcikMike** [comment]
@SzymonPobiega do we plan to do anything in this area? I know that you did the fixed for dedup subscriptions. But are we planning to implement the check that @weralabaj is writing about?

**Comment by SzymonPobiega** [comment]
That would be a new feature in V6 :)

**Comment by danielmarbach** [comment]
@SzymonPobiega @WojcikMike @weralabaj Is this fixed? Can you raise a new issue for the check and close this one?

**Comment by WojcikMike** [comment]
I created an issue #3600 to capture the feature aspect of this request.
