### ISSUE TITLE
Enabling outbox in code but disabling it in config results in the endpoint to be started

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3275]
When enabling the outbox in code via `.EnableOutbox()` you get an exception with MSMQ or SQLServer transports:

> System.Exception: To use the Outbox feature with MSMQ or SQLServer transports you need to enable it in your config file. 

If you then add the setting but set its value to _false_ the endpoints starts.

```
<appSettings>
    <add key="NServiceBus/Outbox" value="false" />
</appSettings>
```

It is unclear if the outbox is now running with the outbox enabled or disabled.

If now the outbox is not activated then what transactional model is now being used as calling `.EnableOutbox()` results in disabling distributed transactions (transactionscope).
## Expected behavior

Expected behavior is that when configuration setting 'NServiceBus/Outbox' conflicts with `.EnableOutbox()` that the endpoint will not start and raises an exception during start.

**Comment by SimonCropp** [comment]
My preferce would be to drop the file based config option in v6. If people want to read form a file config (or db or env variable or command line param) it is trivial to do so and then pass that to the code config.

Also in my mind using the file config would be extremely unlikely. To use the outbox is an arcitechtual decision that is made and hard coded. I see little use case to switch it in production using a file change

**Comment by ramonsmits** [comment]
@SimonCropp This is about the requirement to have this setting in the appsettings. I've added the appsetting snippet to make it more clear.

**Comment by SimonCropp** [comment]
@ramonsmits I understand that. I don't know why anyone would ever want it as an app setting

**Comment by ramonsmits** [comment]
@SimonCropp Me neither :-) but it was done as an additional precaution for MSMQ and SQL

> The reason you need to do this is because we need to ensure that you have read all the documentation regarding this feature and know the limitations when running it under MSMQ or SQLServer transports.

I would be in favor to remove this double opt-in in V6 if it is still present.

What about the conflicting configuration that removes the error but results in unknown / undocumented execution for V5?

**Comment by andreasohlund** [comment]
Should we just remove the double opt-in?

**Comment by danielmarbach** [comment]
Yeah the double opt-in feels weird. Understand it from a historic perspective but nowadays we can get rid of it

**Comment by SimonCropp** [comment]
Double opt in is a poor approach, this was true at the time it was added just as it is true now

**Comment by timbussmann** [comment]
let's raise a new issue about removing double-opt in then?

**Comment by timbussmann** [comment]
issue raised here: https://github.com/Particular/NServiceBus/issues/4183

do we still want to address the current behavior since the removal should happen in a major version?

I think @ramonsmits  point is completely valid and something we can easily ship in a next minor.

**Comment by ramonsmits** [comment]
@timbussmann You mean for core V5 as well as V6?

**Comment by andreasohlund** [comment]
I'd say v6 only, not critical enough for a backport?

**Comment by ramonsmits** [comment]
@andreasohlund Not critical? I don't know if outbox is enabled as stated in the description. If the customer expects outbox is enabled but if it isn't then this can result in data corruption so that would qualify as critical.

**Comment by andreasohlund** [comment]
>If the customer expects outbox is enabled but if it isn't then this can result in data corruption so that would qualify as critical.

So you're saying that we would silently not run the outbox even if the user has `.EnableOutbox()` in code?

**Comment by ramonsmits** [comment]
> So you're saying that we would silently not run the outbox even if the user has .EnableOutbox() in code?

@andreasohlund I don't know :-) maybe just having the app setting "NServiceBus/Outbox" with *any* value or maybe even empty will enable it.

**Comment by timbussmann** [comment]
I don't see this as a bug tbh. V6 only imho.

**Comment by andreasohlund** [comment]
>I don't know :-) maybe just having the app setting "NServiceBus/Outbox" with any value or maybe even empty will enable it.

As long as we don't silently disables outbox even though users asked for it I'd say we're good and close this in favor of #4183 ?

**Comment by andreasohlund** [comment]
Replaced by #4183
