### ISSUE TITLE
Refactor Test Scenario Runner to Cleanup in Edge Cases

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus#3286]
If an Endpoint with `EndpointRunner.cs` has `Stop()` called, cleanup is successful.
If anything before the `try` block fails in `ScenarioRunner.PerformScenarios(...` cleanup is never called.

```
 static async Task PerformScenarios(RunDescriptor runDescriptor, IEnumerable<ActiveRunner> runners, Func<bool> done, Func<Exception, bool> allowedExceptions)
        {
            var cts = new CancellationTokenSource();
            var endpoints = runners.Select(r => r.Instance).ToList();

            await StartEndpoints(endpoints, allowedExceptions, cts).ConfigureAwait(false);
            runDescriptor.ScenarioContext.EndpointsStarted = true;
            await ExecuteWhens(endpoints, allowedExceptions, cts).ConfigureAwait(false);

            var startTime = DateTime.UtcNow;
            var maxTime = runDescriptor.TestExecutionTimeout;

            // ReSharper disable once LoopVariableIsNeverChangedInsideLoop
            try
            {
                while (!done() && !cts.Token.IsCancellationRequested)
                {
                    if (DateTime.UtcNow - startTime > maxTime)
                    {
                        throw new ScenarioException(GenerateTestTimedOutMessage(maxTime));
                    }

                    await Task.Delay(1).ConfigureAwait(false);
                }
            }
            finally
            {
                await StopEndpoints(endpoints).ConfigureAwait(false);
            }

            if (runDescriptor.ScenarioContext.FailedMessages.Any(kvp => endpoints.Single(e => e.Name() == kvp.Key).FailOnErrorMessage))
            {
                throw new MessagesFailedException(runDescriptor.ScenarioContext);
            }
        }
```

There should be a better pattern for specifying cleanup methods for tests and also wider coverage of where those cleanup methods are called. 

Tests failing before Endpoints have stopped has resulted in Raven databases leaking and filling both developer drives and also the build agent drives. 
https://github.com/Particular/NServiceBus.RavenDB/issues/116

This pull request is a bandaid until we have revisited this issue: https://github.com/Particular/NServiceBus/pull/3277

cc / @adamralph @andreasohlund

**Comment by johnsimons** [comment]
@colin-higgins in SC we use the teardown method to clean up raven db paths, see https://github.com/Particular/ServiceControl/blob/3068a4e0f2ff31bc8c713341959716d32261235c/src/ServiceControl.AcceptanceTests/AcceptanceTest.cs#L141-L151

Do you think that would work ?

**Comment by colin-higgins** [comment]
@johnsimons Yes, most likely

**Comment by andreasohlund** [comment]
@timbussmann is this still relevant given the cleanup you've done to the acpt tests?

**Comment by timbussmann** [comment]
this was fixed.
