### ISSUE TITLE
`TransportDefinition` phase to setup default settings

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3290]
The transport itself currently needs to use a Feature implementation to setup the default settings on the `SettingsHolder`. Because the features are created and started after the transport definition the information of these default values is not available during the setup of the transport. We would require a more explicit model where the `TransportDefinition` has two phases:

* First phase, let's call it `AfterUseTransport` gets access as early as possible to the `SettingsHolder` (not locked)
* Second phase, let's call it `AfterLockdown` gets access to the `ReadonlySettings` right after the settings have been locked

Since the transport definition becomes stateful per `SettingsHolder` with #3289, it can save the `ReadonlySettings` and use it to setup its dependencies where necessary. So this means the methods on `TransportDefinition` which get now access to `ReadonlySettings` no longer require it as a method parameter.

Something like

```
public abstract partial class TransportDefinition
{
    ...

    protected internal abstract AfterUseTransport(SettingsHolder settings);

    protected internal abstract AfterLockdown(ReadonlySettings settings);

    ...
}
```

@Particular/tf-async-transport please chime in because this has an impact on all transports

**Comment by tmasternak** [comment]
Does TransportDefinition need to know about those two phases? Maybe we can have "ApplyDefaultConfiguration" instead that would be called by core at a proper moment?

**Comment by yvesgoeleven** [comment]
@tmasternak yes, only transport knows what 'proper' moment is for it's own internal infrastructure

**Comment by tmasternak** [comment]
@yvesgoeleven but isn't the AfterUseTransport used only for setting the defaults? Is it supposed to do something more?

**Comment by yvesgoeleven** [comment]
@tmasternak yes, but nothing prevents user to hold on to settingsholder and try to make changes to it at later stage. with other method we want to indicate that that cannot be done anymore

**Comment by johnsimons** [comment]
@danielmarbach don't want to derail this issue but so you are also aware, in RabbitMQ transport impl we currently also have a need to add extra steps to main pipeline, see https://github.com/Particular/NServiceBus.RabbitMQ/blob/70ecf977ea7f58d6b94724fba7a656aec6c429ef/src/NServiceBus.RabbitMQ/Config/RabbitMQTransportCallbacks.cs.
@andreasohlund is trying to avoid this but at this stage we need it.

**Comment by johnsimons** [comment]
I am not conviced we should need to add defaults to the settings, IMO those defaults should be figured out at instanciating time, see example of this [here](https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L149-L166) and [here](https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L170-L178)

Would this work for you @yvesgoeleven ?

**Comment by yvesgoeleven** [comment]
@johnsimons you're hardcoding there, our defaults depend on the topology and cannot be hardcoded. So we need to add them to settingsholder

**Comment by johnsimons** [comment]
@yvesgoeleven but I assume the topology is set by the user right ? So that should already be selected ?

**Comment by johnsimons** [comment]
@yvesgoeleven [here is an example](https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L142-L168) how we do it in Rabbit, as u can see we read the topology set by the user before, and the user sets it via the `BusConfiguration`, would this model work for you ?

**Comment by yvesgoeleven** [comment]
@johnsimons No I don't think it's good enough, I see calls to GetOutboundRoutingPolicy, GetSubscriptionManager, GetSupportedTransactionMode, GetSupportedDeliveryConstraints before I can get the chance to read, or set the defaults for, configurations made by the user. All of those depend on choices that the user could (but not should) have made. Ideally I would get a point on the TransportDefinition in which I could set the defaults, after the user made his settings, but before it got locked down and before any other method on transport definition is called.

**Comment by yvesgoeleven** [comment]
How about changing the API like this?

```
public class SomeTransport : TransportDefinition
{
	// Called right before settings lockdown 
	SupportedByTransport Initialize(SettingsHolder settings);
	
	EndpointInstance BindToLocalEndpoint(EndpointInstance instance);
	string ToTransportAddress(LogicalAddress logicalAddress);	
}

public interface SupportedByTransport
{
	TransportReceivingConfigurationResult ReceiveInfrastructure { get; }
	TransportSendingConfigurationResult SendInfrastructure { get; }
	TransportSubscriptionConfigurationResult SubscriptionInfrastructure { get; }

	IEnumerable<Type> DeliveryConstraints { get; }
	TransportTransactionMode TransactionMode { get; }
	OutboundRoutingPolicy OutboundRoutingPolicy { get; }
	
	string ExampleConnectionStringForErrorMessage { get; }
}
```

**Comment by danielmarbach** [comment]
LIke it!

**Comment by tmasternak** [comment]
:+1:

**Comment by johnsimons** [comment]
I'll spkie this in a PR

**Comment by yvesgoeleven** [comment]
@johnsimons Implemented your spike in ASB, had to move the initialization slightly up as some of the features being activate use Support to make decissions, and also removed the exception thrown in message driven subscriptions as that feature is always on, it would always throw on transports with native pubsub support. Now there are about 20 ATT's failing because the ATT framework itself also uses Support property without initializing, but that should be covered by https://github.com/Particular/NServiceBus/issues/3292

**Comment by johnsimons** [comment]
@yvesgoeleven that PR is not finished at all.

**Comment by yvesgoeleven** [comment]
@johnsimons I know, just trying to help

**Comment by danielmarbach** [comment]
Improved as part of https://github.com/Particular/NServiceBus/commit/f25bc7e800bc468507350c8238a769ddc3aa83ef. Closing
