### ISSUE TITLE
mapper.ConfigureMapping does not validate if both properties are of same type

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3291]
Which blows up in NH persistence because NH constructs the criteria object based on the mapping. The core should make sure the mapping is valid (types match in message and saga).

The test that blows up (in NH, not in core) is `When_forgetting_to_set_a_corr_property`. In core it works because the in memory persistence does not care about types.

**Comment by andreasohlund** [comment]
:+1: lets fix this, marking as "up-for-grabs"

**Comment by andreasohlund** [comment]
@SzymonPobiega did we check this in v5 or has this been a big all along?

**Comment by SzymonPobiega** [comment]
@andreasohlund not sure. I've realized we're not doing this when I started running the new acceptance tests for the NH persisters.

**Comment by andreasohlund** [comment]
How strict should the rule be? do we need an exact match or should the type be convertible to the target type?

Does NH have special requirements?

**Comment by WilliamBZA** [comment]
The current test assumes convertible is enough.

We can implement a `IUserType` in NHibernate to support conversion between common types (e.g. `string` <==> `Guid`) but would have to check that the other persistences also allow for conversion between the same types.

**Comment by andreasohlund** [comment]
Perhaps the core should convert instead?

**Comment by WilliamBZA** [comment]
I'm sure we could write the code to do that. Is it the correct solution though?

Using a different Type to find a saga to the Type the actual saga uses should probably fall under an IFindSagas use case.  Writing our own conversion code around this could introduce precision/length bugs that we would have to test for (and fix the inevitable cases we miss).

**Comment by WilliamBZA** [comment]
In fact, I might go as far as to recommend that this check is done at compile time.  I.e. use generics to enforce the type safety between the types of `SagaPrpertyMagger` and `ToSagaExpression`

**Comment by WilliamBZA** [comment]
We have a test (`ValidateThatMappingOnSagaIdHasTypeGuidForMessageProps`) that checks that `int` isn't used where a `Guid` is expected. So expanding on this seems to indicate that the expected behavior is that the types should match.

I've spiked a quick change to make this a compile time check (which is how I found the test), so compile time is definitely possible - but is a breaking API change.

If we're happy with a compile time check, that could be in v6 and we could raise an exception on incorrect types for previous versions.

**Comment by andreasohlund** [comment]
Ok, forcing types to match seems resonable to me :+1: 

Can you elaborate on how to get the compile time checks?

**Comment by WilliamBZA** [comment]
The current `ConfigureMapping` method looks like this:
```C#
public ToSagaExpression<TSagaData, TMessage> ConfigureMapping<TMessage>(Expression<Func<TMessage, object>> messageProperty)
{
    Guard.AgainstNull(nameof(messageProperty), messageProperty);
    return new ToSagaExpression<TSagaData, TMessage>(sagaMessageFindingConfiguration, messageProperty);
}
```

with the `ToSagaExpression` looking like:
```C#
public void ToSaga(Expression<Func<TSagaData, object>> sagaEntityProperty)
{
    Guard.AgainstNull(nameof(sagaEntityProperty), sagaEntityProperty);
    sagaMessageFindingConfiguration.ConfigureMapping(sagaEntityProperty, messageProperty);
}
```

By introducing a third generic type argument and following that through to the `ToSagaExpression` we can enforce that the message property is the same type that the `ToSagaExpression` would look for.

Adding the type argument gives us:
```C#
public ToSagaExpression<TSagaData, TMessage, TSagaIdentifier> ConfigureMapping<TMessage, TSagaIdentifier>(Expression<Func<TMessage, TSagaIdentifier>> messageProperty)
{
    Guard.AgainstNull(nameof(messageProperty), messageProperty);
    return new ToSagaExpression<TSagaData, TMessage, TSagaIdentifier>(sagaMessageFindingConfiguration, messageProperty);
}

public void ToSaga(Expression<Func<TSagaData, TSagaIdentifier>> sagaEntityProperty)
{
    Guard.AgainstNull(nameof(sagaEntityProperty), sagaEntityProperty);
    sagaMessageFindingConfiguration.ConfigureMapping(sagaEntityProperty, messageProperty);
}
```

Which enforces that the `TSagaIdentifier`'s match at compile time.

The API for mapping changes a little as we have to specify the type argument (unless someone can work out how to do partial inferences for generic types?)

So where we would previously say:
```C#
protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MyEntity> mapper)
{
    mapper.ConfigureMapping<Message1>(m => m.InvalidProp)
        .ToSaga(s => s.InvalidProp);
}
```

We now say (note the new DateTime generic argument):
```C#
protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MyEntity> mapper)
{
    mapper.ConfigureMapping<Message1, DateTime>(m => m.InvalidProp)
        .ToSaga(s => s.InvalidProp);
}
```

If the types don't match, compiler throws an error.

**Comment by andreasohlund** [comment]
Interesting, I'd say that should be a different pull in order to not derail this pull. We need to talk about how the config api will change when we move to "single correlation sagas" https://github.com/Particular/PlatformDevelopment/issues/469 . Does that make sense?

**Comment by WilliamBZA** [comment]
Yep.

I'll go ahead and prepare a non-API-changing PR for this bug, and then chime in on the single correlation issue.

**Comment by mauroservienti** [comment]
should we consider this in scope for V6? if yes, could you please ad the expected `Tag: Core V6` label? cheers.
