### ISSUE TITLE
Move test selection responsibility from ATT Infrastructure to ATT implementations

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3292]
ATT infrastructure "categorizes" acceptance tests by using `Repeat(r => r.For<Category>())`. Here is an example

```
       public async Task Should_trigger_the_catch_all_handler_for_publishers_with_centralized_pubsub()
        {
            await Scenario.Define<Context>()
                ...
                .Repeat(r => r.For<AllTransportsWithCentralizedPubSubSupport>())
                ...
                .Run();
        }
```

We have the following categories right now

* AllDtcTransports
* AllNativeMultiQueueTransactionTransports
* AllTransportsWithCentralizedPubSubSupport
* AllTransportsWithMessageDrivenPubSub
* AllTransportsWithoutNativeDeferral

Internally the category statically initializes a new `TransportDefinition` which of course has not information about what is going to be configured later on when the acceptance test executes. 

Example: 

```
    public class AllTransportsWithCentralizedPubSubSupport : AllTransports
    {
        public AllTransportsWithCentralizedPubSubSupport()
        {
            AllTransportsFilter.Run(t => t.GetOutboundRoutingPolicy(new SettingsHolder()).Publishes == OutboundRoutingType.Unicast, Remove);
        }
    }
```

Because important information is lacking for the transport implementor it cannot answer the "questions" (i.ex. `GetOutboundRoutingPolicy`) asked by the category to determine whether the test should run or not.

It is Ok that tests are categorized by the core acceptance tests but answering those questions should be delegated to the acceptance test implementation. For example, we envision a possibility where the ATT infrastructure asks the `IConfigureTestEnvironment` (or another suitable implementation) which categories of tests should be run.

One of the concerns we need to address is:

What happens if we add another category like AllNonDtcTransports. We would need to make sure that those tests are not left out accidently by the implementors of the ATTs. One possible way to address this is to use an *Exclusion Model*  instead of an *Inclusion Model*.

@Particular/nservicebus @Particular/tf-async-core What is your thoughts on that? This has an implication on the downstreams.

**Comment by SeanFeldman** [comment]
It makes sense since `IConfigureTestEnvironment` implementation in the downstream projects has all the knowledge about given transport/scenario. Example: ASB that has two topologies where they don't support the same features. This way it will be easier to have ATTs configured per topology/case.

**Comment by johnsimons** [comment]
@danielmarbach not sure if you have considered this but please take into consideration that we use the AT framework to run the AT for the different transports in ServiceControl, we currently select the different transports on the implementations of `IEndpointSetupTemplate`, see https://github.com/Particular/ServiceControl/blob/3068a4e0f2ff31bc8c713341959716d32261235c/src/ServiceControl.AcceptanceTests/Contexts/DefaultServer.cs#L45
Not sure if this has any implications ?

**Comment by yvesgoeleven** [comment]
@johnsimons we all select the transport from env vars

**Comment by johnsimons** [comment]
@yvesgoeleven, SC doe not do that

**Comment by yvesgoeleven** [comment]
@johnsimons yes you do, https://github.com/Particular/ServiceControl/blob/3068a4e0f2ff31bc8c713341959716d32261235c/src/ServiceControl.AcceptanceTests/AcceptanceTest.cs#L81

**Comment by danielmarbach** [comment]
We improved the situation a lot with introducing https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/IConfigureSupportedScenariosForTestExecution.cs. Closing this one
