### ISSUE TITLE
Make NServiceBus responsible for managing transaction scope

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3299]
Current support packages for persistence seem to create their own TransactionScope (Suppress/RequiresNew).

Wouldn't it be better if NServiceBus would manage those to prevent that the support package would run in the ambient transaction?

**Comment by yvesgoeleven** [comment]
Quite the opposite imo, they probably start those scopes to get rid of the core's ambient transaction.

I assume you're talking v5 here, as in V6 core managed transaction scopes should be gone

**Comment by ramonsmits** [comment]
@yvesgoeleven That is exactly what I wanted to address. Isn't it the core its responsibility to make sure that the persistence logic does not take part in the transaction scope that core creates.

After a session with @andreasohlund and @MarcinHoppe it is clear that V6 brings improvements where the transaction scope will be managed by the (for now?) transport OR by the Unit of work which basically means a transaction scope that potentially includes the fetched messages for transports that support this.

In V6 we also have a outbox transaction object to allow the outbox to have a session that is worked on by @SzymonPobiega which makes it possible for the outbox to have a session which can create a update lock preventing deadlocks and makes it possible to synchronize work in environments that have a high amount of duplicates (as in, same message, multiple transport messages with identical ID).

We agreed to migrate this issue to making sure that persistence is not unnecesaarily creating transaction scopes by first scanning where transaction scopes are used (core + persistence) and than decide if that is the correct behavior.

**Comment by andreasohlund** [comment]
The core is no longer creating any scopes by default. Only the transports (sql+msmq) that supports DTC will do it if configured in the DTC txmode. It given this it seems wrong for the core to care about this?

If a persister can participate in DTC and decides that its needed (eg msmq substorage is designed in such  way that no transactions are needed at all) it can chose to participate. 

I'd say we close this one?

**Comment by ramonsmits** [comment]
Yes, it was my lack of knowledge on the internals.
