### ISSUE TITLE
New timeouts trigger querying the store two times

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3300]
Here's what happens in `ExpiredTimeoutsPoller` when a new timeout comes (assuming the store has already been queried at least once since the endpoint has started):
 * @ `00:00:05` the `nextRetrieval` is set to `00:01:05` (one minute after previous time when we queried (L127)
 * @ `00:00:15` the new timeout comes (to be executed after 20 seconds). `nextRetrieval` is updated to `00:00:35` and `timeoutPushed` is set to `true` (L44)
 * @ `00:00:35` the store is queried and a single timeout is returned. `NextTimeToQuery` is set (by store) to `00:10:35` (NHibernate persistence returns T+10min in case there is no more timeouts in the DB). Timeout is dispatched to be processed. The logic around L108 detects that `timeoutPushed == true` and `NextTimeToQuery` is larger than `nextRetrieval` (which still is `00:00:35`) and skips setting the `nextRetrieval`
 * @ `00:00:35.01` immediatelly after the previous run of the loop, the new run is triggered since `nextRetrieval` has not been modified. It queries the store and gets the same timeout again. It dispatches it to processing

The result is, in a non-scale-out scenario, for each timeout pushed, there will be two messages dispatched. One of them will find no timeout data and will cause an exception to be thrown to roll back the transaction. That exception causes the ATs to fail. 

The root cause it the broken logic which shortens the time before next query if a new timeout has been added.

**Comment by SzymonPobiega** [comment]
@timbussmann @Particular/nservicebus please take a look. It causes failure in NH but I believe the issue is deep in the core in the way `ExpiredTimeoutsPoller` work.

**Comment by timbussmann** [comment]
so does this part makes sense at all then?

```
else if (timeoutChunk.NextTimeToQuery < nextRetrieval)
{
    nextRetrieval = timeoutChunk.NextTimeToQuery;
}
```

**Comment by SzymonPobiega** [comment]
@timbussmann my feeling is it does not make sense but wanted to get more feedback as I might misread the code.

**Comment by andreasohlund** [comment]
Pretty sure we added it to reduce the polling intervall when messages with short expiry time come in?  cc @johnsimons

**Comment by SzymonPobiega** [comment]
@andreasohlund yeah, but the current code seems to reduce the interval *and* then query once more (triggering the exception).

**Comment by Scooletz** [comment]
When I run DotCoverage over non-acceptance tests, it showed no tests for `ExpiredTimeoutsPoller`. IMHO we have a suite with the scenarios like that one described by @SzymonPobiega ?

**Comment by timbussmann** [comment]
I think @Scooletz correctly noticed that although we query again immediately, we shouldn't receive the same timeout again, since we adjusted `startSlice` on the first query to be `00:10:35` which is later than the received timeout.

**Comment by Scooletz** [comment]
I've discussed some of my ideas with @timbussmann . 
It looks the polling for the next slice is a separate issue from the NHibernate persistence. If we changed the behavior of updating the 'nextRetrieval', that would result only in changing the schedule of polling for `TimeoutsChunk`. The `startSlice` storing the start of the next slice is updated to the value of of the oldest timeout. This means that the next query will be issued with the greatest timeout time:
```
foreach (var timeoutData in timeoutChunk.DueTimeouts)
{
    if (startSlice < timeoutData.DueTime)
    {
        startSlice = timeoutData.DueTime;
    }
// ...
```
This results in having two separate issues: on for the ExpiredTimeoutsPoller which I'm working on, the second for NHibernate issued here: Particular/NServiceBus.NHibernate#145

**Comment by Scooletz** [comment]
The behaviors all of the above have been covered by a new suite of tests for the poller here #3334. We can discuss this on their basis and change the behavior if needed. I'd be happy if one could take a look at them.

**Comment by Scooletz** [comment]
@SzymonPobiega Having this behavior documented in tests for the poller and a separate issue created for NHibernate, are we ok with closing this issue? If not, can we work on modifying the existing test towards a better behavior?

**Comment by mauroservienti** [comment]
should we consider this in scope for V6? if yes, could you please ad the expected `Tag: Core V6` label? cheers.

**Comment by SzymonPobiega** [comment]
@Scooletz so the main issue has been fixed and now it is the question if we should change the interface?

**Comment by Scooletz** [comment]
The change would require some work to propagate through the implementations and would require additional coverage in tests (I've done only tests to cover the current poller behavior). In my opinion it's not `S` in size, but again, as I mentioned above, it looks that they can be scenarios where we can skip a timeout until the next restart. The question is: is it realistically possible to get the error described above?
If you agree with my reasoning, then we have a potential bug in there.

**Comment by SzymonPobiega** [comment]
I've created a PR #3540 that attempts to address this. Closing this issue.
