### ISSUE TITLE
TransportDefinition.GetSubscriptionManager() should receive as parameter the main queue address

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3304]
In Rabbit, when we return the `IManageSubscriptions` impl, we need the main queue address to create it.
I wonder if this should be part of the contract ?
See https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L203

For now I am dodging it by keeping an instance field and populating it via the call to `ToTransportAddress(LogicalAddress logicalAddress)`, see https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L234

**Comment by johnsimons** [comment]
@Particular/tf-async-transport thoughts ?

**Comment by andreasohlund** [comment]
@danielmarbach @yvesgoeleven  in the new model we talked to the idea was to pass all relevant info to the new "settings are locked now" method right? This means that the address should already be there?

**Comment by danielmarbach** [comment]
Yes

**Comment by andreasohlund** [comment]
So given that @johnsimons needs `LogicalAddress` should he get that from the settings or do we pass it explicitly?

https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L221

**Comment by andreasohlund** [comment]
cc @SzymonPobiega

**Comment by yvesgoeleven** [comment]
Transport definition should get in all relevant information, not just queue name, but also f.e. publisher addresses or other routing info. It is usefull for many aspects of the definition, not just the subscription manager, the new model should adress this as well.

**Comment by yvesgoeleven** [comment]
Here's the related issue https://github.com/Particular/NServiceBus/issues/3290

**Comment by johnsimons** [comment]
BTW, I have raised this before, there are other code smells in the contract, as you can see from the impl of Rabbit, we need to call Initialize from both [`ConfigureForReceiving`](https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L51) and [`ConfigureForSending`](https://github.com/Particular/NServiceBus.RabbitMQ/blob/74ecbbf6e8d80c02297c3c31bd58c3bfe2f230ca/src/NServiceBus.RabbitMQ/Config/RabbitMqTransport.cs#L108) (because I have no idea what order those get called). @SeanFeldman showed me today that Azure impls are also doing similar things but instead are using a `Feature`.

 So I think we need some kind of Initialize method

**Comment by tmasternak** [comment]
@johnsimons and in general we cannot make any assumptions on that I guess. We can have 'SendOnly' endpoint which will have only one of those methods called.

**Comment by yvesgoeleven** [comment]
@johnsimons AfterLockdown can be used as initialization method as at that point the settings are fixed

**Comment by johnsimons** [comment]
> AfterLockdown can be used as initialization method as at that point the settings are fixed

@yvesgoeleven are you talking about #3290?

**Comment by yvesgoeleven** [comment]
@johnsimons yes

**Comment by SzymonPobiega** [comment]
In the current version the `settings.LocalAddress()` returns that shared queue to be used when subscribing so I consider this done. Do you agree @johnsimons ?

**Comment by johnsimons** [comment]
no idea, is the contract updated?

**Comment by andreasohlund** [comment]
I can confirm that this works since I used it in the devtranport


https://github.com/Particular/NServiceBus/pull/2950/files#diff-84dfb9e90332fd3003920ba1eacca45cR40

**Comment by SzymonPobiega** [comment]
The contract is not updated but the behavior of core has changed. Previously when you provided the instance ID/discriminator, the `LocalAddress` would point to the queue with the ID/discriminator which was wrong from pub/sub point of view. Now it points to the shared queue so no additional parameter is needed.

**Comment by bording** [comment]
I had actually moved to using `settings.EndpointName()` to get the shared queue name, which seemed to be working.

Since it looks like using `settings.LocalAddress()` is more correct, I'll update it to use that instead.

So yes, this should be considered done!

**Comment by SeanFeldman** [comment]
@andreasohlund it was closed prematurely. The change was not communicated to the downstream projects :disappointed: 

I caught this accidentally on a slack, rather than through a PR to a downstream project. Sent a [PR](https://github.com/Particular/PlatformDevelopment/pull/662/files) to ensure it's a part of the [nservicebus-maintainers.md](https://github.com/Particular/PlatformDevelopment/blob/8d273a3343e0f099a7e48be199bcbf12ebaec7e3/Maintainers/nservicebus-maintainers.md) and we don't forget about communication :wink:

**Comment by andreasohlund** [comment]
Good catch @SeanFeldman !

**Comment by SzymonPobiega** [comment]
@SeanFeldman terribly sorry I for that. When I was doing #3374 I forgot to include the ASB transport in the TODOs :-(

**Comment by SeanFeldman** [comment]
No worries @SzymonPobiega. The good thing is that w/o forgetting about ASB we'd never know that nservicebus-maintainers.md needs to be updated.

Are you going to open a PR or should I?

**Comment by SzymonPobiega** [comment]
@SeanFeldman I'll do it.

**Comment by SzymonPobiega** [comment]
@SeanFeldman I've reviewed the code in `StandardTopologySectionManager` and it seems like it correctly uses `EndpointName` as a basis for naming the subscription. The `LocalAddress` is the transport-specific name of the incoming queue that is deterministically generated from `EndpointName`.

**Comment by SeanFeldman** [comment]
@SzymonPobiega what about queue per instance scenario? In that case subscriptions should be created using `LocalAddress` rather than `EndpointName`.

**Comment by SzymonPobiega** [comment]
@SeanFeldman You're right. Or it should be endpoint instance name. Maybe it really is a good idea to pass something to `GetSubscriptionManager`... But I am not sure if I would prefer endpoint instance name or local transport address. The transport address is probably not ideal for naming purposes because it might contain some "junk".

**Comment by SeanFeldman** [comment]
Have to admit I'm somewhat confused by permutations of endpoint name/address that we have :) Would be nice to have a chart with an example.

@SzymonPobiega right now the scenario I've mentioned in https://github.com/Particular/NServiceBus/issues/3304#issuecomment-193413394 is not working at all.

**Comment by SzymonPobiega** [comment]
I think it all really dependes on the outcome of https://github.com/Particular/NServiceBus/issues/3495.
