### ISSUE TITLE
Move to code only configuration of max concurrency

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3311]
It appears that there are two ways to set max concurrency

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/StartableEndpoint.cs#L153

One is via `TransportConfig` and one is via `LimitMessageProcessingConcurrencyTo(...)`.

If you specify both then the endpoint fails to start up. This means that someone in Ops may try to change the concurrency settings via config and then run into problems. To resolve this they need a developer to come and change (or preferably remove) the hard-coded value. 

Why is the `LimitMessageProcessingConcurrencyTo()` method available? It does not appear to be documented. And why doesn't the config override it?

**Comment by andreasohlund** [comment]
>Why is the LimitMessageProcessingConcurrencyTo() method available? 

We want to move towards a code only config api

>This means that someone in Ops may try to change the concurrency settings via config and then run into problems. 

Should OPS really be allowed to this without consent from the developers?

Devs can always expose a config option if they write code that can safely be tuned by ops people?

Should we consider obsoleting the config api in favor of the code api?

**Comment by mikeminutillo** [comment]
> Should we consider obsoleting the config api in favor of the code api?

I think so. If we do that, it makes more sense to throw at runtime if you've set that value because I assume that you can't get a compile time error on a config setting.

**Comment by andreasohlund** [comment]
Correct, code api's ftw!

**Comment by mauroservienti** [comment]
Is this in scope for V6? it is linked to the milestone but the type is `discussion`.

**Comment by andreasohlund** [comment]
Changed it to refactoring and updated title

**Comment by timbussmann** [comment]
> Should we consider obsoleting the config api in favor of the code api?

I tend to disagree. Why shouldn't it be possible to configure different concurrency settings for different instances? While it may be rare use cases, I don't think it's entirely wrong.

Instead of throwing an exception, would it be more appropriate to use the config value over the code API in case both exist (and log a message)?

> Should OPS really be allowed to this without consent from the developers?

yes.

**Comment by andreasohlund** [comment]
>Why shouldn't it be possible to configure different concurrency settings for different instances?

That seem like a bit of an edge case?  

And it can easily be handled with `config.MaxConcurrency(Convert.ToInt(AppSettings["MaxConcurrency"]))` ?

**Comment by timbussmann** [comment]
> And it can easily be handled with config.MaxConcurrency(Convert.ToInt(AppSettings["MaxConcurrency"]))

That seems to be a valid solution. I was just saying that this is a perfectly valid scenario which should be easy to achieve for users. `Convert.ToInt(AppSettings["MaxConcurrency"])` seems about the same effort as defining configSections.

**Comment by andreasohlund** [comment]
>Convert.ToInt(AppSettings["MaxConcurrency"]) seems about the same effort as defining configSections.

:+1:  So are you ok to proceed with the code first api?

**Comment by timbussmann** [comment]
:+1: I'm good with it.

**Comment by timbussmann** [comment]
`TransportConfig` option has been obsoleted. I think we can close this one now.
