### ISSUE TITLE
Log a warning when decryption keys are configured

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3314]
When decryption keys are configured than it means that the customer is potentially still using encryption keys without key identifiers and vulnerable to data corruption. Logging a warning would make the customer aware of this.

**Comment by andreasohlund** [comment]
Is this one done?

Removing the core v6 label

**Comment by andreasohlund** [comment]
@ramonsmits can you reopen in https://github.com/Particular/NServiceBus.Encryption.MessageProperty if this is still relevant?
