### ISSUE TITLE
Remodel encryption service XML configuration for cleaner configuration

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3316]
The current XML configuration for the encryption service was extended in such a way that it is semver compatible but this configuration contract is not optimal

Drawbacks:
- KeyIdentifier attribute is not currently required
- Current Key is the collection item key which must be unique which requires a hack in the 'KeyIdentifier' attribute to support multiple key identifier to share the same key. Making the key identifier the item key/id resolves this issue
- There are no expired keys, they are in use but only used for decryption.
- Expired keys must be configured in the specific order that we should try using them to decrypt a message

Suggested configuration:

``` xml
<RijndaelEncryptionServiceConfig EncryptionKeyIdentifier="2015-10">
  <Keys>
    <add KeyIdentifier="2015-07" Key="12345" />
    <add KeyIdentifier="2016-01" Key="54321" />
  </Keys>
  <DecryptionKeys>
    <add Key="cdDbqRpQdRbTs3mhdZh9qCaDaxJXl+e6" />
  </DecryptionKeys>
</RijndaelEncryptionServiceConfig
```

This configuration would also match the current code API signature

``` c#
public static void RijndaelEncryptionService(
    this BusConfiguration config,
    string encryptionKeyIdentifier,
    IDictionary<string, byte[]> keys,
    IList<byte[]> decryptionKeys = null
    )
```

**Comment by MarcinHoppe** [comment]
Do we want to further ehance XML based config or remove it per #3424?

**Comment by andreasohlund** [comment]
Since we're moving away from xml config I'm removing the v6 core tag

**Comment by ramonsmits** [comment]
@andreasohlund This NEEDS configuration. Operations needs to update this information. If not on a schedule then because keys need to be revoked due to a security incident. We cannot drop configuration here.

**Comment by MarcinHoppe** [comment]
@ramonsmits @andreasohlund Alternative could be to do #3317 so that users can implement it themselves.

**Comment by timbussmann** [comment]
I think there could be several ways to fetch these keys without recompiling. Xml config seems to be only a single solution. With the code first api, it's completely up to the user to use the configuration option he'd like to use? (app config, dedicated config file, centralized storage, ...)? Like the other config options, we could still consider providing app.config file sections in a dedicated package?

**Comment by ramonsmits** [comment]
Lets focus on this issue here as this is about changing the current configuration structure to reflect the current code api. The existing XML configuration schema is *very* confusing for using key identifiers as that was a hack to keep the configuration schema semver compatible for the hotfix in existing released versions.

**Comment by andreasohlund** [comment]
@ramonsmits can you reopen in https://github.com/Particular/NServiceBus.Encryption.MessageProperty if this is still relevant?
