### ISSUE TITLE
Encryption service dynamic key identifier lookup and key retrieval

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3317]
The current encryption service configuration behaves statically. A change in encryption keys requires a restart of the endpoint. If a customer wants to use key rotation then it means they are required to restart the endpoint when the configuration is updated.

It is possible to retrieve the key data from a central location to create the configuration but not to update the key data.

Having a way for the customer to supply func's would allow the customer to rotate keys without restarting the endpoint.

Suggested API:

``` c#
public static void RijndaelEncryptionService(
    this BusConfiguration config,
    Func<string> getEncryptionKeyIdentier,
    Func<string,byte[]> getDecryptionKey,
    Func<IEnumerable<byte[]> decyprtionKeysLookup = nul
    )
```

This is based on the current static api:

``` c#
public static void RijndaelEncryptionService(
    this BusConfiguration config,
    string encryptionKeyIdentifier,
    IDictionary<string, byte[]> keys,
    IList<byte[]> decryptionKeys = null
    )
```

**Comment by ramonsmits** [comment]
@danielmarbach As a async guru I have a question. How would async fit the Func's? Would the following be correct?

```
public static void RijndaelEncryptionService(
    this BusConfiguration config,
    Func<Task<string>> getEncryptionKeyIdentier,
    Func<string,Task<byte[]>> getDecryptionKey,
    Func<Task<IEnumerable<byte[]>> decyprtionKeysLookup = nul
    )
```

**Comment by ramonsmits** [comment]
Thinking about makes me wonder if we don't rather need a interface for it:

```c#
interface IRijndaelKeyProvider
{
    Task<string> GetKeyIdentifier();
    Task<byte[]> GetKey(string keyIdentifier);
    Task<IEnumerable<byte[]>> GetDecryptionKeys();
}

public static void RijndaelEncryptionService(
    this BusConfiguration config,
    IRijndaelKeyProvider keyProvider
    )
```

@justabitofcode @WojcikMike Thoughts?

**Comment by ramonsmits** [comment]
@jdrat2000 As we discussed the key lookup in the past. What do you think?

**Comment by ramonsmits** [comment]
We could also do this via configuration:

XML:

Via KeyProvider attribute?

```xml
<RijndaelEncryptionServiceConfig EncryptionKeyIdentifier="2015-10" KeyProviderType="MyCustomKeyProvider, MyEnterpriseAssembly">
</RijndaelEncryptionServiceConfig>
```

App settings
```xml
<appSettings>
    <add key="NServiceBus/Encryption/Rijndael/KeyProviderType" value="MyCustomKeyProvider, MyEnterpriseAssembly" />
</appSettings>
```

**Comment by ramonsmits** [comment]
As an example: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serialization/ConfigureSerialization.cs

```c#
void RegisterRijndaelKeyProvider(FeatureConfigurationContext context, Type serializerType)
```

**Comment by danielmarbach** [comment]
Isn't encryption mostly CPU-bound? I think most algorithms are so I'd say
it doesn't need to be async

**Comment by MarcinHoppe** [comment]
@danielmarbach Encryption is CPU bound. But we're talking about key lookup here. This might be stored in a file, database, HSM, etc.

**Comment by danielmarbach** [comment]
Then it makes sense to use a task based API

**Comment by andreasohlund** [comment]
Talking to @danielmarbach and while we think the idea is valid we don't see it as a must have for v6.

Removing the label

**Comment by andreasohlund** [comment]
@ramonsmits can you reopen in https://github.com/Particular/NServiceBus.Encryption.MessageProperty if this is still relevant?
