### ISSUE TITLE
Store values in encryption value property that allows more data to be added in the future without breaking compatibility

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3320]
Current implementation writes data to the encrypted value property in a format that cannot be extended in the future. For example, we are not able to add signing data as this breaks backwards compatibility due to the older version not being able to parse this value correctly.

Example:

```
value=the lazy fox;sha1=<sha1-value>;ts=<timestamp>
```

**Comment by andreasohlund** [comment]
@ramonsmits can you reopen in https://github.com/Particular/NServiceBus.Encryption.MessageProperty if this is still relevant?
