### ISSUE TITLE
Add encrypted property value signing to prevent tampering and data corruption

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3321]
Current encryption properties only encrypt the value. By modifying the value decryption could still fail and this would go undetected. Adding signing would identify when this happens.

**Comment by MarcinHoppe** [comment]
This would probably be accomplished best by using AES in authenticated encryption mode and not rolling out separate integrity protection mechanism.

**Comment by SimonCropp** [comment]
@MarcinHoppe @ramonsmits  about when people want tamper protection but not encryption?

**Comment by MarcinHoppe** [comment]
@SimonCropp @ramonsmits A tongue-in-cheek answer would be: always. I think people tend to have a tacit assumption that data they send/receive are legit. They may ask themselves which pieces of data need to be confidential but they tend to take integrity and authenticity for granted.

Of course this point of view does not hold when your system is put into an adversarial setting, i.e. you acknowledge an active attacker eavesdropping and modifying messages on the bus.

**Comment by ramonsmits** [comment]
@SimonCropp You want signing when you want to make sure its from a verified/verifyable source.

In our case it migth be that we want to rely on the transport as the sender should be authenticated before it can even queue a message and not allow **everyone** queue priviledges. However, might the queue infrastructure been compromized then this would add an additional layer of protection.

**Comment by andreasohlund** [comment]
@ramonsmits can you reopen in https://github.com/Particular/NServiceBus.Encryption.MessageProperty if this is still relevant?
