### ISSUE TITLE
Remove unneeded IncomingMessage body allocations.

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus#3325]
In v6, `IncomingMessage` provides the message body as a Stream but still, does the copying to a byte array. The old Body property is used in multiple places. 
I've seen related issues: #2049 and #1272 but it looks like this hasn't been pushed till the `byte[]` removal. IMHO that could be a good place to lower some memory pressure for big messages. For cases like `IMutateIncomingTransportMessages` which uses some other context that's based on the body, we could do the lazy initialization or break the context contact and provide the body as a stream as well.

The stream could be based on a concept similar to the one provided by https://github.com/valeriob/EventStore-1/tree/master/src/EventStore/EventStore.BufferManagement

This could improve performance by lowering GC pressure, additionally, allowing hiding implementation by a well defined `Stream` interface.

**Comment by Scooletz** [comment]
@andreasohlund @danielmarbach  if you could write a few words about that idea, that'd be great!

**Comment by johnsimons** [comment]
:+1: to use streams all around

**Comment by danielmarbach** [comment]
@andreasohlund and I gave it a go months ago. It is not trivial. We ditched
it for v6 because we decided the impact is currently not high enough. Happy
to revive if we feel otherwise now. There should still be a branch available

**Comment by johnsimons** [comment]
@danielmarbach @andreasohlund what made it difficult ?

**Comment by danielmarbach** [comment]
Forwarding, Auditing and Reverting the body, as well as lazy applying
stream manipulation like mutators requires non trivial stream wrapping and
handling. But we didn't invest a lot of time.

**Comment by andreasohlund** [comment]
Agree with @danielmarbach , this is not trivial.

Here's the pull to get mutators working on streams https://github.com/Particular/NServiceBus/pull/2974

**Comment by Scooletz** [comment]
Thx @andreasohlund for sharing that PR. It looks that if we wanted to push that till the end, the changes would be even bigger, for instance, including for instance replacing of `OutgoingPhysicalMessageContext.Body' with stream as well (currently it's byte[]).

I can your point @danielmarbach and agree with @andreasohlund that it is non trivial, still seeing that many operations over `byte[]` looks like a potential big perf improvement, especially when taken into consideration proper buffer pool management.

**Comment by Scooletz** [comment]
Closed as duplicate of #1272
