### ISSUE TITLE
IPipelineTerminator should extend IStageConnector

### ISSUE THREAD

**Issue by ghola** [Particular/NServiceBus#3328]
Since these interfaces exist in order to allow third parties to create their own features (together with behaviors, connectors and terminators), there is a good chance that the developer creates an IPipelineTerminator implementation which does not also implement IStageConnector.

The current logic present in PipelineModelBuilder would fail to identify it as a terminator and it would treat it as a normal behavior/step which in turn would lead to a possibly incorrect ordering of steps within that stage.

If IPipelineTerminator would extend IStageConnector this issue would be fixed.

**Comment by johnsimons** [comment]
@danielmarbach thougths ?

**Comment by danielmarbach** [comment]
@johnsimons I think we should internalize IPipelineTerminator (like IStageConnector) and force users to inherit from PipelineTerminator. This aligns with the usage approach of Forks, Stages...

**Comment by danielmarbach** [comment]
Made `IPipelineTerminator` internal as part of #3332
