### ISSUE TITLE
Shouldn't behavior dependency cycles be detected instead of ignored?

### ISSUE THREAD

**Issue by ghola** [Particular/NServiceBus#3329]
Given the current implementation of the topological sort performed for behaviors/steps within a stage, dependency cycles are ignored. Shouldn't cycles be detected and an exception raised instead of ignoring them?

**Comment by mauroservienti** [comment]
@danielmarbach :point_up_2:

**Comment by danielmarbach** [comment]
Good point. I think they should. Probably not high prio for us now but I
see what we can do.
