### ISSUE TITLE
Should Outbox result in synchronized processing for the same ID?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3330]
Should usage or the outbox result in synchronized processing for messages with the same ID?

If the Outbox would synchronze based on message ID then the handlers are not required to perform locking and assume similar behavior as when its not possible to receive multiple physical messages sharing the same ID.

### Sender(s)

Send multiple message that share the same message ID. This can be achieve by setting the header either directly or somewhere in the pipeline for example a message mutator.

This can happen when the sender is running in a non transactional environment.

If there are (supported) transports that when scaled-out in a atleast-once scenario that might resuls in similar behavior.

### Receiver

Allows for concurrent processing either because it has multiple instances running or it has increased the maximum concurrency.

### No duplicate message ID's

The outbox behavior works fine to have exact-one processing when the transport never gives multiple message with the same ID. Its implementation is that if the same message is received sequentially that it will skip processing if there already is an outbox record and jumps to dispatching unless that is also already performed and then finishes. This works fine is either processing or dispatching fails.

This works fine because the message is locked when fetched. It will only be retried when the transport transaction rolls back. This results in sequential processing of the exact same physical message.

### Duplicate message ID's

When having multiple physical messages that share the same ID it now can happen that when two or more physical messages with the same message ID are processed concurrently that corresponding handlers are invoked in parallel.

When processing is fully transactional than either they will deadlock or the last writer looses and rollback.

If its not transactional the handles gets invoked with the same message and are not synchronized. Handlers could be having first/last reader/writer wins issues due to the parallel processing.

**Comment by andreasohlund** [comment]
>If the Outbox would synchronze based on message ID 

I think we would need a separate "conversation id" (perhaps our current `ConversationId` since duplicating message ids would lead to problems for lots of other things like SI and SC that expects the messageid to be unique?

**Comment by ramonsmits** [comment]
@andreasohlund Not sure what you are saying. The message ID is unique, the body is identical.

This currently can already happen if the outbox transmits the same message more than once. The behavior is similar.

But synchronizing on conversation id could be interesting especially in regards to saga congestion. 
Might we want to create a issue for this?

**Comment by andreasohlund** [comment]
I thought that you where proposing for the user to reuse the same message id on multiple messages. Re-reading this I can't see where I got that from :)

Given that the outbox currently dedupe on message id correctly (we talked about this a few weeks back) is there anything more to discuss here?

**Comment by ramonsmits** [comment]
@andreasohlund Reading this its more or less identical to #4086 but that one has a better title. I would say, close this one in favor of #4086. I'll review both and add pieces from this issue to #4086 is that makes sense.

I do like your idea of synchronization on the conversation ID. Its easier to do then synchronizing on the saga instance ID as that requires message inspection but it can also mean we are synchronizing on a too high level on some cases.

**Comment by andreasohlund** [comment]
Closed in favor of https://github.com/Particular/NServiceBus/issues/4086
