### ISSUE TITLE
Add a failing unit test for missing configure await

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3340]
Using cecil

**Comment by SimonCropp** [comment]
@distantcam should be possible?

**Comment by distantcam** [comment]
@simoncropp is it a blanket test for all async calls in a library? Yes that should be possible.

**Comment by distantcam** [comment]
Actually thinking about this it would better to do a Roslyn code analyser. There might already be one out there to do that.

**Comment by distantcam** [comment]
https://github.com/aelij/ConfigureAwaitChecker

**Comment by SimonCropp** [comment]
as I understand it there is pain associated with getting Roslyn analysers to fail the build?

**Comment by distantcam** [comment]
Nah, it's pretty easy actually.

I'd like to do this as part of a larger effort of using analyzers in our projects though. This would be a good first one to work on.

**Comment by WilliamBZA** [comment]
:+1: for roslyn analyzers. I'd love to help out with that when you start @distantcam

**Comment by WilliamBZA** [comment]
PR submitted https://github.com/Particular/Particular.CodeRules/pull/1/files

**Comment by WilliamBZA** [comment]
PR ready for review. So here's the steps I see involved in completing this issue:

- [x] Add configure await analyzer to CodeRules project
- [ ] Publish CodeRules project to NuGet (or MyGet?)
- [ ] Add CodeRules project to each individual system
- [ ] Make each system compile (assuming warnings treated as errors)

So following from this, the remaining work will start once this PR is fully reviewed, fixed and merged.

**Comment by WilliamBZA** [comment]
@Particular/nservicebus-maintainers can I get a review on this please?

**Comment by distantcam** [comment]
Now that #3434 was merged, I'll close this.

**Comment by SimonCropp** [comment]
@distantcam and every other repo?

**Comment by distantcam** [comment]
@SimonCropp This issue is for NSB. Is there a similar issue on the other repos?

**Comment by SimonCropp** [comment]
@distantcam  my understanding is that configureawaitfalse is our standard approach for all library based products

**Comment by distantcam** [comment]
The larger effort to add the code rules to other projects is being tracked here - https://github.com/Particular/PlatformDevelopment/issues/610
