### ISSUE TITLE
How to handle MessageDeserializerResolver for external serializers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3341]
so `MessageDeserializerResolver` is internal https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/MessageDeserializerResolver.cs

it is configured here https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serialization/ConfigureSerialization.cs#L37

but it is a hard requirement for `DeserializeLogicalMessagesConnector` https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs#L16

So how would this work for an external serializer

**Comment by SimonCropp** [comment]
@hmemcpy @SzymonPobiega do either of u have any ideas?

**Comment by danielmarbach** [comment]
Since we agreed that even stage connectors should be replaceable this type
probably needs to be public

**Comment by SzymonPobiega** [comment]
I have a local branch with serializer refactoring going. Should get to some results today or tomorrow.

**Comment by SzymonPobiega** [comment]
Actually I might need a micro-TF for that to handle it properly...

**Comment by SzymonPobiega** [comment]
@SimonCropp what is the scenario where you would like to replace the `DeserializeLogicalMessagesConnector` and still use the resolver? I thought the whole purpose of replacing connectors (which I don't like, as an idea) is to provide an fully custom implementation.

**Comment by mauroservienti** [comment]
should we consider this in scope for V6? if yes, could you please ad the expected `Tag: Core V6` label? cheers.

**Comment by andreasohlund** [comment]
Given that the [multi deserializer sample ](http://docs.particular.net/samples/pipeline/multi-serializer) now works can we close this one? 

Yes the user can't get access to what was configured in their replaced behavior but they kind of know that anyway since they are the ones configuring serializers on the endpoint config that anyway?

**Comment by timbussmann** [comment]
closing this since there weren't any comments since the last ping from @andreasohlund. Feel free to reopen.
