### ISSUE TITLE
MessageIntent is incorrectly set

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3344]
In NSB v6 sample it seems that message intent is always set to Send even if the event was published. Issue found in my extended PubSub sample:
https://github.com/WojcikMike/PubSubSample

File representing the issue:
[v6 results.txt](https://github.com/Particular/NServiceBus/files/96891/v6.results.txt)

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus/blob/937a77d4c2839006af2f370bb411c511cf6f44ba/src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs#L33

**Comment by danielmarbach** [comment]
Assigned myself since @WojcikMike is on vacation

**Comment by WojcikMike** [comment]
I organized some work for myself so that I have some nice, small bug when I am back from vacation to find that @danielmarbach stole it from me. Oh my dear friend beware your vacation :)

**Comment by danielmarbach** [comment]
@WojcikMike I'm truly sorry! I told you, never trust the Swiss people ;) Beer next time we meet?

**Comment by WojcikMike** [comment]
Sure :+1:
