### ISSUE TITLE
Move message property encryption to a separate package

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3345]
After speaking with several people about encryption the last few weeks it becomes clear than encryption should be split from the core.
### Benefits
- Out of bound releases
- Get a better idea of customer using encryption (track downloads?)
- Easier way to .NET Core support
- New features
- Opens a way to provide encryption capabilities slated towards different scenarios and deployment models:
  - Platform dependent (based on Windows CNG)
  - Platform independent (e.g. based on OpenSSL on Linux & Mac OS X)
  - Cloud-based (Azure Key Vault & AWS Cloud HSM)
  - Targeting different key management strategies (config file / database / Windows key storage facilities / TPM / HSM)

**Comment by johnsimons** [comment]
> After speaking with several people about encryption the last few weeks it becomes clear than encryption should be split from the core.

How about sagas, timeouts, mutators, UoW, SLR, ... ?
In other words, I think this is a nice to have but not something that needs done in the v6.0 timeline, also this can always be done in a subsquent minor release.

**Comment by MarcinHoppe** [comment]
Wouldn't this be a breaking change? 

Alternatively we could also have something very basic in the core for v6 and add more features on top of it by adding extension points in the next minor release and a brand new NuGet  (NServiceBus.Security?).

**Comment by andreasohlund** [comment]
I agree in general @johnsimons but since this is a must have for dotnetcore support we might consider it more important for the v6 timeframe?

**Comment by SimonCropp** [comment]
+1 to splitting it out

**Comment by MarcinHoppe** [comment]
Do we then have a consensus for keeping this issue for v6 release or we need to meet to discuss?

**Comment by andreasohlund** [comment]
Even though we all want this it I can wait until next major. Me and @danielmarbach don't see this as core v6 :(

Removing label

**Comment by andreasohlund** [comment]
Do we keep this open until v7 or close now as done?

**Comment by SimonCropp** [comment]
@andreasohlund obsoleteex will stop us from forgetting. So i think close this and raise a new placeholder issue to show up in the release notes. So assign the new issue to the v7 milestone and close it

**Comment by andreasohlund** [comment]
Why not just assign this to the v7 milestone and perhaps re-title this one?

**Comment by SimonCropp** [comment]
happy either way

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers thoughts on the process here, should I just assign to v7 and keep it open or do we close right away? (the code isn't technically gone yet)

**Comment by andreasohlund** [comment]
We should also raise a similar issue to track https://github.com/Particular/PlatformInstaller/issues/207#issuecomment-294729271

**Comment by timbussmann** [comment]
I think we should close immediately as the move already happened and v7 only removes the core API.

**Comment by andreasohlund** [comment]
Yea, since ObsoleteEx will force us to do it I'm good with closing.

I've updated the title to 

>Move message property encryption to a separate package

and assigned this to `7.0.0`
