### ISSUE TITLE
Kill the outbox, long live idempotency

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3347]
As part of V6 development we made the outbox a core concept (rather than a feature like in V5). The rationale behind it was that we can use the same infrastructure for batching.

Based on the conversation about the new transaction APIs (between @udidahan , @andreasohlund, myself and others) now think we should revert that decision. Here's what I think we should do:

 * Make outbox an opt-in feature again
 * Move outbox persistence out of general persistence definition (because we can't support it for environments without multi-operation transactions)

```
busConfig.UsePersistence<RavenDB>(); //subscription, timeouts
busConfig.UseOutbox<NHibernate>().UseSessionFactory(...); //because we want to ensure we use same session as user data access
```

 * Make SimpeSaga persistence ensure *at-least-once* semantics of processing messages (by storing the IDs of processed messages inside the saga state itself)
 * Add `IdempotentHandler<TMessage, TContext>` API that makes it explicit what we use:

```
public class MyHandler : IdempotentHandler<MyMessage, NHibernateContext>
{
   public Task Handle(MyMessage message, NHibernateContext ctx, IMessageHandlingContext ctx2)
   {
      ctx.Session().Store(new MyMoneyTransferOrder()); //in same transaction as outbox dedup
   }
}
```

 * Guide users to use sagas to implement logic that requires strong consistency, especially in environments such as Azure
 * Drop support for outbox-like behavior in normal `IHandleMessages<T>`
 * Start telling users that DTC is slowly becoming obsolete. In vNext we drop general support for DTC and make it available as a specific MSMQ transport API. In vNext++ we might drop it entirely.

This will allow us to decouple the outbox from saga stores and remove the `ISynchronizedStorage` concept from the public API.

@Particular/nservicebus thoughts?

**Comment by timbussmann** [comment]
> Based on the conversation about the new transaction APIs (between @udidahan , @andreasohlund, myself and others) now think we should revert that decision

can you give some insights about that conversation?

**Comment by DavidBoike** [comment]
> Move outbox persistence out of general persistence definition

Can you elaborate on this? Outbox *should* cooperate with the general persistence because it needs to cooperate in the same transaction as saga storage, although you mention sagas separately...

> Make saga persistence ensure at-least-once semantics of processing messages (by storing the IDs of processed messages inside the saga itself)

This is going to be really hard to pull off since it would require entirely new tables in any relational store, and would be very difficult given the limitations of Azure Table Storage.

@Particular/engineers I think wider discussion is necessary. Surprised how few people are in the nservicebus group.

**Comment by yvesgoeleven** [comment]
Besides datatype & format limitations, please mind that azure storage has no transaction support either.

**Comment by SzymonPobiega** [comment]
@DavidBoike the idea is that these simplified new Sagas will implement idempotence internally without the need for the outbox.

The simple sagas would not use tables but rather be serialized into a single blob, along with the <pick a number> of most recently processed message IDs to ensure desired level of idempotence guarantee.

**Comment by Scooletz** [comment]
I might be missing something but, as the sagas are eventually removed, is it valid to consider following scenario:
1. The saga `S` is started by a message `m`
2. `S` receives another message and is completed (deleted)
3. After a while `m` is redelivered. There's no saga `S`, and it is recreated again?

**Comment by SzymonPobiega** [comment]
That's true @Scooletz . These simple sagas would have to leave some "ghosts" after completing. Such a "ghost" would only contain the list of processed messages but the "user" part of the state would be removed.

**Comment by Scooletz** [comment]
Without a piece of infrastructure you can never delete these 'ghosts' as a message may be redelivered sometime in the future. You can use some heuristics like 'remove older than' but you have no guarantee. How do we want to prevent this always growing set of 'ghosts'?

**Comment by SzymonPobiega** [comment]
We use a heuristic in V5 outbox (limiting the history to 5 or 7 days by default). We can use the same one. We can also do some other "smart" things e.g. when a simple saga or an idempotent handler gets a message whose *sent at* time is lower than the *sent time* of any message in the history, it might mean that this message has been lost for a while and there are chances it has already been processed. In such case we can allow user to implement an optional virtual method e.g.

```
public virtual bool ResolvePotentialDuplicate(object message, object someContext);
```

**Comment by danielmarbach** [comment]
Another option would be to retain the fact that the saga existed but was
completed

**Comment by mauroservienti** [comment]
yeah. Soft deletes.

**Comment by SzymonPobiega** [comment]
That soft deletes apply even when there is no outbox in normal sagas. If a
message that can start a saga arrives right after completing an existing
saga, it will incorrectly start a new one.

**Comment by dvdstelt** [comment]
> the idea is that these simplified new Sagas will implement idempotence internally without the need for the outbox.

Internally, as  in NSB does it for the developer? Should I think of an 'inbox'? I don't see how outbox would help solving idempotence on incoming messages. I do get how it helps with pub/sub and not generating multiple id's for the same message.

**Comment by SzymonPobiega** [comment]
@dvdstelt yes, a deduplicating inbox built-into the saga instance.

**Comment by Scooletz** [comment]
@SzymonPobiega :+1:

**Comment by SzymonPobiega** [comment]
Updated the description with a plan regarding supporting classic outbox and DTC.

**Comment by danielmarbach** [comment]
@SzymonPobiega since we have https://github.com/Particular/PlatformDevelopment/issues/554 in platform development would it make sense to move this one into PD as well?

Btw. also removed yourself from being assigned to it

**Comment by timbussmann** [comment]
@SzymonPobiega would you be able to raise this issue in PDev (+ including the outcome of the discussions so far)?

**Comment by SzymonPobiega** [comment]
Yeah i will. I have it in my inbox do feel free to close this one. I need
to reword my proposal slightly.
