### ISSUE TITLE
TimeToBeReceived original value is lost when Outbox is enabled

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#3350]
## Who's affected

Anyone who's using `TimeToBeReceived` with their messages and enables the `Outbox` feature.

## Symptoms

A message with `TimeToBeReceived` will have it's value lost once the `Outbox` feature is enabled.

## Steps to reproduce

Use [Outbox - SQL Transport and NHibernate](http://docs.particular.net/samples/outbox/sqltransport-nhpersistence/) sample. Update `OrderAccepted` message to have `TTBR` attribute with some value (example: `[TimeToBeReceived("00:01:00")]`). Using SQL profiler, monitor inserted outbox records. The outbox record for `OrderAccepted` should have in it's delivery options value for TTBR, but the whole key/value pair is missing.

**Raised in**:
- GG: [link](https://groups.google.com/forum/#!msg/particularsoftware/QnaRmAaYNs4/GKCnbyY8DAAJ)
- Desk case [15739](https://nservicebus.desk.com/agent/case/15739)

@Particular/nservicebus this appears to be an issue how core serializes and stores `SendOptions`

**Comment by andreasohlund** [comment]
This seems to be a patch and backport worthy issue since it prevents TTBR from working

**Comment by RobertBernstein** [comment]
Thanks for looking into this, guys!

**Comment by andreasohlund** [comment]
Added failing test https://github.com/Particular/NServiceBus/pull/3351

**Comment by andreasohlund** [comment]
Thank you so much for verifying the proposed fix @RobertBernstein we will release to NuGet shortly (will be version 5.2.13)

**Comment by andreasohlund** [comment]
I've verified that v6 already handles this properly and does have acceptance tests to cover it

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_dispatching_transport_operations.cs#L15

so this is a v5 problem only. Backports to 5.1 and 5.0 will be raised as separate issues if needed

**Comment by andreasohlund** [comment]
@SeanFeldman hotfix branch prepared, can you update the sql+outbox sample and confirm as well?

**Comment by RobertBernstein** [comment]
You're welcome, @andreasohlund.

**Comment by andreasohlund** [comment]
Verified by @SeanFeldman , proceeding with the release

**Comment by MarcinHoppe** [comment]
@RobertBernstein We've just released the bug fix for this issue to NuGet as 5.2.13.

You can grab it here: https://www.nuget.org/packages/NServiceBus/5.2.13

**Comment by RobertBernstein** [comment]
I just installed 5.2.14 and TTBR is working as expected in my environment now.

Thanks!

Rob
