### ISSUE TITLE
Allow transports to lookup configured distribution strategies

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#3358]
Currently the user can configure distribution strategies, but this information is only used inside the core implementation on Unicast operations. This will be very confusing to the user when using a broker (probably considered a bug) as it won't respect these strategies. Please provide a way so that the transport can also take these strategies into account for it's routing at the physical level (if needed)

**Comment by SzymonPobiega** [comment]
@yvesgoeleven the distribution policy was meant to be applicable to unicast routing only. I'll create a PR to move make it explicit.

**Comment by SzymonPobiega** [comment]
@yvesgoeleven can we sync to figure out if we can't do it without passing this to the transport? The instances of `EndpointInstance` should contain information about the namespace the endpoint uses.

**Comment by yvesgoeleven** [comment]
@SzymonPobiega The transport will add no namespace info in EndpointInstance, for multiple reasons.
- Transport supports multiple namespaces
- Users asked to keep security sensitive connectionstring info out message headers, logs, etc... so we will no longer pass it around

In order to respect the distribution strategy, the transport would need that info somehow (lookup in settings prefered)

**Comment by andreasohlund** [comment]
@SzymonPobiega @yvesgoeleven is this one still a must have for v6?

**Comment by yvesgoeleven** [comment]
@andreasohlund @SzymonPobiega I assume no, as these would be moved into an msmq specific namespace there should be no more confusion

**Comment by andreasohlund** [comment]
Is this still relevant, can we close?

**Comment by yvesgoeleven** [comment]
@andreasohlund I don't think it is, closing
