### ISSUE TITLE
Auditing for Acceptance Tests

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus#3360]
We should add method level auditing for our acceptance testing framework.

This is especially useful for flaky tests which may be difficult to reproduce locally.

I propose generating an audit file per test detailing entry and exit of all methods. When the test succeeds, it will cleanup the file. If the test fails, we can use it for diagnostic purposes.

Possibilities: Writing to an audit file with test run id; spinning up an audit endpoint to receive messages with auditing information

@DavidBoike @kbaley @mauroservienti

**Comment by mauroservienti** [comment]
I like the idea, is it something that should be implemented in the ATT FX
or at the RavenDB level? ATT FX I'd say

On Tue, Jan 26, 2016 at 4:30 PM Colin Higgins <notifications@github.com>
wrote:

> We should add method level auditing for our acceptance testing framework.
>
> This is especially useful for flaky tests which may be difficult to
> reproduce locally.
>
> I propose generating an audit file per test detailing entry and exit of
> all methods. When the test succeeds, it will cleanup the file. If the test
> fails, we can use it for diagnostic purposes.
>
> @DavidBoike <https://github.com/DavidBoike> @kbaley
> <https://github.com/kbaley> @mauroservienti
> <https://github.com/mauroservienti>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3360>.
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by danielmarbach** [comment]
Are you talking about a Method interceptor for every method in NSB?

**Comment by mauroservienti** [comment]
Is this something we can do with Fody? @simoncropp
On Tue, 26 Jan 2016 at 17:14, Daniel Marbach <notifications@github.com>
wrote:

> Are you talking about a Method interceptor for every method in NSB?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3360#issuecomment-175096054>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by kbaley** [comment]
This feels like something that should be off by default and that we should be able to turn on at some level, maybe with a build parameter. Mostly because we will not need the output from this very often.

**Comment by MarcinHoppe** [comment]
Maybe we could look into IntelliTrace if it could be used here? Workflow could look like this:

 - Run tests as usual
 - Notice a flaky test
 - Move flaky test to some sort of quarantine state (*)
 - Run tests in quarantine with IntelliTrace or some other means of collecting audit trail

(*) to keep the build from going red intermittently.

**Comment by danielmarbach** [comment]
Although I cannot speak for Colin who apparently suffered a lot of pain
with RavenDB and the acceptance tests, I think we should not go for a
generic solution first. Let's determine a particular flaky repo, test out
an approach in a specific repo and from there on decide whether it is worth
pursuing or not.

**Comment by mauroservienti** [comment]
@MarcinHoppe `IntelliTrace` seems to be a very good fit. We could use the [stand alone](https://msdn.microsoft.com/en-us/library/hh398365(v=vs.140).aspx) when needed and download the trace locally to debug it.

**Comment by MarcinHoppe** [comment]
@mauroservienti  It has a downside, too: VS Enterprise only.

**Comment by mauroservienti** [comment]
to load the `IntelliTrace` output, correct? not to run the collector.

**Comment by MarcinHoppe** [comment]
I'm not sure how the collector is licensed. But anyways, you have to have VS Enterprise to work with it as a developer. Trace collection on a build server does not require separate license (I hope).

**Comment by danielmarbach** [comment]
I suggest we close this in favor of https://github.com/Particular/NServiceBus/issues/3362

**Comment by colin-higgins** [comment]
@danielmarbach I'd agree that #3362 should take priority but I think this would still have utility in the future.

**Comment by danielmarbach** [comment]
I think we are trying to find a solution for a problem which is imposed by using the wrong approach to test i.e. persistence. And this would add another layer of complexity on top of it. Like going to the grocery store with a tank to do your weekly shopping ;)

**Comment by danielmarbach** [comment]
This seems to be a big gun. @SzymonPobiega came up with a [simple solution which allows you to enable logging per ATT](https://github.com/Particular/NServiceBus/pull/3745). We favour that PR over this one. Closing
