### ISSUE TITLE
Introduce a component test suite for persisters

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3362]
This came up after talking to @SeanFeldman about the issues @dbelcham and @DavidBoike had with getting the acceptance test suite to run properly. After talking to @danielmarbach and @SimonCropp, we came up with the following proposal.
1. Stop using the acceptance test source package in the azure persister
2. Create a component test suite in the azure persister that will test the persister by invoking the various persistence api's. Call this project `NServiceBus.AzureStoragePersistence.ComponentTests`
3. Azure storage will create custom acceptance tests in `NServiceBus.AzureStoragePersistence.AcceptanceTests` to smoke tests a few end to end use cases that are relevant for the persister. This will hopefully cover most of the ground we lose by not running all of the core acceptance tests anymore

Optionally after we applied that to at least another persister:
1. Move the tests to a new `NServiceBus.PersistenceTests.csproj` in the core
2. Figure out a way to detect the persistence (it should run for inmemory persistence in the core)
3. Create a source only package
4. Apply to other persisters

Related to [How to better communicate design assumptions in core for downstreams?](https://github.com/Particular/PlatformDevelopment/issues/946).

**Comment by andreasohlund** [comment]
@SimonCropp @danielmarbach review please

**Comment by danielmarbach** [comment]
Made a few adjustements

**Comment by andreasohlund** [comment]
Renamed `IntegrationTests` => `ComponentTests`

**Comment by danielmarbach** [comment]
@Particular/azure-storage-persistence-maintainers @Particular/ravendb-persistence-maintainers @Particular/nhibernate-persistence-maintainers since you guys have been going through the pain of implementing a specific persister it might make sense to address this issue as part of the overall persistence maintainers budget but consulting with the @Particular/nservicebus-maintainers. Thoughts?

**Comment by DavidBoike** [comment]
Note that the first version of these was [built for Azure Storage Persistence](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/tree/develop/src/NServiceBus.Persistence.AzureStorage.ComponentTests).

Raised https://github.com/Particular/NServiceBus.RavenDB/issues/242 to cover integrating those tests within Raven, and to see what works and what doesn't, to help arrive at a final core set of tests that could be generalized.

**Comment by andreasohlund** [comment]
Given that we're heading in the direction of pushing timeouts and subscriptions into the transports should we consider creating a NServiceBus.SagaPersisterTests suite similar to the transport tests suite?

**Comment by MarcinHoppe** [comment]
@andreasohlund Given Particular/PlatformDevelopment#946, is there a reason to restrict ourselves to saga persistence only? 

/cc @timbussmann @WilliamBZA @weralabaj

**Comment by andreasohlund** [comment]
I was just thinking as a first start?

Outbox should also be added. But I'd say we hold off with the others until we see what happes to timeouts/subscriptions?

**Comment by weralabaj** [comment]
> is there a reason to restrict ourselves to saga persistence only?

I'm with Andreas here, seems this is just a first step.

**Comment by MarcinHoppe** [comment]
I'd say let's start with the biggest pain point. Is is sagas?

**Comment by danielmarbach** [comment]
Just a random idea: Could we define those tests outside the core repo so
that they have an individual lifecycle and it makes it really hard to
accidentally access internals of the core?

**Comment by andreasohlund** [comment]
Shouldn't they evolve together with the core since they represents the behavior the core expects of that seam?

**Comment by MarcinHoppe** [comment]
I am with @andreasohlund. To me these tests are a form of consumer-driven contract (NSB being the consumer of downstream persisters) and should evolve together with the consumer.

**Comment by danielmarbach** [comment]
From a @Particular/nservicebus-maintainers perspective we definitely want to do this. Judging based on the discussion here the persistence maintainers are also on board. Assigned the future milestone.

**Comment by SeanFeldman** [comment]
Service Fabric persistence TF has made an attempt to standardize on the component tests for persistence. Please see details under [PlatDev issue](https://github.com/Particular/PlatformDevelopment/issues/1123#issuecomment-286878971).

**Comment by andreasohlund** [comment]
We now have a standard test suite - https://github.com/Particular/NServiceBus/tree/master/src/NServiceBus.PersistenceTesting

Closing this
