### ISSUE TITLE
Encryption flaky test fails

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#3365]
Here's the log:

http://builds.particular.net/viewLog.html?buildId=142041&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

and here:

https://builds.particular.net/viewLog.html?buildId=155920&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

**Comment by andreasohlund** [comment]
Seems to be related to the encryption cc @ramonsmits @justabitofcode

**Comment by ramonsmits** [comment]
@MarcinHoppe @andreasohlund This should not be happening on develop anymore. I'll verify develop and report back.

**Comment by andreasohlund** [comment]
Not seen it in a while now

**Comment by danielmarbach** [comment]
We haven't seen it for a while. I'll close this issue, we can reopen any time.

**Comment by timbussmann** [comment]
just saw it today on the buildserver: https://builds.particular.net/viewLog.html?buildId=165633&buildTypeId=NServiceBus_2RunAcceptanceTestsForMsmq

reopening this.

**Comment by timbussmann** [comment]
@MarcinHoppe are you also interested in investigating this? Giving this maintainer budget.

**Comment by MarcinHoppe** [comment]
@timbussmann Sure, I'll give it a shot.

**Comment by andreasohlund** [comment]
:+1: this one has been haunting us for a while!

**Comment by MarcinHoppe** [comment]
Closing.

**Comment by andreasohlund** [comment]
This test failed again earlier today

https://builds.particular.net/viewLog.html?buildId=183967&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

:(
