### ISSUE TITLE
The new pipeline doesn't support IAdvancedSatellite features. 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3370]
When we had the `IAdvancedSatellite` interface in v5, we had the ability to specify a different receiving strategy, one even different from what the current endpoint uses. 

For example:
- An endpoint can use SqlTransport
- The endpoint could use an IAdvancedSatellite and specify a MSMQ receiving strategy using the 
  ```
  public Action<NServiceBus.Unicast.Transport.TransportReceiver> GetReceiverCustomization()
  ```

Find out what things are possible and what things are not. 

- [ ] GetReceiverCustomization - Define what's possible and what's not possible. 
  For example:  
  Here's how it's being used in ServiceControl:
https://github.com/Particular/ServiceControl/blob/89921c608f9153a28e81d61e84b9866d648624c2/src/ServiceControl/Operations/AuditQueueImport.cs#L120

  Here's how it was used in the old SqlBridge where a different transport receiving strategy can be used.
https://github.com/Particular/docs.particular.net/blob/master/samples/sql-bridge/Version_5/SqlBridge/MsmqReceiver.cs#L30

- [x] Possible to manage custom failures using an additional step
- [x] Ability to trigger a critical failure.

**Comment by SzymonPobiega** [comment]
@andreasohlund do you remember this? I am pretty sure that we dropped that feature accidetaly when working on `extend pipeline to transport` initiative that predates V6. We looked at how SC uses satellites and didn't actually spot that `Receiver` property of `TransportReceiver` was writable.

**Comment by andreasohlund** [comment]
Pretty sure it wasn't a concious decision to drop it.

What if there was a way to create a new "message pump" instead?

var msmqPump = settings.Get<MsmqTransportDefinition>().CreateMessagePump(address,...);

**Comment by indualagarsamy** [comment]
@andreasohlund - wouldn't settings.Get() give you the settings for the current endpoint, i.e. SqlTransport in this case? Whereas I want a MSMQ message pump. Sorry, not sure I follow.

**Comment by andreasohlund** [comment]
Damn, lost the formatting, I had `settings.Get<MSMQTransport>()`, but you are right, it would need to be:

`new MsmqTransport().GetMessagePump(...)` or something along those lines?

**Comment by SzymonPobiega** [comment]
Here's my multi transport spike as an alternative solution: https://github.com/Particular/NServiceBus/pull/3021

**Comment by johnsimons** [comment]
I have reviewed ServiceControl currently uses of `IAdvancedSatellite.GetReceiverCustomization()`, and it seems the new `context.AddSatellitePipeline` in `Features` will cater for all ServiceControl needs :)

**Comment by danielmarbach** [comment]
Then let's close this

**Comment by indualagarsamy** [comment]
@johnsimons Does ServiceControl try to swap transport receivers in the GetReceiverCustomization()?

**Comment by indualagarsamy** [comment]
What I am trying to highlight here is a missing feature of the interface. Whether ServiceControl uses that aspect or not is a different story? If ServiceControl doesn't use it, should we kill it? Might make sense. But I just want to make sure that we make a conscious decision before closing this issue.

**Comment by indualagarsamy** [comment]
Update: I am working on trying to convert over the IAdvancedSatellite. Based on that, I'll close this issue if I don't run into any issues.

**Comment by timbussmann** [comment]
@indualagarsamy there weren't any updates on this for a while, so can we close this issue?

**Comment by indualagarsamy** [comment]
@timbussmann - I haven't abandoned this effort yet. I've been working on related things that's possible to do with the IAdvancedSatellite, such as changing managing custom failures, worked through the bugs of not being able to change the satellite queue address. I'll post updates here.

**Comment by tmasternak** [comment]
@indualagarsamy Do you think it could be possible to break-down the work needed here so that we can get idea of the amount work needed? 

What is the definition of done here?

**Comment by indualagarsamy** [comment]
@tmasternak @andreasohlund - I've updated the issue description. 

The main thing is the questions on the `GetReceiverCustomization` ability of the `IAdvancedSatellite`.
I need to know what can be done and what can't be done. 
If we want to document that certain things aren't possible anymore, I am fine with that, in which case we can close the issue. I am working on a doco PR for the satellite changes.

**Comment by indualagarsamy** [comment]
Talking to @bording, it is currently not possible to switch transports in the `GetReceiverCustomization`
@andreasohlund - I am going to mark this as not possible in V6 in the Upgrade Guide. 
The other aspects of GetReceiverCustomization are possible, namely the ability to get hold of a CriticalError, or manage message failures, etc.
