### ISSUE TITLE
Unit test for in-memory Outbox persister occasionaly fails

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#3373]
The test in questions is: `InMemoryOutboxPersisterTests.Should_clear_dispatched_messages_after_given_expiry`.

Last observed random failure:

https://builds.particular.net/viewLog.html?buildId=142062&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

**Comment by danielmarbach** [comment]
@MarcinHoppe would you be willing to invest into this? It is still failing from time to time. We would like to give you a slot from our maintainer budget.

**Comment by MarcinHoppe** [comment]
@danielmarbach I'm on it.

**Comment by andreasohlund** [comment]
PR merged, closing
