### ISSUE TITLE
Transports for NServiceBus v6 retrospective

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3384]
Task force: @Particular/azure-maintainers @Particular/transport-maintainers 

Placeholder. Have a retrospective when V6 is done.

**Comment by SeanFeldman** [comment]
@mauroservienti would it be possible to add some context please? Thank you :)

**Comment by mauroservienti** [comment]
It is just to keep track of the fact that when done with V6 all the
transports folks should participate in the retrospective, nothing else.

On Fri, Jan 29, 2016, 18:17 Sean Feldman <notifications@github.com> wrote:

> @mauroservienti <https://github.com/mauroservienti> would it be possible
> to add some context please? Thank you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3384#issuecomment-176868973>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by timbussmann** [comment]
why do we have an issue about a retrospective? why not keep the original issue open until it's done?

**Comment by mauroservienti** [comment]
Same as https://github.com/Particular/NServiceBus/issues/3126#issuecomment-177890964 @timbussmann

**Comment by mauroservienti** [comment]
Seems that people is scared by long living issues, but an Epic is long living by design.

**Comment by timbussmann** [comment]
I think retrospective issues are just spamming our issue list. Retrospectives are part of the development process and the definition of done. I vote for closing retrospective issues and reopening the related issues. 

I agree with @mauroservienti: epics are long and large by default. If we're not happy with that, we need to scope epics differently / get rid of epics.

**Comment by tmasternak** [comment]
> I vote for closing retrospective issues and reopening the related issues <

@timbussmann what do you mean by `related issues`

**Comment by timbussmann** [comment]
@tmasternak https://github.com/Particular/NServiceBus/issues/3125

**Comment by tmasternak** [comment]
:+1:
