### ISSUE TITLE
Remove concept of Endpoint from CriticalError

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus#3387]
The concept of Endpoint pollutes CriticalError. 
CriticalError should be thread safe and utilize a callback rather than depending on Endpoint.
We could either make CriticalError instance per call, or take it out of the container entirely.

_Relevant pull request_: https://github.com/Particular/NServiceBus/pull/3368

cc / @bording @SeanFeldman @kbaley @timbussmann

**Comment by danielmarbach** [comment]
It should go out of the container and be an explicit parameter passed into the "plugins" where required. But be aware this can be more work than it looks like. I.e. Custom checks also use critical error.

**Comment by andreasohlund** [comment]
v6 only gives access to a [`ICriticalErrorContext`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/CriticalError/ICriticalErrorContext.cs) that doesn't contain the endpoint. Closing this as fixed in v6
