### ISSUE TITLE
TransportDefinition.Dispose() does not get called when an endpoint Stops

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#3392]
In the RabbitMQ transport, the `TransportDefinition` class, `RabbitMQTransport` implements IDisposable because we have broker connections we need to shut down when the endpoint stops.

For a regular endpoint, `Dispose()` is being called and everything appears to be working fine.

However, for a SendOnly endpoint, `Dispose()` is never called, and the process won't shut down correctly because the connection IO threads are still active.

It looks like **[this line](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Receiving.cs#L31)** is the reason that `Dispose()` is being called when an endpoint can also receive.

There is no equivalent call in the Sending feature, so the `TransportDefinition` is never registered in the container for a SendOnly endpoint.

What would be the best way to ensure that `Dispose()` always gets called?

**Comment by andreasohlund** [comment]
Is this a problem on develop or in the released versions as well?

**Comment by bording** [comment]
This is only a problem on develop. In the released versions, as long as you dispose your `ISendOnlyBus` \ `IBus` instance, the connections cleaned up properly also.

**Comment by bording** [comment]
@SzymonPobiega @Particular/nservicebus-maintainers 

Any thoughts on how to best go about improving this?

**Comment by danielmarbach** [comment]
How about we make the SettingsHolder managing the lifecycle of things
thrown in there? we could apply the following: by default a settings key is
not managed. When a value implements IDisposable it will be disposed by
core when the endpoint shuts down

**Comment by SzymonPobiega** [comment]
Seems reasonable @danielmarbach .

**Comment by bording** [comment]
Looking at `RunningEndpointInstance` I'm not seeing a way to directly get to the `SettingsHolder` instance.

I do see that the `SettingsHolder` is registered as a singleton **[here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L28)**.

Would it make sense to have `ReadOnlySettings` implement `IDisposable`, so that `SettingsHolder` can call `Dispose()` on anything in its dictionaries? That would mean that everything would be cleaned up when the builder is disposed in `RunningEndpointInstance.Stop()`.

**Comment by danielmarbach** [comment]
Dispose should be on the holder. Since ReadonlySettings is essentially the
endconsumer interface I would hesitate to make it disposable. I think pass
SettingsHolder to running instance (necessary evil)

**Comment by SzymonPobiega** [comment]
Running instance is the thing that holds all the references together so it is expected to find some evil there. :+1: on @danielmarbach 's proposal.

**Comment by bording** [comment]
> Dispose should be on the holder

I had the same thought later on, we don't want to be handing out a `Dispose()` to everyone.

However, I'm not sure that just putting it on `SettingsHolder` instead really solves the problem. Since `SettingsHolder` is public anyone who gets a `ReadOnlySettings` can cast it back to `SettingsHolder` and call `Dispose()`.

They can also start calling the set methods to add new settings, if `PreventChanges()` hasn't been called yet.

**Comment by bording** [comment]
I've gone ahead and opened a PR with the suggested approach, but it doesn't do anything to address the "casting `ReadOnlySettings` to `SettingsHolder`" issue I mentioned above. 

Is that something that is worth looking into mitigating?

**Comment by andreasohlund** [comment]
Smell like YAGNI to me?

**Comment by danielmarbach** [comment]
Yeah, don't bother

**Comment by bording** [comment]
Fair enough. I only brought it up as something to consider since the `ReadOnlySettings` / `SettingsHolder` split implies we want some control over when settings can be added.

**Comment by timbussmann** [comment]
Does every supported container dispose registered instances if the container didn't create them?

**Comment by danielmarbach** [comment]
@timbussmann see https://github.com/Particular/NServiceBus/pull/3433

**Comment by bording** [comment]
I've looked at the comments on my PR #3428 and I've looked at @danielmarbach's take on it at #3433.

Manually calling the method from inside of `RunningEndpointInstance.Stop()` makes things much more flexible. We aren't required to rely on `IDisposable` at all that way and we can make the method internal if we want. I definitely prefer the approach taken in #3433 now that I've seen it.

However, I've been looking at the changes to the `TransportDefinition` in #3308 and I'm not immediately sure how my original problem looks after I start making those changes, or if it will even still be a problem. Does the `TransportDefinition` still get added to the `SettingsHolder` when it's just an `Initialize()` method, or would that be replaced by the `TransportInfrastructure` instance that is returned instead?

I need to finish implementing a version of the RabbitMQ `TransportDefinition` that works with #3308 and get all the bits shuffled around correctly first, and then I think it might be a bit clearer.

**Comment by yvesgoeleven** [comment]
@bording transport infrastructure will get added to the settings, can we discuss this?

**Comment by danielmarbach** [comment]
@yvesgoeleven @bording also take into account https://github.com/Particular/NServiceBus/pull/3433 please

**Comment by bording** [comment]
Now that #3308 is merged, this is even more important to get resolved, because `Dispose` is now never called, even for regular endpoints. This means that the RabbitMQ transport currently cannot shut down properly.

**Comment by mauroservienti** [comment]
@bording please update the title highlighting that is not only for SendOnly endpoints.
Is this `in progress` or still at the triage stage? Should we move it back to backlog?

**Comment by bording** [comment]
This is resolved now via #3433.
