### ISSUE TITLE
Pass `TransportTransaction` to all persisters

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3395]
Currently `TransportTransaction` is passed by the core only to `ISynchronizedStorageAdapter` but it would be useful to have access to `TransportTransaction` also in `IPersistTimeouts`.

**Comment by andreasohlund** [comment]
I assume the same applies to `IPersistSubscriptions` so that the NH persister can reuse the sqlconnection?

**Comment by tmasternak** [comment]
That's correct.

**Comment by tmasternak** [comment]
@andreasohlund I think this should be 'core v6'.

/cc: @SzymonPobiega

**Comment by andreasohlund** [comment]
:+1:

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by johnsimons** [comment]
It sounds like this is a nice thing to have but it also seems is an addition that can be added in subsquent minor releases.
So are we really really sure we need to do this for v6.0 ?

**Comment by SzymonPobiega** [comment]
SQL Server transport + NH persistence needs it for the timeouts to work *exactly once*.

**Comment by tmasternak** [comment]
@SzymonPobiega Shouldn't we be able to make SqlServer + NH work correctly for Ms Sql regardless? For Oracle we also should be able to get _exactly once_ but will always escalate to distributed transaction. Right?

**Comment by SzymonPobiega** [comment]
you mean sticking SQL transaction in the context bag?

**Comment by tmasternak** [comment]
@SzymonPobiega What I was trying to say is that we could be able to make it run correctly for SqlServer + NHibernate without doing any changes to core or transport . In order to work correctly they need to run with `TransactionMode` set to `DistributedTransactions` so we could potentially change NServiceBus.NHibernate package to make sure we are not suppressing any existing scope in TimeoutPerister. ([this](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L30) is what we do now)

**Comment by SzymonPobiega** [comment]
But that would mean DTC escalation if we are not able to share the same connection.

**Comment by tmasternak** [comment]
But that only for Oracle. Right?

**Comment by SzymonPobiega** [comment]
hmmm... Ok, we need to sync on that. I am not sure how NH will get the instance of SqlConnection without changes to the core.

**Comment by SimonCropp** [comment]
Having tried to hack around this to build a custom persister it is significant pain. To the point of being so dificult that i would consider it a bug that we currently dont expose this explicitly. 

So i am +1 for fixing it in the v6 timeframe

**Comment by SzymonPobiega** [comment]
That feeling when @SimonCropp agrees with my :+1: :  :smile: . For everything else, there's MasterCard.

**Comment by andreasohlund** [comment]
@SzymonPobiega is this still needed for core v6 given #3485 ?

perhaps we can even close this one?

**Comment by SzymonPobiega** [comment]
@andreasohlund yes, not a blocker for V6.

**Comment by SzymonPobiega** [comment]
Closing for now.
