### ISSUE TITLE
Container registrations of message session and message context

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3417]
### Situation in v5

`IBus` is registered over our container abstraction in the user container. Automagically the user gets the right instance of `IBus` depending where his instances are resolved. Let me give you an example

```
class MyHandler : IHandleMessages<MyMessage>
{
   public MyHandler(MyDependency dependency) { }

   public IBus Bus { get; set; }

   public void Handle(MyMessage message)
   {
   
   }
}

class MyDependency
{
    public MyDependency(IBus bus)
}
```

In the above snippets the `IBus` implementation gets automatically resolved from the child container which will resolve the contextual bus. So everything resolved in a scope of a handler will get the contextual bus.

if `MyDependency` is resolved outside the scope of a handler. For example in an implemenation of an `IWantToRunWhenTheBusStartsAndStops` the `IBus` instance resolved will be the singleton non-contextual bus implementation.

## Situation in v6

* `IMessageSession`,`IEndpointInstance` and `IMessageHandlerContext` are not registered on the container

If a user blindly applies the following refactoring: `IBus` --> `IMessageSession` like

```
class MyDependency
{
    public MyDependency(IMessageSession session)
}
```

then they are in trouble. This code compiles and runs. Possibly for days, weeks until exceptions occur and a handle message is rollbacked. Why? Because the message session injected into `MyDependency` is no context of the incoming pipeline. So all operations done on `IMessageSession` will not rollback when the surrounding handler rolls back. The users would need to redesign their code to something like this:

```
class MyDependency
{
    public Task DoWork(IMessageHandlerContext context) {}
}
```

So this is a potential message loss scenario that we need to address with a proper design. Here are a few proposals

## Solution approach
1. Somehow check on the message session for the availability of `TransportReceiveContext` or `IncomingMessage` and throw a runtime exception if found.
1. Implement proper scoping of the message session outside the handler and therefore make it almost impossible to directly register the session on the container like describe in https://github.com/Particular/PlatformDevelopment/issues/591 

In my opinion we should try to approach https://github.com/Particular/PlatformDevelopment/issues/591 and come up with a design which doesn't require us to throw during runtime.

@Particular/nservicebus-maintainers @Particular/tf-handlercontext Thoughts?

**Comment by timbussmann** [comment]
should we also discuss that we currently do not automatically register `IMessageSession`/`IEndpointInstance` and users need to do register it manually with the container?

> Somehow check on the message session for the availability of TransportReceiveContext or IncomingMessage and throw a runtime exception if found.

I don't think this works. Sends from `IMessageSession` always use the `RootContext`. I don't see how you want that detection to work.

> Implement proper scoping of the message session outside the handler and therefore make it almost impossible to directly register the session on the container like describe in Particular/PlatformDevelopment#591

To be clear: I love the "session scoping" idea and completely support it. But I start to think this would be better suited for v7.

**Comment by danielmarbach** [comment]
I think we can't properly solve the problem above without session scoping.
With #3416 we can no longer rebind on child containers (which is not supported in all containers anyway) so we cannot inject a throwing implementation of `IMessageSession` into the child builder.

**Comment by danielmarbach** [comment]
> should we also discuss that we currently do not automatically register IMessageSession/IEndpointInstance and users need to do register it manually with the container?

updated

**Comment by danielmarbach** [comment]
Superseded ​by hthttps://github.com/Particular/PlatformDevelopment/issues/819
