### ISSUE TITLE
SerializationDefinition.Configure should be public

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus#3419]
Currently, the factory method provided by `SerializationDefinition` is `protected internal`
```
public abstract class SerializationDefinition
{
    protected internal abstract Func<IMessageMapper, IMessageSerializer> Configure(ReadOnlySettings settings);
}
```
This makes any component that was using serializer in the earlier versions of NServiceBus unable to create its own instance of the serializer. When working on ASQ Transport I discussed the new behavior with @danielmarbach & @andreasohlund. The solution based on creating its own serializer for ASQ, still aligned to the one in core, introduces a friction for users that are using serializers different from `Json`. To migrate from version 5 to 6 when using custom serialization one would register it for the core, then again, for ASQ with a custom method.

My proposal is to make this method public and allow creation of serializers for any component interested in that. That would not only limit the size of change in ASQ but be easier for users (configure serializer once).

**Proposed signature change**
```
public abstract class SerializationDefinition
{
   public abstract Func<IMessageMapper, IMessageSerializer> Configure(ReadOnlySettings settings);
}
```

Ping @Particular/nservicebus-maintainers 

/cc @yvesgoeleven @bording @SeanFeldman @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
2 points:
1. From the user perspective - don't force me to tell NSB twice what serialization to use.
2. Different release cycles of core and transport could potentially introduce breaking changes if serializers are different and not aligned.

**Comment by timbussmann** [comment]
> allow creation of serializers for any component interested in that

that sounds like we should make the IMessageSerializer accessible instead of just making this function public?

> The solution based on creating its own serializer for ASQ, still aligned to the one in core, introduces a friction for users that are using serializers different from Json.

Sorry, I can't follow. Can you explain that a bit more detailed?

**Comment by SzymonPobiega** [comment]
What is that serializer in ASQ used for? I mean, is there a value in us continuing to provide users with the choice? Allowing other components to access the serializers in core creates coupling where we don't want it (in the transport seam).

**Comment by bording** [comment]
> What is that serializer in ASQ used for? I mean, is there a value in us continuing to provide users with the choice?

We discussed this during today's transport sync meeting. The ASQ transport needs to serialize the message headers into the message, because ASQ doesn't have it's own concept of headers.

I asked the same question about why not just pick one and use it internally in the transport, and the answer regarding that would was that it would impact backwards compatibility with previous versions of the transport.

**Comment by SzymonPobiega** [comment]
Then how about:
 * In the ASQ implement JSON (based on DataContractSerializer) and XML (based on XmlSerializer)
 * Add *advanced* option to provide your own header serialization

We dropped usage of core serializers for SC plugins and we are also dropping it for SQL Transport (in all cases in favor of DataContractSerializer).

**Comment by Scooletz** [comment]
The previous version of ASQ created for Core v5 was overriding serialization to JSON and using core serializer for internal objects.

1. If one wasn't overriding serialization on your own, migration to v6 requires
 1. explicit registration of JSON as serializer for the core
 1. explicit registration of JSON for ASQ if we don't use @SzymonPobiega approach (that's how I implemented the first time)
1. If one was overriding serialization on your own, migration to v6 requires:
 1. explicit registration of the selected serializer for the core
 1. explicit registration of the selected serializer for ASQ

When handling core serializers with additional code in ASQ just to cover JSON & XML, the only difference is 1ii. In case of custom serialization we have to provide it twice.

@SzymonPobiega IMHO there are different dependencies. It's one thing to use serializer implementation from the core package, another is to use serializer configured for this endpoint instance.

**Comment by Scooletz** [comment]
@timbussmann I've updated the original description. I hope it's a bit clearer now.

**Comment by SzymonPobiega** [comment]
@Scooletz my point is the transports (or any other add-in for NSB) should not care what kind of serialization the core uses, if any. One of the things we've discussed recently is raw endpoints which offer you nothing more than raw "transport" message in which case there is no serializer registered. 

I think it is fair so say that with ASQ vNext you need to specify the serializer in the core (ASQ no longer overrides to JSON) and that you have to specify header serialization on ASQ transport level with two out-of-the-box options (XML and JSON).

**Comment by andreasohlund** [comment]
>The previous version of ASQ created for Core v5 was overriding serialization to JSON


Isn't the solution to make serializer selction in the core mandatory? 

This way we would just tell asq users (and azure users in general to select the external json.net serializer. Since they can't start without selecting one there is no way they wouldn't notice.

We could tell them to use the ilmerged version as well with a warning telling them that they have to use the external one in v7 of the core.



This is something we want to do anyway as a step to get json.net out of the core (cc @SimonCropp )

**Comment by Scooletz** [comment]
I'm closing this as the method is public now.
