### ISSUE TITLE
Remove custom ConfigurationSections

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3424]
It [was decided](https://github.com/Particular/Vision/issues/22) to remove custom configuration sections in favor of code first APIs. This is part of the vision to make the API more discoverable and easier to maintain since it allows us to properly obsolete/change configuration options.

These are the remaining ConfigurationSections.
- [ ] NServiceBus.Config.AuditConfig
- [x] [NServiceBus.Config.MasterNodeConfig](https://github.com/Particular/NServiceBus/issues/3429)
- [ ] NServiceBus.Config.RijndaelEncryptionServiceConfig
- [ ] NServiceBus.Config.Logging
- [ ] NServiceBus.Config.MsmqSubscriptionStorageConfig
- [ ] NServiceBus.Config.MessageForwardingInCaseOfFaultConfig
- [x] NServiceBus.Config.SecondLevelRetriesConfig
- [x] NServiceBus.Config.TransportConfig
- [ ] [NServiceBus.Config.UnicastBusConfig](https://github.com/Particular/NServiceBus/issues/1465)

**Comment by andreasohlund** [comment]
I can't find `ConfigurationSection` in the reference source for net core , http://dotnet.github.io/api/index.html, so I'd say this is a pre-requiste for supporting dotnet core

**Comment by dvdstelt** [comment]
What is the timeframe for this? I'm busy on AzureStorageQueues, cleaning up config there and making sure code overrules config. But there's an ASQ configsection, as well as the "NServiceBus/Transport" appsetting, which is running in NSB.Core.

For V6 customers are already in a ~~world of pain~~ steep upgrade path, I vote for keeping config sections for now and mark them obsolete. Providing guidance on configuration for the future and maybe provide additional NuGet packages to be backwards compatible. This was mentioned somewhere else, with the idea that if you want config from configsections, registry, database or anything else, users can write their own implementation. With our own implementation available in NuGet.

**Comment by timbussmann** [comment]
> What is the timeframe for this?

It's not required for the v6 release right now. With regards to the net core roadmap, it will probably be part of v7. I'd say it's not necessary for current tasks to refactor to the code first API, but at least we shouldn't introduce any new app settings options.

> For V6 customers are already in a world of pain steep upgrade path, I vote for keeping config sections for now and mark them obsolete.

It's not really possible to obsolete config sections properly (one of the reasons to get rid of them). Following the usual process of obsoleting public APIs, they are of course obsoleted and startup checks make sure you're no longer using them in the app config.

>  This was mentioned somewhere else, with the idea that if you want config from configsections, registry, database or anything else, users can write their own implementation. With our own implementation available in NuGet.

For most settings, it's pretty easy to continue reading from the app settings and we already updated some samples/docs to show how to do it. I'm not convinced on the value of NuGet packages provided by us, but we can discuss that in a different issue I think.

**Comment by dvdstelt** [comment]
> startup checks make sure you're no longer using them in the app config.

I'm not 100% sure what steps to take. Does this mean (option1) we still support configsections in V6, but logging it (incl. a warning) when the user is using them? And in V7 completely remove the configsection? Or (option 2) should we now remove configsection while making code-over-configuration?

The way I'm currently developing it is
- Default values in our own codebase
- Read from configsections and override defaults
- Override everything from custom-code via EndpointConfig (for example `configuration.UseTransport<AzureStorageQueueTransport>.ConnectionString("whatever").PeekInterval(10);`)

**Comment by timbussmann** [comment]
>  (option1) we still support configsections in V6, but logging it (incl. a warning) when the user is using them? And in V7 completely remove the configsection? 

yes we can still support config sections and we won't even log a warning for the supported sections. The warnings are basically removing the config section, because it's not possible to obsolete config sections properly.

Basically for existing configuration options: keep as is or introduce an additional code-first API optionally.
For new configuration options: Only introduce code-first APIs, don't add/enlarge existing config sections.

**Comment by andreasohlund** [comment]
Updated to POA with the current state of affairs. 6 sections still left in the core

**Comment by timbussmann** [comment]
this issue is replaced by https://github.com/Particular/PlatformDevelopment/issues/1153
