### ISSUE TITLE
Rename BusNotifications

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3425]
With the decision to remove "bus" from our APIs, we need to rename `BusNotifications` to something more appropriate.

Maybe we can already align the naming to the [proposed notifications vision](https://github.com/Particular/PlatformDevelopment/issues/605).

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers any objections to `Notifications`?

**Comment by danielmarbach** [comment]
Simple is good. Throwing in Endpoint wouldn't add much. So :+1:

**Comment by andreasohlund** [comment]
:+1: Since we have to go through doco I propose we sync this with #3175 to avoid repeating the work?

@SimonCropp thoughts?

**Comment by andreasohlund** [comment]
Let's go ahead with the rename. @timbussmann will you handle this?

**Comment by timbussmann** [comment]
@andreasohlund seems like this is an easy task which can be handled by everyone looking for work?

**Comment by andreasohlund** [comment]
:+1:

**Comment by andreasohlund** [comment]
@petersgiles can you wait with this one, https://github.com/Particular/NServiceBus/pull/3568 will kind of deal with this. Lets sync up?

**Comment by petersgiles** [comment]
@andreasohlund yep no problem

**Comment by timbussmann** [comment]
@andreasohlund since #3568 is merged and it's still `BusNotifications` I think @petersgiles could pick that up?

**Comment by andreasohlund** [comment]
Yea, lets go ahead

**Comment by timbussmann** [comment]
picking this up.
