### ISSUE TITLE
Remove obsolete distributor config in UnicastBusConfig

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3426]
These two properties on `UnicastBusConfig` are unused:
* `DistributorControlAddress`
* `DistributorDataAddress`

related to https://github.com/Particular/NServiceBus/issues/3424
related to https://github.com/Particular/NServiceBus/issues/1465

**Comment by SzymonPobiega** [comment]
@timbussmann they are not used. How do we handle obsoleting the config properties? `WARN` log entry on startup?

**Comment by timbussmann** [comment]
@SzymonPobiega obsoleting the property to make it unavailable from a code api perspective and throw an exception when the property has a value from the config file, e.g. something like here: https://github.com/Particular/NServiceBus/pull/3418

**Comment by janovesk** [comment]
Kill it with fire! :-)

**Comment by janovesk** [comment]
Backtracking on this. This is still in use. We intend to support V6 endpoints as workers for a V5 distributor to ease transition away from distributor.

**Comment by SzymonPobiega** [comment]
The V6 worker setup API looks currently like this: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/Legacy/ConfigureMSMQDistributor.cs
so it does not use the config section. There is, however, on open question if we should actually support fully distributor in V6.

**Comment by janovesk** [comment]
In that case I withdraw my objection :)

**Comment by andreasohlund** [comment]
> There is, however, on open question if we should actually support fully distributor in V6.

@SzymonPobiega has this been decided on?

@mat-mcloughlin do you plan to work on this?

**Comment by SzymonPobiega** [comment]
@andreasohlund not sure. @SimonCropp challenged me to prepare a draft of an announcement telling the customers that there will be no V6 version of distributor and that they need to switch to a stand-alone distributor scenario if they used distributor in-process. Here's the draft: https://github.com/Particular/NServiceBus/issues/3437

**Comment by mat-mcloughlin** [comment]
@andreasohlund My PR for obsoleting this properly was pulled in a while back now and I opened up a doco PR for it. I think @mikeminutillo is going to take it off my hands now as it required a bit more knowledge of the distributor than I have at the moment

Doco PR https://github.com/Particular/docs.particular.net/pull/1197

**Comment by danielmarbach** [comment]
@mat-mcloughlin Ok I assigned @mikeminutillo

**Comment by mikeminutillo** [comment]
I also have little context about the distributor and had just intended to update the doco PR. If someone can provide me with the context I need and review the changes I make, I'm happy to take a look. 

It sounds like obsoleting the two config properties has already been done and that we want to drive users towards the code-first configuration API. This is in line with the doco PR. Is that the end of this?

**Comment by timbussmann** [comment]
closing this one as code changes were merged and doc PR exists.
