### ISSUE TITLE
Obsolete the masternodeconfig since it's no longer used

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3429]
Since the master node concept is gone from the core in v6 I consider it a bug to keep the configuration laying around since that might lead users to believe it can still be used.

### Who's affected

Users using v6 endpoints as workers behind a v5 distributor

### Symptoms

The configured value would not be used and will cause confusion.

### Workaround

Call `configure.EnlistWithLegacyMSMQDistributor("MasterNode")`

**Comment by andreasohlund** [comment]
Also can we obsolete https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/UnicastBusConfig.cs#L92 as well?

**Comment by janovesk** [comment]
First case definitely. I don't know of any use case/supported scenario for an external timeout manager anymore either.

**Comment by andreasohlund** [comment]
Ok, lets handle that separately. We can move that to a separate code firt api for now if needed

**Comment by janovesk** [comment]
Backtracking on this. This is still in use. We intend to support V6 endpoints as workers for a V5 distributor to ease transition away from distributor.

**Comment by janovesk** [comment]
As per @SzymonPobiega's [comment](https://github.com/Particular/NServiceBus/issues/3426#issuecomment-181447612) I withdraw my objection :)

**Comment by andreasohlund** [comment]
Keeping the core v6 label on since this is a left over from the removal of the masternode concept. @SzymonPobiega @janovesk would any of you like to drive this?

**Comment by andreasohlund** [comment]
@WojcikMike sync with @timbussmann since he's added some code to warn about obsoleted config that you can add to

**Comment by WojcikMike** [comment]
Should we add this change to doco? Potentially to upgrade guide?

**Comment by gbiellem** [comment]
> Should we add this change to doco? Potentially to upgrade guide?

Default answer to whether something needs doco....  Public api = yes

**Comment by andreasohlund** [comment]
>Default answer to whether something needs doco.... Public api = yes

Agreed! In this case those changes should already have been documented by the task for that did the initial change (should have mentioned that in my comment)

**Comment by SimonCropp** [comment]
nope acording to this masternodeconfig is still alive and kicking
http://docs.particular.net/search?q=masternodeconfig

**Comment by WojcikMike** [comment]
ok I am on it. Will create PR in doco.

**Comment by andreasohlund** [comment]
Let me know when the PR is up so I can merge this

**Comment by WojcikMike** [comment]
@andreasohlund here PR create: https://github.com/Particular/docs.particular.net/pull/1326

**Comment by andreasohlund** [comment]
nice, ok to close this one?

**Comment by WojcikMike** [comment]
I will close it when the PR is merged, as otherwise this issue is not done by my standards.

**Comment by timbussmann** [comment]
@WojcikMike we consider the issue as done from the NSB repo when the WIP doc PR exists. I assigned you to the doc PR.

**Comment by SzymonPobiega** [comment]
@andreasohlund @timbussmann I think this was closed prematurely as @WojcikMike wanted it to be longer. I am not aware of the process that enforces closing issues as soon as there is a doco PR and I even remember a case where I was asked to not close my issue until the corresponding doco PR is actually merged.

**Comment by timbussmann** [comment]
@SzymonPobiega what's the value to keep this open?

> remember a case where I was asked to not close my issue until the corresponding doco PR is actually merged.

The [documented rules](https://github.com/Particular/PlatformDevelopment/blob/master/Maintainers/nservicebus-maintainers.md) state that a WIP doc PR suffices.

**Comment by SzymonPobiega** [comment]
I meant the value/no value call should be up to the assignee and the rules do not state *you must closed an issue as soon as there is a doco PR*. I use a filtered waffle board to keep track of my stuff and I usually prefer to close an issue if the doco PR is created but other people might use different work management approaches.

**Comment by timbussmann** [comment]
@SzymonPobiega there is no must. I closed this because I assumed this issue no longer contains any work left to do in the NServiceBus repository. It's our gromming process to try to close issues so we don't have to check them over and over again. Feel free to raise a discussion about this.
@WojcikMike In case there is still work left to do in the core, please feel free to reopen.
