### ISSUE TITLE
Support distributor and worker in same endpoint in V6

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3437]
Should we upgrade the distributor package to V6 in order to support setting up distributor and worker in a single endpoint in addition to the new scale-out option in V6?

Pros:
- We should give users time to move to the new API
- Distributor+worker in same endpoint was a common setup (anecdotal evidence) 

Cons:
- Cost of upgrading the distributor package to V6
- It is very easy to migrate to a setup where distributor is a separate endpoint
- It is relatively easy to migrate to new sender-side distribution

Customer communication draft:

In version 6 of NServiceBus we decided to improve our scale-out support, especially for the majority of our customers who use the MSMQ transport. The pre-6 scale-out solution we offered was the Distributor. The advantage of the Distributor was ability to execute handlers on bigger number of total threads by splitting the workload between several machines (workers). The disadvantage was the fact that due to the way load distribution worked, the maximum throughput of Distributor setup could not exceed [put a number] msg/s. 

In V6 we introduce the sender-side distribution mechanism where a sender (not the middle man -- the distributor) is responsible for balancing the load between the workers. This helps overcome the throughput limitations and allows close-to-linear scaling.

In order to allow smooth piecemeal upgrades we still support the Distributor in V6. Old (pre-6) endpoints can talk to the cluster via a distributor while new endpoints send messages directly. The only limitation is the need for the distributor to be hosted in a separate endpoint. This is because the distributor can work only with V5 of NServiceBus.

If you have a setup where one of the worker nodes also hosts the distributor, you need to spit them apart:
- Create a new empty V5 endpoint only for the purpose of running the distributor and add the distributor package. You can also download this sample showing how to do it [put a link here].
- Remove the distributor package from your worker codebase
- Migrate all distributor configuration to the newly added endpoint
- Remove the worker configuration from the worker codebase
- Upgrade the worker to V6
- Use the `EnlistWithLegacyMSMQDistributor` API to let NServiceBus know that to use the legacy distributor

One of the differences you will notice is that the V6 distributor-enabled endpoint needs a stable _endpoint id_ that is used to generate the queue name (instead of guid-like queues of V5 and earlier).

**Comment by SzymonPobiega** [comment]
@andreasohlund @DavidBoike @janovesk @SimonCropp thoughts?

**Comment by DavidBoike** [comment]
Ask champs?

**Comment by SimonCropp** [comment]
-1 to asking champs. no matter what the response, from asking a very samll subset of users a question, i dont see how it would effect the decision making process here

**Comment by SzymonPobiega** [comment]
@SimonCropp added a customer communication draft.

**Comment by SzymonPobiega** [comment]
@SimonCropp ping.

**Comment by andreasohlund** [comment]
@SzymonPobiega can you add the customer communication to the upgrade guide/open issue in docs and close this one?

**Comment by SzymonPobiega** [comment]
Let's wait till @SimonCropp and @DavidBoike agree that this is the way to go and no code needs to be written.

**Comment by SimonCropp** [comment]
@SzymonPobiega so what is the "Cost of upgrading the distributor package to V6"?

**Comment by SzymonPobiega** [comment]
@SimonCropp Hard to tell for sure but I am sure it would not be trivial.

**Comment by DavidBoike** [comment]
I think we owe it to ourselves to do the due diligence of at least estimating the effort. If not astronomical, we can provide a proper treatment of deprecated for one major, then unsupported in the next. Especially if we find that the new sender-side distribution pattern has some weaknesses that can't be quickly addressed.

**Comment by SimonCropp** [comment]
My main reason for pushing back on this is that we usually try to have a period of transition befor edeprecating something. Ie a period of time where it is full supported but we have communicated the fact that it will be removed some time in the future. The usual reason we dont do this is when it is simply not possible, which i dont think is the reasoning here. 

I am not stopping the train on this one. I just want to make sure the conversation has been had.

**Comment by petersgiles** [comment]
Based on this discussion @DavidBoike has invited me to upgrade the current NServiceBus.Distributor.Msmq to v6. 

Should I create a new issue for the work? Does who has been involved in this discussion anyone want to join the task-force with me?

**Comment by DavidBoike** [comment]
LOL, way to throw me under the bus! I think we need to have a better understanding of how much work would be involved to fully complete the upgrade and support the distributor package before we dismiss updating it out of hand. So call this a spike for now?

**Comment by petersgiles** [comment]
A spike it is :)

**Comment by petersgiles** [comment]
After upgrading nuget packages to v6 I get 206 errors mostly around obsoleting of the API

Here's a summary list (there's a lot more)

- 'Address' is obsolete: 
- 'BusConfiguration' is obsolete:
- 'ControlMessage' is obsolete: 
- 'ISendMessages' is obsolete: 
- 'IWantQueueCreated' is obsolete
- 'OutgoingContext' is obsolete: 
- 'SendOptions' is obsolete: 
- 'StartedMessageProcessingEventArgs' is obsolete: 
- 'Storage' is obsolete: 
- 'TransportDefinition.HasNativePubSubSupport' is obsolete: 
- 'TransportMessage' is obsolete:
- 'TransportReceiver' is obsolete:
- 'UnicastBus' is obsolete: 

So I guess the time to get this done would be based on someone who has limited knowledge of the changes going through and attempting to replicate the original functionality with the new api

**Comment by petersgiles** [comment]
`UnicastBus` had a property `Transport` that the distributor used 

Now that `UnicastBus` is obsolete how do I access the myriad functionality that it provided

//cc @Particular/nservicebus-maintainers

**Comment by petersgiles** [comment]
@DavidBoike having looked at this and the list of obsoleted things that this code depends on I would say that this is at least a medium sized task, maybe even a large one depending on the amount of documentation required. The task-force would definitely need someone on it who is familiar with where functionality went when it was obsoleted.

A side effect of looking at this is that we can improve the documentation around the api changes too.

I don't as this as core to the V6 deliverable. This could probably wait until after.

**Comment by mikeminutillo** [comment]
Now that the spike has been done, what is needed to close this issue? Just set up a meeting to make the final decision? Who needs to be at that meeting? If the decision is made not to update the distributor, is there an announcement to make? Any doco to be updated?

**Comment by SzymonPobiega** [comment]
Would a reference to [this sample](http://docs.particular.net/samples/scaleout/distributor-upgrade/) (in the upgrade guide) be enough?

**Comment by petersgiles** [comment]
@mikeminutillo +1

@SzymonPobiega I have no idea who makes all the calls on what is in or out or done or good enough. See @mikeminutillo 's comment

**Comment by DavidBoike** [comment]
@petersgiles is your spike pushed on a branch to peek at?

**Comment by andreasohlund** [comment]
@SzymonPobiega @DavidBoike @petersgiles can you guys make a call on this one?

**Comment by petersgiles** [comment]
The spike was simply an exercise in looking at much stuff would need to be fixed, there is no product.

The original question was "should we upgrade the distributor package?".

> Pros:
- We should give users time to move to the new API

Not sure how this prevents migration given there's another way to do it now

> - Distributor+worker in same endpoint was a common setup (anecdotal evidence)

Our opinion from what I can gather from our replacement solution is that this is a bad thing anyway

> Cons:
- Cost of upgrading the distributor package to V6

A lot of time for a few people as determined by the spike

> - It is very easy to migrate to a setup where distributor is a separate endpoint

Not sure what this is someone might need to explain it to me

> - It is relatively easy to migrate to new sender-side distribution

Yep and that's the solution we want people to go to

### Therefore I don't think we need this for v6.0

We shouldn't provide insurance policies by adding more and more extras. Lets do a few things really well rather than do a bunch of things poorly.

**Comment by DavidBoike** [comment]
I don't think we should *never* deliver it, but as long as we're reasonably confident we could deliver it after the release of V6 (without requiring any changes to the core) I would be more than happy to "wait and see."

Do we have a label for "Right After V6"?

**Comment by timbussmann** [comment]
> Do we have a label for "Right After V6"?

nope. But let's add the Feature tag then?

**Comment by DavidBoike** [comment]
Added Feature tag, removed V6 Launch, and backlogged for now.

@SzymonPobiega if you think this needs to be done to ensure it is workable with V6 Core, feel free to override me.

**Comment by SzymonPobiega** [comment]
@DavidBoike I fully agree this can wait.

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers  How about closing it and re-opening if we discover it is necessary?

**Comment by andreasohlund** [comment]
@SzymonPobiega agreed, lets close for now
