### ISSUE TITLE
Ensuring subscriber is actually subscribed

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3439]
Ok, extending this #3398 idea, should we (probably after V6) have an API that ensures a subscription exists **before** an endpoint is started? Something like:

```
IStartableEndpoint e = Endpoint.Intialize(busConifg);
e.EnsureSubscribed<MyEvent>();
IRunningEndpoint e2 = await e.Start();
```

On broker transports subscriptions are configured on subscriber side so subscriber knows when it is "connected" but on transports without native pubsub (MSMQ, ASQ, SQL) there is no feedback if `subscribe` request has been processed so we are never sure if the "connection" to publisher has been properly established.

**Comment by timbussmann** [comment]
> we are never sure if the "connection" to publisher has been properly established.

In terms of eventual consistency, that seems to be incorrect? If you send a subscribe message, you can/should be sure that you will subscribe at some point.

As far as I understand you correctly, the proposed mechanism is for non-broker transports? How would they be able to ensure that they are subscribed? And how would a first start of this application look like?

**Comment by andreasohlund** [comment]
Not sure I agree since that API would lead users to bad habits. If its important that they are subscribed on startup we should guide them to use out of band tooling to "prime" the subscription storages /setup broker bindings/etc. This could be something we output similar to @SimonCropp 's idea on how do deal with installing queues, creating tables etc going forwards.

This way users can:

1. subscribe the endpoint at midnight tomorrow
2. Take the DB backup up until that point and migrate the data needed to the business DB that the endpoint uses
3. Once the data is ready and verified, start the endpoint up and catch up 

This is the practice we want the users to follow since business data is always (IMO) relevant to sync when you have those requirements.


If you don't need to sync business data I have a hunch that they are fine with being eventually consistent anyway? (since there might have been a publish just a few milliseconds before they started up anyway)


What do you all think?

**Comment by SzymonPobiega** [comment]
@timbussmann @andreasohlund I don't think eventual consistency is good enough. Given that the subscription messages leave very little trace when they fail it is hard to detect a failure of subscribe (for whatever reason). The subscribing endpoint has no way to check if it's subscribe request has succeeded and can continue to operate assuming it is subscribed. I am thinking about making the `Subscribe` a request-response operation.

An alternative would be removing the message-driven pub sub and replacing it (gradually) with native implementations using shared subscription storages.

**Comment by danielmarbach** [comment]
I'm all for removing Message-Driven pub sub. It provides little value and the autonomy we get through message driven pub-sub is a fallacy.

**Comment by andreasohlund** [comment]
>I am thinking about making the Subscribe a request-response operation.

That highlights my point. Any app that absolutely requires to be subscribed at a given point needs to make sure that the subscription is present "out of band" , usually by adding it straight to the "storage".

If you don't care I see no value in this over logging, errorq etc?

Also if we move to a model where pubsub is handled by each transport then this becomes a implementation detail of each transport?

`.Subscribe` returns when:

* Rabbit: bindings are registered 
* NativeSqlServer: Entry is inserted into table
* DevTransport: File is written to `events\{eventtyp}\{endpointname}.subscription}`
* ASB: Topic is setup
* ASQ: Row is insered into table storage
* MSMQ: Sub message sent (like today) or "subscription ack" is returned

From a public api perspective its still a `.Subscribe` ?

**Comment by SzymonPobiega** [comment]
I guess this issue confirms that we should move pubsub to the transports.

My point was slightly different. If you use `session.Send()` the message will eventually arrive at the destination because it has been sent. If you use `session.Publish()` the message might not be sent or might not be routed to any queue and dropped by the broker which is a message loss case from system point of view. It is not enough to tell people who care to prime the topics/subscription storages because the procedure might fail. 

When looking at the publisher, it does not care how many subscribers there are and that is just fine. But when looking at the whole system, we know that there are three subscribers and, in order for the system to work correctly, these subscribers need to be subscribed **at all times**. 

Here's what I think we should do:
 * allow people to define their pub/sub architecture in the series of assertions like `Endpoint X is subscribed to message A` or `Endpoint X may send commands B to endpoint Y`
 * compile these assertions
 * be able to run these assertions at build time i.e. fail the build if the endpoint does not comply to them
 * be able to run these assertions at endpoint startup time. Each sender/publisher would send/publish a tracer message and each receiver/subscriber would reply with status
 * endpoint would refuse to start if the assertions are not valid i.e. one of the asserted routes is not configured/invalid

**Comment by andreasohlund** [comment]
@SzymonPobiega ok to close this?
