### ISSUE TITLE
Persistent subscriptions

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3440]
Extending on #3439 even further, should we add persistent subscriptions? A persistent subscription would make sure that the subscriber does not miss any single event.

A persistent subscription would only be allowed for an event that is published durably. Some transports might support such durable publications e.g.

```
var transport = busConfig.UseTransport<SQLServer>();
transport.UseDurablePublicationFor<MyEvent>();
```

Durable subscriptions would behave similarly to EventStore's projections. They would be read-only in terms of code/logic once deployed. When a new version is deployed, it would read the stream of events (building up its state) until it gets to the current point and in that moment the old subscription would be dropped and the new would take over the processing.

The usage scenarios of such subscriptions would be all kinds of view generation based on event streams. The focus here would be, as usual in NSB, on correctness and ease of use rather than throughput.

**Comment by timbussmann** [comment]
From your description, is *persistent subscriptions* correct? Wouldn't a the described use case be something a user would code themselves e.g. consume events and put them in an event store?

**Comment by timbussmann** [comment]
looking into this as @SzymonPobiega is assigned to this issue, I'm not really sure this something for the future backlog. There seems to be a larger story about this which seems to be something for specific transports or the platform development process. Should we close this @Particular/nservicebus-maintainers @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@timbussmann I'd close it for now.
