### ISSUE TITLE
File based persistence for development time

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3445]
Similar to #2950 we need storage that is durable and optimized for development use.

This would enable a good "F5" experience while still providing durable storage that is close enough to production storages.

This allows us to:
- Have durable storage in all samples without having to select NH or Raven
- Get rid of the in memory storage in the core which is IMO just a liability since using it will cause message loss
- It's like cassini was to IIS, allows you to get going without having to install infrastructure
- Allows new starters to get familiar with sagas etc before making a choice on what storage infra to use
- We can propagate the knowledge that a dev persistence is in use to allow dowstreams to adjust accordingly
- When doing support cases we can send code samples that is storage agnostic without knowing what persistence they are on
- \* Gives us a persistence in the core that can drive the acceptance tests better since we can run tests that needs durability

Old spike here - #2204

**Comment by timbussmann** [comment]
Are there other reasons than sagas that we need non-volatile persistence mechanism during development? Timeouts seem to be negligible, not sure about subscriptions though.

From the spikes, did you encounter any blockers?

>  Gives us a persistence in the core that can drive the acceptance tests better since we can run tests that needs durability

I think we should use InMemory solutions for acceptance tests

**Comment by andreasohlund** [comment]
Timeouts should be durable during dev to not loose retries/saga timeouts.

I guess substorages is less interesting if we go with the devtransport since that will take subscriptions out of the picture.

Side note: We could make the dev transport support timeouts natively and that would take the timeouts out as well and leave only sagas.

The sagas would be trivial if we could go with the "single correlation" sagas that I've proposed.

**Comment by andreasohlund** [comment]
>I think we should use InMemory solutions for acceptance tests

Not convinced, cleaning is super easy, just delete the "storage folder", and we want to test the  proposed persistence anyway?

I would hope we can get rid of the InMemory persitence alltogether and in that case the FileBased one would be just as easy to use?

**Comment by timbussmann** [comment]
> Not convinced, cleaning is super easy, just delete the "storage folder", and we want to test the proposed persistence anyway?

For setting up scenarios and verifying assertions, an InMemory model would be much less effort. But let's keep that out of topic for now?

> Timeouts should be durable during dev to not loose retries/saga timeouts.

Not sure this is really true for all scenarios (personally I never wanted to have that).

Which developers does this file based persistence really aim for? As soon as a customer uses a certain storage in production, they most probably use the same technology during development, right? So we're aiming at first time users or scenarios where you just want to spike something quickly?

again, what were the reasons preventing the two previous spikes to not complete?

**Comment by andreasohlund** [comment]
>For setting up scenarios and verifying assertions, an InMemory model would be much less effort. But let's keep that out of topic for now?

:+1: 

>Which developers does this file based persistence really aim for? As soon as a customer uses a certain storage in production, they most probably use the same technology during development, right? So we're aiming at first time users or scenarios where you just want to spike something quickly?

Yes, first time users, samples, demos, repros, etc

>again, what were the reasons preventing the two previous spikes to not complete?

The main issue is the saga persister which needs indexing and concurrency checks. The simple saga idea would solve this since we would be looking up on ID (filename in this case) all the time. And since file writes are atomic it would make the concurrency check trivial as well

**Comment by danielmarbach** [comment]
@Particular/platform-dev-squad I think we should consider this as part of the first time user experience initiative and make a decision as part of that initiative whether file based persistence and transport in the core is the way to go or we want the users to always select a specific transport

**Comment by DavidBoike** [comment]
@danielmarbach Are you talking about making a decision? Or potentially building the feature as well.

**Comment by danielmarbach** [comment]
@DavidBoike first of all I would like to have a decision. There seems to be some slight push from @andreasohlund into the direction of a file-based transport. I think we should lay out the pros and cons a bit better, as well as the alternatives and then come to a conclusion how to proceed (and potentially turn the spike into a feature)

**Comment by andreasohlund** [comment]
A filebased saga persister will be added in v6.3.0

The value of the others storage types is diminishing fast as most transports are moving towards native pubsub and timeouts. The only transport that might benefit from this in the long run would be MSMQ that could use a filebase dev persister for timeouts. For subscriptions its better go with the current MSMQ persister since that is a sensible default that's also production worthy.

I propose that we replace this with one issue for the dev saga persister and one for a dev TM storage for msmq?

@Particular/nservicebus-maintainers thoughts

**Comment by andreasohlund** [comment]
Duplicate of https://github.com/Particular/NServiceBus/issues/4278

**Comment by andreasohlund** [comment]
Its unlikely that we'll create filebased persisters for subscriptions and timeouts 
as explained in https://github.com/Particular/NServiceBus/issues/3445#issuecomment-294779108

Closing this
