### ISSUE TITLE
`PipelineCollection` should stop pipelines concurrently

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3447]
Aligns with [Lifecycle of startable and stoppable components](https://github.com/Particular/PlatformDevelopment/pull/616)

`PipelineCollection` should [stop](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/PipelineCollection.cs#L36) pipelines concurrently

**Comment by distantcam** [comment]
To be clear, the PR does *not* stop the pipelines concurrently.

**Comment by danielmarbach** [comment]
Yes my bad. I got trapped by the log statements. Will fix

**Comment by danielmarbach** [comment]
This is still solved. I got trapped by wording issues. I will update the PR description in #3481
