### ISSUE TITLE
Stop `FeatureStartupTasks` concurrently

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3448]
Aligns with [Lifecycle of startable and stoppable components](https://github.com/Particular/PlatformDevelopment/pull/616)

We should [stop](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureActivator.cs#L77) `FeatureStartupTasks` concurrently

@andreasohlund and I went through the `FeatureStartupTasks` and came to the conclusion that the order of stopping the tasks should not matter. And if we change the core to concurrently stop the tasks and hit an issue where it matters, then it is probably a design smell in the feature dependencies which needs to be solved.

**Comment by timbussmann** [comment]
I think we at least should ensure we stop every started component. Currently we stop stopping&disposing components as soon as one throws an exception.

The only place where concurrent stopping could potentially be dangerous would be on features which have a dependency on other features, but I'm not sure if there is every case where that dependency is still relevant when stopping?

**Comment by danielmarbach** [comment]
@andreasohlund and I agreed that stop shouldn't matter like you described.
If we find a bug by comcurrently shuttinf down then we'll fix the feature
dependency which caused it.

Are you proposing to track the started feature startup tasks and like we
currently do with IWanToRun...?

**Comment by timbussmann** [comment]
> If we find a bug by concurrently shutting down then we'll fix the feature
dependency which caused it.

:+1: 

> Are you proposing to track the started feature startup tasks and like we
currently do with IWanToRun...?

It probably doesn't make sense to call stop in case start never was called, but from the naming perspective it doesn't seem wrong either (IWantToRunWhen[...]Stops), since it doesn't imply any dependency to the start method. Since it doesn't seem to be an issue, let's keep it that way unless it requires more effort to maintain the current behavior.
