### ISSUE TITLE
Is TransportTransactionMode.SendsAtomicWithReceive relevant given our behavior in v6?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3451]
I was discussing transaction behavior with @bording and we came across this:

As described here we do batched dispatch in V6: http://docs.particular.net/nservicebus/messaging/batched-dispatch#behavior-in-version-6-and-higher

If I don't want to do batched sends, then I need to do the below when sending the message:
```c#
SendOptions options = new SendOptions();
options.SetDestination("TranOff");
options.RequireImmediateDispatch();
await context.Send(new SayHello(), options);
```

If I do the above, regardless of the transaction mode, i.e.`TransportTransactionMode.TransactionScope` or `TransportTransactionMode.SendsAtomicWithReceive`, the message is always sent. 

The other case is, when I set to TransportTransactionMode.SendsAtomicWithReceive but don't use RequireImmediateDispatch, again the behavior is not expected.

For example, endpoint Config:

```c#
endpointConfiguration.UseTransport<MsmqTransport>()
.Transactions(TransportTransactionMode.SendsAtomicWithReceive);         
```
In the following code, the `SayHello`message is never dispatched:

```c#
public class DoSomethingHandler : IHandleMessages<DoSomething>
    {
        public async Task Handle(DoSomething message, IMessageHandlerContext context)
        {
            Console.WriteLine("Received message!");
            await context.SendLocal(new SayHello());
            throw new Exception("BAD STUFF!");
            
        }
    }
```

So, when do I need to use `TransportTransactionMode.SendsAtomicWithReceive` ?
As I understand, this mode is only relevant for MSMQ and SQLServer transports.

**Comment by andreasohlund** [comment]
>If I do the above, regardless of the transaction mode, i.e.TransportTransactionMode.TransactionScope or TransportTransactionMode.SendsAtomicWithReceive, the message is always sent.

Immediate dispatch means "send the message straight out and do not return until you are sure that the message is safely in the hands of the queuing system" so the behavior seems to make sense to me?



>In the following code, the SayHellomessage is never dispatched:

And it shouldn't be since the configuration requested the "sends to be atomic with the receive operation" ?

>So, when do I need to use TransportTransactionMode.SendsAtomicWithReceive ? 

You would use it for scenarios where you want to make sure that no ghost messages slips out but don't want to make use of the DTC or the outbox. Batched dispatch makes ghost message less likely on all transports regardless of mode but it's still possible.


>As I understand, this mode is only relevant for MSMQ and SQLServer transports.

ASB also supports this (with a few restrictions on the target of the send/publish, think it needs to be in the same "namespace" cc @Particular/azure-maintainers )

**Comment by SeanFeldman** [comment]
@andreasohlund correct.

**Comment by indualagarsamy** [comment]
@andreasohlund - Can you please make sure that your explanations are documented in our doco appropriately?

**Comment by andreasohlund** [comment]
I went through 

http://docs.particular.net/nservicebus/messaging/transactions

and

http://docs.particular.net/nservicebus/messaging/batched-dispatch

but nothing stands out to me so I need a little help on what to change. Perhaps we can get on a call and walk through those docs together?

**Comment by weralabaj** [comment]
@andreasohlund I think this one is worth doing https://github.com/Particular/docs.particular.net/issues/1176. Something like listing in the box what transports support this option, so it's clearly visible at first sight.

**Comment by andreasohlund** [comment]
Agreed, I've chimed in there

**Comment by indualagarsamy** [comment]
@andreasohlund - I've setup a meeting for tomorrow.

**Comment by indualagarsamy** [comment]
Related Docs Issue: https://github.com/Particular/docs.particular.net/issues/1176
