### ISSUE TITLE
Race condition in container tests

### ISSUE THREAD

**Issue by HEskandari** [Particular/NServiceBus#3452]
There's a race condition in [this test][1], resulting brittle test runs. The problem is, the finalizer is run on another thread and you're not awaiting that to finish.

This also affects all downstream container repositories.

[1]: https://github.com/Particular/NServiceBus/blame/develop/src/NServiceBus.ContainerTests/When_releasing_components.cs#L26

**Comment by danielmarbach** [comment]
We ripped that test out. It is useless and testing internals of the
container. Here is the PR

https://github.com/Particular/NServiceBus/pull/3449

**Comment by andreasohlund** [comment]
Fixed in #3449
