### ISSUE TITLE
Prevent mixing constructor and property injection

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3458]
Not sure if we still are but we should:

* Write a unit test to make sure we don't mix (since spring don't support it)
* Fix any violations if found
* Figure out how to enforce this in our down streams as well

Question: Can we reliably detect this or are there legit use cases for a non-default ctor + public property that you set manually? or will that blow spring up as well

Note: Yes we want to kill off the containers but we're not there yet and I think this rule makes sense regardless

**Comment by timbussmann** [comment]
> Note: Yes we want to kill off the containers but we're not there yet and I think this rule makes sense regardless

Agree, the rule makes sense. I don't think we need to automate it tough. Or is it really such a big pain point? Let's make sure our guidelines state we always use constructor injection.

**Comment by SimonCropp** [comment]
i would prefer we drop property injection. if people still want it they can configure their container themselves

**Comment by andreasohlund** [comment]
>i would prefer we drop property injection

![image](https://cloud.githubusercontent.com/assets/125028/13042812/b3e60e74-d3c3-11e5-90d2-7a9a383c8acb.png)

There is no usages of `.ConfigureProperty` in the core, how about we obsolete it?

**Comment by danielmarbach** [comment]
I think we should. See also https://github.com/Particular/NServiceBus/issues/3464

**Comment by timbussmann** [comment]
:+1: for dropping property injection support.

**Comment by andreasohlund** [comment]
I took a quick look and this is the only blocker:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Basic/When_injecting_handler_props.cs

**Comment by danielmarbach** [comment]
@andreasohlund The history is here

https://github.com/Particular/NServiceBus/issues/2600

**Comment by andreasohlund** [comment]
yea, so are we happy with not supporting that and guiding users to use their container of choice?

**Comment by andreasohlund** [comment]
WIP pull [here](#3467). Seems doable if we want to pull this off?

**Comment by andreasohlund** [comment]
Probably better to focus on removing the container all together. Closing this
