### ISSUE TITLE
Make auto correlated properties [Unique] by default

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#346]
Properties set to be auto correlated by the user, CorrelatedBy(s=>s.CustomerId); should be [Unique] by default

**Comment by andreasohlund** [comment]
This is done from a core perspective. Only the InMemoryPersister is modified to honor this(by looking at the SagaMetaModel)

I'll raise separate issues to make sure it gets done for the other persisters.

I don't like the current api towards the persister since it's done by injecting the model:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs#L23

Does any one have ideas on how to make this more explicit?

**Comment by danielmarbach** [comment]
@andreasohlund why don't you change the `ISagaPersister` interface including it in the Save and Update call?

**Comment by andreasohlund** [comment]
That would be part of it. We also need this info during install time (to let eg NH setup indexes) but I guess that is something we can tackle together with the installer rewamp.

Don't we need it on the get call as well? (think raven would need it)

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus/pull/2693
