### ISSUE TITLE
Should we remove `RegisterSingleton` from `IConfigureComponent`

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3464]
Larger goal: We want to move away from the container.

`RegisterSingleton` is essentially not really needed since you can replace all `RegisterSingleton` calls with

`Configure(() => singleton, SingleInstance)`

When the core is refactored we could then remove `RegisterSingleton` which is a step in the right direction because it would force all existing users only using our Container abstraction API for all their `RegisterSingleton` usages to directly use a container.

@Particular/nservicebus-maintainers Thoughts?

**Comment by andreasohlund** [comment]
:+1:

**Comment by andreasohlund** [comment]
Issue raised to track the removal raised https://github.com/Particular/NServiceBus/issues/4180
