### ISSUE TITLE
Fix FLR max retries parameter

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#3466]
From https://github.com/Particular/NServiceBus/issues/3054
>Currently in v6 the FLR MaxRetries and SLR NumberOfRetries are interpreted in a different way than in v5. We should fix that. E.g. MaxRetries = 3 and NuberOfRetires = 2 result in 9 retires in total in v5 and 12 in v6

From https://github.com/Particular/NServiceBus/issues/3065
>Currently when endpoint instance restarts or in scale out deployments it possible that FLR/SLR will do more attempts than maxRetries. That's why we should change the name that it's actually minAttempts that can be specified.
The previous configuration options should be still supported for compatibility reasons.

**Comment by andreasohlund** [comment]
Definitely think the retries api should be merged. Not sure about the "error queue", but it definitely is related.

This related to [the notifications pull ](#3282 )as well since FLR and SLR is separate 

https://github.com/Particular/NServiceBus/pull/3282/files#diff-a8ffdd5b3ddae68e362456faeb0d634bR65

**Comment by timbussmann** [comment]
At first glance, I think we should still separate errorQ handling from retries. Retries is a feature which can be enabled/disabled, the errorQ behavior can't be disabled.

**Comment by MarcinHoppe** [comment]
Can't you call `configuration.DisableFeature<StoreFaultsInErrorQueue>`?

As to your second question, my idea (not yet fleshed out) is to move FLR and SLR settings together so that they are configured in one place. I think we can should be much more cautious around removing FLR and SLR concepts (albeit this is perhaps a discussion we need to have).

**Comment by timbussmann** [comment]
> Can't you call configuration.DisableFeature<StoreFaultsInErrorQueue>

no, the `StoreFaultsInErrorQueue` feature is private.

:+1: on having the FLR and SLR config options "close to each other"

**Comment by MarcinHoppe** [comment]
@timbussmann Good catch about visibility of `StoreFaultsInErrorQueue`, it is indeed not public.

**Comment by danielmarbach** [comment]
@MarcinHoppe Forgive my question. Are you driving this forward?

**Comment by MarcinHoppe** [comment]
@danielmarbach It's next on my TODO list but I'd love to brind a larger group together to work on this.

**Comment by andreasohlund** [comment]
Not a must have for v6, removing the label

**Comment by MarcinHoppe** [comment]
@andreasohlund This being a breaking API change effectively means we're postponing this until v7? I'll flesh out my thinking on this API change so that it is a starting point for discussion when the time comes.

**Comment by andreasohlund** [comment]
> This being a breaking API change effectively means we're postponing this until v7?

Yes

> I'll flesh out my thinking on this API change so that it is a starting point for discussion when the time comes.

:+1:

**Comment by MarcinHoppe** [comment]
@andreasohlund Do we need to re-open #3054 and #3065? They were supposed to be covered by this issue. Now that it is closed, I think we might need to bring these two back from the dead.

/cc @tmasternak

**Comment by andreasohlund** [comment]
>They were supposed to be covered by this issue. Now that it is closed

Since this one is still open can't we just let this one cover both just we planned?

**Comment by MarcinHoppe** [comment]
We can re-purpose this issue but I'm afraid this will drop the API redefinition issue into the abyss.

**Comment by andreasohlund** [comment]
>We can re-purpose this issue but I'm afraid this will drop the API redefinition issue into the abyss

Isn't this issue already re-purposed to cover the mentioned issues?

Side note: If we just add new apis this don't have to be a breaking change and can be done in a 6.X?

**Comment by MarcinHoppe** [comment]
At the cost of maintaining two sets of APIs to manage the same thing. I will re-purpose this issue to cover the two mentioned items and create a new issue with an API extension proposal.

**Comment by MarcinHoppe** [comment]
Done: #3593.

**Comment by MarcinHoppe** [comment]
Superseded by Particular/V6Launch#69.
