### ISSUE TITLE
HandlerContext.Advanced - More scoping on handler context?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3470]
Today in the short API walkthrough with @udidahan @indualagarsamy @mikeminutillo we discussed the handler context API and how it presents itself in intellisense. Here is a screenshot taken from a handler:

![image](https://cloud.githubusercontent.com/assets/174258/13077745/06f32758-d4bb-11e5-883e-76ae2fb621da.png)

The top level API exposes

* The bus operations
* Extensions
* SynchronizedStorageSession
* MessageId
* Headers
* ReplyToAddress

We agreed that in the majority of use cases inside handlers you probably only need access to the bus operations. Everything else can be considered "advanced" usage.

One possibility would be to hide all advanced usages in a property or method on the handler context like the following

```
context.Advanced.Extensions
context.Advanced.SynchronizedStorageSession
context.Advanced.MessageId
context.Advanced.Headers
context.Advanced.ReplyToAddress
```

@Particular/nservicebus-maintainers Thoughts?

**Comment by mat-mcloughlin** [comment]
Just saw the recording. I'm a fan of this idea.

It also reduces some of the noise in the intellisense popup

**Comment by danielmarbach** [comment]
I discussed this with @timbussmann today. The current handler context design makes it impossible at first sight to fulfill this idea. This comes from the fact that the pipeline contexts implement the different scope handler context interfaces. If we would implement an advanced property or method this would immediately be exposed in the pipeline as well. Arguably in the pipeline this `.Advanced` approach would not be intention revealing. 

We discussed a solution approach with extension methods where the extension methods expose the advanced stuff on different levels. The problem is that the extension method is applied on the user facing interface and would need to "evil cast" the user facing context into the internal pipeline context. This would pretty much destroy testability as we currently have it.

**Comment by SimonCropp** [comment]
-1 on this idea. the number of member in that intelisense popup is not large. just clarifying it with one character eg s for send and it is much simplified.

**Comment by bording** [comment]
One of the ways I'll often start to explore a new API is to just create an instance of a class and then open intellisense to see what is available. Having some sort of logical grouping to related API methods/properties makes it much easier to understand how the API works.

This sort of exploratory investigation is much harder when there are a lot of unrelated items all hanging off the same class.

**Comment by danielmarbach** [comment]
I don't think this provides enough value to justify large rework and possibly overhaul the handler context API, see comments https://github.com/Particular/NServiceBus/issues/3470#issuecomment-184688098
