### ISSUE TITLE
Pitfalls & Boilerplate when starting the endpoint

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3471]
Today in the Short API walkthrough with @udidahan @indualagarsamy @mikeminutillo we discussed the potential pitfalls and involved boilerplate when starting an endpoint.

1. Starting and stopping requires an asynchronous operation. The most commonly used hosts like console and windows service are not async friendly
2. Start of the endpoint needs to be wrapped in a `try/finally` all the time to properly shutdown the bus. To be able to write `await` in a `finally` block you need CSharp language level 6.
3. Too much noise end Endpoint static class level.

### A naive approach

```
 static void Main(string[] args)
 {
     var configuration = new EndpointConfiguration();
     var endpoint = await Endpoint.Start(configuration);
 }
```

Alt+Enter

```
static async void Main(string[] args)
 {
     var configuration = new EndpointConfiguration();
     var endpoint = await Endpoint.Start(configuration);
 }
```

Housten, we have a problem

### Recommended approach by samples and guidance

```
 static void Main(string[] args)
 {
     Run().GetAwaiter().GetResult(); // or .Wait()
 }

 static async Task Run() {
     var configuration = new EndpointConfiguration();
     var endpoint = await Endpoint.Start(configuration);
  }
```
Is there a way we could improve this?

## Boilerplate to start and stop the endpoint

```
 static async Task Run() {
     var configuration = new EndpointConfiguration();
     try {
     var endpoint = await Endpoint.Start(configuration);
     } finally {
         await  endpoint.Stop();
     }
  }
```

Essentially the try/finally is used in each and every endpoint. Arguably before it was the same "boilerplate" but with a `using` statement in V5.

Being able to write `await` in a `finally` block requires CSharp language level 6. Is it fair to assume that all people using v6 should already have CSharp Language Level 6?

### Noise on `Endpoint` static class

Currently we have 

* `Endpoint.Start` - Prepares, Creates and Starts the endpoint in one go. Should be used by majority of users
* `Endpoint.Create` - Validates the configuration and creates an initialized endpoint which can later be started
* `Endpoint.Prepare` - Validates the configuration

Should we ditch `Prepare` and `Create` from the public API level?

### Starting and stopping the endpoint

* Provide helper methods in core or as a separate bootstrapping package which removes the need to write the boilerplate code

## Boilerplate to start and stop the endpoint
* Provide helper methods which starts/stops the endpoint with a finally block. i.e. (just an idea)

```
await Endpoint.Start(configuration, 
   endpoint => { 
      // similar to scoped session, might even be the same ;)
   });
// endpoint is already stopped
```

This might remove the necessity to use CSharp language level 6. But I'd argue since when you are working in an async codebase you end up needing an `await` in a finally block anyway and therefore most users might already fulfill the language level requirement when they start adopting v6.

### Noise on `Endpoint` static class

Just get rid of it.

@Particular/nservicebus-maintainers Thoughts?

**Comment by bording** [comment]
Regarding the `Endpoint` methods, I agree with removing `Prepare` and `Create` from the public API and just have `Start'. 

I'm not sure I see the benefit of the proposed helper method. You still have to await it, which means it still won't work in a standard `void Main` entry point. How much has this actually improved anything?

**Comment by SimonCropp** [comment]
@danielmarbach 

> Essentially the try/finally is used in each and every endpoint

Not sure that is true? The most common scenarios for real world hosting are 

 * NSBHost https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/nservicebus-host/Version_6/Sample/EndpointConfig.cs
 * web application https://github.com/Particular/docs.particular.net/blob/master/samples/web/asp-web-application/Version_6/WebApplication/Global.asax.cs
 * Windows Service hosting https://github.com/Particular/docs.particular.net/blob/master/samples/hosting/windows-service/Version_6/Sample/ProgramService.cs

None of the above need the try/await in finally or a using. From my experience the using or the try finally pattern is of very little value in most hosting scenarios. It is only common in samples since most samples are not designed to illustrate the complexities of hosting.

So based on that i would say "Boilerplate to start and stop the endpoint" is yagni.

**Comment by mikeminutillo** [comment]
>  From my experience the using or the try finally pattern is of very little value in most hosting scenarios. It is only common in samples since most samples are not designed to illustrate the complexities of hosting.

I agree with this. In most real-world cases it is not the same method that starts and stops an endpoint nor is the code to manage the endpoint so close to the process entry point.

**Comment by danielmarbach** [comment]
@simoncropp

In my personal opinion, there is nothing to change/add to the current way
of starting and stopping the endpoint (except the removal of Prepare and
Create on Endpoint). But since we discussed it in the call I wanted to
raise awareness here by discussing it in a question.

**Comment by distantcam** [comment]
Suggesting try/finally is actually harmful and we shouldn't do it.

    static void Main()
    {
        Run().GetAwaiter().GetResult();
    }

    static async Task Run() {
        var configuration = new EndpointConfiguration();
        configuration.ForwardReceivedMessagesTo("audit");
        configuration.SendFailedMessagesTo("error");
        IEndpointInstance endpoint = null;
        try {
            endpoint = await Endpoint.Start(configuration);
        } finally {
            await  endpoint.Stop();
        }
    }

This code throws a `NullReferenceException` on the line in `Main`. Can you tell why? Do you think our users will understand what's going on, or have the knowledge to debug it themselves?

**Comment by danielmarbach** [comment]
@distantcam Yeah of course my contrive example was missing a null check.

**Comment by distantcam** [comment]
@danielmarbach Null isn't the actual issue. What is the issue?

**Comment by danielmarbach** [comment]
Yeah I meant that if endpoint start throws an exception, then endpoint is null but the null reference exception is raised deep down in the state machine because we are trying to await something that can't be awaited. So the exception you'd see would be "masking" the root cause

**Comment by danielmarbach** [comment]
You can easily reproduce this with

```            try
            {
                throw new InvalidOperationException();
                endpoint = await Endpoint.Start(configuration);
            }
            finally
            {
                await endpoint.Stop();
            }
``
Boom, you get a System.NullReferenceException instead of the InvalidOperationException

```
NServiceBus.ApiDemo.Program.<Run>d__1.MoveNext() Program.cs: line: 32
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
NServiceBus.ApiDemo.Program.Main(String[] args) Program.cs: line: 13
System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
System.Threading.ThreadHelper.ThreadStart_Context(Object state)
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Threading.ThreadHelper.ThreadStart()
```

**Comment by distantcam** [comment]
Right! So now the "boilerplate" gets a little more complex as you try to handle exceptions in the start call.

That's why I don't think we should recommend a try/finally boilerplate at all. Or even a try/catch/finally. The boilerplate is complex enough we should just implement it ourselves in a helper class.

**Comment by danielmarbach** [comment]
Talked to @andreasohlund @timbussmann and we came to the conclusion this is mostly about adding new syntactic sugar and helpers. We don't need to do this as part of the v6 launch

**Comment by andreasohlund** [comment]
Now that the v6 ship has sailed can we extract some action points from this discussion?

**Comment by danielmarbach** [comment]
I'd vote for closing this one and wait for real user feedback.
