### ISSUE TITLE
Allow IQueryTimeouts to be notified when the endpoint shuts down or when work needs to be cancelled

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3472]
We have [scenarios](https://github.com/Particular/NServiceBus.RavenDB/issues/140) in which a downstream component may hang and prevent the endpoint to be shut down properly.

There is a [proposed fix for the specified issue](https://github.com/Particular/NServiceBus.RavenDB/pull/166) but the fix relies on the fact that the component implementation is the expected one and not the Core interface, since the Core interface (`IQueryTimeouts`) misses the required method. Obviously if the end user replaces the default implementation the issue may surface again (and the above fix will fail).

Given that the above is a bug we need to backport it to previous NServiceBus versions as well, V5 at least, any suggestion on how to approach the issue is very welcome.

The easy fix would be to add a `Shutdown` method to the `IQueryTimeouts` interface a much better one would be to provide a Feature with an `OnStart` and `OnStop` options.

/cc @colin-higgins 

Thoughts?

**Comment by danielmarbach** [comment]
For the `IQueryTimeouts`

A query has well-defined semantics. When you call a query you get the result back in a reasonable amount of time or a timeout exception if the resource you are querying is unresponsive. Adding a shutdown method feels wrong. A CancellationToken would make more sense.

here is how EF does it

https://msdn.microsoft.com/en-us/library/dn220262(v=vs.113).aspx
https://msdn.microsoft.com/en-us/library/dn220059(v=vs.113).aspx
https://msdn.microsoft.com/en-us/library/dn236970(v=vs.113).aspx

**Comment by mauroservienti** [comment]
After a discussion with @timbussmann, @andreasohlund and @ramonsmits I'm closing this one in favor of this effort https://github.com/Particular/NServiceBus/issues/3532.
The idea is that we can fix this at the persistence level without affecting core, especially in light of the fact that we have the goal to completely re-design timeouts management.
