### ISSUE TITLE
Have an alternative for FLR in non-transactional transport configurations

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3476]
It seems that V6 has the option to have SLR enabled even though transactions on the transport are disabled. We do a best effort to schedule the message for SLR.

It would be nice if we would also have this for FLR. Current FLR relies on rolling back the transaction and having an lookup state to identity the FLR count.

The alternative would be to just enqueue it again. The message would end up in the backlog but retries.

In this case the retry count state can just be added to the message and no FLR state needs to be maintained in the endpoint instance or even across multiple instances.

This retry mechanism would only work if the transaction is not participating in a possibly active distributed transaction. Distributed transactions can still be used but that scope should be created after retrieving the message from the queue.

**Comment by ramonsmits** [comment]
Based on the second part of this comment: https://github.com/Particular/NServiceBus/issues/2750#issuecomment-153475164

@andreasohlund asked to raise this as a separate issue.

**Comment by timbussmann** [comment]
What value does this provide over just using SLR?

**Comment by ramonsmits** [comment]
@timbussmann Not being dependent on timeouts. This method retries as fast as possible. It will not be send to a retries queue first, then scheduled, dehydrated and put on a queue again.

Second is that the number of retry attempts are fixed and also works in competing consumer environments.

**Comment by danielmarbach** [comment]
Since we are moving towards a lingo where we only talk about retries I have a hunch this will be built-in

**Comment by timbussmann** [comment]
> This method retries as fast as possible. It will not be send to a retries queue first, then scheduled, dehydrated and put on a queue again.

I don't see enough value over just using SLR. Yeah it's faster but I don't really see a urgent need to make error cases be more performant.

> Second is that the number of retry attempts are fixed and also works in competing consumer environments.

Again, like on other issues, I'm strongly against solving the "fixing retry attempts" for special edge case scenarios only. I think it's best to keep the behavior consistent and find a solution which works for every approach.

**Comment by danielmarbach** [comment]
I agree with @timbussmann 

@Particular/nservicebus-maintainers I vote for closing this but consider it when we address recoverability in the next release

**Comment by danielmarbach** [comment]
Deleted my comment. See follow up from @timbussmann

**Comment by timbussmann** [comment]
after discussing this quickly with @danielmarbach I need to revert my opinion on this issue. Since we have to use transactions for SLR to work properly (currently we're not using transactions and this is a known bug which will be fixed before v6 release). This means there is no way to use SLR behavior on non-transactional endpoints. I agree with @ramonsmits that it can make sense to allow certain non-transactional retry mechanisms.

@andreasohlund did v5 allow SLR retries without using transactions? (if so, do we need to consider this feature for the v6 release?)

**Comment by andreasohlund** [comment]
>did v5 allow SLR retries without using transactions

No, `transactions.Disable` in v5 meant no FLR, no SLR and no MoveToError

**Comment by MarcinHoppe** [comment]
I think we should document it on this page: http://docs.particular.net/nservicebus/errors/automatic-retries.

When I read it as an NSB newbie, it would not occur to me that retries are off when transactions are disabled (although it might seem obvious after giving it a little bit of thought).

Agree?

**Comment by timbussmann** [comment]
@MarcinHoppe :+1: raised a doco issue here: https://github.com/Particular/docs.particular.net/issues/1320

**Comment by MarcinHoppe** [comment]
Thanks @timbussmann. I'm on it.

**Comment by timbussmann** [comment]
quick thoughts on this issue: it seems that a "Error Queue Behavior" would also be a desirable feature besides retry mechanisms. But it seems that all of them would be in a best-effort manor, still not providing any guarantees.

**Comment by timbussmann** [comment]
Closing this issue as this is currently tracked internally.
