### ISSUE TITLE
Log diagnostic information at startup

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3479]
It would be nice if we would log diagnostical information at startup. Information like:
- Commandline
- Process identity info
- GC Settings (server/desktop)
- Running as x86 or x64
- The OS
- Number of cores/processors
- Current path / temp path

This helps in identifying the environment in which the endpoint is running. Maybe this should be moved to the 'host'.

**Comment by danielmarbach** [comment]
I'd say this is a hosting concern. For example in the azure host you might need specific SDK calls to determine the information. The information you gather could vary a lot between different hosting environments

**Comment by MarcinHoppe** [comment]
@andreasohlund Have items raised by @ramonsmits been added to the startup diagnostics logged by the core?

**Comment by andreasohlund** [comment]
Everything except cmdline since it was deemed to potentially contain sensitive data like passwords.

@ramonsmits can you confirm?

**Comment by andreasohlund** [comment]
See https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/HostInformationFeature.cs#L55

**Comment by timbussmann** [comment]
I'd say this is done then?
