### ISSUE TITLE
More explicit TransportTransaction

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3485]
@andreasohlund @SzymonPobiega and I were contemplating if we need a more explicit way to deal with transport transactions.

## PushContext

Current the `TransportTransaction` implements a `ContextBag` but the `PushContext` itself also accepts a `ContextBag`. Without more information it feels weird that essentially two context bags are passed in. The reason why `TransportTransaction` is a `ContextBag` is because of the transaction sharing between SqlTransport and NHibernate. Since there should be no dependency between those two packages we can use the `ContextBag` exposed by the `TransportTransaction` as a duck type to get the required information out of it. Another approach would be

* Make `TransportTransaction` an abstract class in the core with a `ContextBag` property similar to this

```
public abstract class TransportTransaction {
   public ContextBag Extensions { get; } // or Extras...
}
```
* Provide in the core a NoOp implementation similar to this

```
public class NoTransaction : TransportTransaction { }
```
* Change the push context to register the type hierarchy of the `TransportTransaction` implementation so that transport implementors can `TryGet` their implementation
* Transports which don't use `NoTransaction` can then implement their own strongly typed version of the transaction without losing the duck typing benefit, see pseudo code

```
class MsmqNaitiveTx : TransportTransaction

//msmq Dispatcher
   context.TryGet<MsmqNaitiveTx>


//nhibernate

 context.TryGet<TransportTransaction>()
    .Extensions .TryGet<ISession>
```

## Dispatcher

Furthermore we were also rationalizing over passing in the `TransportTransaction` as an explicit parameter to the `IDispatcher` interface like

```
Task Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, ContextBag context);
```

We think this doesn't have to be part of V6 since the benefit is not that huge. Thoughts?

@Particular/nservicebus-maintainers @Particular/transport-maintainers

**Comment by danielmarbach** [comment]
Closing this. Not enough value right now.

**Comment by tmasternak** [comment]
Just adding my 2cc for future reference:
 * I think we should identify all scenarios in which `TransportTransaction` sharing between **different** packages can happen. I know that currently it's `NServiceBus.SqlServer` and `NServiceBus.NHibernate`. What are other examples? It would be good to identify them to make sure we have a proper use cases to support the code changes
 * I would like to have discussion if we should use the same mechanism to share transactions between different packages (see example in point above) and inside given transport (`MessagePump` and `MessageDispatcher`
