### ISSUE TITLE
Null task handling

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3486]
In the short API walkthrough with @udidahan @indualagarsamy and @mikeminutillo we discussed this issue. This is a summary for a discussion

By default tools like Resharper auto generate implementations for handlers like the following

```
public Task Handle(MyCommand message, IMessageHandlerContext context)
{
    return null;
}
```

This is problematic because when we `await` such a handler internally in the core a `NullReferenceException` is raised. If you don't know that you should not return null for `Task` then this `NullReferenceException` doesn't help the user to find the root cause.

The root cause is that CSharp allows null but the Task API doesn't. A task represents a promise or future. Null doesn't fulfill the API constraints to represent a promise and therefore can't be awaited. The task based API is very close to functional programming. In functional programming a function always has a return type which is not null. The idiomatic way to represent a promise which indicates there is nothing to do here is to use `Task.CompletedTask`

## Correct way of doing it

```
public Task Handle(MyCommand message, IMessageHandlerContext context)
{
   return Task.CompletedTask;
}
```
or

```
public async Task Handle(MyCommand message, IMessageHandlerContext context)
{
}
```
Unfortunately produces compiler warning which the hint that nothing is awaited inside the handle method and therefore the code will be executed synchronously.

### It is how it is, educate

Language and API constraints are the nature of this problem. We can decide to not do anything but educate our users with the story I started.

### It is how it is, educate, write a tool & analyzer

Language and API constraints are the nature of this problem. We can decide to ship an analyzer or tool to educate our users in combination with the story I started.

### Handle null tasks in the framework

Skim through all extension points which return a task and decide whether we want to handle null tasks or not. If the decision is to handle null tasks we have to decide what to do. We would need the following pattern:

```
var task = invocation(Instance, message, handlerContext);
if (task == null)
{
   // what do we do here?
}
return task;
```

The next sections might only be relevant for code paths which participate in receiving a message.

#### Throw a new more meaningful exception

Rethrow an exception like

```
throw new InvalidOperationException("Please return either a Task, a completed Task or mark the method { methodInfo } as async")
```

#### Log Warning and mark message as processed

We could log a warning and mark the message as processed nonetheless. The assumption would be that the intent of returning null was that the user executed the code in the handler synchronously.

### Thoughts

The impact of this is non-trivial. For handlers and sagas there is one extension points which calls the `IHandleMessages`, `IHandleTimeouts` etc. implementations. But consider for example the pipeline. Essentially users can hook in at any arbitrary place their own behaviors. Which would mean we would need to safeguard all behaviors if we want to do it consequently.

## Stories

* The null promise (working title) https://github.com/Particular/Stories/pull/325

**Comment by danielmarbach** [comment]
@distantcam Made an attempt to tackle on of the approaches described above in this PR

https://github.com/Particular/NServiceBus/pull/3475

**Comment by danielmarbach** [comment]
My vote is for approach "It is how it is, educate, write a tool & analyzer" but of course I'm biased ;)

**Comment by udidahan** [comment]
> If you don't know that you should return null for `Task`

Is that supposed to be "you should not return null" ?

**Comment by danielmarbach** [comment]
@udidahan yes sorry. Fixed

**Comment by distantcam** [comment]
> It is how it is, educate, write a tool & analyzer

The only problem with analyzers is they only work in Visual Studio 2015. All other IDE's won't have them.

> It is how it is, educate

This is basically saying "you're doing it wrong". At the end of the day this is a trivial language detail. I can appreciate wanting to educate our users but I'm not sure how it really educates them beyond the complexities of the TPL. On top of that if tools like R# also recommend returning null we probably shouldn't argue against the tooling. I just get frustrated and annoyed when the tools don't work together.

> Throw a new more meaningful exception

Ultimately I don't think it's a mistake to return null. The only way to return null is if the code is sequential, so there's no actual harm. The reason why it's "wrong" is conceptual, and not because it could lead to errors or other problems.

> Log Warning and mark message as processed

If we must complain about null then this is my preferred option.

> Handle null tasks in the framework

Ultimately I prefer this option.

**Comment by udidahan** [comment]
&lt;Engineer hat on/&gt;
For the "handle in the framework" option, I'd say that we can take into account some additional points:
1. Developers who write behaviors tend to be more knowledgeable and skilled
2. Most of our users only write handlers (and maybe simple sagas) probably know less about async

If these assumptions are correct, the possibly low-effort option of only handling null for handlers and sagas may be acceptable. For the pipeline, we may be able to get away with education/docs.

Thoughts?

**Comment by danielmarbach** [comment]
@udidahan would the same reasoning apply to

* `IWantToRunWhenTheBusStartsAndStops`
* `IFindSagas`

?

**Comment by danielmarbach** [comment]
FYI. I did a quick analysis with MVC vNext. A controller with

```
        public Task<IActionResult> Index()
        {
            return null;
        }
```

chokes the following exception prepared by the framework:

```
Cannot return null from an action method with a return type of '{0}'.
```

```
        public Task<string> Index()
        {
            return null;
        }
```

works


```
        public Task Index()
        {
            return null;
        }
```

works.

**Comment by SimonCropp** [comment]
From my perspective

When someone is implementing a contract and we are consuming that contract the retrun value should be considered part of our public api surface area. So we should treat it exactly the same as any parameter that is passed into any of the methos, ie we guard against invalid values and throw an informative exception.

Now i realize some things are more difficult to guard against than others. So we need to apply some roi logic when doing this. But i think in most cases it is trivial to validate return values. Yes it is a little extra noise but worth it.

-1 to an analyser since it is not possible to definitively say, at compile time, that a given function will return a null. So for me the roi on that one is not quite high enough.

**Comment by mikeminutillo** [comment]
For handlers, I think it is worth accepting `null` returns. There will be many users who are not writing async handler code. There will also be many users who lean on R# to implement our interface. I would expect the cross section of these sets of users to be quite large. Time and again they will generate code that we could easily have handled and instead we will shout at them. 

If that happened to me there are a few responses I might have:
1. *R# sucks. It is generating the wrong code.*
2. *NSB sucks. I don't even want to do async.*

I think the second response is more likely. We are the thing that has changed (or is new).

**Comment by bording** [comment]
I agree with @SimonCropp here. We should guard against a null return value and throw an exception unless there is an actual valid path we can take in the `// what do we do here?` section. I suspect that most of the time we'd just have to throw.

 It should be obvious pretty quickly during development if you get a "don't return a null task" exception while running your code.

I'd also like to point out that not everyone uses R#. I personally find it too invasive and don't have it installed. If you rely on on the default Visual Studio tooling to implement the interface you get the following:

```
public Task Handle(MyCommand message, IMessageHandlerContext context)
{
    throw new NotImplementedException();
}
```

**Comment by johnsimons** [comment]
I noticed this is not tagged for v6, so with that in mind, how about we release what we have and improve it later once we start getting constructive feedback from our users

**Comment by SimonCropp** [comment]
@johnsimons so null ref in the guts of NSB is the worst of the possible ways to handle this

**Comment by SimonCropp** [comment]
@mikeminutillo 

> For handlers, I think it is worth accepting null returns

The only reason i dont like that is we cant tell if it is a null because they did it on purpose or it is a null because they have a bug in their code.

**Comment by mikeminutillo** [comment]
@SimonCropp 

> The only reason i dont like that is we cant tell if it is a null because they did it on purpose or it is a null because they have a bug in their code.

Can you think of a scenario where this could happen accidentally? It will not happen in an `async` method as the Task is generated. It will only happen if they explicitly return a `Task`. They could conceivably call in to a method that return `null` and return that to us and we'd be hiding that. Is that likely?

**Comment by udidahan** [comment]
&lt;Engineer hat still on /&gt;
What about the matter of different behavior when the #debug flag is set?

**Comment by SimonCropp** [comment]
@udidahan I don't really see any value we can leverage from that. Can u add some more detail?

**Comment by udidahan** [comment]
What if we were to handle nulls returned from handlers and sagas this way:

if (returnedTask == null)
{
    if (userDidntDeclareTheyKnowWhatTheyreDoing)
        if #debug throw exception ("here's why you shouldn't do that")
        else log.Warn(...);
}

It was my understanding that this is the approach we generally take for baked-in guidance.

**Comment by SimonCropp** [comment]
@udidahan in compiled code u cant reliable detect that

**Comment by SimonCropp** [comment]
@mikeminutillo 

> Can you think of a scenario where this could happen accidentally? 

U mean a case where something is unexpectedly null? well that is the reason why nullrefexcetions are common, because we never expect something to be null :)

**Comment by mikeminutillo** [comment]
@SimonCropp
> U mean a case where something is unexpectedly null? well that is the reason why nullrefexcetions are common, because we never expect something to be null :)

Well there are only 3 cases that I can think of.

### 1. Async

```CSharp
public async Task Handle(SomeMessage message)
{
  // return null; 
}
```
You can't return a null task from an `async` method because the compiler generates the `Task` for you. 

### 2. Return null inline

```CSharp
public Task Handle(SomeMessage message)
{
    // Normal processing with message
    return null;
}
```
Processing has finished by the time you return `null`. If we swallow this it's OK.

### 3. Return null "accidentally"

```CSharp
public Task Handle(SomeMessage message)
{
    // Normal processing here
    return SomeMethod(); // SomeMethod returns null
}
```
The thing is, for `SomeMethod()` to return `null` it must be case 2 above or another instance of case 3. Eventually we will hit case 2. I don't think it's possible to return `null` from a handler *without having handled the message*.

**Comment by danielmarbach** [comment]
I still think in the "return null inline" case we shouldn't just handle that gracefully but have an opinionated way of dealing with it. Like raising an InvalidOperationException which an explanatory exception message.

**Comment by mikeminutillo** [comment]
@danielmarbach what is the benefit of doing that? Are we preventing the user from making a mistake that will hurt their application?

**Comment by timbussmann** [comment]
> This is basically saying "you're doing it wrong". At the end of the day this is a trivial language detail.

That doesn't change the fact that they are doing it wrong. If they learn from us that returning null is ok, they will encounter a lot of problems when using other frameworks/libraries just because we try to make async/await easier than it is.

I'd vote for checking & throwing on handler invocation.

**Comment by andreasohlund** [comment]
>That doesn't change the fact that they are doing it wrong. If they learn from us that returning null is ok

Agreed, the same way that we make developers better by educating them around messaging topics we should do the same for code related stuff. Users rely on us paying attention to these things and help them "become better developers". Hiding their bad code is just defering their pain until they use another lib just like @timbussmann points out.

>I'd vote for checking & throwing on handler invocation.

I vote for this as well

**Comment by danielmarbach** [comment]
thanks @timbussmann and @andreasohlund that I'm not the only one who thinks like that :dancer:

**Comment by danielmarbach** [comment]
Does this require a sync meeting @udidahan or can we go with the proposed exception approach favoured by @andreasohlund, me and @timbussmann ?

**Comment by udidahan** [comment]
I don't need another sync on this.

**Comment by danielmarbach** [comment]
Opened up a new issue reflecting the work to be done.

https://github.com/Particular/NServiceBus/issues/3533
