### ISSUE TITLE
RijndaelEncryptionService.cs NotSupportedException: "Please use overload Encrypt(string, OutgoingContext)"

### ISSUE THREAD

**Issue by fafachd** [Particular/NServiceBus#3490]
Moving from https://github.com/Particular/ServiceControl/issues/620 as requested by @gbiellem 

I just upgraded from NServiceBus v5.2.8 to 5.2.12. Now when I try calling the Encrypt(string) method using the RijndaelEncryptionService I get the following NotSupportedException: "Please use overload Encrypt(string, OutgoingContext)". However I cannot find this new overload; I still only see Encrypt(string) implemented.

Thanks,
Danny

**Comment by ramonsmits** [comment]
@fafachd When are you calling that? Can you give some more context? That is used by our property encryption.

**Comment by fafachd** [comment]
We are calling this method manually to encrypt sensitive saga-data properties in before NSB saves them in RavenDB so we can leave read access open for developers on our raven instances in production.

**Comment by ramonsmits** [comment]
@fafachd Using the encryption service to provide encryption for persistence. That is an interesting use case.

It is not possible anymore to use the regular `IEncryptionService` as this was changed to prevent the possibility of data corruption when using rotating keys:

- [5.2.9 Release notes](https://github.com/Particular/NServiceBus/releases/tag/5.2.9)
- [5.2.11 Release notes](https://github.com/Particular/NServiceBus/releases/tag/5.2.11)

Internally we added the `IEncryptionServiceWithContext` interface but that interface is not exposed.

**Comment by ramonsmits** [comment]
This usage was not foreseen and maybe not the intent of the interface. The intent was (I assume) to be able to use your own encryption logic in the encryption behavior.

- http://docs.particular.net/nservicebus/security/encryption#property-encryption-custom-handling-of-property-encryption

There are a couple of options

1. This is not the correct usage of `IEncryptionService`
1. It is allowed, then we can:
 1. Revert throwing those throws and support previous behavior
 1. Expose [`IEncryptionServiceWithContext`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Encryption/IEncryptionServiceWithContext.cs) but then you also have to provide the additional parameters.
 1. Do both

NServiceBus would not be using the old methods anymore but that results in a risk that the user potentially has data corruption when rotating keys.

@andreasohlund @DavidBoike @justabitofcode @WojcikMike What is your opinion?

**Comment by ramonsmits** [comment]
@fafachd Do you use key rotation? That would mean that your data is not re-encrypted until the saga data is saved again which means that your old keys are always present in your (code) configuration.

**Comment by andreasohlund** [comment]
>This is not the correct usage of IEncryptionService

Leaning towards this one, this interface was never intended for general purpose encryption.

**Comment by danielmarbach** [comment]
I agree with @andreasohlund The interface it tightly coupled with the usage in the core and is not intended built for general purpose encryption. I'd suggest you use your own custom encryption component as a pipeline extension or use ravens encryption bundle

https://ravendb.net/docs/article-page/3.0/csharp/server/bundles/encryption

**Comment by danielmarbach** [comment]
@ramonsmits @andreasohlund I lean towards, Close won't fix.

**Comment by fafachd** [comment]
Closing this issue and opening a feature request instead:
https://github.com/Particular/NServiceBus/issues/3519

**Comment by fafachd** [comment]
Thanks for the tips, @danielmarbach, I'll look into those options.
