### ISSUE TITLE
Outbox behavior: outgoing messages and transactions

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3493]
Open question raised during a call with @tmasternak 
Say that we have an Outbox enabled endpoint where in the configuration the user enabled distributed transactions (and we are running on a DTC enabled transport), the messages flow is the following:

```
- input message
  - message handler
     - business data changes
     - event publishing (to 5 subscribers)
```

What happens with the Outbox?
### Scenario A

```
- input message
  - message handler
     - business data changes
     - event publishing (to 5 subscribers)
- 5 outgoing messages/operations are stored in the Outbox table
- a single transaction is started by the outbox
   - messages are delivered to their destinations
- the Outbox transaction is committed
```
### Scenario B

```
- input message
  - message handler
     - business data changes
     - event publishing (to 5 subscribers)
- 5 outgoing messages/operations are stored in the Outbox table
- for each outgoing message
   - transaction is started by the outbox
      - the message is delivered to its destination
   - the message transaction is committed
```

**Comment by andreasohlund** [comment]
For v6:

We automatically lower the transaction mode to `ReceiveOnly` if the outbox is enabled but if the user explicitly requests `TransactionScope` it will lead to a variation of ScenarioB

Ie the same steps will happen but with all ops, both outbox and outgoing sends, enlisted in the scope created by the transport for the message receive operation.

For v5: Would have to check but there are more scopes involved, best guess is same as above

Does this clear things up?

**Comment by tmasternak** [comment]
I think that we were wondering if performing sends for outgoing messages will be done in a single transaction or separate transactions - one for each outgoing message.

@andreasohlund if I understand correctly unless user sets both Outbox and DistributedTransactions the sends will be done in separate transactions. Is that correct?

**Comment by andreasohlund** [comment]
>@andreasohlund if I understand correctly unless user sets both Outbox and DistributedTransactions the sends will be done in separate transactions. Is that correct?

Correct, outbox tx and send tx is separate transactions.

**Comment by tmasternak** [comment]
Here is the summary of quick sync with @andreasohlund. Here is how it works:
|>-------------------[Msg Receive Transaction]--------------------------------------<|
------|>--[Handler + Outbox Storage Trans]---<|---|>---[Outgoing Msg]-------<|

What we are interested is `Outgoing Msg` part (I'm not calling it transaction for a reason). What is happening is that core will give the transport all messages that it wants to be sent with DispatchConsistency set to Isolated. 

What it means is that transport is not obliged to respect any existing transaction and/or bundle all sent messages in single sent operations. In practice behavior depends on the transport e.g. SqlServer will enforce separate transaction per outgoing message and ASB will do a batch sends - 100 messages at a time.

/cc: @mauroservienti if that answers you initial question feel free to close this issue.

**Comment by timbussmann** [comment]
> Correct, outbox tx and send tx is separate transactions.

@andreasohlund we are dispatching outbox messages in isolated mode, so that's even a bit different, isn't it?

@mauroservienti is there still something to answer/discuss here?

**Comment by andreasohlund** [comment]
>we are dispatching outbox messages in isolated mode, so that's even a bit different, isn't it?

Correct, all messages are dispatched with the isolated flag so the transport is free to optimize as it sees fit

**Comment by timbussmann** [comment]
I'll close this issue as of now. @mauroservienti feel free to reopen if your questions haven't been answered. In case you want to propose some behavior changes, I think it would make sense to open a new issue.
