### ISSUE TITLE
Transient_component_should_be_destructed_called only works when compiled in release

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3496]
At least for structuremap.

Should we put an `#if !DEBUG` around it?

**Comment by danielmarbach** [comment]
@andreasohlund we remove that test as part of https://github.com/Particular/NServiceBus/pull/3449/files#diff-5e8469813b60e7b73e3937c2b2e97222L11

**Comment by andreasohlund** [comment]
Duplicate of https://github.com/Particular/NServiceBus/pull/3449
