### ISSUE TITLE
V6 Timeouts do not work with Outbox

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3499]
TimeoutStorage satellite and Main Pipeline satellite are both performing message de-duplication in `TransportReceiveToPhysicalMessageProcessingConnector`. Outbox record id equals EndpointName+MessageId and is the same no matter if Outbox record has been created in satellite or in Main Pipeline. 
As a result no timeout will be delivered when Outbox is turned on. Let's say we have EndpointA and message with Id=123. What happens is:
 * Timeout message is sent to Timeout queue
 * It's processed by TimeoutStorage pipline and EndpointA/123 record is added to Outbox
 * After due time the timeout message gets dispatched to main queue
 * It's processed by Main Pipeline and considered duplicate because Endpoint/123 record already exists in Outbox

**Comment by DavidBoike** [comment]
This is just a V6 pre-release bug, correct?

Sounds like the TimeoutStorage pipeline should not be doing outbox dedupe as it's logically not processing the message, invoking handlers, etc.

**Comment by weralabaj** [comment]
Yes.

**Comment by danielmarbach** [comment]
I think this highlights again the flaw of our satellite approach.
Satellites should be really raw and not reusing
TransportReceiveToPhysicalMessageProcessingConnector

**Comment by weralabaj** [comment]
One thing we weren't sure about with Tomasz is how the v6 implementation is different from v5. It also uses single storage right? How does it differentiate between "double-processing" Timeout message (which in this case is expected) and normal message?

**Comment by DavidBoike** [comment]
@weralabaj not sure I understand.

In V5 I don't believe satellites used the pipeline. They were just given a TransportMessage and everything else was up to the satellite. Here's the [TimeoutMessageProcessor](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutMessageProcessor.cs) satellite in master.

So as far as Outbox is concerned, it's only processing messages bound for handlers.

**Comment by andreasohlund** [comment]
>Satellites should be really raw and not reusing
TransportReceiveToPhysicalMessageProcessingConnector

Agreed, the satellites should supply the raw [`Func<PushContext, Task> pipe`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/IPushMessages.cs#L14). There is no need for a pipeline in satellites. (cc @janovesk , @SzymonPobiega )

**Comment by weralabaj** [comment]
Stupid question - doesn't mean it'll take a lot of time to fix it (significant changes)?

**Comment by timbussmann** [comment]
> There is no need for a pipeline in satellites.

Not sure if I agree with this. Retry mechanisms on the satellites also work with behaviors (=pipeline). But satellites definitely should use a very primitive pipeline.

**Comment by SzymonPobiega** [comment]
> There is no need for a pipeline in satellites.

I strongly disagree with that statement. The bug is that we (probably I) reused the connector where I should have cut the pipeline even before that connector. Using pipeline has two benefits IMO:
 * Reusing same concepts (not introducing new abstractions)
 * Providing a framework for structuring satellite code a bit. Otherwise we would end up with one huge class that handles both retries and actual business logic for timeouts

**Comment by danielmarbach** [comment]
@SzymonPobiega my point was we should have a dedicated `SatelliteToPhysicalMessageProcessingConnector`

**Comment by SzymonPobiega** [comment]
@danielmarbach :+1:

**Comment by SzymonPobiega** [comment]
Should I add this to the satellite API adjustments PR?

**Comment by danielmarbach** [comment]
I don't think you should. Different context = different PR

**Comment by SzymonPobiega** [comment]
@danielmarbach here you are: https://github.com/Particular/NServiceBus/pull/3516

**Comment by SzymonPobiega** [comment]
Should I now close it?

**Comment by danielmarbach** [comment]
When the PR is merged, then yes

**Comment by andreasohlund** [comment]
@tmasternak @weralabaj can you verify and close this one?

**Comment by weralabaj** [comment]
Fix verified in https://github.com/Particular/docs.particular.net/pull/1312. I'm closing this issue.
