### ISSUE TITLE
V6: Unable to use a different name for the satellite queue name if different than the endpoint name

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3505]
Since we have obsoleted `ISatellite` interface in v6, I was trying to see how to use the pipeline in v6 in lieu of the ISatellite and I hit some roadblocks. We need to have proper guidance in the Upgrade Guide. We have an [issue open for this](https://github.com/Particular/docs.particular.net/issues/532#issuecomment-153509376). My goal was to get enough details so I can document this in the Upgrade Guide. 

In v5, if someone wanted to use the Satellite, 
- they'd implement ISatellite interface
- Provide an input queue address
- Specify what needs to happen when a message is received in the Handle method. 
See: https://github.com/indualagarsamy/NSBSatelliteMigration/blob/master/v5/MySatellite.cs

In v6
- Need to implement a feature class
- In the feature Setup class, need to invoke the AddSatellitePipeline method on the context
- Create a new behavior which implements the PipelineTerminator. 
See: https://github.com/indualagarsamy/NSBSatelliteMigration/blob/master/v6/MySatelliteFeature.cs

Problems:
- In v5, I could specify any queue as the satellite queue. However it looks like in v6, the satellite's address is derived from the endpoint's name. The qualifier is used to extend to the name. For example, if the endpoint's name is "MySatellite" and the qualifier is "targetQueue", the satellite queue will be "MySatellite.targetQueue". However what if my satellite is a queue called "SomeDestination" ? 
- The implementation in v6 seems to far more complex.

Repro:
https://github.com/indualagarsamy/NSBSatelliteMigration

**Comment by andreasohlund** [comment]
@indualagarsamy can we close this given #3506 ?

**Comment by danielmarbach** [comment]
:+1: for closing as soon as @indualagarsamy verified the API changes

**Comment by indualagarsamy** [comment]
@andreasohlund @danielmarbach - I verified the new overload. Closing this issue.
