### ISSUE TITLE
IConfigureTestExecution.Cleanup() no longer called

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#3512]
I was running into some issues with the RabbitMQ acceptance tests, when I discovered that `Cleanup()` wasn't being called between tests to purge the queues.

It looks like #3433 ending up breaking this since the `SettingsHolder` is now cleared when the endpoint is stopped. 

The acceptance test framework currently looks for `IConfigureTestExecution` instances to call `Cleanup()` on them after the endpoint has stopped, which means they've already been removed:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs#L174

It doesn't seem to make sense to try and move the cleanup call to before the endpoint has been stopped, so does that mean we should remove the collection clear on the `SettingsHolder`?

Since the main reason for the #3433 change was to make sure the `TransportInfrastructure` is disposed if it implements `IDisposable`, perhaps we should make that more explicit vs. trying to dispose everything in the `SettingsHolder`?

**Comment by danielmarbach** [comment]
I would rather explore a way so that we don't need to pass those instances
over the settings

On Thursday, February 25, 2016, Brandon Ording <notifications@github.com>
wrote:

> I was running into some issues with the RabbitMQ acceptance tests, when I
> discovered that Cleanup() wasn't being called between tests to purge the
> queues.
>
> It looks like #3433 <https://github.com/Particular/NServiceBus/pull/3433>
> ending up breaking this since the SettingsHolder is now cleared when the
> endpoint is stopped.
>
> The acceptance test framework currently looks for IConfigureTestExecution
> instances to call Cleanup() on them after the endpoint has stopped, which
> means they've already been removed:
>
>
> https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs#L174
>
> It doesn't seem to make sense to try and move the cleanup call to before
> the endpoint has been stopped, so does that mean we should remove the
> collection clear on the SettingsHolder?
>
> Since the main reason for the #3433
> <https://github.com/Particular/NServiceBus/pull/3433> change was to make
> sure the TransportInfrastructure is disposed if it implements IDisposable,
> perhaps we should make that more explicit vs. trying to dispose everything
> in the SettingsHolder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3512>.
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by danielmarbach** [comment]
I have an idea how to fix this. Working on a spike

**Comment by danielmarbach** [comment]
@bording Linked the PR

**Comment by danielmarbach** [comment]
Done as part of https://github.com/Particular/NServiceBus/pull/3514
