### ISSUE TITLE
Stop using namespaces for our test projects

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3526]
I recently had a discussion with @danielmarbach about removing the NS all together for our tests since they don't provide any value. 

https://github.com/Particular/NServiceBus/pull/3523#issuecomment-190081070

Arguably they cause some harm:

* 3 extra lines in each file
* Allows us to be sloppy with test names since we can have a "When_publishing_a_message" in more than one place

@timbussmann brought up the issue with tooling since file create new will add the default namespace (vs require it to be non "" ). And things like "R# adjust namespace" will add it back.

Thoughts? 

cc @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
what if we use an entirely non-core-related namespace e.g. "AcceptanceTests" (no sub-namespaces for folders). This would more accurately mirror how user code would look like since we also have the same namespace imports on the tests. 

> More noise when moving files btw "capability" folders since the NS has to be changed

As in the core, folders shouldn't influence the NS?

**Comment by andreasohlund** [comment]
>As in the core, folders shouldn't influence the NS?

Good point, I withdraw that argument!

**Comment by danielmarbach** [comment]
I'm on the fence. I like the naming of tests argument which makes me lean towards :+1: for ditching the namespaces

**Comment by mauroservienti** [comment]
Can this in any way affect external users? Most of them simply don't know that a namespace is an optional and not mandatory thing

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers We haven't addressed this in the guidelines yet. I propose we close this issue since we have no good guidance for namespaces and the test namespaces will reflect these guidances as well.

**Comment by andreasohlund** [comment]
Well we have some guidance now? https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/namespaces.md

We could add a section for tests?

**Comment by danielmarbach** [comment]
> we have no good guidance for

Sorry typo! I wanted to write
> we have now

**Comment by bording** [comment]
> We could add a section for tests?

If anything, we could add something that makes it clear that test projects should follow the same rules.

Looking at the document, I would think they would need to follow the downstream section.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers I'm leaning toward keeping the tests & namespaces as is for now. I don't see much value gained by changing the namespace rules and we haven't even come up with some better rules (I don't think we should remove the namespaces). Should we close this?
