### ISSUE TITLE
When_timeout_storage_is_unavailable_temporarily takes 45 seconds to run

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3531]
Due to the stop [criteria](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs#L27)

We need to find a better way

@colin-higgins you introduced this, any ideas?

**Comment by danielmarbach** [comment]
Closed in favour of https://github.com/Particular/NServiceBus/issues/4361
