### ISSUE TITLE
Throw `InvalidOperationException` with a meaningful message when handler or saga returns null instead of a task.

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3533]
Outcome of [Null task handlig](https://github.com/Particular/NServiceBus/issues/3486)

```
public Task Handle(MyCommand message, IMessageHandlerContext context)
{
    return null;
}
`
```

something like

```
throw new InvalidOperationException("Please return either a Task, a completed Task or mark the method { methodInfo } as async")
```

### Status

* [ ] Particular/NServiceBus Pull Request: #3570 - Pull updated with revisions
* [ ] Particular/docs.particular.net Pull Request: [#1288](https://github.com/Particular/docs.particular.net/issues/1288) - WIP / Revisions Requested

**Comment by andreasohlund** [comment]
:+1: do include IWantToRunWhenTheBusStartsAndStops as well since we need to move it anyway

**Comment by danielmarbach** [comment]
@andreasohlund done

**Comment by danielmarbach** [comment]
@boblangley will be working on this. I'm a member of this TF as well.

**Comment by boblangley** [comment]
@danielmarbach @andreasohlund 

I looked through the public interfaces and came up with this other list. Here are ones I can recommend to include right away:

- IMutateIncomingMessages
- IMutateOutgoingMessages
- IMutateIncomingTransportMessages
- IMutateOutgoingTransportMessages
- IManageUnitsOfWork

What about these ones advanced users or downstream packages may implement?:

- ICriticalErrorContext
- IDataBus
- IPersistTimeouts
- IQueryTimeouts
- IDeduplicateMessages
- INeedToInstallSomething
- IBehavior
- PipelineTerminator
- CompletableSynchronizedStorageSession
- ISynchronizedStorage
- ISynchronizedStorageAdapter
- IOutboxStorage
- OutboxTransaction
- IUnicastRoute
- ISubscriptionStorage
- ISagaPersister
- ICancelDeferredMessages
- ICreateQueues
- IDispatchMessages
- IManageSubscriptions
- IPushMessages

**Comment by danielmarbach** [comment]
I see value in


- IHandleMessages
- IHandleTimeouts
- All overridable saga members
- Sagas
- IWantToRunWhenTheBusStartsAndStops

Optionally (but let's the above do first)

- IMutateIncomingMessages
- IMutateOutgoingMessages
- IMutateIncomingTransportMessages
- IMutateOutgoingTransportMessages
- IManageUnitsOfWork

all other are really internal advanced extension points. I don't see the value there.

**Comment by andreasohlund** [comment]
:+1:

**Comment by boblangley** [comment]
Added doco [pull request](https://github.com/Particular/docs.particular.net/pull/1288) as well.

**Comment by mikeminutillo** [comment]
Other than the optional items mentioned by @danielmarbach above, is there any more to do here beyond waiting for the associated PRs to be reviewed and merged by the respective maintainers groups? Everything in the Plan of Attack is checked off.

**Comment by danielmarbach** [comment]
@mikeminutillo the work is done on the PR. There is a last decision we need to take which is discussed on the PR. We close this issue when the PRs are merged

**Comment by boblangley** [comment]
I updated the description with status:

Particular/NServiceBus pull request has revisions requested
Particular/docs.particular.net pull request is still WIP and has not been updated since it was created. Some review has been done but has not been incorporated.

**Comment by boblangley** [comment]
>I'm good with trying an approach which doesn't rely on reflection (and provides a bit less information). If we see that doesn't help enough, we should use the Func<string> approach.

I pushed the commit up pulling out the strings / reflection. I will squash if we decide this is good enough. If not the `Func<string>` change is quick.

This does the bare minimum, it gives an exception message that can quickly identify the problem with some log diving. This will most commonly be a develop time problem in any case.

Personally I think this combined with some [doco](https://github.com/Particular/docs.particular.net/issues/1288) is good enough.
