### ISSUE TITLE
`PendingTransportOperations` should be thread-safe

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3539]
`PendingTransportOperations` get added by the transport receive behavior and pending transport operations are enqueued when no immediate dispatch is used. Since a user could potentially write inside the handler

```
var t1 = context.Send();
...
var tN = context.Send();

return Task.WhenAll(t1,...,tN);
```

adding pending transport operations should be safe even under concurrent access. 

Since `PendingTransportOperations` is using a list internally and the `Add` operation is not safe for concurrency we could risk ending up seeing the following exception 

```
  ----> System.IndexOutOfRangeException : Index was outside the bounds of the array.
at System.Collections.Generic.List`1.Add(T item)
`` 
You can simulate this (although not really accurate) with

```
        [Test]
        public void PendingTransportOperationsThreadSafety()
        {
            var list = new PendingTransportOperations();
            Parallel.For(0, 10000000, i =>
            {
                list.Add(new TransportOperation());
            });
        }
```

Thoughts?

**Comment by andreasohlund** [comment]
:+1 to fix

**Comment by danielmarbach** [comment]
@boblangley will be working on this. I'm a member of this TF as well.

**Comment by boblangley** [comment]
Rebased with some utilization changes.
