### ISSUE TITLE
Why `PauseAfterReceiveFailure(Timespan)` is obsoleted?

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus#3544]
In V5 we had PauseAfterReceiveFailure(Timespan) parameter for CircuitBreaker. CircuitBreaker was public and used e.g. in SQL Server transport.

In V6 CircuitBreaker was made internal and the parameter was removed. Why?

TODO: Document answer in upgrade guides ("Main" upgrade guide and SQL Server transport one).

**Comment by andreasohlund** [comment]
That parameter is not used in the core. If sql wants it we should copy paste the v5 impl over to the sqltransport

**Comment by danielmarbach** [comment]
We made a conscious decision that core should not be a utility library.

@andreasohlund we need to write this down in the PD guidelines

**Comment by danielmarbach** [comment]
@andreasohlund she would need to copy paste the v6 async version and reintroduce that parameter

**Comment by andreasohlund** [comment]
>we need to write this down in the PD guidelines

Agreed, are U doing it? :)

**Comment by danielmarbach** [comment]
@andreasohlund your wish is my command!

**Comment by weralabaj** [comment]
> We made a conscious decision that core should not be a utility library.

Agreed, but I know why it was removed in SQL transport - because it was removed from Core and we copied it. But I don't know why it was removed in core? How is that different then from SQL Circuit Breaker?

**Comment by andreasohlund** [comment]
We didn't seem to need to adjust is and hardcoded it to 1s https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs#L43

I guess we called YAGNI on it?

**Comment by weralabaj** [comment]
Fair enough, thanks.

**Comment by danielmarbach** [comment]
Close it?
