### ISSUE TITLE
review obsoletes for usages of "Bus"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3547]

**Comment by distantcam** [comment]
@SimonCropp Please provide more context.

Is this for adding obsoletes of old bus methods?
What should we do when we find a usage of "bus"?

**Comment by SimonCropp** [comment]
search for bus in obsolete messages

**Comment by danielmarbach** [comment]
@SimonCropp I agree with @distantcam at least a sentence in the description of this issue would be nice ;)
