### ISSUE TITLE
remove incorrect mentions of add-NServiceBusAuditConfig

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3548]
eg https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Audit/AuditConfigReader.cs#L73

**Comment by petersgiles** [comment]
> "Endpoint auditing is configured using the registry on this machine, ensure that either the Set-NServiceBusLocalMachineSettings cmdlet has been run on the target deployment machine or specify the QueueName attribute in the AuditConfig section in the app.config file. To quickly add the AuditConfig section to the app.config, in Package Manager Console type: add-NServiceBusAuditConfig."

What should it be?

**Comment by andreasohlund** [comment]
@petersgiles I think this is a great opportunity to validate our doco, go through http://docs.particular.net/nservicebus/operations/auditing etc and propose a new wording based on what you can find there?

**Comment by SimonCropp** [comment]
and perhaps verify that the mention of it in the upgrade guide is consistent with the new guidance/exception message  http://docs.particular.net/search?q=add-NServiceBusAuditConfig

**Comment by SimonCropp** [comment]
@indualagarsamy also might have an idea of better wording

**Comment by petersgiles** [comment]
I'm thinking that wording should be along these lines

'Endpoint auditing is configured using the registry on this machine, see Particular Documentation for details on how to address this with your version of NServiceBus http://docs.particular.net/.'

Or is this too generic?

**Comment by SimonCropp** [comment]
i would drop the link

**Comment by indualagarsamy** [comment]
@petersgiles - what's the goal here? What do we want to tell the user?
That the current way of configuring is wrong? And we want to point them to the proper way?

**Comment by indualagarsamy** [comment]
If that's the case, how about something like:

Auditing on this endpoint is currently configured via the machine's Registry. The registry approach is no longer a recommended option. For more details, please refer to the Version 5 to 6 upgrade guide.

**Comment by petersgiles** [comment]
The upgrade doco doesn't tell them that its not recommended http://docs.particular.net/nservicebus/operations/auditing#machine-level-configuration

I made a change to the message based on removing `add-NServiceBusAuditConfig` now I'm confused, because I can totally see @indualagarsamy's point, the code says it's not recommended but the doco doesn't really state that its not...I don't have any context for why? 

//cc @Particular/nservicebus-maintainers

**Comment by indualagarsamy** [comment]
@petersgiles - see http://docs.particular.net/nservicebus/upgrades/5to6#visual-studio-powershell-helpers-removed

**Comment by petersgiles** [comment]
Yeah that's about the powershell helpers and the 5 to 6 doco is pretty clear about the decision about dropping the powershell config builder (it sounds like @SimonCropp's voice when I read it). 

What the code is talking about is machine level registry setting which it says is 'verboten' now

**Comment by petersgiles** [comment]
@SimonCropp should we put a warning about not using the registry on this page http://docs.particular.net/nservicebus/operations/auditing#turning-off-auditing given the code warns people that its a bad idea

**Comment by SimonCropp** [comment]
i fixed my dodgy language int he upgrade guide

**Comment by SimonCropp** [comment]
@petersgiles that sounds reasonable

**Comment by petersgiles** [comment]
So given that the log message has changed can we close this one then?

**Comment by SimonCropp** [comment]
@petersgiles can u link to the commit that changed the message?

**Comment by petersgiles** [comment]
https://github.com/Particular/NServiceBus/commit/3ddf2b2b062b383e3e6ea02d18fcf82afc1f3df0

**Comment by SimonCropp** [comment]
@petersgiles thanks
