### ISSUE TITLE
Incorrect "DefineEndpointName" and "EndpointVersion" in exception message?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3549]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/EndpointHelper.cs#L38
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/EndpointHelper.cs#L58

**Comment by petersgiles** [comment]
> "No endpoint name could be generated, specify a convention using Configure.DefineEndpointName()"

> "No version of the endpoint could not be retrieved using the default convention, specify a custom version using endpointConfiguration.EndpointVersion(version).");

What should they read?

**Comment by andreasohlund** [comment]
Didn't we remove `EndpointVersion` in v6?

**Comment by petersgiles** [comment]
@andreasohlund I think that's part of the problem. There should be something in the upgrade doco about that (written by the designers of the change) and then we can go through and make the relevant changes to advise people what to do here

**Comment by andreasohlund** [comment]
Seems like the core is only adding "EndpointVersion" to the settings dictionary but is not using it.

RavenDB seems to be using it though - https://github.com/search?l=&q=user%3Aparticular+%22EndpointVersion%22&ref=advsearch&type=Code&utf8=%E2%9C%93

@petersgiles I think you need to do some digging here

@johnsimons I have a faint memory that you and me talked about this?

**Comment by johnsimons** [comment]
not me @andreasohlund

**Comment by petersgiles** [comment]
@andreasohlund summarizing what @johnsimons told me.

The way DTC works needs to have a resourceManagerId you need to have an identifier to survive a transaction failure.

We want ensure that the correct version of the endpoint is involved in a transaction. The example would be that if you were to upgrade an endpoint (side by side) the DTC would know which is the correct version and be able to recover properly.

In nsb.ravendb it is used like this.

``` C#
 var resourceManagerId = settings.Get<string>("NServiceBus.LocalAddress") + "-" + settings.Get<string>("EndpointVersion");
            store.ResourceManagerId = DeterministicGuidBuilder(resourceManagerId);
```
So for EndpointVersion it seems like a mistake to have dropped it in v6

**Comment by andreasohlund** [comment]
We actually have to stop using the `EndpointVersion` in ravendb to avoid data loss on upgrades

https://github.com/Particular/NServiceBus.RavenDB/issues/178 (cc @DavidBoike )

So I'm :+1: for removing the endpointversion "left overs" in the core

**Comment by petersgiles** [comment]
@andreasohlund I don't know how to proceed here. It looks like you and @DavidBoike have a deeper understanding of the problem and what these exception messages should say. Feel free to take this and run with it

**Comment by andreasohlund** [comment]
This one will be handled if we do https://github.com/Particular/NServiceBus/issues/3549 since then the endpointhelper class is gone

**Comment by DavidBoike** [comment]
@andreasohlund This issue **is** 3549. What case did you mean to link to?

**Comment by andreasohlund** [comment]
Duh, I mean't https://github.com/Particular/NServiceBus/pull/3597
