### ISSUE TITLE
Consider getting rid of IReadOnlyCollection, IList, IReadOnlyDictionary on the message paths

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3558]
While doing other things I let two benchmarks run on my machine to compare performance and garbage collection behavior with IReadOnlyDictionary and IReadOnlyList. Looking at the result below, should we consider getting rid of these interfaces in the message handling paths?

```ini
BenchmarkDotNet-Dev=v0.9.1.0+
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz, ProcessorCount=8
Frequency=2728069 ticks, Resolution=366.5596 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0

Type=Framework_DictionaryVsIReadOnlyDictionary  Mode=Throughput  

```
                         Method |         Median |        StdDev | InitialSize | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
------------------------------- |--------------- |-------------- |------------ |------ |------ |------ |------------------- |
          **DictionaryEnumeration** |     **22.7423 ns** |     **2.8235 ns** |           **0** |     **-** |     **-** |     **-** |               **0.00** |
 IReadOnlyDictionaryEnumeration |     45.7276 ns |     4.1545 ns |           0 |  1.97 |     - |     - |              23.66 |
          **DictionaryEnumeration** |     **37.1876 ns** |     **4.0774 ns** |           **1** |     **-** |     **-** |     **-** |               **0.00** |
 IReadOnlyDictionaryEnumeration |     66.3751 ns |     6.5084 ns |           1 |  2.14 |     - |     - |              25.51 |
          **DictionaryEnumeration** |     **69.7049 ns** |     **6.9562 ns** |           **5** |     **-** |     **-** |     **-** |               **0.00** |
 IReadOnlyDictionaryEnumeration |    163.2822 ns |    14.9492 ns |           5 |  1.55 |     - |     - |              27.23 |
          **DictionaryEnumeration** |    **127.2260 ns** |    **10.6103 ns** |          **10** |     **-** |     **-** |     **-** |               **0.01** |
 IReadOnlyDictionaryEnumeration |    271.1730 ns |    26.3795 ns |          10 |     - |     - |     - |              27.30 |
          **DictionaryEnumeration** |    **994.7732 ns** |    **88.6415 ns** |         **100** |     **-** |     **-** |     **-** |               **0.18** |
 IReadOnlyDictionaryEnumeration |  2,095.0940 ns |   267.6076 ns |         100 |     - |     - |     - |              27.79 |
          **DictionaryEnumeration** |  **9,594.3194 ns** |   **813.1986 ns** |        **1000** |     **-** |     **-** |     **-** |               **3.78** |
 IReadOnlyDictionaryEnumeration | 20,188.7690 ns | 1,923.5481 ns |        1000 |     - |     - |     - |              38.45 |

```ini
BenchmarkDotNet-Dev=v0.9.1.0+
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz, ProcessorCount=8
Frequency=2728069 ticks, Resolution=366.5596 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0

Type=Framework_ListVsIReadOnlyCollection  Mode=Throughput  

```
                         Method |         Median |        StdDev | InitialSize | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
------------------------------- |--------------- |-------------- |------------ |------ |------ |------ |------------------- |
 **IReadOnlyCollectionEnumeration** |     **24.7351 ns** |     **2.9765 ns** |           **0** | **15.17** |     **-** |     **-** |              **19.56** |
                ListEnumeration |     16.0834 ns |     1.9000 ns |           0 |     - |     - |     - |               0.00 |
 **IReadOnlyCollectionEnumeration** |     **38.0020 ns** |     **3.8209 ns** |           **1** | **14.50** |     **-** |     **-** |              **18.76** |
                ListEnumeration |     18.2782 ns |     2.6628 ns |           1 |     - |     - |     - |               0.00 |
 **IReadOnlyCollectionEnumeration** |     **87.0158 ns** |     **8.2320 ns** |           **5** | **11.89** |     **-** |     **-** |              **19.40** |
                ListEnumeration |     31.3169 ns |     5.6732 ns |           5 |     - |     - |     - |               0.00 |
 **IReadOnlyCollectionEnumeration** |    **163.9335 ns** |    **12.3794 ns** |          **10** |  **3.69** |     **-** |     **-** |              **17.64** |
                ListEnumeration |     64.5294 ns |     9.4158 ns |          10 |     - |     - |     - |               0.00 |
 **IReadOnlyCollectionEnumeration** |  **1,205.1754 ns** |   **119.5672 ns** |         **100** |     **-** |     **-** |     **-** |              **19.51** |
                ListEnumeration |    470.3594 ns |    48.7333 ns |         100 |     - |     - |     - |               0.03 |
 **IReadOnlyCollectionEnumeration** | **11,452.6509 ns** | **1,524.0866 ns** |        **1000** |     **-** |     **-** |     **-** |              **20.62** |
                ListEnumeration |  3,717.9186 ns |   866.1660 ns |        1000 |     - |     - |     - |               0.69 |

**Comment by timbussmann** [comment]
Interesting data :+1: 

I'm ok with replacing on internal structures but I think they still make sense on public APIs. It's probably still better to use the slightly slower (we're talking ns here) read only collections/interfaces than using more memory to clone collections when we really want to avoid accidental mutation?

**Comment by andreasohlund** [comment]
What's the action points? Add this to "design guidelines"?

**Comment by danielmarbach** [comment]
It seems we don't agree yet fully on this one. Should we have a quick conversation at the sync and then decide where to put the decision?

**Comment by danielmarbach** [comment]
Added it to the maintainer sync topics

**Comment by danielmarbach** [comment]
Raised a PR https://github.com/Particular/NServiceBus/pull/4250
