### ISSUE TITLE
Version 6 - Fix the IManageMessageFailures Obsolete message

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3563]
The `IManageMessageFailures` extension is now obsolete for Version 6.

The obsolete message says:
IManageMessageFailures is no longer an extension point. If full control over what happens when a message fails (including retries) is required then override the MoveFaultsToErrorQueue behavior. To get notified when messages are being moved use BusNotifications.Errors.MessageSentToErrorQueue.Subscribe(e=>{}) 

However, we have a problem with replacing existing behaviors. See #3574 for more details. 

Rather than replace the existing behavior, as @andreasohlund suggested, adding a new behavior in the pipeline which offers the user much better control of message processing is better. 

The suggested steps are in here: https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_6/CustomErrorHandlingBehaviour.cs

- [x] [Update the upgrade to the 5to6 guide including this code as a snippet](https://github.com/Particular/docs.particular.net/pull/1300)
- [x] [Change the obsolete message to reflect our findings here](https://github.com/Particular/NServiceBus/pull/3575)

Related PRs:
https://github.com/Particular/docs.particular.net/pull/1300/
https://github.com/Particular/NServiceBus/pull/3575

---
Investigation of migrating IManageMessageFailures

The `IManageMessageFailures` extension is now obsolete for Version 6.

The obsolete message says:
IManageMessageFailures is no longer an extension point. If full control over what happens when a message fails (including retries) is required then override the MoveFaultsToErrorQueue behavior. To get notified when messages are being moved use BusNotifications.Errors.MessageSentToErrorQueue.Subscribe(e=>{}) 

I followed the steps suggested in the obsolete message, however the custom behavior is not getting invoked. 
@Particular/nservicebus-maintainers - Can you please tell me what I am doing wrong? 
See repro: https://github.com/indualagarsamy/CustomFaultManagerMigration/tree/master/Version_6

Related issue: 
https://github.com/Particular/docs.particular.net/issues/1281

**Comment by indualagarsamy** [comment]
Also for the [serialization failed scenario](https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_5/CustomFaultManager.cs#L7-L10), in v6 simply check the exception type?

**Comment by andreasohlund** [comment]
How about adding a behavior to the physical incoming pipeline that does a try catch + what ever the user want to do with the message?

**Comment by timbussmann** [comment]
First, you're using the wrong id to replace the behavior, it should be `"MoveFaultsToErrorQueue"`

The bigger problem though is the fact, that you can't replace a behavior which is registered in a `Feature` from `INeedInitialization` because initialization is executed before the features, therefore your custom registration is overwritten again.

The even bigger problem is, even with a Feature there is currently no way to tell that your feature runs AFTER the `StoreFaultsInErrorQueue` behavior. Which means you probably still end up running before the behavior setup you want to replace. Since `StoreFaultsInErrorQueue` there seems to be no way to replace the behavior correctly. I tested it with making the  `StoreFaultsInErrorQueue` feature public and it worked with a custom feature using `DependsOn<StoreFaultsInErrorQueue>()`.

**Comment by indualagarsamy** [comment]
@timbussmann - I used it because I saw this code:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs#L9

I used the type name of the behavior. This goes to the confusion of well known Ids.

**Comment by indualagarsamy** [comment]
@timbussmann - Regarding your comment here:
https://github.com/Particular/NServiceBus/issues/2783#issuecomment-193658606

> Replacing the MoveFaultsToErrorQueueBehavior is quite a drastic change to NServiceBus. I think replacing steps is always for very special use cases and for advanced users not a common usage scenario. From that perspective It doesn't seem to bad to use magic strings (or move them to the behavior e.g. MoveFaultsToErrorQueueBehavior.StepId).

However, that's what we suggest in our obsolete message for IManageMessageFailures. Again, see previous usage for IManageMessageFailures, it wasn't exactly a complicated thing to do. It was easy and yet it gave people the customization they wanted.

**Comment by andreasohlund** [comment]
@indualagarsamy did you try my idea to just add a behavior to the physical incoming pipeline?

**Comment by indualagarsamy** [comment]
@andreasohlund - no. I'll try that and see how that goes. My goal is to be able to check for both the SerializationFailure and all the other failures like what the previous interface provided. What you suggested might be an easier and better approach. I'll let you know if i run into any snags.

**Comment by andreasohlund** [comment]
You should be able to catch serialization failed since (deserialization) happens later in the pipeline.

**Comment by indualagarsamy** [comment]
@andreasohlund - @petersgiles had a go at this. Here's the code:
https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_6/CustomErrorHandlingBehaviour.cs
However, need to tweak this so that FLRs happen, but not SLRs (to mimic the same behavior of IManageMessageFailures in Version 5) - ideas?

Also what about the issues that @timbussmann mentioned earlier? regarding replacing behaviors and the current problems? What's the way forward?

**Comment by andreasohlund** [comment]
>to mimic the same behavior of IManageMessageFailures in Version 5

I'd say we could decide on changing the behavior to what makes sense if we just document it properly in the upgrade guide.

>However, need to tweak this so that FLRs happen

Just rethrow to have the FLR kick in?

>but not SLRs 

Add a custom retry policy to turn off the retries for the given ex?

**Comment by petersgiles** [comment]
@indualagarsamy and I worked through this using @timbussmann's fork as an example. 
The result is this behavior. 

The user can control SLR behavior by disabling SLR in the endpointconfig...a good thing :)

https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_6/CustomErrorHandlingBehaviour.cs

You can see the deserialization being caught in the example

- [ ] We are planning an upgrade to the 5to6 guide including this code as a snippet 
- [ ] We also need to change the obsolete message to reflect our findings here

`IManageMessageFailures is no longer an extension point. To achieve a similar behavior please review the version 5 to 6 upgrade guide`

**Comment by indualagarsamy** [comment]
@andreasohlund - Can I change this issue to replacing the obsolete message for the IManageMessageFailure? And thanks for your suggestion. I like this solution better than replacing the existing behavior. As a user they can still get better control of if they want to execute this custom behavior after SLR or no SLR at all.

**Comment by andreasohlund** [comment]
>Can I change this issue to replacing the obsolete message for the IManageMessageFailure?

I see that you already did :)

Issues are cheap so my default move would be to not reuse issues but instead close and link to new one. In this case perhaps just a pull with the next text + close this one?

**Comment by indualagarsamy** [comment]
@andreasohlund - There's an associated pull with the new obsolete text and tests are good.
I have a doco PR that's almost good enough in progress. Can you please close this issue once that PR is merged?

**Comment by timbussmann** [comment]
@indualagarsamy @petersgiles would it make sense to have a dedicated page about "handling failing messages" which describes the different approaches and options (before/after slr/flr, rollback, swallow exception, rethrow exception)?

**Comment by petersgiles** [comment]
@timbussmann :+1:

**Comment by andreasohlund** [comment]
@indualagarsamy  https://github.com/Particular/NServiceBus/pull/3575 is merged so I'm closing this
