### ISSUE TITLE
Memory leak in InMemoryGatewayDeduplication results in OutOfMemoryException

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus#3564]
[`InMemoryGatewayDeduplication`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs) is an internal class, which makes [`DeleteDeliveredMessages`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs#L36) inaccessible

`DeleteDeliveredMessages` is never referenced internally by NSB

**Comment by danielmarbach** [comment]
@chrisbednarski Unfortunately this seems to be a leftover from a redesign which hasn't been cleaned up. Since we do not recommend to use the `InMemory*` (Persistence, Gateway...) in production can you explain why you'd require this functionality?

**Comment by chrisbednarski** [comment]
We're using it in production. The process that self-hosts NSB and the gateway
- is never scaled out (so the dedup storage doesn't need to be shared between processes)
- uses a custom gateway channel, a polling channel, where the roles are reversed, (ie. the logical sender is polled for messages by the receiver - pull instead of push)
- needs to manage memory well, memory footprint is important
- needs to stay running 24/7 - up-time is important

**Comment by danielmarbach** [comment]
@chrisbednarski @janovesk will look into this.

**Comment by danielmarbach** [comment]
ping @janovesk

**Comment by janovesk** [comment]
Is this still relevant for you, @chrisbednarski? What version are you running on?

**Comment by chrisbednarski** [comment]
yes, we're using 4.7.12

**Comment by timbussmann** [comment]
@janovesk you seem to be assigned to this. How do we proceed with this? Are you planning on addressing this? I think we need to take into account that v4 is no longer supported? Is this also an issue in v5/v6?

**Comment by janovesk** [comment]
Well.. since v4 is no longer supported and the edge case-iness :) of using in-memory deduplication I'm a bit hesitant to do much here.  

@chrisbednarski, do you have a workaround that is acceptable until you upgrade to v5/v6?

**Comment by chrisbednarski** [comment]
yes, would like to remove the workarounds when we migrate to v5/v6

the in-memory implementations are serving us well for integration testing as well

**Comment by timbussmann** [comment]
so this issue has been around for a while without any actions. I think there is no chance that this is going to be addressed in v4 or v5 as this doesn't qualify as a critical bug.

Looking at the inmemory as well as other implementations, it looks like the gateway storage is a source of memory leaks or constantly growing databases as there is no cleanup mechanism. I think this is the real issue and we should raise an issue in the gateway to handle this properly instead of forcing users to handle this themselves. Thoughts @Particular/nservicebus-maintainers @janovesk ?

**Comment by andreasohlund** [comment]
@chrisbednarski is this still an issue for you?

**Comment by chrisbednarski** [comment]
Not so much. we've injected our own implementations where required. Still on version 4.* and likely not moving forward

**Comment by andreasohlund** [comment]
Got it, closing this issue in favor of https://github.com/Particular/NServiceBus.Gateway/issues/92

**Comment by ramonsmits** [comment]
Reopening, in memory persister is part of core.

**Comment by ramonsmits** [comment]
Issue is still  prevent in current supported versions:

- https://github.com/Particular/NServiceBus/blob/7.1.8/src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs


Method `DeleteDeliveredMessages` is not part of interface `IDeduplicateMessages` and will never be invoked.

**Comment by ramonsmits** [comment]
Will be fixed in 7.1.10 and 6.5.8
Will get a public config API in 7.2.0
