### ISSUE TITLE
Event duplication when subscribing for messages published by pre-6 endpoint

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3571]
There is an issue which causes events to be delivered to each instance (rather than to single instance) in following conditions:
 * MSMQ transport
 * Scaled-out endpoint with multiple instances deployed to different machines

The problem becomes a bit more important with the advent of V6 which makes it reasonable to deploy such configurations without the distributor (because of V6 sender-side distribution). Although the problem affects also V5 in that version distributor was advertised as *the only* scale-out solution for MSMQ so people would probably not deploy scaled-out endpoints without it.

What should we do with this problem?
 * Ignore (because it is not worse than V5) and add proper guidance to tell users that a V6 cluster requires a distributor to be able to communicate with pre-6 endpoints
 * Other solutions?

### Chosen solution

Document the problem: https://github.com/Particular/docs.particular.net/pull/1315

**Comment by SzymonPobiega** [comment]
@janovesk what do you think?

**Comment by timbussmann** [comment]
Just to verify based on your description:
Only when sending events to v5 msmq scaled-out endpoints without using the distributor?

In that case I'd challenge the v6 label.

**Comment by SzymonPobiega** [comment]
@timbussmann the problem is both in 5 and 6 but in V6 it will be easier to make a mistake since such a scaled-out distributor-less deployment will actually be usable. I think it requires an action as part of V6 release. The action can be as small as adding a huge `WARNING` in the doco.

**Comment by johnsimons** [comment]
:+1: to add huge warning to doco

**Comment by andreasohlund** [comment]
> add proper guidance to tell users that a V6 cluster requires a distributor to be able to communicate with pre-6 endpoints

That seems to be the way to go, can you raise a docs pull/issue and close this one @SzymonPobiega ?
