### ISSUE TITLE
Found the empty `SendOptions` quite confusing

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3572]
**DOESN"T NEED TO BE DONE NOW**

A bit of feedback regarding the new v6 API.
I actually found the empty `SendOptions` quite confusing.
I was trying to send a message to a specific destination so my first instinct was:
```c#
context.Send(new MyMessage(), new SendOptions() { Destination = "blah" } ); // But there is no Destination property in SendOptions
```
So I scratch my head for a while, till I remember the love affair v6 has with extension methods, so I ended with:
```c#
context.Send(new MyMessage(), new SendOptions().SetDestination("blah") ); // But again does not work because SetDestination does not return this
```

So it seems that the only way to send a message to a specific destination is:
```c#
var sendOptions = new SendOptions();
sendOptions.SetDestination("blah");
context.Send(new MyMessage(), sendOptions);
```	
or
```c#
context.Send<MyMessage>("blah", myMessage => {});
```	

IMO, it would be nice to have the extension methods support fluent or have the old override:
```c#
context.Send("blah", new MyMessage());
```

**Comment by timbussmann** [comment]
While it's trivial to add extension methods which wrap 
```
var sendOptions = new SendOptions();
sendOptions.SetDestination("blah");
context.Send(new MyMessage(), sendOptions);
```

This sucks from a testing perspective, because we don't want to have dedicated `ExpectXyzOption` expectations. This assumes users know that we internally just use the extension method on SendOption when they want to verify that option was used. That's why I'm suggesting the approach in #3559 which in the end requires much less extension methods.

**Comment by danielmarbach** [comment]
We backtracked on doing https://github.com/Particular/NServiceBus/pull/3559 so I suggest we close this one as well.

**Comment by ppittle** [comment]
+1 SendOptions are confusing at first glance

**Comment by andreasohlund** [comment]
Closing this in favor of https://github.com/Particular/NServiceBus/issues/3763
