### ISSUE TITLE
When configured to use MSMQ as the persistence, endpoint throws an unfriendly exception

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3588]
## Who's affected

Version 6 users using MsmqPersistence without any other persistence configured.

## Symptoms

The endpoint throws the following exception:

*An exception of type 'Autofac.Core.Registration.ComponentNotRegisteredException' occurred in NServiceBus.Core.dll but was not handled in user code*

*Additional information: The requested service 'NServiceBus.Timeout.Core.IQueryTimeouts' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.*

*If there is a handler for this exception, the program may be safely continued.*

## Steps to repro
Configure an endpoint to use MSMQ Persistence and start the endpoint.

```c#
EndpointConfiguration endpointConfiguration = new EndpointConfiguration();
endpointConfiguration.EndpointName("Samples.EndpointWithMsmqStorage");
endpointConfiguration.UseSerialization<JsonSerializer>();
endpointConfiguration.UsePersistence<MsmqPersistence>();
endpointConfiguration.EnableInstallers();
endpointConfiguration.SendFailedMessagesTo("error");

IEndpointInstance endpoint = await Endpoint.Start(endpointConfiguration);
try
{
  Console.WriteLine("Press any key to exit");
  Console.ReadKey();
}
finally
{
  await endpoint.Stop();
}
```
## Workaround

Enable InMemoryTimeoutPersistence and/or InMemorySagaPersistence.

## Questions
Can we either
- Deprecate `MsmqPersistence`
or
- Clarify the exception better? 

**Related Documentation**: http://docs.particular.net/nservicebus/msmq/subscription-persistence

**Comment by danielmarbach** [comment]
That is an interesting one, since

        internal MsmqPersistence()
        {
            Supports<StorageType.Subscriptions>(s => s.EnableFeatureByDefault<MsmqSubscriptionPersistence>());
        }

The persistence feature explicitly says that it only supports subscriptions. So the core should at least check if you require additional persistence and give a meaningful exception message.

**Comment by andreasohlund** [comment]
Since MsmqPersistence isn't widely used and this will hit during development and doesn't affect the production stability of v6 I don't see this as a must have for v6, removing the v6 label and flagging this as a low impact bug. Fixing this will not be a breaking change.

**Comment by danielmarbach** [comment]
@andreasohlund I agree that we can fix this without a breaking change. But the bug has wider implications. You'd see the exact same exception when you'd enable another feature like sagas and you don't provide saga persistence. So any partially implemented persistence will result in an exception

**Comment by danielmarbach** [comment]
@indualagarsamy While I was doing the triage for this one I realized when can easily improve the situation. See the linked PR.
