### ISSUE TITLE
Even though Sagas are disabled, the endpoint expects Saga persistence to be configured

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3589]
NServiceBus Version: `6.0.0-unstable1663`

**Steps to Reproduce**
Configure an endpoint with just Subscription and timeout storage configured and explicitly disable the Sagas feature and start the endpoint, an exception regarding ISynchronizedStorage is thrown. 

If you add the `StorageType.Sagas`, then the endpoint starts successfully. 

```c#
EndpointConfiguration endpointConfiguration = new EndpointConfiguration();
endpointConfiguration.EndpointName("Samples.EndpointWithMsmqStorage");
endpointConfiguration.UseSerialization<JsonSerializer>();
endpointConfiguration.UsePersistence<InMemoryPersistence, StorageType.Subscriptions>();
endpointConfiguration.UsePersistence<InMemoryPersistence, StorageType.Timeouts>();
         
endpointConfiguration.DisableFeature<Sagas>();
endpointConfiguration.EnableInstallers();
endpointConfiguration.SendFailedMessagesTo("error");

IEndpointInstance endpoint = await Endpoint.Start(endpointConfiguration);
try
{
  Console.WriteLine("Press any key to exit");
  Console.ReadKey();
}
finally
{
  await endpoint.Stop();
}
```

**Exception details:**
*'Autofac.Core.Registration.ComponentNotRegisteredException' occurred in NServiceBus.Core.dll but was not handled in user code*

*Additional information: The requested service 'NServiceBus.Persistence.ISynchronizedStorage' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.*

*If there is a handler for this exception, the program may be safely continued.*

**Comment by SzymonPobiega** [comment]
The reason it fails is because in V6 the synchronized storage is initialized for each message being processed. I think this should be fixed by adding an entry in the upgrade guide.

**Comment by indualagarsamy** [comment]
@SzymonPobiega - Can you clarify what needs to be done in the upgrade guide?

**Comment by SzymonPobiega** [comment]
I suppose this fix by @WilliamBZA should fix this https://github.com/Particular/NServiceBus/pull/3594.

**Comment by andreasohlund** [comment]
@indualagarsamy can you verify?

**Comment by indualagarsamy** [comment]
@andreasohlund - will do. I'll update the issue or close it accordingly.

**Comment by indualagarsamy** [comment]
Tested with `6.0.0-unstable1776` and the endpoint starts up successfully without any exceptions.

**Comment by SzymonPobiega** [comment]
:tada: kudos to @WilliamBZA
