### ISSUE TITLE
Do not deploy unsupported packages to NuGet

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3592]
We should not deploy unsupported (e.g. source only) packages to NuGet. They are still available on the particular MyGet feed.

* NServiceBus.AcceptanceTests.Sources
* NServiceBus.ContainerTests.Sources
* NServiceBus.AcceptanceTesting

~~Should we also remove the acceptance testing framework (NServiceBus.AcceptanceTesting) from NuGet since it's also unsupported? There seem to be users using it in their projects so I'm not entirely sure.~~

**Comment by danielmarbach** [comment]
We never officially supported it. Those who decided to use it are on their
own. We can always point them to the myget feed.

**Comment by timbussmann** [comment]
@danielmarbach good with that. Adjusted title and description :+1:

**Comment by danielmarbach** [comment]
@SzymonPobiega can you help out here? Could we fix that in the creation of the deployment package, i.ex. have a exclude filter or something smarter?

**Comment by SzymonPobiega** [comment]
This step would have to be modified http://deploy.particular.net/app#/library/steps/ActionTemplates-37. I think the easiest way is to allow per-project-per-environment filter which would be applied in line 24. Then, for the `Production` environment of `NServiceBus` project we would filter out unwanted source packages.

**Comment by andreasohlund** [comment]
What are the cons with publishing to NuGet?

I actually like us publishing our acceptance tests so that we can say we follow semver from a api perspective but we also publicize our acceptance tests to prove that we don't break behavior as well.

Also 3:d party transports and persistence's should use the test suit, eg the SQS transport passes all our tests last time I checked.

**Comment by timbussmann** [comment]
closing this as it doesn't seem something causing any pain, so no need to tackle this atm.
