### ISSUE TITLE
Improved retry configuration API

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#3593]
This issue description is a brain dump of thinking behind unification of retry configuration API.

### Background

Currently recoverability mechanisms (FLR/SLR and moving to error queue) are all configured using independent APIs. We need a single API to define all recoverability concerns.

### Use cases

Here's a (possibly not complete) list of use cases covered by existing API that we must at minimum support with the new API:

- FLR
 - [Configure number of retries](http://docs.particular.net/nservicebus/errors/automatic-retries#first-level-retries-configuring-flr-through-iprovideconfiguration)
- SLR
 - [Enable / disable SLR](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-disabling-slr-through-code)
 - [Configure number of SLR attempts](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-configuration-slr-through-iprovideconfiguration)
 - [Configure time increase](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-configuration-slr-through-iprovideconfiguration)
 - [Define custom retry policy](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-custom-retry-policy)

### What the API might look like

Here's how the API might look like:

- FLR
 - Configure number of retries
```csharp
configuration.Retry
    .Immediately(7);
```
- SLR
 - Enable / disable SLR
```csharp
configuration.Retry
    .Immediately(7)
    .Only();
```
 - Configure number of SLR attempts
```csharp
configuration.Retry
    .Immediately(7)
    .ThenWaitAndRetry.Times(2);
```
 - Configure time increase
```csharp
configuration.Retry
    .Immediately(7)
    .ThenWaitAndRetry.Times(2).BackoffBy(TimeSpan.FromSeconds(10));
```
 - Define custom retry policy
```csharp
configuration.Retry
    .Immediately(7)
    .ThenWaitAndRetry.OnMessage(message => 
        if (message.NumberOfRetries >= 3) return TimeSpan.MinValue;
        return TimeSpan.FromSeconds(5);
    );
```

### External links

[Polly](https://github.com/App-vNext/Polly) has a very nice API to control retry policies.

**Comment by timbussmann** [comment]
regarding custom retry policy, this is a very good proposal from @mikeminutillo about the discussion around returning `TimeSpan.MinValue`:

> return `Retry.Immediately();` or `return Retry.After(timespan);` or `Retry.Never();` would signal intent better

**Comment by danielmarbach** [comment]
@MarcinHoppe can you roll up all retry-related issues in a Platform Dev issue? ping me if you want to get on a call and do it together.

**Comment by MarcinHoppe** [comment]
@danielmarbach I created a Platform Dev issue. Can you have a look and chime in?

**Comment by MarcinHoppe** [comment]
Superseded by Particular/V6Launch#69.
