### ISSUE TITLE
Autosubscribe for unicast should require explicit mappings

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3596]
In V5 we used to require routing information to be present when autosubscribing on unicast transports. It has changed since then. I did some archaeology and found [this](https://github.com/Particular/NServiceBus/commit/290f24c49042e73ae8fd7d3243aee2ccd028b03d) commit by @andreasohlund and [that](https://github.com/Particular/NServiceBus/commit/66d91e7a6a439717b1ae7856f81594704616dc6f) one by myself and @dvdstelt .

It seems like the three of us removed that flag and changed the behavior to not check the routing. This results in an exception being thrown when there is a handler for event `E` but there is no information on who publishes `E`. Is this the behavior we want to continue having in V6 or should we revert back to old V5 behavior?

**Comment by SzymonPobiega** [comment]
Marking it as V6 because it might be an accidental change we don't want to ship in V6.

**Comment by andreasohlund** [comment]
Here's how I believe it should work:

For events where there is a message handler:

Unicast: If there is a configured address => subscribe
Multicast: Always subscribe

Thoughts?

**Comment by SzymonPobiega** [comment]
@andreasohlund If we take V5 behavior out of the equations I would prefer to throw when there is a handler but no routing configured because the code expects the message but configuration is wrong. But given that in V5 the behavior was to silently ignore messages which have handlers but no corresponding routing, I am a bit on the fence.

**Comment by andreasohlund** [comment]
>But given that in V5 the behavior was to silently ignore messages which have handlers but no corresponding routing, I am a bit on the fence.

Lets align the current behavior to be backwards compat and raise a new issue to discuss throwing for eventhandlers with no config?

**Comment by andreasohlund** [comment]
@SzymonPobiega what happens on startup when the mappings are missing? exception?

**Comment by SzymonPobiega** [comment]
Yes, exception. I'll work on a PR to fix it.

**Comment by SzymonPobiega** [comment]
#3603 attempts to fix it.
