### ISSUE TITLE
Have the ability for transports to provide a supported list of transaction modes.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3598]
Based on the discussion in related Issue: https://github.com/Particular/NServiceBus/issues/3581

Currently, the core defines the following as [transport transaction modes](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/TransportTransactionMode.cs)

None (0)
ReceiveOnly (1)
SendsAtomicWithReceive (2)
TransactionScope (3)

An exception will be thrown if the user configures a transaction mode that is not supported by the transport. For example, If “TransactionScope” is set as the transaction mode when using RabbitMQ transport, the core will throw an exception.

The core assumes that when a transport says it supports a given mode, it supports all lesser modes. 
Example: If a transport says it supports, TransactionScope which is enum 3, the core assumes that 0, 1 and 2 are also supported by the transport.

https://github.com/Particular/NServiceBus/blob/5d8c6c03b6ae8815a800d1c560440e82004a484b/src/NServiceBus.Core/Transports/TransactionModeSettingsExtensions.cs#L27

A better API would be:
- The transport should specify a collection of modes that it supports. If the user-specified option isn’t on the supported list from the transport, then the core should throw a NotSupported exception.
- The transport shouldn’t have to make any assumptions about trying to match a lower transaction mode than what’s on the supported list.

**Comment by indualagarsamy** [comment]
@andreasohlund @bording @yvesgoeleven - I've raised this issue to have the transport provide a list of supported transaction modes. Please review this issue. I understand that it won't make it for v6.

**Comment by timbussmann** [comment]
can you add samples of our supported transports which do not support a "lower than supported" transaction mode to the description?

**Comment by andreasohlund** [comment]
>can you add samples of our supported transports which do not support a "lower than supported" transaction mode to the description?

Based on my discussions with @bording and  @yvesgoeleven all current transports supports all lower modes

**Comment by andreasohlund** [comment]
@indualagarsamy closing this, please reopen if you still thing this is worth pursuing
