### ISSUE TITLE
Align DateTime usage & switch to DateTimeOffset where necessary

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3601]
Background

http://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset

Two problems:

* We still have a few `DateTime.Now` calls
* We use `DateTime` and `DateTimeOffset` inconsistently

we currently have 92 usages of `DateTime` in the core. For the `DoNotDeliverBefore` extension method on `SendOptions` we already switched to `DateTimeOffset` but the `DoNotDeliverBefore` constraint doesn't expose a `DateTimeOffset` but a `DateTime` struct.

Methods like `RequestTimeout` on the sagas use `DateTime`.

Should we switch to `DateTimeOffset` on the public APIs as well as internal APIs?

We can argue this problem doesn't need to be solved as v6. I just want to highlight that our public API is not consistent and we should care about these details in major releases.

**Comment by timbussmann** [comment]
> For the DoNotDeliverBefore extension method on SendOptions we already switched to DateTimeOffset but the DoNotDeliverBefore constraint doesn't expose a DateTimeOffset but a DateTime struct.

The change to DateTimeOffset here was mainly to make sure users to not provide a time with Kind.Unknown which wouldn't allow us to determine whether it's already utc or not. Since we're always working with UTC internally I'm not really sure what the benefit over using DateTimeOffset is.

Can you give some examples where damage could be caused because of using DateTime? I'm not really sure we need to actively tackle the usage of DateTime (at least for the `DoNotDeliverBefore` path). What's the time format on headers?

**Comment by danielmarbach** [comment]
I have no real strong arguments. I'm all for consistency. 

From a framework perspective I have the feeling using a nonlocalized date time format is clearer. Users can always translate from their local time to the universal time.

**Comment by andreasohlund** [comment]
:+1: for DateTimeOffset which seems to be the SO favorite :) esp since we always want to deal with UTC times

http://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset

**Comment by timbussmann** [comment]
As essentially commented before, I think `DateTimeOffset` makes sense from an API perspective where users can provide dates to make sure we know how to translate that time to UTC. Since we internally always work with UTC, it shouldn't really matter whether we use `DateTime` or `DateTimeOffset`.

**Comment by danielmarbach** [comment]
Talked to @timbussmann, we verified our usages of `DateTime`. Where it matters we expose `DateTimeOffset` to the end-users. Internally we are consistently using `DateTime` and `DateTime.UtcNow` which is good enough at the moment since we don't need the additional offset information provided by `DateTimeOffset`. Yes it is not a pure usage as argument in https://github.com/Particular/NServiceBus/issues/3601#issuecomment-240630093 but good enough for now
