### ISSUE TITLE
Circuit breaker and critical errors are broken OOTB

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3612]
Ever since the 'circuit breaker' pattern is introduced it has been a serious pain for our customers that usually get into trouble when they are in production. Behavior and configuration is hidden and unstable by default.

Some observations:

* Circuit breakers by default set the bus instance in an unworkable state without our customers knowing.
* Circuit breaker values are hard if not impossible to configure as some cannot even be configure.
* When using the NServiceBus.Host it *crashes* the windows service requiring waiting for windows service recovery to kick in (at least 1 minute). 
* When self-hosting in IIS users can an `ObjectDisposedException` that can only be solved by recycling the application pool

The timeout circuit breaker period is AFAIK the only circuit breaker that is configurable but you cannot disable it or influence the 'failure' behavior.

Even when we refer our customers to supply a critical error callback action it's *very* hard to implement as basically the only option that you have is to 'shut down'. In real world environments most customers use DI so they *register a single instance* in their container.

* How will a customer be able to swap this if is wants to continue running?
* A critical error will dispose the container, the same container that is passed to NServiceBus! How can we dispose an external resource passed to us of which we should not control its lifespan.

IMHO NServiceBus should be stable by default and *not* exit / fail-fast due to a few errors and even if we do so, this behavior should not be hidden. It should be an explicit opt-in/out as you would not expect that a framework just 'kills' the application.

We should not underestimate how expensive it can be to 'restart' a whole application because we crashed it.

I would vote for a 'proper' circuit breaker implementation that instead of terminating would do a back-off and logging its state all the way information upfront what actions it is undertaking and in which time period.

In for example, the timeout poller the circuit breaker has a relation with the poll sleep interval. The circuit breaker could increase the poll interval. 

Based on the choice of the user the circuit breaker could just back off for ever.

Each hosting environment would want to react differently to these different circuit breakers. Some might want to disable them, some might want to exit, or throttle down, or wait for an external event, or notify a sysop but should never just quit the application unless the user explicitly would want to have this behavior.

The circuit breaker of choice should be configurable by the end-user. If we do not want to 'expose' the `CircuitBreaker` and / or `RepeatedFailuresOverTimeCircuitBreaker` then we should expose at least the `ICircuitBreaker` interface so users are able to supply a dummy for each component of choice or use a different kind of implementation that would use adaptive throttling.

## References

Configuration:

* http://docs.particular.net/nservicebus/hosting/critical-errors
* http://docs.particular.net/nservicebus/errors/critical-exception-for-timeout-outages

A few issues related to this. There are lots more of these and from now on I'll try and not forget to add these to this issue every time I see a related incident.

* https://github.com/Particular/NServiceBus/issues/1228
* https://groups.google.com/forum/#!topic/particularsoftware/VgXe9wHM0o4
* https://github.com/Particular/NServiceBus/issues/2085
* https://github.com/Particular/NServiceBus/issues/3542
* http://stackoverflow.com/questions/35443131/nservicebus-how-do-i-set-the-timeoutpersisterreceiver-timespan-in-config
* http://stackoverflow.com/questions/36022712/howto-increase-nservicebus-4-x-timeoutpersisterreceiver-circuit-breaker
* https://nservicebus.desk.com/agent/case/12882
* https://nservicebus.desk.com/agent/case/14633
* https://nservicebus.desk.com/agent/case/11599
* https://nservicebus.desk.com/agent/case/10083
* https://nservicebus.desk.com/agent/case/9229

**Comment by ramonsmits** [comment]
And another one: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/6dsZcWCxaiM/TMPV9UqGBAAJ

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers Decided to raise an issue to completely revamp/rethink the our approaches to critical error handling based on the existing issues. 

https://github.com/Particular/PlatformDevelopment/issues/746

Closing this one

**Comment by ramonsmits** [comment]
And another one: https://nservicebus.desk.com/agent/case/18026

**Comment by ramonsmits** [comment]
And another one bites the dust: http://stackoverflow.com/questions/39196276/how-to-create-sandpit-dynamics-crm-instance-on-azure%3E

**Comment by ramonsmits** [comment]
Another one bites the dust: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/IsdyI8kOhes/pG6VB6ZJAwAJ

**Comment by ramonsmits** [comment]
Yet again! https://groups.google.com/forum/#!topic/particularsoftware/uvaAkmS_TG4%5B1-25%5D

**Comment by timbussmann** [comment]
@ramonsmits that scenario doesn't sound like an issue with the circuit breaker but rather that we raven should prevent startup in the first place?

**Comment by ramonsmits** [comment]
@timbussmann I've spoken to the customer yesterday and he explained to me they sometimes have failing endpoints. This log file snippet was just for reference for the exception they were getting.

**Comment by ramonsmits** [comment]
And again... https://eu1.salesforce.com/500D000001J7RAa

**Comment by ramonsmits** [comment]
Another victim https://eu1.salesforce.com/console#%2F500D000001Ke6od

**Comment by timbussmann** [comment]
@ramonsmits I think it makes more sense to post these in the related pdev issue to help the issue get priority. It won't help anything in here?
