### ISSUE TITLE
Kill SendOptions

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3613]
This is the outcome of a [spike](https://github.com/Particular/NServiceBus/pull/3559) I worked on recently.

Based on our experiences while updating the testing framework to v6 and generally using the `Send`(&co) APIs I wasn't too happy with the current `SendOptions` API for sending messages. Current "pain points" with `SendOptions`:
- It forces us to use extension methods instead of properties (e.g. `options.SetMessageId(...)` instead of `options.MessageId = ...`) to allow downstream repositories add their own options (e.g. `SendToSite`). There were constantly requests to change this to properties for options provided by the core (because the extension methods really suck). The maintainers don't want to have the API "split" by using properties in the core and extensions in downstream repositories.
- We need a way to retrieve the configured options again (e.g. for testing). The current "workaround" is to provide "getter extension methods" (e.g. `options.GetMessageId()`) which feels weird and doesn't reed nicely with many options. It also adds a lot of noise to Intellisense.
- It's nearly impossible to "stringify" the configured options with the current approach. This was noticed on the testing update, because we can't easily output configured options of an outgoing message. There is no easy way to tell the user "here are the options which you set for the outgoing message".
- `SendOptions` can easily be reused in multiple send operations. It's quite easy to introduce bugs or undesired behavior this way. They are stateful and mutable.
- To share options between `SendOptions` `PublishOptions` and `ReplyOption` it's sometimes required to duplicate certain extension method (e.g. when it's only support for send and publish but not for reply).
- The obligatory `SendOptions` parameter required for outgoing operations is required even when you don't want to configure any options. It's so much noise that we have to provide extension methods which wrap this.

Note: every time `SendOptions` are mentioned this also includes `PublishOptions` and `ReplyOptions`.
## Proposal

 change the signatures from `Send(object message, SendOptions options)` to `Send(object message, params ISendOption[])` (and similar with publish and reply).

Where `ISendOption` instances are provided by dedicated factories like `Defer.By(TimeSpan delay)` or `Defer.To(DateTimeOffset deliveryDate)`, `MessageId.Set(string messageId)` or `Route.ToThisEndpoint()`.
### Advantages:
- It's much easier to properly "stringify" the options and to analyze options on an outgoing message.
- Created options are immutable.
- It's easier to scope options because you can implement the corresponding options interface (e.g. `IPublishOption`).
- This is highly subjective but I think it reads better than the extension methods.
- It allows to expose more meaningful data on the option classes usable for inspection & assertions (e.g. `Headers.Key` or `Defer.TimeSpan`).
- It scopes configuration options nicely together. E.g. all routing options are visible in `Routing` without other options adding noise to Intellisense.
### Disadvantes:
- It's less explorable, since you can't just see all available like options on the `SendOptions` class. I'd argue this is ok since users probably need to read docs about the specific options anyway, also R# is able to show available factory methods.
- Fluent APIs are not cool anymore. I'd argue this isn't a fluent API at all and more OOP than the current approach.
### Sample

Sample from the Spike:

Before:

```
var options = new SendOptions();
options.DelayDeliveryWith(TimeSpan.FromMinutes(15));
options.RouteToThisEndpoint();
options.SetCorrelationId("correlationId");
options.SetMessageId("messageId");
options.SetHeader("header1", "value1");
options.SetHeader("header2", "value2");
options.RouteReplyToThisInstance();
session.Send(new object(), options);
```

After:

```
session.Send(new object(),
  Defer.By(TimeSpan.FromMinutes(15)),
  Route.ToThisEndpoint(),
  CorrelationId.Set("correlationId"),
  MessageId.Set("messageId"),
  Header.Set("header1", "value1"),
  Header.Set("header2", "value2"),
  Reply.ToThisInstance());
```

From the spike it seems like this shouldn't be difficult to implement since it's pretty simple to shim it using `SendOptions` internally (and the other way round). The implementation of this API is very similar to the current `SendOptions` approach but just avoids the public "options bag" class.

**Comment by andreasohlund** [comment]
I'm :+1: , given that this only affects the more advanced parts of the API it seems resonable to leave as if for v6 from a end user perspective?

@timbussmann would you say that the drawbacks you listed are enough for us to consider this v6?

**Comment by timbussmann** [comment]
I think it would add value to the v6 release, but it's certainly not critical.

**Comment by danielmarbach** [comment]
Discussed this with @timbussmann today. We still believe that the SendOptions API is less than optimal from a discoverability standpoint. How about we prioritize a spike which tries to build the proposal here as a plugin API on top of `IMessageSession` and `IMessageHandlerContext`? If it works we can raise a platform dev issue to see if it makes sense to provide this as an official plugin or in labs and then track the feedback / downloads there to see if we really want to introduce those breaking changes into core.

**Comment by WilliamBZA** [comment]
👍 I like it, but with a bit more cleverness around the `params ISendOption[]` options. We should spend some effort making this somehow compile-time safe so developers don't accidentally specify 2 competing options.

E.g.

```
session.Send(new object(),
  Reply.ToThisInstance(),
  Reply.ToAnyInstance());
```

Would compile, but makes no sense. Something like a fluent interface could be used to make this scenario impossible.

**Comment by timbussmann** [comment]
> Something like a fluent interface could be used to make this scenario impossible.

not sure we really want to go down that path.

I'm +1 on doing some basic validation, but there's only limited capabilities as different options may come from different downstream packages. Btw. the current API also can't provide this configuration.

**Comment by WilliamBZA** [comment]
Yeah sure, happy to not go a fluent route. I would still encourage some kind of thought into compile-time basic validation. Pit of success and all that.

**Comment by timbussmann** [comment]
oooh, yeah in retrospective that makes much more sense than "pit of sarlacc" :/

![image](https://cloud.githubusercontent.com/assets/3524870/19302037/c74ae398-9062-11e6-913a-f3cc3500ff7e.png)

**Comment by timbussmann** [comment]
Spike currently in progress here: https://github.com/timbussmann/NServiceBus.FluentOptions

**Comment by timbussmann** [comment]
I think the spike is in a good enough shape to showcase the proposed idea. At that moment I'd prefer that approach but I'm not sure it provides such a huge benefit over the current approach besides a nicer (subjective) syntax. How do we proceed with that?

**Comment by danielmarbach** [comment]
TBH I don't think the value is high enough to proceed. Since you have an external package we could mention that in the community section of the docs page and see how many people download it and refer to it in the GG groups cases and defer the decision. Thoughts?

**Comment by timbussmann** [comment]
my spike is not published as a package. As I doubt that I can drive enough attention to this package, I'm only partially motivated to finish it.
