### ISSUE TITLE
No access to CriticalError from in dispatcher and subscription manager

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3616]
The `CriticalError` component cannot be accessed by transport components (apart from the message pump) because it can only be obtained from the builder.

The factories that are part of the transport should provide the `CriticalError` as an input argument for both `IDispatchMessages` as well as `IManageSubscriptions`.

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers please review this one. For me it is a blocker for properly implementing EventStore transport where subscription manager is an active component that becomes useless when it is unable to reconnect to the EventStore. It should be able to initiate the endpoint shutdown when unable to reconnect.

**Comment by andreasohlund** [comment]
The dispatcher and subscription manager is always called with a `Context`, I know its a bit of a hack but would doing `context.Builder.Build<CriticalError>()` get you unstuck?

**Comment by danielmarbach** [comment]
We only pass in the `ContextBag`. This would require some evil castings.

**Comment by SzymonPobiega** [comment]
For the dispatcher it might be enough but for the `IManageSubscriptions` which has an active thread refreshing the internal cache -- not. I currently have a hack in which I drive all my starts and stops from `IPushMessages` but it has some disadvantages (as there might be two instances of message pumps).

**Comment by andreasohlund** [comment]
Talking to @danielmarbach we propose to not include this in v6 since there is a workaround (yes a nasty hack) and none of out currently supported transports needs it.

Handling this in vNext also means that we will have time to evaluate a better implementation for critical error potentially using the new event aggregator.

@SzymonPobiega are you ok with this plan?

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by danielmarbach** [comment]
Ok removed the label then

**Comment by andreasohlund** [comment]
We still have to have a good way to raise them?

@SzymonPobiega 's use case with `IManageSubscriptions `

>For the dispatcher it might be enough but for the IManageSubscriptions which has an active thread refreshing the internal cache

Still seems legit regardless of our change in default behavior?

**Comment by timbussmann** [comment]
I think I'd still expect the endpoint to continue to run and trying to recover? It'd argue it's fine to disallow any outgoing message during a potentially "outdated system state" but not to tear down the endpoint.

**Comment by SzymonPobiega** [comment]
I think this is related to the collaborative cancellation raised by @timbussmann . If all types of components would be able to trigger the critical shutdown of the endpoint, that would be ideal.

**Comment by adamralph** [comment]
@SzymonPobiega is this taken care of now given that cancellation token support has been added in NServiceBus 8 (not yet released) — #5865.

**Comment by SzymonPobiega** [comment]
@adamralph yes, I think this is no longer an issue in the new seam.
