### ISSUE TITLE
CircuitBreaker and Critical Error handling misbehaviors

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3618]
I was in the process of addressing a customer question when I came up with the following issue when using the `DefineCriticalErrorAction` on the `BusConfiguration` object.
The observed endpoint behavior changes when using different transports, I actually tested `MSMQ` and `SQL`, and it gets worse if there is a persistence, other than `InMemory`, or heartbeats in the mix.
I'm using the latest V5 for all my tests and self hosting the endpoint.

### MSMQ Transport

using MSMQ via the following code:

```
var cfg = new BusConfiguration();

cfg.EnableInstallers();

cfg.UsePersistence<InMemoryPersistence>();
cfg.Conventions()
    .DefiningCommandsAs(t => t.Namespace != null && t.Namespace.EndsWith(".Commands"))
    .DefiningEventsAs(t => t.Namespace != null && t.Namespace.EndsWith(".Events"));

using(var bus = Bus.Create(cfg).Start())
{
    Console.Read();
}
```

If while the endpoint is running I stop the MSMQ service what happens is:

* The CircuitBreaker DOES NOT kick in
* The endpoint is gracefully shut down
* The process is still running

I then define a `DefineCriticalErrorAction`, such as:

```
cfg.DefineCriticalErrorAction((s, ex) =>
{

});
```

* The CircuitBreaker DOES NOT kick in
* The CriticalErrorAction is immediately called 4 times
* The endpoint is NOT gracefully shut down
* The hosting process after a while shuts down

In both cases: If, with the MSMQ service not running, I try to start the endpoint the endpoint blows up at startup

### SQL Transport

using SQL via the following code:

```
var cfg = new BusConfiguration();

cfg.EnableInstallers();

cfg.UsePersistence<InMemoryPersistence>();
cfg.UseTransport<SqlServerTransport>()
    .ConnectionString(@"Data Source=.\SQLEXPRESS;Initial Catalog=ServiceControl;Integrated Security=True");

cfg.Conventions()
    .DefiningCommandsAs(t => t.Namespace != null && t.Namespace.EndsWith(".Commands"))
    .DefiningEventsAs(t => t.Namespace != null && t.Namespace.EndsWith(".Events"));

using(var bus = Bus.Create(cfg).Start())
{
    Console.Read();
}
```

If while the endpoint is running I stop the SQL Server service what happens is:

* The CircuitBreaker kicks in
* The endpoint is gracefully shut down
* The process is still running

I then define a `DefineCriticalErrorAction`, such as:

```
cfg.DefineCriticalErrorAction((s, ex) =>
{

});
```

* The CircuitBreaker kicks in
* after a very long time the CriticalErrorAction is called 4 times
* the endpoint apparently does not shut down
* I can see in the logs a lot of warnings about missing SQL connectivity
* CriticalErrorAction is not called anymore and the status is unknown

In both cases: If, with the SQL Server service not running, I try to start the endpoint the endpoint blows up at startup

The scenario gets far more tricky the more features are added to the matrix. The end result is that the `CriticalErrorAction` seems to be completely useless.

Questions:
* what was the original `CriticalErrorAction` use case? 
* Should I check the same behavior in V6?

**Comment by timbussmann** [comment]
as discussed here: https://github.com/Particular/NServiceBus/issues/354, a CriticalErrorAction should not be empty. Also by providing a custom CriticalErrorAction you're overriding the existing one. The default action does stop the bus. If you don't stop the bus yourself in the CriticalErrorAction nothing else does.

Which circuitbreaker are you referring to? Msmq has at least two circuit breakers and SQL has it's own.

Note there is another issue about improving CriticalErrorAction https://github.com/Particular/NServiceBus/issues/3612.

**Comment by mauroservienti** [comment]
> CriticalErrorAction should not be empty. 

Is documented somewhere? It's not obvious and I cannot find any mention of it (on the phone right now)

Shouldn't the behavior be consistent across transports?

**Comment by mauroservienti** [comment]
BTW in https://github.com/Particular/NServiceBus/issues/354 there is nothing related to the CB.

> The default action does stop the bus. If you don't stop the bus yourself in the CriticalErrorAction nothing else does (= you have to do that yourself if you provide a CriticalErrorAction).

How? is there a way for the user to gracefully stop the bus in V5? And in V6?

> Which circuitbreaker are you referring to?

I don't know :smile: I simply observe 2 different behaviors, well 4 different behaviors.

Questions:

* what was the original `CriticalErrorAction` use case?
* Should I check the same behavior in V6?
* Shouldn't the behavior be consistent across transports?
* Is there a way to gracefully stop the bus in V5 and in V6?

**Comment by timbussmann** [comment]
> what was the original CriticalErrorAction use case?

I think mainly to do custom logging/cleanup before bus shutdown. /cc @andreasohlund 

> Should I check the same behavior in V6?

it works the same as in v5, but it provides an input parameter which allows to stop the bus (which indeed is more complex in v5).

> Is there a way to gracefully stop the bus in V5 and in V6?

copy&paste from the default v5 implementation (yes, extremely ugly imho):

            var components = configure.Builder.Build<IConfigureComponents>();
            if (!components.HasComponent<IBus>())
            {
                return;
            }

            configure.Builder.Build<IStartableBus>()
                .Dispose();

v6 (exactly what the default implementation does):

```
        Task CriticalErrorAction(ICriticalErrorContext criticalErrorContext)
        {
            return criticalErrorContext.Stop();
        }
```

regarding the circuit breaker behavior: it's the transports responsibility to define and configure circuit breaker which trigger when a transport is no longer able to stay operational. So regarding:

> Shouldn't the behavior be consistent across transports?

I don't think the circuit breaker behavior should be consistent. Again, there are different numbers of circuit breakers, different errors, different configurations and all is transport specific. Therefore I think it's ok for them to behave differently?

What was the user scenario regarding CriticalErrorAction?

**Comment by danielmarbach** [comment]
So does that mean our current approach with critical errors is wrong? Should a definition of a critical error action NOT override the shutdown behavior then? I'm starting to feel so but would need to investigate more. But since this is an API which is rarely used I'd say we should backlog it.

**Comment by timbussmann** [comment]
> So does that mean our current approach with critical errors is wrong? Should a definition of a critical error action NOT override the shutdown behavior then?

I think so since quite a while. It just seems to be too dangerous to skip shutdown, but then again that's probably the only reason besides custom logging to provide a ciriticalErrorAction.

**Comment by mauroservienti** [comment]
Well, when self-hosting I want to be responsible to shut down or not, I don't want my process to blow up because something in the bus failed. What I'd like to have is a clean and simple way to achieve 2 goals:

* Understand that the bus is facing a critical failure
* Gracefully shut down the bus, not necessarily my process

> What was the user scenario regarding CriticalErrorAction?

Unreliable connectivity to a very large SQL infrastructure, it may happen that the SQL broker is not available for longer than what is expected by the default circuit breaker implementation. Changing the default CB timeout is not an option as well since the timeout may vary at runtime a thing that is not supported, nonetheless not all the CBs are customizables.
So the only option seems to be (given that there is no way to fix the infrastructure):

* handle critical errors
* shutdown the bus
* write some custom code to check periodically the infrastructure status
* when infrastructure is back start the bus once again
* repeat if needed :smile: 

My actual issue is that the behavior is not consistent across transports and if you add to the same endpoint persistence and heartbeats the critical error action is called several times and it is very hard to understand what is going on in the endpoint.

**Comment by ramonsmits** [comment]
@mauroservienti Do you have a desk case link? Could you add it to #3612?

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers Decided to raise an issue to completely revamp/rethink the our approaches to critical error handling based on the existing issues. 

https://github.com/Particular/PlatformDevelopment/issues/746

Closing this one
