### ISSUE TITLE
Minor V6 Naming Inconsistencies in the Pipeline

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3621]
Most Connectors have names that end with `Connector` but `MulitcastPublishRouteBehavior` does not. 

Most Terminators have names that end with `Terminator` but `DispatchTimeoutBehavor` and `StoreTimeoutBehavior` do not.

**Comment by timbussmann** [comment]
Should we also adjust `DeserializeLogicalMessagesConnector` and `LoadHandlersConnector` to the "naming convention"?

**Comment by bording** [comment]
Looking at this pipeline visualization that @mikeminutillo created:

![pipeline](https://cloud.githubusercontent.com/assets/753669/13963476/e5c9a90c-f03b-11e5-9f21-b1d7071b3feb.png)

It looks like there are several other places that we might want to consider renaming. A lot of the connectors follow an **A***To***B***Connector* pattern showing the name of the stages, but not all of them.

It also looks like fork connectors tend to just have `Behavior` in their name vs. `Connector`.

We also seem to be inconsistent in the usage of `Processing` in the name contexts and connectors.

**Comment by mikeminutillo** [comment]
If I understand correctly, the Fork Connectors are actually Behaviors. They just have the opportunity to initiate another stage (either before, after, or instead of the main flow).

> Should we also adjust DeserializeLogicalMessagesConnector and LoadHandlersConnector to the "naming convention"?

I don't know. I like that they tell me what they do. The one that surprised me was `TransportReceiveToPhysicalMessageProcessingConnector`. There is a lot of Outbox related behavior in there but it's not clear from the name. I think that naming something XToYConnector will make it easier to add functionality into the connectors that belongs somewhere else.
