### ISSUE TITLE
Core requires providing default connection string (V6)

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus#3635]
In SQL Server transport V3 we can provide custom connection factories `UseCustomSqlConnectionFactory` or `EnableLagacyMultiInstanceMode`.
If we don't also include some dumb entry in app.config then the application throws exception saying "Additional information: Transport connection string has not been explicitly configured via ConnectionString method and no default connection has been was found in the app.config or web.config file for the SqlServerTransport Transport.".

In my opinion this is not right, and I'd rather not tell users to use the hack with dumb connString entry. What other options I have?

**Comment by weralabaj** [comment]
@mauroservienti I'm not sure it's the right solution. In the situation I faced we still require providing some connection string just using factory.

**Comment by tmasternak** [comment]
@weralabaj Maybe we should change that only for `MulitInstanceLegacyMode`?

**Comment by weralabaj** [comment]
@tmasternak if possible, that would make more sense IMO.
