### ISSUE TITLE
Simplify API for providing endpoint instance ID

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3652]
This issue is a replacement for #3406 . For now we agreed to provide simple API like

```
config.InstanceId(string id);
```
- [ ] Core change
- [ ] Doco update
- [ ] Compatibility tests update

**Comment by SzymonPobiega** [comment]
@Particular/tf-v6-launch-plat-dev please mark it as 'V6' since we can't ship it with the old `config.ScaleOut().InstanceDiscriminator()` API.

**Comment by andreasohlund** [comment]
Flagged as `Consider for v6`

**Comment by bording** [comment]
FYI, #3654 has introduced another place in the code where the old API has been referenced in an exception message.

**Comment by SeanFeldman** [comment]
@SzymonPobiega added compatibility tests to the check-list

**Comment by SzymonPobiega** [comment]
Thanks @bording  & @SeanFeldman  :)

**Comment by tmasternak** [comment]
It looks that this can be address as a minor release. In addition this seems to be advanced api so users should be able to cope with what we have right now.

/cc: @danielmarbach @boblangley

**Comment by bording** [comment]
@tmasternak I wouldn't really consider this an advanced API. You have to use it to enable Callbacks, for example.

The current `config.ScaleOut().InstanceDiscriminator()` API makes this a very bizarre API that you'd need to call just get to get Callbacks working.

**Comment by SzymonPobiega** [comment]
@tmasternak I don't think we can address it in minor because this is a braking change to the public API.

**Comment by johnsimons** [comment]
@SzymonPobiega looking at this, I agree with @tmasternak, it seems all you need to do is introduce the new API in a minor release and deprecate the old one, this is how we usually manage this kind of api changes.
Yes I agree that the current API is not very intuitive, so is `config.InstanceId(string id);` better ? I am not sure!

**Comment by SzymonPobiega** [comment]
@johnsimons ok, I am ok with this approach.

**Comment by tmasternak** [comment]
@SzymonPobiega that was the intention. Keep the current API but in minor add a more convenient one.

**Comment by tmasternak** [comment]
@SzymonPobiega that was the intention. Keep the current API but in minor add a more convenient one.

**Comment by timbussmann** [comment]
the v6 release changed the `config.ScaleOut().UniqueQueuePerEndpointInstance()` to  `endpointConfiguration.MakeInstanceUniquelyAddressable`. Since there was no progress on this issue and no clear steps forward, we're going to close this. Feel free to reopen if we missed something or you think there is still an important task outstanding.

**Comment by kristianjaeger** [comment]
Hello, I was looking at issue 3406 and this one.  So, to route messages to a logical endpoint (not queue) if I understand correctly I need `endpointConfiguration.MakeInstanceUniquelyAddressable` ?  So, say there's a use case where I need to send to instances A, B, C (all different VMs, same queue, but different logical endpoint ID).  Is this one of the intended uses of this MakeInstanceUniquelyAddressable method with NSB 6?  Thanks.

**Comment by kristianjaeger** [comment]
Thanks @timbussmann .  I probably should have phrased this better as I would like to send to one of three endpoints based upon a request header.  Seems possible via the routing table.  Cheers.

**Comment by kristianjaeger** [comment]
Thanks again. We'd prefer to use the same queue if possible.  We're still using MSMQ as the transport at the moment.  The doc refers to "The **following queues will be created** for endpoint Sales configured with discriminator B:

Sales
Sales-B".  I think that I have an alternative that will work (routing table). I'll see what support says as well when they reply after I clarified my question.  Cheers.
