### ISSUE TITLE
Redesign logging APIs

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3653]
The `LogManager` is the last place in NServiceBus which uses static fields which:
- Makes it hard to tests the log output
- Prevents usage of different logging configurations for endpoint instances that live in the same appdomain

**Comment by timbussmann** [comment]
given the tendency to move away from DI, any suggestions?

An attempt to improve the situation is this PR: https://github.com/Particular/NServiceBus/pull/3661
which makes it easier to test log output (with some limitations)

**Comment by danielmarbach** [comment]
Let's backlog this. Since we have right now a half-baked way we can look into this again at a later stage.

**Comment by timbussmann** [comment]
Is this worth keeping open?

>  Makes it hard to tests the log output

we have `TestingLoggerFactory` which helps with this usage to a certain degree.

> Prevents usage of different logging configurations for endpoint instances that live in the same appdomain

What would be the usage scenario of this? Usually every logger provides a custom configuration API allowing to customize every single logger if needed. Not sure I understand what the real driver behind this would be?

**Comment by SzymonPobiega** [comment]
@timbussmann hosting multiple endpoints in the same app process. That becomes quite common scenario with all the bridges and transport adapters. For some of these I might want to have different logging configuration (e.g. different file etc.)

**Comment by timbussmann** [comment]
@SzymonPobiega how would you achieve this outside NServiceBus given that most logging framework themselves heavily rely on statics to access loggers?

**Comment by SzymonPobiega** [comment]
@timbussmann Haven't checked all of them but `Serilog` supports non-static configuration.

**Comment by timbussmann** [comment]
Sounds like this approach only makes sense when hosting multiple endpoints in the same process in the first place. I'd suggest to consider this as a feature request for platdev as this requires significant breaking changes probably. Are you able to move this issue to platdev @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@timbussmann well, I don't feel strong enough about this to move it to PlatDev. OK to close it.
