### ISSUE TITLE
Remove the "hack" from RouteDeferredMessageToTimeoutManagerBehavior

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3657]
https://github.com/Particular/PlatformDevelopment/issues/133 introduced a hack in this behavior and has been closed prematurely without removing the hack. This issue is about removing that technical debt.

**Comment by boblangley** [comment]
We would prefer to get this done before V6 launch since it is messing with the pipeline, which by nature are high risk.

/cc: @Particular/tf-v6-launch-plat-dev

**Comment by danielmarbach** [comment]
[PR ](https://github.com/Particular/NServiceBus/issues/3655) is merged. Closing
