### ISSUE TITLE
Publicize types used by connectors so that connectors can be replaced

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3659]
[Originally raised by @SzymonPobiega]( https://github.com/Particular/NServiceBus/issues/3642)

A while ago we had a discussion about ability to replace **any** behavior in the pipeline, including the connectors. As far as I remember the outcome was to continue supporting replacing of anything. While porting one of the samples I discovered that at least following behaviors:

 * TransportReceiveToPhysicalMessageProcessingConnector
 * RoutingToDispatchConnector

are not replaceable due to the fact that `PendingTransportOperations` is internal.

## Plan of Attack
* [x] Make `PendingTransportOperations`
* [x] Check other connectors and make necessary changes so that connectors can be replaced.

**Comment by danielmarbach** [comment]
As part of https://github.com/Particular/NServiceBus/issues/3655 `PendingTransportOperations` are public.

**Comment by timbussmann** [comment]
closing this as #3655 solved the issue with `PendingTransportOperations` and it seems that the other connectors are replaceable.
