### ISSUE TITLE
When the user has multiple implementations of IProvideConfiguration, only one of them is used.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3660]
When multiple instances of IProvideConfiguration for the same configuration section are found, only the first one is taken into consideration and others are ignored.

Related to: https://github.com/Particular/NServiceBus/issues/3649

**Comment by SeanFeldman** [comment]
Closing in favour of #3649 with more details.

**Comment by adamralph** [comment]
Marking as duplicate.

**Comment by indualagarsamy** [comment]
Thanks @SeanFeldman - My bad for opening this one.
