### ISSUE TITLE
Deserializing unobtrusive message fails when no handler exists.

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3671]
When an endpoint which uses unobtrusive messages receives a message it has no handler for, instead of the typical "No handler found" exception it throws the following exception:

> NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message ad5454c8-8da5-49ab-81e1-a5e600c82e1a ---> System.Exception: Could not determine type for node: 'DownloadIsReady'.
   at NServiceBus.XmlDeserialization.InferNodeType(XmlNode node, Object parent) in C:\Projects\NServiceBus\src\NServiceBus.Core\Serializers\XML\XmlDeserialization.cs:line 288
   at NServiceBus.XmlDeserialization.Process(XmlNode node, Object parent, Type nodeType) in C:\Projects\NServiceBus\src\NServiceBus.Core\Serializers\XML\XmlDeserialization.cs:line 202
   at NServiceBus.XmlDeserialization.Deserialize(Stream stream, IList`1 messageTypesToDeserialize) in C:\Projects\NServiceBus\src\NServiceBus.Core\Serializers\XML\XmlDeserialization.cs:line 52

Before this exception, the log states this:

> WARN  NServiceBus.Unicast.Messages.MessageMetadataRegistry Message header 'Store.Messages.Events.DownloadIsReady' was mapped to type 'Store.Messages.Events.DownloadIsReady' but that type was not found in the message registry, ensure the same message registration conventions are used in all endpoints, especially if using unobtrusive mode.

The conventions are all correctly configured, but the assembly scan seems to only include unobtrusive messages which it has handlers for, therefore missing the received message type.

Because the message is not in the registry, the XMLDeserializer fails to determine the type from the xml content (because it doesn't have the full class name) and throws the exception.

The exceptions and logs aren't especially helpful in this case and the regular "no handlers found for this message" would be better.

We know the included message type from the headers, so it would be possible to correctly deserialize the message if we provide the fully qualified name to the deserializer? Or would it be possible to apply the message conventions in the assembly scanning process?

**Comment by danielmarbach** [comment]
Have you considered native integration scenarios and unobtrusive mode as well in your thought process?

**Comment by timbussmann** [comment]
> Have you considered native integration scenarios and unobtrusive mode as well in your thought process?

good point. If we don't want to use the message header, then we need to apply message conventions at assembly scanning time? Since we're detecting unregistered types, we could probably also adjust the code to do a runtime registration of the type?

**Comment by danielmarbach** [comment]
Since this is a different exception which hides the original problem it is inconvenient but not urgent. We can fix this in a minor release

**Comment by andreasohlund** [comment]
Duplicate of https://github.com/Particular/NServiceBus/issues/4000
