### ISSUE TITLE
DispatchConsistency is non-intuitive and being abused by the outbox

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3677]
I was reviewing the Sql Server Transport dispatcher and realized that the `DispatchConsistency` is non-intuitive and being abused by the outbox.

The core uses the `DispatchConsistency` in two places. 
-  For immediate dispatch in the [ `RoutingToDispatchConnector`](https://github.com/Particular/NServiceBus/blob/7df2cc7f289629072b1a13c8adead40efe0eb180/src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs#L18)
- For outbox purposes in [`ForceBatchDispatchToBeIsolatedBehavior`](https://github.com/Particular/NServiceBus/blob/09c94279a068ea0282c5d7bead34badd870d080b/src/NServiceBus.Core/Reliability/Outbox/ForceBatchDispatchToBeIsolatedBehavior.cs#L14)

In the immediate dispatch scenario the `TransportOperations` collection that is passed to the dispatcher will only contain one transport operation with the consistency level set to `isolated`.

In outbox scenarios when you only have one session call inside the message handling pipeline the dispatcher will get one entry on the `TransportOperations` collection with consistency level set to `isolated` as well. When we have many transport operations that are created in the message handling pipeline all will be marked with consistency level to `isolated` and then the whole batch is contains only isolated operations.

The SQL server dispatcher assumed that when dispatch Isolated is set each operation has to be sent out individually in a transaction which is not participating in the receive transaction. In the case of an outbox being present this would lead to suboptimal performance. 

From a transport usage perspective it would make much more sense to mark the whole TransportOperations collection with a flag like `UseWhateverOperationModeYouPreferAsLongAsYouDoNotEnlistInReceiveTransaction`. For immediate dispatch we would just have a flag on the transport operation called `DispatchImmediately`. This would be much clearer and less "abusive".

Thoughts @Particular/transport-maintainers @Particular/nservicebus-maintainers ?

**Comment by timbussmann** [comment]
so `isolated` means just not participating in existing transactions, not isolated against all other outgoing transport operations.

If I understand correctly, this could be optimized completely by the transports without changing the API since they could just group isolated operations if this yields benefits (e.g. sharing a connection)?

**Comment by andreasohlund** [comment]
>so isolated means just not participating in existing transactions, not isolated against all other outgoing transport operations.

Correct, it means to not participate in the existing **receive transaction**. When the dispatch call returns the messages should all be acked by the transport.

**Comment by danielmarbach** [comment]
Carved out a concrete action point into #4270 Closing
