### ISSUE TITLE
In Version 5 messages sent out by handlers for message for which a saga is invoked carry the `OriginatingSagaId` header

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3689]
### Symptoms

If there is both a handler and a saga defined for a given messages type, messages sent out (e.g. via `Bus.Reply`) by the handler contain `OriginatingSagaId` header which make them look like they were sent by a saga but in fact they are sent by the normal stateless message handler that happened to coexist with the sagas in the same message processing pipeline.

### Who's affected

Users of NServiceBus 5 who have saga and a handler defined for same message type.

**Comment by timbussmann** [comment]
what's the effect on receivers of these messages containing the incorrect header?

**Comment by SzymonPobiega** [comment]
I think they never notice that. The only different would be, if you `Reply` to such a message, the reply would be auto-routed to an existing saga rather than starting a new one. But that would be a very very specific case. Given messages like:
 * StartSaga -> StartsASaga
 * Reply

In a conversation like this:
```
A->B: StartSaga
B->A (from a handler): Reply
A->B: StartSaga
```

A might expect to start a new saga but in fact it's message would be routed to an existing saga that was created when the `Repy` was sent.

**Comment by timbussmann** [comment]
@SzymonPobiega does v6 have the same bug?

**Comment by SzymonPobiega** [comment]
@timbussmann no, I could not repro it on V6.

**Comment by timbussmann** [comment]
I can see some potential impact by this issue, but the scenario which is hit by this bug seems to be quite unlikely/rare. Shall we close this? @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
I'm going to close this since there were no further arguments why we should backport a fix to v5. Feel free to reopen if you disagree.
