### ISSUE TITLE
Changing RoutingStrategies in the RoutingContext is dangerous

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3690]
`RoutingContext` allows to set the `RoutingStrategies` when a message should be redirected to other destination. This is dangerous because the routing stage is used not only be the main sending pipe but also by some other features, including (but not limited to):
 * Audit
 * Forwarding
 * Failure handling

[This](https://github.com/Particular/NServiceBus.SqlServer/issues/202) is an example of a bug caused by this design flaw where audit (and error) messages are redirected to the callback queue of the sender after being processed in the receiver.

My proposal is (again, I've raised that before), make the routing stage read-only and allow forking into it from behaviors that need to override the address.

**Comment by SzymonPobiega** [comment]
Although this does not have to technically go to V6, I would strongly suggest it does, @Particular/tf-v6-launch-plat-dev @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
hm, isn't the routing stage exactly made for this? `RouteDeferredMessageToTimeoutManagerBehavior` relies on the ability to change the routing. But this seems to be the only modifying behavior in he core, not sure about downstreams.

whether we continue to allow it or not, this doesn't seem to be a bug but a refactoring @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
I marked it as a bug because it is to me a design flow that invites bugs. Whoever changes the `RoutingStrategies` in a behavior in the routing stages, does it also for the audit and error messages. And there is no good way to detect, inside the routing stage, if you are dealing with a normal message or an audit/error/forward message.

**Comment by andreasohlund** [comment]
Talking to @timbussmann and @SzymonPobiega we concluded that nothing needs to done for v6.

@SzymonPobiega will raise a new issue to outline the routing changes we want to do in vNext and close this one

**Comment by SzymonPobiega** [comment]
Replaced with https://github.com/Particular/NServiceBus/issues/3695. Closing.
