### ISSUE TITLE
Add explicit API for writing exception headers and log entries 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3692]
I think this is a legitimate use case
http://docs.particular.net/samples/logging/stack-trace-cleaning/#manipulate-error-queue-header

It would be nice to not have to leverage the pipeline and 3rd party logging APIs to achieve this

**Comment by danielmarbach** [comment]
Nice!

**Comment by timbussmann** [comment]
like the idea :+1: Do you have any thoughts on the API?

**Comment by SimonCropp** [comment]
add two delegate methods. one to `EndpointConfiguration` for the error queue. and the other to the looging `DefaultFactory`.

Both delegates would take in an `Exception` and return a string.

**Comment by danielmarbach** [comment]
I know that we don't want to rethrow the exception inside the delegate. Nonetheless, I would lean towards using an [`ExceptionDispatchInfo`](https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo(v=vs.110).aspx) as the container to pass the exception to the delegate.
