### ISSUE TITLE
Skip the routing stage for "built-in" messages

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3695]
In V6 the built-in messages e.g. audits, errors go through the routing stage. The reason for that is we want to take advantage of `RoutingToDispatchConnector` which handles the batching. In order to avoid problems caused by behaviors in the routing stage changing the destination of messages we should skip the routing stage when sending these mentioned built-in messages. Here's the possible solutions:
- Introduce another stage between routing and dispatch
- Implement support for batching where the fork happens (e.g. AuditToDispatchConnector)
- ?

**Comment by danielmarbach** [comment]
> Implement support for batching where the fork happens (e.g. AuditToDispatchConnector)

Wouldn't that mean we need some base behavior? The implications would be that we have to duplicate that logic into various connectors. Not saying that it is per definition a bad thing, but I tend to lean towards 

> Introduce another stage between routing and dispatch

But I have troubles to come up with a good name for that stage.
