### ISSUE TITLE
Microsoft.Net.Compilers missing from Core project

### ISSUE THREAD

**Issue by sebastianslutzky** [Particular/NServiceBus#3698]
Hi,

I've just cloned the repository and tried to compile it. 
It failed with the following message
`...Could not load file or assembly 'Microsoft.CodeAnalysis'...`

The compilation succeeded after I've added the missing package from the nuget.org feed
`Install-Package` Microsoft.Net.Compilers`

Regards,
Sebastian

**Comment by distantcam** [comment]
@sebastianslutzky Which version of Visual Studio were you using?

**Comment by sebastianslutzky** [comment]
@distantcam:
 Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Professional

**Comment by distantcam** [comment]
@sebastianslutzky Visual Studio 2015 Update 1 will also fix the problem.

**Comment by sebastianslutzky** [comment]
I see. thanks for clarifying, I'll close it as a non issue then
