### ISSUE TITLE
DateTime.UtcNow for time measurement is flawed

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3699]
in `ProcessingStatisticsBehavior` we do this

            state.ProcessingStarted = DateTime.UtcNow;
            context.Extensions.Set(state);
            try
            {
                await next().ConfigureAwait(false);
            }
            finally
            {
                state.ProcessingEnded = DateTime.UtcNow;
            }

But if the system clock adjusts during message processing those two times are not useful when compared. So the math that is done in the SLA and Critical time

            var processingDuration = processingEndedInstant - processingStartedInstant;

is void. We should instead be only capturing one date and then use a stopwatch to measure the milliseconds. this results in negative time in SI
![2016-04-22 10_51_26-settings](https://cloud.githubusercontent.com/assets/122666/14728460/498b2bba-0878-11e6-9670-6c62c619493f.png)

This means that the processing duration can only be calculated in the endpoint and has to be passed all the way through to SC

**Comment by danielmarbach** [comment]
@SimonCropp can you send in a fix against release branch?

**Comment by andreasohlund** [comment]
This effects v5 as well right?

Is it a must have for v6?

**Comment by SimonCropp** [comment]
@danielmarbach it is not that easy. looking into it further it requires a change in SC and most likely SI. 

also we do the calculation twice. while we can use a stopwatch in ProcessingStatisticsBehavior that will not work in 

    class AuditProcessingStatisticsBehavior : Behavior<IAuditContext>
    {
        public override Task Invoke(IAuditContext context, Func<Task> next)
        {
            ProcessingStatisticsBehavior.State state;

            if (context.Extensions.TryGet(out state))
            {
                context.AddAuditData(Headers.ProcessingStarted, DateTimeExtensions.ToWireFormattedString(state.ProcessingStarted));
                // We can't take the processing time from the state since we don't know it yet.
                context.AddAuditData(Headers.ProcessingEnded, DateTimeExtensions.ToWireFormattedString(DateTime.UtcNow));
            }

            return next();
        }
    }

so this is not a "simon can fix on his own" issue :)

**Comment by mikeminutillo** [comment]
Can we just record the start date using `DateTime.UtcNow`, start a stopwatch and then fake the end date using `start + stopwatch`?

That way nothing else needs to change.

**Comment by SimonCropp** [comment]
@mikeminutillo is correct

**Comment by mikeminutillo** [comment]
This works

```CSharp
            state.ProcessingStarted = DateTime.UtcNow;
            var stopwatch = Stopwatch.StartNew();
            context.Extensions.Set(state);
            try
            {
                await next().ConfigureAwait(false);
            }
            finally
            {
                state.ProcessingEnded = state.ProcessingStarted + stopwatch.Elapsed;
            }
```

... but ...

These values are not used to populate the headers. They are only used to calculate values for SLA and Critical Time perf counters :(

**Comment by andreasohlund** [comment]
>These values are not used to populate the headers. They are only used to calculate values for SLA and Critical Time perf counters :(

Yes, this is the same tire fire me and @danielmarbach hit when we found

https://github.com/Particular/NServiceBus/issues/3565

and

https://github.com/Particular/NServiceBus/issues/3494

:(

**Comment by andreasohlund** [comment]
Had a false start with the stop watch in #3735 but we concluded that it would work. Will revisit this in a separate pull in the future

**Comment by timbussmann** [comment]
@andreasohlund anything we need to do for v6 here?

**Comment by andreasohlund** [comment]
Nah, this can be fixed in a later release

**Comment by danielmarbach** [comment]
Seems to be trivial to fix. Assigned 6.1 and sent in #4249
