### ISSUE TITLE
Make features use the full type name

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3702]
To avoid name clashes

### POA

- [x] [Update core](https://github.com/Particular/NServiceBus/issues/3701) 
- [x] Update docs
- [x] Update RavenDB to properly depend on the outbox
- [x] Update NHibernate to properly depend on the outbox

**Comment by andreasohlund** [comment]
@Particular/tf-v6-launch-plat-dev based on discussion in #3701 I've included this in v6 scope.

**Comment by andreasohlund** [comment]
Backlogging this for now after talking to @SimonCropp , we need to fix this for RC, no need to rock the beta boat for now

**Comment by andreasohlund** [comment]
Given the latest round of releases isn't this one done?

**Comment by SimonCropp** [comment]
@andreasohlund well there is no doco. but there was no doco for the old behavior. so not sure how to proceed?

**Comment by andreasohlund** [comment]
Perhaps a note on http://docs.particular.net/nservicebus/pipeline/features#dependencies ? and a section in the upgrade guide?

**Comment by SimonCropp** [comment]
ok. will do it tomorrow
