### ISSUE TITLE
race condition in When_auto_correlated_property_is_changed

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3711]
There is a race condition  in When_auto_correlated_property_is_changed

the test does 

            var exception = Assert.Throws<AggregateException>(async () =>
                await Scenario.Define<Context>()
                    .WithEndpoint<Endpoint>(
                        b => b.When(session => session.SendLocal(new StartSaga
                        {
                            DataId = Guid.NewGuid()
                        })))
                    .Done(c => c.ModifiedCorrelationProperty)
                    .Run())
                .ExpectFailedMessages();

and the handle method does this 

                public Task Handle(StartSaga message, IMessageHandlerContext context)
                {
                    Data.DataId = Guid.NewGuid();
                    TestContext.ModifiedCorrelationProperty = true;
                    return Task.FromResult(0);
                }

but because these are happening on different threads then the asserts may finish prior to the exceptionbeing thrown

**Comment by SimonCropp** [comment]
manifests here https://builds.particular.net/viewLog.html?buildId=161667&tab=buildResultsDiv&buildTypeId=NServiceBusAzure_NServiceBusAzureServiceBus_2RunAcceptenceTests

**Comment by SimonCropp** [comment]
@timbussmann any ideas on where to put the `ModifiedCorrelationProperty` to prevent the race condition?

**Comment by timbussmann** [comment]
@SimonCropp hm this is strange. As soon as the done condition is met, the endpoint should stop but wait until all inflight messages are processed, so the exception should be catched, or am I missing something?

I know this is wild speculation, but seeing this code in ASB:

                var processTask = ProcessMessageAsync(message);
                pipelineInvocationTasks.TryAdd(processTask, processTask);

Makes me wonder whether you see a different behavior if you add a `await Task.Yield()` in the first line of your message handler implementation?

**Comment by timbussmann** [comment]
sidenote: seems like the same test is failing for rabbitMQ (https://github.com/Particular/NServiceBus.RabbitMQ/pull/136)

**Comment by timbussmann** [comment]
I have a hunch that this is related to the changed behavior of the `MoveToErrorQueueBehavior`. Before the fix, we immediately sent the message to the errorqueue (while processing the message), the new behavior is to mark the message and roll it back and dispatch it only on the next receive. So by ending the endpoint there's a good chance of not receiving the message the second time, therefore never actually sending it to the errorqueue.

**Comment by andreasohlund** [comment]
>So by ending the endpoint there's a good chance of not receiving the message the second time, therefore never actually sending it to the errorqueue.

Seems very likely to me

**Comment by timbussmann** [comment]
temporary fix here: https://github.com/Particular/NServiceBus/pull/3712 please try that @SimonCropp 

I think we need to change the "error queue message detection" mechanism. While the workaround used in #3712 itself works, there is a risk of not failing the test when messages are sent to the errorqueue

**Comment by timbussmann** [comment]
I think this should be fixed by this change: https://github.com/Particular/NServiceBus/pull/3716 
Please feel free to reopen if the test is failing.
