### ISSUE TITLE
Detecting failed messages in ATT

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3714]
Acceptance tests should fail when a message fails to process. We detected this by listening to the "message moved to error queue" notification.

The mechanism moving messages to the errorq now requires the message to be rolled back and retried because of transactions (no issue when disabling transport transactions). If the done condition is met before the failed message is read again from the queue, the test may complete without actually sending the message to the error queue. This can cause different issues:
* Tests expecting a message to be sent to the error queue fail because the test ends before the message is sent to the error queue.
* Tests not expecting a message to be sent to the error queue may finish successfully although message processing may have failed.

The first point can be solved using `context.FailedMessages.Any()` as the done condition. This approach will not solve point 2 though.

samples of failing tests:
https://github.com/Particular/NServiceBus/issues/3713
https://github.com/Particular/NServiceBus/issues/3711#issuecomment-215326602
https://github.com/Particular/NServiceBus.RabbitMQ/pull/136

**Comment by MarcinHoppe** [comment]
Just for the sake of completeness: some test also use the `ErrorSpy` approach.

**Comment by timbussmann** [comment]
> Just for the sake of completeness: some test also use the ErrorSpy approach.

Especially for satellite pipelines which aren't tracked by the existing infrastructure

**Comment by timbussmann** [comment]
fixed by #3716
