### ISSUE TITLE
Hotpath UnicastRoutingTable.GetDestinationsFor should avoid linq expression to save on heap allocations

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3718]
https://github.com/Particular/NServiceBus/blob/4d9c771e57810d28e4bcdf0209a0d2b0d776c89d/src/NServiceBus.Core/Routing/UnicastRoutingTable.cs#L14-L34

You could probably cache the staticroutes in a dictionary to avoid `staticRule.Invoke(type, contextBag)`, this call should always return the same addresses right ?

**Comment by andreasohlund** [comment]
@timbussmann @SzymonPobiega is this still an issue?

**Comment by bording** [comment]
This has completely changed now: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/UnicastRoutingTable.cs#L13

So I'm going to close this.
