### ISSUE TITLE
MessageDrivenSubscriptionsConfigExtensions.SubscriptionAuthorizer is exposed to brokers that support native subscription

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3719]
In rabbit a user can do the following:

``` c#
endpointConfiguration.UseTransport<RabbitMQTransport>().SubscriptionAuthorizer(context => false);
```

This actually does not stop subscriptions

**Comment by andreasohlund** [comment]
Yea, only message driven pub sub transports should expose that option :(

**Comment by timbussmann** [comment]
this is addressed with v6 as the `SubscriptionAuthorizer` API is only available to transports with message driven pub sub 👍 Closing this.
