### ISSUE TITLE
NUnit 2.6 ignores Task returning tests

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3723]
NUnit v2 ignores tests which return tasks instead of awaiting them. e.g. this test is green when run explicitly and ignored when running the whole suite:

        [Test]
        public Task ShouldFail()
        {
            return Task.Run(() => { throw new Exception("pewpew"); });
        }

We merged this PR last week: https://github.com/Particular/NServiceBus/pull/3705 which causes over 60 tests to be ignored on the build server.
Since nUnit v3 handles returned tasks correctly there are currently two options to resolve this:

* Update to nUnit v3
* Revert the commit and check for other returned tasks.

I'd strongly prefer updating nUnit v3

**Comment by WojcikMike** [comment]
:+1: for nUnit v3

**Comment by SimonCropp** [comment]
done
