### ISSUE TITLE
SetMessageHeader Obsolete message is not very clear on what needs to be done.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3725]
The current obsolete message is here:
https://github.com/Particular/NServiceBus/blob/7df2cc7f289629072b1a13c8adead40efe0eb180/src/NServiceBus.Core/obsoletes.cs#L689

The upgrade guide section documents this behavior:
http://docs.particular.net/nservicebus/upgrades/5to6#header-management-setting-headers-on-outgoing-messages
Talks about adding header to all outgoing messages, but doesn't highlight how to set a specific header. 

Relates to: https://github.com/Particular/V6Launch/issues/35

**Comment by andreasohlund** [comment]
How about we switch to
> Use the Send|Publish|Reply  overload that accepts an options parameter and use `options.SetHeader("MyHeader","MyValue")`.

?

**Comment by indualagarsamy** [comment]
`Use the appropriate overload for the `Send`, `Publish` or `Reply` that accepts an options parameter. Call options.SetHeader("MyHeader","MyValue") instead.`

**Comment by danielmarbach** [comment]
labelled this issue so that it doesn't show up in the unlabelled issue list.

**Comment by timbussmann** [comment]
fixed with #3784
