### ISSUE TITLE
V6 API Feedback / Question

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3726]
Even though Version 6 is completely rebuilt for Async the method names don't follow the standard async naming conventions, namely prefixing the methods with Async. Why?

There is a subset of NServiceBus customers that get value out of using the Async suffix, as a consistent pattern across other libraries/frameworks. 

See: 
- Google user post here:
https://groups.google.com/forum/#!searchin/particularsoftware/async$20suffix/particularsoftware/xrSJpgjowJQ/RWAlIxpfBgAJ
- Also reported by Customer: https://github.com/Particular/V6Launch/issues/36

**Comment by timbussmann** [comment]
I think @danielmarbach answered that question in the linked user group question? Here is a lot of background on that decision: https://github.com/Particular/NServiceBus/pull/3083

In case we're assuming this questions gets asked a lot with the v6 release, do we need some kind of FAQ?

**Comment by indualagarsamy** [comment]
@timbussmann - I agree. However we need this to be captured in our upgrade guide or a separate page that the upgrade guide points to. Yes, I think when we go against the norm, there will be questions and we need to document this properly. I opened an issue in the core, but this is legit feedback from our users using the API.

**Comment by timbussmann** [comment]
I think the upgrade guide is the wrong place for this? This question can also come from someone new to NSB.

**Comment by DavidBoike** [comment]
Raised a doco issue https://github.com/Particular/docs.particular.net/issues/1523 to cover generating this content and added it to the CoreV6 milestone.

**Comment by SeanFeldman** [comment]
Beta customer feedback: https://github.com/Particular/NServiceBus/issues/3765
