### ISSUE TITLE
Auditing creating recursive subscriptions

### ISSUE THREAD

**Issue by seantarogers** [Particular/NServiceBus#3730]
Hi,

I think this is an issue.  I have been trying to enable auditing in across our NServiceBus endpoints.  We have an Audit endpoint which takes a copy of all messages processed and adds them to a SQL database.

When auditing is enabled for any endpoint that publishes events we have noticed that an additional recursive subscription is written to our subscription db table.  It seems the publisher endpoint's are subscribing to their own events. So whenever an event is published a copy of it is  moved into its own publisher's error queue with the following exception:
 
```cs
    System.InvalidOperationException: No handlers could be found for message type: Messages.Events.SomethingHappenedEvent
     at NServiceBus.LoadHandlersBehavior.Invoke(IncomingContext context, Action next) in  C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\LoadHandlersBehavior.cs:line 29
    at NServiceBus.BehaviorChain`1.InvokeNext(T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 107
    at   NServiceBus.BehaviorChain`1.&lt;&gt;c__DisplayClass4_0.&lt;InvokeNext&gt;b__0() in  C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 94

```
The only way I have found to resolve this is to disable auditing. 

I am using NSB 5.2.14 with unobtrusive mode.
I have a repo here that recreates the potential issue.

https://github.com/seantarogers/AuditingIssue

Thanks for your time

**Comment by timbussmann** [comment]
Hi @seantarogers , thanks for raising the issue and providing a sample to reproduce your issue :+1: We will have a closer look at this.

**Comment by timbussmann** [comment]
@seantarogers this is how my subscriptions table looks like when running your sample:
![image](https://cloud.githubusercontent.com/assets/3524870/15069448/dfeb4b66-137d-11e6-9bd2-b5c8eab0e979.png)
so I'm not getting that subscription you mentioned. Did you try to drop your subscriptions table and check whether running your sample still produces the unwanted subscription?

**Comment by seantarogers** [comment]
Hi @timbussmann thanks for looking into it.  I just deleted the subscription table plus all of the queues and re-ran the solution. I still get:

![subscriptionissue](https://cloud.githubusercontent.com/assets/8544425/15090609/3d17a8d2-1425-11e6-9259-7d25d4a7a8fa.png)

I notice your subscription has the logicalEndpoint column, I dont have this.  We are not using different NSB versions somehow?

**Comment by seantarogers** [comment]
Hi, @timbussmann this was not a nsb bug, @sfarmar has kindly corrected my code.  See SO for details: http://stackoverflow.com/questions/36668142/nservicebus-saga-auditing-no-handlers-found-exception.   Thanks for your time spent on this.
