### ISSUE TITLE
NServiceBus.Transports => NServiceBus.Transport

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3731]
So based on this we should fix the `NServiceBus.Transports` to be  `NServiceBus.Transport`

https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/namespaces.md

**Comment by andreasohlund** [comment]
I'd say not worth the hazzle right now, we know that we have to make changes to the transport seam in vNext so it would be a low hanging fruit then?

**Comment by andreasohlund** [comment]
Since we're about to change the seam to handle #3792 this is a lowhanging fruit, I've added it to the POA for https://github.com/Particular/V6Launch/issues/69

**Comment by andreasohlund** [comment]
This is included in Beta6, closing
