### ISSUE TITLE
DataBus directory convention is broken

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3732]
Repo's in v5 and v6

So `FileShareDataBusImplementation.MaxMessageTimeToLive` is never used 
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DataBus/FileShareDataBusImplementation.cs#L16

So MaxMessageTimeToLive will always be Zero

So apply this to the key generation

```
    string GenerateKey(TimeSpan timeToBeReceived)
    {
        if (timeToBeReceived > MaxMessageTimeToLive)
        {
            timeToBeReceived = MaxMessageTimeToLive;
        }

        var keepMessageUntil = DateTime.MaxValue;

        if (timeToBeReceived < TimeSpan.MaxValue)
        {
            keepMessageUntil = DateTime.Now + timeToBeReceived;
        }

        return Path.Combine(keepMessageUntil.ToString("yyyy-MM-dd_HH"), Guid.NewGuid().ToString());
    }
```

And the result will always be `DateTime.Now`.

So a bit of history. The key is used to generate a directory that uses the ttl as part of the convention. The theory being that when cleanup was implemented (which was never done) that convention could be more easily used to cleanup the files. 

So moving forward do we fix the directory convention to properly use the ttl?

**Comment by timbussmann** [comment]
>  The theory being that when cleanup was implemented (which was never done) that convention could be more easily used to cleanup the files.

@SimonCropp so while I agree this should be treated as bug, the only impact currently is a wrong directory name, right?

**Comment by SimonCropp** [comment]
Correct. Very minor bug
