### ISSUE TITLE
DataBusExtentions misspelled

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3733]
Should be `DataBusExtensions`. This is a breaking change, should we fix for v6?

Since its extmethods we probably only have to change here

http://docs.particular.net/nservicebus/messaging/databus#configuring-azuredatabus

**Comment by SimonCropp** [comment]
yep

**Comment by andreasohlund** [comment]
@Particular/tf-v6-launch-plat-dev I propose we roll this into the RC task since its a very small change

**Comment by andreasohlund** [comment]
Bundle into the RC release

**Comment by timbussmann** [comment]
#3781 is merged, closing this
