### ISSUE TITLE
DistributionStrategy lifecycle is wrong

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3737]
This causes round-robin distribution to not work when there is more than a single downstream endpoint. Unfortunately our tests did only cover a single downstream scenario.

**Comment by SzymonPobiega** [comment]
I am sure this is must-have for RC.

**Comment by SzymonPobiega** [comment]
I think it should be tackled together with #3670 because they are closely related.

**Comment by andreasohlund** [comment]
Makes sense, flagged as v6

**Comment by andreasohlund** [comment]
Let's deal with https://github.com/Particular/NServiceBus/issues/3679 and https://github.com/Particular/NServiceBus/issues/3678 since they are all about routing?

cc @Particular/tf-v6-launch-plat-dev

**Comment by timbussmann** [comment]
This is fixed by https://github.com/Particular/NServiceBus/pull/3752 which is included in the current v6 release
