### ISSUE TITLE
Need for a multi-transport feature

### ISSUE THREAD

**Issue by aaronpalmer** [Particular/NServiceBus#3738]
My company is moving to a new architectural pattern of CQRS with Event Sourcing using a service bus to manage our business sagas.  We have multiple systems and currently have a significant investment using MSMQ with BizTalk.  We have been considering using Greg Young's Event Store along with NServiceBus as our service bus.  The difficulty we are having is creating a saga with a single endpoint that allows us to connect to two transports, MSMQ for our legacy systems and Event Store for the new implementation.  We have also considered a solution of using MSMQ for the "Command" part of CQRS and Event Store for the "Query", ideally all of the implementation details nicely tucked under the hood of NServiceBus.  Whether we use the MSMQ/Event Store together long term has yet to be seen, but for the transition period of phasing in Event Store it would be much easier if we had the ability to at least leverage both as transports as our sagas logically span both the legacy and new systems.

Reference question:
http://stackoverflow.com/questions/37146866

**Comment by danielmarbach** [comment]
Thanks @aaronpalmer for bringing this up. I see that @SzymonPobiega already provided an answer on StackOverflow which was accepted as the answer. We also have a few samples around multi transport integration. For example

* [MsmqToSql Relay](http://docs.particular.net/samples/msmqtosqlrelay/)
* [Sql Bridge](http://docs.particular.net/samples/sql-bridge/) which has been superseeded by the MsmqToSql relay example

The principles shown above can be applied to transport integration in general.

**Comment by danielmarbach** [comment]
@aaronpalmer Thanks again for bringing this up. We are not going to address multi-transport integration for the foreseeable future. As it stands we are leaving it at the level of samples. I hope the samples and the answer from @SzymonPobiega helped you to resolve your questions. I'm closing this one.
