### ISSUE TITLE
Saga does not throw when no mappings exist

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#3755]
For V6 we're promising that we will throw if you forget to map an IAmStartedBy message. This is true if we map one message and not another (due to the check for a non-default correlation id value) but does not hold up if you forget to map any messages at all.

**Comment by andreasohlund** [comment]
Flagged as maintainer prio after talking to @timbussmann.

 @bording @danielmarbach ok?

**Comment by timbussmann** [comment]
:+1:

**Comment by danielmarbach** [comment]
Good

**Comment by bording** [comment]
:+1:

**Comment by andreasohlund** [comment]
PR is merged, closing
