### ISSUE TITLE
NSB 6 Behavior exception Registration 'InvokeHandlers' specified in the insertbefore of the 'MyBehavior' step does not exist

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#3770]
Looks like there is a bug in Behavior registration in [NSB 6 Beta 2](https://www.nuget.org/packages/NServiceBus/6.0.0-beta0002).

I upgrade my NSB 5 Behavior:

    /// <summary>
    /// Logs each incoming message that comes into a <see cref="IHandleMessages{T}"/>
    /// </summary>
    public class LogIncomingMessageBehavior : Behavior<IInvokeHandlerContext>
    {
        /// <summary>
        /// Logs the incoming message
        /// </summary>
        public override async Task Invoke(IInvokeHandlerContext context, Func<Task> next)
        {
            var logger = LogManager.GetLogger(context.MessageHandler.Instance.GetType());

            if (logger.IsDebugEnabled)
                logger.Debug(
                    $"Handling [{context.MessageMetadata.MessageType.Name}]",
                    context: 
                        context.Headers);

            await next().ConfigureAwait(false);
        }
        internal class Registration : RegisterStep
        {
            public Registration() :
                base(nameof(LogIncomingMessageBehavior), 
                          typeof(LogIncomingMessageBehavior), 
                          "Log Incoming Messages")
            {
                InsertBefore(WellKnownStep.InvokeHandlers);
            }
        }
    }

And then register in my Config:

    config.Pipeline.Register<LogIncomingMessageBehavior.Registration>();

When my Endpoint starts up I get this exception:

    Registration 'InvokeHandlers' specified in the insertbefore of the 'LogIncomingMessageBehavior' step does not exist. Current StepIds: 'LogIncomingMessageBehavior'
    at NServiceBus.PipelineModelBuilder.ProcessBefores(Node node, Dictionary`2 nameToNode) in C:\Build\src\NServiceBus.Core\Pipeline\PipelineModelBuilder.cs:line 195
    at NServiceBus.PipelineModelBuilder.Sort(IList`1 registrations) in C:\Build\src\NServiceBus.Core\Pipeline\PipelineModelBuilder.cs:line 176
    at NServiceBus.PipelineModelBuilder.Build() in C:\Build\src\NServiceBus.Core\Pipeline\PipelineModelBuilder.cs:line 106
    at NServiceBus.Pipeline`1..ctor(IBuilder builder, ReadOnlySettings settings, PipelineModifications pipelineModifications) in C:\Build\src\NServiceBus.Core\Pipeline\Pipeline.cs:line 23
    at NServiceBus.StartableEndpoint.<BuildPipelines>d__9.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 131
    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    at NServiceBus.StartableEndpoint.CreateIncomingPipelines(IPipelineCache pipelineCache) in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 70
    at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 44

Is `WellKnownStep.InvokeHandlers` not registered at this point?

**Comment by andreasohlund** [comment]
InvokeHandlers is now what we call a "pipeline terminator" so you will always be running before it. You can safely remove the call to `InsertBefore`.

With the new stages in v6 there shouldn't really be a need for any InsertBefore/After, do you have other examples?

We're in the processes of cleaning up the WellKnownSteps so please accept my apologies for the confusion.

https://github.com/Particular/NServiceBus/issues/2783

**Comment by andreasohlund** [comment]
Some doco on this topic http://docs.particular.net/nservicebus/pipeline/customizing-v6

**Comment by danielmarbach** [comment]
@andreasohlund That being said the topological sort could actually try to identify this case and throw a meaningful exception. Thoughts?

**Comment by andreasohlund** [comment]
Good point, we could detect that if the Before/After is a terminator (or a stage connector) and throw a better ex

**Comment by ppittle** [comment]
A better exception would certainly be helpful.

**Comment by andreasohlund** [comment]
@ppittle can you confirm that removing the InsertBefore works? (I will raise a new issue for the improved ex)

**Comment by ppittle** [comment]
Confirmed.  Changed my `Registration` class as below and *no* longer get an exception:

    internal class Registration : RegisterStep
    {
        public Registration() :
            base(nameof(LogIncomingMessageBehavior), 
                      typeof(LogIncomingMessageBehavior), 
                      "Log Incoming Messages")
        {            
        }
    }

**Comment by andreasohlund** [comment]
New issue raised to track the better ex

https://github.com/Particular/NServiceBus/issues/3772

closing this one. Thanks @ppittle for finding this!
