### ISSUE TITLE
Remove Saga.RequestTimeout HandlerContext parameter

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3778]
V6 currently requires users to provide a `IMessageHandlerContext` parameter to `Saga.RequestTimeout` and `Saga.ReplyToOriginator`. This was introduced because all send operations need to use `IMessageHandlerContext` which is provided as a parameter on the `Handle` method which needs to be passed down to `RequestTimeout` or `ReplyToOriginator`.

Should we explore other approaches to see whether we can improve the Saga API?

/cc @DavidBoike

**Comment by timbussmann** [comment]
some obvious approaches:
* Introducing `ISagaContext`: Probably quite a big effort, but fits best with the "context" vision
* make the current context somehow available on the saga class (without using DI)
* extension method on `IHandlerMessageHandlerContext`: Doesn't work well since it cannot be scoped to be only available on sagas.

**Comment by danielmarbach** [comment]
Why? Do we have any feedback that the API is not clear? 

I think it makes it clear that you can only use `RequestTimeout` or `ReplyToOriginator` as part of a `Handle` method and aligns well with the floating context design paradigm we want users to use.

**Comment by andreasohlund** [comment]
I also think that the api looks funky but I also agree with @danielmarbach, let's wait for some feedback before we do anything?
