### ISSUE TITLE
Cannot set error queue on a remote server for MSMQ

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#3787]
Raised in GG: [here](https://groups.google.com/forum/#!topic/particularsoftware/tn6ihLnjjK0)

The issue appears to be when the message pump for MSMQ transport is validating input queue to be a local one. Rather than performing the test on the input queue, it [tests the error queue instead](https://github.com/Particular/NServiceBus/blob/896c5dfa8efe3f2e92491643ae0e436022a1db28/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L37).

```c#
var inputAddress = MsmqAddress.Parse(settings.InputQueue);
var errorAddress = MsmqAddress.Parse(settings.ErrorQueue);

if (!string.Equals(errorAddress.Machine, Environment.MachineName, StringComparison.OrdinalIgnoreCase))
{
       var message = $"MSMQ Dequeuing can only run against the local machine. Invalid inputQueue name '{settings.InputQueue}'";
       throw new Exception(message);
}
```

should be

```c#
var inputAddress = MsmqAddress.Parse(settings.InputQueue);
var errorAddress = MsmqAddress.Parse(settings.ErrorQueue);

if (!string.Equals(inputAddress.Machine, Environment.MachineName, StringComparison.OrdinalIgnoreCase))
{
       var message = $"MSMQ Dequeuing can only run against the local machine. Invalid inputQueue name '{settings.InputQueue}'";
       throw new Exception(message);
}
```

**Comment by timbussmann** [comment]
why does that have a 7.0.0 milestone?

**Comment by SeanFeldman** [comment]
@timbussmann to draw your attention. Target achieved, check.
Probably my world is mostly v7 (Azure). :)

**Comment by SeanFeldman** [comment]
fixed via https://github.com/Particular/NServiceBus/commit/2245dc55cebb21137f8caf106b04be8d46f9b584
