### ISSUE TITLE
Deprecate Remove from PipelineSettings-API

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3790]
After a discussion with @andreasohlund and @SimonCropp we couldn't come up with a scenario where removing a behavior would make sense. In the worst case you could still replace a behavior with an empty dummy.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers any objections?

**Comment by danielmarbach** [comment]
No objections. Making it harder by forcing to replace existing ones seems to be a good move

**Comment by andreasohlund** [comment]
Low hanging fruit, assigning to v7

**Comment by bording** [comment]
So, RabbitMQ is actually taking advantage of Remove now: 

https://github.com/Particular/NServiceBus.RabbitMQ/blob/1708fc2d015798d2dfee39905f327108ce894da5/src/NServiceBus.RabbitMQ/DelayedDelivery/PreventRoutingMessagesToTimeoutManager.cs#L20

I suppose swapping in a dummy implementation would work too, but I wanted to point out that I do have a use case for it.

**Comment by WilliamBZA** [comment]
@andreasohlund @lailabougria @ramonsmits @aleksandr-samila I see this was tagged for the 8.0.0 release but can't see which commits or docs changes form part of this.

Has this been captured in an upgrade guide anywhere?

**Comment by lailabougria** [comment]
It's in [this PR](https://github.com/Particular/Website/pull/643) under Exceptional guidance and the code was changed [here ](https://github.com/Particular/NServiceBus/pull/5771)

**Comment by WilliamBZA** [comment]
So nothing in the upgrade guide, correct?

**Comment by lailabougria** [comment]
Looking at it and can't find anything in there, so that's a gap indeed!

**Comment by andreasohlund** [comment]
I have a faint memory that we said that given the very limited use of the method that the obsolete message would be enough guidance https://github.com/Particular/NServiceBus/pull/5771/files#diff-3c42f1561d4b35e9e29b798b9980511120c9316708abde192ab600143d211f80R365
