### ISSUE TITLE
`WindowsIdentity.GetCurrent()` can return null

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3798]
http://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,804

but we have some with no null check

**Comment by andreasohlund** [comment]
@timbussmann I have a faint memory your removed one because R# complained, could that be a R# bug?

**Comment by timbussmann** [comment]
no resharper bug, the call we used internally always sets the `bool threadOnly` to false and therefore it can never be null.

**Comment by SimonCropp** [comment]
Ok
