### ISSUE TITLE
v6 IConfigureThisEndpoint Move Complicates Multi-Hosted Endpoint

### ISSUE THREAD

**Issue by tekmaven** [Particular/NServiceBus#3808]
We primarily use `NServiceBus.Hosting.Azure` to host our endpoint in a Cloud Service.  In the development environment, we use `NServiceBus.Host` to host the endpoint locally.  In NSB v5, `IConfigureThisEndpoint` was defined in `NServiceBus.dll`, and each hosting endpoint automatically found and executed this.  

In v6, this was moved to the host assemblies at the same exact namespace - `NServiceBus.Host` and `NServiceBus.Hosting.Azure` both define the type `NServiceBus.IConfigureThisEndpoint`.  We can not even create a single EndpointConfig class that inherits both interfaces because they literally conflict with each other.

```
EndpointConfig.cs(16,35,16,57): error CS0433: The type 'IConfigureThisEndpoint' exists in both 'NServiceBus.Host, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Hosting.Azure, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'
```

To run in this configuration, we will now need three assemblies:
* An assembly with our handlers and a class that configures the endpoint (but does not impliment any `IConfigureThisEndpoint`.
* `AzureHost` which references `NServiceBus.Hosting.Azure` and calls the configuration code in the first assembly.
* `StandardHost` which references `NServiceBus.Host` and calls the configuration code in the first assembly.

I do appreciate the reasoning behind the changes here, but this creates a 3x increase in assemblies to accomplish what we were doing in NSB v5.  I think the best solution would be to differentiate the namespaces that `IConfigureThisEndpoint` are using.

**Comment by yvesgoeleven** [comment]
@tekmaven try to run your on https://www.nuget.org/packages/NServiceBus.Hosting.Azure.HostProcess/7.0.0-beta0001 in your dev env instead of NServiceBus.Host

**Comment by SeanFeldman** [comment]
@tekmaven does that work for you?

**Comment by SeanFeldman** [comment]
@tekmaven I've raised an [issue](https://github.com/Particular/docs.particular.net/issues/1583) to document this option.

**Comment by danielmarbach** [comment]
@SeanFeldman @yvesgoeleven can we close this issue and update the doco as outlined in the linked doco isue?

**Comment by SeanFeldman** [comment]
@danielmarbach will be done as part of https://github.com/Particular/docs.particular.net/issues/1255

**Comment by andreasohlund** [comment]
Tracked by Particular/docs.particular.net#1255 , closing this
