### ISSUE TITLE
Make `ErrorQueueSettings` and `AuditConfigReader` public

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3811]
Currently in V6 there is no way outside of the core to discover the location of error/audit queues. This functionality is provided by `ErrorQueueSettings` and `AuditConfigReader`. If we expose these two classes then other plugins will be able to make use of this information. 

This is currently required by the [ServiceControl V6 plugins](https://github.com/Particular/ServiceControl/issues/742).

**Comment by andreasohlund** [comment]
I rather have a custom extension method on `ReadonlySettings` or similar instead ?

Eg: 

FeatureX.Setup(context)
  `var error = context.Settings.GetErrorQueue()`

**Comment by mikeminutillo** [comment]
@andreasohlund like [this](https://github.com/Particular/NServiceBus/pull/3812)?

**Comment by mikeminutillo** [comment]
I've put this into In Progress under the maintainer budget because I'm doing it in order to fix the SC plugins. In essence this is happening under the SC maintainer budget.

**Comment by andreasohlund** [comment]
@mikeminutillo given that https://github.com/Particular/NServiceBus/issues/3812 is merged can we close this one?

**Comment by mikeminutillo** [comment]
@andreasohlund yep. Still waiting on the release of beta5 so that I can update the downstreams properly but this issue is done.
