### ISSUE TITLE
Ability to hook into the outgoing message to set native message properties

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3821]
It is not possible to change native message properties. It would be nice if a customer would add or change native message properties / values. This would give a customer the ability to make use of native features which might not be supported by NServiceBus.

Each transport will have its own type of native message but maybe we can define a couple of common logical steps. Maybe this is upto each transport to implement but it would be nice if all transports would use similar names.

If we can have common steps then maybe we can have either generic or object type based API. 

The following issues is sort of related. Maybe we can extract a generic step in the core API so that not each transport has its own way of naming steps: https://github.com/Particular/NServiceBus.RabbitMQ/issues/156

**Comment by timbussmann** [comment]
if it's a native feature which is supported by multiple transports, that would probably something which could be added to the `DeliveryConstraints` like non-durable messages. If it's only a single transport, I think that would be an issue for the transport to solve, making transport specific things available through abstract core APIs doesn't sound like a good approach?

**Comment by ramonsmits** [comment]
@timbussmann Our transports are not really extensible due to our current step of converting the transport message to the 'physical' message and that is the reason I created it in the NServiceBus repo.

So no, its not something that would be configured in core but it would be nice if all transports have a very similar extension model to achieve this. The actual implementations would be in the transports or in extensions to the transports.

Please read the provided RabbitMQ issue as an example. If you would currently want to implement this you need to fork the transport and implement the change. This is (currently) an issue that all transports share.

**Comment by Scooletz** [comment]
@ramonsmits What you propose is an ability to inject a piece into `IDispatchMessages` where it would enable to augment native messages on the basis of `TransportOperations` and other properties.
This would be a very transport specific as for `ASQ` for example that would require to act on the basis of:
- `CloudQueueMessage`
- `UnicastTransportOperation`

For other transports that enable some different dispatch mechanisms that would be a totally different signature as they may provide batched dispatching. I think there's no way of providing a coherent extension for every transport.

**Comment by yvesgoeleven** [comment]
Like this? https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Sending/IConvertOutgoingMessagesToBrokeredMessages.cs

**Comment by yvesgoeleven** [comment]
it would be very dependent on transport indeed, ASB will do this very different from ASQ f.e., unicast vs multicast, batching, etc... will make it different

**Comment by SimonCropp** [comment]
For me this should be a transpoort specific api that requires no change in the core

**Comment by danielmarbach** [comment]
I agree with @SimonCropp since you want to set data on the native message using the native infrastructure a generic approach in the core would always be a useless abstraction.

**Comment by ramonsmits** [comment]
Yes, such extensions are very transport specific but with this issue I want to prevent from happening that MSMQ would use some kind of callback, ASB using a provider and another transport using even another option.

It would be nice if all are aligned and having a pipeline behavior / step / stage / fork that would make the 'transport message to native message' more explicit and force alignment. Most important aspect is all transports must be extendable. 

While on that topic I created issue #3908 which is aligned with this concern.

It would not be a useless abstraction even though it would use transport specific types which are open for extension and required a dependency on both the transport as core. If maintainers of transports and core state that his is absolutely not possible and / or unwanted including why then this issue can be closed.

**Comment by danielmarbach** [comment]
Closing this since we agree such extension points should be transport specific (if needed).
