### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by seesharper** [Particular/NServiceBus#3824]
I am the author of the LightInject DI framework and more and more people are asking for an integration for LightInject. The last time I attempted this I got in trouble with a missing NServiceBus license after a certain period of time. I think it was a month or so. I would very much like to make this integration happen, but that requires me to reliably being able to pull down the NServiceBus and NServiceBus.ContainerTests.Sources without suddenly having it to break because of licensing issues. 
Any way you can help me out here?

**Comment by dadhi** [comment]
+1, interested for potential [DryIoc](https://bitbucket.org/dadhi/dryioc) integration.

**Comment by timbussmann** [comment]
hey @seesharper and @dadhi ,

Great to hear that you are interested in support NServiceBus for your DI containers :+1: !

> I would very much like to make this integration happen, but that requires me to reliably being able to pull down the NServiceBus and NServiceBus.ContainerTests.Sources without suddenly having it to break because of licensing issues. 

That sounds weird to me. Running the tests shouldn't be tied to a license in any way. Can you describe the problem you're running into?

As an open source project you are entitled for a NServiceBus license if you are following the requirements of the [RPL 1.5](https://opensource.org/licenses/rpl1.5.txt) license (for all NServiceBus versions licensed under RPL 1.5). In that case, please contact willie.levy@particular.net and he will be able to help you with this.

**Comment by timbussmann** [comment]
@seesharper @dadhi are you fine with me closing the issue or is there anything else regarding our licensing you could need help with?

**Comment by dadhi** [comment]
I am fine, thanks for reacting.

**Comment by seesharper** [comment]
All good
