### ISSUE TITLE
Make exception and retry counter available to custom SLR policy

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3831]
The current custom SLR policy is defined as `Func<IncomingMessage, TimeSpan>`. The documentation ( http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-custom-retry-policy ) shows how to extract the exception and retry counter from the message headers, but in v6 these headers aren't present on the incoming message ( https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/1S61S-jB1YY/mO254IgILAAJ ). These information are available on the SLR behavior which invokes the custom policy, but they are not passed to the user: https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs

I think we should provide an (alternative) custom policy where the user callback also receives the exception and the retry counter. Also requires a doco update.

@Particular/nservicebus-maintainers I think that should be fixed as part of v6.0 since the header access as demonstrated in the sample doesn't work.

**Comment by timbussmann** [comment]
(note that the acceptance tests verify the presence of the headers but they only succeed because the headers are present after the first SLR retry attempt)

**Comment by danielmarbach** [comment]
I agree this should be fixed. Since we demonstrate it users are going to assume it just works.

**Comment by timbussmann** [comment]
will be fixed in v6 with #3832. Closing this.
