### ISSUE TITLE
Validation error implies working behavior of IMessage for pub/sub

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus#3839]
When publishing a message marked with IMessage the following warning is displayed:

> You are using a basic message to do pub/sub, consider implementing the more specific ICommand and IEvent interfaces to help NServiceBus to enforce messaging best practices for you.

This implies that it works, but NServiceBus never sends subscription messages to the publisher. I think we should at the very least change the message. But perhaps when scanning for handlers & messages we should throw an exception saying that a subscription message is never sent?

It concerns this validation message: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs#L48

**Comment by timbussmann** [comment]
> This implies that it works, but NServiceBus never sends subscription messages to the publisher. 

you're talking about the autosubscribe feature here, right? Does bus.scrube work with an IMessage object?

**Comment by dvdstelt** [comment]
Just verified and it does.

```
public class MyMessage : IMessage {   }
```

and then 

```
var bus = Bus.Create(config).Start();
bus.Subscribe<MyMessage>();
```

will make sure the subscription does work. You think we should rather change it to something like this?

> You are using a basic message to do pub/sub. Either manually subscribe to events or consider implementing the more specific ICommand and IEvent interfaces, which will help NServiceBus to enforce messaging best practices for you.

**Comment by dvdstelt** [comment]
Some background info from @DavidBoike on Slack. Isn't really necessary, but always good to read more context on the why and what.

> I think that error messages was written at V3,  a time right after IEvent and ICommand were created, and they still did auto-subscribe
> and then either V4 or V5 changed that behavior, so only IEvents will autosubscribe

**Comment by danielmarbach** [comment]
We don't consider this important enough at the moment. If you feel strongly about it feel free to raise a PR.
