### ISSUE TITLE
RuntimeEnvironment.MachineName should not be static

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3845]
- Makes it hard to test code that is based on it
- we support multiple endpoints per appdomain. so is there never a requirement to have different MachineName values per endpoint?

**Comment by timbussmann** [comment]
not sure in what scenario you really want to have a different machine names when using multiple endpoints per appdomain but from a testing perspective it makes sense to avoid the statics.

**Comment by danielmarbach** [comment]
I think it would make sense to make it non-static and always deal with it over the settings if we can

**Comment by bording** [comment]
> I think it would make sense to make it non-static and always deal with it over the settings if we can. This simplifies acceptance testing scenarios.

Are there any places where we need MachineName but don't have access to settings? If so, how would we deal with those?

**Comment by SimonCropp** [comment]
Fwiw i dont think this needs to happen for v6
