### ISSUE TITLE
RuntimeEnvironment.MachineName should not be a delegate 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3846]
since it is executed in the pipeline it means if people put expensive code in the delegate it could significantly slow down message processing

**Comment by bording** [comment]
I can't see a good reason for allowing the machine name to possibly change on every execution of the delegate.

It seems like dropping the delegate, and just having a settable string property would be enough here.

It also has the side benefit of allowing us to call `Environment.MachineName` and store the result in a way that doesn't require a closure allocation on each call.

**Comment by danielmarbach** [comment]
Agreed. Should we address it together with https://github.com/Particular/NServiceBus/issues/3845 as a maintainer prio?
