### ISSUE TITLE
KeyNotFoundException when using UnitOfWork().WrapHandlersInATransactionScope()

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#3847]
When using UnitOfWork().WrapHandlersInATransactionScope() the core throws a KeyNotFoundException with message 'The given key (NServiceBus.TransportTransactionMode) was not present in the dictionary'

setting transportConfiguration.Transactions(TransportTransactionMode.SendsAtomicWithReceive) solved the problem for me, but the exception message could be clearer

**Comment by yvesgoeleven** [comment]
@andreasohlund V6

**Comment by andreasohlund** [comment]
Found the issue, fix proposed here https://github.com/Particular/NServiceBus/pull/3848

**Comment by andreasohlund** [comment]
Should be fixed on the release branch. Can you verify @yvesgoeleven ?

**Comment by danielmarbach** [comment]
Closing this one. @yvesgoeleven feel free to reopen if not fixed
