### ISSUE TITLE
XmlSerializer doesn't use custom Namespace

### ISSUE THREAD

**Issue by mowensoft** [Particular/NServiceBus#3852]
The `XmlSerializer` continues to use the default namespace, `http://tempuri.net`, even when a custom namespace is specified.  I only notice this issue when actually sending messages from a running endpoint; cloning the repo and running the unit tests all pass as expected.  I tested this against version 6.0.0-beta0004 and 6.0.0-beta0002.

I'm not 100% sure how/when the configuration and `SettingsHolder` are supposed to work, otherwise I'd have a pull request handy for you.  I did make a unit test to reproduce the issue though, which can be found here: [NServiceBusXmlSerializerBug.cs](https://gist.github.com/mowensoft/22036edb1637c4f2eca0a655c5a8d3ce#file-nservicebusxmlserializerbug-cs)

**Comment by timbussmann** [comment]
Hey @mowensoft,

You're right, it seems like the `Namespace` extension doesn't work at all in the v6 beta. That's definitely something which needs to be fixed before the release candidate.

Thanks a lot for reporting the issue and providing a test to reproduce the issue! :+1:

**Comment by timbussmann** [comment]
Hey @mowensoft ,

This bug should be fixed once beta6 of NServiceBus is out. I'm closing this for now, please reopen this in case you're still encountering issues after beta6. Thanks again for reporting the issue!

**Comment by mowensoft** [comment]
Awesome! Thanks @timbussmann!
