### ISSUE TITLE
Internal visibility for FeatureConfigurationContext makes testing awkward

### ISSUE THREAD

**Issue by stimms** [Particular/NServiceBus#3853]
I'm trying to build a custom persister and I'm finding it difficult to properly test the feature creation. This is because the `Setup` method requires a `FeatureConfigurationContext` whose only constructor is internal. This, obviously, makes it painful to pass in my own implementations of Feature around this. I've pulled as much logic as I can out of that class into a testable one but it still leaves some crucial code untestable.

**Comment by bording** [comment]
Hi @stimms,

Which version of NServiceBus are you currently targeting? We have improved the testing scenario for V6 by including testable versions of the various context classes we've introduced. However, it does appear that a `TestableFeatureConfigurationContext` is not currently included. We'll have to look into adding that one.

In general, the approach of keeping logic out of the actual Feature and moving it into other classes is a good one. What sort of logic are you finding that is required to stay in the `Setup` method that requires tests?

**Comment by stimms** [comment]
I'm working against V6. My implementation isn't fully fleshed out yet but if we take the NHibernate implementation as an example https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/SagaPersisters/NHibernateSagaStorage.cs it performs model mapping.

**Comment by timbussmann** [comment]
The simple fix would be to make that ctor just public but that will essentially just uncover the whole iceberg, since there required parameters are also a bit tricky and with internal ctors. I think even when all ctors are public it looks like we would need to provide a `TestableFeatureConfigurationContext` to make testing custom features more comfortable. In general I'm :+1: to make features more testable but these are probably two different issue (making required things public to unblock & providing a `TestableFeatureConfigurationContext`).

**Comment by stimms** [comment]
Making things testable by providing your own testable implementations seems silly to me (I stumbled on `TestableMessageHandlerContext` today). You're assuming that you know the test scenarios for all clients and that nobody will need to create their own custom implementations. In general my approach would be to provide interfaces people can mock themselves.

**Comment by danielmarbach** [comment]
@stimms 

> providing your own testable implementations seems silly to me 

Thanks for your feedback. We take an opinionated approach here. For most of our contexts (except for the FeatureConfigurationContext) we provide both. The testable implementation is looking at how the contexts are meant to be used by our customers and how they are used by our infrastructure (dogfooded). They provided a helpful implementation which should fit most of our users. 

If for a small number of users they don't fit then they can just use any available faking library out there to stub behavior on the base interfaces. We get the benefit of both worlds.

* Simple testable implementations which already stub out the majority of the behavior which might be a bit difficult to "reverse" engineer for our customers
* For Advanced scenarios which we didn't anticipate users can always go with their own implementations.

**Comment by danielmarbach** [comment]
In our opinion are features like DI modules. Testing DI modules in isolation in our opinion doesn't provide a lot of value. Instead, DI modules should be tested by hooking them into acceptance and/or integration tests. The same applies for features. Closing this one.
