### ISSUE TITLE
When a subscription message cannot be delivered an unhandled exception exits the process

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3854]
When a subscription message is sent its seems to be done on a separate thread. If an exception occurs like the following the process just exists. [This is because its an unhandled exception on a threadpool thread](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Subscriptions/MessageDrivenSubscriptions/SubscriptionManager.cs#L29). 

> System.Messaging.MessageQueueException (0x80004005): Access to Message Queuing system is denied.

The offending line is:

* https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Subscriptions/MessageDrivenSubscriptions/SubscriptionManager.cs#L59

This is not catching all exceptions.

This was found by logging `AppDomain.UnhandledException`.

**Comment by andreasohlund** [comment]
Yea :(

We only do this to get a better F5 experience for MSMQ (see #2950) . What version is this btw?

**Comment by johnsimons** [comment]
@ramonsmits I am pretty sure UnhandledException would be logged in the eventviewer ?

**Comment by ramonsmits** [comment]
@andreasohlund This is V5, as you can see on the link (master branch). Not understanding your comment about the F5 experience though. You mean that the send subscription message task is put on the threadpool?

@johnsimons Maybe, but the framework should never result in unhandled exceptions on threadpool tasks.

**Comment by andreasohlund** [comment]
>Not understanding your comment about the F5 experience though. You mean that the send subscription message task is put on the threadpool?

When you start a sample with multiple endpoints for the first time there is a race condition. If the subscribers start before the publisher the publisher queue won't be created. There for we added this "loop" to keep the subscribers retrying to allow the publisher to come up. In production scenarios this is not what we want since the queue not being there == something wrong. (also most likely the publisher would be on a different machine so you wouldn't notice a misconfigured queue). 

In essence a tradeoff btw first time user experience and production robustness. Should we have a transport optimized for samples/first time users we could remove this loop from the MSMQ transport since its a "production" transport.

Does this make sense?

**Comment by andreasohlund** [comment]
I think we're fine in v6 (can you double check @ramonsmits ) since we no longer uses the threadpool?

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs#L58

**Comment by ramonsmits** [comment]
@andreasohlund Its not the loop that causes the issue and thanks for explaining the behavior. That makes a lot of sense indeed an environment where you debug two or more endpoints in a single solution where the queues still need to be created.

The V6 code seems to wait for all tasks to complete and that will probably result in an `AggregateException`. https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs#L47

I do think this is a bug that we should fix in V5. Something like the following: 

* https://github.com/Particular/NServiceBus/pull/3866

**Comment by ramonsmits** [comment]
IMHO it should be patched. You just don't know what is wrong when it hits you.

**Comment by SimonCropp** [comment]
it would not seem to meet any of these patch requirements https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/triage.md#critical-bug-criteria

**Comment by danielmarbach** [comment]
I agree with @SimonCropp It doesn't meet the patch requirements

**Comment by ramonsmits** [comment]
Interesting @SimonCropp that you mention that it doesn't meet patch requirements for a critical bug as the first bullet is *Security related* and this issue is the cause of misconfigured authorization. Second, it also matches *Causes outages in production* as its unclear how to resolve the cause and it you are hit by it your endpoint will not start without knowing why.

**Comment by andreasohlund** [comment]
>Causes outages in production

The question here is: Is it ok for the endpoint to not start up given that it can't subscribe properly?

I'd say yes since if we start the endpoint would not receive published events properly == message loss

If we agree on that behavior the issue here is then that we make it harder for the user to diagnose the issue since we don't log it properly and the only visible trace of the failure is what gets written to the eventlog?

Thoughts?

**Comment by ramonsmits** [comment]
@andreasohlund Yes agreed, the behavior of the endpoint not starting is fine but it should report the reason why that is what this issue is about.

By the way, a suggested fix (#3866) was declined even though I think this should still be patched as I think it meets our patch requirements.

**Comment by andreasohlund** [comment]
It seems that we agree on

>the issue here is then that we make it harder for the user to diagnose the issue since we don't log it properly and the only visible trace of the failure is what gets written to the eventlog?

I don't see this meeting any of the patch requirements?

Since this is fixed in v6 I still think we should close this since its not unlikely for users to look at the eventlog if they have issues with their endpoints?

**Comment by ramonsmits** [comment]
@andreasohlund There was log output of the endpoint. If you have logging output and the process stops you don't really expect that it crashes. It was just because I noticed the log didn't have a 'shutdown' sequence that I concluded that the process crashed. Indeed, the windows event log contained details but that was because of my intervention with this customer. 

> I don't see this meeting any of the patch requirements?

* Security related
* Causes outages in production

Some one at the customer changed queue permissions that resulted in this issue. There was an outage due to our behavior of several hours. The customer was not able to resolve this issue on its own.

Don't you agree with these path requirements?

**Comment by andreasohlund** [comment]
>Security related

I don't see how this is security related? ( yes the customer issue was due to permissions changed but that doesn't make this a security vulnerability=

>Causes outages in production

This is the one that we could argue about. 

1. They changed queue permissions
2. Endpoint didn't start (crashed) with no logs (correct to not start since it would be message loss if we did start)
3. Only logs that that where visible was in the eventlog

Does this qualify as "ouatage in production"?

@Particular/nservicebus-maintainers what do you thing?
@gbiellem  @kbaley your thoughts? (from an ops perspective)

**Comment by danielmarbach** [comment]
@andreasohlund I think @ramonsmits is right, the fact that a customer faced this issue and after few hours of digging they needed to call support and @ramonsmits had to go into event log to see the actual issue means there was a production outtage which cause grief for the customer. If we can we should deal with this. For example by making sure the `MessageQueueException` is properly wrapped in a `QueueNotFoundException`

**Comment by kbaley** [comment]
> There was an outage due to our behavior of several hours.

I'm going to show my ignorance here: Is this specifically _our_ behaviour causing this or is it a consequence of changing the queue permissions? I.e. would changing queue permissions normally be considered a benign operation that shouldn't cause ill-effects? On the surface, it sounds like something I wouldn't normally do in a production environment without trying it on a test environment first.

**Comment by timbussmann** [comment]
I think this discussion went for long enough, let's count the votes? I see this bug in a certain grey area for the critical criteria. I agree with @andreasohlund on the behavior as described on his comment:

> The question here is: Is it ok for the endpoint to not start up given that it can't subscribe properly?

> I'd say yes since if we start the endpoint would not receive published events properly == message loss

yes, there should be better exception handling / logging. But as that PR has already been closed a while ago, I'd say let's stay with the decision made back then and close this. @Particular/nservicebus-maintainers @ramonsmits

**Comment by danielmarbach** [comment]
After talking to @andreasohlund I withdraw my statement https://github.com/Particular/NServiceBus/issues/3854#issuecomment-251207715 and agree with @timbussmann @kbaley and @andreasohlund Let's close this

**Comment by timbussmann** [comment]
Closing this then.
