### ISSUE TITLE
Obsolete Bus class

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3855]
When upgrading a saga the `Bus` property on the base class no resolves to the `Bus` class and we get a "cant find static method" error. 

![image](https://cloud.githubusercontent.com/assets/122666/16248975/28a2f0c8-3856-11e6-8ae3-0d9bfb9ca2cb.png)

But since the Bus class itself is not obsolete it is hard to work out what is wrong

We should obsolete Bus and give a useful message

**Comment by andreasohlund** [comment]
Is this the only place we would get this? (since the saga used to have a `.Bus` property)

How about "Sagas no longer provide access to bus operations via the .Bus property. Use the context parameter on the `Handle` method instead" ?

**Comment by SimonCropp** [comment]
instead is redundant. but i like the rest

**Comment by andreasohlund** [comment]
Also I can find any obsoletes for the  `Saga.Bus` property

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Saga/Saga.cs#L28

should we add it? (would it help)

**Comment by danielmarbach** [comment]
@simoncropp PR is pending and linked

**Comment by timbussmann** [comment]
PR merged
