### ISSUE TITLE
Manual subscriptions fail when migrating from V5 to V6-beta

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#3858]
I have a very simple self-hosted V5 endpoint:

```
var cfg = new BusConfiguration();
cfg.EnableInstallers();

cfg.UsePersistence<RavenDBPersistence>()
    .DoNotSetupDatabasePermissions();

cfg.DisableFeature<AutoSubscribe>();

cfg.Conventions()
    .DefiningCommandsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Commands" ) )
    .DefiningEventsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Events" ) );

using( var bus = Bus.Create( cfg ).Start() )
{
    bus.Subscribe<ISomethingHappened>();

    Console.Read();
}
```

that disables `AutoSubscribe` and forces a subscription when the endpoint starts, it works as expected and the subscription is delivered according to the `MessageEndpointMappings` in the config file.

As I upgrade the endpoint to V6, latest on MyGet:

```
var cfg = new EndpointConfiguration(typeof(Program).Namespace);
cfg.EnableInstallers();

cfg.UsePersistence<RavenDBPersistence>()
    .DoNotSetupDatabasePermissions();

cfg.DisableFeature<AutoSubscribe>();

cfg.Conventions()
    .DefiningCommandsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Commands" ) )
    .DefiningEventsAs( t => t.Namespace != null && t.Namespace.EndsWith( ".Events" ) );

var endpoint = await Endpoint.Start(cfg).ConfigureAwait(false);

await endpoint.Subscribe<ISomethingHappened>().ConfigureAwait(false);

Console.Read();

await endpoint.Stop().ConfigureAwait(false);
```

it fails at startup with the following exception:

> No publisher address could be found for message type ISomethingHappened. Ensure the configured publisher endpoint has at least one known instance.

Even if the `MessageEndpointMappings` are still there and are correctly used if I enable `AutoSubscribe`. The only way to make it work is to explicitly add the following config

```
cfg.UnicastRouting()
    .AddPublisher("MyPublisher", typeof(ISomethingHappened).Assembly);
```

Am I missing something? Is this a bug? a behavior change?
Reading [this](http://docs.particular.net/nservicebus/upgrades/5to6#autosubscribe) it seems that I must declare a publisher, however I was expecting the `MessageEndpointMappings` to be enough.

**Comment by SzymonPobiega** [comment]
@mauroservienti can you take a look at this gist: https://gist.github.com/SzymonPobiega/0c28b5bb44630968204397786df064e1. I've tried to repro it in an acceptance tests but it works just fine. Not sure if that gist is exactly equivalent to your scenario -- can you verify?

**Comment by mauroservienti** [comment]
it is exactly as my failing sample @SzymonPobiega, I'll polish it and push to my github account

**Comment by timbussmann** [comment]
This seems to be something we need to fix for v6.0? @mauroservienti @SzymonPobiega any updates on this?

**Comment by mauroservienti** [comment]
I have a repro, need to find time to isolate it and upload.

**Comment by SzymonPobiega** [comment]
@mauroservienti any updates?

**Comment by mauroservienti** [comment]
Updated my repro from `6.0.0-unstable1729` to `6.0.0-beta0006` and now it works as expected. Closing.
