### ISSUE TITLE
Message Headers for failed message should include processing endpoint

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3872]
For v6 when sending successful message there is a header called ProcessingEndpoint that holds information about the endpoint that processed the message. It is equal to EndpointName. 

For failed messages there is no ProcessingEndpoint header the only information available is FailedQ which contains queue name rather than endpoint name. This cause our underlying products to show value from FailedQ as an endpointName when analyzing failed queues (both in ServiceInsight and ServicePulse). 

It is not seen in most cases as input queue for the most parts is the same as endpoint name, but as we allow users to change queue name: http://docs.particular.net/nservicebus/endpoints/specify-endpoint-name#input-queue 
We are causing confusion as successful messages are marked as processed by endpoint Subscriber1, while error messages by endpoint: someWeirdAddress.

Successful message:
![image](https://cloud.githubusercontent.com/assets/604826/16335970/1977fd9a-3a0a-11e6-92bc-ec615867c618.png)

Failed message:
![image](https://cloud.githubusercontent.com/assets/604826/16335974/1d2f1fc2-3a0a-11e6-8262-d5a756f6e5c9.png)

From what I saw the same behavior is present for v5. 

cc: @Particular/servicecontrol-maintainers @Particular/serviceinsight-maintainers @Particular/servicepulse-maintainers

**Comment by tmasternak** [comment]
@andreasohlund @timbussmann We should be able to solve that as part of https://github.com/Particular/V6Launch/issues/69

**Comment by WojcikMike** [comment]
Moved this issue to: https://github.com/Particular/PlatformDevelopment/issues/860
