### ISSUE TITLE
Should we seal `SecondLevelRetriesConfig` because of Virtual Member call in ctor?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3875]
See https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/SecondLevelRetries/Config/SecondLevelRetriesConfig.cs#L16-L18

## Readings
http://stackoverflow.com/questions/119506/virtual-member-call-in-a-constructor
https://msdn.microsoft.com/en-us/library/ms182331.aspx

**Comment by timbussmann** [comment]
since we want to get rid of the config section, is that even worth the effort since I can't come up with a scenario where you want to derive from that class in the first place? But since it's a trivial change, I'm not against it.

**Comment by andreasohlund** [comment]
Config section is now gone of the release branch
