### ISSUE TITLE
Outbox dispatch mode is slightly broken

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3882]
Currently there are two dispatch modes:
 * `Default` - dispatch according to transport transaction mode
 * `Isolated` - dispatch immediately (not synced with the receive transaction)

Outbox uses the `Isolated` mode. I believe it is wrong. The semantics of outbox are slightly different than `Isolated` mode. `Isolated` means that, given N operations in a dispatch call, they all should succeed or fail atomically. An example would be a publish call that results in 3 messages being dispatch to the subscribers. 

The `Outbox` dispatch mode is more lax. We don't care about atomicity there because, in case of failure, we will retry anyway. Using `Isolated` for outbox dispatch puts unnecessary constraints on the transport.

**Comment by timbussmann** [comment]
> Isolated means that, given N operations in a dispatch call, they all should succeed or fail atomically.

I think we don't apply any batching logic to isolated sends, so each of the n operations itself is sent independent from other isolated messages?

**Comment by SzymonPobiega** [comment]
@timbussmann well, they should be sent together. I just noticed there is bug in MSMQ transport related to that. If I do

```
var ops = new PublishOptions();
ops.ImmediateDispatch();
bus.Publish(new MyMessage(), ops);
```

then I expect that this message will be either delivered to all subscribers or to none of them. The current MSMQ code, as I understand it, would send each to each of the subscribers separately. 

So I see two action points now:
 * [ ] Fix handling of `Isolated` mode in MSMQ to use a single transaction (detached from the receive transaction)
 * [ ] Add more lax `IsolatedFromEachOther` mode that would work same as current implementation of `Isolated` in MSMQ (send each transport op indepdendently of each other)

**Comment by danielmarbach** [comment]
I agree we should fix it for MSMQ. If I recall correctly @SzymonPobiega @tmasternak and I had a discussion when we changed the implementation of the SQL Server dispatcher. As I see it it is fixed for SQL server since Isolated operations are dispatched in the same transaction scope

https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs#L18

Since MSMQ supports natively and by using TxScope [spanning multiple queues ](https://msdn.microsoft.com/en-us/library/ms978430.aspx)I propose we apply the first proposed fix.

On the fence on the second one. I don't think we really need it at this momet.

**Comment by tmasternak** [comment]
:+1:  for the first point.

When it comes to second point: How about changing the Outbox behavior? Can we make sure that it will pass one `TransportOpertion` at a time which will effectively result in `IsolatedFromEachOther`?

**Comment by SzymonPobiega** [comment]
@danielmarbach we don't need it at the moment, but we can't introduce it without breaking the API. It can be very important for SQL Server transport.

**Comment by SzymonPobiega** [comment]
@tmasternak we can't because that would effectively disable batching which would affect the throughput of azure transports.

**Comment by SzymonPobiega** [comment]
Let me spike it.

**Comment by danielmarbach** [comment]
Ok I'll wait for the spike until I throw in my devils advocate sentence ;)

**Comment by SzymonPobiega** [comment]
After talking to Andreas I am closing this one. The `ReceiveOnly` mode in which the outbox runs does not imply that all operations need to be dispatched atomically.

**Comment by adamralph** [comment]
@Particular/platform-dev-squad what did we say about this one?

**Comment by danielmarbach** [comment]
@adamralph labelled it

**Comment by adamralph** [comment]
Thanks @danielmarbach
