### ISSUE TITLE
Avoid closure capturing in `Task.ContinueWith`

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3883]
If you pass any context (this, an instance member,or a local variable) to a lambda, caching won’t work to a closure.

If we make sure we don't capture state we can benefit from lambda delegate caching and generally save allocations per closure.

Sounds like not worth optimizing for? Keep in mind that when executing hundreds of operations concurrently allocations like that can easily add up.

```ini

BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU E5-2673 v3 2.40GHz, ProcessorCount=8
Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0

Type=ContinueWithBenchmarks  Mode=Throughput  

```
              Method |    Median |    StdDev | Scaled |      Mean |  StdError |    StdDev |      Op/s |       Min |        Q1 |    Median |        Q3 |       Max | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
-------------------- |---------- |---------- |------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |------ |------ |------ |------------------- |
        ContinueWith | 1.4619 us | 0.0958 us |   1.00 | 1.4484 us | 0.0110 us | 0.0958 us | 690426.13 | 1.1596 us | 1.4091 us | 1.4619 us | 1.5169 us | 1.6524 us | 39.75 | 19.50 |     - |              58.61 |
 ContinueWithClosure | 1.4960 us | 0.1938 us |   1.02 | 1.4654 us | 0.0396 us | 0.1938 us | 682392.75 | 0.6727 us | 1.4612 us | 1.4960 us | 1.5093 us | 1.7665 us | 91.00 | 19.00 |     - |              82.30 |

**Comment by timbussmann** [comment]
how many `Task.ContinueWith` do we have?

**Comment by danielmarbach** [comment]
@timbussmann one. Already fixed and proposed as PR.

**Comment by timbussmann** [comment]
do we need to add this to some "performance guidelines"?

**Comment by Scooletz** [comment]
This is a really nice catch!

**Comment by timbussmann** [comment]
@danielmarbach what else do we need to do since all PRs seem to be merged?

**Comment by danielmarbach** [comment]
If I haven't missed one let's close it

**Comment by timbussmann** [comment]
closing this then :+1:
