### ISSUE TITLE
Avoid closure capturing in Task.Run

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3884]
If you pass any context (this, an instance member,or a local variable) to a lambda, caching won’t work to a closure.

If we make sure we don't capture state we can benefit from lambda delegate caching and generally save allocations per closure.

Sounds like not worth optimizing for? Keep in mind that when executing hundreds of operations concurrently allocations like that can easily add up.

Ultimately this means the following for our code

Instead of `Task.Run` we need to use `Task.Factory.StartNew`. For async code it means instead of 

`Task.Run(async() => { access closure state here });`

we will rewrite it to

``` 
Task.Factory.StartNew(async state =>
            {
                var externalState = (State)state;
            }, passStateInHere, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default)
.Unwrap();
``` 

```ini

BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU E5-2673 v3 2.40GHz, ProcessorCount=8
Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0

Type=TaskRunVsTaskFactoryClosure  Mode=Throughput  

```
                    Method |    Median |    StdDev | Scaled |      Mean |  StdError |    StdDev |      Op/s |       Min |        Q1 |    Median |        Q3 |       Max | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
-------------------------- |---------- |---------- |------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |------ |------ |------ |------------------- |
 TaskFactoryWithoutClosure | 1.4423 us | 0.1124 us |   1.00 | 1.4257 us | 0.0193 us | 0.1124 us | 701406.94 | 1.0964 us | 1.3922 us | 1.4423 us | 1.4811 us | 1.6555 us | 10.81 |     - |     - |              37.38 |
        TaskRunWithClosure | 1.4831 us | 0.0626 us |   1.03 | 1.4882 us | 0.0140 us | 0.0626 us | 671969.58 | 1.4195 us | 1.4485 us | 1.4831 us | 1.5046 us | 1.7071 us | 21.00 |     - |     - |              65.89 |

**Comment by bording** [comment]
:+1: I've already started applying this pattern where appropriate in the RabbitMQ transport.

**Comment by bording** [comment]
Given how much noisier `Task.Factory.StartNew` is to use, it might be a good idea to add some helper methods to `TaskEx`:

```csharp
public static Task Start(object state, Action<object> action) => Task.Factory.StartNew(action, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);

public static Task Start(object state, Func<object, Task> function) => Task.Factory.StartNew(function, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default).Unwrap();
```

**Comment by danielmarbach** [comment]
@bording absolutely agree!

**Comment by timbussmann** [comment]
@danielmarbach what do we do with this issue? Are there still places we can "fix"? I think there were several PR's related to this which aren't linked to this issue or am I confusing things again?

**Comment by timbussmann** [comment]
ah just realized they were linked to https://github.com/Particular/NServiceBus/issues/3883

**Comment by danielmarbach** [comment]
I did some analysis. 

```
Find all "Task.Run", Subfolders, Find Results 1, Entire Solution, ""
  C:\particular\NServiceBus\src\NServiceBus.Core\CriticalError\CriticalError.cs(68):            Task.Run(() =>
  C:\particular\NServiceBus\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs(41):            timeoutPollerTask = Task.Run(() => Poll(token));
  C:\particular\NServiceBus\src\NServiceBus.Core\Routing\FileBasedDynamicRouting\AsyncTimer.cs(14):            task = Task.Run(async () =>
  C:\particular\NServiceBus\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs(72):            messagePumpTask = Task.Run(() => ProcessMessages(), CancellationToken.None);
  C:\particular\NServiceBus\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs(149):                    var receiveTask = Task.Run(async () =>
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Features\FeatureStartupTests.cs(33):            var builder = new FakeBuilder(typeof(FeatureWithStartupTask.Runner));
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Features\FeatureStartupTests.cs(40):            Assert.True(FeatureWithStartupTask.Runner.Started);
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Features\FeatureStartupTests.cs(41):            Assert.True(FeatureWithStartupTask.Runner.Stopped);
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Persistence\InMemory\When_multiple_workers_retrieve_same_saga.cs(42):            var returnedSaga1 = await Task.Run(() => persister.Get<TestSagaData>(saga.Id, new InMemorySynchronizedStorageSession(), new ContextBag()));
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Persistence\InMemory\When_multiple_workers_retrieve_same_saga.cs(118):            var returnedSaga1 = await Task.Run(() => persister.Get<TestSagaData>(saga.Id, new InMemorySynchronizedStorageSession(), new ContextBag()));
  C:\particular\NServiceBus\src\NServiceBus.Core.Tests\Persistence\InMemory\When_multiple_workers_retrieve_same_saga.cs(130):            var returnedSaga3 = await Task.Run(() => persister.Get<TestSagaData>("Id", saga.Id, new InMemorySynchronizedStorageSession(), new ContextBag()));
  C:\particular\NServiceBus\src\NServiceBus.AcceptanceTesting\Support\EndpointRunner.cs(109):                    await Task.Run(async () =>
  Matching lines: 12    Matching files: 7    Total files searched: 1251
```

Most of them can't be replaced because they capture over to many fields. When you want to replace those with `Task.Factory.StartNew` you end up wrapping the data in a `Tuple<T1,...,TN>` and then all the benefits are gone. I'm OK to close this from a core perspective

**Comment by bording** [comment]
Even if you need to to create a custom state class to transfer all the captured fields, there is still a benefit. Behind the scenes, the compiler is already creating that class anyway to implement the closure.

So, if you were to manually create a state class to pass to StartNew, there is still the benefit of not creating the delegate on every call.

**Comment by danielmarbach** [comment]
@bording I did some micro-benchmarking. As soon as this class captures more than 2 reference types the benefit is almost gone. I'll send in the results soon

**Comment by danielmarbach** [comment]
Fixed with https://github.com/Particular/NServiceBus/pull/3951
