### ISSUE TITLE
Set logging destination folder in config

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3902]
The documentation shows that the logging destination folder can only be set via code:

http://docs.particular.net/nservicebus/logging/

```c#
var defaultFactory = LogManager.Use<DefaultFactory>();
defaultFactory.Directory("pathToLoggingDirectory");
```
It should be possible to change that using config:

```xml
<configSections>
  <section name="Logging" 
           type="NServiceBus.Config.Logging, NServiceBus.Core" />
</configSections>
<Logging Threshold="Debug" Directory="D:\logs\myapp\" />
```

That would prevent custom initialization like:

```xml
<appSettings>
    <add Key="NServiceBus/Logging/Directory" Value="D:\logs\myapp\"/>
</appSettings>
```

```c#
var defaultFactory = LogManager.Use<DefaultFactory>();
var path = ConfigurationManager.AppSettings["NServiceBus/Logging/Directory"];
defaultFactory.Directory(path);
```

Especially because this needs to be called before the first log entry is written.

**Comment by SimonCropp** [comment]
-1

 * as you have shown there is a valid way to do this already.
 * code is flexible where config is now
 * no point duplicating functionality that is less flexible than the existing code approach
 * if people really want this they can, and should, be switching to any of the the full logging frameworks

**Comment by ramonsmits** [comment]
> * as you have shown there is a valid way to do this already.

But requires a code change, a build and a new deployment and most important probably a change request at the dev team which takes days if not weeks.

> * code is flexible where config is not
> * no point duplicating functionality that is less flexible than the existing code approach

Config is flexible is you take (1) into consideration

> * if people really want this they can, and should, be switching to any of the the full logging frameworks

I disagree, if that is the case then why do we even have `.Directory(path)`.

Try looking at this while wearing an operational hat.

**Comment by SimonCropp** [comment]
@ramonsmits this discussion has been had several time over the years eg https://github.com/Particular/NServiceBus/issues/2478  so far you have not added anything new or compelling that would change the current direction

in summary. file based config is

 - less discoverable
 - less flexible
 - results in a single "god configuration file" (see where wcf failed)
 - harder to obsolete
 - create ordering issues in which comes first
 - harder for consumers to write tests when using them

> Try looking at this while wearing an operational hat.

I have heard this several times. it effectively equates to "let optimise for an environment where devs dont communicate to ops" this is doomed to result in poor api decisions.

**Comment by SimonCropp** [comment]
also if u want to change the direction a PR done to this https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/discoverability.md is probably better

**Comment by danielmarbach** [comment]
Agreed with the reasonings outlined by @SimonCropp . Closing this one as won't fix.
