### ISSUE TITLE
Setting MessageId in Message Mutator is ignored V6

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3907]
Found while [documenting the ability to set message Id via SendOptions](https://github.com/Particular/docs.particular.net/pull/1667)

In the past, the recommended way to set message Id on an outgoing message is to set the NServiceBus.MessageId header from within a Message Mutator. This will fail silently in V6 as the header gets overwritten later in the pipeline ([specifically here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPhysicalToRoutingConnector.cs#L12))

We should either detect that the message mutator has updated this particular header and set the underlying message id accordingly OR detect that the header has been updated and throw with a message articulating the correct way to perform this action.

**Comment by danielmarbach** [comment]
@mikeminutillo not even sure why this code is there in the first place. We might need to involve @SzymonPobiega @timbussmann @bording or @DavidBoike they are currently knee deep into routing

**Comment by timbussmann** [comment]
I think we shouldn't to the first option. We have specific APIs to set the message id and should avoid a duality there. Not against detecting potential misuse of the headers to bypass existing APIs.

**Comment by mikeminutillo** [comment]
Created a PR to detect modifications to the message id header from outgoing message mutators and throw. This will at least prevent difficult to diagnose issues. If customers really want this behavior we'll have to revisit it. 

@SimonCropp brought up the point that all of those contexts should probably rely on `IDictionary<string, string>` to represent headers rather `Dictionary<string, string>` because it will make it easier to change those implementations later if we need to.

**Comment by johnsimons** [comment]
Why this breaking change, what is wrong with supporting updating the message id via outgoing mutator, specially since that was the recommended way in the past and sometime is not possible at send time to set it.
Eg. the mutator could be a piece of middleware that the devops puts in.
And yes I am aware that the middleware can be a behaviour in the pipeline, but still that would be more changes a dev would have to do to update their code.

All I am saying is that it seems we are about to add restrictions to something that we probably should not.

**Comment by timbussmann** [comment]
> what is wrong with supporting updating the message id via outgoing mutator

bcause there is logic which acts on the configured message id earlier, and changing that "mid flight" will break all of this, so therefore it's not allowed.

**Comment by danielmarbach** [comment]
I opened up a counter proposal here https://github.com/Particular/NServiceBus/pull/3961. Discussed it with @timbussmann I vote for taking that simple approach.

**Comment by weralabaj** [comment]
The PR https://github.com/Particular/NServiceBus/pull/3961 has been merged, is that issue resolved?
