### ISSUE TITLE
Validate endpoint in routing API?

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3914]
The following configurations will throw a runtime exception when sending/subscribing because the final address will end up being "v6@localhost@localhost":

`routingSettings.RouteToEndpoint(typeof(MyMessage), "v6@localhost");`
`routingSettings.RegisterPublisherForType("v6@localhost", typeof(MyEvent));`

I could imagine it's fairly easy to write the lines above when migrating from the MessageEndpointMapping configuration, which allows physical addresses, to the new routing API. Should we check the parameters at configuration time to throw a better exception at startup?

**Comment by danielmarbach** [comment]
I can imagine that as well since users might end up copy pasting stuff. Any help we can provide to make the transition a good experience is definitely something worth investing our time

**Comment by timbussmann** [comment]
should we add this to the routing PoA or just give it maintainer prio?

**Comment by weralabaj** [comment]
is there a reason why `RouteToEndpoint` is exposed in a different place than `RegisterPublisherForType`? Is the latter only used by msmq and sql server?

Also I think we could add similar check for `UnicastRoutingTable` for `RouteToEndpoint` and `RouteToAddress`.

**Comment by timbussmann** [comment]
> is there a reason why RouteToEndpoint is exposed in a different place than RegisterPublisherForType? Is the latter only used by msmq and sql server?

both should be exposed on config.UseTransport<TransportDefinition>().Routing(), otherwhise please update to latest `release-6.0.0`? If you mean by the extension class containing these methods: Yes, the later is only required for message driven pub/sub transports.

> Also I think we could add similar check for UnicastRoutingTable for RouteToEndpoint and RouteToAddress

RouteToAddress may contain `@` (since it's the address) while `RouteToEndpoint` is called by `routingSettings.RouteToEndpoint`. So I'd say let's have these checks on the endpoint config related APIs for now?

**Comment by weralabaj** [comment]
The difference is subtle, and I think it might matter only from tests perspective (?). If I use `UseTransport(transport)` it doesn't expose `RegisterPublisherForType`, but `UseTransport<T>()` does.

https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs#L47 works for `RoutingSettings<T>`

https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Routing/RoutingSettings.cs#L24 works both for  `RoutingSettings<T>` and  `RoutingSettings`

Or am I missing some PR being merged? :)

**Comment by weralabaj** [comment]
Are those settings in separate classes for a specific purpose or is that accidental and could be merged?

**Comment by timbussmann** [comment]
> The difference is subtle, and I think it might matter only from tests perspective (?). If I use UseTransport(transport) it doesn't expose RegisterPublisherForType, but UseTransport<T>() does.

yes, this is intended since `RegisterPublisherForType``is transport specific and for that to be enabled only on supported transports, it needs to be on the generic settings.

> Are those settings in separate classes for a specific purpose or is that accidental and could be merged? 

yes they are, publisher configuration is separated from regular message routing configuration.

let me know in case you have further questions, it's probably easier to go through some parts of the API in a call.

**Comment by weralabaj** [comment]
OK, that's all I needed to know for now, thanks :)

**Comment by danielmarbach** [comment]
Fixed in https://github.com/Particular/NServiceBus/issues/3927
