### ISSUE TITLE
NewtonsoftSerializer does not allow configuration when used as a deserializer

### ISSUE THREAD

**Issue by dloukola** [Particular/NServiceBus#3919]
The serializer for NewtonsoftSerializer works great with custom settings, but the deserializer does not offer this same feature.

I would expect to do the following:
 
SerializationExtensions<NewtonsoftSerializer> serializer = endpointConfiguration.AddDeserializer<NewtonsoftSerializer>();
            
//Allow inherited types in messages
JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.All
};
serializer.Settings(jsonSerializerSettings);

**Comment by danielmarbach** [comment]
@dloukola we use an internalized version of JSON.NET which [is not configurable](http://docs.particular.net/nservicebus/serialization/json#customization). If you need special configuration and type handling I recommend you to use the [Newtonsoft JSON serializer ](http://docs.particular.net/nservicebus/serialization/newtonsoft)which is shipped as an [external package](https://www.nuget.org/packages/NServiceBus.Newtonsoft.Json/). It allows to pass in [serializer settings](http://docs.particular.net/nservicebus/serialization/newtonsoft#usage-custom-settings)

**Comment by dloukola** [comment]
@danielmarbach I understand, that is not my problem. In NSB 6, you can have serializers and deserializers. 
**Example:** 

1. System A's main serialization is JSON. It uses NewtonSoftSerializer with custom settings. 
2. System B's main serialization is XML. 
3. System A wants to send a message to System B. 

This can be achieved now by adding the configuration "AddDeserializer" to System B's configuration. However, there is no option to add the custom settings to the "AddDeserializer" as there is when you add custom settings to the serializer.

**Comment by danielmarbach** [comment]
@dloukola I'm sorry! My bad. Will investigate.

**Comment by danielmarbach** [comment]
@dloukola I submitted a PR https://github.com/Particular/NServiceBus/pull/3923

**Comment by timbussmann** [comment]
since this will be fixed with the next v6 beta version, I think we can close this @danielmarbach ?

**Comment by danielmarbach** [comment]
Correct
