### ISSUE TITLE
Move Persistence/StorageType to root NServiceBus namespace

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3921]
Since its used by end users

**Comment by danielmarbach** [comment]
Can we postpone that for vNext?

**Comment by andreasohlund** [comment]
Reopening until I get downstreams and docs in order

**Comment by andreasohlund** [comment]
I've verified that this isn't a breaking change (SqlP updates fine).

Upgrade guide PR opened: https://github.com/Particular/docs.particular.net/pull/3288
