### ISSUE TITLE
Move Log/DefaultFactory to the root NServiceBus namespace

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3922]
Since its used by end users

**Comment by danielmarbach** [comment]
Can we postpone that for vNext?

**Comment by danielmarbach** [comment]
Discussed with @timbussmann and we don't see much value in this. Moving LogManager is a breaking change which in this case doesn't provide any value for our customers. The only ones which would get value out of it would be us from an alignment perspective. Closing.

**Comment by andreasohlund** [comment]
Hmm, isn't this similar to eg renaming `Transports` => `Transport`. 

We have a namespace rule that config methods targeted at users should be in the root `NServiceBus` namespace, this violates this, I'd say it should be considered as a low hanging fruit for the next major since it's trivial and caused pretty much no friction for the users?
