### ISSUE TITLE
Purging Audit Tables

### ISSUE THREAD

**Issue by rahulsax** [Particular/NServiceBus#3930]
We have Audit and Error Queues configured in SQL server. We used to purge these tables during our releases where we STOP the services and then purge the tables, now we don't have the frequent releases and audit tables are growing massively. Can we purge these tables without STOPPING the services?
Our system runs 24 * 7 and we don't want to stop the services to purge these tables.

**Comment by danielmarbach** [comment]
@rahulsax I don't think purging all the content is a good idea. Since endpoints would still be inserting data while running into that table. So I suggest you either determine based on the RowVersion which entries can be deleted and filter them out in your delete statement based on the RowVersion. You can also use `OverrideTimeToBeReceived` described here http://docs.particular.net/nservicebus/operations/auditing#configuring-auditing which makes messages expire in the audit queue if they reach a certain threshold. Does that help?

**Comment by rahulsax** [comment]
Hi Daniel,
Thank you for you reply.
I don't want to use delete as it will again create huge transaction logs which can be a overhead to the system.
I will explore more on OverrideTimeToBeReceived as I understand it removes messages from Queue after time is elapse, in our case we have messages in SQL Server instead of MSMQ so need to understand the behavior there.

**Comment by danielmarbach** [comment]
@rahulsax In SqlServer transport there is a background operation which triggers the following statement

DELETE FROM {1}.{2} WHERE [Id] IN (SELECT TOP ({0}) [Id] FROM {1}.{2} WITH (UPDLOCK, READPAST, ROWLOCK) WHERE [Expires] < GETUTCDATE() ORDER BY [RowVersion])

By default it does that every 5 minutes and the batch size is 10000

**Comment by MarcinHoppe** [comment]
@rahulsax @danielmarbach Please bear in mind that expired messages will be purged from queue tables only if there is an endpoint that received messages from this queue? Are these error and audit queues being consumed by a tool such as ServiceControl? 

I suggest we move the issue to the SQL Server transport repo.

**Comment by rahulsax** [comment]
Thanks Marcin,
We don't have any consumer for these queues. So it could be possible that OverrideTimeToBeReceived will not work for us?

**Comment by rahulsax** [comment]
Can I use the truncate without stopping the services if I know that there will not be any activity in the system during that window.

**Comment by MarcinHoppe** [comment]
@rahulsax If you don't consume messages from these queues, then `OverrideTimeToBeReceived` will not help. The SQL Server transport does not have any component that runs on the broker that could purge expired messages. An endpoint is needed to run this code (normally this would be ServiceControl or a custom endpoint that monitors error and audit queues),

If you are sure you do not need messages in error and audit queues, then you can use `TRUNCATE TABLE` to purge them. Indeed it will be a lot easier on the transaction log than (even batched) `DELETE` statements.

**Comment by danielmarbach** [comment]
If the audit messages are not used, why even collect them? Wouldn't it make more sense to disable auditing entirely?

**Comment by rahulsax** [comment]
We do want audit messages in-case we want to backtrack the  messages and currently only for last 15 days. In future we may disable the messages altogether.
Thank you guys for your prompt reply and helping me in resolving my query and I think I can close my thread.
