### ISSUE TITLE
MSMQ Distributor with combined worker tries to send failed messages to Retry queue instead of error queue, causing the endpoint to shutdown.

### ISSUE THREAD

**Issue by omega1970** [Particular/NServiceBus#3944]
When using a distributor with worker, there is no Retries queue...so this should not happen, right? Any help is appreciated.

Using NServiceBus 5.2.14
MessageForwardingInCaseOfFaultConfig ErrorQueue="error@svchost-tst"
AuditConfig QueueName="audit@svchost-tst"

FATAL NServiceBus - Fault manager failed to process the failed message with id 0aa96788-14c4-4f38-b360-a64700fea59d
System.InvalidOperationException: Could not forward failed message to error queue 'ProjectInstanceService.Retries@svchost-tst' as it could not be found. ---> NServiceBus.Unicast.Queuing.QueueNotFoundException: Failed to send message to address: [ProjectInstanceService.Retries@svchost-tst] ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.

**Comment by danielmarbach** [comment]
Related Google Group Case https://groups.google.com/forum/#!topic/particularsoftware/ACLds2sFVIY

**Comment by danielmarbach** [comment]
Moved to https://github.com/Particular/NServiceBus.Distributor.Msmq/issues/42#issuecomment-234540301
