### ISSUE TITLE
Make transport selection mandatory

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#3945]
I think making transport selection mandatory is a must for V6.
- Everyone but MSMQ has to do it anyway.
- All routing APIs are now scoped in there, so making it mandatory will make the routing API more discoverable for MSMQ users.
- Require transport in V6 gives us a path for .NET Core: We relax the requirement in V7, with the new default value being a development-time transport.
  - If we do not, then what does a V6 solution with no UseTransport call mean when upgraded to V7?
- Enables better, more obvious guidance than "It's not required to set it, but you really really should."

@Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
This is not going to make it for v6, removing the consider for label

**Comment by andreasohlund** [comment]
Should we consider to start logging a WARN in 6.3 to prepare users for v7? (since msmq will go out of the core)

**Comment by dbelcham** [comment]
Sounds like a good idea to me.

**Comment by danielmarbach** [comment]
Good idea. I wonder if it would be so bad to make it mandatory immediately. I know "breaking chance" but is it worth being religious here?

**Comment by DavidBoike** [comment]
Because all the routing API is accessed via UseTransport, and we're also warning if you're using MessageEndpointMappings, I think it's sufficient to warn in 6.x.

**Comment by timbussmann** [comment]
> Should we consider to start logging a WARN in 6.3 to prepare users for v7? (since msmq will go out of the core)

not really sure about the value this would yield? In the best case, you configure the transport on version before it's mandatory, what would this really change?

I think we should rather spend some thoughts about the transport configuration API. The current API is not well suited for a mandatory option.

**Comment by andreasohlund** [comment]
We need to do this since MSMQ is being moved out, assigning this to the v7 milestone

**Comment by timbussmann** [comment]
implemented by https://github.com/Particular/NServiceBus/pull/4742 🎉
