### ISSUE TITLE
GetAvailableTypes is used many times in the startup logic

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3947]
Settings.GetAvailableTypes is used 14 times in the core startup logic. Most of these calls filter by Conventions.IsMessageType. Let's cache the result for once and expose it on the settings.

**Comment by timbussmann** [comment]
@danielmarbach do we want to invest more time besided #3938 or should we close this?

**Comment by danielmarbach** [comment]
Think it is good right now. We can always reopen other issues if required
