### ISSUE TITLE
Reveal intent and improve discoverability by renaming ForwardReceivedMessagesTo and SendFailedMessagesTo

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3973]
Rename `endpointConfiguration.ForwardReceivedMessagesTo(string)` and / or `endpointConfiguration.SendFailedMessagesTo(string)`

Current:

``` c#
cfg.ForwardReceivedMessagesTo("audit");
cfg.SendFailedMessagesTo("error");
```

I wondered why these are not named similarly as their behavior is both about forwarding a message.

``` c#
cfg.ForwardReceivedMessagesTo("audit");
cfg.ForwardFailedMessagesTo("error");
```

And while at it I wondered why we do not differentiate between _Completed_ and _Failed_. The name _ForwardReceivedMessagesTo_ suggests that the message is always forwarded no matter the outcome.

The following names would make the intent more visible and also makes there more discoverable.

``` c#
cfg.ForwardCompletedMessagesTo("audit");
cfg.ForwardFailedMessagesTo("error");
```

@danielmarbach mentioned that there has been a discussion about these methods in the past but I couldn't find it in Slack / GitHub.

**Comment by danielmarbach** [comment]
@ramonsmits 

https://github.com/Particular/NServiceBus/pull/3941

Here we proposed to move the error queue to recoverability since it actually belongs there

```
configuration.Recoverability().Failed(failed => failed.SendTo("errorQueue"));
```

The only problem we see is since currently specifying the error queue is mandatory uses would always need to write

```
configuration.Recoverability().Failed(failed => failed.SendTo("errorQueue"));
```

@timbussmann suggested making the error queue non-mandatory again and by default assign it to "error"

**Comment by timbussmann** [comment]
> And while at it I wondered why we do not differentiate between Completed and Failed. The name ForwardReceivedMessagesTo suggests that the message is always forwarded no matter the outcome.

I think you are confusing auditing (`AuditProcessedMessagesTo`) with forwarding (`ForwardReceivedMessagesTo`)? (But I have to admit that I never really understood why we need to have both...)

**Comment by timbussmann** [comment]
btw. :+1: on aligning naming, but as @danielmarbach pointed out, I already suggested to make the error-queue a default value instead of always forcing the user to configure one.

**Comment by ramonsmits** [comment]
Consider also the term *Move* as mentioned by @adamralph https://github.com/Particular/NServiceBus.RabbitMQ/pull/188/files#r72291607

**Comment by timbussmann** [comment]
:-1: for the term move. Move is usually a `Cut & Paste` semantic. This could be understood as "don't process the message on this endpoint, but move it to X". I think forward is the better word here.

Since the error queue is undergoing several changes anyway, should we ignore that and instead focus on the audit queue and the forwarding? So we have:

```
cfg.ForwardReceivedMessagesTo("not-audit");
cfg.AuditProcessedMessagesTo("audit");
```

At first glance, I don't think we should rename `AuditProcessedMessagesTo` to `ForwardProcessedMessagesTo` or something similar. Having "Audit" in the config name seems valuable to me. We usually refer to auditing and audit queue therefore the config option should also contain "audit" for better discoverability.

**Comment by ramonsmits** [comment]
@timbussmann I like the term probably because I'm very used to it :-) however, I also really like to term *journal* but maybe that is very conflicting with MSMQ although its behavior is pretty similar (stored in the queue after it is processed) and maybe even the term log in combination with audit?

If these config values are grouped by 

Maybe one of the following :

````
cfg.AuditForwarding(x => x.ToQueue = "audit") // My most favorite
cfg.Auditing(x => x.ForwardToQueue = "audit") 
cfg.Audit(x => x.ForwardToQueue = "audit") 
cfg.AuditLogging(x => x.ForwardToQueue = "audit") // My least favorite
```

**Comment by andreasohlund** [comment]
>cfg.AuditForwarding(x => x.ToQueue = "audit") // My most favorite

That mixes "audit" and "forwarding" so 👎 

I would propose:

`ForwardReceivedMessagesTo` => `ForwardProcessedMessagesTo`

but leave the [error config](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/Faults/ConfigureError.cs#L13) as is

**Comment by danielmarbach** [comment]
It seems we have different opinions represented here. Can we reach to a conclusion asap and then spin-off dedicated issues and close this one?

**Comment by ramonsmits** [comment]
> ForwardProcessedMessagesTo

@andreasohlund Although I like the term processed it's not unambiguous. Are we forwarding *after* processing for successful processed messages or also after correct error handling? Its better then *Received* as that doesn't make it clear when we forward/move/send to the audit queue. 

So you suggest:
```
cfg.ForwardProcessedMessagesTo("audit");
cfg.SendFailedMessagesTo("error");
```

The naming issue remains why I originally opened the issue. Why is one using *Forward* and the other *Send*?

@danielmarbach Shall we do a zoom session?

**Comment by adamralph** [comment]
At this stage I think a zoom call is probably the best way to wrap up this discussion. Count me in, I always love a good naming debate. 😸

**Comment by timbussmann** [comment]
@ramonsmits if you're still interested in this, can you schedule a call including @Particular/nservicebus-maintainers and @adamralph to discuss this and come to a conclusion?

**Comment by timbussmann** [comment]
closing this as the discussion seems to have stalled and nobody is interested in driving this forward actively.
