### ISSUE TITLE
Unobtrusive message types break polymorphic handler behavior

### ISSUE THREAD

**Issue by Tsjunne** [Particular/NServiceBus#3975]
The following behavior is different from v5 to v6:

- I have defined a custom `IMyCommand` interface and registered it as such in the convension config using `convensions.DefiningCommandsAs(t => typeof(IMyCommand).IsAssignableFrom(t))` on both sender and receiver
- I have a handler `GenericHandler` implementing `IHandleMessages<IMyCommand>`
- A command `ConcreteCommand` implementing `IMyCommand` will be handled by `GenericHandler`

In v5 the command comes in as `ConcreteCommand`.
In v6 the command comes in as `IMyCommand_impl` generated proxy

The behavior remains the same in v6 as in v5 when not using unobtrusive message types

**Comment by bording** [comment]
Hi @Tsjunne,

I believe this has already been addressed by https://github.com/Particular/NServiceBus/pull/3926. 

You should see this included in the next beta release.

**Comment by Tsjunne** [comment]
OK, cool!
Thx for the update!

**Comment by timbussmann** [comment]
Indeed, this should be fixed on the next beta version which should be available soon. Let's keep that open until @Tsjunne can verify this is working with the new beta.

**Comment by timbussmann** [comment]
Hey @Tsjunne NServiceBus v6 beta7 is available on NuGet: https://www.nuget.org/packages/NServiceBus/6.0.0-beta0007
Can you verify that your issue is resolved?

**Comment by Tsjunne** [comment]
Hey @timbussmann, 
It looks like now the type comes in correctly, although no properties of the concrete command are set
So something changed, but it doesn't look like the behavior is correct.

I also tried adding some properties to the IMyCommand interface, but none of those are set either in this case, all properties are default values

**Comment by andreasohlund** [comment]
What serializer are you using?

In essense your handler for ConcreteCommand is called but the properties are not set even thought the raw payload has values set?

**Comment by Tsjunne** [comment]
Exactly.

The payload on the wire has everything set, including correct headers and body. I haven't configured any serializer, so it defaults to XML. I'm using the RabbitMQ transport.

When changing the tagger interface for command messages from the custom one to the NServicebus one, everything works as expected. 

The conventions are set as follows:

`endpointConfiguration.Conventions().DefiningCommandsAs(t => t.Name.EndsWith("Command"));`

My handler is set up as:

`IHandleMessages<Shared.ICommand>` for custom interface scenario (no properties set)
`IHandleMessages<NServicebus.ICommand>` for native interface scenario (all properties set)

In both cases the correct concrete command class comes in.

When using other conventions, like based on interface type, the behavior is still incorrect for the custom interface and correct for the native one.

The observed change in the unobtrusive scenario between beta0004 and beta0007 is:

beta0004: all properties mapped, but generated class in stead of correct concrete class
beta0007: no properties mapped, but correct concrete class

**Comment by danielmarbach** [comment]
@Tsjunne I got a repro https://github.com/Particular/NServiceBus/pull/4095 I also have a potential fix on my machine. Will keep you posted

**Comment by danielmarbach** [comment]
@Tsjunne pushed the fix

**Comment by timbussmann** [comment]
this should be fixed and available on the current release candidate as daniel's PR was merged. Closing this. @Tsjunne please comment in case you're still getting wrong behavior.
