### ISSUE TITLE
TimeToBeReceived does not work with unobtrusive mode in v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3989]
## Who's affected

* All users of v6 (beta customers) which are using unobtrusive mode in conjunction with TimeToBeReceived.

## Symptoms

* The new assembly scanner excludes all assemblies from assembly scanning that do not reference NServiceBus directly. Message types that are handled on a receiver will be automatically readded to the type list. Unfortunately time to be received settings and the behavior rely on a type mapping. So if you have an unobtrusive convention for messages and time to be received the message type is never contained in the scanned type list and therefore the TTBR will never be added to the message.

## Steps to reproduce

* Use http://docs.particular.net/samples/unobtrusive/?version=core_6 with beta 
* Send `MessageThatExpires`
* Message should never be received when the receiver is started later than the expiry

**Comment by danielmarbach** [comment]
A reproduction test is already available https://github.com/Particular/NServiceBus/pull/3988

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus/pull/3988 has been merged. I will smoke test it with the sample as well and then close this issue

**Comment by andreasohlund** [comment]
@danielmarbach did you check? (should be able to quickly tweak http://docs.particular.net/samples/databus/?version=core_6 )

**Comment by danielmarbach** [comment]
Yes I did. Works. The header is now present with that sample
