### ISSUE TITLE
Property Encryption does not work with unobtrusive mode in v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3990]
## Who's affected

* All users of v6 (beta customers) which are using unobtrusive mode in conjunction with property encryption.

## Symptoms

* The new assembly scanner excludes all assemblies from assembly scanning that do not reference NServiceBus directly. Message types that are handled on a receiver will be automatically readded to the type list. Unfortunately encryption settigs and the behavior rely on a type mapping. So if you have an unobtrusive convention for messages and an encrypted property convention the message type is never contained in the scanned type list and therefore the encryption feature disables itself behind the scene automatically.

## Steps to reproduce

* Use http://docs.particular.net/samples/unobtrusive/?version=core_6 with beta 
* Send `MyCommand`
* The command is sent without encrypted data
* The receiver blows up with the exception from https://github.com/Particular/NServiceBus/issues/3986

**Comment by timbussmann** [comment]
#3991 is merged. Since it contains an acceptance tests for the described scenario I'm closing this.
