### ISSUE TITLE
missing changes related to immediate and delayed retries

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3995]
Connects to https://github.com/Particular/V6Launch/issues/69

 * [ ] `ErrorsNotifications.MessageHasFailedAFirstLevelRetryAttempt`
 * [ ] `ErrorsNotifications.MessageHasBeenSentToSecondLevelRetries`
 * [ ] `FirstLevelRetry`
 * [ ] `SecondLevelRetry`
 * [ ] `SecondLevelRetriesConfig` should be obsolete
 * [ ] `SecondLevelRetriesSettings` should be obsolete
 * [ ] `SecondLevelRetriesConfigExtensions` should be obsolete
 * [ ] `RecoverabilityExecutor` line 66 logs the message `Logger.Info($"First Level Retry is...` and line 95 `Logger.Warn($"Second Level Retry will reschedule `

**Comment by danielmarbach** [comment]
Thanks will fix

**Comment by SimonCropp** [comment]
Also r there some pipeline steps that need to be renamed?

**Comment by timbussmann** [comment]
can we connect that to the recoverability issue @danielmarbach ?

**Comment by danielmarbach** [comment]
@timbussmann done

**Comment by mikeminutillo** [comment]
The obsolete message on the `SecondLevelRetries` feature is incorrect

```
SecondLevelRetries is no longer a separate feature. Please use configuration.Delayed.NumberOfRetries(0) to disable delayed retries. Will be removed in version 7.0.0.
```

The correct API is `builder.Recoverability().Delayed(cfg => cfg.NumberOfRetries(0));`

The FLR one is the same

```
FirstLevelRetries is no longer a separate feature. Please use configuration.Recoverability().Immediate.NumberOfRetries(0) to disable immediate retries. Will be removed in version 7.0.0.
```

`builder.Recoverability().Immediate(cfg => cfg.NumberOfRetries(0));`

Should I open a separate PR for this or add that change here?

**Comment by danielmarbach** [comment]
We will address it in https://github.com/Particular/NServiceBus/pull/4004

**Comment by danielmarbach** [comment]
@mikeminutillo applied it on #4004

**Comment by andreasohlund** [comment]
#4004 is merged, can we close this one?
