### ISSUE TITLE
Throw exception when explicitly configure routing file does not exist

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3998]
Connects to Particular/V6Launch#68

The current (after https://github.com/Particular/NServiceBus/pull/3900) behavior is disabling the file-based instance mapping when the file does not exist, no matter if it is the default file or user-specified one.

**Comment by danielmarbach** [comment]
Merged PR. Closing

**Comment by SzymonPobiega** [comment]
Thx @danielmarbach
