### ISSUE TITLE
How to get an unobstrusive message dll included in scan

### ISSUE THREAD

**Issue by Anders2020** [Particular/NServiceBus#4005]
I have an unobstrusive dll  (with some command class) that does not get scanned? I checked the nservicebus scanning code and observed that the dll gets rejected because it does not have any dependency on nservicebus.core. It seems the code does not scan a dll without a dependency to nservicebus.core. How does nservicebus then build any meta data for my messages if they dont get scanned in??

**Comment by danielmarbach** [comment]
Good morning/afternoon/evening @Anders2020 
You are right. In NServiceBus Versions 6 and above we exclude assemblies which don't reference NServiceBus from Assembly scanning by default. All types `TMessage` that are handled on an endpoint with `IHandleMessages<TMessage>` will be included again into assembly scanning. We do this as a tradeoff. The more we scan, the slower NServiceBus bootstrapping becomes and the more we risk that we scan assemblies that we shouldn't be scanning. 

That being said. Most unobtrusive conventions are used explicitly during runtime anyway (and heavily cached where possible) or are only relevant on the incoming / receiving side of the spectrum. We still have an outstanding issue though https://github.com/Particular/NServiceBus/issues/4000. Could it be that you are running into this issue? Or what is your reason why you would like to include it into the scanning process?

**Comment by Anders2020** [comment]
I am using a client app to send commands to a server app. The server side is ok. the client side does not do any sub/handling it just send 1 or commands to the server. and the unobstrusive message dll above is used by both client and server. So I can I send my commands to the server from client without the unobstrusive dll being scanned on the client side. Will the client build any supporting meta data on the fly??

**Comment by danielmarbach** [comment]
@Anders2020 sending the unobtrusive message doesn't require metadata. As long as the conventions are available everything should be ok

**Comment by danielmarbach** [comment]
Closing this.
