### ISSUE TITLE
TransactionScope, Transports , DTC escalation and outbox

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4006]
Related issue https://github.com/Particular/docs.particular.net/issues/1023.

Before we release we need to check the persistence extension points, the persisters, the outbox and the core code for points where unwanted DTC escalation could happen. 

## TranscationMode assumptions

For example as it stands right now the assumption is that only with TransactionMode.TransactionScope there will be a TxScope present which is spawned by the transport. That is not entirely true with Azure Service Bus. Azure Service Bus requires a TransactionScope with Serializable level for SendsWithAtomic receive but nothing can enlist into that scope. The Azure SDK will immediately blow up if something tries to enlist in that scope. Currently, we work around that issue by injecting a behavior into the physical part of the pipeline which suppresses the scope spawned by the transport. Unfortunately, this trick doesn't work for Satellites created by the core since the satellite definition is owned by the core and the function delegate cannot be wrapped in any kind by the transport (or at least not that I know of). As it stands right now Satellites use the same transactionality as the endpoint. Which means for Azure SB with SendsWithAtomic receive custom satellites could not call into persisters which might end up escalating. Luckily right now we have no issue because only timeouts with timeout manager need to store something in a satellite but ASB has native deferral so we are fine. But I doubt we can continue with those assumptions.

## Outbox

With SendsWithAtomicReceive with ASB or with any transport that supports TransactionMode.TransactionScope currently the persister implementation might automatically escalate to DTC. I think for the outbox this is totally unnecessary (outbox is built for NON-DTC type interaction so why should it escalate?) and we should check and document the expected behavior so that persisters can implement it correctly.

## Persisters in general

Should persisters check the transaction mode and automatically suppress any scope present if the TxMode is less than TxScope because of how ASB behaves with SendsWithAtomitcReceive? Or should that special case be handled in ASB seam?

@Particular/nservicebus-maintainers @Particular/ravendb-persistence-maintainers @Particular/nhibernate-persistence-maintainers Let's organize a meeting and talk about the implications and assumptions

**Comment by danielmarbach** [comment]
Had a discussion with @andreasohlund. The outbox sets the default transaction mode to `ReceiveOnly` when enabled. In that mode ASB will not use any transaction scope so we are fine.

Satellites are advanced extension points. Implementors of satellites need to deal with TxScopes if available especially when they are calling out to multiple resource managers.

**Comment by SzymonPobiega** [comment]
Not sure I agree with closing this one. There are two scenarios that can still cause problems;

### Order matters

Following code

```
config.UseOutbox();
config.UseTransport<AzureServiceBus>().Transactions(TransportTransactionMode.SendsAtomicWithReceive);
```

will behave incorrectly

### Interpretation of `TransportTransactionMode`

So far we assumed that when the transport is passed the transaction mode via `PushSettings` this is the **minimum** required mode and the transport is free to use higher guarantee level. In theory a transport can always use `TransactionScope` and would be fine except for the outbox. I think we should take an action here -- one of the following:
 * Suppress the transaction scope in the outbox behavior
 * Throw if there is a transaction scope in the outbox behavior
 * Make the outbox storages not enlist even if there is scope

**Comment by andreasohlund** [comment]
>will behave incorrectly

It will blow up on the first message so users will find this immediately and we can tell them that SendsAtomicWithReceive isn't needed with Outbox on.

Isn't that enough?

**Comment by SzymonPobiega** [comment]
For now I can agree it may be enough.

**Comment by weralabaj** [comment]
Should anything be done with this issue from the doco perspective? See related issue in the description.
If not, please close the doco issue.

**Comment by andreasohlund** [comment]
The ASB behavior when AtomicSendsWithReceive is uses is about to be documented by @yvesgoeleven 

https://github.com/Particular/docs.particular.net/pull/1755

But we could perhaps change http://docs.particular.net/nservicebus/outbox/?version=core_6 to mention that turning the outbox on lowers the required transaction mode to "ReceiveOnly" for the transport it self and configuring a higher mode doesn't add any value? (not 100% true but close enough)

**Comment by weralabaj** [comment]
so just a note like:

Note: When Outbox is enabled then NServiceBus automatically lowers the delivery guarantee to `ReceiveOnly`, even if the configuration specifies higher level of guarantee (i.e. `TransactionScope`, or `SendAtomicWithReceive`.

?

**Comment by andreasohlund** [comment]
>even if the configuration specifies higher level of guarantee

No it only lowers the default mode (which is the highest supported by the transport) to `ReceiveOnly`, users can still explicitly configure another mode

So change to "lowers the default delivery guarantee..."?

**Comment by andreasohlund** [comment]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs#L20

**Comment by weralabaj** [comment]
ah ok!
