### ISSUE TITLE
Recoverability code first examples give compiler error?

### ISSUE THREAD

**Issue by Anders2020** [Particular/NServiceBus#4012]
```
var recoverability = endpointConfig.Recoverability();
            recoverability.Immediate(
                customizations: immediate =>
                {
                    immediate.NumberOfRetries(3);
                });
            recoverability.Delayed(
                customizations: delayed =>
                {
                    var numberOfRetries = delayed.NumberOfRetries(10);
                    numberOfRetries.TimeIncrease(TimeSpan.FromSeconds(10));
                });
```

the above error gives complier error 

> ...EndpointConfiguration does not contain a definition for 'Recoverablity' ... in 6.0004 beta? 

But I have seen a number of examples code with this on the site??

**Comment by timbussmann** [comment]
Hey @Anders2020 

The API you are referring to isn't available in beta4 and is contained in beta6 which should be on nuget soon. You can either upgrade to the latest beta from our myget feed or use the beta4 API which should look something like:

```
endpointConfig.FirstLevelRetries().NumberOfRetries(3);
endpointConfig.SecondLevelRetries().[...]
```

sorry about the confusion, the docs use the latest available beta from our myget feed. I hope that helps.
