### ISSUE TITLE
When ingesting timeouts, TimeoutPersisterReceiver queries in tight loop

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#4015]
In the TimeoutPersisterReceiver, when ingesting a large amount of timeouts into persistence, the value of `timeoutPushed` is held at true, which results in no code path where `nextRetrieval` is modified. This results in a tight loop where the timeout persistence is queries over and over, even if the timeouts being added are far into the future.

## Who's affected

Users of RavenDB timeout persistence that register large amounts of saga timeouts or deferred messages.

## Symptoms

When logging at INFO level or above, nothing would be evident in an endpoint's logs, because the TimeoutPersisterReceiver only logs at DEBUG level. At the DEBUG mode, rapid requerying of timeouts would be observed. Alternatively, you may notice undue load on the RavenDB server when ingesting timeouts, although it would be easy to misattribute this to the actual writing of timeouts.

**Comment by timbussmann** [comment]
is v6 affected by this too?

**Comment by DavidBoike** [comment]
I don't know yet, will be checking that out for sure.

**Comment by DavidBoike** [comment]
V6 is not affected by this. V6 does not have the timeoutPushed concept or the tricky if/then logic based on it. It only has NextRetrieval, which is simply backed up if a timeout comes in that's before the current value. Much better IMO, and my same test harness proves it out.

**Comment by danielmarbach** [comment]
Nice @DavidBoike

**Comment by DavidBoike** [comment]
Updated the description with Who's affected and Symptoms information for possible release notes.

**Comment by andreasohlund** [comment]
Reading the updated description and @bording [comment ](https://github.com/Particular/NServiceBus/pull/4016#issuecomment-239276950)on the PR I'm :+1: to go ahead and release this

**Comment by DavidBoike** [comment]
Will release on my Monday morning.

**Comment by DavidBoike** [comment]
This is now released in NServiceBus 5.2.15.
