### ISSUE TITLE
In Beta6 Routing.Mapping is gone whats the alternative?

### ISSUE THREAD

**Issue by Anders2020** [Particular/NServiceBus#4017]
`routing.Mapping.Physical.Add(
            new EndpointInstance(server, "1").AtMachine(RuntimeEnvironment.MachineName),
            new EndpointInstance(server, "2").AtMachine(RuntimeEnvironment.MachineName));`

the above code no longer works in Beta6 so the fairdistribution sample does not compile. what the alternative, while still maintaining code first config??

**Comment by danielmarbach** [comment]
Beta 6 is not yet offficially released. Is there a reason you jump on it
with myget?

**Comment by timbussmann** [comment]
Hey @Anders2020 

For MSMQ please refer to this documentation about how to do client side distribution: http://docs.particular.net/nservicebus/msmq/scalability-and-ha/sender-side-distribution
That page should already be updated to beta6. Some of the samples aren't updated to latest beta versions and will follow soon.

It's no longer possible to directly hardcode instances at the bus configuration level, although there is an advanced API available which is accessible within a custom `Feature`. In general we highly recommend the approach described in the linked documentation.

**Comment by Anders2020** [comment]
beta 6 is what now available on nuget pre

**Comment by danielmarbach** [comment]
@Anders2020 interesting

![image](https://cloud.githubusercontent.com/assets/174258/17431129/b09b11bc-5af8-11e6-9039-d5fb8373ce70.png)

This  is what I see. Will investigate

**Comment by danielmarbach** [comment]
Can you check if you are using our myget feedback in the nuget.config? If yes I would recommend you to use the nuget.org feed only.

**Comment by timbussmann** [comment]
Hey @Anders2020,

Were you able to use the instance mapping file as described in http://docs.particular.net/nservicebus/msmq/scalability-and-ha/sender-side-distribution or to downgrade to beta4?

**Comment by timbussmann** [comment]
All the samples should have been updated to the latest available beta version. Thanks for raising the issue!

**Comment by Anders2020** [comment]
sender side distribution seem to be working but have yet to a more detailed
test
