### ISSUE TITLE
NonDurableMessages do not work with unobtrusive mode in v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4022]
## Who's affected

* All users of v6 (beta customers) which are using unobtrusive mode in conjunction with non-durable messages.

## Symptoms

* The new assembly scanner excludes all assemblies from assembly scanning that do not reference NServiceBus directly. Message types that are handled on a receiver will be automatically readded to the type list. Unfortunately non-durable messaging and the behavior rely on a type mapping. So if you have an unobtrusive convention for messages and a non-durable convention the message type is never contained in the scanned type list and therefore the `DetermineMessageDurabilityBehavior `will not mark a message as non-durable.

## Steps to reproduce

* Use http://docs.particular.net/samples/unobtrusive/?version=core_6 with beta 
* Send `RequestExpress`
* The message is flagged as Recoverable and doesn't contain NonDurable header with true

**Comment by danielmarbach** [comment]
// cc @timbussmann

**Comment by timbussmann** [comment]
let's mark this as a "critical" since that should be fixed before v6 RC?

**Comment by andreasohlund** [comment]
PR is merged, lets close this?
