### ISSUE TITLE
MessageDeserializerResolver throws duplicate key exception

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4031]
We have multiple serializers that can handle json.

if someone tries to use AddDeserializer to make them co-exist then this 
https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Serializers/MessageDeserializerResolver.cs#L12
will throw a duplicate key exception

**Comment by johnsimons** [comment]
@SimonCropp you need to ensure the other deserializer "content type" key does not clash with existing ones.

**Comment by SimonCropp** [comment]
@johnsimons that doesnt make sense. as long as u dont register multiple u can still use json to transition over. also saying "all downstream serializers need to be aware of all other serializers and not use the same key" is not reasonable

**Comment by johnsimons** [comment]
You can transition over, all u need to do is ensure the serializer that u want to transition to is the default one, and then ensure that the old and new are configured as deserializers.

> "all downstream serializers need to be aware of all other serializers and not use the same key" is not reasonable

Yes the exception can be improved

**Comment by SimonCropp** [comment]
@johnsimons so based on your statements it is not "contenttype" at all.

**Comment by johnsimons** [comment]
That is correct @SimonCropp it is just a string key.

That said, you can still use it as it is define by the http standards, eg "application/json; type=json.net; version=1.0", this would treat "application/json; type=json.net; version=1.0" as the key and therefore would be not equal to eg "application/json" or "application/json; type=json.net; version=2.0"

Hope this make sense.

**Comment by danielmarbach** [comment]
Be aware that this would break wire compat since we would be emitting
different headers. I would question if it makes sense to add multiple
deserializers for the same content type.

**Comment by SimonCropp** [comment]
@danielmarbach i wasnt saying it should be supported. i just want a better exception message. "duplicate key" is never a valid exception

**Comment by timbussmann** [comment]
+1 for a better exception message, but not really seeing value in going further than that.

**Comment by danielmarbach** [comment]
Agree to that

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers give it maintainer prio?

**Comment by danielmarbach** [comment]
@timbussmann Luckily I saw that you already opened a PR. Can you make sure you assign it first to you before you start working on it :)

**Comment by timbussmann** [comment]
@danielmarbach sorry, forgot about that. Decided to quickly raise a PR while skimming over maintainer issues.

**Comment by danielmarbach** [comment]
Addressed in https://github.com/Particular/NServiceBus/issues/4033
