### ISSUE TITLE
When using MSMQ transport can't change input queue name

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#4040]
When I was pursuing another bug, I found that when using MSMQ transport I was unable to change input queue name. 

According to this [article](http://docs.particular.net/nservicebus/endpoints/specify-endpoint-name#input-queue) you can do it by adding 2 snippets of code. 

To reproduce it I downloaded [step-by-step](http://docs.particular.net/samples/step-by-step/) sample for v6.

I added following code. Server:
```
endpointConfiguration.UseTransport<MsmqTransport>().AddAddressTranslationException(
            new EndpointInstance("Samples.StepByStep.Server"), "d12345");
```

To client:
```
var transport = endpointConfiguration.UseTransport<MsmqTransport>();
        var routing = transport.Routing();
        routing.RouteToEndpoint(typeof(PlaceOrder), "Samples.StepByStep.Server");
        transport.AddAddressTranslationException(
            new EndpointInstance("Samples.StepByStep.Server"), "d12345");
```

When running the sample the queue `d12345` is not created. Application works like a charm on the regular queue names. I have similar sample on Rabbit that uses the change queue. 

cc: @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
To get the server working, you need to change your code as follows:

```
endpointConfiguration.UseTransport<MsmqTransport>().AddAddressTranslationException(
            new EndpointInstance("Samples.StepByStep.Server").AtMachine(RuntimeEnvironment.MachineName), "d12345");
```

because this sucks the routing tf removed this API in the latest v6 version, there will be a `OverrideInputQueueName` on `EndpointConfiguration` instead.

on the client side you would also have to specify the machie for the endpointinstance, but a quick test didn't work. not sure whether this is indeed a bug, but since this API will be gone anyway, I'd suggest to close this anyway and not dig deeper. Any objections?

**Comment by timbussmann** [comment]
raised a doc PR describing the latest core behavior here: https://github.com/Particular/docs.particular.net/pull/1766

**Comment by WojcikMike** [comment]
@timbussmann I am fine with closing this. However can we write acceptance test to verify that this feature work? Maybe by checking if failed message from endpoint contains FailedQ with given value?

This exact code worked when using NSB core beta 6 with Rabbit. But with Msmq it didn't.

**Comment by timbussmann** [comment]
@WojcikMike these are the acceptance tests we currently have in the core around that feature:
https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Msmq.AcceptanceTests/When_overriding_address_translation.cs
https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.AcceptanceTests/Hosting/When_overriding_local_addresses.cs

do you think we need to refine those or add additional ones?

**Comment by WojcikMike** [comment]
The above looks good
