### ISSUE TITLE
In V6 MessageEndpointMappings are processed in wrong order

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4044]
Connects to Particular/V6Launch#68

In V5 the MEM's are processed in the descending order which means they are processed from the least specific to the most specific, ensuring that most specific rules override least specific ones (namespace and assembly).

**Comment by timbussmann** [comment]
@SzymonPobiega are we just about talking about order or are there also some "weights" taken into account?

@DavidBoike I remember you did several tests with the v5 API

**Comment by DavidBoike** [comment]
What @SzymonPobiega states about the V5 order is what I would expect as well. My tests were mostly concerned with all that polymorphic stuff though and didn't really hit on this.

So yes, **by type** should override **by namespace** which should override **by assembly** in V6.

**Comment by SzymonPobiega** [comment]
https://github.com/Particular/NServiceBus/pull/4046 is a solution for this one so closing.
