### ISSUE TITLE
TransportTransaction is not added to the ContextBag in satellites

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#4047]
### What is the problem?

During [making the transport transaction an explicit concept on the dispatcher](https://github.com/Particular/NServiceBus/pull/3981) a change has been made that separates the `TransportTransaction` from the message receive context. Some downstream components (most notably the NHibernate persister) depend on the transport transaction, so the transport transaction still gets stored in the context bag in the `TransportReceiveContext`. This has been [called out](https://github.com/Particular/NServiceBus/pull/3981/files#r72663439) during the code review.

The problem is that this is only done for the main pipeline. Satellites do not have `TransportTransaction` in the context bag.

The result is that the TimeoutManager cannot access the persistent storage within the receive transaction. This causes deadlocks and timeouts when using the NHibernate persistence with the SQL transport and lack of transactionality when using NHibernate persistence with MSMQ. Other combinations might also be affected.

Second part of the problem is that the transport transaction is not properly passed to the dispatcher in satellites as they are currently retrieved from the context bag. They need to be retrieved from the `MessageContext`.

### What to do about it?

Adding transport transaction to the context bag in satellites is the simplest option.

We could also make the transport transaction an explicit concept for the persisters but this would be a breaking change for the persisters API.

**Comment by MarcinHoppe** [comment]
Resolved by #4050

**Comment by andreasohlund** [comment]
@MarcinHoppe you mentioned that this would have been caught if the NH + SQLServer acceptance test had been running.

@Particular/nhibernate-persistence-maintainers @Particular/sqlserver-transport-maintainers perhaps make it a joint "maintainer prio" to get those tests back green again? 

https://builds.particular.net/viewType.html?buildTypeId=NServiceBusNHibernate_AcceptanceTestsSqlServer

**Comment by MarcinHoppe** [comment]
@andreasohlund @Particular/nhibernate-persistence-maintainers @Particular/sqlserver-transport-maintainers I'll work on these tests.
