### ISSUE TITLE
Unit Test naming convention

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4048]
It seems every developer follows his own unit test naming conventions, and sometimes not even that. I propose to decide on a naming convention, document that as a guideline and follow that guideline for newly added unit tests.

Conventions:
* Unit test classes should be named after the class they use in their "act" on + `Tests`.
* Naming of the unit tests should be `[MethodActedUpon]When...Should....` where the part in `[]` is optional.

The above is just a first suggestion.

**Comment by danielmarbach** [comment]
Ping @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
I used to be a big fan of following naming conventions with Unit tests. Since working here I came to the conclusion I don't really care anymore as long as it is clear what is being tested.

**Comment by andreasohlund** [comment]
On the fence, but since we would have to enforce this by code reviews(??) I'm not sure the ROI is there?

**Comment by danielmarbach** [comment]
Agree with @andreasohlund comment (@bording liked it as well). I think we have bigger fish to fry. I vote for closing this. The implications though would be that we cannot nitpick on the shape of the test name anymore but just the name. So for example reviews like this would be no longer valid:

> Test: ShouldDoSuperDuperThing
> Reviewer: Can you rename to Should_do_super_duper_thing

Only valid review would be

> I don't understand what "super duper thing" means. How about "ShouldDoExtraOrdinaryThing"

Or should we agree that we stick to the convention that was started in a given file?

So for example, if a file contains

`Should_do_super_duper_thing` and someone writes `ShouldDoAnotherSuperDuperThing` that it would be valid to nitpick and say: Please align test name with other tests in file.

**Comment by bording** [comment]
> Or should we agree that we stick to the convention that was started in a given file?

👍

**Comment by timbussmann** [comment]
> Or should we agree that we stick to the convention that was started in a given file?

that was a no-brainer for me so far. Do we need to document that?

**Comment by andreasohlund** [comment]
Pr against maintainer.md for now?

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus/pull/4217. Closing this
