### ISSUE TITLE
Acceptance Tests with multiple test cases

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4051]
In `When_registering_publishers_unobtrusive_messages` we have two test cases which test different subscription scenarios based on the same publisher endpoint. This works fine on the core using the inmemory persistence which is reset after every test case. But on downstream persistence, this tests start to fail because the persistence now contains subscriptions from both test cases while only one of the subscribers is available. This [throws an exception](https://builds.particular.net/viewLog.html?buildId=181279&tab=buildResultsDiv&buildTypeId=NServiceBusNHibernate_2AcceptanceTests) about an inexistent queue because there are queues in the subscription table which belong to other test cases. 

One solution in this case we is to split the test cases into two different test classes to avoid these conflicting subscriptions.

Should we make sure that no test can contain more than one test case to avoid problems like these? In many cases this is not necessary, but identifying problematic tests is tricky (e.g. other routing tests which don't use the subscription storage aren't affected)

@Particular/nservicebus-maintainers thoughts?

**Comment by danielmarbach** [comment]
Let's refactor the once that are affected and then close this issue. Don't think we should do it as a general purpose approach.

**Comment by danielmarbach** [comment]
Maybe we can add a review remark to the maintainer readme of the core maintainers?

**Comment by danielmarbach** [comment]
Even better should the acceptance test base class throw an exception when more than one `[Test]` attribute is detected?

**Comment by timbussmann** [comment]
@danielmarbach I like that idea, having automatic verification of guidelines makes it much easier to enforce it on all contributors.

**Comment by andreasohlund** [comment]
Is still an issue? (Remember that we talked about this on a PR recently and the consensus seemed to that its a non issue)

**Comment by dbelcham** [comment]
We're still finding them occasionally when we're doing the review of the acceptance tests #4457 . We split them apart at that time, so I'd say that we're cleaning this up. By the time we're done #4457 the problem shouldn't exist anymore....until someone creates a new test file with two tests.

**Comment by timbussmann** [comment]
the mentioned tests has already been split and if there are any remaining tests, this should be addressed as described by @dbelcham. If there is a specific test causing issues, it would make most sense to create a new issue for that test. Based on that, I'm closing this issue for now as I think it's no longer relevant.
