### ISSUE TITLE
Timeout manager has high probability of duplicates when endpoint is scaled out

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4085]
When an endpoint is scaled out the timeout manager has multiple running instances. This has a high probability of dispatching duplicate messages when the endpoint is not using distributed transactions like when the outbox is enabled or when using a timeout persister that is not transactional or is transactional but doesn't support locking.

Because SLR uses the timeout manager it's likely that SLR results in duplicates even though the customer will never generate duplicate messages.

This is an issue as duplicates will be generated even though this is not happening due to technical recovery but in regular happy message processing for example when using saga timeouts or defers.

**Comment by ramonsmits** [comment]
@yvesgoeleven already created an issue with a potential solution to prevent unnecessary duplicates in the happy flow more then 1.5 years ago: https://github.com/Particular/NServiceBus/issues/2602

**Comment by danielmarbach** [comment]
@Particular/rabbitmq-transport-maintainers @Particular/sqlserver-transport-maintainers @Particular/azure-storage-queues-maintainers should we discuss if we can prioritize native timeout for the transports. Discussed with @andreasohlund and we think it is highly unlikely that we address this in the near future.

**Comment by adamralph** [comment]
I've spun off a discussion for the RabbitMQ transport at https://github.com/Particular/NServiceBus.RabbitMQ/issues/234

**Comment by ramonsmits** [comment]
I just noticed this is closed. I don't understand why. This is a very serious issue!

**Comment by danielmarbach** [comment]
@ramonsmits see https://github.com/Particular/NServiceBus/issues/4085#issuecomment-247999757 we want to support native timeouts.

**Comment by ramonsmits** [comment]
I understand that native transport timeouts if supported resolve the issue and that #234 has spun of from this. Problem is, that is marked as 'Discusson'. This issue IMHO should be resolved ASAP in one way or the other.

**Comment by adamralph** [comment]
Small correction, only https://github.com/Particular/NServiceBus.RabbitMQ/issues/234 has been spun off from this, and that is only for RabbitMQ. It is marked as a discussion since the general feeling right now is that it probably won't even possible for the RabbitMQ transport.
