### ISSUE TITLE
Remove legacy retries satellite

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#4087]
In version 7 we no longer need legacy retries satellite and it can be safely removed.

**Comment by bording** [comment]
We should also make sure we obsolete `RecoverabilitySettings.DisableLegacyRetriesSatellite` as part of this.

**Comment by andreasohlund** [comment]
@bording you've done this already right?

**Comment by bording** [comment]
Not yet, since it didn't already have an obsolete attribute. I'll submit a PR for it.
