### ISSUE TITLE
Check interface names for I prefix and log that this is leaking into the wire message

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4091]
A lot of customers use interfaces for their messages but they name them like .net interfaces:

``` c#
interface IStrategyCreated
{
    //...
}
```

This results in the message having the name `IStrategyCreated` and probably isn't the intent.

We could verify the interfaces and detect if the user is applying .net naming convention on their messages types and inform them that this convention should not be applied on these types.

Discussion: https://particularsoftware.slack.com/archives/support/p1472111011000746

**Comment by timbussmann** [comment]
while I agree that the `i` doesn't make much sense for messages, I don't see how it hurts or why we should prevent users from using it? If it annoys you, remove it. It's naming, name it whatever you like?

**Comment by andreasohlund** [comment]
I don't see us enforcing this in the core, please re-open if you feel strongly for this @ramonsmits
