### ISSUE TITLE
Init.ps1 logs errors when installing the RC package

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4103]
I updated the WireCompatTests and while the update worked I got `A cmdlet named 'Add-NServiceBusAuditConfig' already exists` in the output window. See below

<details>

Added package 'NServiceBus.6.0.0-rc0001' to 'packages.config'
Executing script file 'C:\dev\EndToEnd\packages\NServiceBus.6.0.0-rc0001\tools\init.ps1'...
Type 'get-help about_NServiceBus' to see all available NServiceBus commands.
Type 'get-help about_NServiceBus' to see all available NServiceBus commands.
Import-Module : A cmdlet named 'Add-NServiceBusAuditConfig' already exists. Cmdlets must have unique names.
At C:\dev\EndToEnd\packages\NServiceBus.4.7.12\tools\init.ps1:11 char:3
+         Import-Module $pathToNServiceBusPSCmdLets
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Import-Module], PSNotSupportedException
    + FullyQualifiedErrorId : NotSupported,Microsoft.PowerShell.Commands.ImportModuleCommand
 

Type 'get-help about_NServiceBus' to see all available NServiceBus commands.

Existing NServiceBus v(4.7.12) user detected
Existing Platform user detected

Type 'get-help about_NServiceBus' to see all available NServiceBus commands.

Existing NServiceBus v(5.0.11) user detected
Existing Platform user detected

Type 'get-help about_NServiceBus' to see all available NServiceBus commands.

Type 'get-help about_NServiceBus' to see all available NServiceBus commands.

Type 'get-help about_NServiceBus' to see all available NServiceBus commands.

Import-Module : A cmdlet named 'Get-NServiceBusVersion' already exists. Cmdlets must have unique names.
At C:\dev\EndToEnd\packages\NServiceBus.3.3.18\tools\init.ps1:8 char:1
+ Import-Module (Join-Path $toolsPath nservicebus.powershell.dll)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Import-Module], PSNotSupportedException
    + FullyQualifiedErrorId : NotSupported,Microsoft.PowerShell.Commands.ImportModuleCommand

</details>

**Comment by andreasohlund** [comment]
@gbiellem is there some :chicken: that we need to sacrifice to the PowerShell gods?

**Comment by SimonCropp** [comment]
This is expected since all ps addins share the same vs app domain. So to stop the conflict u need to uniquely name them on every version release.

**Comment by andreasohlund** [comment]
aha, so closing as "by design"
