### ISSUE TITLE
Favour Component Tests over Acceptance Tests

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#4113]
The maintainers rules need to be updated to state this.
See previous update in https://github.com/Particular/PlatformDevelopment/pull/830/files#diff-7fd98d74615ed86a474385724cbcb541R22

**Comment by adamralph** [comment]
PR raised - https://github.com/Particular/NServiceBus/pull/4112

**Comment by andreasohlund** [comment]
PR is merged
