### ISSUE TITLE
Pass EndpointInstances to transport seam explicitly

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#4116]
In V6 if transport seam need to change `EndpointInstances` collection (e.g. to extend properties collection) it need to retrieve it from SettingsHolder passed during configuration time.
This should be modeled as explicit parameter passed to the seam.

Connect to: #4115

**Comment by timbussmann** [comment]
and what if the transport seam needs to change/add routes or publishers?

What's the scenario where the transport seam needs to access the collection?

**Comment by tmasternak** [comment]
In SqlServer we need to put data in the properties dictionary of `EndpointInstance` when user configures custom schema. It is especially useful/convenient when doing that for local endpoint as all satellites inherit the values. 

I don't know of any scenarios in which routes/publishers need to be changed.

**Comment by tmasternak** [comment]
After talking with @timbussmann I'm convinced that this is not a transport seam logic but a configuration of routing that in case of Sql Server is covered with convenience methods.
