### ISSUE TITLE
Write log entry when publishing without subscribers when message driven pubsub is used

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4119]
We seem to be officially support publishing on a send only endpoint (#2612).

For diagnostical purposes, I would propose to write a log entry with level WARN stating the following message

> 0 subscribers for event {0}, this can indicate a configuration issue. Are you running a send only instance and/or using volatile persistence?

Concerns: 
- It can actually be a valid configuration to not have subscribers. Instead of a WARN we could log this at a lower log level
- To prevent log spamming the log entry could be written only once and tracked in a concurrent dictionary.

**Comment by andreasohlund** [comment]
Related to https://github.com/Particular/PlatformDevelopment/issues/893

**Comment by andreasohlund** [comment]
Note: this is only relevant for the message driven transports (msmq+asq+sql) since we have no way of knowing this with Rabbit+ASQ since the broker has that info

@Particular/rabbitmq-transport-maintainers  does rabbit have some kind of native "if no binding was present let me know" feature?

@Particular/azure-service-bus-maintainers does ASB have some way of knowing that there was no one listening to the topic?
@az

**Comment by yvesgoeleven** [comment]
@andreasohlund not really, but we can query the namespace for that info

**Comment by WojcikMike** [comment]
@andreasohlund there is mandatory flag that lets broker know if you should be informed if the message cannot be delivered to any queue (like publishing without subscribers). At the moment, mandatory flag is set for Sends (as the message should get to someone) and to not set for publish (as publishing with no subscriptions is considered valid scenario). So it seems that there could be an option to do something with it if needed.

**Comment by andreasohlund** [comment]
This seems like a low hanging fruit, do you want to send in a PR @ramonsmits ?

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/UnicastPublishRouter.cs#L77
