### ISSUE TITLE
IManageUnitsOfWork does not receive exception if output persistence fails in V6 beta

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4134]
When `IManageUnitsOfWork.End(Exception)` is called the persistence can have outstanding operations that are only flushed once the persistence transaction is committed.

For example, saga operations are not flushed and can still fail. The unit of work `End(Exception)` is called and deems the processing is successful and a bit later the outbox will commit the transaction and this can result in storage errors.

In V5, the outbox transaction commit would be catched by the unit of work.

//cc @danielmarbach @andreasohlund @tmasternak

**Comment by ramonsmits** [comment]
After discussion with @danielmarbach @tmasternak and @andreasohlund it is clear that the reason for this is that the outbox and unit of work order is changed but that this is by design for V6 and this needs to be documented. The documentation could contain a link to the documentation that shows how the user can interact with error recovery.

**Comment by timbussmann** [comment]
> this needs to be documented

are you going to raise a docs PR? Should we keep this open until a doco PR is created?

**Comment by tmasternak** [comment]
The doco pr has been already merged

14.09.2016 3:11 PM "Tim Bussmann" <notifications@github.com> napisał(a):
