### ISSUE TITLE
Logs are missleading when no queue name configured for MSMQ sub storage

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4145]
I saw this on the group:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/fLGSWcmeEGE/E4ImM1HGCAAJ

> 09/20/2016 14:31:47 -03:00 [Warning] Could not find configuration section for Msmq Subscription Storage and no name was specified for this endpoint. Going to default the subscription queue

This seems to imply that there is no endpoint name when in this case there is no specific name specified for the storage queue so we default it to `NServiceBus.Subscriptions`

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/11.
