### ISSUE TITLE
MSMQ persistence default queue name

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4147]
When using MSMQ persistence as the subscription storage and not specifying an explicit queue to store the subscriptions, it logs a warning and falls back to "NServiceBus.Subscriptions". This may cause different logical endpoints to use the same subscription storage.

The documentation states:
> By default NServiceBus uses a queue called {Name of the endpoint}.Subscriptions.

this doesn't seem to be true looking at the implementation:

                if (cfg == null)
                {
                    Logger.Warn("Could not find configuration section for Msmq Subscription Storage and no name was specified for this endpoint. Going to default the subscription queue");
                    queueName = "NServiceBus.Subscriptions";
                }

Also, is warning the right log level for that setting? Is it expected to configure a custom queue?

Seems like a bug to me (or we need to align the docs)? @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
I could have sworn we used the endpoint name as well. Looking at the v5 code it seem that we use "NServiceBus.Subscriptions".

I think we have to make it mandatory since just changing the default would be a breaking change that would means message loss on upgrade since we'll create a new queue?

Ie: Create a mandatory code api for setting this in vNext?

This also shows that our transport+persitence api is a bit off since we can't enforce this without doing runtime checks atm.

Or could we have the storage check for the existence of a queue called "NServiceBus.Subscriptions" and use that one if present and use the EndpointName.Subscriptions one if not? (think I rather be explicit here)

**Comment by andreasohlund** [comment]
So short term action point would be to verify v5 behavior + fix docs?

**Comment by timbussmann** [comment]
looking at the v5 code, it seems like it's the exact same code as in v6. I'll verify with a real endpoint.

If that assumptions holds true, how about:
* Fix the docs
* Improve the situation of a "generic" default queue name for the next version

**Comment by andreasohlund** [comment]
>Improve the situation of a "generic" default queue name for the next version

Changing defaults would mean message loss for users not reading the upgrade guide? (ie a no go)

**Comment by danielmarbach** [comment]
@andreasohlund I'm sure with 

> Improve the situation of a "generic" default queue name for the next version

@timbussmann indicated that he wants to fix it in a way that doesn't mean message loss. Not sure what you mean with [your statement ](https://github.com/Particular/NServiceBus/issues/4147#issuecomment-248544881)@andreasohlund

**Comment by andreasohlund** [comment]
>you mean with your statement

Just pointed out that we can't lean on users reading upgrade guides (like the .retries case) to avoid loosing messages. And changing the default would require that? (I propose we make the setting mandatory for vNext)

**Comment by timbussmann** [comment]
of course, when changing the behavior for a next version we would have to ensure backward compatibility in some way or another (e.g. by mandatory configuration, queue checking or whatever seems to suit best)

**Comment by andreasohlund** [comment]
👍

**Comment by timbussmann** [comment]
confirming that v5 also uses `nservicebus.subscriptions` as a default value. Will raise a docs PR (probably also need to verify the v4 behavior)

**Comment by timbussmann** [comment]
v4 seems to use the endpoint name for the subscription storage by default.

**Comment by andreasohlund** [comment]
So we broke it in v5

**Comment by timbussmann** [comment]
docs PR raised here: https://github.com/Particular/docs.particular.net/pull/1931

**Comment by timbussmann** [comment]
Issue about changing the behavior raised here: https://github.com/Particular/NServiceBus/issues/4148

@andreasohlund as you also raised an issue about the log statement, are we good to close this one?
