### ISSUE TITLE
Change MSMQ Subscription Storage default queue

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4148]
When using the MSMQ subscription storage it uses the queue `NServiceBus.Subscriptions` by default (v5-v6). V4 used `{endpointName}.Subscriptions` instead. It seems to make more sense to use a endpoint-specific subscription queue in order to avoid conflicts when running multiple endpoints using MSMQ subscription storage on the same machine.

Some ideas raised by @andreasohlund:

> I think we have to make it mandatory since just changing the default would be a breaking change that would means message loss on upgrade since we'll create a new queue?
> 
> Or could we have the storage check for the existence of a queue called "NServiceBus.Subscriptions" and use that one if present and use the EndpointName.Subscriptions one if not? (think I rather be explicit here)

relates to https://github.com/Particular/NServiceBus/issues/4147

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/10.
