### ISSUE TITLE
Prevent mistakes in instance mapping file

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4154]
It's possible to configure all sorts of attributes in the instance mapping file for an endpoint instance (e.g. `machine`) but in case an user doesn't exactly use the casing as expected, the transport will not be able to find the attribute (unless it explicitly looks for all possible mutations).

At first glance I see two different implementations:
- Make the schema for the instance mapping file more strict to not allow arbitrary attributes and include the `machine` and `queue` attributes. This will cause exceptions if anything else is configured. In case of runtime changes, this might result in changes not being picked up since after startup validation changes will let the endpoint keep the last known valid mapping configuration. As the instance mapping file is currently limited to MSMQ, there is no more need for the support of arbitrary information in the mapping file.
- Make the lookup to the `EndpointInstances.Properties` property more forgiving so that a lookup for `machine` will also return if the attribute was declared `MACHINE`. This easy to implement by passing  `StringComparer.InvariantCultureIgnoreCase` to a newly created Dictionary.

/cc @bording @SzymonPobiega

**Comment by bording** [comment]
At this point I prefer the first option, making the xml schema actually able to catch these types of errors by getting rid of the `any`.

**Comment by timbussmann** [comment]
I agree with @bording but I wonder whether this would essentially mean a breaking change? The later option can easily be handled in a minor version, does this hold true for the changed schema?

**Comment by mikeminutillo** [comment]
We had a support case with a customer running into this issue as there was a [doco page](https://docs.particular.net/nservicebus/msmq/scalability-and-ha/sender-side-distribution#mapping-physical-endpoint-instances) that showed a sample file with upper case Machine. 

The major issue with this is that everything appears to work fine but messages get routed to the queue on the local machine. This is because the MSMQ address translation defaults to localhost if a machine name isn't found. If you happen to have a receiver on your machine (as you tend to in dev), it appears to work but only one instance is getting the messages.

It's a pain to diagnose.

**Comment by timbussmann** [comment]
weird, I'm pretty sure we fixed that doco already once.

If we go with option2, we could include this in 6.1, whereas for the schema change, I'd say this would require v7? Thoughts? @mikeminutillo @bording

**Comment by bording** [comment]
My first thought it is: if MSMQ was a separate package, we could just bump it and leave core alone. 😉 

But for actually solving this specific problem, I think it makes sense to go ahead and make things more forgiving with option 2, and then fix the xml schema when we can.

**Comment by timbussmann** [comment]
so how about:
* we raise an issue as breaking change for the the next major to make the schema more strict (that would probably be the time we extract msmq from the core too)
* we make it more forgiving in 6.1 to lower the risks

**Comment by timbussmann** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/19.
