### ISSUE TITLE
Performance counters not working with MSMQ transport in V6 RC

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4157]
The windows performance counters not working with MSMQ transport in V6 RC. 

With MSMQ:

![image](https://cloud.githubusercontent.com/assets/152998/18828266/48c82c02-83d7-11e6-82fa-6853049bdd6b.png)

The highlighted line stays on 0.

With RabbitMQ:

![image](https://cloud.githubusercontent.com/assets/152998/18828336/aeb0f47c-83d7-11e6-9e83-0eedeaf2c887.png)

The highlighted line shows activity.

**Comment by danielmarbach** [comment]
Did a quick glance at the code. We are setting it up in a generic transport agnostic way. I have difficulties to understand why it should work with Rabbit but not with MSMQ.

https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Performance/Statistics/ReceivePerformanceDiagnosticsBehavior.cs#L18
https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Performance/ReceiveStatisticsFeature.cs#L15-L21

@Particular/nservicebus-maintainers thoughts?

**Comment by ramonsmits** [comment]
@Particular/nservicebus-maintainers After more research it seems that the performance counters *are* working but not with the same instance name:

RabbitMQ : performancetest
MSMQ : performancetest@zolder
SQL :performancetest@[v6]

It seems that an instance discriminator is added to performance counter instance name. I don't know if that is the correct performance counter instance naming behavior as in V5 the logical endpoint name is used.

The docs don't mention anything about the performance counter instance naming.

- https://docs.particular.net/nservicebus/operations/performance-counters
- https://docs.particular.net/samples/performance-counters/


To me it does feel more natural to use the logical name.

**Comment by ramonsmits** [comment]
Looking at the code:

- https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Performance/ReceiveStatisticsFeature.cs#L15
- https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Performance/Statistics/ReceivePerformanceDiagnosticsBehavior.cs#L57

Shouldn't that just pass `context.Settings.EndpointName()` instead of `context.Settings.LocalAddress()`?

**Comment by andreasohlund** [comment]
If you have multiple instances on the same box would you want to separate them?

**Comment by ramonsmits** [comment]
@andreasohlund thinking about it I guess both scenarios make sense.

The SQL version seems not to be about instance' but more physical representation of the queue?

If endpoint instance would be the correct one I think would expect performance counter instance name = logical endpoint + instance discriminator.

For example, MSMQ is using the machine name which is redundant as that is already part of the performance counter data (captured machine).

**Comment by andreasohlund** [comment]
>For example, MSMQ is using the machine name which is redundant as that is already part of the performance counter data (captured machine).

Agreed, I'd say we need to fix this now since this would be both breaking and very confusing for OPS people

**Comment by danielmarbach** [comment]
As discussed in a call with @timbussmann @ramonsmits and @andreasohlund we will fix this for RC3 and switch back to endpoint name.

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus/issues/4165. Closing this one
