### ISSUE TITLE
Static centralized routing

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4161]
During the last few weeks and months we experienced a lot of issues and pains around routing and pub/sub. Some of them are:
* Removing subscriptions for decommissioned endpoints is a PITA for certain transports
* The upgrade scenario from the distributor to sender-side distribution is a PITA
* The story for operations in production environments to add/decommission endpoints does not exist.
* Routing configuration is non-trivial and very transport specific (e.g. publisher config in MSMQ vs. publisher config in Azure, transport specific routing settings like machine name or sql schema, ...)
* Message hierarchies and routing inheritance

Thanks to the new routing internals in v6, I was able to spike a file based routing quite easily. It can be found here and includes some description on how to use it: https://github.com/timbussmann/NServiceBus.FileBasedRouting
quick summary of its capabilities:
* A routing file (xml) defines all messages handled by an endpoint (including events)
* Endpoints need to have that file around and need no further configuration
* Removes message driven pub/sub for MSMQ and uses the routing file instead
* Endpoints can easily be removed and unsubscribed by editing the routing file which is automatically reloaded
* Makes use of the already existing instance mapping file to enable sender side distribution for sender AND publishers (currently, ssd for publishing is not using the instance mapping file).

## User Impact

This solution orients itself heavily on endpoint and routing management in production environments:

* OPs can easily add or remove endpoint instances without having to mind about subscription storages or adjusting routing on all somehow related endpoints.
* OPs can easily decommission endpoints without the need of adjusting routing and subscriptions on all somehow related endpoints.
* No dedicated subscription storage required.
* Routing configuration can be checked and validated to prevent misconfiguration.
* Routing can be changed based on environment e.g. using xslt

## Vision

Thinking further about this approach, there are many things this can serve as a base:
* Getting rid of message driven subscriptions
* Centralized routing and instance management (e.g. by ServiceControl)
* Automatic routing configuration by endpoints
* Configurable routing inheritance

## Next steps:

Based on the mentioned spike, a production ready package for MSMQ could be provided as a particular labs project as a pilot for interested users to get more feedback about this approach on routing.

/cc @SzymonPobiega @janovesk

**Comment by SzymonPobiega** [comment]
I think this is generally good direction but...
 * If we can wait till `6.1` we will be able to properly replace `UnicastPublishRouterConnector` and this way avoid providing a custom subscription store implementation making this easier for users to configure.
 * As the input to the transport we should give:
  * For the commands, what is the logical destination endpoint
  * For the events, what are the logica subscribers
  * Instance mapping
 * The information above can be provided via a file which improves the store quite a bit (easy decommissioning of subscribers etc.) but for the bigger impact we should combine it with Autonomous Component-based routing where the routing table lists AC and maps them to hosts.

I think this issue would be well-aligned with devops theme as it removes significant portion of a friction between devs and ops in context of message routing.

**Comment by timbussmann** [comment]
sorry, wrong repo, reraised in pdev: https://github.com/Particular/PlatformDevelopment/issues/954
