### ISSUE TITLE
MSMQ subscription storage may be initialized too late if messages are sent from a custom feature

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4164]
Subscription storage implementations implement `IInitializableSubscriptionStorage` which includes an `Init` method. This method is called from a FeatureStartupTask of the `StorageInitializer` Feature from the core. I assume this is done this way because FST support DI and therefore it can resolve the registered  `IInitializableSubscriptionStorage`  implementation.

But there's a chance that another FST run before this specific FST and since they receive a session they can publish messages before the subscription storage is initialized, causing a loss of the published event.
- Subscription storages should be initialized before running FeatureStartupTasks
- `Init` should probably be a Task based API (which makes it more difficult to call it in a Feature setup).

This might align very well with other ideas to move subscription storages closer to the transport in general. But since it could cause message loss when publishing from FeatureStartupTasks, I think this should be addressed soon. @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Also related https://github.com/Particular/NServiceBus/issues/2449
