### ISSUE TITLE
Performance counters should be named according to logical address

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4165]
## Who's affected

* All customers that are running 6.0.0-RC1 or 6.0.0-RC2
* Customers upgrading from v5.x to 6.0.0-RC1 or 6.0.0-RC2

## Symptoms

The receive statistics performance counters in 6.0.0-RC1 and RC2 are installed using the local address. The local address is the address that has been translated by the transport infrastructure. 

In version 5.0 those counters are created using:

`receiveAddress.Queue`

which happens to be

> The (lowercase) name of the queue not including the name of the machine or location depending on the address mode

This is a behavior breaking changes which adds no real value. It would require users which upgrade from version 5 to change their operation scripts to capture those newly created perf counters as well as a new installation of the performance counters under the elevated permissions. 

This is a spin-off issue from https://github.com/Particular/NServiceBus/issues/4157

## Actions required

Since this change changes the name of the performance counters you have reinstall the counters. More information can be found on the [performance counter documentation](https://docs.particular.net/nservicebus/operations/performance-counters) page.

## Change
- [x] Switch from local address to Logical Address
- [x] Document it as a breaking change for RC 1 and RC2 users

**Comment by timbussmann** [comment]
>  Document it as a breaking change for RC 1 and RC2 users

how are we going to do that?

**Comment by danielmarbach** [comment]
Good question. We can add it to the release notes @andreasohlund is preparing. Maybe also ask @Particular/docs-maintainers how we want to fly this

**Comment by andreasohlund** [comment]
>We can add it to the release notes @andreasohlund is preparing.

I was prepping release notes for v6? ( I figured we'd auto gen the release notes for the RC3?)

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus/issues/4173 is merged. Closing
