### ISSUE TITLE
Custom Saga Finders and concurrency behavior clarification

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4166]
What is the expected behavior with custom saga finders in relation to saga ids and concurrency? Is it even possible to properly control saga ids with custom saga finder? Wouldn't a custom saga finder for a saga which is started by multiple messages in the majority of cases mean we would create multiple saga instances?

**Comment by timbussmann** [comment]
maybe add to the description that currently, when using a custom saga finder it can result in a "duplicate" saga when two messages which start a saga are handled concurrently and they would otherwise result in the same saga according to the custom finder logic. This becomes even a bigger problem when the saga is completed, because the duplicate saga may still be around? Isn't that actually a bug?

**Comment by andreasohlund** [comment]
>Wouldn't a custom saga finder for a saga which is started by multiple messages in the majority of cases mean we would create multiple saga instances?

When using a custom finder it's up to you to handle the concurrency as you see fit. On let's say sqlserver it's likely that the user would create a unique key constraint to prevent duplicates?

**Comment by danielmarbach** [comment]
Looking at https://docs.particular.net/nservicebus/sagas/saga-finding I
think this is not clear at all. Also the name of the finder suggest query
semantics. Do we need to clarify docs?

**Comment by timbussmann** [comment]
👍 to fix docs immediately and enhance the snippets to show some locking mechanism to prevent duplicates

**Comment by danielmarbach** [comment]
A custom saga finder is inherently tied to the persistence. For example a custom saga finder would use RavenDB session or NHibernate session to find the saga data. This would mean we would need to show a way to do it for each persistence. Not sure it is worth the effort.

**Comment by timbussmann** [comment]
the locking mechanism doesn't seem to be necessarily tied to the persistence?

**Comment by danielmarbach** [comment]
well yes it is. You wouldn't write an InMemory lock in a custom saga finder if you have a database technology for example providing unique key constraints, or would you?

**Comment by timbussmann** [comment]
but wouldn't an inmemory lock be good enough to demonstrate the issue and that users need to handle it themselves?

**Comment by andreasohlund** [comment]
The docs https://docs.particular.net/nservicebus/sagas/saga-finding
 
already has a note that says:

>When using custom saga finders users are expected to configure any additional indexes needed using the tooling of the selected storage engine.

Isn't that good enough? or do we need to spell out "and unique key contraints etc See saga concurrency for more info LINK"

**Comment by timbussmann** [comment]
I'd explicitly state that users need to handle concurrency to prevent duplicate sagas themselves.

**Comment by danielmarbach** [comment]
The above statement is very vague. I think we need to explicitly state that they need to handle concurrency and link to the saga concurrency page.

**Comment by andreasohlund** [comment]
so reword + make it a warning?

**Comment by andreasohlund** [comment]
Doco pr raised https://github.com/Particular/docs.particular.net/pull/1968
