### ISSUE TITLE
Move the InMemoryGatewayPersistence to the gateway package

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4167]
No need for it to be in the core.

Moving the IDeduplicateMessages interface should also be done but that's a different issue

**Comment by lailabougria** [comment]
I think this is done looking at https://github.com/Particular/NServiceBus/blob/c936c938c76f6a2e2e98a2849a9f029bb530e09b/src/NServiceBus.Core/obsoletes-v8.cs#L15

**Comment by andreasohlund** [comment]
Yea, its done. Assigning to v8 milestone
