### ISSUE TITLE
Check usage of DependsOn in Feature

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4168]
We know that most usage of DependsOn with features is a design smell. It is an indication of feature dependencies and arguably that means the feature cannot stand on its own. Let's check the current DependsOn of features and chop out individual workable items for it.

**Comment by andreasohlund** [comment]
How about we go through them all and make sure we have issues raised to deal with each usage?

**Comment by danielmarbach** [comment]
@Particular/nhibernate-persistence-maintainers @Particular/azure-storage-persistence-maintainers @Particular/ravendb-persistence-maintainers in the long run we would like to get rid of feature dependencies. Based on our research we found out that feature dependencies mostly hide missing design flaws and we would like to properly address those. I raised and linked several issues to this parent issue. The storage related issues (here talking about InMemory) also affect RavenDB and NHibernate.

**Comment by danielmarbach** [comment]
Raised individual issues. Closing
