### ISSUE TITLE
Compatibility with ASPNET Core runtime

### ISSUE THREAD

**Issue by bottomup** [Particular/NServiceBus#4179]
As mentioned, the latest prerelease of NServiceBus does not support the new ASPNET Core runtime.
https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/

When will this be supported? Please inform because it will influence component usage decisions. Thanks.

**Comment by janovesk** [comment]
Hi, @bottomup!

Unfortunately we don't currently have a version of NServiceBus that is compatible with the .NET Core runtime. 

We have had quite a bit of internal discussion surrounding .NET Core, how and when to implement a compatible version of NServiceBus for it. There are a few full framework features that we currently depend on. Also, we also have dependencies on a multitude of downstream libraries that would need to support it, like the client libraries for the transports, persistence, and containers.

We are watching the progression of .NET Core but haven't yet made a decision on when we will be supporting it.

That said, there is no issue running NServiceBus inside ASP.NET Core applications as long as they target the full .NET Framework, just as this sample demonstrates.

**Comment by bottomup** [comment]
Hi @janovesk thanks for clarifying. I will follow the discussion and try to target the full .NET Framework in my Core application.

**Comment by johnfake** [comment]
Hi @janovesk ,

currently your statement ist true and works fine:

> That said, there is no issue running NServiceBus inside ASP.NET Core applications as long as they target the full .NET Framework, just as this sample demonstrates.

However, ASP.NET Core 2.0 (release in a few months) cannot target the full framework anymore. I would be nice if you can comment this breaking issue. See https://github.com/Particular/NServiceBus/issues/4686

Best Regards
Alexander

**Comment by timbussmann** [comment]
@bottomup just a quit follow up: we announced the upcoming support of .NET Core 2.0 on our blog: https://particular.net/blog/nservicebus-on-net-core-its-time. This will allow you to run NServiceBus v7 on the .NET Core platform.

**Comment by bottomup** [comment]
@timbussmann thanks for the heads up!
