### ISSUE TITLE
SubscriptionBehavior in acceptance tests (core and MSMQ) uses InsertBeforeIfExists

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4199]
Relates to https://github.com/Particular/NServiceBus/issues/3582

`NServiceBus.AcceptanceTests `and `NServiceBus.Msmq.AcceptanceTests `contain a `SubscriptionBehavior` which invokes an `OnEndpointSubscribed `or `OnEndpointUnsubscribed `action. The behavior uses a RegisterStep with `InsertBeforeIfExists("ProcessSubscriptionRequests");` to only enable this behavior if MessageDrivenPubSub is used. Let's get rid of it.

**Comment by danielmarbach** [comment]
It is also used of course in other repos see https://github.com/search?q=org%3AParticular+InsertBeforeIfExists&type=Code

**Comment by danielmarbach** [comment]
ServiceControl seems to use it for the acceptance tests to add a special header https://github.com/Particular/ServiceControl/blob/d681bfe2f3611ce0c9123e5a1e7641bb122452f8/src/ServiceControl.AcceptanceTests/SessionCopBehavior.cs

**Comment by timbussmann** [comment]
> he behavior uses a RegisterStep with InsertBeforeIfExists("ProcessSubscriptionRequests"); to only enable this behavior if MessageDrivenPubSub is used. Let's get rid of it.

`InsertBeforeIfExists` always registers the behavior, it just doesn't throw in case the dependent behavior doesn't exist. How exactly do you want to get rid of it, as there are many tests which rely on this behavior?

**Comment by timbussmann** [comment]
maybe we could move the registered behaviors from `OnEndpointSubscribed` and `OnEndpointUnsubscribed` to the `TrnsportReceiveContext` instead.
