### ISSUE TITLE
SubscriptionReceiverBehavior uses InsertAfterIfExists

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4200]
Relates to https://github.com/Particular/NServiceBus/issues/3582#issuecomment-252558068

The `SubscriptionReceiverBehavior` uses  `InsertAfterIfExists("ExecuteUnitOfWork");` to put itself after the `ExecuteUnitOfWork` step. Do we really need unit of work support for the subscription storage? I suppose any subscription storage we currently have doesn't need the manage unit of work approach and if it does then it is a code smell. How about we remove that feature dependency in a major? Or could we do it in a minor since I'm pretty sure relying on manage unit of work for a subscription store would not work and could be treated as a bug?

**Comment by andreasohlund** [comment]
I'd say this can go in a minor for the reasons you mention

**Comment by mikeminutillo** [comment]
We do have [a unit test asserting this behavior](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_a_subscription_message_arrives.cs#L13)
