### ISSUE TITLE
Callbacks use InsertAfterExists

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4201]
Relates to https://github.com/Particular/NServiceBus/issues/3582#issuecomment-252558068

InsertAfterExists is used by the callbacks in the correlation table update behavior.

https://github.com/Particular/NServiceBus.Callbacks/blob/7d69f94979e7dc82c8527d7cbc0a0d95a863a7e0/src/NServiceBus.Callbacks/Request/UpdateRequestResponseCorrelationTableBehavior.cs#L46

It uses `context.MessageId`. The intention of placing it after the outgoing mutators is to capture any updates on the message id. This seems to be a tricky one to fix because it requires us to reach consensus whether we still allow overriding the message id in mutators or in general.

**Comment by andreasohlund** [comment]
Do we have any known use-cases for overriding message id today?

Outbox is the only one that comes to mind and there we could consider using a specific header for this purpose instead `NServiceBus.OutboxMessageId` or similar?

**Comment by andreasohlund** [comment]
@danielmarbach should this be moved to the callbacks repo?

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus.Callbacks/issues/47
