### ISSUE TITLE
InstanceMappingFileFeature depends on RoutingFeature

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4203]
Relates to https://github.com/Particular/NServiceBus/issues/4168

Currently the InstanceMappingFileFeature depends on the RoutingFeature. Let's flesh out a plan of attack to remove the dependency

**Comment by danielmarbach** [comment]
@timbussmann @SzymonPobiega would this be something you could have a look at when investigating the static routing?

**Comment by dbelcham** [comment]
to be addressed in #4389
