### ISSUE TITLE
InMemoryGatewayPersistence stringly typed depends on NServiceBus.Features.Gateway

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4206]
Relates to https://github.com/Particular/NServiceBus/issues/4168

Should be moved out and resolved when the persistence for the gateway is moved into the gateway package. This also affects NHibernate and RavenDB persistence (as well as native SQL Server persistence)

**Comment by dbelcham** [comment]
Does this deserve the same decision as #4210 and other's have received about no action? https://github.com/Particular/NServiceBus/issues/4210#issuecomment-260302405

**Comment by danielmarbach** [comment]
@dbelcham agreed.Closing
