### ISSUE TITLE
InMemorySagaPersistence depends on Sagas

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4208]
Relates to https://github.com/Particular/NServiceBus/issues/4168

Flesh out a PoA to address this issue

**Comment by dbelcham** [comment]
Does this deserve the same decision as #4210 and other's have received about no action? https://github.com/Particular/NServiceBus/issues/4210#issuecomment-260302405

**Comment by danielmarbach** [comment]
@dbelcham agreed.Closing
