### ISSUE TITLE
MsmqUnitOfWork doesn't clear transactions correctly

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4215]
While investigating issues during upgrading ServiceControl to 5.2.18 we noticed that MsmqUnitOfWork doesn't "clear" transactions properly. This wasn't an issue before 5.2.18 because with LongRunning tasks, there was no risk of reusing threads while this is now very likely in 5.2.18 where we use the ThreadPool instead.

## Who's affected

This only affects users on NServiceBus 5.2.18 using MSMQ transport with native transactions (DTC disabled)  and when sending from outside the pipeline.

## Symptoms

Exceptions (e.g. `Failed to send message to address`) occur when sending messages via `IBus`.

For more details, please refer to the fix raised in #4216. 
Thanks for raising the problem @johnsimons and to @danielmarbach for the brainpower ;)

**Comment by bording** [comment]
Fixed in #4216

**Comment by johnsimons** [comment]
Well done team, awesome investigation.
