### ISSUE TITLE
Bad missing performance counters error message 

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus#4230]
> 2016-10-12 14:53:51.9052|FATAL| 1|Host.Program|MainNServiceBus performance counter for 'Critical Time' is not set up correctly. To rectify this problem download the latest powershell commandlets from http://www.particular.net downloads page.

There are no PowerShell commandlets at http://particular.net/downloads

I'm not sure exactly how the error message should change. The info I found to get things working is at https://docs.particular.net/nservicebus/operations/performance-counters#installing-counters but I'm not sure we want to deep link.

**Comment by danielmarbach** [comment]
@adamralph would you like to give this a stab?

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers it seems we are talking here about improving a WARN in a log statement. It seems to be feasible to work on that for the next minor. Do you agree?

**Comment by timbussmann** [comment]
@danielmarbach 👍 sounds good to me.

**Comment by adamralph** [comment]
@danielmarbach sure, I can't get to it just yet, but I'll assign myself so I don't forget. 

In the meantime, I'm happy if someone else picks it up if they have time.

**Comment by danielmarbach** [comment]
There is no hurry @adamralph

**Comment by adamralph** [comment]
@Particular/docs-maintainers would it be OK to deep link https://docs.particular.net/nservicebus/operations/performance-counters#installing-counters in an NSB log message?

**Comment by danielmarbach** [comment]
I don't think this is acceptable. At least we have never done it before because subtitles can always be moved and will not be redirected

**Comment by SimonCropp** [comment]
Yeah someone can rename a section heading and your link is broken

**Comment by adamralph** [comment]
That was my fear. Thanks for confirming.

What about stepping up a level and deep linking to the page only? Do we have any kind of redirect policy for when a page is renamed/removed?

**Comment by SimonCropp** [comment]
Yes we do redirects where possible. Sometimes it is not. Eg splitting a page. 

Putting a link in code is making an agreement that the content, at the target url, will not change as long as someone is using that code is used. So we r talking years.

**Comment by adamralph** [comment]
OK, so any kind of deep link is not a good choice.

I'm not sure how best to change the message. Would something like this work?

> NServiceBus performance counter for 'Critical Time' is not set up correctly. To rectify this problem consult the documentation regarding performance counters at https://docs.particular.net
