### ISSUE TITLE
Create a guide for customers migrating routing from beta to RTM

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#4240]
Yesterday I stumbled upon the customer who had issues in upgrading his code from using NSB v6 RC 1 to NSB v6 RTM (routing bit). As the API changed within the V6 release we haven't provided any obsoletes nor upgrade guide leaving our customers in bad spot. I think what we need to do is write some small upgrade guide for anyone that built their system on early RC to make the upgrade easier. 

cc: @timbussmann @SzymonPobiega 

The desk case: 
https://eu1.salesforce.com/02sD00000107hXZ

**Comment by timbussmann** [comment]
to clarify, this scenario isn't RC1 to RTM since we cannot have no breaking changes between those versions following our RC "policy", but beta1 to RTM. Yes there are no upgrade guides between beta versions. Personally, I don't see value in maintaining upgrade guides between beta versions and between beta and RTM versions.

I'd be more interested what parts on our documentations were not good enough to help the user look up the routing API there instead?

**Comment by WojcikMike** [comment]
@timbussmann you are correct with beta rather than RC. 

In terms of not maintaining upgrade guides. I understand that usefulnes of such thing is short lived however we are asking customers to use our betas to get feedback. And then when they want to upgrade they don't get the same experience when upgrading between majors. I don't think it is fair for our customers to put them in such situation. 

With regards to documentation. If I were the person that wrote the code then it means that I need to once again go through the doco and almost repeat the process of discovering the API keeping in mind what I wrote previously. When you get have something obsoleted with a message, "this api was  removed use instance mapping file" - the message is clear. If you don't see API on the doco page it is not such clear. 

Now if someone else is migrating the code that I wrote then they see API that don't exist for which there is no documentation and are looking on new documentation trying to map what they see in beta code vs what is in RTM. 

Creating something small to cover the difference made in routing would make life of some customers easier.

**Comment by timbussmann** [comment]
While I don't disagree with you that it would make it easier if some guidance would exist, I still think it's not worth the effort to go through.

* Betas are expected to contain breaking changes and by using betas I think you are aware of that situation and that we're not going to provide the same amount of effort to design upgrade paths.
* We spent a lot of time into our documentation and upgrade guides. E.g. https://docs.particular.net/nservicebus/messaging/routing isn't more than a 5 minute read which I'd assume should answer most of the questions how to do routing in the RTM. I think that's an amount of time which is acceptable for an upgrade. And again, if the docs wasn't helpful, I'm more than happy to improve the docs in general.
* I think that we can help users coming from betas to the RTM via our support channels in case the documentation isn't able to answer the questions.

thoughts @Particular/nservicebus-maintainers ?

**Comment by bording** [comment]
I agree with @timbussmann here. I don't see the value of creating an upgrade guide for a beta -> RTM migration. Our existing documentation and V5 to V6 upgrade guide should provide enough information.

**Comment by timbussmann** [comment]
as there were no further thoughts/arguments for the last days, I'm closing this discussion. Feel free to reopen if you feel this is something we should discuss again.
