### ISSUE TITLE
MSMQ catch invalid TransactionScope configurations at startup

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4247]
based on #4237, we can detect unsupported/invalid configurations at startup and prevent "runtime" errors  (during message handling). Instead we can throw on endpoint startup which makes it easier to detect the issue.

Unsupported configurations:
- when using TransportTransactionMode.TransactionScope
  - TransactionScopeOptions(isolationLevel:IsolationLevel.Snapshot)
- when using a different TransportTransactionMode, any TransactionScopeOptions usage should be avoided.

any other invalid transaction configurations (e.g. invalid timeout settings)?

**Comment by andreasohlund** [comment]
We already check the timeout value to make sure it's with in the valid range for the machine.

But similar to ScopeOptions we shouldn't allow the timeout to be changed if `TransportTransactionMode.TransactionScope` is used right?

**Comment by timbussmann** [comment]
> We already check the timeout value to make sure it's with in the valid range for the machine.

ah, wasn't aware of this 👍 

> But similar to ScopeOptions we shouldn't allow the timeout to be changed if TransportTransactionMode.TransactionScope is used right?

yeah. Ideally we wouldn't have an API which allows that configuration without configuring transactionscope.

**Comment by andreasohlund** [comment]
What actions do we take here? to fix this we would have to push the `.Transactions()` method down to the transport? 

I propose we close this as covered by https://github.com/Particular/NServiceBus/issues/4277 with a comment about the timeout settings

**Comment by timbussmann** [comment]
I'd think we should keep this open (and move to the MSMQ repo)?

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/9.
