### ISSUE TITLE
Default MSMQ deadletter flag to OFF for messages with a TTBR

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4260]
To avoid filling the DLQ's with expired messages.

Yes this would hide configuration issues but I think that is better compared to filling the DLQ and running out of disk?

Split of https://github.com/Particular/NServiceBus/issues/2372

Customer Request: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/GeHawkCKsgU/zSqU54QzAwAJ

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers are we ok with treating this behavior change as a bug since DLQ == on essentially cancels out the disk space saving part of TTBR usage by moving the messages to DLQ when they expire.

In short: 

TTBR becomes pointless from a disk saving perspective unless we fix this. (TTBR will currently still save the endpoints from needed processing of messages though)

**Comment by timbussmann** [comment]
there are maybe other reasons to use TTBR outside disk saving reasons. I'm on the fence about marking this as a bug. From the specific use case you mentioned, yes this could be treated as a bug. The documentation states nothing about that scenario and instead says:

> his is important mainly in environments with high volumes of messages where there is little business value in processing a delayed message since it will already be replaced by a newer, more relevant version.

would treating this as a bug change anything?

**Comment by andreasohlund** [comment]
>would treating this as a bug change anything?

We wouldn't have to wait until the next major?

**Comment by timbussmann** [comment]
from the docs:

Rabbit:

> Using TimeToBeReceived as a disk saving measure on RabbitMQ is not ideal for queues with long-lived messages

Azure transports: (ASB + ASQ ?)

> Using TimeToBeReceived as a disk saving measure on the Azure transports is not a great choice for queues with long-lived messages

In Sql it could possibly be seen as a disk saving measure as far as I understand it. Can we add an optional setting in v6 to disable DLQ and make it default in v7?

**Comment by andreasohlund** [comment]
>Can we add an optional setting in v6 to disable DLQ and make it default in v7?

You can already turn DLQ off for the entire endpoint

https://docs.particular.net/nservicebus/msmq/connection-strings

That seems good enough for now. Flagging this as a breaking change so that we consider it for v7

**Comment by timbussmann** [comment]
turning it off for the whole endpoint seems to be a bit more radical, but also I don't see a real issue with that as of now. I'm ok to already assign this to v7 if we think that's definitely something we want to address in the next major.

**Comment by gbiellem** [comment]
@andreasohlund From a ServiceControl plugin perceptive it would be good to be able to turn it off selectively for MSMQ . Having Heartbeats fill the txDLQ is a real headache for end users.

**Comment by andreasohlund** [comment]
Since the heartbeats have a ttbr set this would sort that out right?

**Comment by gbiellem** [comment]
Yes it would but it seems wrong to force this to be off for the whole endpoint to stop the SC plugin from DDOSing the system.  I assume we default to having this on for a reason.

**Comment by gbiellem** [comment]
Or if you mean default MSMQ deadletter flag to OFF for messages with a TTBR would solve it then yes I agree.  However waiting for V7 to solve this for SC seems like a fail

**Comment by andreasohlund** [comment]
>Or if you mean default MSMQ deadletter flag to OFF for messages with a TTBR would solve it then yes I agree

Correct

> However waiting for V7 to solve this for SC seems like a fail

@Particular/nservicebus-maintainers thoughts, this should be a fairly small change that we can bundle into 6.2? (or do we see this as a breaking change == major)

**Comment by timbussmann** [comment]
to change DLQ settings for the TTBR messages, it does require changes on the message producer, do I understand this correctly?

**Comment by andreasohlund** [comment]
Correct, on send do a:

"if message has TTBR  then default.DLQ = off"

**Comment by indualagarsamy** [comment]
See related discussion on GG issue here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/GeHawkCKsgU/zSqU54QzAwAJ

**Comment by timbussmann** [comment]
I'm ok with including this in 6.2. Do we need to make sure that we provide an API to opt-in into the current behavior? Could we have a sendoption which defines whether the message should be DLQed?

**Comment by andreasohlund** [comment]
>I'm ok with including this in 6.2. Do we need to make sure that we provide an API to opt-in into the current behavior?

I think we should but it would be at the endpoint level

>Could we have a sendoption which defines whether the message should be DLQed?

That idea is already tracked here:

https://github.com/Particular/NServiceBus/issues/2372

**Comment by andreasohlund** [comment]
Talking to @timbussmann we decided to not treat this as a breaking change but rather a bugfix since the current default defeats half of the purpose with TTBR namely to save disk space by allowing messages that have lost their business value to be discarded by the queuing system. Given that this is not a critical but it will be released in the upcoming 6.2

**Comment by andreasohlund** [comment]
I'll go ahead with the doco
