### ISSUE TITLE
TimeoutManager concurrency configuration

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4264]
The TimeoutManagers satellite queues use the default concurrency settings (`PushRuntimeSettings.Default`) ( previously using the main queues settings, fixed here: https://github.com/Particular/NServiceBus/issues/4213). This value can't be modified currently.

This may cause issues in environments with a lot of timeouts or be too "costly" in environments with very few timeouts. To adjust to these situations, we should provide a configuration API to specify the TimeoutManagers concurrency setting.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers I think we should include this in 6.1, thoughts?

**Comment by danielmarbach** [comment]
Definitely think it would be worth to include this in 6.1

**Comment by timbussmann** [comment]
implemented by #4282 
need to raise a doc PR before closing this

**Comment by timbussmann** [comment]
closing this as docs PR has been raised.

**Comment by SimonCropp** [comment]
doco merged https://docs.particular.net/nservicebus/operations/tuning#configuration-timeoutmanager-satellite-queues

@tim thanks
