### ISSUE TITLE
Transport Test for isolated dispatch with one or multiple isolated transport operations

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4270]
Carved out from https://github.com/Particular/NServiceBus/issues/3677

Currently we don't specify what the behavior of a dispatcher should be for the supported transaction modes in combination with isolated dispatches. Should we write one or multiple transport tests that represent the transaction modes as well as the behavior expected with one or multiple isolated dispatches?

For example:

- In a handler an immediate dispatch leads to a dispatcher call with one transport operation marked as isolated. 
- With the outbox turned on all outgoing operations are marked as isolated and passed in one call to the dispatcher. 

In theory for example for MSMQ we could batch all outgoing isolated transport operations into a single transaction when the transaction mode is higher than ReceiveOnly. For ReceiveOnly we could in theory create a transaction per outgoing queue. Should we align this behavior over all transports if possible?

@Particular/nservicebus-maintainers @Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers @Particular/rabbitmq-transport-maintainers @Particular/sqlserver-transport-maintainers 

This issue could serve as a parent issue for all related transport changes.

**Comment by tmasternak** [comment]
👍 for the idea. We did some minimal testing around that in [sql](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer.IntegrationTests/When_dispatching_messages.cs#L46). 

> In a handler an immediate dispatch leads to a dispatcher call with one transport operation marked as isolated.

I think this is true only for transports with native pub-sub support. Otherwise on publish with `DispatchConsistency.Isolated` and more than one subscriber a `Dispatcher` will receive two operations.

**Comment by adamralph** [comment]
I'm afraid I don't have enough context to comment on behalf of @Particular/rabbitmq-transport-maintainers. I'd need an explanation of some of these concepts.

**Comment by bording** [comment]
Since RabbitMQ has no transactions or batching capability, we currently don't even look at the DispatchConsistency value that gets passed to the dispatcher. I can't think of anything we could do differently based on that value, either.

**Comment by SeanFeldman** [comment]
ASB does batch based on isolation level. 👍 for a test.

**Comment by timbussmann** [comment]
I think @bording brings up an interesting point: We somehow assume that `ReceiveOnly` means "single queue transactions" which doesn't hold true in rabbitMQ. So that assumption couldn't be met by rabbitMQ. But for `SendsAtomicWithReceive` it would still be valid.

**Comment by tmasternak** [comment]
@timbussmann I think that it might be good to explicitly state the message processing model that NServiceBus takes. From user\handler perspective we say that endpoint works in receive-message->process->send-messages loop. In such case the `TransactionMode` refers to transactionality of all three grups operations.

**Comment by timbussmann** [comment]
Discussed this with @Particular/nservicebus-maintainers we concluded that it's up to the transport how to handle multiple transport operations with isolated consistency within the same dispatch operation. Note that ImmediateDispatch will always contain a single operation anyway. But we want to add a transport test to ensure that isolated dispatches are not included in transactions (see #4392)
