### ISSUE TITLE
Update license dialog screenshot in license renewal email

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus#4272]
As per https://github.com/Particular/OptimizeTrialExtensions/issues/10#issuecomment-255846666

@Particular/nservicebus-maintainers please make sure this is done with the next release which includes https://github.com/Particular/NServiceBus/pull/4146

**Comment by indualagarsamy** [comment]
@adamralph - OTE is a private repo. Can you expand on the what was actually said in the OTE issue comment in the issue description itself as NServiceBus is a public repo?

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - does this issue even belong in this repo? How is sending an email connected to this repo?

**Comment by adamralph** [comment]
@indualagarsamy I was asked to raise this here. In retrospect I agree that it doesn't make sense to have this as an issue in this repo. One way or another though, this needs to be done in coordination with the 6.1.0 release.

**Comment by timbussmann** [comment]
6.1 is now released. From the comments in the linked issue it's not immediately clear to me what steps are required to to, so can somebody from the original tf please chime in and do this together with us? As @DavidBoike seems to have gone through the required steps already, I'll assign him (+me) to this task now.

**Comment by DavidBoike** [comment]
Image updated in Pardot. Also added info to https://github.com/Particular/OptimizeTrialExtensions/issues/10#issuecomment-255846666 to describe where it's hosted and how to change it again in the future.
