### ISSUE TITLE
IManageUnitsOfWork can't access pipeline state

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4281]
Eg. multi tenancy would need access to headers to pick the correct connection string etc.

Since we plan to deprecate this API in v7 I propose the following:

- [ ] Change the upgrade guide for v6 to highlight this and guide users towards using a behavior if they need access to pipeline state
- [x]  [Create a sample that show how to mimic UOW using a behavior instead](https://github.com/Particular/docs.particular.net/issues/2228)
- [ ]  Put a NOTE in the UOW doco https://docs.particular.net/nservicebus/pipeline/unit-of-work to highlight this
- [ ]  Put a NOTE in https://docs.particular.net/samples/unit-of-work/ to point v6 users to the new sample

**Comment by MarcinHoppe** [comment]
Is obsolete in a minor release advisable under SemVer?

**Comment by andreasohlund** [comment]
This is a bit of a grey zone but we've decided that obsolete with a WARN is ok since user can still use the type.

The caveat is that you would have to suppress the WARN if you have "fail build on warning" turned on.

**Comment by MarcinHoppe** [comment]
That can go into upgrade guide, right?

**Comment by andreasohlund** [comment]
I'll start creating the new UOW sample

**Comment by brunobertechini** [comment]
+1

**Comment by timbussmann** [comment]
@andreasohlund do we still want to obsolete the uow interface completely? It seems it would still work as previously as long as you're not accessing context/message specific data (e.g. managing a ravendb session across multiple handlers still works perfectly fine)

@brunobertechini seeing your +1, are you currently experiencing issues with the uow interface in v6? If yes, would you mind giving us some insights what you're trying to achieve within that unit of work to make sure we have relevant use cases in mind?

**Comment by andreasohlund** [comment]
Given that my statement

>Store state like a "session" somewhere. In v5 users would lean on their IoC container/thread static for this

Is false, since we use child containers you can store state in the IoC just fine.

This means that IManageUnitsOfWork is fine as long as you don't need access to headers/message etc.

Description updated.

@SimonCropp are you happy with making the new UoW sample + updates to upgrade guide and doco the only action points here?

**Comment by SimonCropp** [comment]
> are you happy with making the new UoW sample + updates to upgrade guide and doco the only action points here?

Sounds good

**Comment by andreasohlund** [comment]
Description updated, removed this from the 6.1 milestone since no changes to the core code is needed.

Will raise a docs issue instead

**Comment by andreasohlund** [comment]
Issue raised to improve the UOW api in the future https://github.com/Particular/NServiceBus/issues/4298

**Comment by SimonCropp** [comment]
sample merged and checkbox ticked off in description

**Comment by andreasohlund** [comment]
docs PR raised https://github.com/Particular/docs.particular.net/pull/2274

 closing this
