### ISSUE TITLE
Update testing projects to .NET Framework 4.6

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4291]
We should update the all testing projects in the core to 4.6. Since shipping this with a new minor version could cause downstream packages to break, it seems like we should plan this for the next major?

**Comment by dbelcham** [comment]
What problem does moving the tests to 4.6 solve?

**Comment by timbussmann** [comment]
there are no direct problems related to it, but since it's a breaking change I'd say we should make sure we update it before missing that opportunity with the next major.
Also, it makes it slightly more comfortable to write async code e.g. by using `Task.CompletedTask`.

**Comment by timbussmann** [comment]
also, to align better with potential .net standard 2.0 support, we should upgrade to 4.6.1 anyway.

**Comment by timbussmann** [comment]
decided with @Particular/nservicebus-maintainers to RFC this as for .net core support we don't need to bump the major version and we could keep the amount of breaking changes for existing users lower.

**Comment by timbussmann** [comment]
just realized that this issue is actually only about the testing project. I think at the current point there is not much value in targeting different frameworks in core and testing. An RFC to update core to target 4.6.2 has been raised. Closing this issue as the outcome of the RFC will also impact the target framework of the testing projects.
