### ISSUE TITLE
Remove Repeat from ATT Framework

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4292]
So far it seems that there are no direct objections on removing the `Repeat` functionality for acceptance tests as we don't want to run the same tests multiple times with different configurations in repeat but use different tests / test projects instead.

We currently use repeat mainly to ignore tests which aren't supported on the specific configuration (e.g. native pubsub, dtc support, ...).

Removing `Repeat` will make the tests easier to read, the framework easier to maintain and provide the same way to write tests across all configurations.

One possible approach would be something similar used in the transport tests, where a failed check essentially calls `Assert.Ignore` and causes the test to be skipped. Based on that idea we could state the "test requirements" before executing the test, e.g.:

```
Require<DtcSupport>();

await Scenario.Define<Context>()[...]
```

With the current Repeat options, it's the test projects responsibility to opt-out of unsupported configurations. That seems to be the "safer" but more painful approach than opt-in.

(also, for potential end users it's very unlikely to use these methods, as they most likely won't have different plugins and configuratinos)

@Particular/nservicebus-maintainers thoughts?

**Comment by bording** [comment]
I like the idea of moving the configuration support checks out into their own thing so that we don't have to write those kinds of tests differently.

I'm not convinced yet that switching to an opt-in approach is a good thing though. That seems to make it too easy for a downstream to miss tests that should be run.

**Comment by danielmarbach** [comment]
I think having a require instead of a repeat would be more intention revealing. The benefit of hooking into ignore or any similar kind of infrastructure would be that you also see on the build server all the ignored tests. Tag as future?

**Comment by dbelcham** [comment]
Has this moved from Discussion to needing an actionable issue that should be marked as Future? Or should we just remove Discussion from this issue?

**Comment by timbussmann** [comment]
it seems that so far we all agree on getting rid of the repeat as it's not used what it was intended for and we can find a better mechanism for what we use it for nowadays. Seems like there is not a clear idea on how the replacement would look like, but I think that's something which we don't necessarily need to agree on this discussion. So I'll raise an issue for the backlog and close this discussion then 👍

**Comment by andreasohlund** [comment]
@timbussmann how much of the repeat stuff is left?

**Comment by timbussmann** [comment]
none :) forgot about this issue. Closing this.
