### ISSUE TITLE
Should_throw_when_decrypting_with_wrong_key is flaky

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4295]
The acceptance test Should_throw_when_decrypting_with_wrong_key fails from time to time on the build server. I thought we already had a look at it, but it still seems to fail regularly.

e.g. https://builds.particular.net/viewLog.html?buildId=196924&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

**Comment by timbussmann** [comment]
#4299 temporarily ignores the test so it doesn't break random builds from time to time.

**Comment by kbaley** [comment]
Is this still an issue with the encryption moved out to a separate package?

**Comment by andreasohlund** [comment]
Correct, closing

@Particular/encryption-maintainers fyi
