### ISSUE TITLE
Improved unit of work API

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4298]
The current implementation has the following drawbacks:

* Can't access the pipeline state
* Requires users to register their implementation explicitly in DI

### New API proposal
 This proposal still allows DI to be used but removed the need users to explicitly register their UoW using our container abstraction/in their chosen container.

#### Registration

We can allow both a custom factory and a shortcut similar to our behaviors currently.

`config.RegisterUnitOfWork<MyUnitOfWork>()`

```
//use custom factory method
var myFactory = new MySessionFactory();

config.RegisterUnitOfWork(builder=>new MyUnitOfWork(myFactory));

```

#### Runtime API 

Here we can go with a similar approach to behaviors:

```
MyUnitOfWork: IV2UnitOfWork
   
   MyUnitOfWork(MySessionFactory factory)
   {
         this.factory = factory;
   }

   Task Execute(context,next)
   {
      using(var mySession = await factory.Open(context.Headers["tennant"]))
      {
           context.Extension.Set(mySession);
           await  next();

          await mySession.Complete();
      }
   }

```

**Comment by dbelcham** [comment]
Not going to label this as a Breaking Change since we have both the ability to do this without breaking (create new interface) or with a break.

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/issues/4493
