### ISSUE TITLE
when_receiving_multiple_timeouts  mapping to wrong property?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4320]
so this 
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs

has this

                protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MultiTimeoutsSaga1Data> mapper)
                {
                    mapper.ConfigureMapping<StartSaga1>(m => m.ContextId)
                        .ToSaga(s => s.Id);
                }

i think it should be

                protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MultiTimeoutsSaga1Data> mapper)
                {
                    mapper.ConfigureMapping<StartSaga1>(m => m.ContextId)
                        .ToSaga(s => s.ContextId );
                }

**Comment by andreasohlund** [comment]
Yea looks wrong.

Wonder if there ever is a use case to map to the saga id?(perhaps we should validate and throw at startup?)

**Comment by danielmarbach** [comment]
@SimonCropp would you mind sending in a PR?

**Comment by timbussmann** [comment]
> perhaps we should validate and throw at startup

I think for a real saga it can't be valid to specify the id as the correlation property for messages starting a new saga?

**Comment by andreasohlund** [comment]
>I think for a real saga it can't be valid to specify the id as the correlation property for messages starting a new saga?

Agreed, can you raise an issue?

**Comment by andreasohlund** [comment]
PR merged, closing this
