### ISSUE TITLE
make ActiveSagaInstance mock-able

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4322]
i was doing persister testing and needed to do a test where i needed an instance of `ActiveSagaInstance`. but the constructor is internal

**Comment by andreasohlund** [comment]
It seems pretty harmless to just make the ctor public, all types passed to it is public anyway.

**Comment by danielmarbach** [comment]
@SimonCropp is the test somewhere so that we can have a look at it? We could pull the change into 6.1, how about sending in a PR and link to the test in the description?

**Comment by timbussmann** [comment]
> It seems pretty harmless to just make the ctor public, all types passed to it is public anyway.

sounds like a reasonable small change to improve the situation 👍 

ping @SimonCropp (see @danielmarbach comment)

**Comment by SimonCropp** [comment]
well the only reason i need this is because i want to get the current saga https://github.com/NServiceBusSqlPersistence/NServiceBus.SqlPersistence/blob/master/SqlPersistence/Saga/ContextBagExtentions.cs  so to test that i need to inject an instance of ActiveSagaInstance into the context

**Comment by timbussmann** [comment]
will be included on the next minor.
