### ISSUE TITLE
Failure to set MSMQ permissions is suppressed

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4323]
We currently only log a warning meaning that the queues we create won't have the appropriate permissions. Everyone/Anonymous have write access but unless you're and admin you won't be able to read from the queue.

https://github.com/Particular/NServiceBus/pull/4304 fixes this for 6.1

I don't see a reason to backport?

**Comment by timbussmann** [comment]
I don't see a reason to backport either.
