### ISSUE TITLE
Limit MSMQ format name to 102 characters?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4324]
MSMQ can create and run with format names up to 159 characters but things like Queue.Exists and .SetPermissions can only handle 102.

### Symptoms

Users with a endpoint name resulting in a format name above 102 characters will see warnings in the log stating that the queues couldn't be checked and the queues won't have the requested permissions.

Should we consider only support max 102 character queues in vNext?

**Comment by andreasohlund** [comment]
Discovered while doing https://github.com/Particular/NServiceBus/pull/4304 cc @ramonsmits

**Comment by ramonsmits** [comment]
Maybe make it a soft validation. Limit the length to 102 and have the ability to disable this validation is the user actually needs longer queue names?

**Comment by timbussmann** [comment]
> Should we consider only support max 102 character queues in vNext?

since the queue name heavily depends on the environment (e.g. machine name), is there a way to check that upfront without causing msmq exceptions to bubble up and stop the endpoint?

**Comment by danielmarbach** [comment]
MSMQ is supported since the dawn of time. How many customers have actually run into this problem? I think we should not invest too much into MSMQ at the moment unless it provides huge value to our customers. Backlog or close?

**Comment by andreasohlund** [comment]
I'd say backlog for now with the intent to close as won't fix?

**Comment by timbussmann** [comment]
why not close it right away then?

**Comment by dbelcham** [comment]
I agree with @timbussmann What benefit do we get from having it open between now and the time we actually do "close as won't fix"?
