### ISSUE TITLE
Worker does not send a "ready" message processed message is retried or moved to the error queue

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4325]
## Who's affected

* Users using the NServiceBus Distributor with NServiceBus v6 when messages are going through Delayed Retries or are moved to the error queue

## Symptoms

The distributor node handles the capacity of all workers enlisted in the distributor. Everytime a worker becomes available for work it sends a ready message to the distributor indicating that the capacity is available again. When a worker fails processing a messages depending on its Recoverability configuration it either sends the messages to Delayed Retries or moves it into the error queue. The ready message is not sent back to the distributor. Each time such a failure occurs, the effective capacity of a worker as seen by a distributor decreases by 1 to the point when it reaches 0 and the distributor no longer sends messages to that worker.

This problem causes outages in production when the number of failed messages is higher than the capacity of a worker (usually the concurrency of the worker which by default is the processor count)

## Workaround

* Monitor the SLA [performance counters
](https://docs.particular.net/nservicebus/operations/performance-counters)
* Restart the worker node which is affected when no messages are being consumed

also to consider:

* Increase the concurrency of an endpoint

## Background information

Starting from v6 each worker has its own dedicated timeout manager. The distributor node has also its dedicated timeout manager. This is fine since the distributor and its workers are treated as a single logical instance and needs to share the timeout storage anyway. 

We cannot blindly send out ready messages when the processed messages goes into Delayed Retries since this could lead an ever increasing capacity of the worker as seen from the distributor node therefore potentially overflooding the worker. 

In mixed environments where Sender Side Distribution is mixed with the distributor, as advised in our upgrade guides, a worker can process messages coming from Sender Side Distribution as well as from the distributor. In 6.0.0 all failing messages are handled by the timeout manager on the worker and stick to the worker the message failed on. With 6.0.1 we will change this erroneous behavior to the following:

* No matter whether the message is coming from Sender Side Distribution or the distributor the delayed retries will always to sent to the distributor and handled by the timeout manager by the distributor as long as the worker is enlisted.

**Comment by SzymonPobiega** [comment]
PR with failing acceptance tests: https://github.com/Particular/NServiceBus/pull/4327

**Comment by SzymonPobiega** [comment]
Closed in favor of https://github.com/Particular/PlatformDevelopment/issues/1044

**Comment by timbussmann** [comment]
discussed a potential approach with @danielmarbach. One thing which I think might differ from v5 is that we wouldn't send ready messages for SLR messages, as this could also end in a constant increase of the workers capacity if not handled very very carefully. E.g. consider the scenario:
- message1 arrives, fails all immediate retries, no ready message
- message1 sent to local timeout manager via delayed retries, send ready message (capacity = 1)
- message2 arrives from the dispatcher, succeeds, send ready message (capacity = 2)
- message1 comes around from the timeout manager, either succeeds or moves to the error queue, send ready message, (capacity = 3)

therefore I think we should only send ready messages on "completed messages" ( = succeeded or completely failed). Thoughts @SzymonPobiega ?

**Comment by andreasohlund** [comment]
>we wouldn't send ready messages for SLR messages

This sounds off, at least in v5, timeouts where routed via the distributor so it would be ok to send a ready message once the SLR is requested since the retry would be routed to one of the instances just like any other message?

Also imagine if you have a long SLR delay => the instance won't process any messages until that delay is over?

**Comment by timbussmann** [comment]
> This sounds off, at least in v5, timeouts where routed via the distributor

I can't see any logic around that in v6, so my assumption is that we use the local timeout manager.

**Comment by SzymonPobiega** [comment]
I confirmed this. It is a problem in V6 worker implementation. It should be deferring to the distributor but it is not.

**Comment by SzymonPobiega** [comment]
Should we manage this bug separately or include this in scope of this issue?

**Comment by andreasohlund** [comment]
It seems like the fix for this issue is connected to how the timeouts are manages? (so we have to bundle?)

If not we will starve workers requesting timeouts?

Lets say we have capacity == 10.

Now have a saga do: RequestTimeout<CalculateInsurancePolicy>(TimeSpan.FromYears(1))

This will cause the first 10 messages to be processed but then we have to wait a year for the other ones?

**Comment by SzymonPobiega** [comment]
We discussed this in detail with @danielmarbach @timbussmann and @tmasternak  and we agreed that we have a technical solution for sending ready messages in a transactional way.

The other thing we discussed was weather we should send the SLR message to the distributor or to the worker queue. In V5 we always delayed to the distributor. The problem is we cannot find a good place to make a decision, at runtime, if SLR should go distributor or to worker queue. We agreed that we have two options:

### SLR to distributor

We always delay to distributor (but possibly via a local TM satellite). This had an advantage of working the same as in V5 for distributor scenarios but has a disadvantage of sending SLR messages to distributor even if they came directly to the worker (via sender-side distribution)

### SLR to worker

We send a ready message immediately when we send a message to SLR but we send the SLR to the worker queue. This has an advantage of work as expected in the sender-side distribution mode. The disadvantage is that works differently than the V5 distributor and if a node is removed, the SLR messages that were targeting it need to be manually re-routed.

**Comment by andreasohlund** [comment]
Updated title to `Worker does not send a "ready" message for delayed retries` , ok?

**Comment by andreasohlund** [comment]
Actually, the title is wrong, the same issue happens when a message is moved to error as well right? (I'll update)

**Comment by danielmarbach** [comment]
@andreasohlund correct

**Comment by gkorobkov** [comment]
Thank you. This is correct.
Originally I found this issue in case of exception is generated and message is moved to the error queue.

**Comment by SzymonPobiega** [comment]
https://github.com/Particular/NServiceBus/issues/4338 is related to this issue.
