### ISSUE TITLE
redundant async in PropertySagaFinder

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4336]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/PropertySagaFinder.cs#L18

**Comment by SimonCropp** [comment]
@danielmarbach ping

**Comment by danielmarbach** [comment]
Unfortunately, this is due to limited [co-variance.](https://social.msdn.microsoft.com/Forums/en-US/2a350bb3-b1cc-48a1-8684-8e67cf17bf55/lack-of-covariance-in-the-task-class?forum=async) `Task<TSagaData>` cannot be implicitly converted to `Task<IContainSagaData>`. Closing this.
