### ISSUE TITLE
Improve our Databus implementations

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus#4349]
Problems with current implementations:
- Performance:
    - GC inefficcient - allocates large byte arrays, rather than using stream API
- Fails in unexpected ways, depending on the used serializer implementation it might fail in different ways (serializer might take over the Databus responsibility without user realizing it which is even worse for performance):
    - doesn't work for deeply nested properties
    - doesn't work for unbound list of byte arrays (e.g. if one message has multiple "attachments")

Proposition:
-  instead of using property-based approach use attachments, in explicit Attachment API you'd pass a delegate instead of doing reflection on message properties
- contents would be read explicitly only when they're actually required, if some handler doesn't need them it would be ignored
- related sample:  https://docs.particular.net/samples/pipeline/stream-properties/
- optionally, File based one could be moved out of the Core to a separate package

/cc: @SimonCropp

**Comment by weralabaj** [comment]
@Particular/nservicebus-maintainers  any objections for doing spike/fix now? seems like it's a good, slow time ;)

**Comment by Scooletz** [comment]
`contents would be read explicitly only when they're actually required` - a new DelayedStream could be provided that would wrap an actual access to a stream for the read side, so you don't need to provide an explicit API.

```
public DelayedStream(Func<Stream> streamAccessor)
```

**Comment by andreasohlund** [comment]
Spikes is IMO always ok. Let's talk about potential actions based on the results of the spike?

**Comment by timbussmann** [comment]
there are quite a few issues around databus in this and the pdev repo. So far they haven't received much interest or priorities. The described issues also don't seem to be more critical than other issues around the databus and maybe we should split this issue into two?

**Comment by weralabaj** [comment]
> So far they haven't received much interest or priorities.  The described issues also don't seem to be more critical than other issues around the databus

Since I'm not on squad or core maintainer group, this is not something I can comment on. I'm simply raising an issue and noting we have some time before the wave starts, so this is a potential filler for the period before the first wave launches.

> split this issue into two

How? Why?

**Comment by timbussmann** [comment]
As andreas mentioned, nobody will stop you from doing some spikes if you care about these changes 👍 

from your description I read at least two issues:
* databus is GC inefficient and should probably use streams
* it can show different behaviors or even failures depending on the selected serializers

these points don't really seem to be tightly coupled to each other?

**Comment by danielmarbach** [comment]
Can we prioritize any work first where we talk about moving it out of the core?

**Comment by timbussmann** [comment]
👍 on @danielmarbach suggestion
