### ISSUE TITLE
IConfigureEndpointTestExecution is not used in MSMQ acceptance tests

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4353]
Currently, the methods provided by `ConfigureEndpointMsmqTransport` (`Configure` and `Cleanup`) in the MSMQ(!) acceptance testing project are never executed. While the interface providing those methods is defined in the `AcceptanceTesting` framework, it's only used & called by the infrastructure in the shared `AcceptanceTests` project. Therefore we never apply the specified configuration (e.g. metadata) and never execute the cleanup procedure.

**Comment by danielmarbach** [comment]
We discussed this in the maintainer sync and came to the conclusion that the MSMQ Acceptance tests should be written like any downstream acceptance tests if possible in order to prepare us for the moving out of MSMQ.
