### ISSUE TITLE
Simple custom ForkConnector throws a NullReferenceException

### ISSUE THREAD

**Issue by distantcam** [Particular/NServiceBus#4354]
In V6, I was trying to create a simple ForkConnector, but even a very basic one throws a `NullReferenceException`.

```
public class SimpleFeature : Feature
{
    public SimpleFeature()
    {
        EnableByDefault();
    }

    protected override void Setup(FeatureConfigurationContext context)
    {
        context.Pipeline.Register(typeof(SimpleFork), "Simple Fork");
    }
}

class SimpleFork : ForkConnector<IIncomingPhysicalMessageContext, ICustomContext>
{
    public override async Task Invoke(IIncomingPhysicalMessageContext context, Func<Task> next, Func<ICustomContext, Task> fork)
    {
        await next().ConfigureAwait(false);

        await fork(new CustomContext(context)).ConfigureAwait(false);
    }
}

interface ICustomContext : IBehaviorContext { }

class CustomContext : ContextBag, ICustomContext
{
    public CustomContext(IBehaviorContext parentContext)
        : base(parentContext?.Extensions)
    {
    }

    public IBuilder Builder => Get<IBuilder>();

    public ContextBag Extensions => this;
}
```

Am I doing something wrong?

**Comment by danielmarbach** [comment]
@distantcam unfortunately we do not support this right now. See 

https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors

![image](https://cloud.githubusercontent.com/assets/174258/20745825/53a4f166-b6e3-11e6-8c6c-7046322ecf68.png)

It is a bit quirky I agree because you can register the connector but you cannot register a custom pipeline. During runtime the pipeline cache tries to create a Pipeline<ICustomContext>. The cache get will [return null](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/PipelineCache.cs#L35)

I will raise an issue to throw a more meaningful exception.

**Comment by distantcam** [comment]
Ah! I was wondering what that line in the documentation meant.

So why can't we expose the https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/ForkExtensions.cs instead?

**Comment by danielmarbach** [comment]
It would still not work since you can't register your own pipelines

**Comment by timbussmann** [comment]
should we raise a new feature request to allow custom pipelines? @distantcam what did you want to do with a the custom pipeline?

**Comment by danielmarbach** [comment]
@distantcam @dbelcham will address the issue for 6.1 by throwing an exception which expresses the fact that we don't support registering of custom pipelines. We will raise an issue to track that feature [as @timbussmann suggested](https://github.com/Particular/NServiceBus/issues/4354#issuecomment-263888513).

**Comment by distantcam** [comment]
I was looking into doing custom auditing without using a transport. Do I
need to use a pipeline for that?

**Comment by andreasohlund** [comment]
>I was looking into doing custom auditing without using a transport. Do I
need to use a pipeline for that?

Is this for the "push audits straight to SI" idea you and me talked about in the past?

In that case perhaps just add a "audit writer behavior" in addition to the audit message going out via the transport? 

Ie just add a behavior for [IAuditContext](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Audit/IAuditContext.cs#L8)?

**Comment by distantcam** [comment]
@andreasohlund yes that's the idea.

So I think the doco is unclear on what exactly is a pipeline, stages, behaviors. It's unclear what I need to do to achieve what I want.

On top of that, why provide documentation on writing your own ForkConnector, StageConnector, etc, if they don't even work? Why not just remove those interfaces from the public api?

**Comment by danielmarbach** [comment]
@distantcam how about we look at your specific scenario a bit closer and see how we could improve the doco then? It is a bit difficult to understand what is missing for me at the moment.

We contemplated that. A few of the core maintainers at that time including me proposed that ForConnectors and StageConnectors are an internal thing and should never be exposed. @SimonCropp brought up good arguments from the perspective of the marketed extensibility of the pipeline that it should be possible to replace existing ForkConnectors and StageConnectors. That's what we enabled by exposing those classes and interfaces. But it is not supported to Fork or Stage into custom contexts.

**Comment by distantcam** [comment]
@danielmarbach That last bit makes sense. I guess then the message needs to be made clearer that ForkConenctors and StageConnectors are only for _replacing bits of the pipeline_, and not _extending_ it.

**Comment by timbussmann** [comment]
I'm removing the 6.1 label here as it is present on the PR which has a more suitable title for release notes.

Do we need to update something on docs (or something else) to make the current behavior clearer before closing this issue?

**Comment by weralabaj** [comment]
@timbussmann yes, could you remove that "There is currently no mechanism available to create custom pipelines and stages." note at the end and instead add a more precise info somewhere at the top of that article?

**Comment by dbelcham** [comment]
What about this at the top of the article: https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors

> There currently is no way to provide custom Pipelines, Stages, Fork Connectors, or Stage Connectors for NServiceBus. The examples below are included here for completeness.

**Comment by timbussmann** [comment]
@dbelcham can you open a PR for that suggestion and then close this issue? 👍

**Comment by dbelcham** [comment]
Doco PR created

**Comment by SimonCropp** [comment]
i dont think doco is enough here. @distantcam was using a public API and got a null ref. that should never happen

**Comment by SimonCropp** [comment]
ignore that i see there is a custom exception
