### ISSUE TITLE
Core routing model

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4358]
Here's my proposal for the logical model of the routing:

## Routing model

Like Orges and onions, routing has layers

## Layer 0 - core - "I want this to be routed"

The layer zero cares about adding 1 or more `RoutingStrategy` object to the context when passing a message to the logical send phase. It does not depends on the semantic meaning of `Send`, `Publish` or `Reply` which are higher-level concepts. In this form the routing has no configuration. Currently this is expressed by having a replacable connector. Instead of this approach we might contemplate having a dedicated extension poing like `IRouting` which has a single method `ISomeCollection<RoutingStrategy> Route(the context)`.

## Layer 1 - core - "I want this to be routed somewhere"

Layer one has two implementations (but can have more)

 * Unicast routing which is in the core and uses routing tables (one for sends, one for publishes) to instruct the transport *to which queue* the message has to be sent. Distribution also happens here. Unicast routing itself offers extensibility points (the mentioned tables) so that higher level features (level 2) can be built on top of it.

 * Native routing which passes the message type as a key to the transport so that the transport can handle the routing itself

Layer 1 can be is aware of `Send` and `Publish` semantics and the variant of level 1 routing (unicast/native) can be configured on per "operation" basis, e.g. unicast for sends, native for publishes (like RabbitMQ)

## Layer 2 - extensions to level 1 - "I want this to be routed here and there"

Layer 2 features build on top of level 1 extensibility e.g. the one in the unicast routing

 * File-based routing sets up the routing tables based on an XML file
 * Automatic routing sets up the routing tables based on what handlers are loaded to the endpoints
 * Message-driven Pub/Sub sets up the subscriber table based on the subscription storage that is driven by subscriber messages

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers can we discuss it (in isolation from the current implementation concerns) and get aligned on the vision and the model? Implementation changes may (or may not :( ) follow

**Comment by timbussmann** [comment]
as we have concluded to stop further immediate actions on routing refactorings at the moment with a specific need/feature behind it, I'm not really sure what kind of actionable items we could get out of this.

I'm not really sure what benefits we would gain from layer 0 at the moment, assuming that layer 1 is already so extendable that it can support routing mechanisms or even native routing.

**Comment by danielmarbach** [comment]
Discussed with @SzymonPobiega today. We are closing the discussion for now.

- We don't see any actionable points to discuss right now
- We should reconsider it if we tackle routing again in a next major release
