### ISSUE TITLE
MessageType not audited for native integration messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4360]
I've done some [native integration using ASQ](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/160) and noticed that when a native message is processed the audited message type will show up as `unknown` in SI.

This is because the `NServiceBus.EnclosedMessageTypes` header is missing on the incoming message. The workaround was to add a mutator that "propagates" the message type if the header is missing to the endpoint

```
 class MessageTypeEncricher: IMutateIncomingMessages
        {
            public Task MutateIncoming(MutateIncomingMessageContext context)
            {
                if (!context.Headers.ContainsKey(Headers.EnclosedMessageTypes))
                {
                    context.Headers[Headers.EnclosedMessageTypes] = context.Message.GetType().FullName;
                }

                return Task.CompletedTask;
            }
        }

```

Question is should the core handle this better by:

1. Do the above 
2. Audit a new "message type we actually processed" header and have SC/SI look for that header first?

No.2 has the advantage of showing the actual type we processed should a mutator/behavior change the message during the incoming pipeline. But the downside is requiring sync with SI and also increased message size.

No.1 Has the downside of "lying" to SI since that header wasn't actually on the incoming message

No.1 seems like a low hanging fruit or is there some dangers with this?

**Comment by bording** [comment]
What serializer were you using when you ran into this problem? I know the XML serializer can infer the type without the header in some cases, but if you were using JSON, wouldn't you have a serialization error if the `NServiceBus.EnclosedMessageTypes` header doesn't have a value? Deserialization happens before the mutators run, so it seems like this would only be relevant for XML serialization.

Does this make sense to do if it only benefits a message that can be processed successfully without a value in the header?

This seems more like something the transport should be attempting to populate from a native message. For example, Rabbit attempts to populate the header with a [native value](https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessageConverter.cs#L53) when it can.

**Comment by andreasohlund** [comment]
>I know the XML serializer can infer the type without the header in some cases, but if you were using JSON, wouldn't you have a serialization error if the NServiceBus.EnclosedMessageTypes header doesn't have a value?

I use json.net and `$type` embedded in the payload

>Does this make sense to do if it only benefits a message that can be processed successfully without a value in the header?

Given that both json and xml supports this I'd say it's worth it?

>Does this make sense to do if it only benefits a message that can be processed successfully without a value in the header?

Since we do support the serializers to "figure out" the message type I'd say yes?

**Comment by andreasohlund** [comment]
After talking to @timbussmann we concluded that this is a relevant enhancement but not urgent, assigning this to the future milestone
