### ISSUE TITLE
When_timeout_storage_is_unavailable_temporarily.Endpoint_should_not_shutdown takes at least 45 seconds to execute

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4361]
https://builds.particular.net/viewLog.html?currentGroup=test&scope=NServiceBus.AcceptanceTests.dll%23teamcity%23NServiceBus.AcceptanceTests.Timeouts%23teamcity%23When_timeout_storage_is_unavailable_temporarily&pager.currentPage=1&order=DURATION_DESC&recordsPerPage=20&filterText=&status=&buildTypeId=NServiceBusCore_Build&buildId=199762&tab=testsInfo

We should make the CB interval internally configurable and then adjust that test to run in a few seconds

**Comment by andreasohlund** [comment]
PR merged, closing
