### ISSUE TITLE
Proposal for evolution of routing

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4365]
Provides an idea for implementing a model outlined in https://github.com/Particular/NServiceBus/issues/4358

### Overall direction with regards to routing (manifest-style):
 * We value native configuration-less routing over unicast configuration-less routing
 * We value unicast configuration-less routing over centralized routing
 * We value centralized routing for events over MDPS

#### Align unicast publish with unicast send

Use a routing table similar to `UnicastRoutingTable` for publishes (UnicastSubscriberTable). That table can be filled by multiple sources e.g. MDPS or centralized filed-based routing.

Quick win:

Allows easy extensibility for unicast routing which will still be used for MSMQ in the foreseeable future. MDPS can coexist with centralized routing, making the transition to centralized routing easier. An example for centralized routing (https://github.com/ParticularLabs/NServiceBus.FileBasedRouting/pull/6) shows how part of the MSMQ solution could already benefit from centralized routing while the other part still uses MDPS.

#### Allow using unicast and native routing for a single message 

If the transport supports both unicast and multicast, opt-in to use both:
 * When sending, try unicast and fall back to native when there is no unciast route
 * When publishing, use both and create 1 `MulticastRoutingStrategy` and 0..n `UnicastRoutingStrategies`

As mentioned, the dual mode would be opt-in and enabled via the transport (transport would pass `Both` as supported command/event routing modes) only for the compatibility scenarios. In the dual mode the handling of `Subscribe`/`Unsubscribe` would be taken over by the transport native support and the unicast part would have to resort to explicitly configured subscribing. This would pave the way for removing `IMessageSession.(Un)Subscribe` in V7.

Quick win:

MDPS can coexist with native pub sub, making the transition to native pub-sub easier (SQL Server, ASQ). It would also make it easy to transition to full native routing e.g. for RabbitMQ.

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers please consider this idea for the 6.2 release. If you think it should be escalated to PlatDev, let me know. The code changes won't touch anything besides the core.

**Comment by timbussmann** [comment]
I'm not really sure how to move this forward. According to our call today, @SzymonPobiega mentioned this to be mainly a mental model. I think we came to the conclusion that for 6.2 we're not setting priorities towards changing routing code in a significant way. Is this something we can feed into docs for better understanding and documentation of our current (already existent) routing "layers", do we need to have a dedicated documentation for that somewhere (outside docs)?

**Comment by danielmarbach** [comment]
@SzymonPobiega what do you think about [@timbussmann comment](https://github.com/Particular/NServiceBus/issues/4365#issuecomment-267297339)?

**Comment by SzymonPobiega** [comment]
My initial intention was not to change the docs. Docs readers are usually not interested in models but APIs we expose. I expected some constructive discussion and challenging of both the assumptions I made and the proposed model.

**Comment by timbussmann** [comment]
After the discussion we had on https://github.com/Particular/NServiceBus/issues/4358 I think we should close this. We decided that at the moment we don't want to address the routing API without a deeper story driven by platform development.

**Comment by timbussmann** [comment]
closing this as no objections have been raised since the last comment.
