### ISSUE TITLE
Log4Net Format Error?

### ISSUE THREAD

**Issue by kevin-whalley-gc** [Particular/NServiceBus#4382]
Noticed this in my log file and having trouble distinguishing with the issue is from NServiceBus 6.x or bubbling up from my endpoint

```
2016-12-05 09:32:53,612 DEBUG NServiceBus.SerializeMessageConnector - <log4net.Error>Exception during StringFormat: Index (zero based) must be greater than or equal to zero and less than the size of the argument list. <format>Serializing message '{0}' with id '{1}', ToString() of the message yields: {2} 
</format><args>{<TypeName>, f26b33c9-3adf-486c-8252-a6d3009d597d, <Exception: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.>}
```

Seems to come from https://github.com/Particular/NServiceBus/blob/d462080b0efa6609f0f92d4e192d760142ac47c2/src/NServiceBus.Core/Pipeline/Outgoing/SerializeMessageConnector.cs#L24

**Comment by danielmarbach** [comment]
Difficult to say based on the output above. Do you have a custom `ToString` implementation on your message?

**Comment by mikeminutillo** [comment]
> Difficult to say based on the output above. Do you have a custom ToString implementation on your message?

That would make sense looking at the log4net code. When there is an error rendering a log message you get:

```xml
<log4net.Error>
  <format>...</format>
  <args>...</args>
</log4net.Error>
```

The arg list is comma separated and surrounded by braces. In the example provided you can see the ares are `<TypeName>`, `f26b33c9-3adf-486c-8252-a6d3009d597d`, and the exception. The exception is being thrown from the call to `context.Message.Instance` which is just an `object`. 

The corresponding log4net code that builds the exception is [called here](https://github.com/apache/log4net/blob/fa13c71e628fd0a59880ecb50e79dc0d5724fa39/src/Util/SystemStringFormat.cs#L110).

**Comment by SimonCropp** [comment]
@kevin-whalley-gc could you share you log4net config. or better yet upload a repro somewhere

**Comment by mikeminutillo** [comment]
@kevin-whalley-gc did you manage to get this resolved?

**Comment by kevin-whalley-gc** [comment]
Thanks everyone, I sat down fresh this morning and found the issue in a custom ToString as @danielmarbach caught
