### ISSUE TITLE
Determine how to manage dependencies within Core

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus#4389]
## Ideas
- what should features do and not do
  - should only be used for things that can be enabled and disabled without breaking Core execution
  - should not depend on each other. If they do it is an indicator that the feature should expose its own extensibility API
  - many Core capabilities currently are features but probably shouldn't be because they cannot be turned off without making Core un-runnable
- many implicit dependencies are not expressed in the code
  - these work because we use a DI container to express dependencies and those are resolved at a later time once setup is completed
  - since we want to get rid of the DI container this ^ is something we want to find a different approach for
  - we use Settings as a poor man's DI container where objects are registered and then accessed from anywhere within in the codebase
- does the use of Settings like ^ a problem from a SemVer standpoint where exposure of the API is obfuscated and difficult to version?

## Outcomes
- establish better guidelines of what are features (and what aren't), how they should behave and what should a feature "do"
- for those things not determined to be features, find actionable steps to move them off of the Feature API
- find a way to avoid dependency management via DI container and Settings

@Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
Not sure the Settings approach is so bad. I definitely think we should try to avoid it. But as a fallback I think it is a viable solution. As long as we make sure we follow the other practices outlined here we probably mostly don't need the settings.

**Comment by timbussmann** [comment]
managing dependencies from other issues or components via settings is currently quite risky as you need to ensure order of execution somehow. The only way to do that reliably is using `DependsOn`. Exposing APIs via settings also makes it very difficult to obsolete them.

**Comment by danielmarbach** [comment]
As a first step we decided to implement https://github.com/Particular/NServiceBus/pull/4305 as an internal redesign which moves as one step closer to the DI-less vision. Closing this
