### ISSUE TITLE
InMemoryTimeoutPersister tests

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4391]
Is this test correct?
It's setting now to [`DateTime.UtcNow`](https://github.com/Particular/NServiceBus/blob/a8ce619c90b506aa757b122c8ef24f022d1db90c/src/NServiceBus.Core.Tests/Timeout/InMemoryTimeoutPersisterTests.cs#L25) time, but the actual timeouts to [`DateTime.Now`](https://github.com/Particular/NServiceBus/blob/a8ce619c90b506aa757b122c8ef24f022d1db90c/src/NServiceBus.Core.Tests/Timeout/InMemoryTimeoutPersisterTests.cs#L29)

**Comment by SeanFeldman** [comment]
@Particular/nservicebus-maintainers please confirm if this is right? This test was failing for me when executed locally (MST, UTC-7)

**Comment by bording** [comment]
@SeanFeldman Can you link to one of the tests in question?

**Comment by SeanFeldman** [comment]
@bording the links in the general description are pointing to that test (`When_multiple_NextTimeToRunQuery_is_min_date`)

**Comment by bording** [comment]
Ah yes, for some reason I didn't see those, sorry!

**Comment by bording** [comment]
Looking at that, I'd say it's a mistake.

**Comment by danielmarbach** [comment]
Definitely a mistake. Would you have time to send in a PR @SeanFeldman ?

**Comment by SeanFeldman** [comment]
Will do
