### ISSUE TITLE
Write transport test to test isolated dispatches

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4392]
Based on #4270 we would like to have a new transport test similar to `When_failure_happens_after_send` but testing that when using Isolated dispatch mode, the message is immediately dispatched and will be received even when the handling fails after the "immediate" dispatch.

Note: Smoke test this change on downstreams (e.g. ASB, Rabbit, ...) before merging it.

**Comment by dbelcham** [comment]
Resolved by #4400
