### ISSUE TITLE
Problem with InMemory saga persister and mulitple handler invocation

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#4393]
The `When_using_a_received_message_for_timeout.Timeout_should_be_received_after_expiration` test seems to be demonstrating this problem, though when run on MSMQ, the test is falsely passing.

Take a look at https://github.com/Particular/NServiceBus.RabbitMQ/pull/316#issuecomment-267187699 to see the results of my investigation so far.

I haven't tried it yet, but I assume the same problem could show up if a message had more than one handler, and not just a handler/timeout mix like the test.

There seems to be something we need to do here, but I'm not sure exactly what that is yet.

**Comment by andreasohlund** [comment]
I can now repro the issue, see
https://github.com/Particular/NServiceBus/pull/4394
https://github.com/Particular/NServiceBus/issues/4074#issuecomment-267259813

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/issues/4397
