### ISSUE TITLE
No AcceptanceTest time limits when debugger attached

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#4402]
When trying to debug an acceptance test, it's difficult to take your time, otherwise the test framework will throw that the Given/Whens took longer than 60 seconds.

It would be really nice to have this (and any similar real-time) check skipped if there's a debugger attached.

**Comment by Scooletz** [comment]
😍 This moment when you see a simple and elegant solution to the pain you've been experiencing a lot.

**Comment by danielmarbach** [comment]
we think this provides good value for the little effort. Assigned to @dbelcham

**Comment by timbussmann** [comment]
reopening this (see https://github.com/Particular/NServiceBus/pull/4435#issuecomment-274496446). @dbelcham please feel free to close again if I missed something.

**Comment by dbelcham** [comment]
@timbussmann looking at the code for `ExecutesWhen` I see that there are also timeouts on `StartEndpoints` and `StopEndpoints`. Should we implement this across all of those?

**Comment by danielmarbach** [comment]
@dbelcham you could directly code it into the timeout extension method and then it is addressed

**Comment by danielmarbach** [comment]
@dbelcham ping me for a further discussion on this. I think we have another issue how we treat cancellation in the framework

**Comment by timbussmann** [comment]
> looking at the code for ExecutesWhen I see that there are also timeouts on StartEndpoints and StopEndpoints. Should we implement this across all of those?

I think at that point ExecuteWhens are the biggest pain point. I don't think we need to explicitly change Start/Stop (in case the also behave the same as ExecuteWhen because of shared code, I don't see an issue with that though).

**Comment by timbussmann** [comment]
closing this again as everything should be addressed with #4439 now 👍
