### ISSUE TITLE
PurgeOnStartup does not write any log event that it is performing a purge operation

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4410]
When calling `.PurgeOnStartup(true)` no log entry is written that a purge operation will be performed. This is tested with V5 and MSMQ.

I propose to write a log entry with log level WARN to indicate this potentially destructive operation at the following location:

- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/StartableEndpoint.cs#L102

**Comment by danielmarbach** [comment]
Assigned to @dbelcham since it is a good improvement

**Comment by danielmarbach** [comment]
Addressed in https://github.com/Particular/NServiceBus/pull/4412. Closing
