### ISSUE TITLE
NServiceBus should write a DEBUG log entry when receiving a message

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4411]
When setting the log level to DEBUG there is not a single log entry when a message is processed in both V5 and V6 when using MSMQ.

I expect that when log level is set to DEBUG that we log an entry similar to the following:

> DEBUG Processing message with transport ID `b644ac05-920c-42ba-ba3f-4d4777ae7afe\405413770` and message ID `24cb9a2d-7131-43d1-bb7d-a6e2014db3f8`

There are alternatives:

- Looking at the performance counters but that requires that these have been enabled
- Have auditing enabled but that requires ServiceControl to be stopped so that it will not immediately ingest messages but as the audit queue received messages from multiple instance this is not very useful
- Enable journaling on the endpoint instance queue and refresh to check if there is activity
- Open ServiceInsight and look at recent processed messages but that requires auditing to be enabled

It would really be very helpful to see such a log entry.

**Comment by danielmarbach** [comment]
Not opposed to this idea as long as we can safely say it doesn't unnecessarily influence the performance in a bad way. Should we check that first?

**Comment by ramonsmits** [comment]
@danielmarbach The log line can be JIT optimized like:

    static bool readonly IsDebugEnabled = Log.IsDebugEnabled:
    
    if(IsDebugEnabled) Log.DebugFormat("DEBUG Processing message with transport ID {0} and message ID {1}", transportId, headerId);

That should result in no performance impact if any log level is configured higher than DEBUG.

**Comment by danielmarbach** [comment]
@ramonsmits good suggestion.

**Comment by timbussmann** [comment]
this should be covered by https://github.com/Particular/NServiceBus/issues/5179 which is going to be added to 7.1. I'm going to close this issue therefore. @ramonsmits feel free to reopen if you think there is more to address.
