### ISSUE TITLE
Possible dispose issue for ExpiredTimeoutsPoller

### ISSUE THREAD

**Issue by CraigN** [Particular/NServiceBus#4415]
I've been attempting to get our application to shutdown cleanly and dispose of all objects properly. In testing I've found a rather annoying issue where calling IEndpointInstance.Stop() appears to call ExpiredTimeoutsPoller.Dispose() however it never seems to call ExpiredTimeoutsPoller.Stop()and can result in a nasty exception as follows:

> System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
>    at System.Threading.Tasks.Task.Dispose(Boolean disposing)
>    at System.Threading.Tasks.Task.Dispose()
>    at NServiceBus.ExpiredTimeoutsPoller.Dispose() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\SatellitePipelineExecutor.cs:line 0
>    at Autofac.Core.Disposer.Dispose(Boolean disposing)
>    at Autofac.Util.Disposable.Dispose()
>    at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
>    at Autofac.Util.Disposable.Dispose()

I think ExpiredTimeoutsPoller.Stop() should be called and the task awaited in ExpiredTimeoutsPoller.Dispose() as it terminates the running task through a CancellationToken.

Tested against NServiceBus 6.0.0 and 6.1.1.

**Comment by SzymonPobiega** [comment]
@CraigN can you provide more logs? It seems like the root cause is somewhere else because in a "happy" path the `ExpiredTimeoutsPoller` is stopped by `TimeoutPollerRunner` which is a feature startup task that is stopped before the container is disposed (which disposes the poller).

**Comment by danielmarbach** [comment]
@CraigN It seems that the task owned by the `ExpiredTimeoutsPoller` is getting disposed before the task is completed. Could it be that you dispose the container before you stop the endpoint? Like @SzymonPobiega mentioned it would be helpful if you can provide some logs. If you don't want to add it to this issue feel free to send me an email to daniel dot marbach at particular dot net

**Comment by timbussmann** [comment]
Hey @CraigN 
As @danielmarbach described, we identified a potential cause for the exception you're seeing caused by an invalid disposal of a task. We eliminated this potential issue but haven't been able to reproduce the exception with a real endpoint so far. These changes will be rolled out as a part of 6.2. Since we haven't heard back from you for a while, we're closing the issue as we assume this can't happen with 6.2 once it's released. 

Thanks for raising this issue!

**Comment by CraigN** [comment]
Thanks Tim. Unfortunately I couldn't spend much more time trying to put a test case together that reproduced it. Any idea when 6.2 will be released?

**Comment by timbussmann** [comment]
Unfortunately I can't tell you a targeted release date yet. However, I pushed an unstable version (current state of the develop branch which will become 6.2) to our myget feed, so if you're interested to test whether the issue remains or would be solved with 6.2, you can test it using this package: https://www.myget.org/F/particular/api/v2/package/NServiceBus/6.2.0-alpha0159. Please let us know if that works for you.
