### ISSUE TITLE
Immediate retries counter not incremented for exceptions during commit/dispose

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4419]
### Who's affected

All Version 6 MSMQ users running in transaction mode `ReceiveOnly` or higher that has recoverability policy that includes immediate retries.

### Symptoms

The `ImmediateProcessingFailures` counter on the error context is never incremented above 1 causing the endpoint to go into a infinite loop trying to reprocess the message. This only happens for exceptions thrown after the processing pipeline has completed. Examples are problems during prepare/commit/dispose when using transaction scopes.

### Criticality

Since messages will not be properly retried/move to the error queue but instead get stuck in an infinite retry loop this is deemed as a critical patch since this will cause messages further down on the queue to not be processed timely. During this failure condition the cpu churns at 100% and the disk will fill up since messages are not moved to the error queue.

**Comment by bording** [comment]
Fixed by #4417
