### ISSUE TITLE
Register IEndpointInstance with Autofac container following Autofac 4.2.1 release

### ISSUE THREAD

**Issue by scrooby** [Particular/NServiceBus#4421]
I'm looking for some guidance on the recommended way to register an IEndpointInstance with an Autofac container following the release of Autofac 4.2.1 where `ContainerBuilder.Update` has been marked as obsolete.

The reason I need to register `IEndpointInstance` is because I have a C# console application, using TopShelf, which needs to handle incoming messages, as well as sending messages outside the message handlers.

Previously, I would use `ContainerBuilder.Update` to update my container with the registered `IEndpointInstance` like so:

```
var containerBuilder = new ContainerBuilder();
...
var container = containerBuilder.Build();

var endpointConfiguration = new EndpointConfiguration(HostConstants.ServiceName);
...
endpointConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(container));

var endpointInstance = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();

var updateBuilder = new ContainerBuilder();
updateBuilder.RegisterInstance(endpointInstance);
updateBuilder.Update(container);
```

My work around so far has been based on this SO answer: http://stackoverflow.com/questions/41188183/nsevicebus-6-how-to-inject-imessagesession-using-autofac-into-a-net-web-api-c

```
public class ServiceHost : IServiceHost
{
    private static IEndpointInstance endpointInstance;

    public bool Start(HostControl topshelfHostControl)
    {
        var containerBuilder = new ContainerBuilder();
		
	containerBuilder.Register(c => CreateEndpointInstance(c.Resolve<ILifetimeScope>()))
	    .As<IEndpointInstance>().SingleInstance();
		
	var container = containerBuilder.Build();

	endpointInstance = container.Resolve<IEndpointInstance>();

	return true;
    }

    public bool Stop()
    {
	endpointInstance.Stop().GetAwaiter().GetResult();
	return true;
    }

    private IEndpointInstance CreateEndpointInstance(ILifetimeScope lifetimeScopeContainer)
    {
	var endpointConfiguration = new EndpointConfiguration(HostConstants.ServiceName);	

	...

	endpointConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(lifetimeScopeContainer));
		
	endpointConfiguration.Notifications.Errors.MessageSentToErrorQueue += OnMessageSentToErrorQueue;
		
	return Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();
    }

    private void OnMessageSentToErrorQueue(object sender, FailedMessage failedMessage)
    {
	var failedMessageResponder = Container.Resolve<IFailedMessageResponder>();
	failedMessageResponder.HandleFailedMessage(sender, failedMessage);
    }
}

public class FailedMessageResponder : IFailedMessageResponder
{
    private readonly IEndpointInstance endpointInstance;

    public FailedMessageResponder(IEndpointInstance endpointInstance)
    {
        this.endpointInstance = endpointInstance;
    }

    public void HandleFailedMessage(object sender, FailedMessage failedMessage)
    {
        ...
        endpointInstance.Publish(failedMessageEvent);
    }
}
```

By resolving the IEndpointInstance out of the container in the `Start` method, the `CreateEndpointInstance` function is executed, starting the endpoint. I then store a reference to the `IEndpointInstance` locally so I can stop it when the TopShelf application is stopped, or an error occurs etc.

This approach appears to work, but essentially getting the container to start the endpoint doesn't feel like a nice solution. Is there an alternative recommended approach, or is this a good way to go?

**Comment by danielmarbach** [comment]
Ping @particular/container-maintainers

**Comment by WilliamBZA** [comment]
Thanks @scrooby 

We're aware of the obsoleted method and will be changing the NServiceBus container adapter so that it will no longer be an issue. For now though - and I fully realise it's painful - you can safely ignore the obsolete warning and carry on as usual.

Unfortunately we currently require the ability to update a container after it has been built. We know we can do better here and are moving towards a better approach to dependency injection, so for now it's ok to just disable the warning.

**Comment by scrooby** [comment]
Thanks for the info @WilliamBZA, it's good to know something's in the pipeline to accommodate the change.

For now we might just stick with the lamda work around, since it appears to be working (unless you saw any issues with that approach...), then update once your changes have been released.

Thanks!

**Comment by WilliamBZA** [comment]
I've created a separate issue for this in the autofac adapter repository.

https://github.com/Particular/NServiceBus.Autofac/issues/36

I'll close this one and we can track the progress on the new issue.
