### ISSUE TITLE
Do not force persistence to be configured if not required

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4422]
For users on transport that have native pubsub and timeouts there is no persistence needed if no sagas are used. Still we prevent this by throwing [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/PersistenceStartup.cs#L22).

I think we should let each feature that needs persistence to check when they initialize instead. This also aligns with a future persistence api that is "per feature" eg.

* `.UseTransport<MSMQ>().SubscriptionPersistence<NHibernate>()`
* `.UseTransport<MSMQ>().TimeoutPersistence<NHibernate>()`
* `.Gateway().DeduplicationStorage<InMemory>()`
* `.Sagas().Storage<SqlPersistence>()`

**Comment by timbussmann** [comment]
👍 
how often do users run without any persistence requirements? Are you good with adding this to the future milestone?

**Comment by timbussmann** [comment]
just saw the linked issue. Seems this would have a higher priority for ASB transports?

**Comment by SeanFeldman** [comment]
@timbussmann azure transports, correct, but also any other transport that doesn't require those features.

**Comment by andreasohlund** [comment]
Given that there is native timeouts in the works for rabbit it would soon be added to the list as well

**Comment by timbussmann** [comment]
sounds like something for the next minor then?

**Comment by timbussmann** [comment]
@andreasohlund any doco changes required?

**Comment by andreasohlund** [comment]
I went through docs and I couldn't find anything that needs change. And since we arguable give better error messages now I'd say we're good as is?
