### ISSUE TITLE
Timeouts are skipped on transport exceptions

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4436]
### Who's affected:

All endpoints using the `TimeoutManager`. The `TimeoutManager` is required for delayed sends, delayed retries and saga timeouts on transports without native delayed deliver mechanism.

### Symptoms

Timeouts may arrive later than they were scheduled after transport related exceptions.

### Cause

This has been identified by @SzymonPobiega. This is from the current `ExpiredTimeoutsPoller` implementation which does read timeouts from the persistence:

            var timeoutChunk = await timeoutsFetcher.GetNextChunk(startSlice).ConfigureAwait(false);

            foreach (var timeoutData in timeoutChunk.DueTimeouts)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    return;
                }

                if (startSlice < timeoutData.DueTime)
                {
                    startSlice = timeoutData.DueTime;
                }

                var dispatchRequest = ControlMessageFactory.Create(MessageIntentEnum.Send);

                dispatchRequest.Headers["Timeout.Id"] = timeoutData.Id;

                var transportOperation = new TransportOperation(dispatchRequest, new UnicastAddressTag(dispatcherAddress));
                await dispatcher.Dispatch(new TransportOperations(transportOperation), new TransportTransaction(), new ContextBag()).ConfigureAwait(false);
            }

If something during `dispatcher.Dispatch` fails (e.g. all sorts of transport issues), the `startSlice` has already been moved to the latest timeouts due time. When the timeout poller queries the storage again, but now starting at the updated `startSlice` causing the previously failed messages to not be sent again.

This should not cause timeouts to disappear completely with NH and Raven Persistence as they already query for older leftover timeouts from time to time, but it might be an issue with other implementations.

A solution might be to move down the assignment to `startSlice` after the dispatch operation.
Regardless of the fix, this seems to be dependent on the timeout enumerable to return the timeouts in order of the due date, do we I did not check whether we verify this by some tests.

issue reported by @janpieterz in https://github.com/Particular/NServiceBus/issues/4431

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers Not sure whether we need to treat this as critical because of the raven and nh workarounds they already use, but aside from them, it seems to be something we should definitely address? thoughts?

**Comment by bording** [comment]
@timbussmann Once we know if v5 is also impacted, then I think that gives a better feel for how large of a problem it might be.

**Comment by timbussmann** [comment]
this is the code used in v5, so I think it's safe to assume that v5 works the same way:

                var timeoutDatas = TimeoutsPersister.GetNextChunk(startSlice, out nextExpiredTimeout);

                foreach (var timeoutData in timeoutDatas)
                {
                    if (startSlice < timeoutData.Item2)
                    {
                        startSlice = timeoutData.Item2;
                    }

                    MessageSender.Send(CreateTransportMessage(timeoutData.Item1), new SendOptions(DispatcherAddress));
                }

**Comment by timbussmann** [comment]
one issue we discussed on a call, is that our storages shouldn't be affected in a critical way since they all implement the "catch up mechanism" to fetch older timeouts from time to time. A quick look at community owned persistence showed that none of them make us of such a mechanism which makes them vulnerable to this issue.

**Comment by SzymonPobiega** [comment]
@timbussmann NH is not fixed in all the latest minors. I am pretty sure SQL Persistence does not have this "safety" feature cc @SimonCropp

**Comment by timbussmann** [comment]
> NH is not fixed in all the latest minors

shouldn't this be fixed for supported versions?

>  I am pretty sure SQL Persistence does not have this "safety" feature

yeah, as said, I think none of the community projects do that. Also, InMemoryPersistence doesn't either.

**Comment by SzymonPobiega** [comment]
@timbussmann I don't think this problem is considered a critical. We backported to the most probably used versions.

**Comment by timbussmann** [comment]
@SzymonPobiega on endpoints with a persistence without catch-up mechanism, this could lead to delay of timeouts until the next endpoint restart. While I'm good with not considering a delay of a few minutes as critical, a delay till a restart is close to message loss (or message loss in the case of inmem).

**Comment by SzymonPobiega** [comment]
6.1.0 (which we don't backport to) has been released on Mar 2, 2015 so I think we are covered.
