### ISSUE TITLE
Spike native delayed delivery for MSMQ

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4443]
@SzymonPobiega [found a potential solution / hidden MSMQ feature](https://github.com/Particular/NServiceBus/issues/4223#issuecomment-272166132) which could allow us to do native delayed delivery and avoiding the TimeoutManager.

## Original Comment from Szymon on #4223 describing the solution

It turns out WCF has always had a way to specify a custom dead letter queue, per contract. It turned out (via dotPeek) that this is done on a per-message level in MSMQ, via property number 67/68:

```
message.TimeToBeReceived = TimeSpan.FromDays(1000);
setUI1.Invoke(newProps, new object[] { 7, (byte)1 }); //Enable dead letter
var buffer = StringToBytes(deadLetter);
setString.Invoke(newProps, new object[] { 67, buffer });
setUI4.Invoke(newProps, new object[] { 68, deadLetter.Length });
queue.Send(message, MessageQueueTransactionType.Single);
```

We the message sent in the way above will come back to the dead letter queue in 1000 days (I verified that for lower values obviously). The only limitation is, the dead letter queue has to be local so you can't have a centralized one (out of the box). That said, we can easily create an endpoint whose only purpose would be receiving messages and putting them in a local centralized timeout queue to wait for their due date.

## PoA
* [ ] Verify this approach works reliably for NSB users using MSMQ transport
* [ ] Identify limitations
* [ ] Identify migration scenarios
* [ ] Assess potential risks (e.g. relying on undocumented features)
* [ ] Decide for go / nogo

**Comment by SzymonPobiega** [comment]
One this. this feature is documented (e.g. [here](https://msdn.microsoft.com/en-us/library/aa368234(v=vs.85).aspx)). It is not exposed via `System.Messaging` abstraction.

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/8.
