### ISSUE TITLE
Breaking change in behavior between core v5 and v6 for delayed delivery

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4445]
When timeout manager is used for delayed delivery, two possible constraints that are not mutually exclusive are used to decide on delay: `DelayDeliveryWith` and `DoNotDeliverBefore` (`DeliverAt` in v5).

Behavior prescribes that one value takes precedence over another. V5 and V6 are not consistent though

## V5 behavior 

`DelayDeliveryWith` takes precedence over `DeliverAt` ([source code](https://github.com/Particular/NServiceBus/blob/530706d3189a948a9dd55df65e3f073c775ecda6/src/NServiceBus.Core/Timeout/Core/TimeoutManagerDeferrer.cs#L21))

## V6 behavior 

`DoNotDeliverBefore` takes precedence over `DelayDeliveryWith` ([source code](https://github.com/Particular/NServiceBus/blob/6c8485d84240e33485b098ead7e9b2546267e4ba/src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs#L58))

## Issues

1. This is a breaking behavior that is not documented
1. Transports implementing native delays do not have a clear API guidance which order to use (for example, ASB stayed loyal to v5 version)
1. Should `DelayDeliveryWith` and `DoNotDeliverBefore` sending options be even allowed on the same sending operation to begin with?

**Comment by andreasohlund** [comment]
I'd say it shouldn't be supported to mix and we should throw?

Out of curiosity how did you find this issue?

**Comment by SeanFeldman** [comment]
@andreasohlund correct, we should throw if those two are mixed.

For $50 I'll let you know how it was discovered

**Comment by SeanFeldman** [comment]
Ok, ok. @bording and myself were pairing on native delays for RabbitMQ and noticed the difference between timeout manager implementation and native implementation (ASB). When compared core v5 and v6, found the difference. Also, the fact that a transport with native delays doesn't have a clear API and has to choose one over another is a smell on its own. 

BTW, you still owe $50 😛

**Comment by timbussmann** [comment]
I agree with @andreasohlund. Let's raise an issue to throw in case both options are specified and close this?

**Comment by SeanFeldman** [comment]
👍

**Comment by bording** [comment]
Before deciding how to handle this in V6, I think we need to know more about how this worked in V5. Can you even have both of the options set in V5?

If we do decide to start throwing in V6, what sort of release can we make this change, seeing how this would be a behavior change?

**Comment by timbussmann** [comment]
@danielmarbach you are assigned to this, but it doesn't look like there is anything going on regarding this. Should we remove you from the assignees? To me it sounds like the best approach would indeed be to throw in case both options are used.

**Comment by danielmarbach** [comment]
@timbussmann I think I remember the idea was that I talk to @SeanFeldman but to be honest I can't say if I did it. Agree probably throwing would be best. Let's scheduled for 6.3? Not urgent enough to pull into 6.2?

**Comment by SeanFeldman** [comment]
@danielmarbach we didn't talke about it. Regardless, 👍 to throw when both options are used.

**Comment by danielmarbach** [comment]
Assigned to 6.3. We will throw an exception in the future. Action item defined in https://github.com/Particular/NServiceBus/issues/4541. Closing
