### ISSUE TITLE
AllAssemblies obsolete now use ExcludeAssemblies

### ISSUE THREAD

**Issue by gmonos** [Particular/NServiceBus#4446]
Hello, i'm new to NServiceBus,
But i got a question regarding the suppression of AllAssemblies that i found very usefull.

now we have to use ExcludeAssemblies, but how can we do with more than 200 dll to exclude ? is there a pattern you implemented to don't have to explicitly name each of the 200 dll ?

thanks.

**Comment by danielmarbach** [comment]
Hi,

I would use reflection like

        var codebase = typeof(YourEndpoint).Assembly.CodeBase.Remove(0, 8);
        var currentDirectory = Path.GetDirectoryName(codebase);
        assemblies = Directory.GetFiles(currentDirectory, "*.dll")
            .Select(Assembly.LoadFrom)
            .Where(a => ShouldBeExcluded)
            .ToList();

and then pass that in exclude assemblies

**Comment by andreasohlund** [comment]
What are the reasons that you need to exclude those assemblies?

**Comment by gmonos** [comment]
because it take so much time to load each assemblies, something like 2min, and i know exactly which assemblies has to be loaded.

i'm just curious why are you deleting this interesting fonctionnality

**Comment by andreasohlund** [comment]
>because it take so much time to load each assemblies, something like 2min, and i know exactly which assemblies has to be loaded.

Got it, have you timed this with v6? (we did some major improvements to our scanner that should now be much smarter when it comes to skip assemblies)

**Comment by timbussmann** [comment]
hey @gmonos , did you have any chance to test whether v6 also takes this long to load your assemblies?

**Comment by andreasohlund** [comment]
@gmonos I assume the workaround provided by Daniel worked so I'm closing this. Feel free to just re-open this issue if needed
