### ISSUE TITLE
RouteToThisEndpoint bypasses Sender Side Distribution

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4473]
While investigating how we can make timeouts on Sagas partition affine for Service Fabric I found out that RouteToThisEndpoint bypasses Sender Side Distribution. I confirmed this with @timbussmann (thanks for the help by the way).

```
        protected Task RequestTimeout<TTimeoutMessageType>(IMessageHandlerContext context, TimeSpan within, TTimeoutMessageType timeoutMessage)
        {
            VerifySagaCanHandleTimeout(timeoutMessage);

            var sendOptions = new SendOptions();

            sendOptions.DelayDeliveryWith(within);
            sendOptions.RouteToThisEndpoint();

            SetTimeoutHeaders(sendOptions);

            return context.Send(timeoutMessage, sendOptions);
        }
```

`RouteToThisEndpoint is treated as if it would be a physical route and directly creates a UnicastRoutingStrategy with the shared queue as a destination. In my opinion this is a bug. I would expect that Sender Side Distribution is applied.

In combination with #2445 we can make sure that even timeouts always comply to the partition affine routing rules. This would also enable the same for deferred messages.

I'll raise a PR with a failing test soon

**Comment by SzymonPobiega** [comment]
@danielmarbach I think that fixing this would require splitting the physical and logical routing stages so that other parts of the core can fork to the physical routing stage and take advantage of SSD.

**Comment by danielmarbach** [comment]
@SzymonPobiega Right now from the perspective of ServiceFabric it is not needed what you propose. On the fence about extending the scope

**Comment by SzymonPobiega** [comment]
@danielmarbach well, given NSB is an OSS project the core maintainers would have to consider a PR is I created it in the evening, right? ;-)

**Comment by timbussmann** [comment]
>  I think that fixing this would require splitting the physical and logical routing stages so that other parts of the core can fork to the physical routing stage and take advantage of SSD.

I like the idea of having clearer stages for routing but for the fix I think this is not something we should introduce easily in a minor. While I think the separation makes sense, I'm not sure whether it provides the value you think for users to fork into the pyhsical/logical routing stage directly. E.g. consider everything happening before or after these stages, what if you just want to influence routing but not shortcut pipeline stages?

**Comment by SzymonPobiega** [comment]
@timbussmann I don't think there is value for the end-user. I think it would be the most clean implementation should we decide to implement @danielmarbach 's idea of using SSD for the local endpoint.

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus/issues/4474 is merged. Closing
