### ISSUE TITLE
Mutator registration API

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4478]
Mutators are not registered automatically and in order to the register them, you have to use the container API (see https://docs.particular.net/nservicebus/pipeline/message-mutators#registering-a-mutator) to do so which is:
* Painful to use
* Hard to version / evolve
* Something we want to remove because of the container dependency

Instead there should be a dedicated API which makes it easy to register mutators and also makes clear at what configuration levels mutators can be registered.

Based on the issue here: https://github.com/Particular/NServiceBus/issues/4463 we're in favor of an API which does not allow mutator registration from feature setups because of the following arguments:
* Mutators are a high level abstraction API designed for direct usage by users, custom features which require mutators should instead rely on behaviors and not take a dependency on the mutator API.
* As we consider mutators as an "optional" feature, other features should not rely on mutators being enabled and usable.

**Comment by bording** [comment]
Whatever we do with this should also apply to the Unit of Work, because it has the same set of problems: 

https://docs.particular.net/nservicebus/pipeline/unit-of-work#implementing-custom-units-of-work-registering-a-unit-of-work

**Comment by timbussmann** [comment]
@bording 👍 but should we raise a dedicated issue?

**Comment by bording** [comment]
@timbussmann I was thinking that it made sense to consider them together, but I suppose they could be tracked separately.

**Comment by andreasohlund** [comment]
Talked to @timbussmann and we propose just removing the mutator api and go with a stage instead

https://github.com/Particular/NServiceBus/issues/4493

In short: that issue should cover the UoW parts of this issue?

**Comment by danielmarbach** [comment]
Should we also revise the decision around connectors? Because every connector is not extendable basically

**Comment by andreasohlund** [comment]
You mean to say that they are no longer replacable and make them private?

**Comment by timbussmann** [comment]
introduced the new API in #4497 , closing this.
