### ISSUE TITLE
Should we consider any Saga API changes wrt current/future persistence needs?

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#4501]
For persisters to work with an MSBuild model (like native SQL persister), the correlation property has to be known at compile time, rendering ConfigureHowToFindSaga pretty useless.

The native SQL persister solves this with a custom attribute that essentially double-specifies the correlation id. (Or more often considering multiple message types already specify the property multiple times.)

```
[SqlSaga(correlationProperty: nameof(SagaData.OrderId))]
public class OrderSaga : Saga<OrderSaga.SagaData>,
    IAmStartedByMessages<StartOrder>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<SagaData> mapper)
    {
        mapper.ConfigureMapping<StartOrder>(order => order.OrderId).ToSaga(data => data.OrderId);
    }
}
```

Or you can use a base class, unique to the persister, that simplifies this somewhat, so you don't have to 

```
[SqlSaga(correlationProperty: nameof(SagaData.OrderId))]
public class OrderSaga : SqlSaga<OrderSaga.SagaData>,
    IAmStartedByMessages<StartOrder>
{
    protected override void ConfigureMapping(MessagePropertyMapper<SagaData> mapper)
    {
        mapper.MapMessage<StartOrder>(message => message.OrderId);
    }
}
```

Is it possible to take any steps in a 6.x timeframe, with additive-only APIs, that could streamline this for the native SQL persister and open the door to other MSBuild-based persisters without causing a proliferation of duplicate APIs like above?

**Comment by bording** [comment]
In those examples I see that the `SqlSaga` attribute is specifying just the SagaData property, but what if it was an attribute that allowed you to specify both sides of the mapping?

I could potentially see having a mapping attribute replace the need to implement `ConfigureHowToFindSaga`. Core could look at the attribute values instead.

However, `ConfigureHowToFindSaga` is abstract, so you have to implement it anyway, so it would be odd to have an empty method + attributes.

**Comment by danielmarbach** [comment]
I was looking briefly into SqlPersistence and opened this https://github.com/Particular/NServiceBus.Persistence.Sql/issues/40
@DavidBoike based on my limited knowledge SqlPersistence should be able to get the property by inspecting the method body.

**Comment by DavidBoike** [comment]
@danielmarbach I like the idea of https://github.com/Particular/NServiceBus.Persistence.Sql/issues/40, which would solve most of the coupling issues without forcing any API changes in the Core.

Eventually, I think the Core will need to evolve to support an ecosystem of MSBuild-based installers, but it would probably be more responsible to make those decisions in a more holistic way once we know all the parameters.

I would be comfortable closing this discussion on that note if you are.
