### ISSUE TITLE
Switch TimeToBeReceivedOnForwardedMessages log warning to error.

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4508]
As the configurationsection will likely be removed completely without obsoletion attributes in v7 (as not supported by .net core), the idea was to increase the log severity with 6.3 to error in order to increase the likelihood of users noticing the log entry.

**Comment by danielmarbach** [comment]
Can we track that somehow so that we don't forget?

Tim Bussmann <notifications@github.com> schrieb am Mo. 27. Feb. 2017 um
12:29:

**Comment by WilliamBZA** [comment]
Milestone?

**Comment by danielmarbach** [comment]
@williambza yeah that is what we usually do. Was a hidden hint to create the milestone ;)

**Comment by timbussmann** [comment]
weird, I was pretty sure I added the milestone when I created the issue. Thanks @WilliamBZA

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers any reason not to extend the scope of this issue to all configuration section warnings (see also https://github.com/Particular/NServiceBus/pull/4644#issuecomment-298369537)?

**Comment by timbussmann** [comment]
closing this as #4644 has been merged and will be included in 6.3
