### ISSUE TITLE
MSMQ: Using non transactional endpoints that are setup to also use non-transactional queues will not forward error messages or audit messages properly

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4516]
Currently, it is possible to have a MSMQ non-transactional endpoint and also use a non-transactional queue. It is configured via the connection string to specify this in the "useTransactionalQueue" attribute. 

```c#
 endpointConfiguration.UseTransport<MsmqTransport>()
.ConnectionString("cacheSendConnection=true;journal=false;deadLetter=true;useTransactionalQueues=false")
.Transactions(TransportTransactionMode.None);
```

However, this can cause some silent issues when messages from these endpoints needs to be forwarded to a centralized error queue or audit queue that are created as transactional queues. The audit and error queues will be transactional when created by ServiceControl. Our recommendation is to always centralize the audit and the error queue. In a system, there will be a mix of endpoints which support transactional and non-transactional, the `useTransactionalQueues=false` configuration is asking for trouble.

The default behavior of MSMQ is that you cannot send messages from a transactional queue to a non-transactional queue and vice-versa. Attempting to do so will result in the messages in the appropriate DLQ (if DLQ is set to be true).

Therefore, by allowing users to create non-transactional queues in an easy manner, what happens is that, both error messages and audit messages from the non-transactional endpoint will not be forwarded to the centralized queues (that are transactional) and instead will end up in the non-transactional Dead Letter Queue (DLQ in the system queues).  These messages will be lost if the DLQ in the connection string is configured to be false. This is not a very friendly configuration. 

Proposal:
While we can allow the endpoint to not take part in transactions, is there any value for the queue to be non-transactional? If so, allowing the "useTransactionalQueue" to be part of a connection string, perhaps make it into a API call where the user will be warned very thoroughly that messages from this endpoint will not be delivered to the centralized error queue.
At least adequately warn users about the repercussions of creating a non-transactional queue. 

This issue relates to the discussion on the topic of DLQs in: https://github.com/Particular/docs.particular.net/pull/2437 with @andreasohlund

**Comment by andreasohlund** [comment]
> is there any value for the queue to be non-transactional?

Only thing I know of is that this is requred for `Express` messages to actually work

>If so, allowing the "useTransactionalQueue" to be part of a connection string, perhaps make it into a API call where the user will be warned very thoroughly that messages from this endpoint will not be delivered to the centralized error queue.

I think all the connection string options should be made into api calls and the conn string obsoleted.

In general, f you want to use non transactional queues you need to do it across the endpoints that needs to interact for the reasons you mention so its indeed a very big architectural decision. 

@Particular/servicecontrol-maintainers is possible to configure SC to run with non tx queues?

My gut feeling tells me that we should obsolete non tx queues and the `Express` attribute in the next major version? ( @Particular/nservicebus-maintainers )

**Comment by gbiellem** [comment]
@andreasohlund we don't ask for,  or expose a way to configure the connection string for MSMQ in the ServiceControl UI.   The only way would be to hack the app.config and I'm not sure that would persist after an upgrade.  So short answer is maybe but not in a good way.

**Comment by indualagarsamy** [comment]
@andreasohlund - this config i.e. Creating non transactional queues was introduced in v4. V3 did not have a way to do this as far as I remember.

What use cases are express messages useful? They still persist to disk: https://blogs.msdn.microsoft.com/johnbreakwell/2008/04/04/why-are-my-express-msmq-messages-being-written-to-disk/


Sent from my iPhone

**Comment by andreasohlund** [comment]
I never used it my self but I guess it performance might be a bit better since the caller don't have to wait for the fsync to happen.

I'm 👍 for removing `Express` from NServiceBus (related issue https://github.com/Particular/NServiceBus/issues/4252)

**Comment by danielmarbach** [comment]
Paging @ramonsmits I thought the performance test investigation he did showed that express doesn't change much in terms of better performance or throughput

**Comment by ramonsmits** [comment]
Non transactional messaging is quite a bit faster. I can easily push over 25,000 messages per second for a single endpoint where transactional queues somewhere in the 10.000 range.

The problem is as @indualagarsamy explained the incompatibility with the error/audit queues. Current if an endpoint it 'non-transaction' that is infectious for all queues being used. That is an NServiceBus issue AFAIK as the transactional queue usage in code can be different for each queue. So we could also fix the delivery issue to any queue in the transaction mode None when we resolve the route to either a transactional or non-transactional queue.

I think in the current form Express messages are a MSMQ concept. As in https://github.com/Particular/PlatformDevelopment/issues/309 is suggested to move it to the MSMQ package once extracted from core.

Creating non-transactional queues is already hard. It can only be done via the connection string and not via the API so I think documenting its implications would be a good thing at https://docs.particular.net/nservicebus/msmq/connection-strings

**Comment by indualagarsamy** [comment]
@ramonsmits - I have a question. When you run your test with transactions off, can you run the test with TransactionMode turned off, *however, keep the queue still transactional by not change the config setting* and see if there's a difference in your test results?

**Comment by indualagarsamy** [comment]
Had a chat with @andreasohlund. Our discussion is summarized as follows:
- We agree that we need a API rather than pass these settings as we do in the connection string. 
- We agree that the "UseTransactionalQueues=false" is a dangerous setting.
- Express messages are believed to be completely in-memory. However that is not true. Express messages are also persisted to disk. The only difference is that they will not be recoverable in case of a crash like the recoverable messages. More on this: https://blogs.msdn.microsoft.com/johnbreakwell/2008/04/04/why-are-my-express-msmq-messages-being-written-to-disk/. 
- We agreed that we currently log a WARN, if the user is using the "usetransactionalqueues=false" setting now.

**Comment by andreasohlund** [comment]
>We agreed that we currently log a WARN, if the user is using the "usetransactionalqueues=false" setting now and reach out to the user group to see how many of our users use the "Express" functionality in MSMQ.

Just adding that the WARN would state that this "feature" will be removed in v7

**Comment by timbussmann** [comment]
@indualagarsamy what's the state on this issue?

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/7.
