### ISSUE TITLE
MSMQ: When EnableInstallers are run on a windows domain, queues are created with "Everyone" however without the "Send" ACL

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4525]
Steps to Repro:

1. Setup a test domain
2. Run the full duplex server sample
3. Inspect the queues created and the security. 
4. Note that Everyone does not have "Send Messages" Queue permission. 

![bad-permissions](https://cloud.githubusercontent.com/assets/854553/23494586/94fec2ae-fec8-11e6-8c91-85411332983f.PNG)

Everyone should be granted Send Messages, otherwise, messages cannot be sent. 

```
Unhandled Exception: System.Exception: Failed to send message to address: Samples.FullDuplex.Server1 ---> System.Messaging.MessageQueueException: Access to Message Queuing system is denied.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_WriteHandle()
   at System.Messaging.MessageQueue.StaleSafeSendMessage(MQPROPS properties, IntPtr transaction)
   at System.Messaging.MessageQueue.SendInternal(Object obj, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
   at System.Messaging.MessageQueue.Send(Object obj, String label, MessageQueueTransactionType transactionType)
   at NServiceBus.MsmqMessageDispatcher.ExecuteTransportOperation(TransportTransaction transaction, UnicastTransportOperation transportOperation) in C:\Dev\NServiceBus\src\NServiceBus.Core\Transports\Msmq\MsmqMessageDispatcher.cs:line 89
```

NOTE: The behavior is different when the machine is not part of the domain. Everyone has "Send" permission in that case. 

I ran this by @gbiellem and we think its a bug.

**Comment by andreasohlund** [comment]
I think we broke this in https://github.com/Particular/NServiceBus/pull/4304 under the false assumption that since MSMQ will add the everyone group we're good.

👍 to fix this since it hurts the current F5 experience

**Comment by ramonsmits** [comment]
I do not consider this a bug. The process owner that created the queue (indu@testdomain.local) is likely to have send privileges thus would not hurt the F5 experience. Can you confirm that @indualagarsamy ? I currently don't have access to a VM running in a domain.

We as a framework should never grant Everyone permissions to a queue. If you are in a production environment that has multiple endpoints running with different credentials than each account involved should have the authorization configured to send to a specific queue. Either manually or scripted.

**Comment by cremor** [comment]
But according to the [documentation](https://docs.particular.net/nservicebus/msmq/transportconfig#queue-permissions) this is a bug:

> By default, queues are created with Everyone and Anonymous Logon permissions to allow messages to be sent and received without additional configuration. 

So either it needs to be changed or the documentation needs to be updated.

**Comment by indualagarsamy** [comment]
@ramonsmits - 

>We as a framework should never grant Everyone permissions to a queue. If you are in a production environment that has multiple endpoints running with different credentials than each account involved should have the authorization configured to send to a specific queue. Either manually or scripted.

While I agree with that, that's the not the current behavior as @cremor pointed out and what I found out during testing. 

At the moment, we grant Send permissions for Everyone if on a workgroup, but don't if on a domain. I see that as an inconsistency. 

@gbiellem - Your thoughts on this?

**Comment by gbiellem** [comment]
@indualagarsamy  you already know my opinion... From above:

>   ran this by @gbiellem and we think its a bug.

**Comment by ramonsmits** [comment]
@indualagarsamy Well, that is behavior from Windows/MSMQ, not from us. Why would we want to align that behavior by explicitly granting non secure permissions in case windows decides that a domain should be more secure by default?

**Comment by gbiellem** [comment]
@ramonsmits  

The current situation is we are inconsistent with permissions between a workgroup machine and a domain machine.  The fact that MS is also inconsistent isn't an excuse or indeed a something to be emulated.  

Personally I'd never use "Everyone" in production but a domain machine is not necessarily a production machine so I don't see that as a reason to treat the installation differently.

This gets back to what are we optimizing for - the  F5 development or Production deployment,
I don't mind which it is as long as it's consistent and documented.  Otherwise stuff like this just confuses our end users.

**Comment by andreasohlund** [comment]
Do we need a call to reach a conclusion?

**Comment by cremor** [comment]
The documentation I linked in https://github.com/Particular/NServiceBus/issues/4525#issuecomment-284139726 was updated to not mention permissions any more. The documentation was moved to https://docs.particular.net/nservicebus/msmq/ in Particular/docs.particular.net#2227 and now has the following text:

> Write access is granted to both Everyone and Anonymous. The reason for this is so that a given endpoint can receive messages from other endpoints running under different accounts.

And while this issue is about the "Everyone" group, the "Anonymous" group should not be forgotten either. Right now queues are created without any permissions for "Anonymous" in domain environments as you can see in the screenshot of the issue description.

**Comment by indualagarsamy** [comment]
Had a chat with @andreasohlund and our discussion is summarized as follows:

- The [queue creation code](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs) does not explicitly add "Everyone" group either for workgroup or domain. The everyone group having these quirks is a Windows/MSMQ thing and not necessarily by us. 
- The documentation as highlighted by @cremor is incorrect and needs to be fixed. Thanks @cremor. 
Will sync with @gbiellem and craft an action plan.

**Comment by timbussmann** [comment]
@indualagarsamy what's the state on this issue?

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/6.
