### ISSUE TITLE
Disabling BestPractices

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4532]
As mentioned in https://github.com/Particular/NServiceBus/pull/4529, it seems that even when best practices are disabled, we still check whether the given type is a message type and no command type when trying to register publishers.

Should we either fix the behavior to be less restrictive when disabling best practices or should we remove the tests which assume that you can violate the best practices (which seemed to work when using message endpoint mappings).

related tests:
* When_subscribing_to_command_bestpractices_disabled_on_endpoint
* When_unsubscribing_to_command_bestpractices_disabled_on_endpoint

**Comment by timbussmann** [comment]
e.g. see this code which just seems wrong:
https://github.com/Particular/NServiceBus/blob/24a99ba5a2c7bd008465ba8c6315cfcd4539054c/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/TypePublisherSource.cs#L31

**Comment by timbussmann** [comment]
@SzymonPobiega since you added that code, do you remember why we still validate even when best practices are disabled?

**Comment by SzymonPobiega** [comment]
@timbussmann I could not find the written source for the code you quoted but my faint memory points me to some conversations with @andreasohlund where we concluded that:
 * When best practices are enforced, we make sure you can only configure publisher for things that are considered events
 * Even when best practices are *not* enforced we need to make sure people are not actively trying to shoot themselves in the foot by ensuring you cannot configure publisher for things that are not even messages (because non-messages would not be handled anyway) or things that are declared as commands.

Does it make sense?

**Comment by timbussmann** [comment]
> ensuring you cannot configure publisher for things that are not even messages (because non-messages would not be handled anyway) 

that makes sense to me 👍 

> or things that are declared as commands.

while it would be pretty bad approach, but it doesn't seem that this would have a deeper reason?

when you enable best practices, we enforce that the type
* is a event (& a message, for whatever reason?)
-> type must be a event

when you disable best practices, wen enforce that the type
* is a message
* or is not a command
-> type must be a message or event

even better, when you enable best practices, the best practices behavior will check when subscribing that the given type is a event OR a message (in the later case, it logs an info entry).

**Comment by SzymonPobiega** [comment]
Pretty sure there are similar checks happening in the subscribe pipeline already.

**Comment by timbussmann** [comment]
> Pretty sure there are similar checks happening in the subscribe pipeline already.

yeah, as mentioned, this happens when best practices are enabled:

> , when you enable best practices, the best practices behavior will check when subscribing that the given type is a event OR a message (in the later case, it logs an info entry).

**Comment by timbussmann** [comment]
although I still think the implementation is weird and somewhat incorrect to the expected behavior when disabling best practices, I can't really come up with a legit scenario where you would be blocked by the behavior, therefore I'm closing this for now and remove the tests. It seems to be an entirely incorrect usage to subscribe to commands regardless of best practices. Best practices may be valuable in ensuring that you subscribe to an event instead of a plain message, but commands seems to be just plain wrong and I don't see a reason why this should be supported.

Please feel free to reopen/comment in case you have a good scenario where this behavior needs to be adjusted.
