### ISSUE TITLE
Bug: Inconsistency between DataBusProperty.HasValue and DataBusProperty.Value

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/NServiceBus#4547]
var productsDataBusProperty = new DataBusProperty<byte[]>(memoryStream.ToArray());
     productsDataBusProperty.SetValue(null);
     Debug.Assert(productsDataBusProperty.HasValue == (productsDataBusProperty.Value != null));

See https://github.com/Particular/NServiceBus/blob/18e4f48f34553206fc9ae9697ac12d93c19d6659/src/NServiceBus.Core/DataBus/DataBusProperty.cs#L60

**Comment by timbussmann** [comment]
Thanks for the bug report @Niklas-Peter , will be fixed as part of 6.2 👍
