### ISSUE TITLE
Memory consumption of (FileShare)DataBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/NServiceBus#4549]
I downloaded the [file share DataBus sample](https://docs.particular.net/samples/file-share-databus/) and changed the size of the byte array to be sent.

Set to 20MB the memory consumption jumps from 35 MB to 120 MB, with a byte array of 90 MB it even needs 430 MB memory. Just for testing I called the garbage collector manually and then the memory significantly decreases. Of course, I do not want to put a call to the GC in my code. 

Is this behavior purely caused by C# or is there anything in NServiceBus consuming such a huge amount of memory? 
I noticed, that when only the sender is active, but not the receiver, the memory consumption is much higher (60 MB compared to 135 MB) than when the receiver is also active.

`IDataBus` uses `Stream`s. Why is `Stream` not supported for `DataBusProperty`?

(I know, there is an example for using streams via a pipeline extension, but I try to understand your restriction to `byte[]` for the DataBus.)

**Comment by timbussmann** [comment]
you are correct, ideally there should be stream support for the DataBusProperty. It's mainly an old design flaw which was never addressed so far as there was no real demand for it.

Our recommendation is to use the samples for using streams via pipeline extensions, which allows for much better customization tailored to the specific needs.

sidenote: It's very likely that the DataBus APIs will be moved out of the core in the future to a dedicated package which would allow for improvements to the databus decoupled from core.

**Comment by Niklas-Peter** [comment]
I just noticed some weaknesses of the Stream sample:

- The Stream is created once for all handlers. If the first handler reads the first byte from the stream the cursor is changed and subsequent handlers can not read the data again.
- The Stream is disposed in the pipeline behavior. If the handler passes the Stream to an object still available after the current message was processed, this outside object will try to access an disposed Stream.

The 2nd point is not critical, because you could add this constraint to the specification.
However, the first one should be fixed. I considered one of these approaches:

- Use a special property type like "StreamBusProperty". On the receiving side this property could provide a factory for the Stream.
- Insert the behavior at a later step in the pipeline to execute it once per handler instead of once per message.

In both approaches each handler would get its dedicated Stream and the responsibility to dispose it.

**Comment by mikeminutillo** [comment]
@SimonCropp are you able to handle these questions about the Streaming attachments sample?

**Comment by SimonCropp** [comment]
@Niklas-Peter 

you are correct that the stream should be injected on each handler execution. I have fixeds the [behavior in docs](https://docs.particular.net/samples/pipeline/stream-properties/#configuring-the-pipeline-behaviors) to reflect that.

**Comment by timbussmann** [comment]
@Niklas-Peter given that @SimonCropp adjusted the sample based on your feedback, are you good with me closing this issue?

**Comment by SimonCropp** [comment]
@Niklas-Peter 

> The Stream is disposed in the pipeline behavior. If the handler passes the Stream to an object still available after the current message was processed, this outside object will try to access an disposed Stream.

You can of course change the sample to work this way. the sample does not work this way by default since it is preferable to perform all handler related actions inside the scope of the current transaction, so if any exceptions occur the transaction will roll back

**Comment by Niklas-Peter** [comment]
@timbussmann Yes, I agree.
