### ISSUE TITLE
Should we internalise RuntimeEnvironment?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4553]
It only has the MachineName API, is not documented, and it would seem it is only public for testing purposed? https://github.com/search?p=1&q=org%3AParticular+RuntimeEnvironment.MachineName&ref=searchresults&type=Code&utf8=%E2%9C%93

Propose we obsolete it with warning.

**Comment by SimonCropp** [comment]
and this should be an explicit API that extends the MSMQ transport https://docs.particular.net/nservicebus/msmq/full-qualified-domain-name

**Comment by timbussmann** [comment]
@SimonCropp aren't we using it here: https://github.com/Particular/docs.particular.net/blob/4dd3ab2b7c0a13136dc3ee988694578c7d717443/Snippets/MsmqTransport/Core_4/FQDM.cs ?
