### ISSUE TITLE
Attempting to publish from a Send Only endpoint should throw an exception

### ISSUE THREAD

**Issue by stimms** [Particular/NServiceBus#4556]
The subscription mechanism requires that endpoints be able to read from a queue to set up their subscriptions. However send only endpoints have to queue from which to read and thus no way to get subscriptions (other than manual subscription). Messages published from send only endpoints are destined to never have any destinations. It is not immediately apparent that this is the case, it would be nice to fail users early by throwing an exception when they attempt to publish from an endpoint marked as send only.

**Comment by janovesk** [comment]
Hi, @stimms!

Thanks for reaching out.

This is a scenario we have thought about, and it's valid. 

It's true that the send-only endpoints themselves will not be able to receive message driven subscriptions, but it's perfectly valid for them to use a subscription store that is populated by a helper endpoint that is not send-only. Remember also that we support transports that have built-in support for pub/sub, meaning no message driven subscriptions in the first place.

The diagram at https://docs.particular.net/nservicebus/hosting/publishing-from-web-applications#storage-driven-transport-topology illustrates the scenario quite nicely.

Regards,
Jan Ove
