### ISSUE TITLE
Assembly load exception in AssemblyScaner.ReferencesNServiceBus()

### ISSUE THREAD

**Issue by allex32** [Particular/NServiceBus#4566]
Good day.
I'm trying use NServiceBus in a complex legacy WinForms application. 
When I try to start `EndpointInstance `inside WinFormApp (for example, when user click on the button), the following error occurs : 
`System.Exception: Could not load "..\LegacyApp.Win.vshost.exe". Consider excluding that assembly from the scanning. The assembly "..\LegacyApp.Win.vshost.exe" has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.`

At the same time `LegacyApp.Win.exe` is the main executable file of application.

StackTrace:
```
 в NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(String assemblyPath, AssemblyScannerResults results, Dictionary`2 processed) в \src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:строка 158
   в NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() в \src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:строка 69
   в NServiceBus.EndpointConfiguration.GetAllowedTypes(String path) в \src\NServiceBus.Core\EndpointConfiguration.cs:строка 255
   в NServiceBus.EndpointConfiguration.Build() в  \src\NServiceBus.Core\EndpointConfiguration.cs:строка 188
```
I tried exclude conflicted  assemblies in a crude way by excluding all assemblies, except for `TargetAssembly.dll,` (there is located custom wrapper for NServiceBus).

Example : 

```
string targetAssembly = "TargetAssembly.dll";
foreach (var fileName in Directory.EnumerateFiles(baseDirectory, "*").Select(Path.GetFileName))
{ 
     if (!Regex.IsMatch(fileName, targetAssembly, RegexOptions.IgnoreCase))                                 
          endpointConfiguration.ExcludeAssemblies(fileName);                                   
}

```
But it didn't help.

Please can you tell me what I'm doing wrong?

**Comment by bording** [comment]
@allex32 Have you tried to specifically exclude the `LegacyApp.Win.vshost.exe` file mentioned in the error message? That is the Visual Studio hosting process, which it uses to enable some debugging scenarios.

What version of Visual Studio are you using? I've tried reproing the problem with Visual Studio 2015, and I can't replicate it.

I'm not sure why the hosting process is causing this issue for you, but you can try disabling the hosting process by going into the project's properties, Debug tab, and unchecking "Enable the Visual Studio Hosting process."

If you'd like to investigate further why your code is having a problem with this without disabling it, please post code showing how you're creating your `EndpointConfiguration` class and starting the endpoint.

**Comment by timbussmann** [comment]
as we haven't received any updates from you @allex32, I'm going to close this issue for now. Please feel free to reopen.

**Comment by kristianjaeger** [comment]
I just hit the same thing for NSB 6 with VS2017.  I was able to workaround it by adding

`var scanner = endpointConfiguration.AssemblyScanner();
  scanner.ExcludeAssemblies("offendingbinarynamegoeshere.vshost.exe");`
Cheers.
