### ISSUE TITLE
Do we support generic messages and handlers?

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4570]
I wasn't able to find some explicit statement whether we support generic messages and generic handlers, e.g. `MyMessage<SomeOtherType>` with a  handler `MyMessageHandler : IHandleMessages<MyMessage<SomeOtherType>>`. 

There seems to be an older issue which would indicate this being supported: https://github.com/Particular/NServiceBus/issues/1549 but as of now, I'm not aware of any acceptance test regarding that scenario.

So in general:

* Are generic messages supported?

I tend to say no, as it seems like a bad practice so use generic messages instead of specific ones but I have to admit that I might just not be aware of a valid scenario.
If we agree to no we should
* document this
* ideally prevent this from being used in the first place

If it would be supported, there there would be a need for quite a few tests around this functionality.

thoughts @Particular/nservicebus-maintainers @SimonCropp 
are there some engineers which can provide some helpful thoughts on this topic?

**Comment by egorpavlikhin** [comment]
Why is it a bad practice to use generic messages? It's just a language feature to reduce code duplication. NServiceBus doesn't seem to support this, which is really unforunate, since the alternative is to write a bunch of T4 templates and I really don't like changing architecture because of one library's shortcomings.

**Comment by timbussmann** [comment]
> Why is it a bad practice to use generic messages? It's just a language feature to reduce code duplication. 

@egorpavlikhin In general, NServiceBus is mostly intended for "business messages", messages which express some kind of business related commands or events and so far we haven't seen generic business events.

But since you mentioned that your architecture is using generic messages, we would be very interested in learning more about your usage of generic messages. Would you be able to share some examples of your generic messages with us to help us understand where you encounter a lot of code duplication in your message contracts?

**Comment by SimonCropp** [comment]
@drokedr would your staging service be better built as a behavior? https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

**Comment by SimonCropp** [comment]
>  designing a staging service that should take in arbitrary Commands, log them, and then decide when they're actually submitted to work queues.

@drokedr so is this a stand alone endpoint with the only role is to do the above? ie no other handlers?

**Comment by timbussmann** [comment]
Closing this discussion for now, as there is now documentation added [here](https://docs.particular.net/nservicebus/messaging/messages-events-commands#designing-messages) that clarifies that generic messages are currently not supported. If this is a feature you'd like to see released, please feel free to raise an issue!
