### ISSUE TITLE
Publish|Reply|Unsubscribe|SubscribeOptions merges into parent context

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus#4573]
## How to know if you are affected

You are affected if you pass `ReplyOptions`, `PublishOptions`, `UnsubscribeOptions` or `SubscribeOptions` into the corresponding `IMessageSession` or `IMessageHandlerContext` operation as demonstrated in the following snippets:

```
var options = new PublishOptions();
options.RequireImmediateDispatch();
await session.Publish(new Event(), options);
```

```
var options = new PublishOptions();
var state = options.GetExtensions().GetOrCreate<MyState>();
state.Property = "Value";
await session.Publish(new Event(), options).ConfigureAwait(false);
```

### Leaking settings between outgoing operations

Options and values set on `PublishOptions`, `ReplyOptions`,  `UnsubscribeOptions` and `SubscribeOptions` are merged into the parent context object and therefore apply to further message operations issued in the same context. There are two different types of contexts which can be used:

#### Message session context

The message session has the same lifetime as the endpoint. The parent context, therefore also has the same lifetime as the endpoint. Any state that is set using either `ReplyOptions`, `PublishOptions`,  `UnsubscribeOptions` or `SubscribeOptions` will end up in the parent context and have the same lifetime as the endpoint.

```
var options = new PublishOptions();
options.RequireImmediateDispatch(); // will affect all operations that happen on message session
await session.Publish(new Event(), options);
await session.Publish(new Event()); // will have immediate dispatch set
await session.Send(new Command()); // will have immediate dispatch set
```

#### Handler context

The handler context has the same lifetime as the message that is being handled. Its parent context also has the same lifetime as the message. Any state that is set using either `ReplyOptions`, `PublishOptions`,  `UnsubscribeOptions` or `SubscribeOptions` will end up in the parent context and will also have the same lifetime as the message.

```
public class MyMessageHandler<MyMessage> : IHandleMessages<MyMessage> {
    public async Task Handle(MyMessage message, IMessageHandlerContext context) {
       var options = new PublishOptions();
       options.RequireImmediateDispatch(); // will affect all operations that happen on context
       await context.Publish(new Event());
       await context.Publish(new Event(), options); // will have immediate dispatch set
       await context.Send(new Command()); // will have immediate dispatch set
    }
}
```

When multiple message handlers are invoked for the same message, operations on other message handlers will also be affected.

### Race Conditions

Concurrent outgoing operations on the same context are vulnerable to race conditions. Race conditions can cause a setting/value to be overwriten as outlined in the following snippet:

```
// Thread 1:
var options = new ReplyOptions();
options.SetCorrelationId("42")
await session.Reply(new Reply(), options);

// Thread 2:
var options = new ReplyOptions();
options.SetCorrelationId("43")
await session.Reply(new Reply(), options);

// Invoked in pipeline on Thread1 and Thread 2:

class BehaviorInOutgoingContext : Behavior<IOutgoingReplyContext> {
   public async Invoke(IOutgoingReplyContext context, Func<Task> next) {
       AttachCorrelationIdBehavior.State state;
       options.Context.TryGet(out state);
       var customCorrelationId = state?.CustomCorrelationId;
       // Executed on Thread 1 might see data from Thread 2 or Thread 1
       // Executed on Thread 2 might see data from Thread 1 or Thread 2
       await next();
   }
}
```

### Memory Leaks

State configured set on `ReplyOptions`, `PublishOptions`,  `UnsubscribeOptions` or `SubscribeOptions` which is passed to `IMessageSession` will be merged into the root context. The root context has the same lifetime as the endpoint and therefore this can cause state to not be disposed.

**Comment by timbussmann** [comment]
This has been addressed in hotfixes 6.1.4 and 6.0.7 and is also merged into develop. Closing this.
