### ISSUE TITLE
Prevent saga entity type reuse

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4597]
Since it can cause incorrect behavior depending on what persister is used.

See https://github.com/Particular/NServiceBus/issues/4585#issuecomment-291778504

@Particular/nservicebus-maintainers this is a trivial change in the saga meta data collection. I propose we do this in 6.3

**Comment by andreasohlund** [comment]
Starting to doubt my self here, not sure if this is worth it. I wonder if we instead should consider making the "SagaTypeId" and explicit thing in the seam and pass it where appropriate to avoid the persisters having to assume that they should use the type of the entity.

If that was the case we would perhaps instead take that "id" from the saga class it self and not the entity and that would make this a non issue and would allow users to reuse the entity in anyway they like (not saying that reusing is a good idea but its supported from a "C#" perspective.

@Particular/nservicebus-maintainers I'd say we close this?

**Comment by timbussmann** [comment]
not sure I have enough context to make a call on this. But it doesn't sound like a trivial change if this has a chance to influence persistence behavior

**Comment by bording** [comment]
@andreasohlund I'm with @timbussmann on this one, I don't have enough context around the problem and proposed changes. Maybe we can talk about it during a sync meeting?

**Comment by andreasohlund** [comment]
Covered by https://github.com/Particular/NServiceBus/issues/4596 , closing
