### ISSUE TITLE
Better tests for message deferral?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4601]
From https://github.com/Particular/NServiceBus.AzureServiceBus/pull/519#discussion_r109590791

> The problem is that ASB has its own time on the broker. When clock skew occurs between the client and the broker then this test will fail. Unfortunately it is not even guaranteed that one second is enough. Should we come up with better tests?

> Wouldn't it be good enough to have two tests where we do the following:
> 
> - One test sets the delay to a fraction of the test run times and asserts that the message was received within the test runtime
> - On test sets the delay to a multiple of the test run time and verifies that the message was not received within the test runtime
> 
> But not asserting the actual receivedAt or only that the timespan falls withing the test runtime which is actually automatically given when we received the message?

As @timbussmann rightfully pointed out this would have the drawback of potentially longer running tests for the "message not received" part

https://github.com/Particular/NServiceBus.AzureServiceBus/pull/519#discussion_r109942975

> > One test sets the delay to a fraction of the test run times and asserts that the message was received within the test runtime
> 
> this of course depends on the delayed delivery mechanism/implementation. But too short delayed delivers are not going through the timeout storage but are short circuited. This might be just a problem with the timeoutmanager though.
> 
> > On test sets the delay to a multiple of the test run time and verifies that the message was not received within the test runtime
> 
> this would make a very long running test as you would have to account for enough time in the test run so that endpoints are able to spin up before the timeout is reached. Such long running tests is something we wanted to avoid.
> 
> @danielmarbach how about raising an issue to discuss this problem in the core?
>

**Comment by timbussmann** [comment]
yeah we are struggling to have good tests around all sorts of delayed sends (including slr and saga timeouts). I think there are actually different things we would like to verify:

* is the message indeed configured to be delayed? This is hard to verify in the core as we can only check for certain configurations/settings as the rest is responsibility of the transport. From a core perspective it might be good enough to check those settings, but that's also hard to do in acceptance tests as it might not be easy to access these settings publicly (not verified). Is there something on the transport tests we could do (testing the dispatcher)?
* is the message delayed be the correct amount of time? This is really hard and also heavily depending on the actual deferal implementation. There might be a way when testing the timeout manager to fake the clock to verify this, but as soon as you're using native solutions, this is no longer possible. This also means there is no good way to test this throughout from acceptance tests.

**Comment by timbussmann** [comment]
I think we all agree on this issue. I think we can close this discussion and raise an issue to find a way to improve those tests somehow. Thoughts @danielmarbach ?

**Comment by danielmarbach** [comment]
Good for me @timbussmann Let @Particular/azure-maintainers know if you need someone to brainstorm

**Comment by timbussmann** [comment]
issue #5007 raised to track this. Closing this discussion. Thanks for raising this Daniel 👍
