### ISSUE TITLE
Change subscription storage seam to not receive the message hierarchy

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4611]
When querying for subscribers in https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/ISubscriptionStorage.cs we pass the full message hierarchy as a parameter. In order to reduce/eliminate the need to know the message hierarchy at the core, I think we should change this API to just pass the the published message type. The message type should contain enough information to derive base classes to find subscribers.

Of course this will require the persistence test suite in order to ensure all storages check for subscribers of base types.

thoughts @Particular/nservicebus-maintainers @Particular/ravendb-persistence-maintainers @Particular/nhibernate-persistence-maintainers @Particular/sqlpersistence-maintainers ?

**Comment by MarcinHoppe** [comment]
What is not clear to me is why this change is beneficial and what problem does it solve.

**Comment by timbussmann** [comment]
@MarcinHoppe mostly to free the core from the responsibility to store "message metadata" which currently only contains the message hierarchy. It would allow us to simplify code and seam APIs.

**Comment by SzymonPobiega** [comment]
🔥 the subscription store.

**Comment by DavidBoike** [comment]
> mostly to free the core from the responsibility to store "message metadata" which currently only contains the message hierarchy. It would allow us to simplify code and seam APIs.

This seems like a benefit to the Core, but it's offloading something complex onto the persisters instead. It seems like an academic exercise to just move the code around, and now multiple packages are going to have to do the exact same thing, in the exact same way, or we'll have an even bigger mess.

And it would take a whole lot of work to get there, across some packages that, quite frankly, work as they are right now, and where I'd rather not rock the boat.

What is the benefit **to the customer?**

**Comment by timbussmann** [comment]
closing this as there doesn't seem to be a large agreement on how that API should look like and as @DavidBoike pointed out correctly, it doesn't seem that this would bring significant improvements to anyone right now.
