### ISSUE TITLE
Treat custom implementation of IManageMessageFailures in the same way as the built in FaultManager is treated

### ISSUE THREAD

**Issue by pawelpabich** [Particular/NServiceBus#463]
Hi,

When a custom implementation of IManageMessageFailures is provided then ErrorQueue property is not being set.
Additionally it's impossible to extend the built-in FaultManager via inheritance because it implementes IManageMessageFailures explicitly. 
If it's possible please register the built-in implementation in the container so it can be extended using composition.

This is a sample implementation that works for me but feels more like a hack than a proper solution.

Thanks
```
public class CustomFaultManager : IManageMessageFailures
    {
        private readonly IManageMessageFailures faultManager;
        static CustomFaultManager()
        {
            Configure.Instance.MessageForwardingInCaseOfFault();
        }

        public CustomFaultManager()
        {
            faultManager = new FaultManager();
            ((FaultManager)faultManager).ErrorQueue = ConfigureFaultsForwarder.ErrorQueue;
        }

        void IManageMessageFailures.SerializationFailedForMessage(TransportMessage message, Exception e)
        {
            faultManager.SerializationFailedForMessage(message, e);
        }

        void IManageMessageFailures.ProcessingAlwaysFailsForMessage(TransportMessage message, Exception e)
        {
            faultManager.ProcessingAlwaysFailsForMessage(message, e);
            //Custom code goes here
        }

        void IManageMessageFailures.Init(Address address)
        {
            faultManager.Init(address);
        }
    }
```

**Comment by johnsimons** [comment]
This will be addressed as part of v6.
In v6 `IManageMessageFailures` is no longer an extension point. If you want full control over what happens when a message fails (including retries) please override the `MoveFaultsToErrorQueueBehavior`. If you just want to get notified when messages are being moved please use BusNotifications.Errors.MessageSentToErrorQueue.Subscribe(e=>{})
