### ISSUE TITLE
Assembly scanning exclusion does not work with 'exe' file extension

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus#4633]
The [Assembly scanning](https://docs.particular.net/nservicebus/hosting/assembly-scanning) documentation page doesn't explicitly say this, but from the sample code it looks like it expects file names including the extension in the call to `assemblyScanner.ExcludeAssemblies()`.

My testing with version 6.2.1 shows that for .dll files it doesn't matter if you specify the file extension or not. But excluding .exe files only works **without** the extension.

**Comment by timbussmann** [comment]
looking at the following code in the `AssemblyScanner`, I think you're right:

        static string DistillLowerAssemblyName(string assemblyOrFileName)
        {
            var lowerAssemblyName = assemblyOrFileName.ToLowerInvariant();
            if (lowerAssemblyName.EndsWith(".dll"))
            {
                lowerAssemblyName = lowerAssemblyName.Substring(0, lowerAssemblyName.Length - 4);
            }
            return lowerAssemblyName;
        }

this code should also remove `.exe` endings I'd say. Thoughts @Particular/nservicebus-maintainers ?

**Comment by dbelcham** [comment]
I agree that we should strip `.exe`. There's nothing saying that messages can't be in that type of file.
