### ISSUE TITLE
Summary documentation on FeatureStartupTask.OnStop wrong

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus#4657]
The summary documentation on `FeatureStartupTask.OnStop` is the same as on `OnStart`: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureStartupTask.cs#L18

Also, you might want to update the param documentation since there is no "bus" any more in v6.

**Comment by timbussmann** [comment]
Good catch, raised a PR here: https://github.com/Particular/NServiceBus/pull/4658

**Comment by timbussmann** [comment]
thanks again for raising this @cremor , the summary will be fixed with the 6.3 release 👍
