### ISSUE TITLE
MSMQ: Should throw an exception if the machine name exceeds NETBIOS limitation instead of just warn

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4660]
Currently we do check for the NetBios limitation here:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/CheckMachineNameForComplianceWithDtcLimitation.cs#L29

However, having an non-compliant machine name could result in problems with messages being sent and has resulted in support cases where the NETBios name was the problem. 

Instead of just logging a warning, should we throw instead?

**Comment by indualagarsamy** [comment]
cc / @Particular/msmq-transport-maintainers

**Comment by dvdstelt** [comment]
As I stated in Slack, a customer says it can reproduce a situation where NServiceBus crashes and then the queue gets corrupt!
Not sure if we can reproduce this, but if customer can and there's just the slightest chance of queues getting corrupt, I agree with @indualagarsamy and think we should throw.

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/4.
