### ISSUE TITLE
Limit message size on the learning transport to Min(SupportedTransports)

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4664]
At the time of writing this would be 64kb (ASQ).

We would throw telling users that some transports won't handle this and suggest the Databus/Claim check pattern. 

We would also provide a config option to up the limit if needed.

cc @Particular/azure-maintainers 

@Particular/rabbitmq-transport-maintainers what's the limit on rabbit?

**Comment by Scooletz** [comment]
👍

**Comment by danielmarbach** [comment]
Like it

**Comment by bording** [comment]
RabbitMQ does not have a maximum message size that is enforced, but a really large message would certainly slow things down inside the broker.

OK, technically there is a max length, because the total payload size is included in the AMQP message header frame as an unsigned 64-bit value! 😄

**Comment by SeanFeldman** [comment]
Just the fact that out of the box transport will raise the awareness about transports potentially having a message size limit is a move in the right direction. 💯%

**Comment by yvesgoeleven** [comment]
👍
