### ISSUE TITLE
How to make sure we start clean when using [TestCase]

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4675]
As this [commit shows](https://github.com/Particular/NServiceBus/pull/4668/commits/4ea362eb071304a43f0fe7efc3fcf7b78a527f0c) we might run into trouble when running multiple [TestCase] tests. This is because NUnit will reuse the test instance and in this case the message pump was left partly initialized causing object disposed issues.

Ideas on how to better handle this since this will hit us again?

**Comment by timbussmann** [comment]
Closing this as we feel like there doesn't seem to be enough interest or pressure to address this and this issue would probably just stay around for a long time. I think this question has to be answered next time we're running into this problem directly instead.
