### ISSUE TITLE
ASP.NET Core 2.0 support?

### ISSUE THREAD

**Issue by johnfake** [Particular/NServiceBus#4686]
Hi,

could somone comment https://github.com/aspnet/Home/issues/2022 this please?

It seems that ASP.NET Core 2.0 can't reference the full framework anymore.
Because of that, we can't use NSB?!

Any comments or ideas appreciated!
Regards

**Comment by timbussmann** [comment]
Hi @johnfake 

we're currently working towards supporting .net core 2.0 but there is no official commitment to .net core support yet. We expect that we can give some more details about NServiceBus and .net core within the next couple of weeks.

Does that answer your question/concerns?

**Comment by MarcinHoppe** [comment]
As a side note, it seems that Microsoft has changed their mind with regards to running ASP.NET Core on the full .NET Framework, which should make NServiceBus usable again in ASP.NET Core applications.

**Comment by johnfake** [comment]
@timbussmann Thanks for you comment.

@MarcinHoppe where do you have that information? Build 2017?

**Comment by MarcinHoppe** [comment]
The [official announcement](https://blogs.msdn.microsoft.com/webdev/2017/05/10/aspnet-2-preview-1/) posted yesterdays list lack of .NET Framework support as a "Preview1 issue":

> This preview version of ASP.NET Core 2.0 ships with support for the .NET Core 2.0 SDK only.  Our goal is to ship ASP.NET Core 2.0 on .NET Standard 2.0 so applications can run on .NET Core, Mono and .NET Framework.  As the team was working through the last of their issues before Build, it was uncovered that the preview of ASP.NET Core 2.0 utilized API’s that were outside of .NET Standard 2.0, preventing it from running on .NET Framework. Because of this we limited Preview 1 support .NET Core only so it would not break a developer upgrading an ASP.NET Core 1.x application to ASP.NET Core 2 preview on .NET Framework.

At least this is how I and some other community members read this announcement.

**Comment by johnfake** [comment]
Hmm.. I think it's a good idea to provide native support for .net core or at least netstandard 2.x. I want to send a message from an API to my backend infrastructure with SqlServer-Transport - that's it. 

Let's wait for .NET Core 2.0 RTM :)

**Comment by MarcinHoppe** [comment]
As @timbussmann said, we're working on .NET Core support. Stay tuned.

**Comment by timbussmann** [comment]
@johnfake we have released an announcement regarding .net core 2.0 support on our blog post: https://particular.net/blog/nservicebus-on-net-core-its-time
