### ISSUE TITLE
Add limited support for TimeToBeReceived in MSMQ transactions

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus#4698]
I'd really like to use the `TimeToBeReceived` attribute in the solution I'm developing right now, but I can't since I also have to use MSMQ in Transaction Scope mode.

According to the [documentation](https://docs.particular.net/nservicebus/messaging/discard-old-messages#caveats-msmq-transport) the problem is that all messages in the same transaction share a TTBR. But wouldn't this also mean that NServiceBus could support it if all messages in the transaction use the same value on the `TimeToBeReceived` attribute?

This would implicitly also mean that a transaction that only sends a single message would always work with TTBR. Only from the second send operation onwards it could fail if a different TTBR value is detected.

**Comment by andreasohlund** [comment]
>This would implicitly also mean that a transaction that only sends a single message would always work with TTBR

Not a 100% true, audits are included but if you turn audit off then yes that would be true.

**Comment by cremor** [comment]
Oh, that's a good point. I use audit in my project, so that would be a show stopper for this improvement for me.

I've done some more research and found a mention of a soft TTBR [here](https://github.com/Particular/NServiceBus/issues/4185#issuecomment-251307921) which links [here](https://github.com/Particular/NServiceBus/issues/3562#issuecomment-250727384). So maybe that would be more suitable for my requirement. Is there an issue for this soft TTBR that I can follow?

**Comment by andreasohlund** [comment]
@cremor I've opened up one in our new MSMQ repo (since MSMQ is about to be pulled out of the core )

https://github.com/Particular/NServiceBus.Transport.Msmq/issues/1

Closing this

**Comment by andreasohlund** [comment]
cc @Particular/msmq-transport-maintainers
