### ISSUE TITLE
how to disable server certificate validation in RabbitMQ Client?

### ISSUE THREAD

**Issue by AnatoliiAPFM** [Particular/NServiceBus#4705]
Sorry about posting this question in issues, is there a way to disable server certificate validation?
 
I am getting this exception when trying to connect to a TLS-enabled RabbitMQ

{"The remote certificate is invalid according to the validation procedure."}

 at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)

I am able to confirm that RabbitMQ is propertly configured and able to validate TLS connections via openssl and even using a web browser.

regards,
Anatolii

**Comment by timbussmann** [comment]
@AnatoliiAPFM are you using self-signed certificates on the broker?

**Comment by AnatoliiAPFM** [comment]
yep using self-signed certificate with a local CA on RabbitMQ,
(set it up according to instructions here: https://www.rabbitmq.com/ssl.html)

**Comment by timbussmann** [comment]
in case you configured your broker to use a certificate, why do you want to disable the certificate validation (It's generally speaking highly unrecommended to do so)?

The exception you're seeing is quite common when using self-signed certificates, you might want to look at those links might help you resolve your issues by installing your certificate to the trusted root certification authorities: https://blogs.msdn.microsoft.com/jpsanders/2009/09/16/troubleshooting-asp-net-the-remote-certificate-is-invalid-according-to-the-validation-procedure/  or  http://stackoverflow.com/questions/28032215/identityserver-the-remote-certificate-is-invalid-according-to-the-validation-pr/32788265

**Comment by AnatoliiAPFM** [comment]
Other than also validating the server and/or client's certificates there is a lot of value in TLS in encrypting the content over the wire. I would like to take advantage of the encryption, but not so interested in validating the server, especially in dev environment when experimenting with the setup, playing with routing, etc. 

Since self-signed certificates can't be validated other than by manually adding something to each client machine (which is very inconvenient), many client tools allow to disable server cert validation. I am wondering if it's possible to do that in NServiceBus as well?

example of disabling validation: http://stackoverflow.com/a/2675183
`ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`
But this doesn't work in NServiceBus unfortunately.

or for example sql server client tools and the sql management studio allows to disable validation by using `TrustServerCertificate=True` the connection string (connection options for studio):

`Data Source=myServer;Initial Catalog=myDatabase;User ID=myUser;Password=myPassword;Encrypt=True;TrustServerCertificate=True`

any help would be super appreciated!

**Comment by bording** [comment]
@AnatoliiAPFM For the RabbitMQ transport, the underlying security settings are handled by the RabbitMQ.Client library we use to connect to the broker. We don't currently expose a way for you to change the validation settings, but I've opened https://github.com/Particular/NServiceBus.RabbitMQ/issues/380 to consider adding this capability.

**Comment by AnatoliiAPFM** [comment]
thanks, guys, would be great if the option became available, for now I disabled certificate name comparison in my custom build of `NServiceBus.Transports.RabbitMQ.dll` by adding the following line:

in file `ConnectionFactory.cs`
after line 43: `connectionFactory.Ssl.Enabled = connectionConfiguration.UseTls;`
inserted line: `connectionFactory.Ssl.AcceptablePolicyErrors |= System.Net.Security.SslPolicyErrors.RemoteCertificateNameMismatch;`

**Comment by timbussmann** [comment]
thanks for raising the issue in the rabbitmq repo @bording. With that issue raised, are you ok if I close this issue @AnatoliiAPFM ?

**Comment by AnatoliiAPFM** [comment]
@timbussmann  - yes definitely, thanks again!
