### ISSUE TITLE
Exception incorrectly guides people to use MessageEndpointMappings  

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4706]
we tell people to use MessageEndpointMappings  [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs#L27) and [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs#L37)

 * but [UnicastBusConfig](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/UnicastBusConfig.cs) is obsolete and we recommend people not use it
 * we also give the above exceptions when people are not even using the config approach

**Comment by timbussmann** [comment]
I think we should include this in 6.3 as it seems to be a trivial change aligning the messages better with the upcoming breaking changes.

**Comment by SimonCropp** [comment]
@timbussmann i agree since in 6.3 at startup, if people are using MessageEndpointMappings, we now log an error
