### ISSUE TITLE
XML documentation issue on TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus#4708]
Minor issue: The XML documentation on `endpointConfiguration.TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages()` says "By default we wait for 2 seconds for the storage to come back." but the actual default value is 2 **minutes**. This should either be fixed or not mentioned at all (it's already documented at [Handling of persistence errors](https://docs.particular.net/nservicebus/messaging/timeout-manager#handling-of-persistence-errors)).

**Comment by timbussmann** [comment]
good catch, thanks for raising this @cremor
