### ISSUE TITLE
Audit control messages going through Outbox

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#4710]
I discovered that Subscribe/Unsubscribe messages currently go through the Outbox, which would seem (at least at my first glance) to be unnecessary. Subscribe and Unsubscribe are idempotent operations that do not generate additional outgoing messages.

This is a bit problematic for persisters as Outbox implementations are generally expecting an NServiceBus-generated CombGuid but due to another bug, [they can get transport-native ids instead](https://github.com/Particular/NServiceBus/issues/4709).

This got me thinking that perhaps all types of control messages should be audited for whether they go through the Outbox, and whether they should. Timeouts, especially, might have a performance benefit from removing Outbox deduplication on them (if it currently is) because that message is going to query timeout data and dispatch the real message which is going to get deduped anyway.

//cc @bording

**Comment by timbussmann** [comment]
> Timeouts, especially, might have a performance benefit from removing Outbox deduplication on them (if it currently is) because that message is going to query timeout data and dispatch the real message which is going to get deduped anyway.

I don't think that timeout messages (processed by the satellite queues) are going through the outbox?

I'm not sure there is value in adding the complexity to differentiate between control/non-control messages on a outbox level since they should be idempotent as you already said?

**Comment by bording** [comment]
> I'm not sure there is value in adding the complexity to differentiate between control/non-control messages on a outbox level since they should be idempotent as you already said?

That was my thought as well.

**Comment by timbussmann** [comment]
@DavidBoike given @bording and my thoughts, do you think we need to further discuss this or can we close it?
