### ISSUE TITLE
Should we limit the LearningTransport concurrency to 1 by default?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4711]
This would make demoing/learning easier but would hurt the learning of concurrency awareness.

I personally vote for limiting since concurrency can be learnt later when user move to a real tranport

**Comment by SimonCropp** [comment]
@andreasohlund can u elaborate on

> This would make demoing/learning easier but would hurt the learning of concurrency awareness.

**Comment by andreasohlund** [comment]
>This would make demoing/learning easier but would hurt the learning of concurrency awareness.

You would not have handlers being invoked concurrently, when switching to a prod transport you would so being exposed to it would be delayed to that point in time. I believe this is fine in this case

**Comment by andreasohlund** [comment]
As for it making demos easier , Console.WriteLines in handlers wouldn't "come in order" etc

**Comment by janovesk** [comment]
Limiting the default concurrency to make them focus on the framework and messaging patterns is a good tradeoff IMHO.

The transition to a production transport is such a huge step anyway, requiring a well thought out plan not to cut yourself.

**Comment by weralabaj** [comment]
I also think that limiting concurrency makes things easier, but we should explicitly point that out in the learning samples/tutorials :)

**Comment by andreasohlund** [comment]
PR raised https://github.com/Particular/NServiceBus/pull/4712

If no one objects by the end of today we'll merge and proceed with the release of core 6.3.0

**Comment by SimonCropp** [comment]
@andreasohlund don't some samples require concurrency?

**Comment by SimonCropp** [comment]
Eg https://docs.particular.net/samples/throttling/

**Comment by andreasohlund** [comment]
We would just configure those samples explicitly to a higher value?

**Comment by SimonCropp** [comment]
Ok. Then i have no objections

**Comment by timbussmann** [comment]
as from the discussion with @andreasohlund and @danielmarbach I think there are two "contradicting" arguments:
* Limiting concurrency removes some complexity, makes the code more predictable and would (imho) be valuable for complete beginners (enough other concepts and APIs to grasp) and for demoing purposes (more predicable, e.g. nicer console outputs or breakpoint hits)
* Limiting concurrency moves the transport further away from the production ready transports and you can easily run into unexpected behavior once you switched over from the learning transport. It might give users the impression, production transports will exactly behave as the learning transport.

Personally, I think the value of "quick successes" without struggling with more complex topics as well as nicer behavior on demo/showcase solutions outweighs the downside of the "learning vs. production transport gap". In workshops there would be a nice path of "leveling up to the next complexity level" by increasing concurrency once attendees are familiar with the NSB API.

**Comment by DavidBoike** [comment]
:+1: for 1 by default.

**Comment by SeanFeldman** [comment]
👍 to keep it 1 by default.

Let learning and F(airy)5 experience gradually build up confidence in the basics of NSB and then the real transport will add enough challenge later.

**Comment by mauroservienti** [comment]
Starting with 1 as default and making it tweakable to whatever makes all learning scenarios possible and makes also for a good learning curve.

:+1:
