### ISSUE TITLE
Learning transport can deadlock under load

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4720]
Sometimes the receiver might get

```
System.IO.IOException occurred
  HResult=0x80070020
  Message=The process cannot access the file because it is being used by another process.
```

when trying to process the file due to the sender still being writing to it. This causes the BeginTransaction to throw and since we run with concurrency 1 this locks the receiver.

**Comment by bording** [comment]
Fixed in the 6.3.1 release.
