### ISSUE TITLE
Can't run Acceptance Tests in parallel, ContextAppenderFactory assumes sequential test runs

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus#4727]
`ContextAppenderFactory` manages a single static instance of `ScenarioContext` - see [ContextAppenderFactory.cs.](https://github.com/Particular/NServiceBus/blob/d462080b0efa6609f0f92d4e192d760142ac47c2/src/NServiceBus.AcceptanceTesting/ContextAppenderFactory.cs) This prevents us from being able to run Acceptance Tests in parallel reliably.

It looks like it's done this way because `ILog`s are usually accessed from a static context.

**Comment by danielmarbach** [comment]
@ahofman Correct. Unfortunately, we haven't come up yet with a good and reliable way to initialize the static loggers so that the tests can be run in parallel. TBH we didn't invest a lot so far.

**Comment by ahofman** [comment]
If we could take a dependency on NUnit, we could potentially use its static TestContext (https://github.com/nunit/docs/wiki/TestContext) i.e., maintain a static map of TestContext Ids to ScenarioContexts. The obviois downside here is the additional dependency on NUnit.

**Comment by timbussmann** [comment]
thanks for your suggestions @ahofman, it might be worth to look a bit closer on how to solve this, but I think there is a very high chance that this isn't the only blocker to run acceptance tests in parallel, although this heavily depends on the selected transport & persistence configuration. But e.g. some transport options currently don't provide fine grained "test scoped" cleanup mechanisms, making parallel execution impossible. We should indeed check what blockers are currently preventing us from running the acceptance tests in parallel, as a faster execution would definitely be desirable.

**Comment by bording** [comment]
Fixed by #4780.
