### ISSUE TITLE
SendOnlyBus doesn't set CurrentPrincipal

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4733]
Originally raised https://groups.google.com/forum/#!topic/particularsoftware/kS762_9n9no

There is a behaviour difference between v5 and v6 when it comes to setting the Thread.CurrentPrincipal

## v5

Setting the principal is done in `UnicastBus.Start` with  `AppDomain.CurrentDomain.SetPrincipalPolicy(PrincipalPolicy.WindowsPrincipal)` the implications are the following

### Bus

In a started bus the `SetPrincipalPolicy` call is executed. Whenever [`Thread.CurrentPrincipal`](https://referencesource.microsoft.com/#mscorlib/system/threading/thread.cs,1358) is accessed the WindowsPrincipal will be returned.

### SendOnly bus

Since this bus will not be started `SetPrincipalPolicy` will never be called. Therefore the empty GenericPrincipal will be set. 

Thread.CurrentPrincipal is used by [`WindowsIdentityEnricher`](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Impersonation/Windows/WindowsIdentityEnricher.cs#L11) and added to the header `Headers.WindowsIdentityName`

### Full endpoint

We always call start, therefore, the WindowsPrincipal will be set

### Send only

We always call start, therefore, the WindowsPrincipal will be set

Identity enrichment for headers has [been removed](https://github.com/Particular/NServiceBus/commit/47f2455916a67cf04699bb2bda64ee3cf0183e22)

## Questions / Thoughts

We explicitly removed the header population. I don't think we have thought about the Behaviour difference when it comes to setting Thread.CurrentPrincipal. Since the change was done in a major I'm leaning towards leaving it as is since there is a workaround (the user can set the principal on the appdomain to whatever they like) after the endpoint is started.

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers thoughts?

**Comment by SimonCropp** [comment]
some more context 

 * https://docs.particular.net/nservicebus/upgrades/5to6/messaging#remove-winidname-header
 * https://docs.particular.net/samples/username-header/

**Comment by timbussmann** [comment]
the described behavior rather sounds like a bug in v5 when using send-only endpoints? Why would you expect send-only endpoints show a different behavior than regular endpoints regarding `CurrentPrincipal`?

**Comment by andreasohlund** [comment]
What's @timbussmann said. I'd say we just doco this (if needed) since the v6 behavior seems to be the correct one?

**Comment by danielmarbach** [comment]
I agree with both of you

**Comment by timbussmann** [comment]
@andreasohlund I'm having trouble to find an appropriate place for that doc? (also I think we rarely document bugs?)

**Comment by andreasohlund** [comment]
I was thinking upgrade guide?  But if we see this as a bug perhaps raise a bug that we close as fixed in v5?

**Comment by timbussmann** [comment]
I think the @Particular/nservicebus-maintainers concluded on yesterday's sync that the v5 send-only endpoint's behavior is a bug, so I'd say let's close?
