### ISSUE TITLE
Prevent internal container registrations for message mutators

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4738]
Since we now have explicit api's for registration

Obsolete this
```
endpointConfiguration.RegisterComponents(
registration: components =>
{
    components.ConfigureComponent<MyMutator>(DependencyLifecycle.InstancePerCall);
});
```
since we now have this
```
endpointConfiguration.RegisterMessageMutator(new MyMutator());
```

**Comment by andreasohlund** [comment]
Are you saying to obsolete the entire `ConfigureComponent` ? (or is it possible to only obsolete for  `ConfigureComponent<IMessgeMutator>` ? )

**Comment by SimonCropp** [comment]
i was thinking log an error or warning when we detect someone registering with `ConfigureComponent<IMessgeMutator`

**Comment by andreasohlund** [comment]
👍 then we should do the same for IUnitsOfWork

or even better deprecate IUnitsOfWork in favor of https://github.com/Particular/NServiceBus/issues/4493

**Comment by andreasohlund** [comment]
I think we should throw btw

**Comment by SimonCropp** [comment]
happy with a throw

**Comment by andreasohlund** [comment]
@SimonCropp changed the title of the issue

**Comment by andreasohlund** [comment]
We can't do this for the UoW since we have no code first api to register them. Title updated

**Comment by andreasohlund** [comment]
Decided to skip this for v7 and instead make sure that we stop using the DI way and also to not guiding users towards this until we can [remove DI usage for mutators completely ](https://github.com/Particular/NServiceBus/issues/4982)

See https://github.com/Particular/NServiceBus/pull/4978#issuecomment-332515975

**Comment by andreasohlund** [comment]
Closing in favor of https://github.com/Particular/NServiceBus/issues/4738
