### ISSUE TITLE
exclude All_saga_entities_in_acceptance_tests_should_have_virtual_properties from acceptance tests

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4762]
it is only verifying that the other tests are written correctly and make no sense to exist in the actual package

**Comment by SimonCropp** [comment]
same with All_sagas_and_entities_should_have_unique_names

**Comment by bording** [comment]
What about for tests written by in the downstream repos? Wouldn't we want to enforce these rules on those tests as well?

**Comment by SimonCropp** [comment]
but tests written by downstreams do not necessarily have those constraints. eg the only downstream that cares about virtual is nhibernate.

**Comment by timbussmann** [comment]
makes sense to me. As it's more effort to exclude tests with the new content packages, should we add this to the v7 milestone? (seems to be a trivial change anyway)

**Comment by bording** [comment]
This will be addressed as part of #4457.
