### ISSUE TITLE
MSMQ requires error queue configuration for send-only endpoints

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus#4769]
## Who's affected
Anyone using the MSMQ transport with send-only endpoints on NServiceBus 6.3.

## Symptoms
After upgrading to 6.3,  users need to configure a error queue unnecessarily.

## Original bug report
This is a change in behavior and has broken the Azure dynamic host, which launches the endpoint as a sendonly endpoint.

**Comment by boblangley** [comment]
This line should include a check to see if the endpoint is not configured as a SendOnly endpoint: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs#L35

**Comment by SeanFeldman** [comment]
I've raised a PR again MSMQ transport: https://github.com/Particular/NServiceBus.Transport.Msmq/pull/25

**Comment by andreasohlund** [comment]
Would we classify this as a patch?

**Comment by SeanFeldman** [comment]
I'd say so. Qualifies at least a [Minor Patch criteria](https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/triage.md#patch-criteria) as azure multi host would require to take the host offline, add an error queue configuration and redeploy. That's quite a workaround 😃

**Comment by andreasohlund** [comment]
How can the azure multi host be affected by a msmq bug?

**Comment by yvesgoeleven** [comment]
@andreasohlund as discussed on slack, it's probably because msmq is on by default as the host doesn't have a need for a transport

**Comment by bording** [comment]
Reopening since we still need to consider a 6.3.x patch.

**Comment by SimonCropp** [comment]
wouldnt this always fail at startup? in which case it could never get to production? and if so not a back port

**Comment by bording** [comment]
@SimonCropp It's not a backport. It's a fix to a regression introduced in 6.3.0

**Comment by SimonCropp** [comment]
@bording ok thanks for the clarification

**Comment by bording** [comment]
Fixed by #4784
