### ISSUE TITLE
Poison message in MSMQ fails to be sent to remote error queue and is retried indefinitely

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4792]
When a message has corrupt headers and a remote error queue has been configured, the `MovePoisonMessageToErrorQueue` fails, which results in the whole operation being rolled back. **The message is retried indefinitely.**

## Who's affected
Anyone using the MSMQ transport with a remote error queue configured.

## Symptoms
- You see repeated log entries for the same message indicating that it has corrupted headers.
- The message in the log entries never appears in the error queue.
- If the concurrency of the endpoint is set to 1, the endpoints stops processing additional messages.

## Backported to

* [6.2.4](https://github.com/Particular/NServiceBus/releases/tag/6.2.4)
* [6.1.8](https://github.com/Particular/NServiceBus/releases/tag/6.1.8)
* [6.0.10](https://github.com/Particular/NServiceBus/releases/tag/6.0.10)
* [5.2.22](https://github.com/Particular/NServiceBus/releases/tag/5.2.22)

## Original bug report

When a message has corrupt headers and a remote error queue has been configured the `MovePoisonMessageToErrorQueue` fails which results in the whole operation to be rolled back. **The message is retried indefinitely.**

- This works correctly for local error queues
- Audit forwarding to remote audit queue works correctly.
- Processing errors are correctly moved to the remote error queue
- This is reproduced in an environment of two machines in the same Active Directory

The log message formatting at the following line is suspicious:
- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs#L95

```c#
var error = $"Message '{message.Id}' is classfied as a poison message and will be moved to '{errorQueue.QueueName}'";
```

This is using `errorQueue.QueueName` and different from the way the RecoverabilityExecutor logs the queue as that is based on the configured queue as a string type. This could explain why audit forwarding and regular error processing still works.

```
System.Messaging.MessageQueueException (0x80004005): The specified format name does not support the requested operation. For example, a direct queue format name cannot be deleted.\r\n   at System.Messaging.MessageQueue.GenerateQueueProperties()\r\n   at System.Messaging.MessageQueue.get_QueuePath()\r\n   at System.Messaging.MessageQueue.get_QueueName()\r\n   at NServiceBus.ReceiveStrategy.MovePoisonMessageToErrorQueue(Message message, MessageQueueTransactionType transactionType) in C:\\BuildAgent\\work\\3206e2123f54fce4\\src\\NServiceBus.Core\\Transports\\Msmq\\ReceiveStrategy.cs:line 95\r\n   at NServiceBus.TransactionScopeStrategy.<ReceiveMessage>d__1.MoveNext() in C:\\BuildAgent\\work\\3206e2123f54fce4\\src\\NServiceBus.Core\\Transports\\Msmq\\TransactionScopeStrategy.cs:line 36
```

Error information logged by NServiceBus:
```
2017-06-06 08:46:19.630 WARN  NServiceBus.ReceiveStrategy Message 'b644ac05-920c-42ba-ba3f-4d4777ae7afe\478520848' has corrupted headers
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.MsmqUtilities.DeserializeMessageHeaders(Message m) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 111
   at NServiceBus.MsmqUtilities.ExtractHeaders(Message msmqMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 50
   at NServiceBus.ReceiveStrategy.TryExtractHeaders(Message message, Dictionary`2& headers) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\ReceiveStrategy.cs:line 70
```

Error information logged by logging AppDomain.FirstChanceException :
```
2017-06-06 08:46:19.666 DEBUG FirstChanceException Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.MsmqUtilities.DeserializeMessageHeaders(Message m) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 111
```

Correctly working error logic for normal processing errors:
```
2017-06-06 08:33:06.991 ERROR NServiceBus.RecoverabilityExecutor Moving message '09281c83-7371-4fa5-b59d-a78a006bbc7a' to the error queue 'error@demo.corp.nbraceit.com' because processing failed due to an exception:
```

Corrupt message to reproduce this:

 - [MovePoisonMessageToErrorQueue.zip](https://github.com/Particular/NServiceBus.Transport.Msmq/files/1054074/MovePoisonMessageToErrorQueue.zip)

### References

- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs#L95
- https://github.com/Particular/NServiceBus.Transport.Msmq/blob/develop/src/NServiceBus.Transport.Msmq/ReceiveStrategy.cs#L95
- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Recoverability/RecoverabilityExecutor.cs#L84

**This issue is a copy of https://github.com/Particular/NServiceBus.Transport.Msmq/issues/26**

**Comment by bording** [comment]
Fixed by #4791
