### ISSUE TITLE
EnclosedMessageTypes header might contain types in wrong order

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4794]
`XmlDeserialization.FindRootTypes` expects the types in the `EnclosedMessageTypes` to be in a particular order: types that are part of same hierarchy of inheritance should be ordered from the most concrete to the most abstract.

`SerializeMessageConnector.SerializeEnclosedMessageTypes` takes the (ordered) type hierarchy and runs through deduplication using a `HashSet` which potentially disturbs the order. As a result, depending on the implementation of the `HashSet`, the resulting order of types in the header might not be correct according to XmlSerializer's expectations.

### Impact assessment

This is *not* a message loss scenario because the faulty message will go to the error queue. Because we did not get any reports of this problem happening in the wild I'd say we can wait with the fix till V7 -> this is not a patch.

**Comment by SzymonPobiega** [comment]
Looking at the [reference source](http://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,188b8f94f8fc999b,references) and having done some tests, it does look like HashSet indeed preserves the order assuming nothing is removed from the set. In this case each added item gets a new slot and the list of free slots is kept empty. This is preserved even is the set is forced to increase the capacity.

**Comment by andreasohlund** [comment]
So this is a non issue then?

**Comment by SzymonPobiega** [comment]
@andreasohlund well, we're still depending on the implementation details of HashSet right now so I'd say we should fix it but it does not have a high priority.

**Comment by andreasohlund** [comment]
Agreed, flagged this as a bug.

@Particular/nservicebus-maintainers thoughts on prio? (v7?)

**Comment by timbussmann** [comment]
looking at the code, I'm not sure how the deduplication would really be necessary in the first place. Even if there would be the same type present twice, could this have any impact (besides of using up more space for the headers)?

**Comment by SzymonPobiega** [comment]
@timbussmann for sure duplicate items would be better than wrong order as the deserialization depends on the order.

**Comment by danielmarbach** [comment]
@timbussmann the space is crucial especially for transports like ASQ and ASB where you have very limited message size
