### ISSUE TITLE
DataBusProperty not supported by some serializers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4805]
since it doesnt have a default constructor. 

eg Jil

**Comment by andreasohlund** [comment]
How urgent would we say this is? Perhaps we should try to get the data bus out of the core/killed instead?

**Comment by SimonCropp** [comment]
@andreasohlund either way it will still be broken when moved out. so fix it now of fix it when it is moved out, is there any difference?

**Comment by andreasohlund** [comment]
I was thinking of completely killing it but that's to agressive I guess

**Comment by SimonCropp** [comment]
> I was thinking of completely killing it but that's to agressive I guess

More than happy with that as an outcome. but we have a tendency to take many years to kill things. if that is the case here we either need to document that the databus does not support all serializers or fix it

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers is there any harm adding a default constructor to DataBusProperty for v7?

**Comment by bording** [comment]
Seems like a reasonable way to deal with this until we decide what do with the data bus in general.
