### ISSUE TITLE
Invalid tests

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4806]
When tried to [upgrade ASB](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/574) to the latest Core and NUnit, specific tests started failing with consistent repetition.

After investigation with @bording we've concluded that this was specific to ASB and NUnit. NUnit has changed their implementation between version 3.6.1 and 3.7.0 which exhibited that behavior.

I've raised an [issue with NUnit](https://github.com/nunit/nunit/issues/2275) and apparently, the scenario where an assertion is used on a thread other than test thread would never work. I've confirmed that with ASB and @bording has confirmed the same with RabbitMQ. The failure that tests are demonstrating is not the result of the assertion failure, indicating that [these tests](https://builds.particular.net/viewLog.html?buildId=221371&buildTypeId=NServiceBusAzure_NServiceBusAzureServiceBus_3RunAcceptenceTestsWithForwardingTop) might be wrong to begin with. All these tests make assertions on a different thread.

**Tests in question**

- When_a_replymessage_is_audited.Should_audit_the_message 	
- When_sending_to_another_endpoint.Should_receive_the_message 	
- When_publishing.Should_be_delivered_to_all_subscribers 	
- When_saga_is_mapped_to_complex_expression.Should_hydrate_and_invoke_the_existing_instance 	
- ~~When_subscribing_to_base_and_derived_polymorphic_events_with_forwarding_topology.Should_handle_- When_message_is_available.Should_invoke_on_message~~

**Verification**

Replace assertion with `Assert.IsTrue(false)` - the tests will fail not because of the assertion, but because the message will be moved to the error queue.

**Comment by danielmarbach** [comment]
Sent in https://github.com/Particular/NServiceBus/pull/4809

Was not able to find `When_subscribing_to_base_and_derived_polymorphic_events_with_forwarding_topology` and assumed that one comes from ASB ;)

**Comment by bording** [comment]
Fixed in #4809
