### ISSUE TITLE
TTBR Diagnostics header being used improperly

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#4807]
While investigating the recent failures of the `When_message_with_TimeToBeReceived_fails.Should_not_honor_TimeToBeReceived_for_error_message` test, with the learning transport, I've come to the conclusion that we've got a problem in how TTBR is being handled in V6.

The way V6 is intending to inform the transports that a message needs to be sent with TTBR is through adding the `DiscardIfNotReceivedBefore` delivery constraint to the message. V6 also introduced a TTBR header. This header is only supposed to be used for diagnostic purposes.

However, after looking through the code of the transports, I see that we've got some transports that are doing the wrong thing and are inspecting the header value instead of looking for the delivery constraint.

By looking at the header instead of the constraint, this means that messages could have a TTBR set on them when they are not supposed to, for example when moving a message to the error queue. This is because we copy headers when creating the new outgoing message.

NOTE: I've gone back and looked at V5, and this is not a problem there. In V5 there was no TTBR header, and the TTBR value was communicated to the transports via the `TransportMessage` class. Core properly clears out that value before forwarding a message to the error queue, etc.

Based on my initial research, here's the current state of the transports:

- MSMQ: constraint
- RabbitMQ: constraint
- ASB; header
- ASQ: constraint (but header is being used [somehow](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/7e35419d5ae9cc225392308b6ee7d344bf99b276/src/Transport/DefaultMessageEnvelopeUnwrapper.cs#L37) also?
- SQL: header
- Learning: header

The learning transport has and additional issue here in that it's looking at the header value in the message pump upon receiving instead of stamping the message in some way when sending.

So to fix this, here's what I propose;
- The affected transports need to update to only use the delivery constraint and not the header
- We should either drop the header from core, or change it be some sort of diagnostics header.

The current test is also not actually testing this behavior properly, so we need to come up with a better test as well.

Transport maintainers, please validate my assessment above about the method being used to read the TTBR value.

@Particular/msmq-transport-maintainers 
@Particular/rabbitmq-transport-maintainers 
@Particular/azure-maintainers 
@Particular/sqlserver-transport-maintainers

**Comment by andreasohlund** [comment]
Slightly related: we have plans to deprecate `HandleCurrentMessageLater` https://github.com/Particular/NServiceBus/issues/4110

Would it help in anyway to go ahead in v7?

**Comment by adamralph** [comment]
👍 from me for the problem analysis and proposed solutions. If the header is indeed being used for diagnostics, then I favour the method of changing it to be explicitly named as a diagnostic header. However, could that change introduce wire incompatibility somehow?

**Comment by bording** [comment]
@adamralph As far as I can tell, there should be no wire compat issues here. The header didn't exist until V6, and the transports (aside from the learning transport) are only looking for it at sending time, not receiving, so it being on the message or not shouldn't make a difference.

**Comment by bording** [comment]
@andreasohlund Removing `HandleCurrentMessageLater` in V7 doesn't really change anything about the current state of this bug. The transports looking at the header need to be updated.

**Comment by SeanFeldman** [comment]
ASB v7 (Core v6) is indeed using the header to determine TTBR rather than use `DiscardIfNotReceivedBefore` delivery constraint. Based on priority of this fix, we'll fix it.
(ASB specific issue https://github.com/Particular/NServiceBus.AzureServiceBus/issues/577 was raised)

**Comment by adamralph** [comment]
@bording thanks for clarification. So all in all, LGTM.

**Comment by tmasternak** [comment]
@bording Your description is accurate in regards to [SqlServer](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Queuing/MessageRow.cs#L30)

**Comment by dbelcham** [comment]
PlatDev issue for this closed so closing this.
