### ISSUE TITLE
Ensure saga data is not shared between sagas

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4811]
Context: https://github.com/Particular/ServiceControl/issues/977#issuecomment-310358526

The current saga validation does not check if saga data is shared between saga classes that inherit from a single base class. If this happens, the effects are following:
 * Both saga instances share the data.
 * Both saga instances are invoked so the downstreams see messages coming from two sagas, but these messages carry the same saga id.

The saga validation could should be extended to cover this issue to not let customers fall into this trap.

**Comment by bording** [comment]
@SzymonPobiega I believe this would be covered by #4596?

**Comment by SzymonPobiega** [comment]
@bording true, but #4596 has much broader scope. We already do some crazy checks on sagas (e.g. must have at lest one IAmStartedBy) so adding one more would not cost us much while it would save customers nasty data corruption bugs.

**Comment by SzymonPobiega** [comment]
Now when I think about it, it might even qualify as a `critical`. If you write code as in the lined issue in ServiceControl repo you'll be corrupting your data without knowing about it. NServiceBus will run fine using a single saga data entity for two logically distinct sagas.

**Comment by dbelcham** [comment]
@SzymonPobiega is there any influence on this by how different persisters implement their saga stuff?

**Comment by SimonCropp** [comment]
@SzymonPobiega so if this was in core then we could get rid of this in the sql persistence https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/SqlPersistence/Saga/SagaInfoCache.cs#L54  ?

**Comment by SzymonPobiega** [comment]
Yeah. In my opinion it makes sense. 

@dbelcham It might be but I haven't checked. For sure `InMemoryPersistence` is not affected because it fails on some internal concurrency checks.

**Comment by Scooletz** [comment]
Azure maintainer hat on. @SzymonPobiega 
If you base security on 

> For sure InMemoryPersistence is not affected because it fails on some internal concurrency checks. 

then Azure Storage Persistence is safe as well, because it uses ETags and optimistic concurrency.

**Comment by SzymonPobiega** [comment]
@Scooletz nah. Let me correct myself

> fails on some internal concurrency checks

Means it throws exception where it could actually continue because it is based on the assumption that you can ever touch one saga data once during a single request processing. Azure Storage persistence does not have this limitation. It will happily create and then load & updated the same saga entity during one request. But it is not Azure Storage bug, it is a core issue. Azure Storage just fulfils the core contract more faithfully than InMemoryPersistence.

**Comment by ramonsmits** [comment]
@SzymonPobiega Just to be sure, you are describing this:

```c#

class MySagaData : ContainSagaData {}

class SagaTypeA<MySagaData> : Saga {}
class SagaTypeB<MySagaData> : Saga {}
```

or even more extreme like the following 2 variants:

```c#
class MySagaData : ContainSagaData {}
class MySagaDataEx : MySagaData {}

class SagaTypeA<MySagaData> : Saga {}
class SagaTypeB<MySagaDataEx> : Saga {}
```

```c#
class MySagaData : ContainSagaData {}
class MySagaData1 : MySagaData {}
class MySagaData2 : MySagaData {}

class SagaTypeA<MySagaData1> : Saga {}
class SagaTypeB<MySagaData2> : Saga {}
```

Based on your issue description in both scenarios, different sagas could share the same data entity if the saga entity matches multiple conventions if both sagas act on the same message.

**Comment by SzymonPobiega** [comment]
@ramonsmits honestly I don't remember why I thought it is a bad idea. I doubt it ever happened in real life. And as the issue is quite old, the behavior now could be different and really differ from persister to persister.

**Comment by Scooletz** [comment]
Neither do I @SzymonPobiega
