### ISSUE TITLE
Host identifier information either too specific or too global

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4824]
The host identifier is currently made of:

- endpoint name
- host path
- machine

If you have multiple instances running due to recycling then these individual processes are not identified so it is not possible to correlate issues to a specific instance thus the host identifier is too generic. On the other hand, we do include path info which for a lot of customers pollutes the ServicePulse inactive endpoints view and for this reason, the host identifier is too specific ([besides being a presentation issue](https://github.com/Particular/ServicePulse/issues/469)).

If we want to have host information in there then:

- Why don't we include assembly version info?
- Why don't we include the process id?
- Why don't we just always generate a new guid at endpoint start and include that to distinguish instances?

If this is out of our control then maybe this should be an explicit configuration value just as the endpoint name and critical error handler should be.

**Comment by timbussmann** [comment]
Are these headers used in SC?

> Why don't we include assembly version info?

would that change anything regarding the recycling scenario?

> Why don't we include the process id?

aren't we doing that already? https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/HostInformationFeature.cs#L26

> If this is out of our control then maybe this should be an explicit configuration value just as the endpoint name and critical error handler should be.

endpoint name is a mandatory config options, I assume this isn't what you meant?

**Comment by timbussmann** [comment]
ping @ramonsmits

**Comment by ramonsmits** [comment]
@timbussmann You are right that including assembly version info does not cover recyling detecting. It is more in regards in currently being either to specific or too global. If we include the path, then why not assembly information?

I didn't know we the process id was contained in the message but I don't think it is part of the host identifier when I look at that code. I think only the host ID is used by ServiceControl, would that maybe mean ServiceControl is not using the right data?

What I meant is that the HOST ID must be an explicit configuration option.

**Comment by timbussmann** [comment]
just looked a bit closer, we're setting the processid on the `HostInformation` class, but it seems like those information are never put on any message. Might be worth to add those additional information somehow.

@ramonsmits making the host-id configurable seems like something which could highly confuse users in the first place. Why would you have to configure a host id along with configuring endpoint name and other stuff. Where would that host-id be used? What need the value to look like? It seems to be more reasonable to me to ensure we're creating a useful default value?

**Comment by ramonsmits** [comment]
@timbussmann The issue is that ServiceControl is dependent on the correct info for the host identifier. 

What about not setting the host identifier at all? Make ServicePulse show a message that in order for host information grouping and/or heartbeats to work correctly that the host identifier needs to be set to an appropriate value.

**Comment by timbussmann** [comment]
> The issue is that ServiceControl is dependent on the correct info for the host identifier.

I would assume that the exact value doesn't matter as long as it can match the identifiers?

> Make ServicePulse show a message that in order for host information grouping and/or heartbeats to work correctly that the host identifier needs to be set to an appropriate value.

I think this causes too much effort on too many users to resolve this single scenario you described.

**Comment by ramonsmits** [comment]
> I would assume that the exact value doesn't matter as long as it can match the identifiers?

Not sure what you mean by that @timbussmann , it is used by SC/SP for presenting the status, it can lead to 'dead' instances without nothing what instances because it is only presenting the endpoint name and not the host id value or any of the source values to generate it

The thing is that the current way of reporting is not clear to our users. They don't know anything about host id but do see strange issues with dead endpoints being reported but they don't know why while the cause is because we hide the host ID generation and host ID usage for them which IMHO is wrong.

**Comment by timbussmann** [comment]
@ramonsmits I'm a bit confused, in the initial description you stated
> If you have multiple instances running due to recycling then these individual processes are not identified so it is not possible to correlate issues to a specific instance thus the host identifier is too generic.

so, it seems to me that 
> it can lead to 'dead' instances without nothing what instances because it is only presenting the endpoint name and not the host id value or any of the source values to generate it

is an entirely different scenario, would that fit better in a dedicated issue?

**Comment by timbussmann** [comment]
@ramonsmits there are still many open questions about this issue. Do you want to follow up or close this issue instead?

**Comment by ramonsmits** [comment]
@timbussmann As in the original description I'm making the case that the current host identifier is either to specific or too generic. We more or less have choosen a default that does not play nice with our platform. 

At the end I'm proposing that is we cannot make this decision to make the host ID an explicit choice.

**Comment by andreasohlund** [comment]
Since the HostId is only used by SC I wonder if we can make it a mandatory setting for the plugins and obsolete the core api?

cc @Particular/servicecontrol-maintainers

**Comment by WilliamBZA** [comment]
Which plug ins @andreasohlund? Are you referring to hearbeats/audits/metrics?

Those aren't the only places where messages wind up in SC, what about messages that end up in the error queue? That comes directly from core and needs to have the host ID

**Comment by SzymonPobiega** [comment]
Host Id is also used in the queue length calculation if I remember correctly (cc @tmasternak @Scooletz )

**Comment by andreasohlund** [comment]
Didn't think about the error and audit queue (although host id could be optional), I retract my idea to pull this out into the SC plugins.

**Comment by WilliamBZA** [comment]
As an aside: yet another ID has been [introduced in the metrics plugin](https://github.com/Particular/NServiceBus.Metrics/blob/develop/src/NServiceBus.Metrics/MetricsFeature.cs#L359)

**Comment by andreasohlund** [comment]
@WilliamBZA what's the semantics of that new id?

**Comment by tmasternak** [comment]
>Host Id is also used in the queue length calculation if I remember correctly (cc @tmasternak @Scooletz )

Almost correct. See below.

**Comment by tmasternak** [comment]
> @WilliamBZA what's the semantics of that new id?

@andreasohlund  This was driven by the fact that in the monitoring capability we needed two things:
 * Unique Id for an instance
 * Meaningful instance name

We could use `HostId` and `HostDisplayName` in most of the cases except for `Azure`. For `Azure` the `HostId` is set to `RoleId` (e.g. `1`) and `HostDisplayName` is set to `RoleName` (`Finance`). In order to prevent custom logic on the processing side that would depend on the hosting we decided to introduce `InstanceId` value that needs to be both unique and display friendly that is meant to be used in `Azure` hosting scenarios.

**Comment by andreasohlund** [comment]
Just noting that the endpoint doesn't actually have to be aware of the hostid since we have extension points that would allow the host to hook into the error and audit pipeline and enrich those messages with host id etc.

Would we consider the metrics and SC plugins to "attach to" the endpoint instance or the host?

Ie in a world where the host is explicit would we have:

```
var endpoint = new EndpointConfiguration("sales", new MsmqTransport())
var host = new WindowsServiceHost(ServiceBase);

host.EnableHeartbeats();

host.Start(endpoint);
``` 
OR

```
var endpoint = new EndpointConfiguration("sales", new MsmqTransport())
endpoint.EnableHeartbeats();
var host = new WindowsServiceHost(ServiceBase);

host.Start(endpoint);
``` 

My hunch is that it would be attaching to the host? (at least in this example with heartbeats)

**Comment by tmasternak** [comment]
> My hunch is that it would be attaching to the host? (at least in this example with heartbeats)

👍

**Comment by mikeminutillo** [comment]
> My hunch is that it would be attaching to the host? (at least in this example with heartbeats)

Do we envisage a scenario where the host contains 2 endpoints and only one of them sends data to the monitoring instance? Or a case where the host contains 2 endpoints and they send data to different monitoring instances?

If not, then this belongs to the host.

Do we see a scenario where we host two instances of the _same_ endpoint in a single host? If so, that's what an `InstanceId` is and how it is different to `HostId`/`HostName`.

**Comment by andreasohlund** [comment]
>Do we envisage a scenario where the host contains 2 endpoints and only one of them sends data to the monitoring instance?
>Or a case where the host contains 2 endpoints and they send data to different monitoring instances?

Sounds like edge cases, and we could solve that on the host level with some kind of: `host.Register(endpoint).DisableMonitoring();` api?

>Do we see a scenario where we host two instances of the same endpoint in a single host?

This seems like a possibility to me to support zero downtime deployments where `Sales-v1.0.0` and `Sales-v1.0.1` runs in parallel inside the same host for some period of time until `v1.0.1` is deamed stable. This seems to suggest that we need to take "endpoint version" into account when identifying endpoint instances?

That said would we allow multiple identical instances to run inside the same host? (I think we came up with the concept "compartments" to handle this when this was discussed a while back, compartment == the process/appdomain/etc that is running the specific instance)

**Comment by ramonsmits** [comment]
@WilliamBZA but that new header has a prefix identifying that it is owned by the metrics package. @SzymonPobiega If host ID is required by the queue length calculation wouldn't it be better if it would use its own header for that?

> Do we see a scenario where we host two instances of the same endpoint in a single host? If so, that's what an InstanceId is and how it is different to HostId/HostName.

That is certainly possible when it is hosted within IIS as recycle operations are always overlapping.

**Comment by andreasohlund** [comment]
@ramonsmits with the new stuff added by the launch wave is this still an issue?

**Comment by timbussmann** [comment]
any conclusions we can extract from this issue?
