### ISSUE TITLE
Timeout manager  TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages and MaxNextRetrievalDelay behavior improvement

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4833]
`TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages` can be called to adjust the circuit breaker duration. The issue is that if timeout storage is not available that by default it can take up to 3 minutes before the circuit breaker trips (1 minute between polls + 2 minutes for the circuit breaker duration).

- https://github.com/Particular/NServiceBus/blob/6.3.4/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs#L149

I configured it to 15 seconds but due to the 1-minute poll interval, this would take max 1 minute + 15 seconds, or on average 45 seconds which is not what I expected after configuring this.

Should the max poll interval be customizable or maybe not allow TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages to be set to less then `MaxNextRetrievalDelay`?

**Comment by bording** [comment]
@ramonsmits I'm not sure see the problem yet. If the storage database goes down and comes back up all between a poll interval, from the standpoint of the poller, it never went down, so why should the state of the storage database matter until a poll fails?

If anything I could see adding something to docs to clarify that the circuitbreaker is armed only after a failed polling attempt.

**Comment by timbussmann** [comment]
Also, is there a real need from a production perspective to shut down the endpoint faster in case connection to the timeout manager is lost? From a messaging perspective, this doesn't seem to cause problems?

**Comment by ramonsmits** [comment]
@bording The API allows smaller periods to be configured. As a use I would expect that if the database is down for longer than the configured period (as I tried to configure 15 seconds) that the endpoint would fail but that didn't happen. I purposely wanted it to fail faster than the default of 2 minutes.

@timbussmann I don't know if this can cause problems besides the behavior that I describe in this issue.

**Comment by timbussmann** [comment]
should we document that minimum value is one minute instead?

**Comment by ramonsmits** [comment]
Behavior is going to be documented, closing this.
