### ISSUE TITLE
Injected IBuilder is always root container

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4837]
When injecting `IBuilder` to resolve dependencies manually, the `IBuilder` is always the root builder. Depending on the container, this can cause the builder to not resolve dependencies in UnitOfWork scope correctly.

This is a repro test:

        [Test]
        public void When_using_injected_builder_to_resolve_uow_dependencies()
        {
            var builder = new CommonObjectBuilder(new LightInjectObjectBuilder());

            IBuilder iBuilder = builder;

            // this is configured by NServiceBus.Core:
            builder.ConfigureComponent(b => iBuilder, DependencyLifecycle.SingleInstance);

            builder.ConfigureComponent<ClassResolvingItsDependencies>(DependencyLifecycle.InstancePerCall);
            builder.ConfigureComponent<UowDependency>(DependencyLifecycle.InstancePerUnitOfWork);

            ClassResolvingItsDependencies c2;
            ClassResolvingItsDependencies c3;

            var c1 = builder.Build<ClassResolvingItsDependencies>();

            using (var childBuilder = builder.CreateChildBuilder())
            {
                c2 = childBuilder.Build<ClassResolvingItsDependencies>();
                c3 = childBuilder.Build<ClassResolvingItsDependencies>();
            }

            Assert.AreNotSame(c1, c2);
            Assert.AreNotSame(c2, c3);

            Assert.AreSame(c2.dependency, c3.dependency);

            Assert.AreEqual(2, UowDependency.InstanceCounter); // 1
            Assert.AreNotSame(c1.dependency, c2.dependency); // fails
        }

        class ClassResolvingItsDependencies
        {
            public ClassResolvingItsDependencies(IBuilder builder)
            {
                dependency = builder.Build<UowDependency>();
            }

            public readonly UowDependency dependency;
        }

        class UowDependency
        {
            public UowDependency()
            {
                Interlocked.Increment(ref InstanceCounter);
            }

            public static int InstanceCounter;
        }

This test currently fails on core with the LightInject implementation. Daniel made an attempt at fixing this here https://github.com/Particular/NServiceBus/pull/4835 but this approach seems to cause weird issues with rabbitmq for example.

**Comment by WilliamBZA** [comment]
Duplicate of https://github.com/Particular/NServiceBus/issues/4744?

**Comment by timbussmann** [comment]
@WilliamBZA not exactly. They are very similar but #4744 relates to the Func<IBuilder, T> factory while this bug is about injecting `IBuilder` directly.

**Comment by andreasohlund** [comment]
I assume this is still true even after the switch to MS DI?

**Comment by timbussmann** [comment]
we'd have to test this, the new API providing the builder is coming directly from the MS API, so it might actually be correct. I can try to run those tests against latest core.

**Comment by andreasohlund** [comment]
That would be awesome!

**Comment by timbussmann** [comment]
the test is green using latest core master and changing the API using `IServiceCollection`/`IServiceProvider` instead of `IBuilder`.

This can be closed as "fixed".

**Comment by danielmarbach** [comment]
We are about to release a fix for this in version 7.7.4 and 7.6.3
