### ISSUE TITLE
LightInject disposes components multiple times

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4838]
It seems like with the current way of registering interfaces of a concrete type, it can cause the concrete type to be disposed multiple times. Given:

    interface ISomeService
    {
        
    }

    class TransientServiceWithInterface : IDisposable, ISomeService
    {
        public TransientServiceWithInterface()
        {
            Interlocked.Increment(ref instanceCounter);
        }

        public static int instanceCounter;
        public static int disposalCounters;
        public void Dispose()
        {
            Interlocked.Increment(ref disposalCounters);

        }
    }

the following test repros the issue:

        [Test]
        public void disposalTest()
        {
            var servicecontainer = new ServiceContainer();

            using (var rootScope = servicecontainer.BeginScope())
            {
                servicecontainer.Register(sf => new TransientServiceWithInterface(), new PerRequestLifeTime());
                servicecontainer.Register(typeof(ISomeService), sf => sf.GetInstance(typeof(TransientServiceWithInterface)), new PerRequestLifeTime(), typeof(TransientServiceWithInterface).FullName);

                using (var scope = servicecontainer.BeginScope())
                {
                    var instance = servicecontainer.GetInstance<ISomeService>();
                }

                Assert.AreEqual(1, TransientServiceWithInterface.instanceCounter); // 1
                Assert.AreEqual(1, TransientServiceWithInterface.disposalCounters); // 2 !
            }
        }

I think we need to align whether that behavior is an issue or not. Applying general disposal best-practices, dispose should be able to handle multiple calls properly, but I'm not sure we can safely assume this is a non-issue therefore.

Also, I wonder whether there is any way to change this behavior at all using LightInject. Maybe @seesharper could be of help on this as well.

**Comment by timbussmann** [comment]
@Particular/container-maintainers do other containers show this behavior as well?

**Comment by mauroservienti** [comment]
I don't have an answer for you @timbussmann, even if I'm a maintainer. What I can say is that the `Dispose` implementation should be designed so that multiple calls are not a problem, at least that's what I remember when I saw the dispose pattern the first time.

**Comment by seesharper** [comment]
We could change this change this behavior in LightInject without breaking anything even though Dispose implementations should be idempotent. We currently keep a list of tracked instances using an IList&lt;T&gt;. We could change this to use a HashSet&lt;T&gt; with a reference equality comparer.  We are changing behavior, but the chance of someone relying on the dispose method to be called multiple times, should be relatively small. So one the one hand we are fixing non-idempotent dispose implementations, but on the other hand, LightInject should maybe not track the same instance multiple times.

**Comment by bording** [comment]
> but on the other hand, LightInject should maybe not track the same instance multiple times.

@seesharper I agree, it doesn't make sense to track the same instance multiple times. If you'd be able to make the change to the HashSet for tracking, I think that would be the ideal solution.

**Comment by timbussmann** [comment]
I like @seesharper solution as well. While in general it shouldn't be an issue if implemented "correctly", there is still a good chance that this can surprise someone registering their disposable service with NSB. I guess we need to make sure that we pull over the changes made in seesharper/LightInject#368 into our sources before closing this issue.
