### ISSUE TITLE
Does the double opt in test make sense in the core?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4853]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Core/Outbox/When_outbox_double_optin_found.cs

Seems it is verifying behaviour that no longer exists in the core? and perhaps should be moved out?

**Comment by timbussmann** [comment]
yeah that should be removed. Both tests in this folder don't seem to run as the core doesn't match the tests requirements anyway.
