### ISSUE TITLE
EndpointConfiguration should throw InvalidOperationException if modified after endpoint create/start

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4873]
I tried to extend the pipeline but my behavior was not invoked and I didn't understand why it wasn't invoked. The issue was that I registered the behavior  **after** the endpoint was already created. I think **any** modification to an `EndpointConfiguration` that has already passed to `Endpoint.Create` or `Endpoint.Start` should result in an `InvalidOperationException`.

```c#
var endpointConfiguration = new EndpointConfiguration("Samples.Metrics.Tracing.Endpoint");
endpointConfiguration.UsePersistence<LearningPersistence>();
endpointConfiguration.UseTransport<LearningTransport>();
var endpointInstance = await Endpoint.Start(endpointConfiguration)
    .ConfigureAwait(false);

// Following line should throw InvalidOperationException 
endpointConfiguration.Pipeline.Register(new PeekExtensionsBehavior(),"Test");
```

**Comment by timbussmann** [comment]
I kinda like this idea. Although this might become quite noisy to implement considering all the extension methods based on `EndpointConfiguration` and it's sub-config classes. Also this would need to be respected from downstream config API.

**Comment by ramonsmits** [comment]
Configuration settings are stored via the settings object right? By having a validation on that it would probably solve this for all variations.
