### ISSUE TITLE
Extend Your Trial - warning appearing in v6.30

### ISSUE THREAD

**Issue by seantarogers** [Particular/NServiceBus#4875]
Hello,

I am not sure if this is a issue or just down to our license.  From what I understand our company has a perpetual license with an expiry in 9999-12-31.  
Anyway, we recently upgraded our .Net Framework 4.6.2 windows services' NServiceBus versions from 6.1.2 to 6.3.4.  Now when we start the Endpoints, the "It's time to extend your trial" warning box appears.  It seems that between v6.2.4 and v6.30 this message started to appear. We typically have a our license embedded in our app.config appSettings.

Thanks

**Comment by bording** [comment]
@seantarogers Please send an email to contact@particular.net, and we should be able to help you get this fixed.

**Comment by seantarogers** [comment]
Thanks
