### ISSUE TITLE
Installers cannot be disabled completely which can cause endpoints to fail to start

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4893]
## Who's affected

* Customers using transport connection strings without manage rights with the debugger attached

## Symptoms

When using Azure Service Bus connection string without manage rights an endpoint can operate but should assume that the required topology is fully created. As such an endpoint using a connection string without manage rights cannot use `EnableInstallers`. Unfortunately when the[ debugger is attached the installers get executed](https://github.com/Particular/NServiceBus/blob/3f85a3df5b9e21af218c5eb9a59b41c41815387b/src/NServiceBus.Core/InitializableEndpoint.cs#L144) nonetheless even though `EnableInstallers` was never explicitly provided which causes an endpoint to fail to start. 

## Steps to reproduce

- Download any ASB sample. 
- Run it with `EnableInstallers`
- Remove manage rights ![image](https://user-images.githubusercontent.com/174258/29016663-9c051ea6-7b53-11e7-8def-cb2d6d4e37cc.png)
- Run again with the debugger attached
- This causes the endpoint to blow up

## Proposed solution

Introduce a mode which allows disabling installers even with the debugger attached. For example

- `EnableInstallers` always runs the installers
- `DisableInstallers` never runs the installers
- Nothing provided with debugger attached runs the installer **Auto Mode**

**Comment by danielmarbach** [comment]
Relates to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/592

**Comment by danielmarbach** [comment]
I would classify this as a bug with requires patching

**Comment by timbussmann** [comment]
this is implemented in NServiceBus 6.4. Closing this issue.
