### ISSUE TITLE
AutoSubscribe is slow due to non-concurrent subscription

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4897]
Detected while investigating into https://github.com/Particular/NServiceBus.AzureServiceBus/issues/592

AutoSubscribe happens in a FeatureStartupTask in a serial fashion like the following

```
protected override async Task OnStart(IMessageSession session)
{
    foreach (var eventType in messagesHandledByThisEndpoint)
    {
        await session.Subscribe(eventType).ConfigureAwait(false);
        Logger.DebugFormat("Auto subscribed to event {0}", eventType);
    }
}
```

With Azure Service Bus a subscription can have multiple rules for routing. We have a subscription per endpoint which contains all the routing rules. Unfortunately creating subscriptions takes time due to the latency to the cloud. The time it takes linearly increases by the amount of messages an endpoint subscribes to. We have a user that has 30 handlers in the same endpoint. Starting such an endpoint takes the first time roughly 26 seconds on my machine. 

When starting the second time we have to query the subscription and unfortunately there is no way of querying the rules available on the subscriptions. So we have to add the rules over and over again. Starting the same endpoint a second time means that the thirty rules need to be re-added per restart. This slows down the endpoint start to up to 70 seconds on my machine. Depending on the latency to the datacenter this can take several minutes (user reported 2-3 min).

We have an idea which will allow us to[ improve the situation on the ASB side of things](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/597) but the idea requires changes in the entities. But if the core subscribes concurrently the startup time can be brought down to roughly 6 seconds consistently over multiple runs.

Here the measurements on my machine for Endpoint.Start

```
10:44:48: 00:01:08.6404252
11:08:11: 00:01:10.7677273
11:41:49: 00:01:05.9032803
Patched core
11:38:11: 00:00:06.9097633
11:39:35: 00:00:06.4044262
```

There is no risk in changing this since message session subscribe needs to be concurrency safe by design.

The user rightfully is considering his options because imagine having to wait 2-3 minutes every time you start the endpoint (for example for debugging) is a really bad experience.

**Comment by timbussmann** [comment]
the proposed change sounds reasonable to me. I think this would be a good fit for 6.4 along with https://github.com/Particular/NServiceBus/issues/4893

**Comment by danielmarbach** [comment]
What is the time frame of 6.4? Is the plan that 6.4 only contains the disable installer API as well as this fix and get out? If the timeframe is reasonable I have no objections to wait until 6.4. If I would have to prioritize I'd say the concurrency issue here is more important to be fixed. We encouraged the user to try to run without manage rights that's why we stumbled upon #4893 but since running without manage rights is not that common we could, in theory, postpone it.

**Comment by timbussmann** [comment]
> What is the time frame of 6.4?

the current plan is to get the two pending patches out and then prepare & release 6.4, so I'd say ~1 week. While I agree that we should unstuck this user asap, it's also hard to consider the current behavior as a bug fix. Would you consider a custom build as a temporary workaround until 6.4 is released?

**Comment by danielmarbach** [comment]
We don't have to consider it a bugfix. I'm talking about a normal patch. A path version doesn't always have to be a bugfix. I think we are mixing up things here. If we are lining up a couple of patches as you stated in https://github.com/Particular/NServiceBus/pull/4898 why not include this?

**Comment by timbussmann** [comment]
will be part of 6.4, closing this therefore. Thanks for raising this and providing a PR 🥇
