### ISSUE TITLE
A series of exceptions is preventing NSB from starting

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus#4902]
So I've been using the same configuration for some time but all stopped working recently after having updated some NSB packages. I'm not sure how to ask this question at this point because it's starting to appear as a cascading failure. I can provide any information that you need and/or grant read access to my repo. I'm at the end of my rope at this point. At any rate, the exceptions being thrown are:

- Thrown by System.dll: The requested Performance counter is not a custom counter, it has to be initialized as ReadOnly. I installed NServiceBus.Metrics.PerformanceCounters.MsBuild but no change.
- Thrown by NServiceBus.Core.dll: No ACE for SID S-1-5-7 found in security descriptor
- NServiceBus.Core.dll: Empty license string
- Various "not found" type exceptions on other dependency libraries where those types actually do exist

My endpoint config:

``` csharp
var licensePath = $"{AppDomain.CurrentDomain.BaseDirectory}/App_Data/NSB_License.xml";
var endpointConfiguration = new EndpointConfiguration(ServiceEndpoints.Reviews);
endpointConfiguration.LicensePath(licensePath);

var logger = HostContainer.Current.Resolve<ILogger>();
endpointConfiguration.EnableFeature<TracingLog>();
endpointConfiguration.SerilogTracingTarget(logger);
var logFactory = LogManager.Use<SerilogFactory>();
logFactory.WithLogger(logger);

endpointConfiguration.Recoverability().DisableLegacyRetriesSatellite();
endpointConfiguration.UsePersistence<NHibernatePersistence>();
endpointConfiguration.EnableOutbox();
endpointConfiguration.SendFailedMessagesTo("error");
endpointConfiguration.AuditProcessedMessagesTo("audit");
endpointConfiguration.UseContainer<WindsorBuilder>(c => c.ExistingContainer(HostContainer.Current));
endpointConfiguration.UseSerialization<JsonSerializer>();
endpointConfiguration.EnableInstallers();

endpointConfiguration.DefineCriticalErrorAction(context =>
{
	var message = $"NSB Failed: {context.Error}\nShutting down...";
	Logger.Fatal(message, this, context.Exception);
	Log.CloseAndFlush();
	Environment.FailFast(message, context.Exception);
	return Task.CompletedTask;
});

const int batchFlushInterval = 250;
var numberOfRecievers = Convert.ToInt32(ConfigurationManager.AppSettings["InstanceCount"]);
var perRecieverConcurrency = Environment.ProcessorCount;
var globalConcurrency = perRecieverConcurrency * numberOfRecievers;

endpointConfiguration.LimitMessageProcessingConcurrencyTo(globalConcurrency);

var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
transport.UseForwardingTopology();
transport.Transactions(TransportTransactionMode.None);
transport.NumberOfClientsPerEntity(numberOfRecievers);
transport.MessagingFactories()
		.BatchFlushInterval(TimeSpan.FromMilliseconds(batchFlushInterval))
		.NumberOfMessagingFactoriesPerNamespace(numberOfRecievers * 2);

transport.MessageReceivers()
	.PrefetchCount(numberOfRecievers);
	
return endpointConfiguration;
```

**Comment by bording** [comment]
Can you provide the full list of packages you're using that have these problems? Can you also provide the last known list of "good" packages where you didn't have these problems?

Do have a way to provide a log file that shows these exceptions?

**Comment by dasjestyr** [comment]
I'll update this when I can locate a last known good config, but here are the current packages. The only logs of the exceptions are appearing in the Events tab of diagnostic tools. The output window only shows that exceptions are being thrown but without any details. Not sure what to do about that:
``` xml
<packages>
  <package id="AutoMapper" version="6.1.1" targetFramework="net462" />
  <package id="Castle.Core" version="3.3.0" targetFramework="net462" />
  <package id="Castle.Windsor" version="3.3.0" targetFramework="net462" />
  <package id="DAS.Infrastructure" version="3.1.6430.30401" targetFramework="net462" />
  <package id="DAS.Infrastructure.Core" version="3.1.6430.30400" targetFramework="net462" />
  <package id="DAS.Infrastructure.EventStore" version="3.1.6430.30406" targetFramework="net462" />
  <package id="DAS.Infrastructure.Messaging" version="1.0.1" targetFramework="net462" />
  <package id="DAS.Infrastructure.Practices" version="3.1.6430.30405" targetFramework="net462" />
  <package id="DAS.Infrastructure.WebClient" version="3.1.6430.30401" targetFramework="net462" />
  <package id="EventStore.Client" version="4.0.0" targetFramework="net462" />
  <package id="Iesi.Collections" version="4.0.2" targetFramework="net462" />
  <package id="loggly-csharp" version="4.6.1.45" targetFramework="net462" />
  <package id="loggly-csharp-config" version="4.6.1.45" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.3" targetFramework="net462" />
  <package id="Microsoft.DependencyValidation.Analyzers" version="0.9.0" targetFramework="net462" />
  <package id="Microsoft.Owin" version="3.1.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.HttpListener" version="3.1.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Hosting" version="3.1.0" targetFramework="net462" />
  <package id="murmurhash" version="1.0.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net462" />
  <package id="NHibernate" version="4.1.1.4000" targetFramework="net462" />
  <package id="NServiceBus" version="6.3.4" targetFramework="net462" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.2.6" targetFramework="net462" />
  <package id="NServiceBus.CastleWindsor" version="6.0.0" targetFramework="net462" />
  <package id="NServiceBus.Metrics" version="1.0.0" targetFramework="net462" />
  <package id="NServiceBus.Metrics.PerformanceCounters" version="1.1.1" targetFramework="net462" />
  <package id="NServiceBus.Metrics.PerformanceCounters.MsBuild" version="1.1.1" targetFramework="net462" developmentDependency="true" />
  <package id="NServiceBus.NHibernate" version="7.2.1" targetFramework="net462" />
  <package id="NServiceBus.Serilog" version="3.0.3" targetFramework="net462" />
  <package id="NServiceBus.Serilog.Tracing" version="3.0.3" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="Serilog" version="2.5.0" targetFramework="net462" />
  <package id="Serilog.Enrichers.Environment" version="2.1.2" targetFramework="net462" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net462" />
  <package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net462" />
  <package id="Serilog.Sinks.Loggly" version="5.0.0" targetFramework="net462" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net462" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net462" />
  <package id="Serilog.Sinks.Trace" version="3.0.0-dev-00724" targetFramework="net462" />
  <package id="System.ValueTuple" version="4.3.1" targetFramework="net462" />
  <package id="Topshelf" version="4.0.3" targetFramework="net462" />
  <package id="WindowsAzure.ServiceBus" version="4.1.3" targetFramework="net462" />
</packages>
```

**Comment by dasjestyr** [comment]
It seems to be starting now (despite the load of exceptions that are thrown at startup. But when I try to send something on the bus, I'm getting the same error that I posted on the other thread:

  

>  at Serilog.Events.LogEvent.AddOrUpdateProperty(LogEventProperty property)
>    at Serilog.Events.LogEvent..ctor(DateTimeOffset timestamp, LogEventLevel level, Exception exception, MessageTemplate messageTemplate, IEnumerable`1 properties)
>    at SerilogExtensions.WriteInfo(ILogger logger, MessageTemplate messageTemplate, IEnumerable`1 properties) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\SagaAudit\SerilogExtensions.cs:line 16
>    at NServiceBus.Serilog.Tracing.SendMessageBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`1 next) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\MessageAudit\SendMessageBehavior.cs:line 34
>    at NServiceBus.Pipeline.Behavior`1.Invoke(TContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Behavior.cs:line 21
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.ScheduleBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Scheduling\ScheduleBehavior.cs:line 21
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.ApplyTimeToBeReceivedBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\TimeToBeReceived\ApplyTimeToBeReceivedBehavior.cs:line 26
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.DetermineMessageDurabilityBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\MessageDurability\DetermineMessageDurabilityBehavior.cs:line 26
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.AddHostInfoHeadersBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\AddHostInfoHeadersBehavior.cs:line 23
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.AttachCorrelationIdBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Correlation\AttachCorrelationIdBehavior.cs:line 43
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.ApplyReplyToAddressBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\ApplyReplyToAddressBehavior.cs:line 39
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.MutateOutgoingMessageBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutators\MutateInstanceMessage\MutateOutgoingMessageBehavior.cs:line 18
>    at lambda_method(Closure , IOutgoingLogicalMessageContext )
>    at NServiceBus.UnicastSendRouterConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\Routers\UnicastSendRouterConnector.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at DAS.Services.Reviews.Command.Controllers.ReviewsController.<ForceIngestion>d__2.MoveNext() in C:\source\das\Platform\das.services.reviews\src\DAS.Services.Reviews.Command\Controllers\ReviewsController.cs:line 37

**Comment by dasjestyr** [comment]
I removed NServiceBus.Serilog.Tracing and the problem seems to have stopped

**Comment by bording** [comment]
You're running this endpoint from inside Visual Studio, starting it with the debugger attached?

If so, then the exceptions you're seeing in the output window are nothing to be concerned about. They are the expected first-chance exceptions that are being handled by our code correctly. They aren't the source of your issue.

Looking at the stack trace, it definitely appears to be something related to your logging configuration, and the [behavior ](https://github.com/SimonCropp/NServiceBus.Serilog/blob/master/NServiceBus.Serilog.Tracing/MessageAudit/SendMessageBehavior.cs)that the NServiceBus.Serilog.Tracing package is inserting into the pipeline. 

The fact that you were able to send a message with that package removed shows that its related to the problem. I think at this point, your original issue https://github.com/SimonCropp/NServiceBus.Serilog/issues/12 the right place to continue diagnosing after all.

**Comment by dasjestyr** [comment]
Good, I'm not crazy. Always a plus. I'll close this issue thanks

**Comment by SimonCropp** [comment]
@dasjestyr as an aside. i note u r using loggly. can u share some screen captures of how NSB information looks in loggly? possibly email me at simon.cropp@particular.net if you dont want to share publically

**Comment by dasjestyr** [comment]
Yep!

![image](https://user-images.githubusercontent.com/3200529/29201389-b595492e-7e12-11e7-9c3f-973f7aefaab7.png)
