### ISSUE TITLE
TimeoutPersisterReceiver may not increment re-poll interval when timeouts are pushed

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus#4916]
After a timeout is pushed, the polling loop in `TimeoutPersisterReceiver` only updates the next retrieval time if the next expired timeout from the persister is less than the pushed timeout value. In those cases, this will cause the loop to re-run immediately, which can generate duplicate timeout messages.

## Who's affected

* All NServiceBus 5 users using the timeout manager for delayed delivery are potentially affected.

## Symptoms

* Timeout messages are duplicated
* The NServiceBus log set to `DEBUG` level will show duplicate polling attempts with the same timestamp.

**Comment by bording** [comment]
Fixed by #4899
