### ISSUE TITLE
Do we still need to set ClsCompliant(true) and ComVisible(false)?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4924]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Properties/AssemblyInfo.cs

**Comment by timbussmann** [comment]
I guess the possibility of supporting F# at some point would be interesting, but it would be easy enough to add that back if that ever gets addressed.

**Comment by dbelcham** [comment]
I think the `ClsCompliant` attribute is required for our users to be able to use VB as their language of choice

**Comment by andreasohlund** [comment]
We concluded that we need both to keep supporting VB and also not expose types to COM

Closing
