### ISSUE TITLE
NServiceBus 4 embedded RavenDB might not have all patches as present in NServiceBus.RavenDB 1.0.7

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4928]
NServiceBus.RavenDB 1.0.7 is released on Jun 6, 2016 and contains https://github.com/Particular/NServiceBus.RavenDB/pull/239 but this is not backported to NServiceBus 4.7 as the last release is 4.7.12 from Jan 28, 2016.

This means that https://github.com/Particular/NServiceBus.RavenDB/pull/239 is not included in core and potentially other patches too.

When the distributor got forked since 4.3, that required to patch both NServiceBus.Distributor.MSMQ as well as the core bits.

**Comment by andreasohlund** [comment]
@Particular/ravendb-persistence-maintainers looking at https://github.com/Particular/NServiceBus.RavenDB/pull/239 its not clear if this fit the critical patch criteria? (can you confirm that it does)

@ramonsmits is there a customer affected by this?

**Comment by ramonsmits** [comment]
@andreasohlund it is just an observation. What needs to happen is to check if this is correct. It is not based on a customer issue although I noticed this while traversing the releases and seeing that RavenDB was embedded in core.

**Comment by DavidBoike** [comment]
I don't see anything in the 1.0.x releases that needs to be migrated to (unsupported) NServiceBus 4.x.
