### ISSUE TITLE
Saga can be completed prematurely and skip recoverability 

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4943]
Original issue raised with ASB as a [question from a customer](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/596#issuecomment-326756003).
TL&DR: Saga completed, outgoing messages fail, saga is not retried and the incoming message is not found in the error queue.

The issue is with transports/persistences that are cannot share a transaction. To make things a bit more difficult, some transports might have a limit on the batch size (ASB:100, ASQ). Because of that, what can happen is premature completion of saga with its data been removed, while dispatching will fail. Retries will take place, but since saga was completed, its data removed, the incoming message will be disregarded and considered as successfully processed.

Ideally, NServiceBus would either not allow to combine outgoing dispatching and saga completion, or log a warning when such a condition is identified. While [`SagaNotFound`](https://docs.particular.net/nservicebus/sagas/saga-not-found) handler handles some of it, it is too general of a solution, and doesn't help customers to correlate between what they observe and the reason it happens.

**Comment by andreasohlund** [comment]
Not sure I follow, before marking a message as ready for dispatch in the outbox all handlers and storage would be completed. If saga completion can't enlist in the same storage tx as flagging the message as ready for dispatching we can't do much from a core perspective?

**Comment by andreasohlund** [comment]
Talking to @SeanFeldman we decided to start with adding doco to point out this behavior. Stay tuned

**Comment by andreasohlund** [comment]
Doco is now updated https://github.com/Particular/docs.particular.net/pull/3177

Should we close this?

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/docs.particular.net/commit/3593f10f0d40249d5ea0403f52139957ce2fd5c1
