### ISSUE TITLE
Remove compatibility layer in DistributionStrategy

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4951]
In 6.2 we introduced the distribution context and a compatibility layer to make it a non-breaking change. 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/DistributionStrategy.cs#L24

This compatibility layer should be removed. So in other words switch from

```
    public abstract string SelectReceiver(string[] receiverAddresses);
    public virtual string SelectDestination(DistributionContext context)
```

to

```
    public abstract string SelectDestination(DistributionContext context);
```

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers I think this should be done before RC but it is not a tragedy if not.

**Comment by timbussmann** [comment]
docs PR raised here: https://github.com/Particular/docs.particular.net/pull/3274.
