### ISSUE TITLE
v7 Beta 3 doesn't pass connection string to transport where a conn string isn't mandatory

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4961]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L52

This was introduced in https://github.com/Particular/NServiceBus/pull/4949

We need to always pass the connectionstring if there is one even if not mandatory for the transport (like MSMQ and SQL)

cc @SimonCropp @Particular/sqlpersistence-maintainers

**Comment by andreasohlund** [comment]
This means that all msmq, learning transport and sqltransport samples are broken for beta3 so we need to expedite the fix

**Comment by bording** [comment]
I'm not sure I'm following why this needs to change. If they don't need a connection string, why do we need to pass one?

**Comment by andreasohlund** [comment]
The name is missleading, it only specifies if its mandatory. Eg. msmq
supports a connection string but its not mandatory. So we should always
pass the string to the transport
