### ISSUE TITLE
Possible JSON/XML Injections

### ISSUE THREAD

**Issue by channeloriginteam** [Particular/NServiceBus#4983]
Possible JSON/XML injections at line 12 in NServiceBus.Core/Pipeline/BehaviorContextStack.cs. For example, the method WriteRawValue() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

**Comment by andreasohlund** [comment]
@channeloriginteam not sure I follow, we're not doing any writes in https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Pipeline/BehaviorContextStacker.cs ?

can you clarify?

**Comment by timbussmann** [comment]
closing this as there is no usage of WriteRawValue in this codebase and there is no BehaviorContextStack.cs as well. At that point, we cant' see a vulnerability as pointed out by @channeloriginteam.

@channeloriginteam we would highly appreciate if you could clarify on the reported vulnerability. Please feel free to respond to this issue, we will happily reopen this issue.
