### ISSUE TITLE
Wording of configuration section obsolete messages

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5006]
V7 deprecates configuration sections and throws exception when you're using them. But as @ramonsmits pointed out, the message states something like this:

> Use of the application configuration file to configure the endpoint is discouraged.

It seems that discouraged does not state clearly enough that it's not just discouraged, but also not possible? Should we change that wording?

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers agreed that we should definitely fix this on the next beta.

**Comment by dbelcham** [comment]
Look for all uses of the word 'discouraged' in the obsoletes and update entire message appropriately
Verify the wording around connectionstrings

**Comment by timbussmann** [comment]
addressed in #5017
