### ISSUE TITLE
Recoverability Delayed retry TimeIncrease formula should be easily overridable to do exponential retry and/or add jitter

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#5012]
Current API:
```c#
cfg.Recoverability()
    .Delayed(c =>
    {
        c.NumberOfRetries(5);
        c.TimeIncrease(TimeSpan.FromSeconds(5));
    });
```

This does not result in exponential backoff which is often used for retries.  By adding an optional lambda we give customers an easy way to calculate an increment/exponential/random delay.

Exponential backoff based on the previous delay:

```c#
c.TimeIncrease(TimeSpan.FromSeconds(2), delay => TimeSpan.FromSeconds(Math.Pow(delay.TotalSeconds(), 2)));
```

Exponential backoff based on the previous delay including randomized jitter:

```c#
var r = new Random();
c.TimeIncrease(TimeSpan.FromSeconds(2), delay =>
{
    double jitter;
    lock (r) jitter = r.NextDouble();
    jitter *= 0.2; // max 20%
    return TimeSpan.FromSeconds(Math.Pow(delay.TotalSeconds, 2 + jitter));
});
```

**Comment by timbussmann** [comment]
I think a custom recoverability policy would cover this requirement: https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy ?

**Comment by timbussmann** [comment]
ping @ramonsmits 
given the ability to use custom recoverability policies, do you still think this is an issue we need to look into further?

**Comment by timbussmann** [comment]
I'm going to close this issue for now as @Particular/nservicebus-maintainers think this is an edge case which we don't see as part of the standard API currently. The custom recoverability policy API does allow much more flexibility in implementing custom recoverability behaviors.
