### ISSUE TITLE
Queues are created even with installers disabled in V7

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#5023]
### What's the problem?

The new default in V7 is that installers are disabled by default (even with a debugger attached). The core will still create the queues unless the user explicitly opts-out by calling:

```csharp
endpointConfiguration.DoNotCreateQueues();
```

This bug affects all transports.

### Credit

The issue was discovered by @gbiellem when using the latest V7 beta of SQL Server transport (https://github.com/Particular/NServiceBus.SqlServer/issues/403). 

### Plan of attack

- [x] PR: #5028 
- [x] Verify V6 behaviour

**Comment by bording** [comment]
This is a regression from V6, where queue creation was handled by an installer, [QueuesCreator](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Queuing/QueuesCreator.cs).

Queue creation is currently handled separately from installers now: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L71

Looks like we missed the impact of this change when evaluating #4843. 😢

**Comment by timbussmann** [comment]
but at least it seems this missed v6.4 and there is nothing we need to patch.

**Comment by timbussmann** [comment]
@MarcinHoppe is there something we need to add/clarify in doco as part of this issue?

**Comment by MarcinHoppe** [comment]
Nothing comes to my mind, except for maybe documenting the `DoNotCreateQueues()` method which is currently undocumented.
