### ISSUE TITLE
Azure Storage Queues Publisher Routing Fails

### ISSUE THREAD

**Issue by afyles** [Particular/NServiceBus#5029]
When we attempt to route via code, we get the following error: 
`A logical endpoint name should not contain '@', but received 'publisher@DefaultEndpointsProtocol=https;AccountName=accountname;AccountKey=X'. To specify an endpoint's address, use the instance mapping file for the MSMQ transport, or refer to the routing documentation.`

The routing we are using is:
`transport.Routing().RegisterPublisher(eventType: typeof(IProductBecameShippable), publisherEndpoint: "publisher@DefaultEndpointsProtocol=https;AccountName=accountname;AccountKey=X");`

The routing works via message mappings in the app.config.  We have tried this under 7.4.2 of the Azure Storage Queue transport package and also under the latest beta.  We feel this should work via code especially since the host is warning that the config file will be deprecated in v8.

**Comment by SeanFeldman** [comment]
@afyles you're correct. MessageEndpointMapping approach works in with 7.4.2, but not the code-based approach. With MEM deprecated in NServiceBus version 7 (ASQ v8), we have fixed this issue and the latest set of beta packages on our MyGet feed should have this issue addressed.

Here are the ASQ specific issues.
Pub/sub: https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/246
Sending commands: https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/274

Pre-release documentation was updated as well.
Should you find any discrepancies, please raise an issued directly in ASQ repository : https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/

Thank you 🙂
