### ISSUE TITLE
ConfigurationException Workaround is only enabled when targeting net452

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5040]
We use [this workaround](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs#L18) in the acceptance tests to avoid the issue described here: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-deserialization-of-objects-across-app-domains

the workaround is wrapped in `#if NET452` but this bug affects all .net framework versions (tested against 4.6.2 and 4.7). Since we ship this code as source files, this workaround doesn't work in case downstreams target some other framework than net452.

cc @SimonCropp

**Comment by bording** [comment]
Give our current expected framework targets, the simplest way to handle this would be to change it to `#if !NETCOREAPP2_0`.

**Comment by andreasohlund** [comment]
Added to the beta10 milestone

**Comment by timbussmann** [comment]
@bording was thinking about this as well. See #5041
