### ISSUE TITLE
Can't get SQL persistence working!

### ISSUE THREAD

**Issue by yg85** [Particular/NServiceBus#5042]
Hello!
I havelatest NServiceBus 7 preview package and trying to have my demo project running on SQLServerExpress with sql persistense.

I am getting those messages:
```
2017-10-19 19:12:21.966 WARN  NServiceBus.ExpiredTimeoutsPoller Failed to fetch timeouts from the timeout storage
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.SSOEndpoint_TimeoutData'.

```
In my database I do not see such table. I have next 3 tables: 'dbo.SSOEndpoint','dbo.SSOEndpoint.Timeouts' and 'dbo.SSOEndpoint.TimeoutsDispatcher'.

What am I doing wrong?

Below is my enpoint config:
```
  var endpointConfiguration = new EndpointConfiguration(endpointName);

	var transport = endpointConfiguration.UseTransport<SqlServerTransport>();

	string connectionString = ConfigurationManager.ConnectionStrings["NServiceBusDatabase"]?.ToString();

	transport.ConnectionString(connectionString);
	transport.DefaultSchema("dbo");
	transport.UseSchemaForQueue("error", "dbo");
	transport.UseSchemaForQueue("audit", "dbo");
	
	transport.Transactions(TransportTransactionMode.None);


	var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
	persistence.SqlDialect<SqlDialect.MsSqlServer>();
	persistence.ConnectionBuilder(
		connectionBuilder: () =>
		{
			return new System.Data.SqlClient.SqlConnection(connectionString);
		});
	var subscription = persistence.SubscriptionSettings();
	subscription.DisableCache();

	var scanner = endpointConfiguration.AssemblyScanner();
	scanner.ScanAppDomainAssemblies = true;
	scanner.ScanAssembliesInNestedDirectories = true;
```

**Comment by DavidBoike** [comment]
Hi @yg85 

Do you also have the **NServiceBus.Persistence.Sql.MsBuild** package installed for the endpoint as described in https://docs.particular.net/persistence/sql/#usage ?

**Comment by yg85** [comment]
Yes. I aslo tried installing NServiceBus.Persistence.Sql.ScriptBuilder, result is the same. 
Project is .NET Core 2.0. 
NServiceBus.Persistence.Sql.MsBuild package version is 3.0.0-beta0004

**Comment by DavidBoike** [comment]
Moved to https://github.com/Particular/NServiceBus.Persistence.Sql/issues/193.

**Comment by DavidBoike** [comment]
@yg85 I moved this issue to the correct repository (the one for SQL Persistence) and then I'll answer further from there: https://github.com/Particular/NServiceBus.Persistence.Sql/issues/193
