### ISSUE TITLE
StartUpDiagnostics should not output default and empty values

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5043]
currently there is a lot of bloat in the output

 * `"EnabledByDefault":false`
 * `"Active":false`
 * `"PrerequisiteStatus":null`
 * `"Dependencies":[]`

i dont think default values and empty collections should be written

**Comment by timbussmann** [comment]
discussed this issue on today's @Particular/nservicebus-maintainers sync and we decided to close this issue for now based on the following reasons:
* Showing default values can be valuable. We're not always aware of the default values or what settings are configurable and are not configured by the user.
* We haven't seen the diagnostics file being used often so far and therefore feedback from the support process. We'd like to wait for more feedback before investing more into this.
