### ISSUE TITLE
Validate Kind of DateTime values passed from the TimeoutPersister

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#5046]
TimeoutPersister APIs return DateTime values in `Peek` and `GetNextChunk`. NServiceBus treats these values as UTC but does not validate if the Kind is set properly.

**Comment by timbussmann** [comment]
I think it would make sense to change these APIs to work with `DateTimeOffset` anyway which would kinda solve this problem as well, would you agree @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
Makes sense 👍

**Comment by timbussmann** [comment]
@SzymonPobiega @dbelcham I raised a dedicated issue for adjusting the persistence seam to keep this more clear. Are you happy to close this one Szymon?
