### ISSUE TITLE
redundant state machine in When_headers_contain_special_characters ?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5060]
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/Outbox/When_headers_contain_special_characters.cs#L76

**Comment by timbussmann** [comment]
Yeah that await seems indeed to be redundant. But since it's just used in the test and not somewhere in the core's hot path I don't see a larger issue with that or am I overseeing something? By my understanding, I'd say nothing we need to address, happy to accept a PR though.

**Comment by SimonCropp** [comment]
Nah not pressing. Will PR and u can merge when timing is convenient
