### ISSUE TITLE
Cannot run the transport outside of an endpoint

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#5064]
The current design with internal `StartupDiagnosticEntries` and public API via `DiagnosticSettingsExtensions` does not allow setting up the diagnostics by code external to the core NSB. 

Doing so could be useful either when setting up a test harness to exercise a transport or when only using transports without the full core (NServiceBus.Raw). This issue prevents me from releasing NServiceBus.Raw which is a dependency for a number of Particular and open source projects including SC.TransportAdapter and NSB.Bridge.

**Comment by timbussmann** [comment]
as `StartupDiagnosticEntries` is mostly a dedicated type for easier settings-access, I see no big harm in making it public to unblock this scenario.

**Comment by SzymonPobiega** [comment]
That would be cool. When I can expect this?

**Comment by andreasohlund** [comment]
👍 to make the type public, will PR later tonight and we can push another beta
