### ISSUE TITLE
`GetRequiredTransactionModeForReceives` cannot be called in transport infrastructure ctor

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#5065]
```
    class MyTransportInfrastructure: TransportInfrastructure
    {
        internal MyTransportInfrastructure(SettingsHolder settings, string connectionString)
        {
            settings.GetRequiredTransactionModeForReceives() // throws even for non-sendonly endpoints
        }
```

![image](https://user-images.githubusercontent.com/174258/32318677-38e6f174-bfb8-11e7-98fe-b4fafa53c075.png)

![image](https://user-images.githubusercontent.com/174258/32318689-450bb606-bfb8-11e7-8cfb-2d95f684a34c.png)

```
System.InvalidOperationException : Receive transaction mode isn't available since this endpoint is configured to run in send-only mode.
   at NServiceBus.ConsistencyGuarantees.TransactionModeSettingsExtensions.GetRequiredTransactionModeForReceives(ReadOnlySettings settings)
```

**Comment by danielmarbach** [comment]
this might affect other transport maintainers

**Comment by bording** [comment]
I think an argument could be made that it was always incorrect to call that from the TransportInfrastructure ctor, and v7 is now enforcing it.

**Comment by danielmarbach** [comment]
@bording I've explained this to @timbussmann and @andreasohlund that I this statement is not true. When we introduced these settings extensions we made a choice and essentially made these extension methods to work wherever the readonly settings are available. Since before this change the core work in a way that the settings holder passed into the transport infrastructure ctor and the behavior of the settings extensions was clearly defined it was OK to call it in the ctor. The changes introduced in the refactorings made a move into a direction where settings extension methods suddenly become context specific and can no longer be called under certain circumstances. I understand the reasoning behind that move. The move towards that direction can be argued is a good move although the ultimate destination would be to have an explicit seam. Introducing a change late in the game and then in retrospect say "it was always incorrect to call" for me seems not to be a good answer since the core went through a clear design change which hasn't been communicated. I would like to stress that I'm not trying to finger point. The sole purpose is to highlight my thoughts which I already communicated to @timbussmann and @andreasohlund

**Comment by andreasohlund** [comment]
My bad, I should have commented and not just assigned it to me.

We concluded to leave this as is since there is a workaround for ASQ.

The long term plan is to:

* Deprecate all the extension methods that provides access to receive settings
* Make the `ReceiveConfiguration` public so that features can access it
* Pass it as a parameter to `InitializeReceiveInfrastructure(...)` so that transports gets access to it.

Should I raise a separate issue to track this or is it a premature solution to https://github.com/Particular/NServiceBus/issues/5044 ?

**Comment by timbussmann** [comment]
I think #5044 covers this.

**Comment by andreasohlund** [comment]
Fair enough, added this info to #5044
