### ISSUE TITLE
Saga.ReplyToOriginator is not working in NserviceBus 7.0.0 -beta0008

### ISSUE THREAD

**Issue by Donjay2101** [Particular/NServiceBus#5067]
Hi,
    I was trying to use Saga in one of my test projects using "NServiceBus 7.0.0. -beta0008" and ".net Core".
Everything is working fine but at last, it is throwing exception when I am calling "ReplyToOriginator".

it says : No handler could not found for message type: <Message>

please help me out on this thank you...

**Comment by andreasohlund** [comment]
Can you share the configuration code and the saga code?

**Comment by Donjay2101** [comment]
Hey,
   here is the  code which I did for demo purpose please find the attachment.
On Nov 3, 2017 5:26 PM, "Andreas Öhlund" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you share the configuration code and the saga code?

**Comment by andreasohlund** [comment]
@Donjay2101 not sure if you can attach things to GitHub comments, can you upload the code somewhere and post a link to it?

**Comment by andreasohlund** [comment]
@Donjay2101 you where not properly awaiting the call to reply to originiatorm I've sent in a PR that make the spike work as you expect it to. Let me know what you think?

https://github.com/Donjay2101/NServiceBus.Saga/pull/1

**Comment by andreasohlund** [comment]
Based on https://github.com/Donjay2101/NServiceBus.Saga/pull/1#issuecomment-342515092 it seems like this is resolved. Closing this

**Comment by Donjay2101** [comment]
thank you for the support, I think the problem was the originator and the message which we are sending from "ReplyToOriginator" method should be under the same endpoint.  for example, in above example, the starting of the project is "Saga.Test"( see program.cs for the test project). So the reply should be in the same endpoint.

Thanks @andreasohlund  for helping me on this, appreciate the time given to my problem.

**Comment by andreasohlund** [comment]
That’s correct, the reply will go back to the endpoint that originally
started the saga. Just let us know if you have any further issues.
