### ISSUE TITLE
Allow to retrieve an existing diagnostic section

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#5069]
I started playing with diagnostics in RavenDB and the actual API seems to be way to limited to achieve what needs to be achieved. Settings and things, as a maintainer I think should be logged, are scattered in many different classes and many different extensions methods. Right now as far as I have understood the way to implement diagnostics is to have a single place where diagnostics are added via the `AddStartupDiagnosticsSection`, in Core happens something similar to:

```
class RavenDBPersistenceStartup : IWantToRunBeforeConfigurationIsFinalized
{
    public void Run(SettingsHolder settings)
    {
        var diagnostics = new Dictionary<string, object>();

       //blindly iterate over settings and add them to the dictionary

        settings.AddStartupDiagnosticsSection("Persistence.RavenDB", diagnostics);
    }
}
```

What would be nice to have is the ability to retrieve an existing section to enhance it with more data. I expect the RavenDB downstream to create the `Persistence.RavenDB` section and then all the extensions methods and all the classes that in raven in some way want to add information could do:

```
var section = settings.GetStartupDiagnosticsSection("Persistence.RavenDB");
section.Add("key", value);
```

Otherwise keeping in sync the single place where diagnostics are added and all the settings that a downstream manages can easily become cumbersome.

//cc @Particular/ravendb-persistence-maintainers

**Comment by andreasohlund** [comment]
Would it be possible to add your "own" dictionary that you later just adds to the diagnostics?

```
// at various places
settings.GetOrCreate<Dictionary<string,object>>("RavenDiagnostics").Add("MySetting",myValue);

//then at the end
settings.AddStartupDiagnosticsSection("Persistence.RavenDB", settings.Get<Dictionary<string,object>>("RavenDiagnostics"));
```

**Comment by mauroservienti** [comment]
Is the suggested way to use the settings holder to share something that is not a setting at all and is not relevant for any runtime usage? Or more of a workaround.

**Comment by andreasohlund** [comment]
>Is the suggested way to use the settings holder to share something that is not a setting at all and is not relevant for any runtime usage? Or more of a workaround.

We don't really have any rules for settings other that that they should not be accessed at runtime. So this usage would be fine IMO.

I have a hunch that the need for this is a sign that the persistence seam needs improvement. Do you have a use case in ravendb that we can look at?

Side note: We mostly use anonymous types ( new{ X = y,  A = b}) in the core so for those use cases this type of API would make less sense. (just an observation)

**Comment by timbussmann** [comment]
I think we should keep the diagnostics API as simple as possible. Retrieving and enhancing existing configurations seems like a tricky approach, especially since we're using anonymous classes quite often (instead of dictionaries as you mentioned in your snippet). That would be just another copy of the settingsholder.

If you need to gather information from multiple places, I'd suggest to do that internally (e.g. by using the Settings) or add multiple sections.

**Comment by mauroservienti** [comment]
I raised this because @andreasohlund 's suggestion seemed to me like a hack, but if that's fine, I'll go with that.

**Comment by andreasohlund** [comment]
I think the proposed workaround is good enought for now, we can reopen this if other downstreams runs into the same types of problems
