### ISSUE TITLE
Hanging DTC transaktions / only failed to notify

### ISSUE THREAD

**Issue by lcorneliussen** [Particular/NServiceBus#507]
From time to time I have left-over "only failed to notify" transactions. It seems to be an issue with distributed transactions across MSMQ and RavenDB.

I can't really reproduce it. But it would be good to know, if the NSB team has seen those? Maybe after running mass tests?

I have a very bad feeling about using this in production without having tracked it down.

Just as a hint: when we used Raven sessions with uow, we had much more of these - now we are using very short living sessions.

Might also be necessary to engage Oren Eini in this discussion.

**Comment by lcorneliussen** [comment]
Back to the same error. Not happening too often, but happens and leaves things inconsitent

**Comment by andreasohlund** [comment]
@lcorneliussen can you reraise this on https://github.com/Particular/NServiceBus.RavenDB with updated versions so that we can track this one down?
