### ISSUE TITLE
Messages are sent as non durable if outbox is enabled on Version 5

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#5074]
### Symptoms

Messages sent from message handlers will be marked as non durable. This can lead to message loss on transports with support for non-durable messages should there be a infrastructure failure with the queuing system.

### Who's effected

All V5 users running on RabbitMQ  with the Outbox enabled.

### Details

Reported by user - https://discuss.particular.net/t/rabbitmq-transport-message-persistence/169/2

Repro: https://github.com/Particular/NServiceBus/pull/5073

**Comment by andreasohlund** [comment]
@yvesgoeleven thanks, updated!

**Comment by bording** [comment]
I've verified the behavior with RabbitMQ on V5. When a message is sent from a handler, it is sent as a transient message if the outbox is enabled.

I've also verified the this does not happen on V6. Messages sent from a handler are correctly persistent.

**Comment by andreasohlund** [comment]
Clarified the sympthoms

>Messages sent from message handlers will be marked as non durable. This can lead to message loss on transports with support for non durable messages should there be a infrastructure failure with the queuing system.

**Comment by timbussmann** [comment]
confirmed with @andreasohlund that MSMQ is not affected because it's not possible to run MSMQ without transactions and with outbox on at the same time. The outbox requires a tx mode > None. But MSMQ transport will only support non-durable messages (non transactional queues) when in tx mode == none.

**Comment by andreasohlund** [comment]
Updated description to reflect that only RabbitMQ users are affected

**Comment by timbussmann** [comment]
fixed as part of 5.2.25
