### ISSUE TITLE
Customers can cause startup diagnostics not to be captured

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#5075]
When a [custom diagnostics writer](https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics-writing-to-other-targets) is used, the diagnostics file will not be written to the expected destination file and customers need to know where that info is written to.

A worse scenario is when a custom diagnostic writer doesn't write anything to a file. In this case diagnostics info will not be available for support personal at all.

@Particular/nservicebus-maintainers should startup diagnostic be always written to allow support personal to retrieve it?

**Comment by andreasohlund** [comment]
This was done intentionally to give us a way to avoid writing to disk should the users environment not allow it. Permissions, anti-virus etc.

We didn't want an explicit `.DisableDiagnostics()` since that would tempt users to turn it off.

Yes this can mean that some users won't write diagnostics at all but I think we will have to live with that?

**Comment by andreasohlund** [comment]
@SeanFeldman does the reasoning to why this is "by design" make sense?

**Comment by SeanFeldman** [comment]
@andreasohlund it does.

When use a custom diagnostic writer option, they might not be aware of this default behavior.
What I'm wondering is could the diagnostics be attempted anywyas, and if running into exceptions, silently swallow those rather than just disabling diganostics.

**Comment by andreasohlund** [comment]
>What I'm wondering is could the diagnostics be attempted anyways,

I don't like us always writing since that might get us into trouble with anti-virus etc. In essense this is an advanced use case and the downsides isn't catastrophic if something goes wrong since this is just diagnostics?

**Comment by timbussmann** [comment]
I'm with @andreasohlund here. The described behavior is as intended. Did you run into any issues with that @SeanFeldman ?

**Comment by SeanFeldman** [comment]
Exactly as described it 🙂
Have added a custom diagnostics writer with @boblangley and we were wondering were the diagnostics file was.

Not going to fight over this. Just something that I think we should do slightly in a different way.

**Comment by timbussmann** [comment]
> Have added a custom diagnostics writer with @boblangley and we were wondering were the diagnostics file was.

why did you provide a custom writer in the first place if you were interested in the original file?
I'm happy to check whether we could improve the naming in the long run (although that ship has sailed for v7) but I don't see us changing the behavior tbh.

**Comment by SeanFeldman** [comment]
We wanted to capture it in our application (custom writer, right?). And when wanted to grab the output as-is (pretend that would be an ask from Particular support) couldn't find it.

> I'm happy to check whether we could improve the naming in the long run

And that could be it. Perhaps it's not so much the behavior as the lack of clarity and implications of introducing a custom writer. Like with diagnostics in .NET. When you introduce a custom diagnostics writer, you do not remove the other ones that were registered by default. You _append_. A name like `ReplaceDiagnosticsWriter()` or something among the lines would at least trigger some thought of "hey, Sean, you're **replacing** diagnostics writter".

**Comment by andreasohlund** [comment]
>ReplaceDiagnosticsWriter() 

Happy to go with this name going forwards, raise a new issue and assign to v8?

**Comment by timbussmann** [comment]
>  You append.

I think in those cases the API clearly expresses that by allow to subscribe to an event or by having some `AddXyz` in the naming, but I tend to agree that the naming could be clearer.

`ReplaceDiagnosticsWriter` seems to be a viable option. Happy to rename in v8 as the usage of this API shouldn't be too common. 👍

**Comment by SeanFeldman** [comment]
@andreasohlund @timbussmann issue #5090 raised
