### ISSUE TITLE
Include fileversion in diagnostics for the assembly scanner

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#5076]
Today we only dump the AssemblyVersion but since we lock the version on our components to `Major.0.0` it would be nice to have the FileVersion as well to know what exactly what version the endpoint has loaded.

**Comment by timbussmann** [comment]
how easy would that actually be? We're working with the `Assembly` class directly, which doesn't necessarily have a file version. So we would have to check for associated files and retrieve those file versions.

**Comment by andreasohlund** [comment]
Not sure how much overhead it would be but yea doing a https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Utils/FileVersionRetriever.cs#L17 was the idea?

**Comment by bording** [comment]
It does seem like it could be a useful additional piece of information to capture.

**Comment by andreasohlund** [comment]
Duplicate of https://github.com/Particular/NServiceBus/issues/5522
