### ISSUE TITLE
Assembly Scanner Ignores Assemblies not Referencing NServiceBus.Core

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus#5092]
In NSB 7.0 it seems the scanner is not looking at assemblies which don't reference NSB core - it just completely ignores them.  

I think I get why this change was made - but in my case I'm not using NServiceBus.IMessage, instead using Conventions to specify my own interface.  I define all my commands and events in a separate assembly which only contains these classes, which means I don't need to reference NSB.  And with this change it also means the scanner won't find my messages.

Moreover - just adding NSB nuget package won't solve the problem, I have to actually reference some namespace for .net to link the package it seems.

If this is going to be the way going forward can we get an api to manually add assemblies to scan regardless of if they reference NSB or not?

Something like `scanner.IncludeAssemblies(x => x.Name.EndsWith("Language"))`

**Comment by bording** [comment]
@volak I'm not aware of any change in behavior for NServiceBus 7 in regard to how the assembly scanner handles assemblies that don't reference NServiceBus.Core.  

Do you have a repro to show that it works in NServiceBus 6 and doesn't work for NServiceBus7 that I could look at?

**Comment by volak** [comment]
I don't have a small repo off hand but what I've tracked down is this method

https://github.com/Particular/NServiceBus/blob/315ddaee460fcf25c11e4fb79a3b434d5e35c6e5/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L150

It only returns true if one of the dependent assemblies is NSB - and in order to be scanned for types this method has to return true.

I'm working on updating my library project, my hello world sample is what I'm trying to get working now https://github.com/volak/Aggregates.NET/tree/netstandard/samples/1.%20HelloWorld

When the Languages project doesn't reference NSB the SayHello and SaidHello types are not found.  When I reference NSB in that project AND add NServiceBus.IEvent to SaidHello both types are found.

**Comment by bording** [comment]
NServiceBus 6 also skipped assemblies if they didn't reference NServiceBus.Core, so that's why I'm saying I'm not aware of a behavior change.

I've just tested our Unobtrusive messaging demo for v7, and it's working: https://docs.particular.net/samples/unobtrusive/?version=core_7

FYI, the shared project there does seem to still have a reference to NServiceBus.Core, but after moving the `ConventionExtensions` class into the Client and Server projects and removing the reference, everything still works. I've filed https://github.com/Particular/docs.particular.net/issues/3481 to fix that.

There certainly could be some other issue that's causing your problem, but I don't think it's related to the assembly scanner skipping files if they don't reference NServiceBus.Core. That's why having a repro example would be very helpful to get to the root of your problem.

**Comment by volak** [comment]
Ok thanks for checking it out.  Assembly scanning is always bites me like once a year - and it takes so long to track it around.  I'll play around with the sample and see if I can reproduce with the sample.

**Comment by volak** [comment]
@bording Ok so the issue is not with the scanner - its with the message mapper.  

My app is failing to deserialize events read from eventstore.  I receive these directly from the eventstore without using NSB transport - but I then try to use the IMessageMapper interface to generate a concrete type for the event interface.  And THATs what fails, because the message mapper doesn't have the event type, because it was not scanned, and seems like due to this PR 
https://github.com/Particular/NServiceBus/pull/4615
message mapper mappings are lazy initiated via the transport.. which I'm not using... haha

So I am stuck in a weird place - because the json deserializer needs the type mapping to deserialize events from eventstore - and the NSB transport won't see the events to load them into the IMessageMapper.

Seems like you guys now do `mapper.Initialize` on every message that comes in - guess the solution is to do the same on every event received from eventstore!

**Comment by andreasohlund** [comment]
>Seems like you guys now do mapper.Initialize on every message that comes in - guess the solution is to do the same on every event received from eventstore!

Yup!

>Why doesn't IMessageMapper do Initialize each time GetMappedTypeFor is used?

We never had a use case for new messages being "found" other then when receiving a message. But I guess you have a case where messages needs to be initialized on the fly. @Particular/nservicebus-maintainers thoughts?

**Comment by bording** [comment]
It seems like calling `Initialize` from `GetMappedTypeFor` could be a reasonable change to make, but I'd need to spend some time analyzing the message mapper code to make sure.

One thing I see is that `CreateInstance` can potentially call both `InitType` and `GetMappedTypeFor`, so something would need to change so `InitType` doesn't end up needlessly being called a second time.

**Comment by volak** [comment]
@andreasohlund @bording  Initializing types lazily in the mapper would be cool - I understand the desire to move away from conventions and hopefully scanning in the future.

The other problem I just came across is that I also depend on knowing all the endpoints messages at the start of the app to generate eventstore projections with all the message types the endpoint is interested in.

But I'm thinking the message handler registry can help me there - handler's are not lazy loaded (I think?) so in theory I can pull all the message handlers out and get all the message interfaces handled by the message handlers without waiting for my endpoint to receive anything?

If so, would it make sense to also do this on the mapper at the very start?

**Comment by andreasohlund** [comment]
>But I'm thinking the message handler registry can help me there - handler's are not lazy loaded (I think?) so in theory I can pull all the message handlers out and get all the message interfaces handled by the message handlers without waiting for my endpoint to receive anything?

Yes that would work

>If so, would it make sense to also do this on the mapper at the very start?

Since the mapper is used for outgoing messages as well its likely that there are messages sent for which the endpoint won't have a handler for this this wouldn't work in that scenario?

**Comment by volak** [comment]
Yes, you are right didn't think about that.  The best solution is still to initialize in mapper seems like.

On a related note, I just had an interesting conversation on gitter/coreclr about assembly scanning and referenced nuget packages not showing up in `AppDomain.GetAssemblies()`
https://gitter.im/dotnet/coreclr?at=5a26e6ec87680e6230d53f8c

Most of the time I've used NSB I've separated my message handlers, events, commands, etc into small packages representing the bounded context.  And my endpoint instance simply installs the context's nuget package.  
Up until .net standard this has been all well.   But these days, unless you build the project with `dotnet publish` (not the default) assemblies referenced by your project don't end up in the working directory.  On top of that, unless you directly reference anything in your dependent package it won't be loaded into the app domain.

So before in 6.0 I could install nuget package "Domain.Network" and thanks to the assembly scanner it would find the nuget package assembly in my directory and load the handlers without me having to refer to anything in "Domain.Network."
But now in .net standard this is no longer the case.  The solution we came up with was to manually do `Assembly.Load("Domain.Network")` and THEN scan the AppDomain.

I mention it because I have a feeling you guys might want to put this bit of info into the docs because I can't be the only one grouping my handlers and messages into separate assemblies.

**Comment by andreasohlund** [comment]
I'm pretty sure we just merged a PR that fixed that

https://github.com/Particular/NServiceBus/pull/5081

thoughts?

**Comment by volak** [comment]
Wow! great response time! 🔥 🔥

**Comment by volak** [comment]
When is the next pre-release planned?  I might just do `Assembly.Load` until this new scanner is available

**Comment by timbussmann** [comment]
@volak this is currently planned to be part of RC1. Until then, the Assembly.Load workaround should indeed do the trick.
