### ISSUE TITLE
QUESTION : How to re-queue a message without picking it up again

### ISSUE THREAD

**Issue by scharada** [Particular/NServiceBus#5093]
Hi
i have a scenario where multiple listeners are listening to a queue for specific messages.
when a message arrives , any listener can pick up the message (whoever does it first and we want to keep that random order). once the message read, it does some processing and based on some metadata, it might require the same processing by another listener, thus it has to re-post it but should not read it again. 

how can this be achieved ?

thank you in advance.

**Comment by ramonsmits** [comment]
@scharada It seems you want to have multiple handlers invoked for the same received message but currently have them stored in different processes that all read from the same queue.

### Multiple handlers on same message type

Maybe it would work if you host all those handlers in a single endpoint, maybe even scale-out this endpoint. 

If a specific handler order is required then this can be configured

 - https://docs.particular.net/nservicebus/handlers/handler-ordering?

Sending a message back to the same queue could always result in that same processor to fetch that messages again.

### Events

If the multiple handlers in a single endpoint does not work for you then you can also just have all the handlers on their own queue. If it is an event message you could have those multiple processors each get their own copy of that event messages

### Publish second event

Another option is that when the first processor has completed processing that publishes an event that it completed. That other listener endpoint could subscribe to that event.


Would that work? If not, then please provide a bit more detail on the actual process.



ps. We also have a forum which might be better suited for such questions in the future: https://discuss.particular.net

**Comment by scharada** [comment]
@ramonsmits thank you for your answer. i probably have give a better explanation for the case. here is a scenario that is almost the exact replica of our business case. think of a bitcoin transaction that requires 3 signatures in order to be confirmed. there are (for the sake of the example, 10 processes that can sign).
the transaction is sent to a queue, one of the 10 processes picks it up, signs it and if the number of required signatures is lower then 3, then puts it back to the queue to be signed by "another process".
the same is repeated until 3 signatures a reached , then the transaction is not queued anymore. 
any ideas ?

**Comment by ramonsmits** [comment]
@scharada How about randomizing a set of signers at start, add that as meta data, and forward the message after each sign operation? Assuming here that a signature is always needed to be added on top of a previous signature. Any logical signer can also be scaled out if needed. it is basically the [routing slip pattern](http://www.enterpriseintegrationpatterns.com/patterns/messaging/RoutingTable.html)

**Comment by timbussmann** [comment]
Hey @scharada 
We haven't heard back from you for quite a while now. I'm going to close this issue for now, but feel free to reopen it in case you have further questions about the suggested solutions. You can also raise your question in our community forum over here: https://discuss.particular.net/
