### ISSUE TITLE
Message get lost if no routing is specified?

### ISSUE THREAD

**Issue by johnfakeacc** [Particular/NServiceBus#5098]
Hi,

I've created three console applications with NSB 6.4.3 installed.
I'm using SqlServer Transport on the same maschine (Version 3.1.3).

**Service A** is sending a Message to a **Saga-Service**.
The Saga-Service is started by the message and inside the handler I want to send a message to **Service B**.

Variant 1 works as expected:
`context.Send("Backend.ServiceB", new DoSomething());`

Variant 2 should throw an exception if no routing is configured?!
`context.Send(cmd);`

If I forget to define a Route for the message the saga sent the message but without any exeptions.
Where is my message? 

Hope you can follow me

Best Regards
John

**Comment by bording** [comment]
If you have not configured any routing information, your Variant 2 APC call should be throwing an exception with the following message: `No destination specified for message: <type of message>`.

If you aren't seeing this, be sure that you're properly dealing with all of the async API calls. For example, `Send` returns a `Task`, so it either needs to be awaited, or it can be returned from your handler method if you have no other async calls in the method.

If everything in your code is properly async, then can you provide a sample that reproduces the issue you're seeing?

**Comment by johnfakeacc** [comment]
Hi bording,

I've attached a demo solution with only one logical sender (clientA).
The expected exeption "No destination specified.." is not thrown.

[LostMessageSample.zip](https://github.com/Particular/NServiceBus/files/1609736/LostMessageSample.zip)
