### ISSUE TITLE
TransportTests do not call TransportInfrastructure's Start and Stop methods

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#5099]
The `NServiceBusTransportTest` class that is the base for all of the transport tests does not call the `Start` and `Stop` methods on `TransportInfrastructure`. This causes a problem for any transports that have behavior that is required to be called from these methods.

I believe @danielmarbach hit this recently with ~~ASQ~~ SQS, and I've just run into it with RabbitMQ as well.

**Comment by danielmarbach** [comment]
Correct but it seems I've forgotten to raise an issue. I discussed this over slack and face to face conversations with you before my vacation. Thanks for raising it. It slipped off my radar.

**Comment by timbussmann** [comment]
👍 for fixing this.

**Comment by timbussmann** [comment]
since we've seen quite an impact on downstream transport tests due to calling start/stop, we've decided to not pull this into v7 at the current point.
