### ISSUE TITLE
No stage connector found for stage NServiceBus.Pipeline.IOutgoingPublishContext

### ISSUE THREAD

**Issue by johnfakeacc** [Particular/NServiceBus#5100]
Hi,

with SqlServerTransport enabled we cannot publish an event outside of a handler

We receive the following message:
**No stage connector found for stage NServiceBus.Pipeline.IOutgoingPublishContext**

[PubSubSample.zip](https://github.com/Particular/NServiceBus/files/1615907/PubSubSample.zip)
Example project attached.

Regards

**Comment by andreasohlund** [comment]
SqlTransport doesn’t have support for native pubsub so you have to keep
message driven subscriptions enabled.

What was the reason for disabling them?(remove the line to disable and it
should work)

**Comment by johnfakeacc** [comment]
because if I remove this line I get the following error:

**The selected persistence doesn't have support for subscription storage. Select another persistence or disable the message-driven subscriptions feature using endpointConfiguration.DisableFeature<MessageDrivenSubscriptions>()**

**Comment by johnfakeacc** [comment]
okay I got it.. I have to inlcude a subscription table via NServiceBus.Persistence.Sql ... otherwise no one can register ...

**Comment by andreasohlund** [comment]
Yes, sqlpersistence is a good choice when using the SqlTransport.

Let us know if that solves it for you.

**Comment by johnfakeacc** [comment]
great support thanks
