### ISSUE TITLE
Replace queue length checks with self-verification test

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5105]
workaround for https://github.com/Particular/NServiceBus/issues/5101 proposed by @andreasohlund 

> what if we removed the lenght checks from the runtime parts but instead added a "SelfVerification" test similar to https://github.com/Particular/NServiceBus/blob/c6355bbcfe0cae11a9af00cb6a6c50dffb6ea9bf/src/NServiceBus.AcceptanceTests/Core/SelfVerification/When_running_saga_tests.cs#L13

> This means that we can't add endpoints that generates to long queue names in the tests we ship but since we don't ship the verifications since they are in the core folder all downstreams are free to do what they like.

**Comment by SeanFeldman** [comment]
👍

**Comment by SeanFeldman** [comment]
And this strikes again. This time with SQS where a queue limit is 80 charachters and test names should be meaningful, but we're forced to truncate to 77 characters w/o an option of keeping the class names as-is and auto-generate queue names using some convention.

**Comment by dbelcham** [comment]
point of the issue can be found at https://github.com/Particular/NServiceBus/blob/c6355bbcfe0cae11a9af00cb6a6c50dffb6ea9bf/src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs#L29

**Comment by SeanFeldman** [comment]
Maybe I'm missing something, but why do we need a self verification test?

I was thinking to expand [`CoreTestSuiteConstraints`](https://github.com/Particular/NServiceBus/blob/090b796a6f27f885faef930978e1b02d3b20585b/src/NServiceBus.AcceptanceTests/Core/CoreTestSuiteConstraints.cs) with an additional field `EndpointNameMaximumLength` which could be set by default to 77 to keep backwards compatibility. Each downstream can override this constraint as they desire and get a standard exception thrown by ATT framework when that size is exceeded. @Particular/nservicebus-maintainers thoughts?

**Comment by andreasohlund** [comment]
>Maybe I'm missing something, but why do we need a self verification test?

The idea, as I recall, was to not check anything in the core at runtime and leave that up to the transports as they see fit.

The self verification test would be there to make sure that core doesn't ship acceptance tests that will violate the name length constraints of the most restrictive transport. Does that make any sense?

**Comment by timbussmann** [comment]
@SeanFeldman not sure how well that would work. The current concept of the `TestSuiteConstraints` doesn' t support something like default values which can be overwritten I think.
Keep in mind that the length is only relevant for transports, not for other downstreams running acceptance tests, so if at all, this should be covered by transports themselves ideally. The self-verification test was intended to just be a simple unit test, similar to several other tests like these to ensure that core follows this 77 character limit as it's the lowest limit across all transports and therefore core must make sure to not ship tests with longer names. This is kinda important as core doesn't own MSMQ transport anymore, and there is actually no good way to ensure core doesn't break MSMQ by using transport specific APIs.

**Comment by SeanFeldman** [comment]
Approach to take:
- Validate an option to override in a partial class a virtual method not to force any new tests on the downstreams
- Otherwise, remove length check from ATT and add an appropreate test to Core (MSMQ limits)
  - Add a note to the maintenace release work item to add that test to the appropreate downstreams (MSMQ, SQS, ASB, etc)

**Comment by timbussmann** [comment]
solved by #5232
