### ISSUE TITLE
Is it possible to edit the message body?

### ISSUE THREAD

**Issue by johnfakeacc** [Particular/NServiceBus#5107]
Hi,

we are using RabbitMQ as transport.
Is it possible to edit the body of a message if the message is in the error queue?

It would be nice if servicepulse could edit messages directly

Any hints or tips?

Regards

**Comment by SeanFeldman** [comment]
@johnfakeacc currently it's not possible to use ServicePulse to modify failed message body and resubmit it.

This feature has been [requested in the past](https://github.com/Particular/ServicePulse/issues/93) and we're aware of it.

There is a potential workaround outlined on our user group here: https://discuss.particular.net/t/modifying-failed-messages-prior-to-retry/280/4 that could help you in the meanwhile.
