### ISSUE TITLE
Timeouts triggering  immediately and infinitely when azure storage queues transport package is referenced

### ISSUE THREAD

**Issue by spinakr** [Particular/NServiceBus#5114]
Using timeout manager, either in a saga or using the `endpoint.ScheduleEvery()`-method, triggers hundreds of timeouts a second, when the "NServiceBus.Azure.Transports.WindowsAzureStorageQueues"-transport also is referenced. The issue is present when the endpoint is configured to use MSMQ transport and in-memory persistence, might be the same for other transport/persistence, this has not been explored.

The issue was found in an application where two endpoints where co-hosted in the same process, one using MSMQ transport and one using AzureStorageQueues. After investigating the problem seems to be present as long as the AzureStorageQueues-transport package is references in the application, even if it is not in use.

The following versions are used:
- "package id="NServiceBus" version="6.4.3" targetFramework="net461" "
- "package id="NServiceBus.Azure.Transports.WindowsAzureStorageQueues" version="7.4.1" targetFramework="net461" "

See [nsb-scheduling-msmq](https://github.com/spinakr/nsb-scheduling-msmq) for a minimal example demonstrating the problem.

Stackoverflow: [timeout-manager-retuning-timout-immediately](https://stackoverflow.com/questions/48420768/timeout-manager-retuning-timout-immediately)

**Comment by spinakr** [comment]
The problem is that the MSMQ endoint scans the AzureStorageQueuesTransport features, which messes up the timeout manager configuration. Most likely this [feature](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/DelayDelivery/PreventRoutingMessagesToTimeoutManager.cs) from the azure queues transport package.

Can be fixed by excluding the transport assembly from the MSMQ endpoints assembly scanner. 

Is this as designed? With features from different packages interfering?

**Comment by danielmarbach** [comment]
@spinakr by design all features that are enabled by default and are found in the application domain base directory are scanned and activated. That being said I think it would make sense to only enable the feature on the endpoint that actually requested delayed delivery. 

@Particular/azure-maintainers thoughts?

**Comment by SeanFeldman** [comment]
I always question the need to mix different transports. In this case you have two endpoints co-hosted in the same process, which causes an issue during assembly scanning. Answer provided on [StackOverflow](https://stackoverflow.com/questions/48420768/timeout-manager-retuning-timout-immediately) is accurate. Alternatively, you could move out your ASQ endpoint to its own host.

Let me know if this resolves the issue for you.

**Comment by spinakr** [comment]
This does solve my issue. We did co-host with different transports to bridge two application, where one run in azure and one on prem, thus the need for both in the same process. This has worked well, using nsb all the way, not having to create any webapis in between etc. has been great.

As long as multi-hosting is a thing I think this is a bit dangerous. If someone was to have an msmq endpoint relying on timeout manager, and then later extend it to co-host an ASQ-endpoint, it would introduce a quite critical bug, since hundreds of timeouts would suddenly trigger every second. But as you point out the docs does actually mention that excluding assemblies is important.

Anyways, thanks for great feedback!

**Comment by SeanFeldman** [comment]
@spinakr more than welcomed.
Just an FYI, there's also a [Bridge option](https://docs.particular.net/nservicebus/bridge/?version=bridge_2), but it means running different endpoints on their transports in different hosts and having an additional briddge process.
