### ISSUE TITLE
Make users aware of non writable saga properties to make sure they where not restricted by misstake

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#5115]
We have seen users making [saga data properties non writable by misstake](https://github.com/Particular/NServiceBus/issues/5103). While data is actually written properly to storage it causes confusion since they will have their default value when accessed from the saga handler.

We should consider ways to make users aware of this, roslyn analyzer, warnings, throwing at startup are all potential options.

**Comment by andreasohlund** [comment]
cc @dikoga

**Comment by HEskandari** [comment]
The PR is opened and was deferred to be picked up for v8 timeframe, as the introduced check is a breaking change.

**Comment by DavidBoike** [comment]
Saga analyzers to be released in NServiceBus 7.7 will include an analyzer for saga data properties that are not writeable. It will be a warning in NServiceBus 7.7 and an error in NServiceBus 8.0. This is the PR targeting master for NServiceBus 8: https://github.com/Particular/NServiceBus/pull/6234
