### ISSUE TITLE
Overriding the host identifier doesn't work always

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus#5116]
Hello

I've got several webjobs running and got them all configured to override the host identifier, but not every endpoint has the configured name. Sometimes it gets the original azure machine name again.

I've tried the code snippet which is documented [here](https://docs.particular.net/nservicebus/hosting/override-hostid#overriding-the-host-identifier)
and this but still there isn't a working solution

```
var host = Environment.MachineName;
var environment = "DEV|TST|ACC|PRD";
configuration
	.UniquelyIdentifyRunningInstance()
	.UsingNames(environment, host)
	.UsingCustomDisplayName(environment);
```
One thing to notice is that all the applications are hosted inside an App Service Environment

**Comment by SeanFeldman** [comment]
@JSCProjects if you're hosting using webjobs, `Environment.MachineName` should be avoided as it's a randon value that will be changing over time.  What I would suggest it to use `UsingCustomIdentifier` and identifier to be endpoint name with a value that would indicate instance ID ([`WEBSITE_INSTANCE_ID`](https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment) should be available with WebJobs as part of Azure WebApps).

Would that help you?

**Comment by JSCProjects** [comment]
Ok thanx I will fix this in our webjobs

**Comment by timbussmann** [comment]
Seems like this issue has been resolved. I'm going to close this issue then for now.
