### ISSUE TITLE
startup diagnostics blows up at startup and gives the wrong message on how to fix it

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5117]
scenario

 * in a web app
 * cant mappath to App_Data
 * using a non default logger. ie have overridden logging with `LogManager.Use<MyFactory>()`

At startup we get blow up with the exception from here https://github.com/Particular/NServiceBus/blob/release-7.0/src/NServiceBus.Core/Hosting/StartupDiagnostics/Host.cs#L69

```
Detected running in a website and attempted to use HostingEnvironment.MapPath(\"~/App_Data/\")
 to derive the logging path. {reason}. To avoid using HostingEnvironment.MapPath to derive the
 logging directory you can instead configure it to a specific path using 
LogManager.Use<DefaultFactory>().Directory(\"pathToLoggingDirectory\");
```

but we have already override `LogManager.Use<>`.

The reason for this is that HostStartupDiagnostics re-uses  `Host.GetOutputDirectory()` https://github.com/Particular/NServiceBus/blob/release-7.0/src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnostics.cs#L40
but that use can in no way re-use the new replaced logging factory

i would assume the context of what is calling `Host.GetOutputDirectory` needs to be passed in so the error message can be tailored.  also startup diagnostics should have a simpler way of overriding the target dir, at least simpler than replacing the whole writer https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics-writing-to-other-targets

**Comment by andreasohlund** [comment]
Yea we should fix the logging. Regarding a better way to turn it off it's kind of by design since we don't want it to easy to turn it off.

Out of curiosity what's the reason for `App_Data` not being usable? Is there something we can detect to avoid having the diagnostics throw?

**Comment by SimonCropp** [comment]
> Out of curiosity what's the reason for App_Data not being usable? Is there something we can detect to avoid having the diagnostics throw?

in this case it is deployed to sharepoint in a sendonly endpoint. so i suspect there is no appdata dir.

> Regarding a better way to turn it off

I didnt request that. i requested "a simpler way of overriding the target dir"

**Comment by andreasohlund** [comment]
>I didnt request that. i requested "a simpler way of overriding the target dir"

`endpointConfiguration.SetDiagnosticsPath("myCustomPath");` ?

https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics

**Comment by SimonCropp** [comment]
sorry. i dont know how i missed that. so just the exception then :)

**Comment by timbussmann** [comment]
I wonder whether the diagnostic logic should not throw an exception in case it's unable to determine an output path and to log an error instead? Thoughts @SimonCropp?

**Comment by SimonCropp** [comment]
I am happy with the throw exception.

**Comment by timbussmann** [comment]
with 7.1 the endpoint will no longer fail to start if it can't write the diagnostic file. There will be a log error in that case, which will have a more useful log text than the current exception. Thanks for raising this 👍
