### ISSUE TITLE
Native ASP.Net Core dependency Injection

### ISSUE THREAD

**Issue by cwoolum** [Particular/NServiceBus#5128]
Are there any plans to support native Asp.Net Core dependency injection? The reliance on a 3rd party DI is causing me some problems.

**Comment by andreasohlund** [comment]
It's on our radar but we need to first drop our requirement/support for property injection to be able to support it.

It should work together with our internal container as this sample demonstrates

https://docs.particular.net/samples/web/send-from-aspnetcore-webapi/

>The reliance on a 3rd party DI is causing me some problems.

Can you elaborate on the issues caused?

What version of NServiceBus are you using?

**Comment by cwoolum** [comment]
I am essentially trying to configure NServiceBus as a reusable extension that i can add to my microservices. My extension method takes in IWebHostBuilder and should normally be able to configure everything from there. The problem though is that IContainer does not exist at this point if I try to resolve it via DI. If I put the creation of the Endpoint inside of the registration function, the call to Start the EndpointInstance locks up and the application never runs.

**Comment by andreasohlund** [comment]
Are you using the same approach as mentioned here https://discuss.particular.net/t/support-for-microsoft-extensions-dependencyinjection/129/3 ?

**Comment by andreasohlund** [comment]
@cwoolum any luck with the approach mentioned in https://github.com/Particular/NServiceBus/issues/5128#issuecomment-372813239 ?

**Comment by cwoolum** [comment]
No, if I don't set some sort of container reference, I'm not able to resolve any dependencies and my handler blows up when receiving a message. The next comment down basically says the same thing.

**Comment by andreasohlund** [comment]
>No, if I don't set some sort of container reference

Ah, now I thing I get it. You have to specify an external container since NServiceBus require property injection to work and this is currently not supported by the ASP.net core DI.

Does this make sense?

**Comment by cwoolum** [comment]
Yeah, that's what I figured. Thanks!

**Comment by andreasohlund** [comment]
Even though we are looking at ditching property injection that won't happen in the near future so until ASP.Net Core DI adds support for property injection we have to consider it not supported.

Is it ok to close this issue?

**Comment by cwoolum** [comment]
Yes, thanks for your help!

**Comment by twenzel** [comment]
Please have a look at [NServiceBus.MSDependencyInjection](https://github.com/twenzel/NServiceBus.MSDependencyInjection).

**Comment by lailabougria** [comment]
Hi @cwoolum,

We've been working on integrating with the Dependency Injection implementation that's built into ASP.NET Core which we thought you'd be interested to know about. You can find out on the work being done in this area [here](https://particular.net/blog/support-for-net-core-3).

**Comment by porsche73rs** [comment]
Does that linked page say July 14, 2021? Is that correct?

**Comment by lailabougria** [comment]
@porsche73rs It's not, thanks for pointing that out 👍
