### ISSUE TITLE
Adding/Replacing connectors and behaviors in the pipeline silently fails when the passed ID is invalid

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#5133]
As shown by this PR https://github.com/Particular/docs.particular.net/pull/3691

The PipelineSettings API fails silently:
- When using the `Register`-API with an already existing ID
- When using the `Replace`-API with a non-existing ID

In any of the above cases, an exception should be thrown so the user can act accordingly.

A new ´RegisterOrReplace´-API will be introduced to cover adding or replacing the behavior/connector without possible failure for cases in which the user is unsure if the behavior/connector will be in place or not.

**Comment by danielmarbach** [comment]
If we'd throw would we then also need a `ReplaceIfExists` kind of API?

**Comment by andreasohlund** [comment]
Sounds resonable to me
