### ISSUE TITLE
Brokered message has been disposed

### ISSUE THREAD

**Issue by xxeasterxx** [Particular/NServiceBus#5142]
When trying to send messages to a queue, it throws brokered message has been disposed exception. This happens only after sending messages 2 or 3 times successfully. Queue is created through enable installers. Do I need to explicitly configure the queue?

**Comment by andreasohlund** [comment]
What transport is this? (Is it the Azure ServiceBus one?)

> Do I need to explicitly configure the queue?

Since the first few messages seems to work I don't think this is the issue

**Comment by xxeasterxx** [comment]
Yes using Azure Service Bus transport. Yes it only work for the first time. After that it will throw the error. FYI, this queue is just on its own without any service handling (message handler). This queue will be used for Azure function service bus trigger.

**Comment by xxeasterxx** [comment]
I believe it has nothing to do with the queue since it occur on outgoing message. Has configured the pipeline bahaviour to catch outgoing message exceptions.

**Comment by andreasohlund** [comment]
What versions of nsb and the transport are you using?

@Particular/azure-maintainers ideas on how to troubleshoot this?

**Comment by SeanFeldman** [comment]
@xxeasterxx could you please:
1. Post the full exception
1. Provide configuration of the queue (NServiceBus / ASB)

**Comment by xxeasterxx** [comment]
public static EndpointConfiguration CreateBaseConfiguration(string endpointName, string servicebusConnString, bool subscribeAllEvents = true)
        {
            var endpointConfiguration = new EndpointConfiguration(endpointName);
            endpointConfiguration.UseSerialization<JsonSerializer>();
            endpointConfiguration.EnableInstallers();
            endpointConfiguration.SendFailedMessagesTo("error");
            var recoverability = endpointConfiguration.Recoverability();
            recoverability.Delayed(
                delayed =>
                {
                    delayed.NumberOfRetries(5);
                    delayed.TimeIncrease(TimeSpan.FromMinutes(5));
                });

            var pipeline = endpointConfiguration.Pipeline;
            pipeline.Register(
                behavior: new IncomingMsgErrorHandlingBehavior(),
                description: "Manages icoming msg exceptions.");
            pipeline.Register(
                behavior: new OutgoingMsgErrorHandlingBehavior(),
                description: "Manages outgoing msg exceptions.");

            endpointConfiguration.Conventions()
                .DefiningMessagesAs(t => t.Namespace != null && t.Namespace.StartsWith(_MessageTypeName));

            if (subscribeAllEvents)
                endpointConfiguration.Conventions()
                    .DefiningEventsAs(t => t.Namespace != null
                        && t.Namespace.StartsWith(_MessageTypeName)
                        && t.Namespace.EndsWith("Event"));

            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString(servicebusConnString);
            transport.UseForwardingTopology();
            transport.Queues().EnablePartitioning(true);
            transport.Queues().EnableDeadLetteringOnMessageExpiration(true);
            
            return endpointConfiguration;
        }

//in the service creating endpoint code
private async Task CreateReceivingEndpointAndStartAsync()
{
              var baseConfig =
                    NServiceBusConfigurationManager.CreateBaseConfiguration(endpointName, sbConnString, 
                   false);
             baseConfig.UsePersistence<InMemoryPersistence>();
              ....

                var endpointInstance = await Endpoint.Create(baseConfig);
                await endpointInstance.Start();    
}

//in the handler code
        private IMessageHandlerContext _messageHandler;
        public async Task Handle(DTO message, IMessageHandlerContext context)
        {
                  .......
                 _messageHandler.Send("queueName", message);
         }

**Comment by SeanFeldman** [comment]
By default the transport is configured with `LockDuration` of [30 seconds](https://docs.particular.net/transports/azure-service-bus/configuration/full#controlling-entities-queues) and `Prefetching` of [20 messages](https://docs.particular.net/transports/azure-service-bus/configuration/full#controlling-connectivity-message-receivers). With a handler such as the one you've shared, all messages should be processed within 30 seconds w/o any problems.

The exception thrown by the ASB client is not about lost lock, but a disposed `BrokeredMessage` which should be [floated into the transports' context](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/d1eab479736fe5ebee982f7b82e344e332eaa05c/src/Transport/Sending/DefaultOutgoingBatchRouter.cs#L101).

1. What specific version of the transport are you using?
1. Was this happening before or this is a recent thing? What has changed if it worked before?
1. `IncomingMsgErrorHandlingBehavior` and `OutgoingMsgErrorHandlingBehavior` - what do they do?
1. Could you share a repo with a repro code?

Couldn't not to notice this  code:
```c#
private IMessageHandlerContext _messageHandler;
```
Is `_messageHandler` used for anything other than sending a command? If no, what's the purpose of that member field?

**Comment by xxeasterxx** [comment]
1. ` <package id="NServiceBus" version="6.4.3" targetFramework="net461" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.2.11" targetFramework="net461" />`

2. This is a new code I've implemented to send to only one standalone queue, not sent to service.

3. They are implemented just to catch incoming/outgoing messages exceptions. Because there's an issue of there's messages in the queue but it's not processing message or sent to deadletter (when deployed to production).

4. Sorry, it's not convenient to share the code.

The _messageHandler is to be used in other parts of the code to send to queue. Exceptions occur in other parts of code.
`private IMessageHandlerContext _messageHandler;

        public async Task Handle(DTO message, IMessageHandlerContext context)
        {
                  .......
                 _messageHandler=context;
                await SendToQueue();
         }

        private async Task SendToQueue(){
                  ...
                  _messageHandler.Send("queueName", message); <---Exception
        }
`

**Comment by danielmarbach** [comment]
Are you reusing the context by any chance? Or missing an await statement in
the call chain?

Could you paste the code from the behaviors as well? If privacy is a
concern you can share the code over support at particular dotnet

xxeasterxx <notifications@github.com> schrieb am Di., 10. Apr. 2018, 06:30:

**Comment by SeanFeldman** [comment]
> Sorry, it's not convenient to share the code.

@xxeasterxx let me clarify my ask - I'm not asking to share your production code. I am asking to provide a minimal reproduction code that would allows us to see what's happening. If you call a mechanic and ask for a help about a vehicle that won't start yet refuse to bring the car in, there's not going to be a lot of progress 🙂

**Comment by xxeasterxx** [comment]
@danielmarbach yes, I'm reusing the context. Even if I put await, I got the same error.
@SeanFeldman Sorry for misunderstanding. Above should be all the minimal reproduction you'll need.
Let me just arrange the code again

public static EndpointConfiguration CreateBaseConfiguration(string endpointName, string servicebusConnString, bool subscribeAllEvents = true)
        {
            var endpointConfiguration = new EndpointConfiguration(endpointName);
            endpointConfiguration.UseSerialization<JsonSerializer>();
            endpointConfiguration.EnableInstallers();
            endpointConfiguration.SendFailedMessagesTo("error");
            var recoverability = endpointConfiguration.Recoverability();
            recoverability.Delayed(
                delayed =>
                {
                    delayed.NumberOfRetries(5);
                    delayed.TimeIncrease(TimeSpan.FromMinutes(5));
                });

            var pipeline = endpointConfiguration.Pipeline;
            pipeline.Register(
                behavior: new IncomingMsgErrorHandlingBehavior(),
                description: "Manages icoming msg exceptions.");
            pipeline.Register(
                behavior: new OutgoingMsgErrorHandlingBehavior(),
                description: "Manages outgoing msg exceptions.");

            endpointConfiguration.Conventions()
                .DefiningMessagesAs(t => t.Namespace != null && t.Namespace.StartsWith(_MessageTypeName));

            if (subscribeAllEvents)
                endpointConfiguration.Conventions()
                    .DefiningEventsAs(t => t.Namespace != null
                        && t.Namespace.StartsWith(_MessageTypeName)
                        && t.Namespace.EndsWith("Event"));

            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString(servicebusConnString);
            transport.UseForwardingTopology();
            transport.Queues().EnablePartitioning(true);
            transport.Queues().EnableDeadLetteringOnMessageExpiration(true);
            
            return endpointConfiguration;
        }

//in the service creating endpoint code
private async Task CreateReceivingEndpointAndStartAsync()
{
              var baseConfig =
                    NServiceBusConfigurationManager.CreateBaseConfiguration(endpointName, sbConnString, 
                   false);
             baseConfig.UsePersistence<InMemoryPersistence>();
                var endpointInstance = await Endpoint.Create(baseConfig);
                await endpointInstance.Start();    
}

//in the handler code
        private IMessageHandlerContext _messageHandler;
        public async Task Handle(DTO message, IMessageHandlerContext context)
        {
                 _messageHandler=context;
                await SendToQueue();
         }

private async Task SendToQueue(){
                  _messageHandler.Send("queueName", message); <---Exception

        }

**Comment by SeanFeldman** [comment]
@xxeasterxx here's what I mean.
```c#
pipeline.Register(
                behavior: new IncomingMsgErrorHandlingBehavior(),
                description: "Manages icoming msg exceptions.");
            pipeline.Register(
                behavior: new OutgoingMsgErrorHandlingBehavior(),
                description: "Manages outgoing msg exceptions.")
```
is that code somehow interfearing with the transport? No idea as the source of the code is not available. Will your endpoint fail to send a message if you remove those two behaviors?

Also, I see no code where your routing would be defined. Is it even defined? Where is it defined?
I hope you can see why I am asking to provide a simple repro. If you're not comfortable with doing so over a public repo, you can share a private repo.

**Comment by xxeasterxx** [comment]
@SeanFeldman the code is added after I implement the sending.. It's to capture exceptions only, just added this code to see why it does not send to queue so I can get the full exception as I'm not awaiting. I've sent the repro code to support email.

**Comment by SeanFeldman** [comment]
Contininuing interaction on a support case.
