### ISSUE TITLE
Bus.Defer allow delay events

### ISSUE THREAD

**Issue by matiii** [Particular/NServiceBus#5151]
I use nsb 5.2.24 version. Method Defer allow delay events what cause creation of duplicate messages on queue. For correctness point of view if Defer method get event message it should throw NotSupportedException ([because it is not supported](https://docs.particular.net/nservicebus/messaging/delayed-delivery?version=core_5)).

**Comment by andreasohlund** [comment]
>Method Defer allow delay events what cause creation of duplicate messages on queue

Can you clarify what you mean by duplicate messages?

`Bus.Defer(new MyMessage())` means that the message passed will be sent to the local endpoint with the specified delay so a new message being created is to be expected? 

>For correctness point of view if Defer method get event message it should throw NotSupportedException (because it is not supported).

Agreed, that said v5 is going out of support in just about 5 month (https://docs.particular.net/nservicebus/upgrades/support-policy) so we're unlikely to prioritize fixing this.

**Comment by matiii** [comment]
>> Method Defer allow delay events what cause creation of duplicate messages on queue

>Can you clarify what you mean by duplicate messages?

Scenario based on [throttling messages](https://docs.particular.net/samples/throttling/?version=core_5):

1. Setup handler to consume 2 events per sec
2. Incoming event cause error (counter = 1, # messages in tick)
3. Recoverability retry event (again cause error), counter = 2
4. Recoverability retry event (again cause error), counter = 3
5. Defer method create duplicate message with new messageid
6. Recoverability retry event (again cause error), counter = 4
7. Defer method create duplicate message with new messageid

The result is that 2 duplicated messages are on the queue.

**Comment by andreasohlund** [comment]
Hmm, that sounds worrying, what transport are U using?

Can you also confirm that you are not using the `Unreliable` transport transaction mode?

https://docs.particular.net/transports/transactions?version=core_5#transactions-unreliable-transactions-disabled

Can you share the code that is doing the `Bus.Defer` ?

**Comment by matiii** [comment]
I use MSMQ. Unreliable transport transaction mode is disabled.

```
using System;
using NServiceBus;
using NServiceBus.Logging;
using NServiceBus.Pipeline;
using NServiceBus.Pipeline.Contexts;
using Scb.Nsb.Messages.Events;
using Scbno.Nsb.EventsProcessor.Contract;

namespace Scbno.Nsb.EventsProcessor.Throttling
{
    public class ThrottlingTelefinansBehavior : IBehavior<IncomingContext>
    {
        private readonly IBus _bus;
        private readonly ITelefinansConfiguration _configuration;
        private readonly IIncomingContextFacade _contextFacade;

        private readonly ILog _logger = LogManager.GetLogger(typeof(ThrottlingTelefinansBehavior));

        private static readonly object Locker = new object();
        private static volatile string _currentTick = DateTime.UtcNow.ToString("G");
        private static volatile int _counter;

        public ThrottlingTelefinansBehavior(
            IBus bus,
            ITelefinansConfiguration configuration,
            IIncomingContextFacade contextFacade)
        {
            _bus = bus;
            _configuration = configuration;
            _contextFacade = contextFacade;
        }

        public void Invoke(IncomingContext context, Action next)
        {
            if (_configuration.ThrottlingIsEnabled && _configuration.IsWorkerEnabled &&
                _contextFacade.GetMessageType(context) == typeof(ApplicationStatusChangedEvent) &&
                _contextFacade.SubmitingSystem(context) == _configuration.SubmitingSystem &&
                _configuration.RequestShouldBeSend(_contextFacade.GetMessage<IApplicationStatusChangedEvent>(context)))
            {
                lock (Locker)
                {
                    if (_currentTick == DateTime.UtcNow.ToString("G")) //increase in the same tick
                    {
                        _counter++;
                    }
                    else //reset counter
                    {
                        _currentTick = DateTime.UtcNow.ToString("G");
                        _counter = 1;
                    }
                    
                    _logger.DebugFormat("For {0:G} datetime and {1} submiting system counter is equal {2}",
                        DateTime.UtcNow, _contextFacade.SubmitingSystem(context), _counter);
                    
                    if (_counter > _configuration.MaxRequestPerSecond)
                    {
                        DelayMessage(context);
                        return;
                    }
                }
            }

            next();
        }

        private void DelayMessage(IncomingContext context)
        {
            _logger.DebugFormat("Delay message for {0} sec id: {1} for counter: {2}",
                _configuration.DelaySeconds,
                _contextFacade.MessageId(context),
                _counter);

            string replyAddress;

            if (_contextFacade.Headers(context).TryGetValue(Headers.ReplyToAddress, out replyAddress))
            {
                _bus.SetMessageHeader(_contextFacade.GetMessage(context), Headers.ReplyToAddress, replyAddress);
            }

            _bus.Defer(TimeSpan.FromSeconds(_configuration.DelaySeconds), _contextFacade.GetMessage(context));
        }
    }
}
```

**Comment by andreasohlund** [comment]
Think I see the issue, if you're not running with transaction scopes on on `_bus.Defer(TimeSpan.FromSeconds(_configuration.DelaySeconds), _contextFacade.GetMessage(context));` will run outside of the scope of the receive transaction and will commit immediately causing a duplicate message.

https://docs.particular.net/transports/transactions?version=core_5#transactions-transaction-scope-distributed-transaction

Could this be it?

Side note: Can you elaborate on use case for this custom delay? Can't you configure the NServiceBus bultin retries to handle this for you?

https://docs.particular.net/nservicebus/recoverability/?version=core_5

**Comment by matiii** [comment]
For such modified method

```
private void DelayMessage(IncomingContext context)
        {
            _logger.DebugFormat("Delay message for {0} sec id: {1} for counter: {2}",
                _configuration.DelaySeconds,
                _contextFacade.MessageId(context),
                _counter);

            if (_logger.IsDebugEnabled)
            {
                bool transactionIsEnabled = Transaction.Current != null;

                _logger.DebugFormat("Transaction is enabled: {0} for delay message.", transactionIsEnabled);
            }

            string replyAddress;

            if (_contextFacade.Headers(context).TryGetValue(Headers.ReplyToAddress, out replyAddress))
            {
                _bus.SetMessageHeader(_contextFacade.GetMessage(context), Headers.ReplyToAddress, replyAddress);
            }

            _bus.Defer(TimeSpan.FromSeconds(_configuration.DelaySeconds), _contextFacade.GetMessage(context));
        }
```

I get log: Transaction is enabled: True for delay message.

**Comment by andreasohlund** [comment]
That doesn't guarantee us enlisting 

https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Transports/Msmq/MsmqMessageSender.cs#L61

in case you have called `transactionSettings.DisableDistributedTransactions();` but you haven't done that right?

**Comment by matiii** [comment]
> in case you have called transactionSettings.DisableDistributedTransactions(); but you haven't done that right?

I haven't.

To sum up.

In order to enlisting for transaction is disabled defer method create duplicate messages ?

What if [transport transaction](https://docs.particular.net/transports/transactions?version=core_5#transactions-transport-transaction) is enabled ? The behavior of defer method will be the same ?

**Comment by andreasohlund** [comment]
>Incoming event cause error (counter = 1, # messages in tick)

Where does this exception happen? in the message handler for the event?

I'll try to reproduce this on my end

**Comment by matiii** [comment]
> Where does this exception happen? in the message handler for the event?

Yes, in the message handler

**Comment by andreasohlund** [comment]
Found the issue:

Since you're just "registering" the pipeline behavior it will go after all the builtin behaviors. Invoking handlers is one of them.

This means that your throttling behavior gets invoked after the handlers have fired and is causing duplicates.

To place your behavior before handler invocation add the following registration class as a nested class inside your behavior (adjust the type as needed)

```
  public class Registration : RegisterStep
        {
            public Registration():base("Throttling",typeof(ThrottlingBehavior),"Provides throttling")
            {
                InsertBefore(WellKnownStep.InvokeHandlers);
            }
        }
```

Then register it like this:

`busConfiguration.Pipeline.Register<ThrottlingBehavior.Registration>();`

Let me know if that does the trick?

**Comment by matiii** [comment]
I have done it already.

```
public class ThrottlingRegistrationStep: RegisterStep
    {
        public ThrottlingRegistrationStep() 
            : base("TelefinansThrottling", typeof(ThrottlingTelefinansBehavior), "Telefinans throttling messages.")
        {
            InsertBefore(WellKnownStep.InvokeHandlers);
        }
    }

configuration.Pipeline.Register<ThrottlingRegistrationStep>();
```

**Comment by matiii** [comment]
I see this case is not obvious. I attached some screens from service insight maybe will help with investigate it. It shows duplicate messages.

![nsb1](https://user-images.githubusercontent.com/4460700/39917821-0299d4e6-550f-11e8-942f-9e7dcb8edfb7.PNG)
![nsb2](https://user-images.githubusercontent.com/4460700/39917822-02b9c8b4-550f-11e8-8e56-6607a973a9dc.PNG)
![nsb3](https://user-images.githubusercontent.com/4460700/39917823-02d726b6-550f-11e8-86a0-0ef2ec6a9660.PNG)


```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceInsight.SequenceDiagram.Diagram.SequenceDiagramLayoutManager.ArrowLayout.Position(Arrow arrow) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\Diagram\LayoutManager.cs:line 135
   at ServiceInsight.SequenceDiagram.Diagram.SequenceDiagramLayoutManager.PerformLayout(IDiagram diagram) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\Diagram\LayoutManager.cs:line 55
   at ServiceInsight.SequenceDiagram.Diagram.DiagramControl.PerformLayout() in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\Diagram\DiagramControl.cs:line 82
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by andreasohlund** [comment]
@matiii any news on this one?

**Comment by matiii** [comment]
> New copy of event with id Y is deferred and will later be processed and also sent to the audit queue

Now I see how it works. Previously I thought that defer method works in message scope. It just create new one. I have idea how to design it correctly, I am going to throttling event producer (handler of command). 

From my side issue can be closed.

Thanks for great support.

**Comment by andreasohlund** [comment]
Got it, glad we go to the bottom of this. Just reach out again if needed
