### ISSUE TITLE
It would be nice to also have an option to append a diagnostics writer

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5158]
https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics-writing-to-other-targets

I want to leave the existing functionality in place and also write to an extra location

**Comment by SimonCropp** [comment]
@dbelcham we have a central diagnostics server (in this case seq). we want that information stored there as well as on the normal disk location. note that this is in an organisation logging lib, so as with nsb, it is not aware of the consuming app type. so we would like to leverage the nsb logic of doing a best guess a diagnostics  location

**Comment by timbussmann** [comment]
the current API also acts as some kind of safeguard to allow disabling diagnostics completely. With your suggested API changes, that would have to be taken into account.

I'll add this to the feature backlog so it can be picked up by future maintenance releases.
