### ISSUE TITLE
Issue with delayed retries and behavior that alters message type

### ISSUE THREAD

**Issue by itzamna314** [Particular/NServiceBus#5160]
I'm running into an issue with delayed retries and a behavior that changes the incoming message type.  When the initial message is sent, I have a custom behavior that wraps the outgoing message in a generic wrapper for compression.  This also allows me to write the compressed/serialized message into a DataBus property in case the message is too big for my queue transport.  When the receiving endpoint gets the message, the corresponding incoming behavior unwraps the message and sends it as the original type.  The whole behavior looks like this:

Endpoint A sends message of type Foo -> Outgoing behavior wraps foo in a message of type Wrapper -> Incoming behavior unwraps message of type Wrapper and forwards message of type Foo -> Endpoint B receives a message of type Foo.

That all works fine.  Where the problem occurs is if Endpoint B throws an exception, and NServiceBus does a delayed retry.  In that case, the original message's bits of type Wrapper get retried, but with the unwrapped message type in the type header.  This leads to:

A sends Foo
Outgoing behavior wraps Foo in type Wrapper
Incoming behavior unwraps Wrapper and forwards Foo
B receives Foo
B throws an error due to a transient conditition
B automatically retries until is performs a delayed retry
Incoming pipeline gets the original message bits, but with a type header of Foo.  It attempts to deserialize a Wrapper into a Foo, which produces a Foo with all of its fields defaulted.
Incoming behavior sees it isn't receiving a Wrapper, and passes along the empty Foo
B receives an empty, invalid Foo.  The original contents of Foo have been lost.

I've tried using a custom retry policy that explicitly calls `RecoverabilityAction.DelayedRetry(...)`, but I get the same error.  As a workaround, I'm catching the known transient exceptions, and then explicitly re-sending the message to the receiving endpoint (B) while preserving its reply-to information.  That works, but I would like to be able to use the built-in recoverability mechanism.  Is there any way to make delayed retries preserve the original message's type header?

**Comment by itzamna314** [comment]
Azure Storage Queues

**Comment by bording** [comment]
@itzamna314 At this point what I'd recommend you try is in your custom incoming behavior, catch any exceptions coming from the the call to `next` and revert your header change there. Then re-throw the exception.

**Comment by itzamna314** [comment]
@bording I'll give that a try, thanks!

**Comment by bording** [comment]
@itzamna314 Any news? Were you able to get it working?

**Comment by timbussmann** [comment]
I'm going to close this issue for now as there doesn't seem to be any activity on this anymore. @itzamna314 please feel free to reopen this issue (or contact us via support@particular.net) in case you still encounter this problem.

**Comment by itzamna314** [comment]
Sorry for the long inactivity.  Re-setting the message type on exceptions did the trick.  Thanks!
