### ISSUE TITLE
startup diagnostics blows up at startup in service fabric

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus#5164]
This came in through live chat: 

apparantly startup diagnostics is trying to create a directory on the disk called .diagnostics. This blows up as apps hosted in service fabric are not allowed to create folders on the disk on the host machine.

The user worked around it by manually creating the folder on the machine that's hosting the SF node, but this is only a temporal solution, when the app moves to a different node on the cluster it will break again.

One potential solution could be to provide an appender that writes somewhere else (e.g. an azure storage blob)

**Comment by andreasohlund** [comment]
Replaces -
https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics-writing-to-other-targets

**Comment by timbussmann** [comment]
@yvesgoeleven is there a reliable way of detecting that an application is hosted in SF?

One things confuses me though: You mentioned that the app blows up, but afaik we're catching exceptions when writing the diagnostic file like this:

            try
            {
                await diagnosticsWriter(data)
                    .ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                logger.Error("Failed to write startup diagnostics", exception);
            }

**Comment by yvesgoeleven** [comment]
@timbussmann no, any arbitrary exe can be hosted there

I haven't tested myself. Could ofcourse be that 'blowing up' means, I have an error entry in my log ;)

**Comment by krosenko-at-starbucks** [comment]
I also ran into this issue. The work-around I used was:

```csharp
            endpointConfiguration.SetDiagnosticsPath(Environment.GetEnvironmentVariable("Fabric_Folder_App_Log"));
```

Perhaps documenting that publicly would help.

**Comment by timbussmann** [comment]
@krosenko-at-starbucks just to verify my understanding of the issue based on my questions on the previous comment: Did you see the endpoint actually failing or did you notice the error messages in the log?

**Comment by krosenko-at-starbucks** [comment]
Neither, I saw the process writing files to a directory it should not have been writing to, and searched for a way to make it write to an allowed location instead. But I was running locally, I did not try deploying to a prod cluster yet. It undoubtedly would have failed if I had tried.

**Comment by timbussmann** [comment]
@krosenko-at-starbucks we have documented the workaround you mentioned here: https://docs.particular.net/nservicebus/hosting/startup-diagnostics do you feel there is some essential information missing from that page?
by the way, the diagnostics file is supposed to help when trying to identify reported problems, however, as this is non-critical, there is no impact on the endpoint itself if it is unable to write to the target directory.

**Comment by krosenko-at-starbucks** [comment]
Right, that is the documentation I used for my work-around. I was saying maybe note that in the documentation on hosting solutions or some other location that Service Fabric users are likely to read, so they can configure it from the start instead of having to debug it later.

**Comment by timbussmann** [comment]
I've added a section to the hosting document to capture requirements on the hosting environments here: https://github.com/Particular/docs.particular.net/pull/4276. I hope this addresses your suggestions. If you feel there's something missing, please feel free to reopen this issue or to raise a PR to that doco page directly. Thanks for the feedback 👍
