### ISSUE TITLE
sender side distribution - duplicate event distribution

### ISSUE THREAD

**Issue by chandmk** [Particular/NServiceBus#5167]
V6, msmq transport
using NServiceBus.Persistence.MongoDb
Trying to use sender side distributor
Events are being sent to each node, causing duplicate message processing.
Not sure if we are missing something obvious.

**Comment by andreasohlund** [comment]
Hi @chandmk can you share your logical and physical mappings?

https://docs.particular.net/transports/msmq/sender-side-distribution

Also noticing that you're on a community persister, would it be possible to temporarily switch to eg. the [InMemory persister](https://docs.particular.net/persistence/in-memory) just to rule out any issue with the subscription storage it self?

**Comment by chandmk** [comment]
Closing this issue.  Our setup is more complicated.  But in a nutshell,  We have an NSB5 process using MongoDB persister publishing into NSB6 subscribers.  It looks like we cannot mix and match sender side distributor between NSB5 and NSB6 implementations.

**Comment by timbussmann** [comment]
hey @chandmk , you mentioned that you are using MongoDB persistence. We would love to chat a little bit about your usage of MongoDB. If you'd be willing to help us by answering some questions, please contact me via tim.bussmann@particular.net or let me know how we can get in touch wit you.
