### ISSUE TITLE
Question : how do i integrate with LightInject ?

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#5176]
Hi,
i saw nservicebus internally switched to LightInject but i can't find any integration package to use it in my projects, is it correct ? i would really like to try LightInject 😄

**Comment by HEskandari** [comment]
Where did you see this? 

NServiceBus uses Autofac as far as I could remember (a version of which is ILMerged in the core assembly). 

There is, however, a community project for LightInject which you can find [here](https://github.com/seesharper/LightInject.NServiceBus) but it is not developed nor maintained by us. I think it is owned by the author of the LightInject framework. There was a discussion a while back which you can find [here](https://github.com/Particular/NServiceBus/issues/2690).

**Comment by valeriob** [comment]
Yea i followed those discussions.
I've been using autofac for many years, and i'm checking if i can adopt LightInject because it's very similar to autofac as features, but with even better performances.
I really hope an integration will be released 😄

**Comment by timbussmann** [comment]
are you noticing any performance impacts from autofac?

**Comment by valeriob** [comment]
I've not measured myself, just checking if it's time to change my default goto Autofac with something else for new projects, since i'm using very few features, mainly constructor injection and some lambda factories.
I like the perfomance of LightInject and the low allocation overhead
https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/index.html

**Comment by timbussmann** [comment]
I can understand the motivation of using a lighter container than the feature rich containers like autofac or ninject. But as @HEskandari mentioned, there are currently no plans to release a LightInject adapter from our side. 

If you're looking for faster performance, maybe the [Simple Injector](https://docs.particular.net/nservicebus/dependency-injection/simpleinjector) adapter is of interest to you. If you really want to use LightInject, implementing the required abstraction to get it working with NServiceBus shouldn't be very difficult. 

We certainly try to keep track of the current IOC container landscape. As there are quite a lot of IOC containers available, it would be become quite a maintenance burden to support every container out there, so we try to provide support for the most commonly used ones. So far, you're the first asking for LightInject but if it's popularity starts to grow, it might be that we have to reevaluate that decision (e.g. there are quite a few users interested in using the new microsoft di container implementation).
