### ISSUE TITLE
Mandatory message marking

### ISSUE THREAD

**Issue by HakanKaraoglu** [Particular/NServiceBus#5180]
Hi, I'am using NSB 5 version. I have a questions. 
Scenario : 
1- Exchange exists, not exists Queue : message is lost
2- Exchange not exists, exists Queue : the message failed while throwing the exchange.
Question : 
We can mark messages in Rabbitmq as mandatory. How can I do the same with NSB. If the discarded message can not be delivered to the queue, it should throw me an error and I must save it in the log file so I do not lose my message to process it again

**Comment by bording** [comment]
@HakanKaraoglu Which version of the RabbitMQ transport package are you using? The transport should already be using the mandatory flag when sending messages to the broker.

Can you explain more about your scenario 1, perhaps provide a small repro sample that demonstrates the behavior you're seeing?

**Comment by bording** [comment]
> Firstly, We use NServiceBus.Transports.RabbitMQ 3.0.0.0 version

That looks like an assembly version, which we set to 3.0.0.0 for all the 3.x releases. What is the NuGet package version you're using?

In the scenario you're describing, you should be seeing an error. We do set the mandatory flag when sending commands.

**Comment by bording** [comment]
@HakanKaraoglu Is there anything else here I can help with? Have you been able to try a newer version of the transport?

**Comment by bording** [comment]
@HakanKaraoglu I'm going to go ahead and close this issue. Feel free to re-open it if you need more information.
