### ISSUE TITLE
Add a generic SettingsHolder.Set

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5182]
so this 
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Settings/SettingsHolder.cs#L204

```
public void Set<T>(object value)
```

It would be nice to have a 

```
public void Set<T>(T value)
```

This way instead of doing this

```
var settings = new SettingsHolder();
var diagnosticEntries = new StartupDiagnosticEntries();
settings.Set<StartupDiagnosticEntries>(diagnosticEntries);
```

I could do this 

```
var settings = new SettingsHolder();
var diagnosticEntries = new StartupDiagnosticEntries();
settings.Set(diagnosticEntries);
```

And the same for `SetDefault` 
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Settings/SettingsHolder.cs#L224

**Comment by timbussmann** [comment]
makes sense to me 👍 
(the same applies for `SetDefault`)

**Comment by SimonCropp** [comment]
@timbussmann thanks. no rush. but it would be a nice to have
