### ISSUE TITLE
Assembly loaded from a different location

### ISSUE THREAD

**Issue by hugovlc** [Particular/NServiceBus#5183]
I am using Nservicebus 6.4.3 and on windows 10 and I get this error when trying to start the instance:

`IEndpointInstance endpointInstance = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();`

`API restriction: The assembly 'file:///C:\devnet\eCdt\sprints\dev-4.0\CdT.UI.Ecdt\CdT.UI.Ecdt.Web\bin\Oracle.ManagedDataAccess.dll' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.`

I saw that there was a fix for a similar issue for the version 6.4.2.
On a windows 7 machine it works fine.

**Comment by bording** [comment]
@hugovlc Take a look at the GAC on both of those machines. I suspect the problem you're running into is that `Oracle.ManagedDataAccess.dll` is in the GAC on the machine that is having the problem, and it's not in the GAC on the machine that is working fine.

If that is the case, then you either need to remove it from the GAC, stop deploying the local copy to the bin folder, or [exclude the assembly from scanning](https://docs.particular.net/nservicebus/hosting/assembly-scanning#exclude-a-list-approach-exclude-specific-assemblies-by-name).

**Comment by hugovlc** [comment]
@bording That is exactly it. Thank you.

**Comment by bording** [comment]
Glad to hear that fixed it for you!
