### ISSUE TITLE
Delete nservicebus sourceforge project

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5184]
https://sourceforge.net/projects/nservicebus/

We wanted to delete this years ago, but at the time sourceforge did not allow project deletion.

Apparently project deletion is now supported https://twitter.com/SimonCropp/status/1003881220126617600

**Comment by timbussmann** [comment]
will hunt for somebody with sourceforge account access.

**Comment by timbussmann** [comment]
There are some minor questions open regarding the code hosted on the nservicebus sourceforge project which need to be answered first. This task is tracked internally as part of our maintenance process. I'm going to close this issue on this repository for now. If you'd like to discuss anything regarding this topic, please feel free to reopen this at any time. Thanks for reminding us about that @SimonCropp 👍

**Comment by timbussmann** [comment]
fyi we decided to not go ahead and delete the sourceforge account as of now. It isn't causing actual problems or pains and there are some valid points to keep the source code of the old NSB code around and publicly available.
