### ISSUE TITLE
Timeouts dispatched to every class implementing the timeout handler, actually executed with InMemory persistence

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus#5187]
### Problem description

A customer reported this.
This is a real edge case scenario though! Here are the constraints:

- Create two sagas
- Both sagas reuse the same class for storing saga state
- Both sagas reuse the same class for a timeout

In this case, with both sagas, the handle method for the timeout will get executed and they share state. Some example code:

```
public class FirstSaga : Saga<MySagaData>,
    IHandleTimeouts<CancelOrder>
{}

public class SecondSaga : Saga<MySagaData>,
    IHandleTimeouts<CancelOrder>
{}
```

If you do not reuse the class for saga state, it simply cannot find the saga and stops.
Here's a repo where I reproduce the issue: https://github.com/dvdstelt/inmemorytimeoutissue

**Comment by andreasohlund** [comment]
This is already fixed in later versions https://github.com/Particular/NServiceBus/issues/4585

**Comment by dvdstelt** [comment]
Forgot to mention this is NServiceBus 5. We're not backporting this? Especially since [v5 support will cease](https://docs.particular.net/nservicebus/upgrades/supported-versions) in a couple of months?

**Comment by dvdstelt** [comment]
Discussed with Andreas. We won't backport since there are 'workarounds' that are best practices, like not reusing a class.
