### ISSUE TITLE
On Decommission Endpoint - Clean up backing transport / persistance

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#5196]
NSB Documentation discusses logistics of [decommissioning endpoints](https://docs.particular.net/nservicebus/endpoints/decommissioning-endpoints), but doesn't cover how to programatically remove the backing transport / persistance resources consumed by a decomissioned endpoint.

**Does NSB support or provide any utilities to assist in cleaning up endpoint resources??**

I have a scenario where I am constantly creating very short lived ephemeral endpoints.  Naively cleaning up after the endpoint is quite burdensome.  I'm using Azure Storage transport / persistance, so I need to remove up to 4 queues (main queue, retries, timeouts), blob storage (timeouts / delays), and tables (timeouts / delays).  Even if I need to make the azure api calls myself to delete these resources it would be very helpful if there was a nsb library I could use to inspect an endpoint and tell me the names of all the resources that endpoint used.

**Comment by danielmarbach** [comment]
@ppittle It is possible but you have to go a bit deeper into the rabbit whole right now. 

For example, the settings bag that you can get over the endpoint configuration contains QueueBindings. The queue bindings contain the receive resources of the endpoint. We do similar trickery in the acceptance tests. 

An example from RabbitMQ
https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ.AcceptanceTests/ConfigureEndpointRabbitMQTransport.cs#L32

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ.AcceptanceTests/ConfigureEndpointRabbitMQTransport.cs#L39

The code that makes the decision to start and stop an endpoint can get access to the queue bindings and then use that information to call out to the Azure APIs to delete the resources. Unfortunately like you mentioned that is only one piece of the puzzle. Persistence can make its own assumptions and create its own resources. And there you have to understand what is doing and creating when you call certain endpoint configuration level APIs and then map this to delete and cleanup operations on your Azure SDK calls.

**Comment by ppittle** [comment]
Thank you both your thoughtful replies.

@dvdstelt I've moved the discussion to the discussion site you recommended: https://discuss.particular.net/t/identify-clean-up-backing-transport-persistance-for-decommissioned-endpoints/635.  I'll answer your requests for context there.

@danielmarbach - I figured the connections of all resources must be somewhere in the settings bag.  I was hoping there would be a nicer abstraction on top of it, but it seems that's not the case.  But I looked at the code you provided and this looks like a good jumping off point.  If I have any further specific questions on how to get access to the connection strings for the azure queue transport / storage persistance I'll post an issue on those repos.

Thanks for the help!

**Comment by DavidBoike** [comment]
I’m going to close this issue for now. There’s a fairly good discussion if you follow the forums link above, where it becomes more obvious that @ppittle is using ephemeral endpoints as a bit of a hack to deal with management of an external resource.

While we support decommissioning of endpoint *instances*, ephemeral endpoints isn’t really something we want to encourage or support, at least for now, until we have a much more defined use case.
