### ISSUE TITLE
Service Pulse Shows Inherited Message Types

### ISSUE THREAD

**Issue by SmegheadSev** [Particular/NServiceBus#5198]
I have a message that is sent that inherits from a base class shared between several different messages but messes with the display within Service Pulse. Is there a way to override the display logic or is this by design? After the first shared message the rest are offset and displayed behind the message name container.

![image](https://user-images.githubusercontent.com/8103294/41723233-2420299e-7530-11e8-81fc-1a62ecc5d678.png)

**Comment by WilliamBZA** [comment]
I believe this will be fixed by https://github.com/Particular/ServicePulse/pull/640

**Comment by WilliamBZA** [comment]
Hi @SmegheadSev, ServicePulse `1.14.3` has been released. Can you update and see if that fixes your problem?

**Comment by SmegheadSev** [comment]
We just upgraded and it did fix the display so we can get the information now, thank you! Question though,   is there a way to format the text that is displayed? Either removing the base class display or getting rid of the fully qualified name?
![image](https://user-images.githubusercontent.com/8103294/41916929-d299399c-791e-11e8-9c4a-9ea7418e5066.png)
Sorry about the blue lines, just marking out a client name. If there's no way to achieve this it's not a big deal it's just an extra step to view the message type in some cases.

**Comment by WojcikMike** [comment]
Hi @SmegheadSev for now it is not possible to format the text that is displayed. We discussed if we should remove the namespace from the type, and we will implement it at some time. At the moment we fixed broken UI and added al the information into the tooltip.

**Comment by SmegheadSev** [comment]
Awesome, thanks for the update and support. It's still usable as is but look forward to future functionality!

**Comment by sergioc** [comment]
@SmegheadSev we've just released [ServicePulse 1.27](https://github.com/Particular/ServicePulse/releases/tag/1.27.0). In this version ServicePulse will only display the actual message type in the list of messages processed by an endpoint. You can still view the full name in the tooltip that shows when hovering the message type name.
