### ISSUE TITLE
License date should be based on the date of the go-live license

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5199]
So where i work we had an interesting licencing  predicament. We were given a go-live license from particular when v7 was still beta. So we updated to the beta and began testing and proceeded under the plan to run with a stable v7 when it was RTM. However the time between the go live date and the rtm date was long enough that our license expired. So we were in a situation where we were allowed to run a beta in production, but not allowed to update to the stable release. Note that we fully intend to acquire a license for v7, just in the enterprise world procurement takes time.

But the above situation is clearly not desirable, so i think as a solution the license logic should be change so that if u were valid when go-live was released, you are still valid when stable is released. essentially, from a licensing perspective, back dating the stable release date to the date of the go-live

**Comment by andreasohlund** [comment]
We'll discuss this internally and make sure the policy gets updated 👍

**Comment by andreasohlund** [comment]
We'll make sure that the policy is updated next time around, thanks for raising this
