### ISSUE TITLE
SQLPersistence and NHibernatePersistence on same endpoint with multiple Sagas

### ISSUE THREAD

**Issue by deshpande89** [Particular/NServiceBus#5200]
Hi,

Can we use both SQLPersistence and NHibernatePersistence on same endpoint with multiple Sagas?
Some saga will use NHibernate and some will use SQLPersistence.
Is that possible? 
Please help.

**Comment by bording** [comment]
While you can configure different persisters for each of the [storage types](https://docs.particular.net/persistence/#storage-types), you can't figure multiple persisters for a single type.

That means you'll need to create two endpoints, one that uses SQL persistence, and one that uses NHibernate, and then split the sagas between them.
