### ISSUE TITLE
MessageMapper Issue using FluentValidation

### ISSUE THREAD

**Issue by dharmeshtailor** [Particular/NServiceBus#5205]
We are using "**NServiceBus.FluentValidation**" to validate our command. It was working alright, up until couple of days back, when we started having following error suddenly:

Can only generate a concrete implementation for '**IValidationRule**' because the interface contains methods. Ensure interface messages do not contain methods.

**IValidationRule** interface is not used explicitly anywhere in the code, this is just internals of FluentValidation. We have Command Validators using FluentValidation in same project as Commands. And commands are hooked up with bus using conventions.

And issue is not related to "NServiceBus.FluentValidation", we get same error even if we don't use it. Just having validators in same project (assembly) as command throws error.

**Comment by andreasohlund** [comment]
It seems like your message conventions are picking up types from the FluentValidation assembly.

Can you share your conventions? (https://docs.particular.net/nservicebus/messaging/conventions )

**Comment by dharmeshtailor** [comment]
Sorry the issue got resolved, there was a class in other assembly that had reference to IMessageHandlerContext. My commands project had reference to that assembly and this issue. I removed that class and it started working.

Just weird that error messages doesnot show the actual cause always. ☺

Closing the issue.

**Comment by andreasohlund** [comment]
>Just weird that error messages doesnot show the actual cause always

That sounds off, I still wonder if your conventions are to greedy, I assume you are using custom message conventions right?

**Comment by dharmeshtailor** [comment]
May be setting convention at folder namespace level should fix issue as well. I'll try that tomorrow and let you know. Currently it was set at project namespace level.

**Comment by andreasohlund** [comment]
>Currently it was set at project namespace level.

Hmm, it should still not pick up types in the `NServiceBus.FluentValidation` unless you happen to have the same root namespace as the `IValidationRule` type?

**Comment by dharmeshtailor** [comment]
No the namespace is different than that. I'll share my conventions and code sample tomorrow.

**Comment by andreasohlund** [comment]
Ping @dharmeshtailor would love to get my hands on that code sample so we can figure out the root cause for this?

**Comment by dharmeshtailor** [comment]
`public static List<string> CommandsNamespaceList => new List<string>
        {
            "Company.Command"
        };

        public static List<string> EventsNamespaceList => new List<string>
        {
            "Company.Integration.Event"
        };

        public static List<Route> Routes => new List<Route>
        {
            new Route(typeof(CreateMatter).Assembly, "Company.Command.Matter", "matters"),
            new Route(typeof(CreateIndividual).Assembly, "Company.Command.Party", "party")
        };

        public static List<string> ExcludeAssemblies => new List<string>
        {
            "Company.Subscription.Service.Interfaces",
            "Company.Core.InfraStructure"
        };`

The issue was because of the class in "Company.Core.InfraStructure" where we were also publishing the events. When I moved the class to other project it worked alright. Now I have excluded that assembly from scanning. It is weird, although I am sure this is because of our project structure and nothing to do with the way NServiceBus scans the assemblies.

**Comment by andreasohlund** [comment]
Still confused, you shouldn't have to exclude any assemblies. Can you zip the entire project and upload or email it to andreas dot ohlund at particular dot net ?

**Comment by dharmeshtailor** [comment]
Sorry I am unable to replicate the issue now, no matter what I do. :-(
