### ISSUE TITLE
Question about Satellite : how to deserialize a message correctly ?

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#5219]
Hi,
we are migrating an endpoint from nsb5 to 7.
We use satellites to offload some computations (sending email, printing etc..). We do that by sending a message to the satellite queue.
In nsb7 we can't find an easy way to deserialize the message, the feature constructor can't have parameters and the IMessageSerializer is not injected in the container anymore.

We tried to use the systems serializer but i think it's just not ment to be used by external code, and anyway our message was not recognized by the serializer so we had to add a dummy IHandleMessages<> to the main queue.

What is the correct way to do that ?

`    public class StampeAutomaticheUdcSatellite : Feature, IHandleMessages<EseguiStampeAutomaticheUdc>
    {
        Func<IMessageMapper, IMessageSerializer> _serializerBuilder;

        public StampeAutomaticheUdcSatellite()
        {
            EnableByDefault();
        }

        public Task Handle(EseguiStampeAutomaticheUdc message, IMessageHandlerContext context)
        {
            return Task.FromResult(0);
        }

        protected override void Setup(FeatureConfigurationContext context)
        {
            var xmlSerializer = new XmlSerializer();
            _serializerBuilder = xmlSerializer.Configure(context.Settings);

            context.AddSatelliteReceiver(
            name: "StampeAutomaticheUdcSatellite",
            transportAddress: BusExtensions.CODA_SATELLITE_STAMPE_AUTOMATICHE,
            runtimeSettings: PushRuntimeSettings.Default,
            recoverabilityPolicy: (config, errorContext) =>
            {
                return RecoverabilityAction.MoveToError(config.Failed.ErrorQueue);
            },
            onMessage: OnMessage);
        }

        Task OnMessage(IBuilder builder, MessageContext message)
        {
            var txt = System.Text.Encoding.UTF8.GetString(message.Body);

            var mm = builder.Build<IMessageMapper>();
            var serializer = _serializerBuilder(mm);
            using (var mem = new MemoryStream(message.Body))
            {
                var deserializedObj = serializer.Deserialize(mem);

            }

            return Task.FromResult(0);
        }
    }`

**Comment by weralabaj** [comment]
@valeriob I wonder if looking at this sample would help in your case https://docs.particular.net/nservicebus/mailer/, especially [MailureFeature.cs](https://github.com/HEskandari/NServiceBus.Mailer/blob/master/NServiceBus.Mailer/MailerFeature.cs) could point you in the right direction.

Overall though, I think it'd be better to use our regular support channels to resolve your issue, i.e. email the question to support@particular.net. That way we can share code, logs and get into a bit more detail than is probably OK for a public Github repository :)
So please, send us an email and add the following information:
- What configuration are you using, e.g. transport, persistence?
- Are you migrating from v5 to v7 directly? (we recommend to do it 1 major version at a time)
- Can you share the code for both old and new implementation (the one not working) and share the logs to show what is the exception?

**Comment by valeriob** [comment]
Thanks @weralabaj MailureFeature uses a lot of code, but the way we reach the serializer is the same.
It just does not really look like someone is supposed to mess with magic setting strings and manually instantiate a MessageMapper 😄 

`var mainSerializer = settings.Get<Tuple<SerializationDefinition, SettingsHolder>>("MainSerializer");
            var serializerFactory = mainSerializer.Item1.Configure(settings);
            return serializerFactory(new MessageMapper());`

Why do not you add to the DI all the serializers configured ? so you can just iterate over them and use the correct one based on ContentType ?

Thanks

**Comment by weralabaj** [comment]
Yeah, it's a bit complex :) Based on the snippet you shared I don't see why you need to instantiate the MessageMapper or how you customize its settings, but there are a couple of more things you may look into, which may help understand how it all works:

- You can have many (de)serializers registered, one per content type. You can see it in this sample https://docs.particular.net/samples/serializers/multiple-deserializers/.

- In case you don't need to support deserializing many content types at the same time, but need some customization it'd be simpler to follow this guidance and provide your implementation instead of trying to tweak the default one: https://docs.particular.net/nservicebus/serialization/custom-serializer?version=core_7.1. As suggested in this article, you can check how other serializers are implemented, the code is public https://docs.particular.net/components/#serializers.

Let me know if that helps or you were looking for something else :)

**Comment by valeriob** [comment]
Thanks @weralabaj you where helpfull, but the snippet comes from the example you pointed me to https://github.com/HEskandari/NServiceBus.Mailer/blob/master/NServiceBus.Mailer/MailerFeature.cs .

I'm aware of the support of multiple serializers, i'm just suggesting to put that support in the DI so ppl can easy access that feature without having to look on the source code and waste some hours 😄 

Valerio
