### ISSUE TITLE
Throw meaningful exceptions when invoking EndpointInstance operations after stopping

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#5221]
The RunningEndpointInstance class allows its operations to be invoked even after the instance has been stopped.

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L76

This leads to weird exceptions further down the callstack (like message session trying to read keys from settings that no longer exist). We could throw a better exception here if the endpoint instance is stopped.

**Comment by dbelcham** [comment]
This issue was prioritized by the DevEx bucket but could not be worked on because it is a breaking change. They would like it to be considered and prioritized for the next major of Core.

**Comment by andreasohlund** [comment]
Why would we classify this as a breaking change? (Pretty sure semver is ok with throwing better exceptions?)

**Comment by dbelcham** [comment]
My understanding is that exceptions are considered part of the public API and changing when they get thrown or which one gets thrown is considered a change in system behavior...thus a breaking change.

**Comment by andreasohlund** [comment]
Couldn’t we argue that this is a bug, we should really throw a InvalidOp
exception and not a KeyNotFound?


Tried to see what Semver says about this but couldn’t find anything?

**Comment by aleksandr-samila** [comment]
Resolved in #5770.
