### ISSUE TITLE
Message body is not valid when using IOutgoingLogicalMessageContext

### ISSUE THREAD

**Issue by MeTitus** [Particular/NServiceBus#5222]
Hi guys,

I have the following code:

```
        public override async Task Invoke(IOutgoingLogicalMessageContext context, Func<Task> next)
        {
            if (!context.TryGetIncomingPhysicalMessage(out var incomingMessage))
            {
                await next().ConfigureAwait(false);

                return;
            }

            const string enclosedMessageTypesHeader = "NServiceBus.EnclosedMessageTypes";

            var serializedMessage = Encoding.UTF8.GetString(incomingMessage.Body, 3, incomingMessage.Body.Length-3);
            var incomingMessageIntance = JsonConvert.DeserializeObject(serializedMessage,
                Type.GetType(incomingMessage.Headers[enclosedMessageTypesHeader]));

            if (incomingMessageIntance is ITrackMessageExecution incoming &&
                context.Message.Instance is ITrackMessageExecution outgoing)
            {
                outgoing.TrackingId = incoming.TrackingId;
            }

            await next().ConfigureAwait(false);
        }
```

Unfortunatelly for some reason the message has a few extra bytes, 3 in my case, which make it an invalid JSON string. Upon removing those extra bytes I get it parsing normally.

Any idea about what the issue might be?

I am using the json serializer (2.1.0), rabbitMQ (5.0.0) and NServiceBus (7.01)

**Comment by SzymonPobiega** [comment]
@MeTitus these three bytes are the Byte Order Mark (BOM) emitted by the Json writer. The `UTF8Encoding` class when created with `true` as the first argument (as in `Encoding.UTF8` case) returns the BOM as a preamble but does not handle it neither in `GetString` nor in `GetBytes`.

You need to handle it yourself (detect the BOM) or use the json reader which does it automatically for your.

**Comment by MeTitus** [comment]
@SzymonPobiega Ok fair enough but why is it that when I specify the serialization settings it still doesn't work?

```
            var serialization = configuration.UseSerialization<NewtonsoftSerializer>();
            
            serialization.WriterCreator(stream =>
            {
                var streamWriter = new StreamWriter(stream, new UTF8Encoding(false));

                return new JsonTextWriter(streamWriter)
                {
                    Formatting = Formatting.Indented
                };
            });

Thanks
```

**Comment by MeTitus** [comment]
Just another thing. There seems to be some inconsistency accross the API because I can get the  outgoing message instance from the IOutgoingLogicalMessageContext like:

`Message.Instance` 

but to get the the incoming message I need to go a bit more low level, what was the reasoning behind this? Also, in the context of the Behavior, I don't have access to the serialization settings, that will means more copy replicated across classes. Maybe something you guys can improve.

**Comment by SzymonPobiega** [comment]
@MeTitus the API is designed so that the most common things are easier while still being readable. We had to make compromises regarding that is available and what is not.

That said, the easiest thing you can do is create another behavior in the incoming pipeline. The pairs of behaviors is a common pattern in the internals of NSB. 

The incoming pipeline behavior would take the `LogicalMessage` from the context, obtain the tracking ID and store the tracking ID under some custom key in the context's extensions.

Then the outgoing pipeline behavior would look up the tracking ID using that same key. Because the behavior contexts further down the chain have access to all the data stored by previous behaviors you will be able to do it.

**Comment by SzymonPobiega** [comment]
@MeTitus this BOM thing is indeed interesting. Can you provide a minimal repro for this case? The Json serializer should honor the writer creation callback you register.

**Comment by MeTitus** [comment]
@SzymonPobiega I'm going to close this ticket for now as I'm tight on time to replicate the code as it is part of a library we're using and stripping the bits and bobs will take me a bit of time. I will test it later and if the same issue persists I'll open a new ticket.

Thanks
