### ISSUE TITLE
Rename TestingLoggerFactory to TestableLoggerFactory 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5231]
to bring it inline with the naming convention of all the other testing types
![image](https://user-images.githubusercontent.com/122666/44011239-ccde6f70-9efa-11e8-9419-1ee619a6356c.png)

**Comment by andreasohlund** [comment]
Makes sense, flagging it as a candidate for the next major since it's a breaking change

**Comment by andreasohlund** [comment]
>move NServiceBus.Testing.Fakes out of the core so u can change it out of the main release cycle

We can actually do that right now by adding the new type in "parallel" to testing and obsoleting the one in the core with a WARN.

This was discussed on by the core maintainers and we didn't see enough value for now so the plan is to just do this in v8

**Comment by andreasohlund** [comment]
We plan to get this fixed in the next major do you prefer that we open a new issue to track it? (To avoid having this issue clutter your todo-list?)

**Comment by SimonCropp** [comment]
yes. thanks

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/issues/5332
