### ISSUE TITLE
Capturing message body in incoming and outgoing logs

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#5234]
This ask was raised as a request in issue #5179 and decided to be postponed in PR #5230.

Currently, when a message is coming in or dispatched later, we log message type and headers.
Messages that override `.ToString()` can have [message content logged](https://docs.particular.net/nservicebus/logging/message-contents) as well. This could be an extensibility point where customers would implement `.ToString()` for their debugging needs.

Note: this is aligned with our [GDPR documentation](https://docs.particular.net/nservicebus/compliance/gdpr)

**Comment by timbussmann** [comment]
@SeanFeldman I think I've lost a bit of context on this issue but it seems that there is already the possibility to overwrite `ToString` to get the message body logged? What else is this issue exactly proposing?

**Comment by SeanFeldman** [comment]
Looks like it was handle by #https://github.com/Particular/NServiceBus/pull/5230, bit I don't recall the reason the issue was not closed when the PR got merged.

**Comment by timbussmann** [comment]
sounds like we can close this then?
