### ISSUE TITLE
Use of StringBuilder.AppendLine often causes empty lines in the log

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5239]
We have several usages of `StringBuilder.AppendLine` which are then written to the log e.g. `logger.Info(stringBuilder.ToString()`. This causes empty lines being written to the log. The lines aren't causing any real issues but might be irritating for users as there is no schema which explains the empty lines on certain log entries and it can cause some visual distraction.

e.g.
```
2018-08-22 11:36:37.932 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2018-08-17'.

2018-08-22 11:36:38.059 WARN  NServiceBus.Transport.Msmq.QueuePe...
```

**Comment by timbussmann** [comment]
shall we keep this open @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@timbussmann I think it is fine to close. I tried to find any other places where we use `AppendLine` before logging but it seems there is none so I think we're done.

**Comment by timbussmann** [comment]
@SzymonPobiega did you see my comment on https://github.com/Particular/NServiceBus/pull/5446 ?

**Comment by SzymonPobiega** [comment]
Ha, not yet. I was reading GH notifications in the reverse order. I'll take a look and fix these also.

**Comment by SzymonPobiega** [comment]
The remaining redundant new lines removed in https://github.com/Particular/NServiceBus/pull/5451
