### ISSUE TITLE
EndpointConfiguration.RegisterMessageMutator() only call mutator from the last invocation

### ISSUE THREAD

**Issue by rhyskoedijk** [Particular/NServiceBus#5257]
Tested on v7.0.1.

````C#

public class FooMessageMutator :
        IMutateIncomingTransportMessages,
        IMutateOutgoingTransportMessages
{
    //...
}

public class BarMessageMutator :
        IMutateIncomingTransportMessages,
        IMutateOutgoingTransportMessages
{
    //...
}

var foo = new FooMessageMutator();
var bar = new BarMessageMutator();
endpointConfiguration.RegisterMessageMutator(foo);
endpointConfiguration.RegisterMessageMutator(bar);
````

When sending a message (specifically, an `ICommand`), only `BarMessageMutator` is invoked.
I would expect both mutators to be invoked.

If this is expected behaviour and not a bug, then could you please explain how I should be correctly registering multiple mutators? I wasn't able to find anything in the wiki about this.

**Comment by andreasohlund** [comment]
@rhyskoedijk looking into this and I can confirm that this is a bug.

While we're doing further analysis and looking into potential fixes you can work around this by using this registration syntax instead:

```
  endpointConfiguration.RegisterComponents(r => {
            r.ConfigureComponent<FooMessageMutator>(DependencyLifecycle.SingleInstance);
            r.ConfigureComponent<BarMessageMutator>(DependencyLifecycle.SingleInstance);
        });

```

**Comment by andreasohlund** [comment]
@rhyskoedijk we're working on a fix, will keep you posted on the progress via this issue

**Comment by rhyskoedijk** [comment]
sounds good. I'll use the above work around until then. cheers.

**Comment by andreasohlund** [comment]
@rhyskoedijk to avoid changing your original bug report I have created https://github.com/Particular/NServiceBus/issues/5263 to track the bug fix.

**Comment by andreasohlund** [comment]
7.1.4 is now released, @rhyskoedijk thanks again and lets us know if you have any further issues
