### ISSUE TITLE
LearningTransport throws an NRE when the saga has a Struct property 

### ISSUE THREAD

**Issue by HEskandari** [Particular/NServiceBus#5258]
When using LearningTransport/Persistence, the following code will break with a `NullReferenceException` whereas switching to other transport/persistence libraries the same code works (tested with SQL Transport / NHibernate Peristence as an example).

Further investigation by @timbussmann shows that it is a limitation of SimpleJson that does not de/serialize Structs. The sample works with v6 (tested with 6.4.4) but not in v7 (tested in 7.1.3).

https://gist.github.com/HEskandari/c935b98b3c71ec0fa17905b35f58f363

**Comment by poornimanayar** [comment]
Tested against latest version and can verify that this is no longer an issue.
