### ISSUE TITLE
In Learning Transport header manipulations done while processing a message are visible in recoverability policy

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#5269]
When a header is added/deleted/modified in an attempt to process a message and that attempt fails, these header manipulations are visible when the recoverability policy is executed to determine if/how the message should be retried.

**Comment by SzymonPobiega** [comment]
@Particular/keeping-the-lights-on-squad given that this is the learning transport, I'd say we leave it up to the @Particular/nservicebus-maintainers to flag (or not) this for the next maintenance release.

**Comment by SeanFeldman** [comment]
Already fixed in https://github.com/Particular/NServiceBus/commit/c22c164d620675154b347aee2e69425f730b24f7
