### ISSUE TITLE
when Extending NSB how does a community member prevent "It's time to extend your trial"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5270]
In the context of writing an extension to NSB. someone in the community should not be expected to have a license.

However when they debug unit tests they get one new browser tab per unit test method

![image](https://user-images.githubusercontent.com/122666/45524490-18cfe500-b812-11e8-946b-aac95b16ea30.png)

**Comment by HEskandari** [comment]
Why not get a free personal license?

**Comment by SimonCropp** [comment]
Can i check that into the codebas. So that anyone wanting to contribute doesnt need to re apply for a license

**Comment by bording** [comment]
@SimonCropp What change are you proposing here?

**Comment by SimonCropp** [comment]
1. only show one popup per process. 
2. allow FOSS projects extending NSB to commit their license to the codebase, so others contributing to the codebase dont get the popup, and stop the license log errors on the build server.

**Comment by kbaley** [comment]
Thanks @SimonCropp. You're right, this experience could be better for extension builders. We'll see what we can do to get the licensing system out of the way.
