### ISSUE TITLE
NServiceBus upgrading major version strategy - message backwards compatibility

### ISSUE THREAD

**Issue by seanfarmar** [Particular/NServiceBus#5275]
Some valid points in the [SO issue](https://stackoverflow.com/questions/52455473/nservicebus-upgrading-major-version-strategy)

Main one beeing: `But I don't understand why a communication system based on serialized and deserialized messages depends on the version of the message assembly`

**Comment by andreasohlund** [comment]
Pretty sure that @DavidBoike have verified that asm redirect works just fine in this scenario so Jonathan Olivier statment is no longer correct.

David?

**Comment by seanfarmar** [comment]
@andreasohlund @DavidBoike So I could suggest the assembly redirect solution...?

**Comment by DavidBoike** [comment]
For the record, I once verified that (at the time) you did not need to use unobtrusive conventions to upgrade major versions of NServiceBus between whatever the current version and V-1 at the time, likely V5 to V6 but can't absolutely remember.
