### ISSUE TITLE
Relax message type matching logic

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5276]
The [MessageMetadataRegistry](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs) is responsible for finding a matching type for a message based on it's `EnclosedMessageTypes` header. This header should normally contain a fully qualified type name (which includes the assembly name, version etc.).

There are scenarios where you might define the message type in different assemblies (e.g. by copy pasting, shared code projects, etc.). In those cases, the registry isn't able to find the similar type (same code, just different assembly) due to the FQN search. This is especially annoying in 3rd party integration scenarios, where the sender might send a raw message not being serialized from a .NET type. Based on that we already have [documentation](https://docs.particular.net/samples/consumer-driven-contracts/#full-names-instead-of-fully-qualified-assembly-names) and [code](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs#L59) in place which is should try to find a type based on the FullName only (~ namespace + class name). This only works when the incoming header already contains the FullName instead of the FQN.
It would be nice if core tries to "downgrade" a FQN to the type's FullName to allow deserializing "equal" types defined in different assemblies in case it can't find a matching type using the FQN. This currently requires a customization via behaviors or mutators modify the incoming/outgoing headers.

(Note: This is mostly an issue with non-XML serializers as the XML serializer also contains an additional step to determine the message type based on the element name)

**Comment by ramonsmits** [comment]
Here is a gist I've shared with several users to workaround our current limitation: https://gist.github.com/ramonsmits/b0bc955541aa714cab9cafc934a364ef

Also is related to https://github.com/Particular/PlatformArchitecture/issues/517

**Comment by mikeminutillo** [comment]
[Released in 7.4](https://github.com/Particular/NServiceBus/releases/tag/7.4.0)
