### ISSUE TITLE
RabbitMq connection drops when rebuilding cluster

### ISSUE THREAD

**Issue by devindran** [Particular/NServiceBus#5291]
We are seeing an issue several times now where an issue with RabbitMq that requires the cluster to be rebuilt, results in the application hosting NServiceBus not to reconnect after the cluster is rebuilt.

Steps are as follows:
1. NServiceBus instance is connected to RabbitMq
2. Some critical fault requires the cluster to be rebuilt. The instance disconnects from RabbitMq
3. After the cluster is rebuilt, the connection does not automatically reconnect, or throw any error.
4. The result is the application continues to run, but RabbitMq does not show any connections, nor is any messages processed.

The current workaround is to manually restart the application/endpoint.

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus.RabbitMQ/issues/503 in RabbitMQ repo. Thanks @devindran for reporting it. I pinged you in the new issue so you should receive updates overthere
