### ISSUE TITLE
Error handling for SendOnly endpoints

### ISSUE THREAD

**Issue by agross** [Particular/NServiceBus#5302]
We run a web site in SendOnly mode to submit web forms to backend services.

I was thinking about error scenarios like the queuing system being unreachable or the target queue that sent messages are routed to gets deleted.

I found no documented way to hook into the send-only pipeline to catch such errors and perhaps serialize the message to disk to handle them later and not loose forms that were submitted by users.

These are the APIs I tried to gain global error handling:
```cs
configuration.Notifications.Errors.*
configuration.Recoverability().Failed(...)
configuration.DefineCriticalErrorAction(...)
```

Or perhaps I'm doing something wrong. I would appreciate if you could point me in the right direction.

Here's the whole endpoint setup:
<details>

```cs
class Routing : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    var routing = configuration
      .UseTransport<MsmqTransport>()
      .Routing();

    
    routing.RouteToEndpoint(Assembly.Load("Foo.Contracts"),
                       "Foo.Contracts.Commands",
                       "foo");
  }
}

public class Conventions : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    configuration
      .Conventions()
      .DefiningCommandsAs(type => ...);
  }
}

class Diagnostics : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    configuration.SetDiagnosticsPath(Path.Combine(NServiceBus.BinPath, "../../logs"));
  }
}

class Features : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    configuration.DisableFeature<AutoSubscribe>();
    configuration.DisableFeature<MessageDrivenSubscriptions>();
    configuration.DisableFeature<TimeoutManager>();
    configuration.DisableFeature<Sagas>();
  }
}

class SendOnly : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    configuration.SendOnly();
  }
}

class Serialization : INeedInitialization
{
  public void Customize(EndpointConfiguration configuration)
  {
    configuration.UseSerialization<NewtonsoftSerializer>();
  }
}
```

</details>

**Comment by andreasohlund** [comment]
The options you mention is targeted towards the message receive parts of the endpoint. Since this is a send only endpoint that doesn't apply.

You have a few options:

* Plug into to the outgoing pipeline https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors#stages-outgoing-pipeline-stages
* Just wrap you `IMessageSession.Send` call in a try catch
   - You could create a custom "StoreOperationsLocallyOnFailuresMessageSession : IMessageSession" that you inject into your forms that does this.

Does this make sense?
