### ISSUE TITLE
Make the internal container immutable

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#5305]
https://github.com/Particular/NServiceBus/pull/5304 introduces a soft enforcement of immutability using acceptance tests. We should make move this to our internal container instead to make sure that downstreams follow this rule and they would break spring.net if not.

### PoA

- [ ] Make the lightinject internal container immutable
- [ ] Remove acceptance test container

**Comment by bording** [comment]
If this could break users, how can this be done in a minor? A behavior break is still a break. Wouldn't this have to wait for a new major?

**Comment by andreasohlund** [comment]
I'm on the fence, we never made any claims around this and we're still good from a semver perspective. 

I don't think this is urgent so happy to defer to next major to play it safe

**Comment by timbussmann** [comment]
@andreasohlund this issue seems to be mostly related to the missing differentiation between registration & resolving phase which has been addressed as part of 7.2. Do you feel that there is more we should do in that regard?

**Comment by andreasohlund** [comment]
I guess since the ATT's verify this we don't have to have the learning one enforce this
