### ISSUE TITLE
When the data volume doubles, the outbox causes the database to be slow

### ISSUE THREAD

**Issue by Varorbc** [Particular/NServiceBus#5321]
NServiceBus Version : 7.1.4

We use the Outbox feature based on [this sample.](https://docs.particular.net/samples/outbox/sql/#code-walk-through-receiver-project) find that transactions must be used, and the Outbox related tables must be in the same database as the business related tables. When the business data suddenly increases and the outbox automatically deletes the data, the database will be slow and affect the business. Is there any good way to solve this problem?

**Comment by janovesk** [comment]
Hi, @Varorbc!

Yes, you can configure both the retention policy(how many days to keep data) and the frequency of how often(including disabling) the cleanup routine should run.

I would recommend you turn down the frequency from the default once per minute to a level where you don't notice any performance effects of it. Alternatively, disable the automatic cleanup routine and do the cleanup yourself at a time where it affects the system the least.

The details of how you configure the cleanup frequency is dependant on the persister you are using. I'm including links for [Nhibernate](https://docs.particular.net/persistence/nhibernate/outbox), [RavenDB](https://docs.particular.net/persistence/ravendb/outbox) and [Service Fabric](https://docs.particular.net/persistence/service-fabric/outbox)

Hope that helps!

Jan Ove

**Comment by Varorbc** [comment]
ok Thanks very much
