### ISSUE TITLE
NServiceBus.AcceptanceTesting should not depend on NUnit

### ISSUE THREAD

**Issue by aguacongas** [Particular/NServiceBus#5322]
IMO this package should not have dependency to NUnit to be used with other test framework as xUnit for sample to be easier to adopt.

**Comment by andreasohlund** [comment]
Hi, @aguacongas thanks for the feedback. We never meant for the acceptance testing framework to be consumed by end users (hence no documentation for it) so I'm afraid that this means that we're unlikely to make any changes to it in the near future.

That said, we are looking at providing better support for this type of scenarios so it would be awesome if you have some time to elaborate on you're testing needs over at https://discuss.particular.net/t/end-to-end-integration-testing/934/2 ?

Perhaps we can help you find some interim solution that gets you going in the meantime, see you in the discussion group!

**Comment by andreasohlund** [comment]
Saw that you chimed in on the discussion group @aguacongas , closing this one
