### ISSUE TITLE
Problem with pub/sub events with NServiceBus and Azure Service Bus

### ISSUE THREAD

**Issue by junaidahmed92** [Particular/NServiceBus#5328]
I am using NServiceBus along with AzureServiceBus transport layer in my .net application. The publisher in .net core web application and the subscriber is .net core console application. Now the issue is I am publishing event for web application and in Azure portal I can see message count increasing after every publish event in Subscribers "Orders" under "bundle-1" topics created as default topic by NServiceBus in Azure Service Bus. But topic's "Active message count" is 0. But my subscriber is doing nothing means it's not listening. What am I doing wrong? Here is the publisher configuration:
```

            var endpointConfiguration = new EndpointConfiguration("Products");
            endpointConfiguration.EnableCallbacks();
            var instanceDiscriminator = "8e3af657-tt56-asd3-a75c-2fe8c4bcb635";
            endpointConfiguration.MakeInstanceUniquelyAddressable(instanceDiscriminator);
            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString("connectionstring");
            var routing = transport.Routing();
            routing.RouteToEndpoint(
                assembly: typeof(OrderPlacedEvent).Assembly,
                destination: "Orders");
            endpointInstance = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();
            services.AddSingleton<IMessageSession>(endpointInstance); 
```
and publishing code:

`await _messageSession.Publish(new OrderPlacedEvent {OrderId = 1}).ConfigureAwait(false);`
and subscriber's code:

       
     Console.Title = "Orders";

            IServiceCollection serviceProvider = new ServiceCollection();
            serviceProvider = Configuration.ConfigureService(serviceProvider);

            var endpointConfiguration = new EndpointConfiguration("Orders");
            endpointConfiguration.SendFailedMessagesTo("error");
            endpointConfiguration.UseSerialization<NewtonsoftSerializer>();
            endpointConfiguration.AuditProcessedMessagesTo("audit");
            endpointConfiguration.EnableInstallers();
            endpointConfiguration.UseContainer<ServicesBuilder>(customizations =>
            {
                customizations.ExistingServices(serviceProvider);
            });
            endpointConfiguration.UsePersistence<InMemoryPersistence>();
            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.RuleNameShortener(n => n.Length > 50 ? MD5DeterministicNameBuilder.Build(n) : n);
            transport.ConnectionString("connectionString");
            var endpointInstance = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();

            Console.WriteLine("Press Enter to exit.");
            Console.ReadLine();

            endpointInstance.Stop().GetAwaiter().GetResult();

and the event:

public class OrderPlacedEvent : IEvent {}

Now I have a debugger attached in my handler but it never gets hit. One more thing I also have some commands and the commands are working fine. The message counter of Queue gets updated when ever I send any command and subscriber always listen to commands. One last thing to mention I am using free trial of Azure portal but I think that wouldn't be an issue because commands are working fine. Any help?

**Comment by SeanFeldman** [comment]
@junaidahmed92 looking at the code you've posted, I'm assuming you're using NServiceBus.Transport.AzureService transport (latest version 1.0.1).

Could you confirm the topology you have in place is the following?

```
queues
|
+ Orders

topics
|
+`bundle-1`
      |
      +Subscriptions
            |
            +`Orders`
                 |
                 +Rules
                    |
                    +`OrderPlacedEvent`  <--- or shortened; should forward to the Orders queue
```

> I can see message count increasing after every publish event in Subscribers "Orders" under "bundle-1" topics created as default topic by NServiceBus in Azure Service Bus. But topic's "Active message count" is 0.

The messages should be auto-forwarded to the `Orders` queue. If they don't, that's off. If this is not a production environment, could you please delete the topic for it to be recreated again and see if that resolves the issue?

**Comment by junaidahmed92** [comment]
@sean, thanks for the answer. Yes I am using NServicebus. Transport. AzureService (1.0.1). I can try the solution you provided as it is not production related. But i tried creating new topic and use that like:
 transport. UseTopic("newTopic");
But still same response. Can you see if there is something missing in configuration?

**Comment by SeanFeldman** [comment]
You shouldn't be specifying routing information for events. It's only needed for commands. Aside from that the rest looks good.

Try deleting that part.

**Comment by junaidahmed92** [comment]
@SeanFeldman , I have tried deleting the topic and NServicebus recreated it again. But the issue is still same. I have 2 subscribers for two different events. For the 1st subscriber NServiceBus automatically created the subscriber under Topics but for the second one it was throwing error that "AutoSubscriber cannot subscribe to an event of type....." so I have to create new subscriber by my own. Now when I am publishing the event I am getting +1 message count for the 2nd subscriber which I created manually but even than my console application (subscriber) doing nothing. And for the 1st subscriber which was automatically created by NServiceBus, even after publishing event the message count is 0.
Any other thing that I can try?

**Comment by SeanFeldman** [comment]
@junaidahmed92 I would suggest to raise a support case at https://particular.net/support pointing to this issue so that more details can be shared. Please supply log files (publisher/subscriber), endpoints configuration code and receiving handler to help with the case. Thanks.

**Comment by timbussmann** [comment]
Closing this issue since there was no more interaction for several months. [Our support channels](https://particular.net/support) are always there to help you in case this issue hasn't been resolved yet.
