### ISSUE TITLE
Message failed. Element 0 in the batch returned an unexpected response code.

### ISSUE THREAD

**Issue by dharmeshtailor** [Particular/NServiceBus#5331]
We use Azure Service Bus Transport:

```
var dataBus = endpointConfiguration.UseDataBus<AzureDataBus>();
dataBus.ConnectionString(config.AzureStorageConnectionString);

var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
transport.ConnectionString(config.AzureServiceBusConnectionString);
transport.UseForwardingTopology();
//transport.MessageReceivers().AutoRenewTimeout(TimeSpan.FromMinutes(10));
//transport.Queues().LockDuration(TimeSpan.FromMinutes(5));
//transport.Subscriptions().LockDuration(TimeSpan.FromMinutes(5));
SetRoutes(transport, config.Routes);
transport.Sanitization().UseStrategy<CustomSanitization>();
var persistence = endpointConfiguration.UsePersistence<AzureStoragePersistence>();
persistence.ConnectionString(config.AzureStorageConnectionString);
endpointConfiguration.UsePersistence<AzureStoragePersistence, StorageType.Sagas>().AssumeSecondaryIndicesExist();
```

We have Implementation as follow:
* Saga creates heaps of commands 
* When commands process is completed by handler, it publishes events.
* Events are handled by Saga.
* Once all expected events are handled by Saga, it marks itself complete.

This flow works alright intermittently. Many times we end up with the error "**Message failed. Element 0 in the batch returned an unexpected response code.**" and events are never received by the Saga.

The process is pretty quick, so my guess is issue with the Saga Concurrency. many events trying to update Saga State. If that's the case, any recommendations around how to avoid the the race condition?

I have to delete the Azure service bus queue and restart the service and it works alright for some time and same issue again.

I tried to google stuff around with no help. Any help is appreciated.

Thanks,
Dharmesh

**Comment by SeanFeldman** [comment]
@dharmeshtailor this is a typical generic error storage tables would return when there's an exception. When your saga is creating lots/heaps of commands and all those are processed and generate follow up events aggregated by the same saga instance, you're running into scatter-gather scenario here that will create a lot of contention on the same saga instance.

There are many questions to be asked about your specific business use case. For example, I could suggest an alternative for the aggregation _if_ you need to aggregate all work to make a decision, and have a look at the [long-running operations sample](https://docs.particular.net/samples/azure/azure-service-bus-long-running/). But that might not be exactly what you need.

A better option would be to contact our support at https://particular.net/support to get on a call with you.

**Comment by dharmeshtailor** [comment]
But can we know the actual reason of the error?

**Comment by yvesgoeleven** [comment]
@dharmeshtailor Sometimes it is possible to get more information about the error by installing a network sniffer or proxy on the machine and to look at the https traffic. The body of the underlying response sometimes contains more information (but not always, azure storage provides very minimal information).

**Comment by dharmeshtailor** [comment]
Weird thing is we have many such implementations, one of the implementation creates approx 550 commands and works perfectly without any issues. But this issue is always observed on one endpoint. And the saga where we have issue, is creating only 9-10 commands (thus expecting back max 10 events).

Anyways thanks, I'll try to dig in bit further, and update here.

**Comment by yvesgoeleven** [comment]
@dharmeshtailor interesting, then it may not be concurrency at all. Concurrency is just the most common reason we see this error, but we've also seen it for invalidate date time values (e.g. DateTime.Min), for illegal characters in rowkeys and others. Azure storage service is very limited in the error info it sends back, so it can take quite some guessing about what the real reason is. I suggest you intercept the traffic and have a look at it.

**Comment by dharmeshtailor** [comment]
We were maintaining the list of values in Saga State, and when we get back event we just remove the particular value from list respective to the event. And when list is empty Saga marks itself complete. What I observed was there were duplicate values in that list. I eliminated that and it is working perfect now. Not sure how this would affect the error in question though.

**Comment by SeanFeldman** [comment]
@dharmeshtailor sniffer didn't provide any extra info? Yeah, that's odd. W/o a way to reproduce this, hard to know what was happening.

**Comment by dharmeshtailor** [comment]
Didn't user sniffer, but very difficult for me to reproduce as well. It happens out of blue. And now everything's working alright. :-)

**Comment by SeanFeldman** [comment]
@dharmeshtailor is this issue still a problem for you or can it be closed?

**Comment by dharmeshtailor** [comment]
> @dharmeshtailor is this issue still a problem for you or can it be closed?

Hi, we are not facing the issue anymore. we deleted all queues and topics and restarted the services, which created queues on initiation and never faced the issues again.
