### ISSUE TITLE
Can Ever RequestTimeout update timeout‘s interval in a Saga

### ISSUE THREAD

**Issue by marjezhang** [Particular/NServiceBus#5334]
I am trying the NServiceBus's Saga proccession.
Saga must be processed to Completed  in the timeline of throughout Timeout's process  when  the Saga's TimeOut is be requested only once ,
In this throughout term, no matter how many message are recevied or replyed in SAGA, as long as they are not processed 'MarkAsComplete();' in IHandleMessage, the saga will be TimeOut.

Is Aboved 's  concept right?   The one  ' RequestTimeout' be processed is for a timeline in whole Saga, not for one context.send  or one sending message to outbound  ?  
Is that right?

I think how can i do update timeout interval in a Saga that have many IHandlemessage would be processed in  sort。  every IHandlemessage need to update new time out interval.

**Comment by SeanFeldman** [comment]
Hi @marjezhang,

This sounds more as a general question and not an issue you'd report with NServiceBus. For general question, you'd benefit from asking on our public form at https://discuss.particular.net This will expose your question to other community members that would be able to answer it. Alternative is to go through support if it's blocking your development. For that, you'd raise a support case at https://particular.net/support

For Sagas, a good starting point would be to review and try out our tutorial located here: https://docs.particular.net/tutorials/nservicebus-sagas/1-getting-started/
