### ISSUE TITLE
How can NServiceBus ensure consistent in Sender

### ISSUE THREAD

**Issue by marjezhang** [Particular/NServiceBus#5335]
for example:
As soon as the sender is ready for send the message to saga after finishing the buisness process in sender, the power goes out or the instance is broken or message broker is down.  
In this time, How can I do ? In this case the buisness process had commited, but the message was not sended .  After that,  the message is not resended even if  i restart the message broker or instance and so on.

**Comment by SeanFeldman** [comment]
Hi @marjezhang,

This sounds more as a general question and not an issue you'd report with NServiceBus. For general question, you'd benefit from asking on our public form at https://discuss.particular.net This will expose your question to other community members that would be able to answer it. Alternative is to go through support if it's blocking your development. For that, you'd raise a support case at https://particular.net/support
