### ISSUE TITLE
Error with startup diagnostics path causes NullReferenceException

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5355]
Brought up by @bording: We have code in Core to determine if we're running inside an ASP.NET web app, and if so we alter the default logging location to be `App_Data` instead. If an `App_Data` folder doesn't exist, we throw an exception indicating this.

There is a problem how we handle this in [HostStartupDiagnostics]( https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnostics.cs), though.

We swallow this exception and log an error instead, and then we attempt to continue running, but we now have a null value for `diagnosticsRootPath`. That means we throw a `NullReferenceExcpetion` when we attempt to create the directory: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnostics.cs#L53

This means instead of seeing an exception that would explain what needs to be done by pointing them to the correct API, that gets buried in the log file (if they are even logging, which the customer in the support case apparently wasn't) and they see an NRE instead.

## Who's affected

* Users running NServiceBus inside an ASP.NET web app that does not have an `App_Data` folder

## Symptoms

The endpoint fails to start, throwing a `NullReferenceException` instead.

**Comment by timbussmann** [comment]
fixed as part of 7.1.7

**Comment by ramonsmits** [comment]
@timbussmann @bording Its a duplicate of this issue I already reported 3 months ago

https://github.com/Particular/NServiceBus/issues/5317
