### ISSUE TITLE
Resolve generic message handlers from DI?

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus#5356]
I work on an application with an synchronous API that invokes (non-NServiceBus) "command handlers" with the following interface

```csharp
  public interface IHandleCommand<in TCommand>
  {
    void Handle(TCommand command);
  }
```

The code base is large as has multiple implementations of this interface. I would like to update the application to send the command on the message bus and handle them in an `IHandleMessages` message handler. At this point, it is not feasible to write adapters to each implementation (they simple are to many), so I tried to write a generic adapter

```csharp
public class CommandHandlerAdapter<TCommand> : IHandleMessages<TCommand>
{
    private readonly IHandleCommand<TCommand> _commandHandler;

    public CommandHandlerAdapter(IHandleCommand<TCommand> commandHandler)
    {
        _commandHandler = commandHandler;
    }

    public Task Handle(TCommand message, IMessageHandlerContext context)
    {
        _commandHandler.Handle(message);
    }
}
```

I registered instances of the `CommandHandlerAdapter<TCommand>` in my DI framework and configured the endpoint to use the existing container. This way, I thought that NServiceBus would pickup the `IHandleMessages` instances from the DI (instead of scanning assemblies).

This does not work for me, and perhaps that is by design 🤷‍♂️. It sound a bit like #4570. Am I mistaken to assume that handlers could be resolved from the DI? If this is not supported, are there any other recommended approaches for this scenario? (It does not feel like a unique one).

We are currently running version 6.x of NServiceBus, we have identified the above step as a pre-req before upgrading to version 7.x.

**Comment by DavidBoike** [comment]
@pardahlman Sorry, but as you have found out, handlers are not loaded from the container.

To get this to work you'd have to create explicit classes for each message type you'd like to handle...

```
public class CommandAHandler : CommandHandlerAdapter<CommandA> {}
public class CommandBHandler : CommandHandlerAdapter<CommandB> {}
```

Note that your `CommandHandlerAdapter` class needs a `return Task.CompletedTask;` at the end of the `Handle` method.

A slightly more esoteric (and much more complex)solution might be to dynamically emit inheriting classes at runtime.

**Comment by pardahlman** [comment]
OK, thanks for bringing clarity to this 🙏 . We have to look for a different approach then 👍
