### ISSUE TITLE
Add Support for CloudEvents 

### ISSUE THREAD

**Issue by lalitkale** [Particular/NServiceBus#5357]
CloudEvents.io provides a CNCF accepted event schema for any sort of events raised. There is .NET sdk as well which implements cloudevents schema. However, would there be any possibility to support CloudEvents bindings and transports natively with NServicebus? Will it be useful to consider it as a part of future roadmap item for NServicebus? 

#question #roadmap #cloudevents

**Comment by boblangley** [comment]
The group internally that tracks these things has already added it to their "watch list". This is our way of exploring whether we should adopt any technology or technique, and means we will check back time to time to see if there are any compelling market or technological indicators for it to be bumped above other things on our list.

What we often lack with these things is context from our users (or potential users). Could you describe to us what you would want to achieve using CloudEvents and how you would see this fitting into NServiceBus?

**Comment by lalitkale** [comment]
@boblangley CloudEvents specification is adopted by many prominent players and frameworks and cloud providers. It would be great to see NServicebus being one of the major platform for implementing event driven architectures, has support for the same. 
Although, I understand that it's a priorities on roadmap vs resource investment for the team. So, I will leave the priority of the item to the team.

There is no specific use case I am looking at this moment. However, it is evident that cross operating events between various components in multi-cloud or hybrid scenario will be the major use case of this specification. NServicebus is supporting Azure and AWS transport. This also falls in same ecosystem. Hope, this helps.

**Comment by lalitkale** [comment]
@boblangley we can close the issue if there is no action item on roadmap.

**Comment by boblangley** [comment]
Thanks @lalitkale . I have referenced this issue and your comments on our tracking item for CloudEvents.io. Thanks for raising the issue!

**Comment by ramonsmits** [comment]
The following feature would make supporting CloudEvents possible:

- https://github.com/Particular/NServiceBus/issues/7072

**Comment by danielmarbach** [comment]
NServiceBus 10 and onwards [supports receiving CloudEvents](https://docs.particular.net/nservicebus/cloudevents)
