### ISSUE TITLE
Sending message to AzureServiceBus Queue with Sessions Enabled, results in error

### ISSUE THREAD

**Issue by aorlenko83** [Particular/NServiceBus#5364]
Hi. 
When trying to send a message using AzureServiceBusTransport to the queue with "Enable Sessions" setting set in Azure Portal, the error is returned: 

> An unhandled exception occurred while processing the request.
> 
> InvalidOperationException: The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value. Reference:824e1746-6d61-418d-a18e-cfc3478e01de, TrackingId:985610410000d6a6000210085cba479d_G19_B6, SystemTracker:esborders:Queue:orders, Timestamp:2019-04-19T22:11:41
> Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList<Message> messageList) in MessageSender.cs, line 567

This is the error message coming from Microsoft.Azure.ServiceBus and has something to do with setting some SessionId header to the message.
However, since I'm working with NServiceBus API, I can't use the native Azure Service Bus classes to set the SessionId.
Is there a way to use "Session Enabled" message queues with NServiceBus? 
In general, AzureServiceBus Sessions guarantee fifo-delivery of messages. Is this supported by NServiceBus?
Thanks.

**Comment by SeanFeldman** [comment]
NServiceBus [Azure Service Bus transport](https://docs.particular.net/transports/azure-service-bus/) does not support ordered messages or Session enabled entities.

**Comment by SeanFeldman** [comment]
@aorlenko83 does this answer your question?
If there's more to this than just the question, consider raising a support case at https://particular.net/support. For bugs, you can target transport directly at https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues
Thank you.
