### ISSUE TITLE
Cannot make "indirect" replies work

### ISSUE THREAD

**Issue by hlubovac** [Particular/NServiceBus#5370]
Should it be possible for a sender service, while waiting the return of the invoked `Request<>` method, to receive a reply that originates from an arbitrary service, which has, in the meantime, received the information about where to send that reply?

E.g. 
1. `Service1` sends a request, waits...
2. `Service2` handles the message sent from `Service1`, and - irrelevant how - tasks `Service3` to deliver the reply to service1's request.
3. `Service3` delivers a message of expected type to `Service1`, magically routed to the result of its `Request` method-call.

Of course, CancellationToken would be used to abandon the request, and the client would know how to proceed without it. Just a theoretical question.

I am able to make `service-1 > service2 > service1` callback scenario to work, though. I can also see this working in a full-duplex mode (minding the per-instance exchanges), but I don't know how to communicate the result from the result-handler to the scope of the original call, unless using some shared object which the client keeps polling for results.

Thank you!

**Comment by hlubovac** [comment]
I was able to make this cycle work by using `IEndpointInstance.Send(string, object)` along the way, while passing around a made-up process-id and origin-endpoint's unique-instance-name, then finally wiring that up using a shared object that handles waiting for a signal from the final handler in the chain - and it all works flawlessly (timeout mechanism incorporated; I know you're rolling your eyes). So, I'm going to close this, in the interest of saving everyone's time. Thanks.

**Comment by andreasohlund** [comment]
To have Service1 get the reply from Service3 you can manipulatr the reply to address using https://docs.particular.net/nservicebus/messaging/reply-to-a-message?version=core_7.2#influencing-the-reply-behavior

Ie to use RouteReplyTo(”Service1”)

Theory: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ReturnAddress.html

**Comment by hlubovac** [comment]
Thank you; I think I tried that already (and I probably messed up somewhere), but I'll try again - now that I know that it should work.
