### ISSUE TITLE
Adding Nuget package NServiceBus.Transport.Msmq (1.0.1) does not work in ASP.NET MVC Core 2.2

### ISSUE THREAD

**Issue by eleg8r** [Particular/NServiceBus#5377]
Adding the package to ASP.NET MVC Core 2.2 project posed no issues but when trying to configure Msmq with an endpoint MsmqTransport class was not available.

`endpointConfiguration.UseTransport<MsmqTransport>(); // MsmqTransport is not found`

Does it mean that Msmq has no support under .NET Core 2.2?

**Comment by bording** [comment]
@eleg8r That's correct. Microsoft has not released a System.Messaging package that works on .NET Core, so we can't support MSMQ on .NET Core until they do.

**Comment by bording** [comment]
If you'd like to add your feedback to request support for MSMQ, the issue to do that on is https://github.com/dotnet/corefx/issues/6204

**Comment by eleg8r** [comment]
@bording Thank you for your quick response

**Comment by HEskandari** [comment]
I'll close the issue for now, as it is not possible to support MSMQ with .NET Core. We'll have this on our radar should it be possible to support in the future.
