### ISSUE TITLE
Using callbacks to reply with Int or Enums is broken

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus#5382]
## Who's affected

Callback users on core 7.1.8 or 6.5.6 that uses [`int` or `enum` values as response types](https://docs.particular.net/nservicebus/messaging/callbacks#using-callbacks).

## Symptoms

Reply operations fail with an `ArgumentNullException`.

## Backported to

- 6.5.7 #5387 

## User report

The latest update to MessageOperations.cs broke callbacks for me.  I use `context.Reply(1)` and such - which now causes an argument null exception 

```
[02:39:06.524 WRN UOW Executor] <UOWException> Received exception while processing message Library.Networking.Messages.Ping
domain_1        | System.ArgumentNullException: Value cannot be null.
domain_1        | Parameter name: messageType
domain_1        |    at new NServiceBus.Pipeline.OutgoingLogicalMessage(Type messageType, object message)
domain_1        |    at Task NServiceBus.MessageOperations.ReplyMessage(IBehaviorContext context, Type messageType, object message, ReplyOptions options)
domain_1        |    at async Task Aggregates.Internal.BulkInvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
domain_1        |    at async Task NServiceBus.SagaPersistenceBehavior.Invoke(IInvokeHandlerContext context, Func<IInvokeHandlerContext, Task> next)
domain_1        |    at async Task NServiceBus.LoadHandlersConnector.Invoke(IIncomingLogicalMessageContext context, Func<IInvokeHandlerContext, Task> stage)
domain_1        |    at async Task Aggregates.Internal.LogContextProviderBehaviour.Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
domain_1        |    at async Task NServiceBus.InvokeSagaNotFoundBehavior.Invoke(IIncomingLogicalMessageContext context, Func<IIncomingLogicalMessageContext, Task> next)
domain_1        |    at async Task Library.Validation.FluentValidationBehaviour.Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
domain_1        |    at async Task Aggregates.Internal.LocalMessageUnpack.Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
domain_1        |    at async Task Aggregates.Internal.UnitOfWorkExecutor.Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
```

Seems due to this change - https://github.com/Particular/NServiceBus/commit/f14473c8cfaab0857e6c641ec7cb5ee4a0ef8fea#diff-59e8e774c2bd8041f702a3a0f23d4de2R120

Which runs the reply message object through IMessageMapper but doesn't account for if the message is not a mapped type.

Running the callbacks request/reply sample should confirm this bug

**Comment by andreasohlund** [comment]
Good catch, the callbacks makes an unfortunate assumption that core will throw late enough so that callbacks can intercept. Raise https://github.com/Particular/NServiceBus/pull/5383 to address this.

What's the urgency for a fix, are you able to run with 7.1.7 until we can get this released?

**Comment by volak** [comment]
Its not crucial no - I'll just wait to update for a bit 

Thanks

**Comment by andreasohlund** [comment]
We've made this a prio so expect a fix to be out shortly
