### ISSUE TITLE
System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'

### ISSUE THREAD

**Issue by fazalWahid56** [Particular/NServiceBus#5390]
My NServiceBus is operating correctly but shows the following error numerous times a day. 

**These are the packages that i am using:**

`<PackageReference Include="NServiceBus" Version="7.1.6" />
    <PackageReference Include="NServiceBus.Callbacks" Version="3.0.0" />
    <PackageReference Include="NServiceBus.Heartbeat" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Metrics.ServiceControl" Version="3.0.2" />
    <PackageReference Include="NServiceBus.MSDependencyInjection" Version="0.1.3" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="1.0.1" />`  

**I am getting following warning succeeded by error message:**
`2019-05-20 07:27:57.8737|40|Warn|NServiceBus.DeserializeLogicalMessagesConnector|
Could not determine message type from message header 'NServiceBus.Metrics.EndpointMetadataReport'. 
MessageId: c5dfb060-ee8b-49a5-82c5-9b48f64f5217`

`2019-05-20 07:27:57.8737|40|Error|NServiceBus.RecoverabilityExecutor|Moving message 'c5dfb060-ee8b-49a5-82c5-9b48f64f5217' to the error queue 'Proj.Esb.Test.ServiceControl.Errors' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message c5dfb060-ee8b-49a5-82c5-9b48f64f5217 ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.
Ensure the following:`

`1. 'Newtonsoft.Json.Linq.JObject' is included in initial scanning.`

`2. 'Newtonsoft.Json.Linq.JObject' implements either 'IMessage', 'IEvent' or 'ICommand' or alternatively, if you don't want to implement an interface, you can use 'Unobtrusive Mode'.`
   
`at NServiceBus.Unicast.Messages.MessageMetadataRegistry.GetMessageMetadata(Type messageType)
   at NServiceBus.Pipeline.LogicalMessageFactory.Create(Type messageType, Object message)
   at NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage)
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TransactionScopeSuppressBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<ProcessMessage>d__21.MoveNext()2019-05-20 `

**Comment by junaidahmed92** [comment]
I am facing the same issue...

**Comment by bording** [comment]
@fazalWahid56 What serializer do you have configured? In your list of packages, I don't see [NServiceBus.Newtonsoft.Json](https://docs.particular.net/nservicebus/serialization/newtonsoft) listed, so your endpoint is likely not configured to handle JSON messages.

If your endpoint is receiving JSON messages, then you need to add the package and configure the endpoint to use it.

**Comment by indualagarsamy** [comment]
@fazalWahid56 - What @bording mentioned. Also, here's the documentation on configuring your json serializer: https://docs.particular.net/nservicebus/serialization/newtonsoft
Can you let us know if it helps? Thanks.

**Comment by fazalWahid56** [comment]
@bording i have not configured any serializer but not any of my end point is receiving JSON message. It receives simple commands i.e classes inherited from ICommand with simple string properties. Do i still need to confugure NewtonsoftSerializer?

**Comment by andreasohlund** [comment]
Looking at the message that fails:

>Could not determine message type from message header 'NServiceBus.Metrics.EndpointMetadataReport'. 

it seems that you have misconfigured our metrics package to send it's data to your endpoint instead of the metrics backend, see:

https://docs.particular.net/monitoring/metrics/install-plugin#configuration

Could that be it?

**Comment by indualagarsamy** [comment]
Hey @fazalWahid56 - any updates?

**Comment by fazalWahid56** [comment]
@indualagarsamy its there.

1) Tried solution provided by @bording. Its throwing new exception that makes service control crash due to errors. (stack trace added at the end of comment.) i added following line of code. 
      `endpointConfiguration.UseSerialization<NewtonsoftSerializer>();`

2) @andreasohlund  i have reconfirmed. I have following configuration for metrics. 
     `var metrics = endpointConfiguration.EnableMetrics();
            metrics.SendMetricDataToServiceControl(
                serviceControlMetricsAddress: "ServiceControl",
                interval: TimeSpan.FromSeconds(2)
            );`

**error with applying serializer:** (None of my end point is receiving Json object, is still think i dont need newtonsoft serializer) 

`2019-06-12 10:46:18.614 ERROR NServiceBus.RecoverabilityExecutor Moving message 'e57a9bbb-a42f-4b63-b41e-aa6a005f1823' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message e57a9bbb-a42f-4b63-b41e-aa6a005f1823 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()`

**Comment by andreasohlund** [comment]
>i have reconfirmed. I have following configuration for metrics.
var metrics = endpointConfiguration.EnableMetrics(); metrics.SendMetricDataToServiceControl( serviceControlMetricsAddress: "ServiceControl", interval: TimeSpan.FromSeconds(2) );

Could it be some other endpoint that is misconfigured to send its metrics to your endpoint? 

`EndpointMetadataReport` can only come from the metrics plugin - https://github.com/Particular/NServiceBus.Metrics.ServiceControl/blob/master/src/NServiceBus.Metrics.ServiceControl/ReportingFeature.cs#L176

**Comment by fazalWahid56** [comment]
@andreasohlund  the only code that log metrics is the above configuration i mentioned. 
Meanwhile in service control management log i found same error with "ServiceControl.Plugin.Heartbeat.Messages.EndpointHeartbeat" also. 

`2019-06-12 17:04:21.8971|40|Warn|NServiceBus.DeserializeLogicalMessagesConnector|Could not determine message type from message header 'ServiceControl.Plugin.Heartbeat.Messages.EndpointHeartbeat'. MessageId: 4576ae93-bce2-40b7-8792-e1d12be04f64
2019-06-12 17:04:21.8971|40|Error|NServiceBus.RecoverabilityExecutor|Moving message '4576ae93-bce2-40b7-8792-e1d12be04f64' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message 4576ae93-bce2-40b7-8792-e1d12be04f64 ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.
Ensure the following: .....`

**Comment by andreasohlund** [comment]
>logfile on serviceControl Management is increasing every second. Above mentioned error is appended in log file again and again every second.

Ah, so this is logged by service control?

>var metrics = endpointConfiguration.EnableMetrics(); metrics.SendMetricDataToServiceControl( serviceControlMetricsAddress: "ServiceControl", interval: TimeSpan.FromSeconds(2) );

It seems like you are pointing the metrics to "ServiceControl" but they should go to the metrics instance which likely is called `Particular.Monitoring` - https://docs.particular.net/monitoring/metrics/install-plugin

Have you setup the metrics instance according to https://docs.particular.net/servicecontrol/monitoring-instances/installation/ ?

**Comment by fazalWahid56** [comment]
Ohh God.  

@andreasohlund  you were write. We had the same problem in configuration. We were sending heartbeat data to "Monitoring"  and  Metrics data to "ServiceControl". Exchanging the value fixed the issue. :) 

Also more meaning full exception in such cases could help. 

Thank you all.
