### ISSUE TITLE
Authentication and authorization of messages in NServiceBus endpoints

### ISSUE THREAD

**Issue by dmossberg** [Particular/NServiceBus#5420]
We are designing a message authentication and authorization mechanism for our NServiceBus endpoints (microservices), in order to support the following scenarios: 

a)	Service A will accept messages from Service B, but not from Service C. 
b)	Service A will accept messages “on behalf of” User X, but not of User Y. 

We are not willing to just trust any message from any endpoint/service that has successfully authenticated to the service bus (we are using RabbitMQ transport), so we are considering different options NServiceBus messages can provide verifiable information about the message’s sender and security context. 

Some approaches we have considered: 

1. Use OAuth2/JWT tokens and pass them along with the messages (we see you considered this in the past, and decided not to implement it: https://github.com/Particular/NServiceBus/issues/127). We already have OIDC/OAuth2 infrastructure for authentication, so this is our preferred option, but we also see a number of potential issues, like message size, access token expiration, etc.

2. Use other NServiceBus “out of the box” message authorization data from the message headers and/or message body. This seems less secure (or not secure at all), but we would be happy to be proved wrong about this assumption. 

3. Mutual endpoint authentication based on encrypted message properties or headers. This could arguably cover scenario a (we trust the sender based on shared secrets), but it doesn’t cover scenario b. For b we could combine this approach with one of the previous options. 

What are your recommendations and considerations about authentication with NserviceBus? Are we thinking about this correctly? Are there other better options we have not considered?

Thanks in advance, 
Daniel

**Comment by yvesgoeleven** [comment]
@dmossberg have you considered to do the authentication with OAuth/JWT tokens at the edge of the system and then extract the business relevant claims out, to be passed into the messages (potentially in encrypted properties or headers). So a combination of 1 & 3 basically. This is what I do in my own designs and it has worked fine for all my usecases so far.

**Comment by HEskandari** [comment]
@dmossberg Did the answer above give you a direction? Do you still need assistance on this?

**Comment by HEskandari** [comment]
Closing as we didn't get a response. Please reopen if you feel this requires further actions.
