### ISSUE TITLE
Async serializer?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5423]
Given System.Text.Json supports async, should the NSB serializer api also support it?

**Comment by ramonsmits** [comment]
Given the fact that we are currently using MemoryStreams to (de)serialized there currently doesn't seem to be an immediate benefit from using the async APIs but definitely should be considered for the next major.

**Comment by timbussmann** [comment]
> Given System.Text.Json supports async, should the NSB serializer api also support it?

I think that's definitely something to consider once we're trying to adopt `System.Text.Json` but that might take a while and I'm not sure there is a huge value in updating the existing serializer interfaces to async already?
