### ISSUE TITLE
Add support for unobtrusive IHandleMessages<IMessage>

### ISSUE THREAD

**Issue by ivanpaulovich** [Particular/NServiceBus#5459]
Hi all,

Is it possible to remove the IHandleMessages<IMessage> using the unobtrusive and conventions?

I found this issue that was solved without much information:
https://github.com/Particular/NServiceBus/issues/151

What's the current status?

**Comment by andreasohlund** [comment]
Not supported at the moment, what’s your use case? (I assume that you want to avoid referencing NServiceBus?)

**Comment by timbussmann** [comment]
7.2 introduces some necessary changes which technically allow to write handlers using lambdas or other delegates. If you're interested you can have a look at this project which implements the support for lambda handlers: https://github.com/timbussmann/Community.NServiceBus.LambdaHandlers
note that this isn't available on github yet as it requires NServiceBus 7.2 to be released (expected to happen soon).

**Comment by ivanpaulovich** [comment]
Hi @timbussmann! That's exactly what I need.
Looking forward for the next release.

**Comment by timbussmann** [comment]
hey @ivanpaulovich, the package is now available on nuget if you want to give it a try: https://www.nuget.org/packages/Community.NServiceBus.LambdaHandlers/0.1.0
