### ISSUE TITLE
OpenTracing support?

### ISSUE THREAD

**Issue by ivanpaulovich** [Particular/NServiceBus#5461]
Hi all,

Does NServiceBus have built-in support to [Open Tracing](https://github.com/opentracing/opentracing-csharp)?
I am trying to setup it but I am not sure how these pieces should work together.

**Comment by danielmarbach** [comment]
Hi

NServiceBus doesn't have built-in support for OpenTracing. I'm not too familiar and I only looked at it briefly but it seems you should be able to manage the span of the tracers via behaviors?

https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

If you push your work to a GitHub repository we might be able to help out a bit there over our regular support

**Comment by ivanpaulovich** [comment]
Hi @danielmarbach,

I did as you said. Added the Behavior:
```
public class TracingHandlingBehavior : Behavior<IIncomingLogicalMessageContext>
{
    private readonly ITracer _tracer;

    public TracingHandlingBehavior(ITracer tracer)
    {
        _tracer = tracer;
    }

    public override async Task Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
    {
        using (var scope = _tracer.BuildSpan("MyTrace").StartActive(true))
        {
            if (context.MessageHeaders.ContainsKey("x-correlation-id"))
            {
                var correlationId = context.MessageHeaders["x-correlation-id"];
                scope.Span.SetTag("x-correlation-id", correlationId);
            }

            // custom logic before calling the next step in the pipeline.

            await next().ConfigureAwait(false);

            // custom logic after all inner steps in the pipeline completed.
        }
    }
}
```
Setup the DI:
```
services.AddSingleton<ITracer>(serviceProvider =>
{
    string serviceName = "MySystem";

    // This will log to a default localhost installation of Jaeger.
    var tracer = new Tracer.Builder(serviceName)
        .WithSampler(new ConstSampler(true))
        .Build();

    // Allows code that can't use DI to also access the tracer.
    GlobalTracer.Register(tracer);

    return tracer;
});

services.AddOpenTracing();
```
And added the references.
```
<PackageReference Include="Jaeger" Version="0.3.6" />
<PackageReference Include="OpenTracing" Version="0.12.1" />
<PackageReference Include="OpenTracing.Contrib.NetCore" Version="0.6.2" />
```

It is working.

**Comment by danielmarbach** [comment]
Hi ivan

You can also consider putting the behavior into an earlier stage of the pipeline if you want to trace more than the logical messages or have multiple traces at different stages, see the stages overview

https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors

Glad it is working!
