### ISSUE TITLE
Understanding how many retries a message went through from headers?

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus#5463]
I'm using serviceinsight and am trying to awnser the following questions based on NServiceBus headers on the message but having a hard time.

1. What headers tell me how many immediate retries had to happen before the message was succesful?
2. What headers tell me how many delayed retries occured before a message was successful?

Looking here i see the Delayed retry count is supposed to be in a header ( https://docs.particular.net/nservicebus/messaging/headers ).  I assume the NServiceBus.Retries header only gets set when delayed retries start happening?  Is it not possible to keep track of immediate retries since they all happen in memory?

**Comment by SzymonPobiega** [comment]
Hi

Yes, your assumption about `NServiceBus.Retries` is correct. Is is only set when the first delayed retry is scheduled. As far as I see in the code, this header is never cleared so it should be visible in an audited message. 

Regarding the immediate retries, they either happen in memory in a `for` loop or by aborting the receive transaction. Either way the number of the retries is not visible.

If you need these values for monitoring purposes, the ServicePulse monitoring provides aggregate values for retries. If you need to have specific values for messages, you can subscribe for recoverability notifications and execute some custom logic there.

**Comment by TraGicCode** [comment]
Hey @SzymonPobiega ,

I'm actually not seeing the NServiceBus.Retries header being set on our messages that make it to the error queue.  Can you see if you can reproduce this issue on your end?  We are using NServiceBus 7.1.7

**Comment by SzymonPobiega** [comment]
This is because when a message is moved to the error queue, the headers are removed (by `MoveToErrorsExecutor` class). 

I think you could copy these headers to a custom headers in a custom recoverability policy if you need them preserved.

**Comment by TraGicCode** [comment]
Oh I see.  Sounds like there should be some call out in the docs saying they are stripped when sent to error queue and are used for the implementation of delayed retries internally

**Comment by SzymonPobiega** [comment]
Does it look OK now https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/headers.md#retries-handling-headers ?

**Comment by TraGicCode** [comment]
Yes this is perfect.  Thank you @SzymonPobiega
