### ISSUE TITLE
Handler registration through DependencyInjection in NServiceBus 7.2

### ISSUE THREAD

**Issue by carl-berg** [Particular/NServiceBus#5469]
I'm having a problem with handler registration when changing from NSB `7.1.10` to `7.2.0`. To complicate matters i'm using a custom object builder for Lamar. The problem manifests as after the upgrade my handlers are not found: `No handlers could be found for message type: MyMessage`.

When debugging component registration in version `7.1.10` i can see, among others, first a call to `Configure<LoadHandlersConnector>(...)` and then a call to `Configure(...)` for my handler, but in version `7.2.0` i don't see either of these calls. Has something changed recently or is there a need to manually register handlers now?

**Comment by andreasohlund** [comment]
There were some changes around DI but nothing that should affect handlers.

Can you the configuration code of the endpoint that is causing the issues?

Have you seen https://docs.particular.net/nservicebus/dependency-injection/#externally-managed-mode ? You might consider switching to the official Lamar adapter for ms di similar to https://docs.particular.net/samples/dependency-injection/aspnetcore/#configuring-to-use-shared-di-with-autofac?

**Comment by carl-berg** [comment]
Configuration for my repro is quite simple:
```csharp
var config = new EndpointConfiguration("TestEndpoint");
var container = new Container(sr => { });
config.UseContainer(new LamarObjectBuilder(container));
config.UseTransport<LearningTransport>();
config.UsePersistence<LearningPersistence>();
config.Recoverability()
     .CustomPolicy((cfg, context) => RecoverabilityAction.MoveToError(cfg.Failed.ErrorQueue));
var endpoint = await Endpoint.Start(config);
await endpoint.SendLocal(new Feature.Message());
Console.WriteLine("\r\nEndpoint created and configured; press any key to stop program\r\n");
Console.ReadKey();
await endpoint.Stop();
```
LamarObjectBuilder looks like this:
```csharp
public class LamarObjectBuilder : global::NServiceBus.ObjectBuilder.Common.IContainer
{
    private readonly IContainer _container;
    private readonly bool _isContainerOwner;
    private readonly ISet<Type> _configuredInstances = new HashSet<Type>();
    private ServiceRegistry _cachedRegistrations = null;
    public LamarObjectBuilder()
    {
        _container = new Container(c => { });
        _isContainerOwner = true;
    }

    public LamarObjectBuilder(IContainer container) : this(container, false) { }

    protected LamarObjectBuilder(IContainer container, bool isContainerOwner)
    {
        _container = container;
        _isContainerOwner = isContainerOwner;
    }

    public object Build(Type typeToBuild)
    {
        EnsureRegistration();
        var instance = _container.GetInstance(typeToBuild);
        return instance;
    }

    public IEnumerable<object> BuildAll(Type typeToBuild)
    {
        EnsureRegistration();
        return _container.GetAllInstances(typeToBuild).Cast<object>();
    }

    public global::NServiceBus.ObjectBuilder.Common.IContainer BuildChildContainer()
    {
        EnsureRegistration();
        return new LamarObjectBuilder(_container.GetNestedContainer() as IContainer, true);
    }

    public void Configure(Type component, DependencyLifecycle dependencyLifecycle)
    {
        ServiceDescriptor makeDescriptor(ServiceLifetime lifetime) => new ServiceDescriptor(component, component, lifetime);
        AddDependency(component, makeDescriptor, dependencyLifecycle);
    }

    public void Configure<T>(Func<T> component, DependencyLifecycle dependencyLifecycle)
    {
        if (typeof(T).IsValueType)
        {
            throw new ArgumentException("Invalid type");
        }

        var pluginType = typeof(T);

        ServiceDescriptor makeDescriptor(ServiceLifetime lifetime) => new ServiceDescriptor(pluginType, s => component.Invoke(), lifetime);
        AddDependency(pluginType, makeDescriptor, dependencyLifecycle);
    }

    public void Dispose()
    {
        if (_isContainerOwner)
        {
            _container.Dispose();
        }
    }

    public bool HasComponent(Type componentType)
    {
        return _container.Model.HasRegistrationFor(componentType) || _cachedRegistrations?.Any(x => x.ServiceType == componentType) == true;
    }

    /// <summary>
    /// Using cached registrations as a way to overcome problems with multiple calls to Configure
    /// See https://github.com/JasperFx/lamar/issues/153 for reference
    /// </summary>
    protected void EnsureRegistration()
    {
        if (_cachedRegistrations != null)
        {
            _container.Configure(_cachedRegistrations);
            _cachedRegistrations = null;
        }
    }

    public void RegisterSingleton(Type lookupType, object instance)
    {
        ConfigureContainer(registry =>
        {
            registry.AddSingleton(lookupType, instance);
            registry.Policies.SetAllProperties(p => p.TypeMatches(t => t == lookupType));
        });
    }

    public void Release(object instance) { }

    protected IEnumerable<Type> GetAllInterfacesImplementedBy(Type t)
    {
        return t.GetInterfaces().Where(x => !x.FullName.StartsWith("System."));
    }

    private void AddDependency(Type component, Func<ServiceLifetime, ServiceDescriptor> getDescriptor, DependencyLifecycle dependencyLifecycle)
    {
        lock (_configuredInstances)
        {
            if (_configuredInstances.Contains(component))
            {
                return;
            }
        }

        var lifecycle = GetLifetime(dependencyLifecycle);
        ConfigureContainer(registry =>
        {
            registry.Add(getDescriptor(lifecycle));
            registry.Policies.SetAllProperties(p => p.TypeMatches(t => t == component));
            foreach (var implementedInterface in GetAllInterfacesImplementedBy(component))
            {
                registry.Add(new ServiceDescriptor(implementedInterface, provider => provider.GetService(component), lifecycle));
                registry.Policies.SetAllProperties(p => p.TypeMatches(t => t == implementedInterface));
            }
        });

        lock (_configuredInstances)
        {
            _configuredInstances.Add(component);
        }
    }

    private ServiceLifetime GetLifetime(DependencyLifecycle dependencyLifecycle)
    {
        switch (dependencyLifecycle)
        {
            case DependencyLifecycle.InstancePerCall:
                return ServiceLifetime.Transient;
            case DependencyLifecycle.SingleInstance:
                return ServiceLifetime.Singleton;
            case DependencyLifecycle.InstancePerUnitOfWork:
                return ServiceLifetime.Scoped;
        }

        throw new ArgumentException("Unhandled lifecycle - " + dependencyLifecycle);
    }

    private void ConfigureContainer(Action<ServiceRegistry> action)
    {
        if (_cachedRegistrations is null)
        {
            _cachedRegistrations = new ServiceRegistry();
        }

        action(_cachedRegistrations);
    }
}
```

I tried using the externally managed approach but ran into some issues. I would rather use the MS DI -approach (if it doesn't have a dependency to asp.net).  I couldn't figure out which package contains the `services.AddNServiceBus(endpointConfiguration)` method though?

**Comment by carl-berg** [comment]
I guess i should use `NServiceBus.MSDependencyInjection`. Seems to work for my simple case. Will check and see if it works for the real service aswell.

**Comment by andreasohlund** [comment]
>I guess i should use NServiceBus.MSDependencyInjection. Seems to work for my simple case. Will check and see if it works for the real service aswell.

I would recommend against that in the long run. That package is considered deprecated. You could use the generic host from MS perhaps?

Ie, copy 

https://github.com/Particular/docs.particular.net/tree/master/samples/dependency-injection/aspnetcore/Core_7.2/NServiceBus.Extensions.DependencyInjection (we're about to release this as an official package)

into your project. And set it up according to: (changing AutoFac to Lamar)

https://github.com/Particular/docs.particular.net/tree/15089a24d0467fb276af57e4dc7cbe7f05185dfd/samples/dependency-injection/aspnetcore/Core_7.2/SampleAutofac to avoid the webhost builder.

Would that work?

**Comment by carl-berg** [comment]
I think i can make do with the code from `NServiceBus.Extensions.DependencyInjection` minus the hosting part which i don't need. A bit tricky to get things in the right order since i need to get things out of the container before i create the endpoint but i think i got it working now.

**Comment by andreasohlund** [comment]
Great news, anything you think we can do better on our end?

**Comment by carl-berg** [comment]
One thing that feels a bit clunky is when you need to pull things from the container during the configuration phase. In my case i can configure the container after it's been created, but that is a bit of a risky move, at least with Lamar because it's not really intended to be used that way. Not sure if there's anything that can be done about that though 😄.

For Lamar, I ended up with this extension method to wireup the NServicebus dependencies and start the endpoint, if anyone would run into the same problem:
```csharp
public static Task<IEndpointInstance> StartEndpoint(this IContainer container, EndpointConfiguration endpointConfiguration)
{
    IStartableEndpointWithExternallyManagedContainer startableEndpoint = null;
    var nserviceBusRegistry = new ServiceRegistry();
    nserviceBusRegistry.AddSingleton(sp => startableEndpoint.MessageSession.Value);
    var adapter = new ServiceCollectionAdapter(nserviceBusRegistry);
    startableEndpoint = EndpointWithExternallyManagedContainer.Create(endpointConfiguration, adapter);
    container.Configure(nserviceBusRegistry);
    return startableEndpoint.Start(new ServiceProviderAdapter(container));
}
```

**Comment by andreasohlund** [comment]
>One thing that feels a bit clunky is when you need to pull things from the container during the configuration phase

Can you elaborate on this, is there something we do that force you to do resolves from the container to early?

Could it be that you're calling start to early? (why do you need to return the `IEndpointInstance` in your code above?)

Eg. in https://docs.particular.net/samples/dependency-injection/aspnetcore/#configuring-to-use-shared-di-with-autofac the endpoint is started as a hosted service.

**Comment by carl-berg** [comment]
>>One thing that feels a bit clunky is when you need to pull things from the container during the configuration phase

>Can you elaborate on this, is there something we do that force you to do resolves from the container to early?

It's not a big deal but i this particular case we're using microsoft `ILogger` logging which is a bit hard to setup without using the service collection extensions so we setup logging in the container and then use this configuration to inject it into NServiceBus:
```csharp
var loggerFactory = container.GetService<Microsoft.Extensions.Logging.ILoggerFactory>();
var logFactory = LogManager.Use<MicrosoftLogFactory>();
logFactory.UseMsFactory(loggerFactory);

var logger = container.GetService<ILogger<Program>>();
endpointConfiguration
    .ConfigureRecoverability() //Custom config for delays etc
    .NotifyOnMoveToErrorQueue(new LogMoveToErrorQueue(logger)) //Logging on move to error queue
    .ConfigureLicense(config);
```

We're currently using `ServiceBase` for hosting. We haven't yet switched to something like `Microsoft.Extensions.Hosting.WindowsServices` (but we probably will in the future)  so in this case i want the endpoint returned so i can dispose it when the service is stopped, and possibly use it during debugging to send local messages.

**Comment by carl-berg** [comment]
Sure. Thanks for the help!
