### ISSUE TITLE
IInvokeHandlerContext behavior not working

### ISSUE THREAD

**Issue by rezajp** [Particular/NServiceBus#5517]
I am trying to add a Behavior like below to the pipeline in order to access IMessageHandlerContext but the behavior is not picked up.

```c#
 configuration.RegisterComponents(c => c.ConfigureComponent<ContextBehaviour>(DependencyLifecycle.InstancePerCall));

            configuration.Pipeline.Register(@behavior: typeof(ContextBehaviour), "test");

            container.Register(Component.For<ContextAccessor>());
```

And that is the definition of the Behavior
```c#
 public class ContextBehaviour : Behavior<IInvokeHandlerContext>
    {
        public override  Task Invoke(IInvokeHandlerContext context, Func<Task> next)
        {
            var contextAccessor = context.Builder.Build<ContextAccessor>();
            // throw new Exception("Context behaviour invoke issue");
            contextAccessor.Context = context;
            return next();
        }
        public class Registration : RegisterStep
        {
            public Registration()
                : base(stepId: "ContextBehaviour", behavior: typeof(ContextBehaviour), description: "Sets IMessageHandlerContext for ContextAccessor")
            {
            }
        }


        
    }
    public class ContextAccessor
    {
        public IMessageHandlerContext Context { get; set; }
    }
```

We have a Behavior<IIncomingPhysicalMessageContext> added to the pipleline and that is working. However, the above one doesn't work and Invoke method for  is never called. I am not sure if I need to replace another behavior or something else is missing.

**Comment by WojcikMike** [comment]
Hi @rezajp 

We have a sample that illustrates registering Behavior<IInvokeHandlerContext>: 
https://docs.particular.net/samples/pipeline/handler-timer/

I would recommend downloading the sample, running it locally and changing it to include your changes. When I modified the sample to use 
```
configuration.RegisterComponents(c => c.ConfigureComponent<ContextBehaviour>(DependencyLifecycle.InstancePerCall));
configuration.Pipeline.Register(typeof(ContextBehaviour), "test");
```
From your example, and everything worked. That leads me to believe that most likely the behavior of not executing a behavior is most likely some configuration issue rather than a bug, but please confirm on your end.

**Comment by mikeminutillo** [comment]
Closing this one as there has been no response in over six months. @rezajp if you still require assistance, please open a [support case](https://particular.net/support).
