### ISSUE TITLE
Slow publish AzureServiceBusTransport

### ISSUE THREAD

**Issue by ChristofKTN** [Particular/NServiceBus#5537]
We are using AzureServiceBusTransport and publish a lot of events in a short time in a saga.
After publishing several 100's of events it takes several seconds to publish 50 more events while still increasing.
Is this an issue or a configuration that needs to be changed to allow this?

**Comment by yvesgoeleven** [comment]
@ChristofKTN are you using standard or premium tier?

**Comment by SeanFeldman** [comment]
@ChristofKTN which transport package are you using and utilization your endpoint has (load, number of endpoints, platform tools, etc)?

Perhaps the issue should be a support case? You can raise it at https://particular.net/support.

**Comment by ChristofKTN** [comment]
We are using standard tier, on a local endpoint, no subscribers yet.

**Comment by SeanFeldman** [comment]
@ChristofKTN let's take this through the support channel as you'll need to provide information such as log file(s), configuration code, etc. We can post the findings here, once the issue is identified.
