### ISSUE TITLE
isnt AsA_Publisher not a thing anymore?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5538]
https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionReceiverBehavior.cs#L61

> Subscription message from {subscriberAddress} arrived at this endpoint, yet this endpoint is not configured to be a publisher. To avoid this warning make this endpoint a publisher by configuring a subscription storage or using the AsA_Publisher role

**Comment by andreasohlund** [comment]
Good catch, the host + the roles are obsoleted so I've raised https://github.com/Particular/NServiceBus/pull/5539 to remove the mention of `AsA_Publisher `

**Comment by SimonCropp** [comment]
@andreasohlund thanks :)
