### ISSUE TITLE
Routing not working based on Assembly for generic types

### ISSUE THREAD

**Issue by brijgogogo** [Particular/NServiceBus#5575]
I have a scenario where I am sending a generic Command like: AddRequest<TObject>.

When I configure routing using Assembly, it doesn't work (error: no destination specified):
`    routeSettings.RouteToEndpoint(assembly, "App2.Endpoint");`
However the command gets sent successfully when configuring routing via type:
```
  var genericType = Type.GetType("SharedApp.AddRequest`1[[SharedApp,MyObject]],SharedApp");
   routeSettings.RouteToEndpoint(genericType, "App2.Endpoint");
```

Is something wrong/missing while configuring it via assembly ?

https://stackoverflow.com/questions/60076813/nservicebus-routing-not-working-based-on-assembly-for-generic-types

**Comment by SzymonPobiega** [comment]
Hi @brijgogogo 

When NServiceBus scans the assembly it looks for message types but all it finds is an open generic type `AddRequest<T>`. Now when you send a message, you send an instance of `AddRequest<MyObject>` which is a closed generic type, different from the one discovered. NServiceBus routing system is not aware of generic types so can't find the route. To make it work you would have to create your own type discovery mechanism:
- given the assembly, enumerate all its types
- for each open generic type message type, find all types that it can accept as the type parameter
- for each of these parameter types, create a closed generic type
- register that close generic type in the routing

**Comment by brijgogogo** [comment]
Yeah, that's what I am doing now. Thank you for the explanation :)
