### ISSUE TITLE
Is the AddNServiceBus() method callable on an IServiceCollection object?

### ISSUE THREAD

**Issue by xocolatl-aficionado** [Particular/NServiceBus#5582]
I'm trying to setup NSB in a .NET Core Web Api project to send commands to a .NET Core Endpoint project containing handlers to receive messages. Code so far to register NSB:
```
public void ConfigureServices(IServiceCollection services)
        {
            ......
            ......
            //services.AddNServiceBus(endpointConfiguration);
            var endpoint = Endpoint.Start(SetupEndpointConfiguration()).GetAwaiter().GetResult();
            services.AddSingleton(endpoint);
        }
```
According to NSB docs ( https://docs.particular.net/samples/dependency-injection/aspnetcore/ ), **using built in DI of .net core** ( 3.1 for me), we should be able to call .AddNServiceBus() on the services object. However, I am unable to do so **since VS cannot resolve the method**. I have the following libraries installed:
   ```
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.OpenApi.Models;
    using NServiceBus;
    using Serilog;
```
**What I've tried:** Made an endpoint using Endpoint.Start() and registered it using addSingleton() as shown in the first code block. But not satisfied since the docs should let me use the AddNServiceBus() to register NSB within ConfigureServices().
Why is .AddNServiceBus() not resolvable, despite having NSB installed?

**Comment by bording** [comment]
@xocolatl-aficionado It sounds like you're using ASP.NET Core 3.1, right? In that case, you need to add a reference to the NServiceBus.Extensions.Hosting package, which is where the `AddNServiceBus` is implemented.

**Comment by xocolatl-aficionado** [comment]
![image](https://user-images.githubusercontent.com/17209734/74554979-557ca000-4f20-11ea-8ddc-8c4dcfc70d21.png)
I do have that package. Do you think this may be a versioning and/or .net core 3.1 compatibility problem? @bording

**Comment by bording** [comment]
If you do already have the package referenced, then I'd only be guess as to what problem you're having. Is the code you're working on available somewhere publicly where I could take a look at it?

**Comment by kbaley** [comment]
@xocolatl-aficionado If [this](https://stackoverflow.com/questions/60230087/is-the-addnservicebus-method-callable-on-an-iservicecollection-object) is the same issue, then I would guess that you are missing a required `using` statement:

> using NServiceBus.Extensions.DependencyInjection;

Can you double-check if this is included? If it is, I could also check if the other required using statements are there. You can see this in the sample you referenced by clicking `COPY USINGS` right about the code snippet.

**Comment by xocolatl-aficionado** [comment]
But is there a NServiceBus.Extensions.DependencyInjection package? I dont see it on my nuget manager.

**Comment by dvdstelt** [comment]
It's not a NuGet package, the code is in the sample itself
https://github.com/Particular/docs.particular.net/tree/master/samples/dependency-injection/aspnetcore/Core_7.2/NServiceBus.Extensions.DependencyInjection

**Comment by timbussmann** [comment]
@xocolatl-aficionado in asp.net core 3 (and higher), you do not use `AddNServiceBus` to the `IServiceCollection` inside `ConfigureServices` but you configure NServiceBus directly on the host builder using `UseNServiceBus` as documented here: https://docs.particular.net/nservicebus/hosting/extensions-hosting

The `AddNServiceBus` is part of [this community package](https://github.com/timbussmann/Community.NServiceBus.WebHost) which supports the ASP.NET Core 2 WebHost.

Does that help?

**Comment by timbussmann** [comment]
I'm closing this issue for now but please feel free to reopen this issue or get in touch with our support if you continue to have issues to get this working.
