### ISSUE TITLE
Headers missing from Behavior<IOutgoingLogicalMessageContext>

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5635]
I have a `Behavior<IOutgoingLogicalMessageContext>` : https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/master/src/NServiceBus.Serilog/MessageAudit/LogOutgoingMessageBehavior.cs

After updating to NSB 7.3 the number of headers in `IOutgoingLogicalMessageContext.Headers` went from 8 to 4.

A failing test can be seen here https://ci.appveyor.com/project/SimonCropp/nservicebus-serilog/builds/32779395/tests

Specifically the following are missing

 * OriginatingHostId
 * OriginatingEndpoint
 * OriginatingMachine
 * ReplyToAddress

NSB 7.2.4

![image](https://user-images.githubusercontent.com/122666/81513385-7dd33980-936b-11ea-814b-c4d6d42955b2.png)

NSB 7.3.0

![image](https://user-images.githubusercontent.com/122666/81513693-9c3a3480-936d-11ea-863b-cabe2c2eef70.png)

**Comment by mikeminutillo** [comment]
@SimonCropp Those headers are all applied by behaviors in the Outgoing Logical context. It is possible that they are being added after your behavior.

- [AddHostInfoHeadersBehavior.cs](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Hosting/AddHostInfoHeadersBehavior.cs#L19-L21)
- [ApplyReplyToAddressBehavior](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Routing/ApplyReplyToAddressBehavior.cs#L34)

**Comment by SimonCropp** [comment]
@mikeminutillo toggling this 

https://github.com/SimonCropp/MissingHeaderRepro/blob/master/Tests/Tests.csproj#L11

 between 7.2 and 7.3 makes this 

https://github.com/SimonCropp/MissingHeaderRepro/blob/master/HeaderRepro/LogOutgoingMessageBehavior.cs#L10

toggle between 4 and 8 headers

isnt that a breaking change?

**Comment by mikeminutillo** [comment]
@SimonCropp Behaviors within the same context should not rely on guaranteed ordering (without specifying ordering requirements). The fact that it works deterministically on one version is an unfortunate coincidence and not a guarantee that it will not break in future releases.

How to fix this depends on exactly what the original behavior is doing.

One way would be by adding `InsertAfter` calls to your `RegisterStep`, but I believe that the ids of those steps may also not be subject to SemVer as they are the `nameof` of a non-public class. The advantage of using `InsertAfter` is that it will throw if that registration step does not exist.

The safer (more stable) approach would be to shift the behavior to Outgoing Physical Context which guarantees that all of the behaviours in Outgoing Logical Context have been run. This may or may not make sense depending on what you are trying to achieve.

**Comment by SimonCropp** [comment]
> Behaviors within the same context should not rely on guaranteed ordering

for context, can u point me to where that is documented

**Comment by SimonCropp** [comment]
although it does seem strange that headers defined by the core are not available in the IOutgoingLogicalMessageContext

**Comment by SimonCropp** [comment]
i cant use `IOutgoingPhysicalMessageContext` since it doesnt expose the message istance

Can u point me to the magic strings to register my step inside `AddHostInfoHeadersBehavior` `ApplyReplyToAddressBehavior`.

**Comment by mikeminutillo** [comment]
The behavior ids are currently:
- `ApplyReplyToAddressBehavior`
- `AddHostInfoHeaders`

**Comment by SimonCropp** [comment]
and the doco?

**Comment by mikeminutillo** [comment]
I believe the documentation for behavior ordering is missing. I will check on it and raise a PR to clarify.

**Comment by SimonCropp** [comment]
> I believe the documentation for behavior ordering is missing

then again i would argue this is a breaking change

also note that it is pretty common to assume core defined headers will exist in IOutgoingPhysicalMessageContext.  @DavidBoike did it a week ago https://www.davidboike.dev/2020/04/overriding-the-nservicebus-conversationid/

**Comment by danielmarbach** [comment]
@SimonCropp @andreasohlund and I compared 7.2 to 7.3. NServiceBus 7.2 was registering the behaviors you mentioned in features. Feature setup order was always subjected to subtle behavior changes due to ordering of assemblies being detected, types being scanned and ordered (unless a feature declares an explicit dependency to another feature).

When it comes to assuming ordering in the same stage you can only do assume a certain kind of ordering if you use the explicit `InsertBefore` and `InsertAfter` registration. Usually it is better to take a stage that is either before the stage or after the stage that you are targeting. 

We have sent in a PR to demonstrate how the serilog code could be change.

https://github.com/NServiceBusExtensions/NServiceBus.Serilog/pull/239

We are also going to update the documentation to better reflect these subtleties. See https://github.com/Particular/docs.particular.net/pull/4835

Thanks for raising it to our attention. Closing this
