### ISSUE TITLE
Changing Exception data type is a breaking change

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5636]
https://github.com/Particular/NServiceBus/pull/5548/files

it is a datetime in this doc https://docs.particular.net/nservicebus/messaging/headers#error-forwarding-headers-example-error-headers. 

after the above PR it is a string with the broken. Yes this broke some of my code at runtime

Changing `Handler type` to a string also broke things

**Comment by SimonCropp** [comment]
not that those extra datas were explicitly added for consumption by downstream loggers https://docs.particular.net/nservicebus/logging/#additional-exception-data  which is exactly the scenario that was broken by the type changes

**Comment by SzymonPobiega** [comment]
@SimonCropp We're sorry about that. We'll investigate how to solve this situation now.

**Comment by SzymonPobiega** [comment]
So if the logging fails due to this problem, does it mean that the endpoint gets into an infinite retry loop?
