### ISSUE TITLE
Adding DeliveryConstraints to TransportOperation can have "global" side effects

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#5647]
This seemingly harmless code can have real consequences

```
var operation = new TransportOperation();
operation.DeliveryConstraints.Add(new DoNotDeliverBefore());
```

If the transport operation is not created with the list of delivery constraints it assigns a default static delivery constraints collection to the property. It being a reference type means that

```
operation.DeliveryConstraints.Add(new DoNotDeliverBefore());
```

adds the constraints globally and therefore makes suddenly all transport operations have delivery constraints.

## Who's Affected

Users of TransportOperation class that initialize it without passing DeliveryConstraints and later on add delivery constraints to it.

## Symptoms

Such usage will alter a shared static collection which can impact other messages. 

### Backported to
7.4.3 - https://github.com/Particular/NServiceBus/pull/5756
7.3.1 - https://github.com/Particular/NServiceBus/pull/5757
7.2.5 - https://github.com/Particular/NServiceBus/pull/5758

**Comment by janovesk** [comment]
All done
