### ISSUE TITLE
Question: Feature Dependency Injection

### ISSUE THREAD

**Issue by alhardy** [Particular/NServiceBus#5665]
I'm building a custom NServiceBus Feature which requires access to a registered dependency. Is there a way to access the container within a Feature? Constructure injection isn't possible and there doesn't seem to be a way to access registered dependencies from the `FeatureConfigurationContext`.

**Comment by mikeminutillo** [comment]
Features are not added to or resolved from the container and the container is not provided as a part of the feature configuration context. If you can defer your opertation until the endpoint starts up, then you can add a `FeatureStartupTask`. There is an overload that accepts `Func<IBuilder, TTask>` and you can resolve things out of the container using the `IBuilder` interface.

If you can share some details about what your feature is doing, I may be able to provide more options.

**Comment by alhardy** [comment]
I've implemented an integration with [App Metrics](https://github.com/AppMetrics/AppMetrics) to capture NSB metrics https://www.app-metrics.io/integrations/nservicebus/

All good I just supported a static instance in the library https://github.com/AppMetrics/AppMetrics/blob/dev/src/NServiceBus/src/App.Metrics.Extensions.NServiceBus/AppMetricsFeature.cs#L96
