### ISSUE TITLE
Have IMessageSession extend IPipelineContext

### ISSUE THREAD

**Issue by fjmorel** [Particular/NServiceBus#5708]
I wrote a service that handles sending sending messages based on some criteria, and had to create 2 overloads: 1 for IEndpointInstance for use in APIs and 1 for IMessageHandlerContext for use inside handlers because they have no common interface.

While writing tests for the service, I found that TestableEndpointInstance & TestableMessageHandlerContext both have IPipelineContext in their ancestry, so I was actually able to re-use most of the test code for both overloads.

Is it possible for IEndpointInstance (or IMessageSession) to extend IPipelineContext? This would greatly simplify writing code to be re-used by code inside and outside handlers.

**Comment by andreasohlund** [comment]
That separation is (currently) intentional since operations performed within the message handling pipeline behaves differently compared to operations performed outside when it comes to enlisting in transactions, delaying outgoing operations etc.

So the rationale is to not make them look similar to force users to be explicit in order to consider the things mentioned above.

Can you elaborate on the use case that you are trying to test?

**Comment by fjmorel** [comment]
They both end up having Send/Publish methods, though. Here's some samples of what I am doing.

Sometimes I generate messages that need to go to multiple routes. I have 2 overloads: 1 for `IEndpointInstance` (for use in APIs) and 1 for `IMessageHandlerContext` (for use in handlers):
```c#
foreach(var route in _realTimeRoutes)
{
    var so = new SendOptions();
    so.SetDestination(route);
    // Send them to SignalR service immediately (do not wait for end of message handling and risk OOM)
    // not necessary for IEndpointInstance but kept for consistency
    so.RequireImmediateDispatch();
    await realTimeUpdates.ForEachAsync(20, x => context.Send(x.Adapt<RealTimeUpdateLog, T>(), so));
}
```
I would like to be able to combine the methods.

For the unit tests I wrote for each one, after calling the overloads above I'm able to pass either `TestableMessageHandlerContext`/`TestableEndpointInstance` into a shared function that does my asserts using `TestablePipelineContext`:
```c#
private void Verify<T>(TestablePipelineContext context, int totalCount, int expectedCount) where T : RealTimeUpdateMessage
{
    Assert.Equal(totalCount, context.SentMessages.Count());
    var relevant = context.SentMessages.Where(x => x.Message is T);
    Assert.Equal(expectedCount, relevant.Count());
    Assert.All(relevant, obj =>
    {
        var msg = Assert.IsType<T>(obj.Message);
        // other obj/msg assertions
    });
}
```
I made this issue when I realized that both test classes extend `TestablePipelineContext`, which was useful, but the interfaces did not have a common interface.

**Comment by andreasohlund** [comment]
>They both end up having Send/Publish methods, though.

Yes that do but they do behave differently depending on the context where they are called :)

> Here's some samples of what I am doing.
 
So in your case you don't care if the message is emitted even if something fails  (indicated by ` so.RequireImmediateDispatch();`)which seems fine if this is realtime updates where new ones will follow shortly. Not calling `so.RequireImmediateDispatch()` would make it behave differently depending on where its called which would be hard to debug hence why we made the decision to keep the 2 scenarios different.

> For the unit tests I wrote for each one, after calling the overloads above I'm able to pass either TestableMessageHandlerContext/TestableEndpointInstance into a shared function that does my asserts using TestablePipelineContext

For me this is a good trade-off, you know what you are doing and that "workaround" feel like a good acknowledgement that you made a conscious decision to share code that will be called from 2 different contexts. 

Would you say that the workaround is acceptable for you?

**Comment by fjmorel** [comment]
Instead of having two overloads, I decided to use dependency injection to get IEndpointInstance. So that will work in my APIs, and my NServiceBus services will need to register the current IEndpointInstance to send these messages. Bad idea I know, but it simplifies the code enough to be worth it. We were using `RequireImmediateDispatch` anyway, so might as well leave the message handler context completely.

**Comment by andreasohlund** [comment]
I guess that would work as long as that endpoint isn't doing anything that would ever have to be transactional in any way 😬 

If you go down that path you might want to consider https://docs.particular.net/nservicebus/messaging/uniformsession (I had forgotten about it) that creates a uniform abstraction for emitting messages?

**Comment by fjmorel** [comment]
I'll keep that in mind for future services (if any) that should be used by both handlers and APIs.
