### ISSUE TITLE
NServiceBus.PerformanceCounterHelper NServiceBus performance counter log messages should be suppressed for sendonly endpoints

### ISSUE THREAD

**Issue by kristianjaeger** [Particular/NServiceBus#5711]
Actual: Messages are logged to the nsb_log_dateGoesHere.txt log file - 
"2020-08-10 15:20:47.329 INFO  NServiceBus.PerformanceCounterHelper NServiceBus performance counter for '# of msgs pulled from the input queue /sec' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation.
2020-08-10 15:20:47.329 INFO  NServiceBus.PerformanceCounterHelper NServiceBus performance counter for '# of msgs successfully processed / sec' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation.
2020-08-10 15:20:47.329 INFO  NServiceBus.PerformanceCounterHelper NServiceBus performance counter for '# of msgs failures / sec' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation."

Expected: For sendonly endpoints this should not be logged as it is misleading.  If one follows this advice an exception is thrown.

Repro: Create a sendonly endpoint and run it.

Thanks.

**Comment by andreasohlund** [comment]
Thanks for reporting this. What version of NServiceBus are you using? 

I'm asking since the latest version have the counters in a separate package and is throwing should you have it installed in a send only endpoint 

https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/master/src/NServiceBus.Metrics.PerformanceCounters/PerformanceCountersFeature.cs#L19

**Comment by kristianjaeger** [comment]
Thanks, @andreasohlund !  For this WebAPI, I'm using NServiceBus 6.5.8. So, I saw the log entries before installing the Windows Perf counters package and then that's when I saw the Exception.  Not a huge deal but the log entries seem misleading for the sendonly use case.  Perhaps there could just be a mention of not using with sendonly in the docs?  Cheers.

**Comment by andreasohlund** [comment]
Good point, I've raised https://github.com/Particular/docs.particular.net/pull/4964 to document this.

**Comment by kristianjaeger** [comment]
Thank you, @andreasohlund !
