### ISSUE TITLE
NiceToHave: Add a extra header with name of databus connection. 

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus#5725]
It would be nice to configure a name when you configure the databus. This can be used with servicepulse and serviceinsight to resolve databus properties

**Comment by SeanFeldman** [comment]
I have a hunch you're referring to the [Azure Blob data bus](https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage). And if yes, perhaps it's better to raise the suggestion there?

**Comment by JSCProjects** [comment]
Done. But I thought this should be persistent ignorant
