### ISSUE TITLE
LicenseReminder fails with access denied on macos

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5751]
```
      MessageTemplate: 'Failed to initialize the license',
      Level: 'Fatal',
      Properties: {
        SourceContext: 'NServiceBus.Features.LicenseReminder',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.UnauthorizedAccessException',
            "HResult": -2147024891,
            "Message": "Access to the path '/Users/appveyor/.local/share/ParticularSoftware' is denied.",
            "Source": 'System.IO.FileSystem',
            "InnerException": {
              Elements: {
                "Type": 'System.IO.IOException',
                "HResult": 13,
                "Message": 'Permission denied',
                "Source": null
              }
            }
          }
        }
      }
```

**Comment by bording** [comment]
Based on the `appveyor` username in that log entry, are you getting this when running tests on macOS through AppVeyor?

Per our [supported platforms](https://docs.particular.net/nservicebus/upgrades/supported-platforms) page, macOS is only supported for development purposes.

The location in question is coming from the `Environment.SpecialFolder.LocalApplicationData` enum, so this should be a writable location. By default, macOS does give write permissions to this folder, so this appears to be specific to AppVeyor's customized environment. I would consider this an AppVeyor bug if they aren't letting the user write to the user folder.

You should be able to work around this by providing a valid license when running in AppVeyor.

**Comment by SimonCropp** [comment]
fair enough
