### ISSUE TITLE
NSB 5 -> NSB 7 - is missing out NSB 6 a recommended upgrade path?

### ISSUE THREAD

**Issue by stevewgh** [Particular/NServiceBus#5777]
Current setup:
NServiceBus 5.2.26
NServiceBus.Host 6.0.2
NServiceBus.NHibernate 6.2.11
Using MSMQ transport and SQL Server for subscriptions and timeouts.

Target setup:
NServiceBus 7.4.3
NServiceBus.Transport.Msmq 1.1.0
NServiceBus.NHibernate 8.4.3
Still using the same transport and SQL Server, but self hosting the endpoint using the Microsoft.Extensions.Hosting approach.

I realise that the SQL Database schema will require the LogicalEndpoint column adding but is there anything that would prevent us from moving from NSB5 to NSB7 and skipping 6 altogether? Would you recommend this approach?

Thanks

**Comment by adamralph** [comment]
hi @stevewgh, while it's theoretically possible to skip a major version, [we don't recommend it](https://docs.particular.net/nservicebus/upgrades/#updating-dependencies).

BTW, it's usually better to ask questions such as these on our [discussion forum](https://discuss.particular.net/).
