### ISSUE TITLE
Unit testing ConfigureHowToFindSaga

### ISSUE THREAD

**Issue by tsmikael** [Particular/NServiceBus#5805]
The setup of message correlation for sagas is an important part a saga. This needs to be setup correctly for messages to find the correct saga. This can be extra important if the mapping that has been set up is of a non trivial nature (perhaps using more than one property). For larger, more complex sagas this becomes even more important.

As it stands today, there is no way of unit testing if  ConfigureHowToFindSaga has been set up correctly. This is an important piece of testing which is missing from the nservicebus testing package today. We need to be able to have automated unit tests that verify saga message correlation.

**Comment by mauroservienti** [comment]
@tsmikael One option here can be to use an open-source toolkit I created recently: [NServiceBus.IntegrationTesting](https://github.com/mauroservienti/NServiceBus.Integrationtesting). While not explicitly designed to test saga mappings it can be used to test them by exercising the real saga using real production transport and persistence if needed.

Using `NServiceBus.IntegrationTesting` multiple tests can be defined to test that the tested saga processes correctly a set of given messages. By asserting that messages are successfully processed it's inherently asserted that mappings are indeed configured correctly.

**Comment by DavidBoike** [comment]
We just released [NServiceBus.Testing 7.4](https://www.nuget.org/packages/NServiceBus.Testing/7.4.0) which includes a new [saga scenario testing feature](https://github.com/Particular/NServiceBus.Testing/issues/363) which enables you to test sagas in such a way that the `ConfigureHowToFindSaga` method does get exercised.
