### ISSUE TITLE
Best way of executing code at startup?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5841]
With the new NServiceBus.Extensions.Hosting model, i cant see an easy way to run some code against the IMessageSession at startup. For example sending a message at startup. Currently the best way i have found is a feature that does the callback (attached). This seems to be something that works OOTB? Am i missing something?

[StartupCallback.zip](https://github.com/Particular/NServiceBus/files/5586415/StartupCallback.zip)

**Comment by andreasohlund** [comment]
How about a https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#ihostedservice-interface that takes the IMessageSession as a ctor arg and sends on `StartAsync`?

Just make sure to register it after the call to `UseNServiceBus()` to make sure that the NSB is started before?

**Comment by SimonCropp** [comment]
do you think that is better than a callback delegate?

**Comment by andreasohlund** [comment]
I think both works but that approach feels more "Generic host aligned". Having to worry about the order of registrations is a downside tho but I guess that is by design from a Generic Host perspective?

It also aligns with how Asp.net gets access to the session so I think that is a benefit as well?

**Comment by SimonCropp** [comment]
IMHO it would be nice to also have the convenience of a simple callback. but if u disagree feel free to close

**Comment by andreasohlund** [comment]
I need to mull over it. Do you see any drawbacks with the hosted service approach other than the ordering issue? Are there any advantages with the callbacks approach that isn't mentioned here?

**Comment by mauroservienti** [comment]
Recently I built [NServiceBus.Extensions.EndpointStarted](https://github.com/mauroservienti/NServiceBus.Extensions.EndpointStarted) which seems to be doing what you're looking for @SimonCropp.

**Comment by SimonCropp** [comment]
seems weird to make it an external packages. it is trivial code with low tech debt to include in the core

**Comment by mauroservienti** [comment]
Dunno @SimonCropp. I solved the problem I was facing at the time I needed in the fastest possible way. I personally don't mind it being an external package. I'll raise this internally, it can be added to the next round of enhancements to Core.
