### ISSUE TITLE
Oracle Hosted CLR: No stage connector found for stage NServiceBus.Pipeline.IOutgoingPublishContext

### ISSUE THREAD

**Issue by yurimaksymenko** [Particular/NServiceBus#5843]
We are trying to get NServiceBus endpoint to send commands via MSMQ from ORACLE Hosted CLR process.
(Yes, I understand that this is a very specific scenario, ORACLE 12c CLR host allows this scenario to work. We got ORACLE 11 to work with NSB4 but now upgrading it to NSB7.4.4)

Everything seems OK on CLR part and we are able to call a function from ORACLE into C# that executes a call to our internal INITBUS method that contains the following NSB7 setup but we are getting an exception (See below)

OUR INTERNAL BUS CONFIG

                var endpointConfiguration = new EndpointConfiguration(destinationEndpoint);
                endpointConfiguration.UseSerialization<XmlSerializer>();
                endpointConfiguration.UsePersistence<InMemoryPersistence>();
                var transport = endpointConfiguration.UseTransport<MsmqTransport>();
                //transport.DisablePublishing();

                endpointConfiguration.UniquelyIdentifyRunningInstance()
                    .UsingNames(
                        instanceName: destinationEndpoint,
                        hostName: Environment.MachineName);

                var scanner = endpointConfiguration.AssemblyScanner();
                scanner.ThrowExceptions = true;
                scanner.ScanAppDomainAssemblies = false;
                scanner.ScanAssembliesInNestedDirectories = true;
                
                // configure commands
                var conventions = endpointConfiguration.Conventions();
                conventions.DefiningCommandsAs(ConfigureCommandTypes);
                endpointConfiguration.PurgeOnStartup(false);

                endpointConfiguration.SendOnly();
                var _bus = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();

Actual Exception:

ERROR
ORA-20100: System.Exception

No stage connector found for stage NServiceBus.Pipeline.IOutgoingPublishContext
   at NServiceBus.PipelineModelBuilder.Build()
   at NServiceBus.Pipeline`1..ctor(IBuilder builder, PipelineModifications pipelineModifications)
   at NServiceBus.SendComponent.CreateMessageOperations(IBuilder builder, PipelineComponent pipelineComponent)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.HostingComponent.<Start>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CLBC.Individual.CommandFacade.CommandFacade.InitializeBus()
   at CLBC.Individual.CommandFacade.CommandFacade.TestBus()
ORA-06512: at "SYS.DBMS_CLR", line 243
ORA-06512: at "SYS.TESTBUS", line 6

Any Insight would be greatly appreciate!!!

**Comment by mauroservienti** [comment]
@yurimaksymenko thanks for raising this.

One thing that is worth trying is to use the [`AdditionalAssemblyScanningPath`](https://docs.particular.net/nservicebus/hosting/assembly-scanning#additional-assembly-scanning-path) option available starting NServiceBUs 7.4.
I have a hunch that what's happening is that the NServiceBus assemblies are not picked up by the scanner due to having `ScanAppDomainAssemblies` set to false. There might be also the issue that the CLR hosting in Oracle makes so that the default AppDomain Location/Path is not the one from which your (and thus NServiceBus) assemblies are loaded.

**Comment by yurimaksymenko** [comment]
@mauroservienti Thank you Mauro,
I think we have tried numerous variations of AssemblyScanning, ON, OFF, Throw Exception etc.
By playing with various combinations and attaching a debugger to ORACLE CLR Host 
we have learned that ScanAssembliesInNestedDirectories flag did not seem to work.
ScanAppDomainAssemblies flag did not seem to work.

Additional investigation revealed that ORACLE CLR host created a $TEMP$ folder inside of CLR host directory
and for some reason this is the PATH that NServiceBus was using as a Application BASEPATH.
This was became apparent after we introduced manual filter to see what is being scanned.

var scanner = endpointConfiguration.AssemblyScanner();
                scanner.ThrowExceptions = true;
                scanner.ScanAppDomainAssemblies = false;
                scanner.ScanAssembliesInNestedDirectories = true;

                // exclude dlls that we do not need to scan
                var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
                foreach (var fileName in Directory.EnumerateFiles(baseDirectory, "*.dll").Select(Path.GetFileName))
                {
                    if (fileName.IndexOf("OurInternalDllPrefix", StringComparison.OrdinalIgnoreCase) == -1)
                    {
                        scanner.ExcludeAssemblies(fileName);
                        break;
                    }
                }

We copied DLLS into a $TEMP$ folder and restarted ORACLE Database service and it started to work.
I got to say that the exception message was not helpful (without the context).

So the issue is resolved and can be closed.
Thank you.

**Comment by mauroservienti** [comment]
Thanks you @yurimaksymenko. Glad that the issue was solved.
