### ISSUE TITLE
support cancellation tokens

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus#5865]
### Plan of action

- [x] Decide whether to change `Func<..., CancellationToken, Task{...}>` params to delegates with an optional token
    - [_it doesn't work_](https://twitter.com/adamralph/status/1346433604218478600)
    - ~how many delegates would be required~
- [x] Consider uniform session - _we just ignore the token in the `IPipelineContext` adapter_
- [x] Obsolete unit of work - _https://github.com/Particular/NServiceBus/pull/5854_
- [x] Revert token additions in [transport seam changes](https://github.com/Particular/NServiceBus/pull/5852) - _https://github.com/Particular/NServiceBus/pull/5858_
- [x] Decide whether to adopt the analyzers approach for `IHandleMessages<T>` and `IHandleTimeouts<T>` - _https://github.com/Particular/NServiceBus/pull/5853_ - _we will not_
- [x] Investigate why `MessageHandler` is public - _@andreasohlund_ - _it's used [here](https://github.com/timbussmann/Community.NServiceBus.LambdaHandlers/blob/a21009880379fd046ccc947b913644993fb740d3/Community.NServiceBus.LambdaHandlers/LambdaHandlersFeature.cs#L18)_
- [x] Update to FastExpressionCompiler 2.0 - _https://github.com/Particular/NServiceBus/pull/5880_
- [x] Ensure internal behaviors implement more performant behavior interfaces - _https://github.com/Particular/NServiceBus/pull/5882_
- [x] introduce `On...` delegates - _https://github.com/Particular/NServiceBus/pull/5889_
- [x] obsolete `AbortReceiveOperation` - _https://github.com/Particular/NServiceBus/pull/5896_
- [x] consider whether the context should have methods to link another token or replace the token - _not for now, can be introduced in a minor if required_
- [x] remove async timer - _https://github.com/Particular/NServiceBus/pull/5912_
- [x] Add token to all relevant APIs - _https://github.com/Particular/NServiceBus/pull/5897_
  - [x] Introduce a token source when stopping the endpoint to use as the message session root token - _#5911_
  - [x] confirm whether we should have an optional token on message session methods but not on receive pipeline methods
- [x] Make all non-private tokens optional - _https://github.com/Particular/NServiceBus/pull/5946_
- [x] Fix tests after https://github.com/Particular/NServiceBus/pull/5936 (plus fixups) is done - _https://github.com/Particular/NServiceBus/pull/5939_
- [x] Consider where else _we_ should check the token and bail out early
  - _https://github.com/Particular/NServiceBus/pull/5964_
- [x] Set the severity level of the new analyzer to suggestion in all test projects - _[oustanding PRs](https://github.com/pulls?page=2&q=is%3Apr+is%3Aopen+author%3Aparticularbot6+user%3AParticular+special)_
- [x] ensure the code that calls feature starts and stops makes sense wrt cancellation and the throwing of `OperationCancelledException` - _https://github.com/Particular/NServiceBus/pull/6050_
- [x] add obsoletes for all the methods we broke which take a `Func<... Task>` - _https://github.com/Particular/NServiceBus/pull/6054_
  - find all the instances of `Func<.... CancellationToken, Task>` in the approval file and ensure there is an obsoleted equivalent without a token
- [x] Remove reflection tests which were replaced with analyzers - _https://github.com/Particular/NServiceBus/pull/6062_
- [x] Add an analyzer and code fixer for forwarding the context token - _https://github.com/Particular/NServiceBus/pull/5923_

**Comment by andreasohlund** [comment]
>add obsoletes for all the methods we broke which take a Func<... Task>

done, ticked the box

**Comment by DavidBoike** [comment]
Done!
