### ISSUE TITLE
" Could not find a started saga for " should include saga type

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5885]
![image](https://user-images.githubusercontent.com/122666/106401468-5af83080-6478-11eb-874d-13769cdf2fd5.png)

**Comment by mikeminutillo** [comment]
In theory there could be more than one saga type that is not found as this happens in the incoming context and not the invoke handlers context.

**Comment by TravisNickels** [comment]
The saga type has been added to the log entry.  There will be an information log entry for each saga and its type that is not found for a message.  If no saga(s) are found at all, there will be another information log entry that states it could not find any sagas for a message.

This is the PR for NServiceBus 8: #6248
This is the PR for NServiceBus 7.7: #6248

**Comment by SimonCropp** [comment]
thanks
