### ISSUE TITLE
Unexpected 'handler could not be found for message type'

### ISSUE THREAD

**Issue by robbaman** [Particular/NServiceBus#5895]
We're running into a situation that I can't explain. We have a message class as follows:

```
namespace JClub.Portal.Api.MessageBus.Events.Clients {
    public class ClientGewijzigdEvent : IRegelGewijzigdEvent<ClientRegelData>, IClientGewijzigdEvent {
    ... properties
    }
}
```

with a handler in a different service like so

```
public class ClientGewijzigdEventHandler : IHandleMessages<IClientGewijzigdEvent> {
   .. implementation
}
```

Now when the event is published it ends up in ServicePulse with the error message:

> System.InvalidOperationException: No handlers could be found for message type: JClubWeb.Messages.Events.TriggerData.IRegelGewijzigdEvent`1[JClubWeb.Messages.MessageData.ClientRegelData]

The reason I can't explain this is because the message headers contain the following value for the `NServiceBus.EnclosedMessageTypes` header:

> JClub.Portal.Api.MessageBus.Events.Clients.ClientGewijzigdEvent, JClub.Portal.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;JClubWeb.Messages.Events.TriggerData.IRegelGewijzigdEvent`1[[JClubWeb.Messages.MessageData.ClientRegelData, JClubWeb.Messages, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null]], JClubWeb.Messages, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null;JClubWeb.Messages.Events.Clients.IClientGewijzigdEvent, JClubWeb.Messages, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null

Note that the `JClubWeb.Messages.Events.Clients.IClientGewijzigdEvent` type is present is that list. In addition, the configuration.txt in the .diagnostics directory contains the following:

```
... stuff
  "Messages": {
    "CustomConventionUsed": false,
    "MessageConventions": [
      "NServiceBus Marker Interfaces"
    ],
    "NumberOfMessagesFoundAtStartup": 225,
    "Messages": [
      "JClubWeb.Messages.Events.Clients.IClientGewijzigdEvent",
      .. more messages
    },
    "MessageHandlers": {
      "JClubWeb.Messages.Events.Clients.IClientGewijzigdEvent": [
        "JClub.DisplayzijdeService.MessageBus.EventHandlers.Clients.ClientGewijzigdEventHandler"
      ],
      ... more message types
... more stuff
```

Clearly the message has the *JClubWeb.Messages.Events.Clients.IClientGewijzigdEvent* type as one of it's enclosed types AND this type was detected by the recipient AND it had a handler registered... what reason could there be for it to think there's no handler? And why does it say it was looking for a handler for JClubWeb.Messages.Events.TriggerData.IRegelGewijzigdEvent`1[JClubWeb.Messages.MessageData.ClientRegelData]?

I'm sure there's a good explanation... but I'm not seeing it. Any help?

**Comment by mikeminutillo** [comment]
@robbaman nothing sticks out as an obvious issue and I was unabe to recreate this behavior locally. Can I get you to [create a support case](https://particular.net/support) and send through the full diagnostic file?

**Comment by mikeminutillo** [comment]
With help from @robbaman we were able to trace the root cause of this issue to an issue with the way the Newtonsoft Serializer handles message proxies when the subscribing endpoint does not have a reference to the concrete message type. Please subscribe to https://github.com/Particular/NServiceBus.Newtonsoft.Json/issues/118 for updates.
