### ISSUE TITLE
Problem registering same behavior multiple times

### ISSUE THREAD

**Issue by markphillips100** [Particular/NServiceBus#5952]
I've been trying to use `INeedInitialization` to configure a behavior that supplies a specific EFCore DbContext to handlers.  The same behavior is required by more than one deployable component in my solution so I provide a bootstrapper in each component that registers the behavior with the endpoint configuration's pipeline.  This means the host doesn't need to know it must configure the behavior in order to reference any of these components.

As soon as I include more than one component that executes its behaviour registration via `INeedInitialization` I get problems either with the endpoint not starting or the behavior not executing.

I investigated further using the [TimeSample](https://docs.particular.net/samples/pipeline/handler-timer) with some minor modifications to replicate the issues.

I modified the `HandlerTimeBehavior` to always log the time so I can be sure it's executing at all times, like so:

```
class HandlerTimerBehavior :
    Behavior<IInvokeHandlerContext>
{
    static ILog log = LogManager.GetLogger<HandlerTimerBehavior>();

    public override async Task Invoke(IInvokeHandlerContext context, Func<Task> next)
    {
        var stopwatch = Stopwatch.StartNew();
        try
        {
            await next()
                .ConfigureAwait(false);
        }
        finally
        {
            var elapsedMilliseconds = stopwatch.ElapsedMilliseconds;
            var handlerName = context.MessageHandler.Instance.GetType().Name;
            log.Warn($"{handlerName} took {elapsedMilliseconds}ms to process");
        }
    }
}
```

Next , the `Program.cs` was modified with 4 possible configurations; Example A, B, C & D.  Uncomment each to exhibit the issue described in the associated comment:

```
#region pipeline-config

// Example A: Works with a single registration.
// endpointConfiguration.Pipeline.Register(typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");

// Example B: Throws exception at endpoint startup.
// endpointConfiguration.Pipeline.Register(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");
// endpointConfiguration.Pipeline.Register(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");

// Example C: No exception however behavior fails to execute during message processing pipeline.
// endpointConfiguration.Pipeline.Replace(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");
// endpointConfiguration.Pipeline.Replace(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");

// Example D: Works however unable to determine if an INeedInitialization should call Register or Replace.
// endpointConfiguration.Pipeline.Register(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");
// endpointConfiguration.Pipeline.Replace(typeof(HandlerTimerBehavior).Name, typeof(HandlerTimerBehavior), "Logs a warning if a handler take more than a specified time");

#endregion

```

I noticed future NSB `PipelineSettings.cs` has a `RegisterOrReplace`, is this to fix this issue?

Is their a workaround in the meantime that would support using a bootstrapper approach?  Example D's approach would require a need to determine what has already been registered from within the bootstrapper.

**Comment by DavidBoike** [comment]
Hi @markphillips100,

Pretty sure `RegisterOrReplace` will do the trick. However, another option is to have your behavior in a separate component that is referenced by each deployable component that needs it. Then you have one version of the code which is either deployed once (even if multiple components require it) or not deployed at all, and then Register will work fine.

**Comment by markphillips100** [comment]
Thanks @DavidBoike .  I'll give that a go until the new functionality is available.
