### ISSUE TITLE
StartNewConversation for PublishOptions

### ISSUE THREAD

**Issue by jm-** [Particular/NServiceBus#5966]
Duplicate of https://github.com/Particular/NServiceBus/issues/5088, but for extending PublishOptions rather than SendOptions.

**Comment by danielmarbach** [comment]
@jm- Thanks for reaching out. Can you explain for what business scenario you would require to start a new conversation for the publish operation?

Unfortunately, I wasn't involved in the implementation for NServiceBus 7.4 but I seem to remember the `PublishOptions` extensions were scoped out at that time. I have a hunch it is due to the lack of missing real user scenarios. So your insight would be very valuable for us.

**Comment by jm-** [comment]
We have a scenario in which an object is built up through choreographed messages across several microservices. After this object is successfully built, there is an event that could be published depending upon the state of the object.

We use the ConversationId header on messages that build up the object so that errors that occur can be easily traced back to the message that started it. When the object is successfully built, the new event that is published will have the same ConversationId header. This means that, should it or following messages produce an error, the value of the ConversationId implies that object was not successfully built.

I think an easy solution here is to issue a new ConversationId header for the new event that could be published.

**Comment by danielmarbach** [comment]
So you are using the conversation id to determine whether a workflow that composes an object out of multiple messages is completed? 

Wouldn't this be better suited to be turned into [a saga](https://docs.particular.net/nservicebus/sagas/) or a [routing slip](https://docs.particular.net/samples/routing-slips/)?

**Comment by jm-** [comment]
We essentially have a new workflow that starts on completion of a previous workflow. The conversation id is propagated to the new workflow. There is an external service that monitors errors, and uses the conversation id to determine what workflow encountered the error.

We've changed our approach to this problem and used commands instead of events for messaging. Thanks for the suggestion to use a saga.

Feel free to close this issue.

**Comment by DavidBoike** [comment]
Ok. We'll close this issue for now, but if you discover a better use case in the future (or anyone else, for that matter) or find that the different approach doesn't work, we may reopen it.
