### ISSUE TITLE
DeferredLogger and LicenseManager logging bug

### ISSUE THREAD

**Issue by alexander-kucherov** [Particular/NServiceBus#6005]
Hi!
We use Info loglevel in our project.
As far as I understand, DeferredLogger  mitigates issue, when IHost isn't built and logging infrastructure not initialized.
It's saving all the log messages during this phase.
Unfortunately, there is [code which uses log level ](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Licensing/LicenseManager.cs#L101)
Debug level is true, because we don't have initialized logger.
After that, when DeferredLogger is called, we have a fully initialized logger. In my case it has info log level and all deferred debug messages is bypassed.
And I lost LicenseManager info log message, because it was logged with debug log level instead [expected info level](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Licensing/LicenseManager.cs#L115)

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus/pull/6002

Thanks for reporting this issue. It will be released in the upcoming v8.
