### ISSUE TITLE
MaximumMessageThroughputPerSecond

### ISSUE THREAD

**Issue by ZacharyHiggins-dbMotion** [Particular/NServiceBus#6007]
When setting TansportConfig concurrency, a possible config value for MaximumMessageThroughputPerSecond is 0. Does this remove throttling entirely, and if set to 0... should it even be set at all? Some information online suggests not setting it at all (https://stackoverflow.com/questions/36758144/how-to-tell-nservicebus-is-using-maximumconcurrencylevel). We're not sure what the specific behavior is when set to 0.

**Comment by ramonsmits** [comment]
@ZacharyHiggins-dbMotion The setting `MaximumMessageThroughputPerSecond` is obsolete and was part of NServiceBus 5 and earlier

NServiceBus 5: https://docs.particular.net/nservicebus/operations/tuning?version=core_5

You can just remove the attribute and no throughput limiting will be applied.

```xml
<TransportConfig MaximumConcurrencyLevel="5" />
```

Second, if you are still on NServiceBus 5 then I can highly recommend upgrading to 6 or 7. NServiceBus 5 is no longer supported but additionally, significant performance improvements have been made. 

Please reach out to us if you require any assistance in upgrading if this is considered.

Any support-related follow-up or questions are better done via one of our [support channels](https://particular.net/support).
