### ISSUE TITLE
Started FeatureStartupTasks are not stopped on endpoint start failure

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#6015]
As part of `Endpoint.Start`, all defined `FeatureStartupTask`s defined by Features are started sequentially. If a subsequent startup task fails (or some other startup failure happens after all startup tasks have been started), the `Endpoint.Start` method throws an exception to the caller but does not call `Stop` on the startup tasks.

This can lead to problems when a `FeatureStartupTask` starts a background job that will continue to run even though the endpoint hasn't been successfully started at all. There is no information for the started background job that it needs to stop. The background job isn't cleaned up at all until the host process terminates. In multi-hosting scenarios or other hosting environments where the host process lifetime doesn't closely align with the endpoint lifetime, this might cause memory leaks or other types of unexpected behavior. 

As an example, NServiceBus.Heartbeats contains such a background job that will report an endpoint as being healthy even though the endpoint failed to fully start. See this user reported issue: https://github.com/Particular/NServiceBus.Heartbeat/issues/121

The following acceptance test reproduces the behavior:

    public class When_feature_startup_task_fails : NServiceBusAcceptanceTest
    {
        [Test]
        public void Should_stop_started_FeatureStartupTasks()
        {
            Context context = null;
            Assert.ThrowsAsync<SimulatedException>(() =>
                Scenario.Define<Context>(ctx => context = ctx)
                    .WithEndpoint<EndpointWithStartupTask>()
                    .Run());

            // Verify expected FeatureStartupTask startup order
            Assert.AreEqual(nameof(EndpointWithStartupTask.FeatureWithWorkingStartupTask.WorkingStartupTask), context.FeatureStartupOrder.First());
            Assert.AreEqual(nameof(EndpointWithStartupTask.FeatureWithFailingStartupTask.FailingStartupTask), context.FeatureStartupOrder.Last());

            Assert.IsTrue(context.StopCalled);
        }

        public class Context : ScenarioContext
        {
            public List<string> FeatureStartupOrder { get; set; } = new List<string>();
            public bool StopCalled { get; set; }
        }

        class EndpointWithStartupTask : EndpointConfigurationBuilder
        {
            public EndpointWithStartupTask()
            {
                EndpointSetup<DefaultServer>(c =>
                {
                    c.EnableFeature<FeatureWithWorkingStartupTask>();
                    c.EnableFeature<FeatureWithFailingStartupTask>();
                });
            }

            public class FeatureWithFailingStartupTask : Feature
            {
                public FeatureWithFailingStartupTask()
                {
                    DependsOn<FeatureWithWorkingStartupTask>();
                }

                protected override void Setup(FeatureConfigurationContext context)
                {
                    context.RegisterStartupTask(b => new FailingStartupTask(b.Build<Context>()));
                }

                public class FailingStartupTask : FeatureStartupTask
                {
                    Context testContext;

                    public FailingStartupTask(Context testContext)
                    {
                        this.testContext = testContext;
                    }

                    protected override Task OnStart(IMessageSession session)
                    {
                        testContext.FeatureStartupOrder.Add(nameof(FailingStartupTask));
                        throw new SimulatedException();
                    }

                    protected override Task OnStop(IMessageSession session)
                    {
                        return Task.FromResult(0);
                    }
                }
            }

            public class FeatureWithWorkingStartupTask : Feature
            {
                protected override void Setup(FeatureConfigurationContext context)
                {
                    context.RegisterStartupTask(b => new WorkingStartupTask(b.Build<Context>()));
                }

                public class WorkingStartupTask : FeatureStartupTask
                {
                    Context testContext;

                    public WorkingStartupTask(Context testContext)
                    {
                        this.testContext = testContext;
                    }

                    protected override Task OnStart(IMessageSession session)
                    {
                        testContext.FeatureStartupOrder.Add(nameof(WorkingStartupTask));
                        return Task.FromResult(0);
                    }

                    protected override Task OnStop(IMessageSession session)
                    {
                        testContext.StopCalled = true;
                        return Task.FromResult(0);
                    }
                }
            }

        }
    }

**Comment by sanilpaul** [comment]
@timbussmann We do need a workaround to stop these features especially heartbeats. 
Other than maintainability and going against the general guidelines, do you see any issues if we invoke FeatureActivator.StopFeatures() as a workaround until there is a fix available. Can you check out this gist and let me know. 
https://gist.github.com/sanilpaul/23fa945c95c0077025e445689b248fe3

**Comment by timbussmann** [comment]
@sanilpaul Unfortunately, I'm not aware of a reliable workaround at the moment. I assume your need is connected to your [issue regarding multi-hosting](https://github.com/Particular/NServiceBus.Heartbeat/issues/121) and I'd recommend either not use multi-hosting or to use our [updated sample approach](https://docs.particular.net/samples/hosting/generic-multi-hosting/) to not allow the process to run with an endpoint that failed to start (maybe you can explain why you'd want to continue with only 1 out of 2 endpoints?) in the meantime.

I can't promise anything about your suggested workaround, the primary risk comes from calling `Stop` on FeatureStartupTasks that haven't been started in the first place, so this definitely has a chance of throwing exceptions or causing other unexpected behavior from other features. Given that `StopFeatures` stops features concurrently, there is a good chance that it will indeed stop affected features, but I can't make any statements about potential side-effects.

**Comment by sanilpaul** [comment]
@timbussmann Thanks for the feedback. Yeah, I was asking more from the context of heartbeats. And also, based on the code it was swallowing exception on stop. But I understand your perspective on code that's not supported. 
https://github.com/Particular/NServiceBus/blob/5d786b10c49fe1b6411371f84e474503d364840d/src/NServiceBus.Core/Features/FeatureStartupTaskController.cs#L29

There are couple of reasons. First, if the generic host bring all the endpoints down, we wouldn't know which endpoint actually caused the issue easily(without going through logs) compared to figuring it out from the heartbeats. Second one is more to our context. Our generic host has resiliency built in. so that it retries until it hits the circuit breaker for each endpoint. In the .net framework world, we could unload app domain which is not possible in .net core. So its important to stop the features that have started up especially heartbeats (May be heartbeats does not belong in a feature startup tasks or have some way to defer heartbeats until endpoint has indeed started up)

**Comment by timbussmann** [comment]
> First, if the generic host bring all the endpoints down, we wouldn't know which endpoint actually caused the issue easily(without going through logs) compared to figuring it out from the heartbeats.

You should be able to identify the failing endpoint by inspecting each endpoint's start `Task` status, e.g. by using something like this:

```
var endpointOneTask = endpointOneBuilder.StartAsync();
var endpointTwoTask = endpointTwoBuilder.StartAsync();
try {
    await Task.WhenAll(endpointOneTask, endpointTwoTask);
} catch {
    // check which one of the tasks is in Faulted state.
}
```

This let's you identify the failed task on code level without having to go through logs.

> Our generic host has resiliency built in. so that it retries until it hits the circuit breaker for each endpoint.

Can you move that retry mechanism to the outer code that starts the two individual generic hosts? That would be more aligned with what you'd get when you host the app as a Windows Service and configure auto-restart settings on a Windows Service.

Can you share more details about what your failing `FeatureStartupTask` is doing and why it's failing?

**Comment by SzymonPobiega** [comment]
This seems to have been fixed in https://github.com/Particular/NServiceBus/commit/b25fda5df7ab%60796941c6264a351ee9b81f67fb33 while working on the cancellation token support. It has been fixed since V8.
