### ISSUE TITLE
Consider a "FeatureBackgroundTask" feature

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#6089]
There are plenty of downstreams (outbox cleaners, native transport timeout pollers, metrics buffer cleaners, metrics senders etc etc) that needs to run as a "background task". That logic is now duplicated all over the place and is likely similar enough to warrant the core to provide such a service.

Examples:

- https://github.com/Particular/NServiceBus.NHibernate/blob/master/src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
-https://github.com/Particular/NServiceBus.Metrics.ServiceControl/blob/master/src/NServiceBus.Metrics.ServiceControl/ReportingFeature.cs#L183
- https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/DelayedDelivery/DueDelayedMessageProcessor.cs#L28

**Comment by SeanFeldman** [comment]
@andreasohlund https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/master/src/Transport/DelayDelivery/DelayedMessagesPoller.cs#L37

**Comment by WojcikMike** [comment]
Will track this elsewhere.
