### ISSUE TITLE
Add saga dynamically

### ISSUE THREAD

**Issue by lillo42** [Particular/NServiceBus#6113]
Hi, 

I'm trying/develop an integration with [Automatonymous](https://github.com/MassTransit/Automatonymous), so for that I'm thinking about generate the saga dynamically during runtime also I'm going to try Source Code Generator.

Is there anyway where I can add  saga dynamically? Like:

```c#

endpointConfiguration.AddSaga<Generated>();
// or 
endpointConfiguration.AddSaga(typeof(Generated));

//or
public class AutomatonymousFeature : Feature
{
    protected override void Setup(FeatureConfigurationContext context) => context.Container.AddSaga(typeof(Generated));
}

```

**Comment by DavidBoike** [comment]
Hi @lillo42,

Sagas are detected by scanning assembly types at runtime. The saga code would need to be a compiled part of an assembly to be detected.

**Comment by lillo42** [comment]
@danielmarbach thank you, 

I'll close the issue for now, the source code generation is doing well
