### ISSUE TITLE
Default options from operations in outgoing behaviors might not be applied

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#6223]
### Symptoms

Sending messages (using `context.Send`) in a custom behavior that is part of the outgoing pipeline (e.g. `IOutgoingLogicalMessageContext`, `IOutgoingPhysicalMessageContext`, etc.) might lead to the message sent from the behavior to be routed to an incorrect endpoint. Typically, the incorrectly routed message then ends up in the error queue with a message like this: `System.InvalidOperationException: No handlers could be found for message type: ...`.

### Who's affected

You are affected if all of the following conditions apply:
* Using a custom behavior in an [outgoing pipeline state](https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors#stages-outgoing-pipeline-stages) to send messages via `context.Send`.
* For the send operation in the behavior, default routing is applied (no routing overrides are configured via the `SendOptions` as [documented here](https://docs.particular.net/nservicebus/messaging/send-a-message#overriding-the-default-routing)).
* For the send operation that triggers the outgoing pipeline behavior (typically a `messageHandlerContext.Send` in a message handler or saga handler), the default routing is overridden using routing extension methods on `SendOptions`  as [documented here](https://docs.particular.net/nservicebus/messaging/send-a-message#overriding-the-default-routing).

Affected (currently supported) versions: NServiceBus 6.5, 7.4 - 7.6

### Root cause

Routing overrides are stored in the pipeline context, which also contains the settings configured in the `SendOptions`. If no override is configured, the default routing applies. 
When using routing overrides in a message handler/saga, the following outgoing pipeline stages contain the override information from the handler/saga in the context. A send operation from within the outgoing pipeline will also contain this routing override information (as context state similar to a stack) if it doesn't use its own routing override. This will lead to routing to find the override information rather than the intended default routing behavior, routing the message incorrectly.

**Comment by JackSinclairT** [comment]
Any news on this? This is causing tens of thousands of exceptions for us per day

**Comment by timbussmann** [comment]
@JackSinclairT I'm sorry to hear that this causes so many errors. This bug is very high up in the priority list but I can't give you any precise timeline right now. We hope to be able to address this issue very soon.

**Comment by timbussmann** [comment]
@JackSinclairT FYI we just started working on this issue and we expect to have a fix available soon. We'll keep you up to date with the progress on this issue. Please make sure that you're on one of the [currently supported versions of NServiceBus](https://docs.particular.net/nservicebus/upgrades/supported-versions) to ensure that you can quickly update to the patch release.

**Comment by JackSinclairT** [comment]
@timbussmann thanks for the update! Any update on when this might go out?

**Comment by timbussmann** [comment]
@JackSinclairT we identified a bunch of other options that are affected by the same issue and we have been working on verifying the potentially affected options, so there has been a bunch of unexpected work that extends the scope of this bug. We're currently evaluating different fixes so we can ship them as soon as possible to all supported versions of NServiceBus version 7.

**Comment by cquirosj** [comment]
Will be shipped with releases: 7.7.1, 7.6.1, and 7.5.1

**Comment by timbussmann** [comment]
@JackSinclairT 7.7.1, 7.6.1, and 7.5.1 are available on our myget feed (https://www.myget.org/F/particular/api/v3/index.json) if you want to give it a try. I can't tell you at what point this will be available/published on the nuget feed itself as we're currently investigating another potentially related issue (but 7.7.1 should address the routing issue you've described).

**Comment by timbussmann** [comment]
hey @JackSinclairT, patch releases have been released to NuGet for versions 7.7.2, 7.6.2 and 7.5.2 that include the fix for the issue (see [the release announcement](https://discuss.particular.net/t/nservicebus-7-7-2-7-6-2-and-7-5-2-patch-releases-available/3005). Thanks for your patience!
