### ISSUE TITLE
GetInstallationUsername in HostingComponent returns DOMAIN_NAME\SYSTEM when endpoint runs under Local System

### ISSUE THREAD

**Issue by FMartens-ATS** [Particular/NServiceBus#6228]
I noticed that the code at https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Hosting/HostingComponent.cs returns 'DOMAIN_NAME\SYSTEM' when the NServiceBus endpoint runs under the Local System account. The code at  https://github.com/Particular/NServiceBus.Transport.Msmq/blob/0bcb1c15632bdab00a33b8843cf18152776aaae1/src/NServiceBus.Transport.Msmq/MsmqQueueCreator.cs#L52 will fail with error 1332 when creating the message queues.

**Comment by kentdr** [comment]
Hi, @FMartens-ATS thanks for posting.  I was able to reproduce the issue, but I suggest you run the service as a different account, such as LocalService. I was able to test running as LocalService and the problem went away.  GIven LocalSystem's "superuser" level permissions, it is ill-advised to run services with that account.
