### ISSUE TITLE
Databus properties are not supported for fields lists and subproperties

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#626]
Detect this on scanning and throw a good exception

## Workaround

The current workaround is to skip the databus and design the message contract to only pass links to the big properties. Essentially mimicking what the databus is doing

**Comment by johnsimons** [comment]
Since this is not a critical issue and there are workarounds, I'm closing it.
If you feel strong about it please reopen it.

**Comment by SathishN** [comment]
Is this issue still fixed or prioritized?

**Comment by chupac** [comment]
I have this same issue as well. Sending a command with a collection of emails with a collection of attachments. Seems odd that this is not supported. Also, it doesn't look like the documentation is updated as it does not mention anything about nested properties?

**Comment by DannyvanderKraan** [comment]
Same here and I could use your advice. Is this bug been scheduled yet, or is it better to implement a workaround?

**Comment by jkodroff** [comment]
@DannyvanderKraan Not to speak for the NSB team, but if I ran into this issue a couple of years ago and it still hasn't been fixed, I would just go with the workaround.

**Comment by DannyvanderKraan** [comment]
@jkodroff Work has commenced on the workaround, don't worry. ;) But this issue is tagged for scheduling nov 28 2014. Well that is not even that long ago if you look at some of the other issues. And I personally think it would be a great addition.

**Comment by peef** [comment]
The DataBus property restriction to be top level property is still not documented 👎

**Comment by DavidBoike** [comment]
Hi @peef, clearly the ball got dropped on this one.

I just amended the documentation here:

https://docs.particular.net/nservicebus/messaging/databus/#specifying-data-bus-properties
