### ISSUE TITLE
Cannot send a command inside a saga with two handlers

### ISSUE THREAD

**Issue by adri-dev** [Particular/NServiceBus#6330]
We have implemented a saga with two handlers, first works and seconds fails. Actually works when sending two times same command.

This is our saga:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/52034596/161061141-c775e0c7-a667-452c-acd4-2f94923bc12f.png)

This is handler:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/52034596/161060818-5cc7e7f2-e9be-406f-a650-57c2ddcf95a0.png)

And this is the error we reaceive:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/52034596/161060889-f2917eb3-f8e7-4adf-8c98-0ace3e87fe08.png)

Thanks in advance.

**Comment by SzymonPobiega** [comment]
Hi

Could you raise a support case for this issue? It would then be possible to have a private conversation about your problem.

Thanks,
Szymon

**Comment by timbussmann** [comment]
I'm closing this issue as this is handled as a support case.
