### ISSUE TITLE
Add an exception type that is treated by core as unrecoverable when thrown

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#6421]
Add an exception that can be thrown, which is by default treated as an unrecoverable exception.

// cc @SimonCropp

**Comment by mikeminutillo** [comment]
This would be useful for Azure Service Bus which throws an exception when trying to send more than 100 messages in a transaction https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/842

**Comment by SimonCropp** [comment]
isnt this trivial to implement? and adds non-trivial value. so why hold off on it?

**Comment by ramonsmits** [comment]
@SimonCropp unsure, it seems it was spiked in https://github.com/Particular/NServiceBus/pull/6611 but not added. @lailabougria @timbussmann can you elaborate on the "further analysis" for why this this was not completed?

**Comment by mikeminutillo** [comment]
For the work we are doing to fix the bug, this would be an optimization. The previous behavior would also retry so we aren't making it worse. We don't want to delay releasing a critical patch on a transport for a couple of minor releases of core. We may revisit this once the patches are out but I wanted to make sure the observation was recorded in case we don't get to it in the near future.

**Comment by timbussmann** [comment]
To be clear, this already exists with the `AddUnrecoverableException` configuration API except that we don't provide a default exception configured: https://docs.particular.net/nservicebus/recoverability/#unrecoverable-exceptions. So the feature request here would be to explicitly provide an NSB-provided type that is registered by default.

If I remember the conversations with @lailabougria correctly, I think the main argument against this was that an NSB provided exception will always require `try/catch` blocks in your business logic to map a business exception to an NSB exception. While this works, it is a very limited approach that requires a lot of infrastructure/recoverability logic in your handlers and essentially abuses custom exceptions to program the control flow. So the alternatives would be:
* Define your own exception and register it using `AddUnrecoverableException` which is a few lines of code.
  * The scenario @mikeminutillo mentioned, I don't see why `AddUnrecoverableException`  couldn't be used by the ASB package internally for a custom exception.
* Write a custom behavior in the recoverability pipeline that contains the logic to inspect exception types and that can then decide inside the recoverability pipeline what the best step would be. This is a lot more powerful and flexible compared to throwing a specific exception from your business logic. Besides just moving to the error queue, this also allows scenarios like inspecting throttling exceptions and selecting the proper delayed-retry values.
* Use `MessageDeserializationException ` which is already showing this behavior. But I think this supports my statement that built-in exception types lack context.

**Comment by SimonCropp** [comment]
> I think the main argument against this was that an NSB provided exception will always require try/catch blocks in your business logic to map a business exception to an NSB exception. 

as the person who originally proposed this, this was never my use case. specifically i wanted it for NBS extensions. for example in nsb attachments. if there is no attachment for a given name+message , there is no point retrying.

throwing MessageDeserializationException  in the above case would be very strange

**Comment by timbussmann** [comment]
> as the person who originally proposed this, this was never my use case. specifically i wanted it for NBS extensions. for example in nsb attachments. if there is no attachment for a given name+message , there is no point retrying.

Is there something specific stopping you from using `AddUnrecoverableException` in your extension with a custom, more meaningful Exception type (e.g. `AttachmentNotFoundException` instead of a generic `UnrecoverableException`)? It sounds to me that it would be more helpful to expose `AddUnrecoverableException` to feature setups (the API is currently only accessible in the `Feature.Defaults` API) instead?

**Comment by mikeminutillo** [comment]
I believe the idea is that NSB would provide a base exception (or maybe markker n interface if that's possible) that represents unrecoverable scenarios and then provide their own use-case specific exceptions. So something like:

```csharp
class AttachmentMissingException : NServiceBus.UnrecoverableException { ... }
```

**Comment by mikeminutillo** [comment]
Perhaps we could add something to the transport infrastructure.

**Comment by timbussmann** [comment]
> I believe the idea is that NSB would provide a base exception (or maybe marker interface if that's possible) that represents unrecoverable scenarios and then provide their own use-case specific exceptions. So something like:

yes and as Ramon pointed out, here's a [complete PR](https://github.com/Particular/NServiceBus/pull/6611/files) for exactly that feature. I still feel the existing APIs are covering this well enough?

> Perhaps we could add something to the transport infrastructure.

I think that would not be a good idea. The recoverability logic is in core's recoverability pipeline and that would add a weird mix of recoverability logic in different places.

**Comment by ramonsmits** [comment]
@timbussmann The transports as any other downstream knows in its specific context what kind of exceptions are unrecoverable.

We need a mechanism so that recoverability will immediately dead-letter certain messages. This is not meant for user code [as you stated yourself](https://github.com/Particular/NServiceBus/issues/6421#issuecomment-1614856291):

>  It sounds to me that it would be more helpful to expose AddUnrecoverableException to feature setups

On top of that, I think it might also be very useful to just have such a base exception for the convenience of any NServiceBus code that knows that a certain error is unrecoverable. I personally don't think any code should throw that exception type but inherit it and throw a specific state exception but then at least you don't need to register that additional unrecoverable exception type.

**Comment by SimonCropp** [comment]
again trivial to implement. non-trivial value. so why hold off on it?

All i want is `throw new UnrecoverableException("my message")`. there is no need to a custom exception, no need to manipulate config at startup

can we please have this feature

**Comment by kentdr** [comment]
Based on the [above analysis](https://github.com/Particular/NServiceBus/issues/6421#issuecomment-1614277690) we are marking this issue as not planned.
