### ISSUE TITLE
AppDomain.CurrentDomain.BaseDirectory Not always populate in Dot Net Core

### ISSUE THREAD

**Issue by DavuKnight** [Particular/NServiceBus#6521]
NServiceBus seems to rely fairly heavily on AppDomain.CurrentDomain.BaseDirectory.
Looks like this might make it unusable in certain scenerios.
Since AppDomain.CurrentDomain.BaseDirectory doesnt always get set in every scenerio.

See: https://github.com/dotnet/runtime/issues/74720

**Comment by DavuKnight** [comment]
Looks like there is a work around as stated in https://github.com/dotnet/runtime/issues/74720 But I would submit that using it is a convention that should be avoided.

**Comment by SzymonPobiega** [comment]
Did you run into that problem? Could you describe scenarios in which that would be an issue?

**Comment by DavuKnight** [comment]
See: https://github.com/dotnet/runtime/issues/74720

If you SelfHost the CLR inside another application the AppDomain settings are whatever you want them to be. Including blank. 
NServiceBus's assumption that the only viable place an App will run is a place with an accessible file system would seem to be a growing fallacy and liability. It is increasingly likely that Applications will run in memory without any state or filesystem to work with. In my case it precluded using NServiceBus and I swapped it out for writing directly to Kafka instead.

**Comment by SzymonPobiega** [comment]
That's interesting given NServiceBus does not have support for Kafka. But anyway, we'll record this and keep observing if we get more signals about this particular aspect of the framework.
