### ISSUE TITLE
[.NET 7] Use new Activity and ActivityContext APIs

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#6587]
https://github.com/Particular/NServiceBus/pull/6585 had to use some code that can be simplified with the new APIs available in .NET 7:

* https://github.com/dotnet/runtime/issues/42575 brings a `ActivityContext.TryParse` overload that offers an `isRemote` parameter that can be used to replace the workaround here: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs#L32
* [Activity.HasRemoteParent](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.hasremoteparent?view=net-7.0#system-diagnostics-activity-hasremoteparent) can be used in related unit tests to verify that the remote flag is correctly set and ensure this behavior is properly tested.

**Comment by SzymonPobiega** [comment]
Addressed in #7049
