### ISSUE TITLE
Consistency via local database, independent of message transport

### ISSUE THREAD

**Issue by Timovzl** [Particular/NServiceBus#6610]
Udi Dahan deals with the problem of consistency between database writes and messages in [this video](https://www.youtube.com/watch?v=AfAojdORxHs). I wholeheartedly agree with the analysis and the proposed solution.

According to the video, the proposed solution will have been available as of NServiceBus 5. However, as far as I can tell from the documentation, the actual implementation offers a more limited interpretation of the solution.

Say that we have the following (dare I say realistic) constraints:

- We have no Distributed Transaction Coordinator (DTC).
- Our message transport cannot support [sends-atomic-with-receive](https://docs.particular.net/transports/transactions#transactions-transaction-levels-supported-by-nservicebus-transports). (For example, we are not on Azure; or we limited to RabbitMQ.)

I see the following options - correct me if I'm wrong:

- Use RabbitMQ as the transport. Now we are lacking the bulletproof solution presented in the video.
- Use our bounded context's own SQL database as the transport. Now we have to deal with its performance constraints. More importantly, we can no longer receive messages from other bounded contexts, since we certainly do not expose our database outside of the bounded context.

In actuality, the solution proposed in the video is far more flexible. It only requires the following:

1. The local database is used as "inbox" and "outbox", i.e. for duplication of incoming messages and for deferring the sending of outgoing messages (until the database transaction is committed).
2. _Something_ enables retries of sending the outgoing messages. If the flow was initiated from a message, this is automatic (since we failed to mark it as handled), but otherwise, some background process should pick up any strays. This point is important, but less relevant to the discussion.

(As a side note, point 1 allows for easy upfront generation of message IDs, which is essential if we want to allow consumers of our messages to be able to deduplicate those.)

Note how no constraints are put on the message transport at all! That is great news.

I believe we should have the ability to use any storage (e.g. SQL) to get the effects of points 1 & 2, transactional with our other writes, irrespective of the message transport being used. This gives us all of the consistency guarantees, on any transport.

Have I overlooked the ability to set things up this way? If not, I believe this to be a very useful feature.

**Comment by timbussmann** [comment]
Hi @Timovzl,

What Udi explains in the linked video is implemented in NServiceBus with the [Outbox](https://docs.particular.net/nservicebus/outbox/), which handles both the deduplication part as well as the dispatching. The Outbox feature can be very easily enabled with our supported persisters which you can find more about here: https://docs.particular.net/persistence/.

Does that help?

**Comment by Timovzl** [comment]
@timbussmann Perfect, that is exactly what I was looking for!

To be sure I understand correctly, can you verify the following?

- When running in a handler:  Obtain the `SynchronizedStorageSession` from the `IMessageHandlerContext`. Send messages via the `IMessageHandlerContext`. It will commit for us.
- Outside of a handler: Obtain `ITransactionalSession` from the container. Get the `SynchronizedStorageSession` from it. Send messages via it. Manually call `Open()` and `Commit()` on it.

Finally, in the handler scenario, is it also possible to commit manually?

**Comment by timbussmann** [comment]
yes, your understanding is correct. We also have samples available to play around with, e.g.
* Some outbox samples: https://docs.particular.net/samples/outbox/
* Transactional session with CosmosDB: https://docs.particular.net/samples/transactional-session/cosmosdb/
* Transactional session with SQL Persistence and EF: https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/

you can easily tweak/adjust the samples to your needs if you want to play around with those.

Make sure to check your selected persister's API when using the `SynchronizedStorageSession ` as they should have special extension methods to get access to a database-specific session type.

> Finally, in the handler scenario, is it also possible to commit manually?

No, committing manually is not possible as NServiceBus needs to make sure that it can persist the message operations in the same transaction as your database operations. This is automatically handled by the NServiceBus pipeline.

**Comment by timbussmann** [comment]
I'll close this issue for now. If you have any further questions, I can also recommend our [community forum](https://discuss.particular.net/) which is a great place to discuss ideas or ask questions.
