### ISSUE TITLE
XmlSerializer's SanitizeInput and DontWrapRawXml settings use same configuration key

### ISSUE THREAD

**Issue by bruusi** [Particular/NServiceBus#6614]
This issue has been edited by Particular Software to provide additional context about the issue

### Symptoms

Enabling one of the `SanitizeInput` or `DontWrapRawXml` settings will automatically enable both of these settings at once. See the [raw XML properties documentation](https://docs.particular.net/nservicebus/serialization/xml#raw-xml) for further details about the behavior of the `DontWrapRawXml` configuration on message serialization.

### Who's affected

You are affected if you are using the XML serializer and configure it with either the `SanitizeInput()` or `DontWrapRawXml()` setting. Note that the XML serializer is the default option if no other serializer is specified.

### Root cause

The internal configuration used to track the state of the affected settings was incorrectly using the same configuration keys. Therefore, any configuration made to one of the related settings also impacted the other setting.

### Backported to

* [7.8.2](https://github.com/Particular/NServiceBus/pull/6623)
* [7.7.6](https://github.com/Particular/NServiceBus/pull/6624)

### Original issue content

        internal const string SkipWrappingRawXml = "XmlSerializer.SkipWrappingRawXml";
        internal const string SanitizeInput = "XmlSerializer.SkipWrappingRawXml";

**Comment by timbussmann** [comment]
huh, good catch, that seems to be a mistake that completely slipped by.

Are you currently affected by this bug @bruusi ?

**Comment by timbussmann** [comment]
Thanks for raising the issue @bruusi , we're going to release patch versions for 8.0, 7.7 and 7.8 shortly.
