### ISSUE TITLE
Saga analyzer rule NSB0006 gives false positive when mapping is done with base interface

### ISSUE THREAD

**Issue by oskar** [Particular/NServiceBus#6714]
#### Description

Consider the following saga and message definitions:

```csharp
public class ReproSaga : Saga<SagaData>,
    IAmStartedByMessages<IFirstMessage>,
    IHandleMessages<ISecondMessage>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<SagaData> mapper)
    {
        mapper.MapSaga(saga => saga.Correlation)
            .ToMessage<IMessageBase>(msg => msg.Correlation);
    }

    public Task Handle(IFirstMessage message, IMessageHandlerContext context) => Task.CompletedTask;

    public Task Handle(ISecondMessage message, IMessageHandlerContext context) => Task.CompletedTask;
}

public class SagaData : ContainSagaData
{
    public string Correlation { get; set; }
}

public interface IMessageBase
{
    string Correlation { get; set; }
}

public interface IFirstMessage : IMessageBase { }

public interface ISecondMessage : IMessageBase { }

```

#### Expected behavior

Since all handled message types are mapped through the base interface, this should be a perfectly fine saga definition. With NSB 7, sagas like this was not a problem (we have them running in production).

#### Actual behavior

When upgrading to NSB 8, the analyzer starts to throw error NSB0006 (which I believe is a false positive):

```
ReproSaga.cs(7, 5): [NSB0006] Saga ReproSaga implements IAmStartedByMessages<IFirstMessage> but does not provide a mapping for that message type. In the ConfigureHowToFindSaga method, after calling mapper.MapSaga(saga => saga.CorrelationPropertyName), add .ToMessage<IFirstMessage>(msg => msg.PropertyName) to map a message property to the saga correlation ID, or .ToMessageHeader<IFirstMessage>("HeaderName") to map a header value that will contain the correlation ID.
```

#### Versions

NServiceBus 8.0.3

### Steps to reproduce

1. Reference NServiceBus 8
2. Take the code block above and build
3. Analyzer generates error

#### Workarounds

Using explicit mapping of all message types seems to satisfy the analyzer.

#### Additional information

Since the analyzer rule is an error and not a warning, we cannot suppress it with for example `<NoWarn>`.

**Comment by DavidBoike** [comment]
Hi @oskar, yep this is probably a bug in the analyzer from an unconsidered edge case.

However you should be able to disable or downgrade the analyzer in one of the following ways:

Using a pragma in the source:

```csharp
#pragma warning disable NSB0006
// Saga code
#pragma warning restore NSB0006
```

Or using an `.editorconfig` file:

```ini
[*.cs]
dotnet_diagnostic.NSB0006.severity = suggestion
```

or

```
dotnet_diagnostic.NSB0006.severity = none
```

Can you confirm that one of these will work for you for the time being?

**Comment by oskar** [comment]
You're absolutely right. I was convinced that only warnings could be suppressed, not errors - but apparently not. Both `#pragma warning disable` in code and `<NoWarn>` in csproj works fine. I didn't try modifying the `.editorconfig` file but that probably also works.

Thanks for the workaround 🙏

**Comment by DavidBoike** [comment]
@oskar Fixed this in https://github.com/Particular/NServiceBus/pull/6733 and it will be released with NServiceBus 8.1.0.

As it was judged not to be a critical bug, especially given the workaround documented here, it won't be backported to previous releases.

**Comment by oskar** [comment]
Great news! I agree it's not critical.

**Comment by DavidBoike** [comment]
Closing this as we are now actively working on releasing 8.1.0 soon.
