### ISSUE TITLE
Unexpected queues added after upgrading to NServiceBus 8

### ISSUE THREAD

**Issue by saasen** [Particular/NServiceBus#6736]
#### Description

After upgrading a `SendOnly` endpoint to NServiceBus 8, audit-queues started to be created. We are doing a call to `AuditProcessedMessagesTo`, which might be why, but should that be ignored in `SendOnly` endpoints?

#### Expected behavior

That the audit-queues are not created (?).

#### Actual behavior

Audit-queues are created. Not sure if this has any effect other than to create un-needed queues.

#### Versions

- `NServiceBus v8.0.3`

### Steps to reproduce

- Create a `SendOnly` endpoint with version 7 of NServiceBus with Azure Service Bus transport with a call to `AuditProcessedMessagesTo`
- Run the endpoint - no queues are created
- Upgrade to NServiceBus 8 (and related packages)
- Run the endpoint again

An `.audit` queue is now created, but not in use since this is a send-only endpoint.

**Comment by DavidBoike** [comment]
Thanks for the bug report!

So that I can understand clearly, can I ask:

1. If you don't use `AuditProcessedMessagesTo()`, no audit queue is created, right?
2. Given the configuration mismatch between specifying an audit queue on a send-only endpoint, I assume this is one of those "well that was a weird difference" situations and that this had no ill effect on the system, correct?

**Comment by saasen** [comment]
Sure.

1. I haven't actually tried that, but I would guess so?
2. I haven't seen that any messages has been sent to / processed on those endpoints. So yeah, I think you are right it's just a weird difference.

However, we also call `SendFailedMessagesTo()` on those endpoints. An error queue **is not** created for send-only endpoints. I would say it's inconsistent behaviour, but it doesn't really affect anything. I was just a little afraid if all our send-only endpoints now suddenly were fully blown processing endpoints.

**Comment by saasen** [comment]
Thanks a lot! I appreciate the fast fix! 👏
