### ISSUE TITLE
NSB0002: CancellationToken analyzer adds the cancellation token into the wrong place for fluent API calls

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#6753]
### Describe the bug

Originally raised by @SimonCropp 

#### Description

For fluent style invocations, the cancellation token analyzer finds the right method that misses the cancellation token parameter

![image](https://github.com/Particular/NServiceBus/assets/174258/960188e9-d497-41e4-9e0e-23d50b64667c)

but does add the parameter to the first method invocation instead of the one that actually accepts the cancellation token

![image](https://github.com/Particular/NServiceBus/assets/174258/35f3a3cf-c927-493f-95dc-da67f18de288)

#### Versions

All supported versions that contain the analyzer  

#### Workarounds

Manually fixing the analyzer code

**Comment by DavidBoike** [comment]
@danielmarbach fixed in https://github.com/Particular/NServiceBus/pull/6751 - will be released as part of NServiceBus 8.1.0.
