### ISSUE TITLE
Message serialization and deserialization fails when using SystemJsonSerializer and sending large message through DataBusProperty<T>

### ISSUE THREAD

**Issue by soujay** [Particular/NServiceBus#6804]
#### Description

As per the [supported serializer docs](https://docs.particular.net/nservicebus/serialization/#supported-serializers), NSB  8 supports the following serializers.
- System.Text.Json
- Newtonsoft
- XML

But when trying send large messages through "DataBusProperty<<T>>" using a Databus and when using the SystemJsonSerializer as the message serializer in the endpoint configuration, an unhandled exception is thrown 

>Unhandled exception. System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported. Path: $.LargePayload.Type.

#### Expected behavior

It should be possible to serialize/deserialize large messages that use Databus with a Databus Property using "SystemJsonSerializer" as their message serializers.

#### Actual behavior
An unhandled exception is thrown when using the SystemJsonSerializer as the message serializer in the endpoint configuration and trying to send in a large message through "DataBusProperty<<T>>" using a Databus

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        
- NServiceBus 8.*

### Steps to reproduce

This exception can be reproduced by downloading and running any of the DataBus Samples
- https://docs.particular.net/samples/databus/blob-storage-databus/
- https://docs.particular.net/samples/databus/blob-storage-databus-cleanup-function/
- https://docs.particular.net/samples/databus/custom-serializer/
- https://docs.particular.net/samples/databus/file-share-databus/

1. Download any of the above sample.
2. Follow the pre-requisites(if any)  described in the sample
3. Before running the sample, ensure that the endpoints use "SystemJsonSerializer" as their message serializer
 
` endpointConfiguration.UseSerialization<SystemJsonSerializer>();`

5. Build and run the sample
6. Send a large message and the following exception is seen
>Unhandled exception. System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported. Path: $.LargePayload.Type.

### Additional Information
 
- The issue is not seen if the endpoints use other message serializer like  xmlSerializer or does not use a DataBusProperty
- See the issue about plans to support ISerializable in System.Text.Json:  https://github.com/dotnet/runtime/issues/54940 

#### Possible solutions

Since System.Text.Json does not support ISerializable , the user needs to write a custom converter that basically does the conversion.
- Reference: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-7-0
- [Sample](https://docs.particular.net/samples/databus/databus-custom-serializer-converter/) that shows the workaround

**Comment by jpalac** [comment]
Will be shipped with Release 8.1.4

**Comment by jpalac** [comment]
[NServiceBus 8.1.4](https://github.com/Particular/NServiceBus/releases/tag/8.1.4) has been released
