### ISSUE TITLE
AssemblyNames containing a dot without file extensions cannot be excluded in the assembly scanner

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#6835]
#### Description

This is a regression. With the recent changes introduced in #6814 it is no longer possible to exclude an assembly name without an extension. This was previously supported and used by ServiceControl

#### Expected behavior

Support excluding assemblies without having to specify an extension

#### Versions

- 8.1.2
- 7.8.3
- 8.0.2

### Steps to reproduce

Use one of the affected versions and try to exclude an assembly without an extension. For example,

`.ExcludeAssemblies("MyCompany.MyAssembly")` instead of `.ExcludeAssemblies("MyCompany.MyAssembly.dll")`

**Comment by timbussmann** [comment]
> .ExcludeAssemblies("MyAssembly") instead of .ExcludeAssemblies("MyAssembly.dll")

@danielmarbach looking at #6834 Is the given example really valid? At first glance it looks like this can only happen if the excluded assembly also contains dots (e.g. `"My.Assembly"`)

**Comment by danielmarbach** [comment]
Yeah my bad I nees to update the text
