### ISSUE TITLE
Add processing times to OpenTelemetry metrics

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#6868]
### Describe the suggested improvement

The [NServiceBus OpenTelemetry integration](https://docs.particular.net/nservicebus/operations/opentelemetry) currently promotes the [following metrics](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/OpenTelemetry/Metrics/Meters.cs):
* nservicebus.messaging.successes: Total number of messages processed successfully by the endpoint
* nservicebus.messaging.fetches: Total number of messages fetched from the queue by the endpoint
* nservicebus.messaging.failures: Total number of messages processed unsuccessfully by the endpoint

The [NServiceBus.Metrics package](https://docs.particular.net/monitoring/metrics/) supports more metrics though, for example 
* [Critical Time](https://docs.particular.net/monitoring/metrics/definitions#metrics-captured-critical-time)
* [Processing Time](https://docs.particular.net/monitoring/metrics/definitions#metrics-captured-processing-time)
* [Queue Length](https://docs.particular.net/monitoring/metrics/definitions#metrics-captured-queue-length)

These metrics are currently not available when using the OpenTelemetry integration instead of the Metrics package. When using OpenTelemetry, it does only add noise and overhead to also rely on the NServiceBus.Metrics package for these additional metrics.

#### Describe the suggested solution

Add additional metrics to the built-in OpenTelemetry metrics, e.g. Critical time and processing time.

**Comment by cjoergensen** [comment]
Does the NServiceBus.Metrics package expose the metrics via OpenTelemetry by default, or does it require custom code?

**Comment by mauroservienti** [comment]
@cjoergensen, the Metrics package was designed before the advent of OTel. It requires custom code to capture and report those metrics to an OpenTelemetry collector. I'm not sure the data exposed by the Metrics package have all the needed information to plugin into the OTel activities model.

More details in [our documentation](https://docs.particular.net/monitoring/metrics/raw#reporting-metrics-data).

**Comment by bbrandt** [comment]
FYI, stay tuned!  Great things are on the way according to David Boike!

https://github.com/Particular/docs.particular.net/issues/6446#issuecomment-1934468629

**Comment by bbrandt** [comment]
Workaround to get these metrics in App Insights:
https://docs.particular.net/samples/open-telemetry/application-insights/

And Prometheus:
https://docs.particular.net/samples/open-telemetry/prometheus-grafana/

**Comment by SzymonPobiega** [comment]
The missing metrics have been implemented in https://github.com/Particular/NServiceBus/pull/7097 and https://github.com/Particular/NServiceBus/pull/7095. They will be released soon as part of 9.1
