### ISSUE TITLE
Should the exception related headers be represented by FaultsHeaderKeys?

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#6872]
#### Is your improvement related to a problem? Please describe.

Every failed message has the following headers.

```
FailedQ
NServiceBus.ExceptionInfo.ExceptionType
NServiceBus.ExceptionInfo.HelpLink
NServiceBus.ExceptionInfo.Message
NServiceBus.ExceptionInfo.Source
NServiceBus.ExceptionInfo.StackTrace
```

But `FailedQ` is the only header represented by `FaultsHeaderKeys`. Should the rest of the keys be added to `FaultsHeaderKeys`?

**Comment by danielmarbach** [comment]
@SeanFeldman is this what you had in mind? https://github.com/Particular/NServiceBus/pull/6876

Do you see any value in exposing `ExceptionInfoData` prefix publicly?

**Comment by SeanFeldman** [comment]
Exactly that, @danielmarbach.

> Do you see any value in exposing ExceptionInfoData prefix publicly?

Not for what I'm doing 🙂

**Comment by danielmarbach** [comment]
Addressed by https://github.com/Particular/NServiceBus/pull/6876. Closing
