### ISSUE TITLE
Reduce dependencies for net 6

### ISSUE THREAD

**Issue by thompson-tomo** [Particular/NServiceBus#7002]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
System.Text.Json can be provided via the framework ie net 6 as such conditions should be placed on it so that it is only included for net framework. Other dependencies can be optimised.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by awright18** [comment]
Thanks for your feedback, we will consider this in future releases.
