### ISSUE TITLE
Allow user to define the scope of a trace

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#7068]
#### Describe the requested feature

By default NServiceBus creates parent-child relationships between spans of each subsequent message in the conversation. When these conversations become too long, it may create problems on the tooling side of things.

To deal with that problem a new API is needed to opt-out of the parent-child relationship and only create a span-link.
        
#### Describe alternatives you've considered

An alternative would be to always rely on links and never create parent-child relationship. This alternative has been discarded because the available tools offer poor support for linked spans.

**Comment by lailabougria** [comment]
Done as part of https://github.com/Particular/NServiceBus/pull/7079, will be released as part of NServiceBus 9.1
