### ISSUE TITLE
Document the Learning Transport

### ISSUE THREAD

**Issue by dannyyy** [Particular/NServiceBus#7104]
#### Is your improvement related to a problem? Please describe.
Currently, the learning transport behaves like a black box. The documentation just mentions the obvious. There are four folders s with the name `.bodies`, `.committed`, ... I guess every developer which is able to use a file manager comes to the same conclusion.

For a commercially provided product, I expect another level of documentation.

#### Describe the suggested solution

Please explain, how the messages within the folders have to look like. How to manually produce new events for testing purposes, ...
        
#### Describe alternatives you've considered

Provide examples in your documentation or GitHub repository

**Comment by tmasternak** [comment]
Hi @dannyy,

Thank you for your feedback! I assume that what you mean by: 

> How to manually produce new events

refers to a scenario in which you want to write a piece of C# code (or use any other language) without any reference to NServiceBus that produces a message that can be consumed by an NServiceBus endpoint. In NServiceBus documentation this is referred to as "native integration" (e.g. [RabbitMQ native integration](https://docs.particular.net/transports/rabbitmq/native-integration)) and is documented for all transports that are supported in production.

As [mentioned in the documentation](https://docs.particular.net/transports/learning/) the Learning Transport (as well as the Learning Persistence) is not meant for production use and as a result, the documentation does not cover the native integration scenario.
 
Could you share more details on your testing approach and why it requires you to follow the native integration path?

**Comment by tmasternak** [comment]
Hi @dannyyy, I'll close this issue for now.
