### ISSUE TITLE
Release 8.2.4

### ISSUE THREAD

**Issue by Kielek** [Particular/NServiceBus#7191]
#### Is your feature related to a problem? Please describe.

In [OTel .NET Auto-Instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) we are executing some integration tests with NServiceBus.

We are in the middle of working on support for .NET9.
.NET9 brings extended NuGet Audit (it can be reproduced on older .NET versions by setting following properties:

```xml
  <PropertyGroup>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
  </PropertyGroup>
```

Referencing NServiceBus 8.*, including 8.2.3 leads at best to

```log
Warning As Error: Package 'System.Text.Json' 8.0.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4
```

#### Describe the requested feature

Release package from https://github.com/Particular/NServiceBus/commits/release-8.2/ branch. [It already contains transitive dependency to non-vulnerable version.](https://github.com/Particular/NServiceBus/pull/7174/files)

#### Describe alternatives you've considered

Workaround it o manually upgrade System.Text.JSon to 8.0.5. It is complicated when you are relay on multiple external components.

**Comment by poornimanayar** [comment]
Hi @Kielek ,

Many thanks for logging this issue. We are aware of the issue and are looking into it internally. 

Regards
Poornima

**Comment by Kielek** [comment]
@poornimanayar, do you have any updates here? ETA?

**Comment by poornimanayar** [comment]
Hi @Kielek ,

8.2.4 is now available in Nuget https://www.nuget.org/packages/NServiceBus/8.2.4

**Comment by Kielek** [comment]
Thank you!
