### ISSUE TITLE
Add support for auto tuning of the number of worker threads

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#748]
Given that we now can monitor throughput and change worker threads dynamically there is a possibility to auto-tune the number of threads. This takes the burden of the user who needs to do this manually to find the optimum number for each specific endpoint.

**Comment by johnsimons** [comment]
@SzymonPobiega with the changes you have done to the threading, what's your thoughts on this?

**Comment by SzymonPobiega** [comment]
Already implemented in [extending pipeline](https://github.com/Particular/NServiceBus/tree/extending_pipeline_to_transport) branch. Also, implemented (in a slightly different way) in upcoming NSB.SQL 2.1

**Comment by johnsimons** [comment]
That is what I thought @SzymonPobiega.
Closing as already implemented
