### ISSUE TITLE
Add support for clients to use their fully qualified hostname as their return address

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#750]
We should add a flag to use Dns.GetHostEntry(serverName).HostName instead of the Environment.MachineName. 

Depending on how we do this the check for a local input queue might need to be modified
https://github.com/NServiceBus/NServiceBus/blob/master/src/impl/unicast/queuing/NServiceBus.Unicast.Queuing.Msmq/MsmqMessageReceiver.cs#L28

**Comment by andreasohlund** [comment]
>can you point me to an example or provide an example of how to use that setting Andreas? I'll experiment with it.

@jdrat2000  Got confirmation from a user on the group that this workaround works - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/Brcd8MvFtB0/U5VO-RP4BgAJ

**Comment by danielmarbach** [comment]
@andreasohlund @jdrat2000 can we close this?
