### ISSUE TITLE
FileShareDataBus.Start implement cleanup

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#846]
Currently the databus does not implement cleanup logic for files which have a timetobereceived set. This could actually use NSB scheduling featuers to cleanup the files periodically.

**Comment by danielmarbach** [comment]
Since this was flagged as a bug, shouldn't we solve this?

**Comment by danielmarbach** [comment]
Flagged for CoreV6. This needs to be fixed

**Comment by distantcam** [comment]
Whether this is urgent or not (it was opened in 2012 and no one has fixed it since then) it is not critical to the release of v6. This could be fixed now before v6, or as part of v6.1, so I'm removing the Core v6 tag.

**Comment by danielmarbach** [comment]
@andreasohlund I think @distantcam made a good point. We could do this as part of 5.3 or any other patch release on top of 5.x. It doesn't have to be part of v6.

**Comment by andreasohlund** [comment]
:+1:

**Comment by ramonsmits** [comment]
There are more improvements regarding the databus: https://github.com/Particular/PlatformDevelopment/issues/539

Just purging blobs is not really a good idea from an endpoint perspective. Please read the ideas about a purging policy that can make decisions based on information from audit and error messages.

**Comment by danielmarbach** [comment]
We [explicitly state in the docs ](http://docs.particular.net/nservicebus/messaging/databus/file-share#cleanup-strategy) that the file share databus does not cleanup files. Marked as a feature. Closing this. Related https://github.com/Particular/PlatformDevelopment/issues/413
