### ISSUE TITLE
Have a non generic Saga.RequestTimeout with no state

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#881]
Take this example
https://github.com/NServiceBus/NServiceBus/blob/develop/IntegrationTests/TimeoutManager/MyServer/Saga/SimpleSaga.cs#L15

If i dont have any state for the call back it looks like this

     public class SimpleSaga:Saga<SimpleSagaData>,
        IAmStartedByMessages<StartSagaMessage>,
        IHandleTimeouts<MyTimeOutState>
    {
        public void Handle(StartSagaMessage message)
        {
            Data.OrderId = message.OrderId;
            RequestTimeout<int>(TimeSpan.FromSeconds(10));
        }

        public override void ConfigureHowToFindSaga()
        {
            ConfigureMapping<StartSagaMessage>(s => s.OrderId, m => m.OrderId);
        }

        void LogMessage(string message)
        {
            Console.WriteLine(string.Format("{0} - {1} - SagaId:{2}", DateTime.Now.ToLongTimeString(),message,Data.Id));
        }

        public void Timeout(int fake)
        {
            LogMessage("Marking the saga as complete, be aware that this will remove the document from the storage (RavenDB)");
            MarkAsComplete();
        }
			}

Note that i need a fake type to work around the missing non-generic version

**Comment by danielmarbach** [comment]
@SimonCropp There is a workaround provided by @chrisbednarski in the comment here

https://github.com/Particular/NServiceBus/issues/881#issuecomment-32434742

I'm closing this.

@udidahan raised a different issue for [your proposal](https://github.com/Particular/NServiceBus/issues/3454)
