### ISSUE TITLE
IAuthorizeSubscriptions not supported by broker implementations (RabbitMQ and ActiveMQ)

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#987]
Because the brokers do not need to send a Subscribe/Unsubscribe message to the publisher,  `IAuthorizeSubscriptions` is never invoked for these transports!

#### The first task that needs to be done is:
* [x] Work out if we still need `IAuthorizeSubscriptions`, does anyone actually use this?

If the interface is required then
#### Brokers implementation:
* Do we make the authorisation part of the broker itself?
* If the authorisation is on the broker, do we rename the interface to be transport specific?
* Do the authorisation in [UnicastBus](https://github.com/NServiceBus/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/UnicastBus.cs#L422) instead of [Mutator](https://github.com/NServiceBus/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/Subscriptions/MessageDrivenSubscriptionManager.cs)
* Or do the authorisation on each `IManageSubscriptions` impl

**Comment by johnsimons** [comment]
Question asked in the forum, https://groups.google.com/d/msg/particularsoftware/PSaHw0ROalQ/0CtpvEY_m1sJ

**Comment by johnsimons** [comment]
So it has been a week since I polled the forum and only Adam came back to me regarding this functionality, but even Adam says that they will keep on using their own external provisioning.

So @Particular/engineers are we all in agreement that we can obsolete `IAuthorizeSubscriptions` ?

**Comment by SimonCropp** [comment]
I dont think we should remove it. Even if no one responded to the group, it meets a legitimate security requirement that should have a simple answer and an explicit API.

**Comment by SimonCropp** [comment]
I would compare this to the encryption feature. even if everyone said "no we do encryption in a custom way or on the transport" I would still say we need this feature in the core.

**Comment by johnsimons** [comment]
@andreasohlund can you please make a decision on this one ?

**Comment by andreasohlund** [comment]
Since we need to rethink this in the light of broker transports anyway I'd say we:

1. Obsolete the current feature since its misleading (doesn't work for all transports), guiding users to use a behavior/custom substorage implementation instead if they happen to be using it (there is always one user :) 
2. Raise a requirement to come up with a "vNext" plan of attack for this

Thoughts?

**Comment by johnsimons** [comment]
What timeline ? v6 ?

**Comment by andreasohlund** [comment]
I see no reason to wait. Let's do it in v6

**Comment by johnsimons** [comment]
Another issue was raised based on the outcome, see #2725
